### ISSUE TITLE
[FEA] UDF Support

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to support scala, java and python UDFs

**Describe the solution you'd like**
Something that can transpile simple scala, java and python byte code into either cuda kernels or catalyst expressions.

**Describe alternatives you've considered**
There really are no other options if we want to be fast.

**Comment by sameerz** [comment]
This is being addressed in other issues.
