### ISSUE TITLE
[FEA] Explore better ways to support aggregates

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10]
**Is your feature request related to a problem? Please describe.**
Spark currently goes out of its way to try and produce the same answer each time an aggregate with floating point values happens. floating point addition is neither associative nor commutative.  By default we turn it off and require you to enable it with `spark.rapids.sql.variableFloatAgg.enabled`.  This is very inconvenient and really only shows up as a problem if someone is doing the stupid thing of joining on a floating point value produced from two aggregate operations.

**Describe the solution you'd like**
It would be great if the plugin could detect that this is happening and disable the has aggregate only when needed, but there are some cases with how spark works with the physical plan that we cannot always tell how this value will be consumed down stream.  We might need to work with the spark community to expose more information in the plan.

**Comment by sameerz** [comment]
Due to variations in floating point reductions it is unlikely we can match CPU and GPU floating point results.
