### ISSUE TITLE
[BUG] test_str_to_map_expr_random_delimiters with DATAGEN_SEED=1702166057 hangs

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10012]
**Describe the bug**
I was able to reproduce this locally on Spark 3.3.0

```
SPARK_HOME=spark_3.3.0/ TEST_PARALLEL=0 PYSP_TEST_spark_rapids_sql_explain=ALL DATAGEN_SEED=1702166057 TZ=UTC ./run_pyspark_from_build.sh --test_oom_injection_mode=always -k 'test_str_to_map_expr_random_delimiters' -s
```

and git version ff190124611e73fcf63a2c2948a9d510ae2f6b3b

It appears to hang in python. No queries were submitted to Spark, from what I could see.

When I tried to use gdb on it I got some great stack traces, but they were all in C, in what appeared to be creating error messages, and I ma not enough of a python expert to really dig into what is happening here.

**Comment by jlowe** [comment]
The test hangs because the test has a bug in it:
```python
    while pair_delim == keyval_delim:
        (pair_delim, keyval_delim) = with_cpu_session(
            lambda spark: gen_scalars_for_sql(delim_gen, 2, force_no_nulls=True))
```
The data generation will reset the generator to the beginning each time, so if it happened to generate two identical scalars it will infinitely loop.
