### ISSUE TITLE
[FEA] Add tests for time zones with DST

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10031]
**Is your feature request related to a problem? Please describe.**
Our current time zone tests that run nightly switch between Iran and Asia/Shanghai. But this does not cover the case for timezones we don't support yet where there is daylight savings time. We don't know that we are falling back to the CPU correctly in those cases.

**Comment by mattahrens** [comment]
Dup of https://github.com/NVIDIA/spark-rapids/pull/9999
