### ISSUE TITLE
Add integration test tag for precommit time zone tests

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10041]
From https://github.com/NVIDIA/spark-rapids/pull/9999#discussion_r1424538347_

It would be nice to have the pre-merge build run tests in different time zones that are tagged in the tests themselves instead of having a hard coded list in the pre-merge script.

**Comment by sperlingxx** [comment]
Hi @revans2, currently the time zone test pieces of pre-merge tests look like:
```bash
    source "$(dirname "$0")"/test-timezones.sh
    for tz in "${time_zones_test_cases[@]}"
    do
        TZ=$tz ./integration_tests/run_pyspark_from_build.sh -m tz_sensitive_test
    done
```
It has the specialized test tag `tz_sensitive_test`. And selected timezones are managed in `test-timezones.sh`.

Does it look good to you?

**Comment by revans2** [comment]
Yes it looks great.
