### ISSUE TITLE
[BUG] Spark3.1.0 changed BasicWriteTaskStats breaks BasicColumnarWriteTaskStatsTracker

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1006]
Looks like Spark 3.1.0 changed the api for BasicWriteTaskStats here https://github.com/apache/spark/commit/b38f3a5557b45503e0f8d67bc77c5d390a67a42f 

This breaks our BasicColumnarWriteTaskStatsTracker

Cause: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.BasicWriteTaskStats.<init>(IIJJ)V
13:34:22    at org.apache.spark.sql.rapids.BasicColumnarWriteTaskStatsTracker.getFinalStats(BasicColumnarWriteStatsTracker.scala:107)
13:34:22    at org.apache.spark.sql.rapids.GpuFileFormatDataWriter.$anonfun$commit$1(GpuFileFormatDataWriter.scala:82)
13:34:22    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
13:34:22    at scala.collection.immutable.List.foreach(List.scala:392)
13:34:22    at scala.collection.TraversableLike.map(TraversableLike.scala:237)
13:34:22    at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
13:34:22    at scala.collection.immutable.List.map(List.scala:298)
13:34:22    at org.apache.spark.sql.rapids.GpuFileFormatDataWriter.commit(GpuFileFormatDataWriter.scala:82)
13:34:22    at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$executeTask$1(GpuFileFormatWriter.scala:298)
13:34:22    at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1460)
13:34:22    ...

**Comment by jlowe** [comment]
Fixed by #1009 when #1012 was merged.
