### ISSUE TITLE
[FEA] Implement GPU kernel for SubstringIndex

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#10072]
**Is your feature request related to a problem? Please describe.**
Our current implementation of `SubstringIndex` uses complex regular expressions, and we have seen that performance is not always good relative to CPU.

**Describe the solution you'd like**
We should evaluate whether a custom GPU kernel would perform better.

**Describe alternatives you've considered**

**Additional context**

**Comment by thirtiseven** [comment]
closed by https://github.com/NVIDIA/spark-rapids/pull/11149
