### ISSUE TITLE
[FEA] Memory optimizations for collect_set with unbounded proceeding to unbounded following

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10114]
**Is your feature request related to a problem? Please describe.**
We have a customer that is doing a `collect_set` for rows between unbounded proceeding and unbounded following. This ends up using the regular `GpuWindowExec` because we don't have a double pass code in place to fix it. I'm not sure we even want to try and do it as normal double pass operation as N^2 memory usage even for a 1 GiB batch is likely very high.

I filed https://github.com/NVIDIA/spark-rapids/issues/10113 to come up with long term/more generic solutions, but this is here to see if we can come up with something that is specific to this one use case sooner than later.

I think the only "quick" fix is to do a groupby instead of a window operation followed by an explode, and the explode needs to take into account the size of the output data and possibly split up the input to make it work. This is not without risks and I think we would want to make a new `GroupByDoublePassWindowExec` class that would not rely on the existing `WindowExec` or `WindowIterator` code. We could also put it under a config so we could turn it off if someone runs into problems.

**Comment by kuhushukla** [comment]
Sounds neat. Would the explode issue still hit OOM scenarios if one row is large enough? Perhaps this change along with https://github.com/NVIDIA/spark-rapids/issues/10088 will do the trick?

**Comment by revans2** [comment]
Yes, we would have to do something similar to #10088 to avoid issues there. But it would not likely be exactly the same.

**Comment by revans2** [comment]
Here is an example query using NDS scale factor 200 decimal data set.

```
store_sales.selectExpr("collect_set(ss_store_sk) over (PARTITION BY ss_sold_date_sk ORDER BY ss_sold_time_sk ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as c").orderBy("ss_sold_date_sk", "ss_sold_time_sk").show()
```

It crashes even on a 48 GiB GPU fairly quickly.

**Comment by mythrocks** [comment]
For `UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING`, on the `libcudf` side, it might be possible to do this via a segmented reduce, and then expand the group results to produce the final column.
On the plugin side, we'd still need to batch the input columns based on the group cardinality.

**Comment by revans2** [comment]
I think the plan is to do it outside of CUDF because we want to have more control over the memory usage when doing the expand.

**Comment by revans2** [comment]
@mythrocks 

The idea is that for an unbounded to unbounded aggregation we would take the input batch. Make it spillable and save it to the side. Then using that input batch we would do a sort based group by aggregation on it along with a count (essentially a segmented reduce). We would then take that result and figure out how much of the aggregation is fully done and how much is only partially done. We would then slice the aggregation results based off of what is fully done and what is only partially done. The partially done results would be saved to be combined with the next batch of input and the fully done results could be used to output whatever we could for the current batches of input. To output results from a fully done aggregation would involve slicing the input batch based off of what is fully done and then expanding the window results using the count. But we would want to be very careful while doing this that we don't go over the target batch size unless we have to.

I don't think we want to try and do this in CUDF for a few reasons. First CUDF in the past has not wanted these types of optimizations in operators. Instead they typically what the optimizations to happen at a higher level. And second I think we have more information about what we want to do, like with the target batch size.

I think we can split this work up into a few different parts.

1) refactor the window exec code so it is not all in a single giant file. (https://github.com/NVIDIA/spark-rapids/pull/10146)
2) Add in a GpuUnboundedToUnboundedAggWindowExec. This would just be the framework for it and not be enabled yet. This might also be skipped and just added in at the end after we do the other refactoring as needed.
3) Provide a way to take an unbounded to unbounded window expression and implement it in terms of an group by aggregation. I think it would be great if we could find a way to reuse as much of the existing aggregation exec code as we can to do this. The important thing is that this should be a sorted group by aggregation along with count.
4) Have code to take an aggregation result along with an input batch and slice them between the parts that we know are fully done and the parts that are not.
5) Provide a way to take an input batch along with the aggregation results (including the count after they have been sliced) and expand(Table.repeat) the results so that we can line them up with the original input rows while still honoring the target batch size as much as possible. `GpuReplicateRows` does something similar, so it might be good to try and make as much of that code common as we can.
6) turn it all on and add integration tests. This would likely involve updating the GpuWindowExecMeta rules to use the new one where we can.


Just be aware that we really only have to do this for `collect_set`, but hopefully we can have others start to work too without much effort at all. But they should probably be follow on issues.
