### ISSUE TITLE
[BUG] Query fails with ClassCastException when enabling dynamic partition pruning

### ISSUE THREAD

**Issue by chenrui17** [NVIDIA/spark-rapids#1011]
**my conf is :**

spark.sql.optimizer.dynamicPartitionPruning.enabled true
spark.sql.optimizer.dynamicPartitionPruning.reuseBroadcastOnly false

spark.sql.adaptive.enabled true
spark.sql.adaptive.coalescePartitions.enabled true

**my bug info is :**
[dpp&ae_bug_info.txt](https://github.com/NVIDIA/spark-rapids/files/5429621/dpp.ae_bug_info.txt)

what i want to say is that : in cpu , if you set this conf , it will not use dpp, but in gpu ,if i set this conf ,it will occur error as above. so I don't know if this is a bug in rapids.

**Comment by jlowe** [comment]
Pasting the relevant snippet of the error here for easier browsing:
```
20/10/23 17:54:04 ERROR sql.rapids.GpuFileFormatWriter [pool-2-thread-2]: Aborting job d7683e9e-0fb4-4a66-a4a3-efdf765a2083.
java.lang.ClassCastException: org.apache.spark.sql.catalyst.plans.logical.Aggregate cannot be cast to org.apache.spark.sql.execution.SparkPlan
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at org.apache.spark.sql.execution.SparkPlanInfo$.fromSparkPlan(SparkPlanInfo.scala:73)
	at org.apache.spark.sql.execution.SparkPlanInfo$.$anonfun$fromSparkPlan$3(SparkPlanInfo.scala:73)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[...]
```

> if i set this conf ,it will occur error as above. so I don't know if this is a bug in rapids.

This is definitely a bug.  Queries should not crash with ClassCastException.

@chenrui17 does this happen on every query or for a specific query?  The stacktrace implies this occurred during a particular group by operation, so I'm thinking it may be specific to only some queries.  If possible, it would be great to have full steps to reproduce this.

**Comment by chenrui17** [comment]
this is happend when DPP is triggered , and i run the TPC-DS query-7 and query-39a and query-39b ,and it's all triggered the DPP.
my conf is :
#scheduler
spark.scheduler.listenerbus.eventqueue.capacity 800000
spark.scheduler.mode FIFO
spark.locality.wait.process 1ms
spark.locality.wait.node 1ms
#spark.locality.wait.rack 1ms
#wait for cache locality, only for aep worker

#network i/o
spark.rpc.askTimeout 240
spark.rpc.lookupTimeout 240
spark.rpc.message.maxSize 512
spark.rpc.netty.dispatcher.numThreads 128
spark.rpc.numRetries 24
spark.rpc.retry.wait 10s
spark.network.timeout 240s
spark.storage.blockManagerSlaveTimeoutMs 240000

#input & output
#spark.sql.splitCombiner.enabled true
#spark.sql.listChildrenFileStatus.enabled true
spark.sql.files.maxPartitionBytes 2147483648

#spark.io.compression.codec org.apache.spark.io.LZ4CompressionCodec
spark.sql.legacy.parser.havingWithoutGroupByAsWhere true
spark.sql.sources.partitionOverwriteMode DYNAMIC
#spark.sql.sources.parallelPartitionDiscovery.threshold 4
hive.exec.max.dynamic.partitions 2500
spark.resultGetter.threads 20

#hive metastore
spark.sql.catalogImplementation hive
spark.sql.hive.convertMetastoreOrc false
spark.sql.hive.schema.enable true
spark.sql.hive.filesourcePartitionFileCacheSize 2147483648

# shuffle
# spark.memory.fraction    0.75
# spark.reducer.maxSizeInFlight	96m
# spark.shuffle.sort.bypassMergeThreshold	3000
# spark.shuffle.mapOutput.minSizeForBroadcast 5m
spark.shuffle.spill.initialMemoryThreshold 104857600L
spark.shuffle.file.buffer 1m
# spark.reducer.maxSizeInFlight 32m
spark.sql.shuffle.partitions 520
spark.sql.broadcastTimeout 1500

# scheduler
spark.scheduler.mode FAIR
spark.speculation.quantile 0.9
spark.speculation true
spark.speculation.multiplier 3
spark.speculation.interval 1s

# dpp
spark.sql.optimizer.dynamicPartitionPruning.enabled true
# default 0.5
#spark.sql.optimizer.dynamicPartitionPruning.fallbackFilterRatio 0.1
spark.sql.optimizer.dynamicPartitionPruning.reuseBroadcastOnly false
# ae
spark.sql.adaptive.enabled true
spark.sql.adaptive.coalescePartitions.enabled true
#spark.sql.adaptive.coalescePartitions.initialPartitionNum 520
#spark.sql.adaptive.coalescePartitions.minPartitionNum 520
#spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes 1048576
#spark.sql.adaptive.skewJoin.skewedPartitionFactor 5
#spark.sql.adaptive.advisoryPartitionSizeInBytes 67108864
#spark.sql.adaptive.shuffle.targetPostShuffleInputSize 67108864
#spark.sql.adaptive.minNumPostShufflePartitions
#spark.sql.adaptive.maxNumPostShufflePartitions

# cbo
spark.sql.cbo.enabled false
#spark.sql.cbo.planStats.enabled true
#spark.sql.cbo.joinReorder.enabled true
#spark.sql.cbo.joinReorder.dp.star.filter true
#spark.sql.cbo.starSchemaDetection true
#spark.sql.autoBroadcastJoinThreshold 500MB

#spark.sql.sortMergeJoinExec.buffer.in.memory.threshold 50000000
#spark.sql.execution.reuseSubquery false
#spark.sql.adaptive.skewJoin.extraShuffle.enabled true

# extensions
#spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
#spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension,org.apache.spark.sql.OapExtensions
#spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog

# gpu related
spark.plugins com.nvidia.spark.SQLPlugin
spark.rapids.sql.concurrentGpuTasks 4
spark.rapids.memory.pinnedPool.size 48G
spark.rapids.sql.batchSizeBytes 536870912
spark.rapids.sql.variableFloatAgg.enabled true
spark.sql.optimizer.inSetConversionThreshold 1000
spark.rapids.memory.gpu.pooling.enabled true
spark.rapids.sql.exec.BroadcastNestedLoopJoinExec true
spark.rapids.sql.castFloatToString.enabled true
spark.rapids.sql.expression.Upper true
spark.executor.resource.gpu.amount 1
#spark.rapids.memory.gpu.debug STDERR
spark.rapids.sql.explain true
spark.rapids.sql.hasNans false
spark.task.resource.gpu.amount 0.1249
#spark.rapids.memory.host.spillStorageSize 17179869184
spark.executor.resource.gpu.discoveryScript /home/work/chenrui17/getGpusResources.sh
# double T4
spark.resources.discoveryPlugin com.nvidia.spark.ExclusiveModeGpuDiscoveryPlugin

**Comment by andygrove** [comment]
Hi @chenrui17 I am trying to reproduce this now. What scale factor was the TPC-DS dataset that you were running against when you saw this error?

**Comment by chenrui17** [comment]
> Hi @chenrui17 I am trying to reproduce this now. What scale factor was the TPC-DS dataset that you were running against when you saw this error?

sf=10000，but i think sf is nothing to do with this problem . so you can try sf=100 or 1000 ?

**Comment by andygrove** [comment]
@chenrui17 I tried running q7, q39a, and q39b both with the spark-sql-perf version of the benchmark and with the version that we have in this repo (writing to parquet in both cases) and they both ran without error against SF=100 data set that I generated using spark-sql-perf.

Could you provide some more information:

- Which Spark version are you using? (I used Spark 3.0.1)
- Which plugin version are you using? (I used branch-0.3 as of yesterday)
- Can you provide instructions for running the benchmark to reproduce the issue?

**Comment by chenrui17** [comment]
sorry, this error is caused by my own code in spark about AQE,  so I close it .
