### ISSUE TITLE
Add tests that use Spark's --packages to fetch the plugin

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#10160]
Relates to #10051.  We should add at least one test that uses Spark's `--packages` feature to fetch the RAPIDS Accelerator from Maven Central to verify that our artifact's Maven dependencies are correct and that the plugin works properly when launched this way with Spark.

**Comment by jlowe** [comment]
That test will run with --packages, but it won't pull the RAPIDS Accelerator that way.  It's only pulling in the Spark Avro jar via --packages in that setup.

**Comment by gerashegalov** [comment]
> That test will run with --packages, but it won't pull the RAPIDS Accelerator that way. It's only pulling in the Spark Avro jar via --packages in that setup.

you are right, forgot about it. 

I use it in my notebooks on a regular basis   
https://github.com/gerashegalov/rapids-shell/blob/4790ef03bcadefe5a55b695c199a59474dd8d9fa/src/jupyter/template-findspark.ipynb
```
findspark.add_packages(f"com.nvidia:rapids-4-spark_2.12:{rapids_version}")
```
There is a limitation in Spark that it currently does not support classifiers https://issues.apache.org/jira/browse/SPARK-20075

It only works because our default artifact is a cuda11 jar.

```bash
$ ~/dist/spark-3.5.0-bin-hadoop3/bin/pyspark --packages com.nvidia:rapids-4-spark_2.12:23.12.1:jar:cuda11

:: loading settings :: url = jar:file:/home/user/dist/spark-3.5.0-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Provided Maven Coordinates must be in the form 'groupId:artifactId:version'. The coordinate provided is: com.nvidia:rapids-4-spark_2.12:23.12.1:jar:cuda11
```

**Comment by GaryShen2008** [comment]
Does this issue require to use --packages to run our integration test with a released version (from maven central)? Or can we use an example ELT like some in spark-rapids-examples so that it can run quickly?

**Comment by jlowe** [comment]
My preference would be to have a test that regularly runs Spark using --packages to pull in the RAPIDS Accelerator from a remote repository.  Just before release, we would run this test on the staged artifact in Maven Central.  Other times we would run against the snapshot artifact published to an internal repository.  We can use the `--repositories` option to spark-submit to specify alternate repositories to use.

**Comment by GaryShen2008** [comment]
Sure, we can run with --packages for both sonatype staging and our internal repository.
My question is if we just want to verify the --packages works to run Rapids Accelerator, a simple ETL job should be enough. Is there any concern that we should run the IT pipeline which may spend a long time?

**Comment by jlowe** [comment]
I don't think we need to do a long test run.  This is more about smoke-testing the --packages loading and verifying we can come up and load the plugin and a few operator classes.  @gerashegalov any more testing that you think is warranted for this setup?

**Comment by gerashegalov** [comment]
+1 for a simple smoke test similar to `SPARK_SHELL_SMOKE_TEST`.

I also remembered another limitation of `--packages` which is the same for `--jars`: until   https://github.com/apache/spark/pull/43627 this test will not work with `RapidsShuffleManager` for standalone / local-cluster modes

**Comment by GaryShen2008** [comment]
ok, seems we can use the similar way as SPARK_SHELL_SMOKE_TEST to run a spark-shell with --packages with some simple code. If there's any different code required here, let's comment in the PR.
Assign to @NvTimLiu .

**Comment by NvTimLiu** [comment]
Working on the issue

**Comment by NvTimLiu** [comment]
We'll verify there's NO dependency issues for rapids plugin from Maven Central, depends on the issue fixing dependency https://github.com/NVIDIA/spark-rapids/pull/10201

I'll enable `--packages` nightly test after this PR get merged
