### ISSUE TITLE
[BUG] `test_cast_timestamp_to_date` fails with `TZ=Asia/Hebron`

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#10170]
**Describe the bug**

```
FAILED ../../src/main/python/cast_test.py::test_cast_timestamp_to_date[DATAGEN_SEED_OVERRIDE=1704816489] - pyspark.sql.utils.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.ProjectExec
```

**Steps/Code to reproduce bug**

```
export TZ=Asia/Hebron
./integration_tests/run_pyspark_from_build.sh -k test_cast_timestamp_to_date
```

**Expected behavior**

**Environment details (please complete the following information)**
CI and local workstation. Spark 3.1.1

**Additional context**

**Comment by NVnavkumar** [comment]
This timezone actually uses DST, so it should actually be skipped in this scenario, will investigate.

**Comment by NVnavkumar** [comment]
I see the issue, will post a PR in a bit.
