### ISSUE TITLE
[FEA] Log the shuffle manager class when shuffle manager is misconfigured

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#10172]
**Is your feature request related to a problem? Please describe.**

Instead of just reporting "Cannot initialize ..."

https://github.com/NVIDIA/spark-rapids/blob/47047a9c71e0bee6f235c9b3d21523e006f227c2/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuShuffleEnv.scala#L106-L113

1. The code should log the "wrong" shuffle manager instance's class
2. For the case it is a classloader problem, also output the corresponding classloader of 1

**Comment by zpuller** [comment]
I am planning to work on this.
