### ISSUE TITLE
[DOC] update the tuning guide

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#10188]
Since we removed `spark.rapids.memory.host.pageablePool.size` in v2310, so `spark.rapids.memory.host.spillStorageSize` is no longer the combined size of `spark.rapids.memory.pinnedPool.size` and `spark.rapids.memory.host.pageablePool.size` memory pools in [tuning guide](https://docs.nvidia.com/spark-rapids/user-guide/latest/tuning-guide.html).

**Comment by viadea** [comment]
This is addressed by MR-40 by @nvliyuan . Next time the doc sync should fix this.
