### ISSUE TITLE
[AUDIT][SPARK-45524] Initial support for Python data source read API

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#10199]
https://github.com/apache/spark/commit/7ef96ee5b88 added Python Data Source in Spark 4.0.

We need to figure out how to support it

**Comment by revans2** [comment]
@HaoYang670 is there a customer that needs this? We generally don't add new features in Spark from an audit until someone wants them.

**Comment by HaoYang670** [comment]
> is there a customer that needs this?

I haven't heard any requirement from customers on this. 

> We generally don't add new features in Spark from an audit until someone wants them.

Thank you for the clarification!
