### ISSUE TITLE
[BUG] Bug in Spark 3.3.3 TableOutputResolver.scala?

### ISSUE THREAD

**Issue by 19021999** [NVIDIA/spark-rapids#10192]
I have recently switched to Spark 3.3.3 from 3.2.1 and encountered an error while using append() in a dataframe.

`dataframe.writeTo(<tableName>).append();`

With new spark I got following error:

```
> Cannot write incompatible data to table <tableName>:
> Cannot write nullable values to non-null column : core_A
> Cannot write nullable values to non-null column : core_B
> Cannot write nullable values to non-null column : core_C
> Cannot write nullable values to non-null column : core_D
> Cannot write nullable values to non-null column : core_E
```

My columnA's schema looks like this:

`{
      "id" : 11,
      "name" : "columnA",
      "required" : false,
      "type" : {
        "type" : "list",
        "element-id" : 25,
        "element" : {
          "type" : "struct",
          "fields" : [ {
            "id" : 26,
            "name" : "core_A",
            "required" : true,
            "type" : "string",
            "doc" : ""
          }, {
            "id" : 27,
            "name" : "core_B",
            "required" : true,
            "type" : "string",
            "doc" : ""
          }, {
            "id" : 28,
            "name" : "core_C",
            "required" : true,
            "type" : "string",
            "doc" : ""
          }, {
            "id" : 29,
            "name" : "core_D",
            "required" : false,
            "type" : "string",
            "doc" : ""
          }, {
            "id" : 30,
            "name" : "core_E",
            "required" : true,
            "type" : "string",
            "doc" : ""
          } ]
        },
        "element-required" : false
      }`

When I executed append, it went to [TableOutputResolver.scala](https://github.com/apache/spark/blob/branch-3.3/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/TableOutputResolver.scala) to check fields nullability. But Since my columnA can be null, I passed all null values. AND it failed in this class while resolving output columns. It is expecting me to pass the non-null values and as per the schema, but since I made this column nullable why is it asking me to force the value?

In Spark 3.2.1, this never gave me an error and used to work properly. There were less checks for complex fields in older version. This was the implementation of Old [TableOutputResolver.scala](https://github.com/apache/spark/blob/branch-3.2/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/TableOutputResolver.scala)

Need clarification and the solution to this problem. Is my attribute definition wrong? Is this definition not allowed?

I am trying to find a solution, maybe an if check I can add to this class and patch this class while the fix comes from Spark officially. 
package org.apache.spark.sql.catalyst.analysis

**Comment by abellina** [comment]
@19021999 this looks like a question that is better suited for the spark mailing list. spark-rapids is a GPU plugin for Spark, but we are not the maintainers of Apache Spark and this question is not related to the GPU operations we accelerate. Here is the community page from Apache Spark, https://spark.apache.org/community.html. An email to user@spark.apache.org is probably the right approach here.
