### ISSUE TITLE
[BUG] GetJsonObject fails at spark unit test $.store.basket[0][*].b

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10217]
**Describe the bug**
In the spark unit test for GetJsonObject with a path of `$.store.basket[0][*].b` and data of
```
  val json =
    """
      |{"store":{"fruit":[{"weight":8,"type":"apple"},{"weight":9,"type":"pear"}],
      |"basket":[[1,2,{"b":"y","a":"x"}],[3,4],[5,6]],"book":[{"author":"Nigel Rees",
      |"title":"Sayings of the Century","category":"reference","price":8.95},
      |{"author":"Herman Melville","title":"Moby Dick","category":"fiction","price":8.99,
      |"isbn":"0-553-21311-3"},{"author":"J. R. R. Tolkien","title":"The Lord of the Rings",
      |"category":"fiction","reader":[{"age":25,"name":"bob"},{"age":26,"name":"jack"}],
      |"price":22.99,"isbn":"0-395-19395-8"}],"bicycle":{"price":19.95,"color":"red"}},
      |"email":"amy@only_for_json_udf_test.net","owner":"amy","zip code":"94025",
      |"fb:testid":"1234"}
      |""".stripMargin
```

we return null, meaning it didn't match anything, but the CPU say it matches `["y"]`. https://jsonpath.com/ also produces the same answer as the CPU.

**Comment by thirtiseven** [comment]
A minimal repro: `{"a":[{"b":"c"},2]}` and `$.a[*].b` will return `["c"]` on cpu and jsonpath.com, but `null` on gpu.

This is related to the `[*]` and I think it's a cudf bug. Will add fallback for paths containing `[*]` first, which is also a requirement from #10216

**Comment by res-life** [comment]
Will be fixed by: https://github.com/NVIDIA/spark-rapids-jni/pull/1868
