### ISSUE TITLE
[BUG] GetJsonObject does not normalize non-string output

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10218]
**Describe the bug**
GetJsonObject on the CPU will first parse the JSON, and then when it goes to output the result it will convert the parsed data back to a JSON string. This results in the new string being normalized. We do not do any of this. Instead we just copy the character range back out. The following bugs can show up because of this.

1. Unnecessary white space is removed

` { "a" : "A" } ` becomes `{"a":"A"}` on the CPU, but `{ "a" : "A" }` on the GPU

2. Quotes are normalized

`{'a':'A"'}` becomes `{"a":"A\""}` on the CPU, but stays as `{'a':'A"'}` on the GPU

3. Numbers are normalized

In the simplest case Spark strips unneeded trailing zeros for floating point numbers.
`[100.0,200.000,351.980]` on the CPU becomes `[100.0,200.0,351.98]`, but on the GPU it is unchanged

For larger floating point numbers it can be converted to scientific notation, or have the notation normalized.
`[12345678900000000000.0]` becomes `[1.23456789E19]` on the CPU, but is unchanged on the GPU.
`[1E308]` becomes `[1.0E308]` on the CPU.

But for very large/small float numbers that would not fit in a double, they are turned into "Infinity"/"-Infinity"
`[1.0E309,-1E309,1E5000]` becomes `["Infinity","-Infinity","Infinity"]`

But integer like numbers are not modified `[12345678900000000000]` just stays the same, even for numbers that are very, very large. i.e. `"1" + ("0" * 400)`

4. Unneeded escapes are removed

`{"a":"B\'"}` becomes `{"a":"B'"}`. Escaping the ' character is not needed here.

That said we don't need to worry about normalizing nulls, as they are always `null` and nothing else is allowed, or booleans because `true` and `false` are the only ones supported.

**Comment by GaryShen2008** [comment]
Hi @SurajAralihalli, as I confirmed with Chong, assign this issue to you.

**Comment by res-life** [comment]
This [commit](https://github.com/NVIDIA/spark-rapids-jni/pull/1868/commits/e097a25a62fa6df84967353fb17b645861535180) will solve items1, item2, item4.
For item3: Numbers are normalized
We need to fix

**Comment by thirtiseven** [comment]
For floating point numbers I think the rule is the same as double to string in java, if so we can reuse `ftos_converter` in jni to have an almost bit to bit match with spark.
