### ISSUE TITLE
[BUG] DBR builds fails when installing Maven

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#10224]
**Describe the bug**

calling `./jenkins/databricks/build.sh`
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/g/guice/libguice-java_4.2.1-1ubuntu0.1_all.deb  404  Not Found [IP: 91.189.91.82 80]
```
**Steps/Code to reproduce bug**

Minimum repro
```
sudo apt install maven
```

We can download from Maven from https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/

**Comment by tgravescs** [comment]
Note, I see this fail on Databricks 12.2 but not 13.3
