### ISSUE TITLE
[FEA] Disable Spark UI for integration tests

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10227]
**Is your feature request related to a problem? Please describe.**
I recently had a CI job fail because the UI could not bind to the desired port. We don't need a UI when we run the integration tests, especially in CI. It is also a potential security problem if the environment the tests are running in are not set up properly.  We should probably just set spark.ui.enabled to false for our integration test runs by default. Especially if we know that they are running in local mode.

**Comment by abellina** [comment]
I think the standalone cluster we run for the shuffle tests should also take this config change.

**Comment by GaryShen2008** [comment]
ok, I think we need to config spark.ui.enabled=false.
