### ISSUE TITLE
Add monitoring for GH action deprecations

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#10277]
I noticed by accident that there are numerous deprecation warnings on our GH workflows

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v3, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

On the one hand we need to fix them but we also could benefit from some automation surfacing these warnings

**Comment by YanxuanLiu** [comment]
I'll take care of this. Is it a good solution to run an action to check if there is deprecation for all actions used?

**Comment by gerashegalov** [comment]
> Is it a good solution to run an action to check if there is deprecation for all actions used?

If you mean to check if  *any* (one or more action) exhibit deprecation warnings I agree.  You can research what is the best and/or easiest way forward for this: 
- whether it should be an non-blocking PR check
- some alert sent to our gh status slack channel
- some gh issue auto-creation with a uniq warning if there is no open yet with the same subject

**Comment by YanxuanLiu** [comment]
I'm trying to run a shell script with gh cli to scan all repos in NVIDIA group. This sh script may run on blossom.

**Comment by YanxuanLiu** [comment]
@gerashegalov I've added a blossom pipeline to scan all warnings of spark-rapids repos, and I've sent the review request to you. Could you help to review the MR? Thanks! Just slack me if you cannot find the MR.

**Comment by YanxuanLiu** [comment]
Fixed with a blossom pipeline.
