### ISSUE TITLE
[AUDIT][SPARK-42821][SQL] Remove unused parameters in splitFiles methods

### ISSUE THREAD

**Issue by parthosa** [NVIDIA/spark-rapids#10299]
This PR removes `sparkSession` parameter in `PartitionedFileUtil.splitFiles` methods. Some of the methods in Plugin use this function. They should be modified accordingly.

Apache Commit - https://github.com/apache/spark/commit/eabea643c74

**Comment by mythrocks** [comment]
This has been addressed in #10857.
