### ISSUE TITLE
[FEA] GPU version of TakeOrderedAndProject

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#103]
**Is your feature request related to a problem? Please describe.**
Because limit is not always deterministic it is typically combined with an order by.  In theses cases a `TakeOrderedAndProject` exec is inserted into the plan.  It would be great to have a GPU enabled version of this to speed up these types of queries and to reduce the amount of data that goes across the PCIe bus.  Inherently this must look at all of the data to do its job, and if we don't have a GPU version of this we have to stream possibly huge amounts of data back from the GPU to the CPU so it can throw out most of it.

Conceptually it should be something like.

```
for each batch:
  combine batch with previous result if it exists
  sort combined result
  save top N results from combined batch
end
return final top N results
```

**Comment by abellina** [comment]
@revans2 I'd love to do this, but I haven't been able to get to it yet, and need to finish something things before I do. I am unassigning myself from it for now.
