### ISSUE TITLE
[DOC] update dead link in UDF doc

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#10322]
We already migrate getting started docs to [new pages](https://docs.nvidia.com/spark-rapids/user-guide/latest/index.html), so we need to fix all dead link in gh-page branch and [original docs](https://nvidia.github.io/spark-rapids/docs/additional-functionality/rapids-udfs.html). And we need to find out why markdown-link checker does not find it.

One [Frequently Asked Questions entry](https://nvidia.github.io/spark-rapids/docs/FAQ.md#how-can-i-run-custom-expressionsudfs-on-the-gpu) dead link in [UDF doc](https://nvidia.github.io/spark-rapids/docs/additional-functionality/rapids-udfs.html),

**Comment by nvliyuan** [comment]
The reason why markdown link checker did not find it is because we just checked the modified files.
https://github.com/NVIDIA/spark-rapids/blob/branch-24.02/.github/workflows/markdown-links-check.yml#L33
There are too much links in the repo, if we check all it will cost tens minutes for each commits.
Let me check all only for this [pr](https://github.com/NVIDIA/spark-rapids/pull/10309) to fix all dead links, and we need to do an all-check if there is a huge doc change pr.
<img width="696" alt="image" src="https://github.com/NVIDIA/spark-rapids/assets/84758614/b846f07c-64db-4cfd-981c-f458056cbb88">

**Comment by nvliyuan** [comment]
There are 3 pages have dead links in total:
https://github.com/NVIDIA/spark-rapids/actions/runs/7707236155/job/21004068930?pr=10309

**Comment by jlowe** [comment]
> we just checked the modified files

This seems like a flawed approach.  It will detect bad links added to the modified files, but it cannot catch the problem of moving/removing a _target_ of a link somewhere else that was not modified (and should have been).

How long does it actually take to run the full scan?  Our CI build already takes 2+ hours, so I'd be shocked if link checking was the limiting factor for PR workflows.  If it's still deemed too expensive to run the full check per PR, we would want to run this regularly (nightly?) to check for bad links.

**Comment by viadea** [comment]
I think we need to run the full checks either nightly or CI. There are huge possibility that the existing doc might have broken links.

**Comment by nvliyuan** [comment]
It will take 5-10 minutes for each commit to check all links, if the CI is two hours then checking all links has very little impact. Will enable all checks.
