### ISSUE TITLE
[FEA] support barrier mode for mapInPandas/mapInArrow

### ISSUE THREAD

**Issue by wbo4958** [NVIDIA/spark-rapids#10344]
**Is your feature request related to a problem? Please describe.**

https://github.com/apache/spark/pull/40520 has introduced barrier mode for mapInPandas/mapInArrow, I hope spark-rapids can support this feature.

How to test?

``` python
spark.range(1, 10, 1, 100).mapInPandas(lambda x: x, "id long", True)
```

to check if all tasks are launched at the same time.

**Comment by wbo4958** [comment]
PR got merged for branch 24.04. Close this issue.

**Comment by revans2** [comment]
reopening because it is being reverted again in 24.04 because it does not build on databricks

**Comment by wbo4958** [comment]
PR got merged. close it
