### ISSUE TITLE
[FEA] Have a repartition fallback for hash aggregates instead of sort

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10370]
**Is your feature request related to a problem? Please describe.**
We know that hash partitioning is faster than sorting.  In GpuHashAggregate if the intermediate values get to be too large we end up sorting the intermediate results and then doing a final pass to output the answer.

In many cases it might be good to have a heuristic in place that sees if the output got smaller so we can decide if we do https://github.com/NVIDIA/spark-rapids/issues/7404 instead.  But in the cases when we see the output is getting a lot smaller than the input or if it is not a partial aggregate, we probably should look at doing hash partitioning of the intermediate results instead of sorting the result.

**Comment by binmahone** [comment]
is this a duplicate with https://github.com/NVIDIA/spark-rapids/issues/8391 ?

**Comment by revans2** [comment]
Yup I filed the same thing twice. Feel free to dupe this to the other or vise versa.

**Comment by binmahone** [comment]
Closing this as it duplicates #8391
