### ISSUE TITLE
[BUG] test_casting_from_overflow_double_to_timestamp `DID NOT RAISE <class 'Exception'>`

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#10431]
**Describe the bug**
Tests failure on Databricks-11.3
```
[2024-02-15T16:06:00.629Z] [31mFAILED[0m ../../src/main/python/orc_cast_test.py::[1mtest_casting_from_overflow_double_to_timestamp[DATAGEN_SEED=1708012573][0m - Failed: DID NOT RAISE <class 'Exception'>
```

**Repro**

The test failure reproduces with an upstream OSS build as well:
```
DATAGEN_SEED=1708012573 \
TZ=UTC \
SPARK_HOME=~/dist/spark-3.5.0-bin-hadoop3 \
TEST_PARALLEL=0 \
./integration_tests/run_pyspark_from_build.sh \
-k test_casting_from_overflow_double_to_timestamp
```

<details>
<summary>Failed: DID NOT RAISE <class 'Exception'></summary>
<pre>
   @allow_non_gpu(*non_utc_allow_for_test_casting_from_overflow_long)
    def test_casting_from_overflow_double_to_timestamp(spark_tmp_path):
        orc_path = spark_tmp_path + '/orc_casting_from_overflow_double_to_timestamp'
        with_cpu_session(
            lambda spark: unary_op_df(spark, DoubleGen(min_exp=38)).write.orc(orc_path)
        )
>       assert_gpu_and_cpu_error(
            df_fun=lambda spark: spark.read.schema("a timestamp").orc(orc_path).collect(),
            conf={},
            error_message="ArithmeticException"
        )

../../src/main/python/orc_cast_test.py:137: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../src/main/python/asserts.py:661: in assert_gpu_and_cpu_error
    assert_spark_exception(lambda: with_gpu_session(df_fun, conf), error_message)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

func = <function assert_gpu_and_cpu_error.<locals>.<lambda> at 0x7face2933910>
error_message = 'ArithmeticException'

    def assert_spark_exception(func, error_message):
        """
        Assert that a specific Java exception is thrown
        :param func: a function to be verified
        :param error_message: a string such as the one produce by java.lang.Exception.toString
        :return: Assertion failure if no exception matching error_message has occurred.
        """
>       with pytest.raises(Exception) as excinfo:
E       Failed: DID NOT RAISE <class 'Exception'>

../../src/main/python/asserts.py:646: Failed
</pre>
</details>

**Comment by mattahrens** [comment]
Initial scope is triaging the failure to see if it is test issue or actual plugin issue or even a Databricks environment issue.

**Comment by gerashegalov** [comment]
The exception is thrown by CPU, not by GPU, debugging the discrepancy
