### ISSUE TITLE
[FEA] Add Spark 3.5.2 snapshot support

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#10437]
**Is your feature request related to a problem? Please describe.**
Once Spark 3.5.1 is released add the Spark 3.5.2 snapshot build and shim.

Note: Need to enable both Scala 2.12 and 2.13

**Comment by tgravescs** [comment]
Note 3.5.2 is up for vote in Apache

**Comment by tgravescs** [comment]
fyi - vote passed in Apache Spark community so should be available soon if not already

**Comment by pxLi** [comment]
I will setup nightly tests after https://github.com/NVIDIA/spark-rapids/pull/11334

**Comment by razajafri** [comment]
@pxLi can you confirm if the nightly has been enabled for 3.5.2? #11334 has been merged.

**Comment by pxLi** [comment]
> [@pxLi](https://github.com/pxLi) can you confirm if the nightly has been enabled for 3.5.2? [#11334](https://github.com/NVIDIA/spark-rapids/pull/11334) has been merged.

yes, it is. We have the nightly CI running for days
