### ISSUE TITLE
[QST] Are all CUDF GPU operations supported?

### ISSUE THREAD

**Issue by timmytwoteeth** [NVIDIA/spark-rapids#10446]
Are all CUDF GPU operations from Rapids-ai supported in Spark-rapids?

For example, say I need to use something like the `SubwordTokenizer`.

**Comment by revans2** [comment]
No we don't directly support everything that the C++ or the python side of CUDF supports. Our primary goal is to take existing SQL/Dataframe queries and accelerate them on the GPU. It should be possible to do something custom with a GPU accelerated UDF. 

https://nvidia.github.io/spark-rapids/docs/additional-functionality/rapids-udfs.html#adding-gpu-implementations-to-udfs

But I am not 100% sure how you would translate the output of the tokenizer back to a SQL format that spark would understand.

**Comment by mattahrens** [comment]
CC @eordentlich

**Comment by timmytwoteeth** [comment]
Thank you for the response and information. So from my understanding once the text has been tokenized you are unable to save it to parquet from the dataframe?

**Comment by jlowe** [comment]
We can save the tokenized text, assuming the tokenized text takes the form of a SQL/DataFrame type that we support writing to Parquet via the GPU.  We support almost all types, e.g.: ArrayType, MapType, StructType, etc.  UDT is something we do not support on the GPU.  If you elaborate a bit on how you propose the UDF would work (i.e.: what it's input types and output types are) that would help us clarify what would and would not be supported automatically by the RAPIDS Accelerator plugin.

**Comment by timmytwoteeth** [comment]
> We can save the tokenized text, assuming the tokenized text takes the form of a SQL/DataFrame type that we support writing to Parquet via the GPU. We support almost all types, e.g.: ArrayType, MapType, StructType, etc. UDT is something we do not support on the GPU. If you elaborate a bit on how you propose the UDF would work (i.e.: what it's input types and output types are) that would help us clarify what would and would not be supported automatically by the RAPIDS Accelerator plugin.

Thank you for the additional information!

Currently what I have envisioned would follow this structure:

1. A set of 128MB parquet files in a datastore containing a singular column of text in string format.
2. The text (str) column is read from the parquet files into the spark rapids data frame.
3. A GPU accelerated UDF utilizes the CUDF SubwordTokenizer to convert the string types to a list of token ints.
4. The tokenized texts (list of ints) are then saved from the spark rapids data frame into snappy parquet files.
