### ISSUE TITLE
[BUG] spark334 and spark342 shims missed in scala2.13 dist jar

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#10464]
spark334 and spark342 shims missed in scala2.13 dist jar

Reported below error when testing with spark-3.4.2 scala2.13 binary
```
24/02/21 23:49:30 ERROR SparkContext: Error initializing SparkContext.
      java.lang.ClassNotFoundException: com.nvidia.spark.rapids.spark342.RapidsShuffleManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
```

**Comment by mattahrens** [comment]
How did the scala 2.13 tests miss these versions and how will we make sure future versions get covered as well?

**Comment by NvTimLiu** [comment]
> How did the scala 2.13 tests miss these versions and how will we make sure future versions get covered as well?

We can not run nightly tests to cover all the shims tests for scala2.13 due to resource is not enough.

But we can optimize our nightly tests to those shims in order every day
