### ISSUE TITLE
Stop using ColumnVector.spark32BitMurmurHash3

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#10487]
cudf is planning to remove the Spark-specific MurmurHash3 kernel since it has been implemented in the `Hash` class in spark-rapids-jni.  See rapidsai/cudf#15074 for details.  The code needs to be updated to stop using ai.rapids.cudf.ColumnVector.spark32BitMurmurHash3 and start using com.nvidia.spark.rapids.jni.Hash.murmurHash32.

**Comment by gerashegalov** [comment]
fixed by #10652
