### ISSUE TITLE
[FEA] Drop support for CentOS7

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#10496]
**Is your feature request related to a problem? Please describe.**
Drop support for CentOS7, as it will be end of life mid-2024, per https://www.redhat.com/en/topics/linux/centos-linux-eol

**Describe the solution you'd like**
Support for Rocky 8, Ubuntu 20.04, 22.04 will continue

**Describe alternatives you've considered**
RAPIDS is dropping support per https://docs.rapids.ai/notices/rsn0037/ , so I am not sure there are many alternatives

**Additional context**
https://github.com/rapidsai/build-planning/issues/23

**Comment by GaryShen2008** [comment]
Assign to myself first to figure out which OS we should use to run the build to support all the OSs. Mainly it's the problem about Glibc compatibility.

**Comment by bdice** [comment]
@GaryShen2008 After dropping CentOS 7, the oldest glibc of any OS supported by RAPIDS will be glibc 2.28, which is used by Rocky Linux 8. [Ubuntu 20.04 uses 2.31](https://launchpad.net/ubuntu/focal/+source/glibc) and [Ubuntu 22.04 uses 2.35](https://launchpad.net/ubuntu/jammy/+source/glibc).

Based on that, you'll probably want to build on Rocky Linux 8.

**Comment by sameerz** [comment]
> @GaryShen2008 After dropping CentOS 7, the oldest glibc of any OS supported by RAPIDS will be glibc 2.28, which is used by Rocky Linux 8. [Ubuntu 20.04 uses 2.31](https://launchpad.net/ubuntu/focal/+source/glibc) and [Ubuntu 22.04 uses 2.35](https://launchpad.net/ubuntu/jammy/+source/glibc). (Also noted in this issue: [rapidsai/build-planning#23](https://github.com/rapidsai/build-planning/issues/23))

Is the glibc version valid for both x86 and ARM on Rocky8 and Ubuntu 20.04?

**Comment by bdice** [comment]
@sameerz Yes, each distro uses the same glibc version on x86-64 and ARM. The glibc version just varies with the OS version.

Also, I just merged https://github.com/rapidsai/shared-workflows/pull/192 which removes CentOS 7 from the RAPIDS 24.06 build/test matrix.

**Comment by NvTimLiu** [comment]
Built out amd64/arm64 jars on Rocky8, running integration tests with spark-rapids to see if any GLIBC issues.

**Comment by NvTimLiu** [comment]
PR to drop CentOS7 build for spark-rapids-jni: https://github.com/NVIDIA/spark-rapids-jni/pull/2010

PR to drop CentOS7 build for cuDF JNI: https://github.com/rapidsai/cudf/pull/15608
