### ISSUE TITLE
[BUG] GetJsonObject throws exception when json path contains a name starting with `'`

### ISSUE THREAD

**Issue by thirtiseven** [NVIDIA/spark-rapids#10537]
**Describe the bug**
`$.'a` is a valid path from Spark's check, so it is normalized to `$[''a']` and passed to kernel in plugin, resulting in

```
ai.rapids.cudf.CudfException: CUDF failure on: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-690-cuda11/thirdparty/cudf/cpp/src/json/json_path.cu:631: Invalid empty name in JSONPath query string
```

Note that `$[''a']` is actually an invalid path from Spark's validation. So maybe the normalization we did in plugin [b9c292c](https://github.com/NVIDIA/spark-rapids/commit/b9c292cd20467f3cc94dc28ed4f512425446b2ca) is losing some information when converting the `List[PathInstruction]` back to a string and causing some problems.

And at the same time, cuDF kernel can't match this case as well if we remove the normalization.

data: `{"'a":"1"}`

Spark, spark-rapids, cudf and jsonpath.com will give very different results in this case.

| JSONPath | Spark | spark-rapids | cudf kernel(spark-rapids without normalization) | jsonpath.com |
|---|---|---|---|---|
| $[''a'] | null | null | Invalid empty name in JSONPath query string | ["1"] |
| $.'a | 1 | Invalid empty name in JSONPath query string | Encountered invalid JSONPath input string | No match |

I think we can fallback on this case until we have a path parser that matches Spark's behavior.

**Comment by thirtiseven** [comment]
https://github.com/rapidsai/cudf/pull/15082 looks to be contributing to fixing this issue, will update after it is included in the plugin.

**Comment by res-life** [comment]
Will be fixed by: https://github.com/NVIDIA/spark-rapids-jni/pull/1868
