### ISSUE TITLE
[FEA] Support "WindowGroupLimit" optimization on GPU for Databricks 13.3 ML LTS+

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#10531]
**Is your feature request related to a problem? Please describe.**
Issue #8208 enabled WindowGroupLimit in the Spark 3.5.0 and 3.5.1 shims.  It did not enable for Databricks 13.3 ML LTS.  

**Describe the solution you'd like**
Enable WindowGroupLimit in the Databricks 13.3 ML LTS shim.  

**Describe alternatives you've considered**

**Additional context**
https://docs.databricks.com/en/release-notes/runtime/13.3lts.html

**Comment by mythrocks** [comment]
Investigating now.
