### ISSUE TITLE
[FEA] Support project expression rewrite for the case ```stringinstr(str_col, substr) > 0``` to ```contains(str_col, substr)```

### ISSUE THREAD

**Issue by winningsix** [NVIDIA/spark-rapids#10578]
**Is your feature request related to a problem? Please describe.**
In the case of ```stringinstr(str, substr) > 0```, currently it's interpreted as ```GreaterThan``` with ```stringinstr``` as its child expression.  And in this case, we don't care about the string location, thus, we can rewrite this condition with ```contains``` at the physical plan level within Spark Rapids Plugin, avoiding an extra binary operation. And ```binary_operation``` is more expensive than string contains.

**Comment by revans2** [comment]
This is going to require a small cudf change to let us get access to a cudf::contains that uses a column of values instead of a scalar.

https://github.com/rapidsai/cudf/blob/64d651dc1a1dc309f08fee2502198f6a2e0e13b0/cpp/include/cudf/strings/find.hpp#L136

**Comment by revans2** [comment]
Never mind, that is a nice to have, but we don't support anything bust a scalar for substr.
