### ISSUE TITLE
[AUDIT][TASK] Test CSV Reader for multi-line mode

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#10577]
This is the result of reviewing https://github.com/apache/spark/commit/829e742df82.

Apache Spark's CSV Reader currently has a workaround that disables column-pruning in the event that input records span multiple lines.
This workaround was put in place in [SPARK-46862](https://issues.apache.org/jira/browse/SPARK-46862) to get around https://github.com/uniVocity/univocity-parsers/issues/529.

I'm not sure how the Spark RAPIDS plugin handles multi-line records such as those in this example:
```
"1","DE","","Yes"
"5",",","",","
"3","SA","","No"
"10","abcd""efgh"" \ndef","",""
```
It would be good to verify that the plugin handles these identically to Spark 3.5.

**Comment by mattahrens** [comment]
We already fallback for CSV multi-line reading and have no plans to support it in the plugin.
