### ISSUE TITLE
[FEA] Remove tailing column-2-row when the entire plan is on GPU

### ISSUE THREAD

**Issue by winningsix** [NVIDIA/spark-rapids#10629]
**Is your feature request related to a problem? Please describe.**
When executing queries like `sql("insert ...")`, it will add an `executeCollect()` for [eager execution](
https://github.com/apache/spark/blob/4a1f2419e243272064fde96529149316fe53bc10/sql/core/src/main/scala/org/apache/spark/sql/execution/QueryExecution.scala#L119-L121). When we enable `InsertIntoHive` with GPU support, it's required to insert a C2R [transition](https://github.com/apache/spark/blob/e22ddcbd852c95375d39fd6074627e1b5a91c6e7/sql/core/src/main/scala/org/apache/spark/sql/execution/Columnar.scala#L518-L521), which is useless as it's returning with empty row.

**Describe the solution you'd like**
We should have a fix up to remove the tailing c-2-r node.

**Comment by jlowe** [comment]
Duplicates #9449

**Comment by firestarman** [comment]
close as duplicated
