### ISSUE TITLE
[FOLLOWUP] Query max instructions length in getJsonObject from JNI

### ISSUE THREAD

**Issue by thirtiseven** [NVIDIA/spark-rapids#10646]
Nit: The max length value should be queried from JNI so we always have such value sync. This can be addressed in the follow up work (which requires JNI to expose such value).

_Originally posted by @ttnghia in https://github.com/NVIDIA/spark-rapids/pull/10581#discussion_r1541941400_

Also some test cases need to clean up, see #10581 's comments.

**Comment by thirtiseven** [comment]
Another follow-up: get_json_object compatibility doc is outdated.

https://github.com/NVIDIA/spark-rapids/blob/branch-24.04/docs/compatibility.md#get_json_object

**Comment by thirtiseven** [comment]
float normalization will have some compatibility issue, as the same as float to string. We should add another test to verify it.

**Comment by sameerz** [comment]
> Another follow-up: get_json_object compatibility doc is outdated.
> 
> https://github.com/NVIDIA/spark-rapids/blob/branch-24.04/docs/compatibility.md#get_json_object

@thirtiseven I noticed the PR that closed this issue did not update the documentation.  Are the docs still accurate?

**Comment by thirtiseven** [comment]
> > Another follow-up: get_json_object compatibility doc is outdated.
> > https://github.com/NVIDIA/spark-rapids/blob/branch-24.04/docs/compatibility.md#get_json_object
> 
> @thirtiseven I noticed the PR that closed this issue did not update the documentation. Are the docs still accurate?

Yes, it has been updated in https://github.com/NVIDIA/spark-rapids/commit/f6054fa94f615056e184dac0fd4b2df9012cde16
