### ISSUE TITLE
[BUG] thrust system_error

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1065]
**Describe the bug**
There was a recent failure in a test run that all we got back was

```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountered
```

I don't know if it is reproducible or not, but at a minimum we probably want to have the JNI CUDF layer handle `thrust::system::system_error` exceptions so we can get more information back about what API was being called, etc at the time.

**Comment by sameerz** [comment]
We think this is fixed by https://github.com/rapidsai/cudf/pull/6710
