### ISSUE TITLE
[AUDIT][SPARK-47009][SQL] Enable create table support for collation

### ISSUE THREAD

**Issue by parthosa** [NVIDIA/spark-rapids#10701]
A new `COLLATE` expression is introduced for creating table with collated columns using parquet. 

Spark Commit: https://github.com/apache/spark/commit/298134fd5e9

**Comment by parthosa** [comment]
Follow up work to disable partitioning on collated columns

https://github.com/apache/spark/commit/813934c69df

**Comment by revans2** [comment]
I think we just want to fall back to the CPU any time see anything that is collated.

https://github.com/NVIDIA/spark-rapids/issues/10687

**Comment by mattahrens** [comment]
Dup of https://github.com/NVIDIA/spark-rapids/issues/10687
