### ISSUE TITLE
[AUDIT] Match DataSourceV2ScanExecBase changes to groupPartitions method 

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#10711]
As part of https://github.com/apache/spark/commit/9e2aafb1373 Spark has made changes to the DataSourceV2ScanExecBase which should be matched.

**Comment by mythrocks** [comment]
I'm taking a crack at this one.

**Comment by razajafri** [comment]
As discussed offline, this is redundant due to #10712. We can converge our efforts in #10944

**Comment by mythrocks** [comment]
Closing this. It's handled by #10944.
