### ISSUE TITLE
[FEA] Databricks 7.3 nightly build and integration testing

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#1071]
Set up nightly builds for the 0.3-SNAPSHOT against Databricks 7.3.  Run the integration tests for 0.3 on Databricks 7.3.  

Depends on the Databricks 7.3 shim being available per issue #502

**Comment by sameerz** [comment]
From issue #1085 : 

> note #502 added support for 7.3 and it added a jenkins files, so we just need to create a build based on it.
https://github.com/NVIDIA/spark-rapids/blob/branch-0.3/jenkins/Jenkinsfile.databricks301nightly

> I tested it in the ci dev environment so it should be good.

**Comment by tgravescs** [comment]
@NvTimLiu @GaryShen2008  can we do this one soon so we can remove the 7.0 nightly. We need to remove the shim layer code for it but I want a build running first.

**Comment by NvTimLiu** [comment]
@tgravescs  Sure, I'm checking it now. If any question, I'll ping you, thanks！

**Comment by NvTimLiu** [comment]
created a test Blossom Jenkins to run the DB301 build, https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/Testing/job/tim-301db/7/console
Will merge this Blossom Jenkins once it PASS.

**Comment by NvTimLiu** [comment]
Some testcase FAILs: @tgravescs  Could you please help to check?

https://ci-dev.ngcc.nvidia.com/job/tim-db301/7/console
18:15:15  <string>:3: IllegalArgumentException
18:15:15  ----------------------------- Captured stdout call -----------------------------
18:15:15  ### CPU RUN ###
18:15:15  ### GPU RUN ###
18:15:15  =============================== warnings summary ===============================
18:15:15  ../../../../databricks/spark/python/pyspark/sql/context.py:77
18:15:15    /databricks/spark/python/pyspark/sql/context.py:77: DeprecationWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
18:15:15      DeprecationWarning)
18:15:15  
18:15:15  -- Docs: https://docs.pytest.org/en/stable/warnings.html
18:15:15  =========================== short test summary info ============================
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[No_Partition-Byte][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[No_Partition-Short][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[No_Partition-Integer][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Unbounded-Byte][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Unbounded-Short][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Unbounded-Integer][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Unbounded_Following-Byte][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Unbounded_Following-Short][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Unbounded_Following-Integer][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Unbounded_Preceding-Byte][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Unbounded_Preceding-Short][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Unbounded_Preceding-Integer][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Lower_Upper-Byte][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Lower_Upper-Short][IGNORE_ORDER]
18:15:15  FAILED src/main/python/udf_test.py::test_window_aggregate_udf[Lower_Upper-Integer][IGNORE_ORDER]
18:15:15  = 15 failed, 3473 passed, 202 skipped, 153 xfailed, 5 xpassed, 1 warning in 9376.59s (2:36:16) =
18:15:27  /bin/sh: 1: Bad substitution
18:15:27  /bin/sh: 1: [: -ne: unexpected operator
18:15:27  Warning: Identity file /home/****/.ssh/id_rsa not accessible: No such file or directory.
18:15:27  Warning: Permanently added '[ec2-54-202-23-20.us-west-2.compute.amazonaws.com]:2200,[54.202.23.20]:2200' (ECDSA) to the list of known hosts.
18:15:27  receiving incremental file list
18:15:27  rsync: link_stat "/home/ubuntu/spark-rapids-built.tgz" failed: No such file or directory (2)

**Comment by tgravescs** [comment]
these are the same failures the Databricks build failed with and should have been fixed here: https://github.com/NVIDIA/spark-rapids/pull/1123/files

what is this using to build?  Did you specify the --runtime_env="databricks" option with spark-submit.  We have the build.sh script we use for Databricks and there is a lot of little setup things in there.

**Comment by NvTimLiu** [comment]
@tgravescs I run the build with latest DB scripts, so --runtime_env="databricks" is set.
https://github.com/NVIDIA/spark-rapids/blob/branch-0.3/jenkins/databricks/build.sh#L128

**Comment by tgravescs** [comment]
oh it looks like https://github.com/NVIDIA/spark-rapids/commit/2ac2a629b012a3ca71a834f544d0f17d45e3cf49#diff-03e1957b22d82445ddd56c7b2da6e6d8c9bc081abde5039a0cef4e7bff69e18d removed the fail. I et that didn't handle it for 7.3 runtime

I commented on https://github.com/NVIDIA/spark-rapids/pull/1124

@NvTimLiu please go ahead and put the build in place or put up PR with build stuff. The tests failing we can fix later.

**Comment by NvTimLiu** [comment]
Added databricks 301 pipeline one Blossom by MR：https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/merge_requests/5

**Comment by revans2** [comment]
These are also failing for 3.1.0 spark test.  I suspect that it is the same issue with the shim layer.

**Comment by NvTimLiu** [comment]
pipeline on Blossom here: https://blossom.nvidia.com/sw-gpu-spark-jenkins/job/rapids_databricks301_nightly-0.3-github/

**Comment by NvTimLiu** [comment]
pipeline created, close
