### ISSUE TITLE
Signature changed for `PythonUDFRunner.writeUDFs` 

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#10714]
As part of https://github.com/apache/spark/commit/d8703dd1c7bbdac24dbcbf3e3eeb9c54595d53c3 Spark made a change to the signature of the `writeUDFs` method in `PythonUDFRunner` class. We directly call that method in `GpuArrowPythonRunner.scala` and we should make that change.

**Comment by razajafri** [comment]
I think this will be best done by @firestarman

**Comment by firestarman** [comment]
Here is the fix, but i failed to verify it for Spark 400.
