### ISSUE TITLE
[DOC] There are too many changelog links on https://nvidia.github.io/spark-rapids/ , and they are not well formatted

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#10736]
## Report incorrect documentation
The content of the following pages does not show up as tables: 
https://nvidia.github.io/spark-rapids/docs/archives/CHANGELOG_0.1_to_0.5.html
https://nvidia.github.io/spark-rapids/docs/archives/CHANGELOG_21.06_to_21.12.html
https://nvidia.github.io/spark-rapids/docs/archives/CHANGELOG_22.02_to_22.12.html
https://nvidia.github.io/spark-rapids/docs/archives/CHANGELOG_23.02_to_23.12.html

**Location of incorrect documentation**
https://nvidia.github.io/spark-rapids/

**Describe the problems or issues found in the documentation**
Data does not appear as tables. 

**Steps taken to verify documentation is incorrect**
N/A

**Suggested fix for documentation**
There are also too many changelog links at https://nvidia.github.io/spark-rapids/ , they should be either one page or in a collapseable section.

**Comment by SurajAralihalli** [comment]
Its immediately after the release notes : https://nvidia.github.io/spark-rapids/docs/download.html#release-notes

>  For a detailed list of changes, please refer to the [CHANGELOG](https://github.com/NVIDIA/spark-rapids/blob/main/CHANGELOG.md).
