### ISSUE TITLE
[DOC] Dead links with tools pages

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10768]
## Report incorrect documentation

I am getting errors in premerge about docs not being there in README.md

```
ERROR: 2 dead links found!
[✖] https://docs.nvidia.com/spark-rapids/user-guide/latest/spark-qualification-tool.html → Status: 404
[✖] https://docs.nvidia.com/spark-rapids/user-guide/latest/spark-profiling-tool.html → Status: 404
```

I manually look and they are gone. I didn't find any other issues for this.

**Comment by mattahrens** [comment]
Fixed by https://github.com/NVIDIA/spark-rapids/pull/10766
