### ISSUE TITLE
[BUG] Issues found by Spark UT Framework on RapidsRegexpExpressionsSuite

### ISSUE THREAD

**Issue by binmahone** [NVIDIA/spark-rapids#10774]
**Describe the bug**

Spark UT Framework enabled RapidsRegexpExpressionsSuite (https://github.com/NVIDIA/spark-rapids/pull/10743), with the following test cases explicitly excluded:

- [x] RegexReplace
- [x] RegexExtract
- [x] RegexExtractAll
- [x] SPLIT

**These excluded test cases needs further investigating!!!**
Notice: Other test cases in this suite may pass with falling back!

**Steps/Code to reproduce bug**
1. Compile everything with `mvn -Dbuildver=330 install -DskipTests`
2. Pick a test case name in the above table
3. Go to RapidsTestSettings and find the line starting with ".exclude" and containing the test case name, comment it out
4. Run the Suite then you'll see one failed test case. E.g. `mvn -nsu -Dbuildver=330 -pl tests -Dsuites="org.apache.spark.sql.rapids.suites.RapidsXXXSuite" test` (replace RapidsXXXSuite with the right name in issue header). ALWAYS double check if your suite name coincide with in source code, as it may contain typos!

**Expected behavior**
The suite can pass without excluding any test case.

**Comment by mattahrens** [comment]
Initial scope is triaging unit test failures to determine priorities of individual issues.

**Comment by NVnavkumar** [comment]
So the 4 tests pass if I disable Whole-stage codegen in `RapidsTestTrait.scala`

```
...        
   .config("spark.sql.codegen.wholeStage", "false")
...
```

I would recommend disabling it and retrying the whole suite of tests to check up on this issue and https://github.com/NVIDIA/spark-rapids/issues/10775 and maybe others.

**Comment by NVnavkumar** [comment]
So most of these tests are falling back to the CPU (the ignored test is a codegen verification test):

```
RapidsRegexpExpressionsSuite:
'LIKE ALL' NOT use RAPIDS
- LIKE ALL
'LIKE ANY' NOT use RAPIDS
- LIKE ANY
'LIKE Pattern' NOT use RAPIDS
- LIKE Pattern
'LIKE Pattern ESCAPE '/'' NOT use RAPIDS
- LIKE Pattern ESCAPE '/'
'LIKE Pattern ESCAPE '#'' NOT use RAPIDS
- LIKE Pattern ESCAPE '#'
'LIKE Pattern ESCAPE '"'' NOT use RAPIDS
- LIKE Pattern ESCAPE '"'
'RLIKE Regular Expression' NOT use RAPIDS
- RLIKE Regular Expression
'RegexReplace' NOT use RAPIDS
- RegexReplace
- SPARK-22570: RegExpReplace should not create a lot of global variables !!! IGNORED !!!
'RegexExtract' NOT use RAPIDS
- RegexExtract
'RegexExtractAll' NOT use RAPIDS
- RegexExtractAll
'SPLIT' NOT use RAPIDS
- SPLIT
'SPARK-30759: cache initialization for literal patterns' offload to RAPIDS
- SPARK-30759: cache initialization for literal patterns
'SPARK-34814: LikeSimplification should handle NULL' NOT use RAPIDS
- SPARK-34814: LikeSimplification should handle NULL
```

These tests are all falling back to CPU for a couple of reasons:


Use of non-literal patterns:
```
 !Expression <StringSplit> split(input[0, string, true], input[1, string, true], -1) cannot run on GPU because regexp only supports StringType if it is a literal value; Only literal delimiter patterns are supported
```

ConstantFolding is excluded:
```
Expression <Contains> Contains(foo, foo) cannot run on GPU because Cannot run on GPU. Is ConstantFolding excluded? Expression Contains(foo, foo) is foldable and operates on non literals
```

Recommend to disable this suite until the tests can be rewritten to avoid these errors. Otherwise, this suite is just running the same tests run by Apache Spark.

**Comment by binmahone** [comment]
will be fixed by https://github.com/NVIDIA/spark-rapids/pull/10851, suggest to close this issue

**Comment by jlowe** [comment]
If we want to close this issue when #10851 is merged, then we can simply link that PR as closing this issue.  Then it will be closed iff that PR is merged.  I've updated this issue accordingly.

**Comment by GaryShen2008** [comment]
Close by #10861
