### ISSUE TITLE
[BUG] Issues found by Spark UT Framework on RapidsStringExpressionsSuite

### ISSUE THREAD

**Issue by binmahone** [NVIDIA/spark-rapids#10775]
**Describe the bug**

Spark UT Framework enabled RapidsStringExpressionsSuite (https://github.com/NVIDIA/spark-rapids/pull/10743), with the following test cases explicitly excluded:

- [x] #10925
- [ ] string substring_index function, related to https://github.com/NVIDIA/spark-rapids/issues/8750
- [x] https://github.com/NVIDIA/spark-rapids/issues/10899
- [x] SPARK-22498: Concat should not generate codes beyond 64KB
- [x] SPARK-22549: ConcatWs should not generate codes beyond 64KB
- [x] SPARK-22550: Elt should not generate codes beyond 64KB
- [x] SPARK-22603: FormatString should not generate codes beyond 64KB
- [x] ParseUrl

**These excluded test cases needs further investigating!!!**
Notice: Other test cases in this suite may pass with falling back!

**Steps/Code to reproduce bug**
1. Compile everything with `mvn -Dbuildver=330 install -DskipTests`
2. Pick a test case name in the above table
3. Go to RapidsTestSettings and find the line starting with ".exclude" and containing the test case name, comment it out
4. Run the Suite then you'll see one failed test case. E.g. `mvn -nsu -Dbuildver=330 -pl tests -Dsuites="org.apache.spark.sql.rapids.suites.RapidsXXXSuite" test` (replace RapidsXXXSuite with the right name in issue header). ALWAYS double check if your suite name coincide with in source code, as it may contain typos!

**Expected behavior**
The suite can pass without excluding any test case.

**Comment by mattahrens** [comment]
Initial scope is triaging unit test failures to determine priorities of individual issues.

**Comment by mythrocks** [comment]
All but one of the reported failures disappear when whole-stage codegen is disabled.

There does seem to be a genuine failure in the tests for `ParseUrl`. I will raise a separate bug to track that one.

**Comment by mythrocks** [comment]
I've filed https://github.com/NVIDIA/spark-rapids/pull/10810, for which a fix is available at https://github.com/NVIDIA/spark-rapids/pull/10811.

**Comment by mythrocks** [comment]
@binmahone, @NVnavkumar, what are your thoughts on disabling whole-stage codegen for these tests?  It should resolve almost all the failures listed here (save for the last one, which will be fixed with #10811).

**Comment by NVnavkumar** [comment]
I think it's the right move. We do need further investigation to disable any of the codegen specific-tests here. I know that in the regexp suite I saw a handful of places that were testing the java output of the codegen step.

> @binmahone, @NVnavkumar, what are your thoughts on disabling whole-stage codegen for these tests? It should resolve almost all the failures listed here (save for the last one, which will be fixed with #10811).

**Comment by binmahone** [comment]
after discussion with Gary and Ferdinand, we have refined the Spark UT Framework by https://github.com/NVIDIA/spark-rapids/pull/10851 , which eliminates the necessity of disabling wholeStage. Now the list of the failed tests is refreshed. After PR 10851 is merged, we can move forward to investigate the remaining failed test cases.

**Comment by mythrocks** [comment]
I'm closing this bug. The remaining issue (#8750) is being tackled by @Feng-Jiang28.  Let's track that issue there.
