### ISSUE TITLE
[BUG] cast(9.95 as decimal(3,1)), actual: 9.9, expected: 10.0

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#10809]
# Repro

```bash
 ~/dist/spark-3.3.0-bin-hadoop3/bin/spark-shell  \
   --conf spark.plugins=com.nvidia.spark.SQLPlugin \
   --conf spark.rapids.sql.test.enabled=true \
   --conf spark.rapids.sql.explain=ALL 
   --jars dist/target/rapids-4-spark_2.12-24.06.0-SNAPSHOT-cuda11.jar 
```

```Scala
scala> val df = Seq(9.95).toDF.coalesce(1)
df: org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [value: double]

scala> spark.conf.set("spark.rapids.sql.enabled", true)

scala> df.selectExpr("cast(value as decimal(3,1))").collect()
24/05/13 11:34:42 WARN GpuOverrides: 
*Exec <ProjectExec> will run on GPU
  *Expression <Alias> cast(value#1 as decimal(3,1)) AS value#5 will run on GPU
    *Expression <Cast> cast(value#1 as decimal(3,1)) will run on GPU
  *Exec <CoalesceExec> will run on GPU
    ! <LocalTableScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.LocalTableScanExec
      @Expression <AttributeReference> value#1 could run on GPU

res2: Array[org.apache.spark.sql.Row] = Array([9.9])

scala> spark.conf.set("spark.rapids.sql.enabled", false)

scala> df.selectExpr("cast(value as decimal(3,1))").collect()
res4: Array[org.apache.spark.sql.Row] = Array([10.0])
```

Related to #9682

**Comment by mattahrens** [comment]
Scope: make casting of floats to decimals feature flag off by default.  Ref: [spark.rapids.sql.castFloatToDecimal.enabled](https://github.com/NVIDIA/spark-rapids/blob/branch-24.06/docs/additional-functionality/advanced_configs.md#sql.castFloatToDecimal.enabled).

**Comment by ttnghia** [comment]
Filed a cudf issue: https://github.com/rapidsai/cudf/issues/15862

**Comment by gerashegalov** [comment]
Also take a look at the discussion around https://github.com/NVIDIA/spark-rapids/issues/9682#issuecomment-2126616418 and above. 9.95 is not representable as double

```java
$ jshell 
|  Welcome to JShell -- Version 21.0.2
|  For an introduction type: /help intro

jshell> new BigDecimal(9.95)
$8 ==> 9.949999999999999289457264239899814128875732421875

jshell> new BigDecimal(9.949999999999999289457264239899814128875732421875)
$9 ==> 9.949999999999999289457264239899814128875732421875

jshell> new BigDecimal(9.95).setScale(1, BigDecimal.ROUND_HALF_UP)
$11 ==> 9.9

jshell> new BigDecimal("9.95").setScale(1, BigDecimal.ROUND_HALF_UP)
$12 ==> 10.0
```

**Comment by ttnghia** [comment]
Okay after reading through the issue https://github.com/NVIDIA/spark-rapids/issues/9682 then I realize that this issue is also one instance of it.

**Comment by thirtiseven** [comment]
I tried the float => string => decimal path (it is very easy to implement in plugin), the differences are from the known limits of ryu float to string and a very edge cases in string to decimal https://github.com/NVIDIA/spark-rapids/issues/10890. I will post a pr next week, but not sure if the diffs are acceptable or original way can match it better.

**Comment by ttnghia** [comment]
That sounds good. I've also found a way to implement in C++ which is very efficient but not sure if it will pass integration test. I'll verify that and will post a PR too.

If having a chance, please list the related tests that I can run to verify.

**Comment by ttnghia** [comment]
@thirtiseven Please test https://github.com/NVIDIA/spark-rapids/pull/10917 to see if you have any test fails. On my local env, all the unit tests and integration tests passed but I'm not sure if I missed anything.

**Comment by GaryShen2008** [comment]
Hi @ttnghia, https://github.com/rapidsai/cudf/pull/15905 has been merged, is it ready to fix this issue by using this new way?

**Comment by ttnghia** [comment]
No that is not what we want. We may need something from https://github.com/pmattione-nvidia/cudf/pull/2 which will be added into https://github.com/NVIDIA/spark-rapids-jni/pull/2078, which is what we actually need. I will work on it soon this week.

**Comment by ttnghia** [comment]
Thanks @GaryShen2008. The fix in JNI will be picked by spark-rapids in https://github.com/NVIDIA/spark-rapids/pull/10917 thus this issue will be closed by that PR.
