### ISSUE TITLE
[FEA] Don't fail the link checker for unreleased maven jars

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#10834]
**Is your feature request related to a problem? Please describe.**
It is at the point now when the majority of people don't check failures in the link checker because it always fails because of this. We really need a good way for the link checker to fail for anything except the latest maven releases.  We have had a few cases when files were removed/changed locations and the link checker found them, but no one did anything for a long time because no one was checking.

**Comment by nvliyuan** [comment]
Let me work with @NvTimLiu
