### ISSUE TITLE
[QST] Why can't I fetch many dependencies, causing many classes to be marked in red? Do I need to set something?

### ISSUE THREAD

**Issue by yongster** [NVIDIA/spark-rapids#10848]
**What is your question?**
project version is 24.02.0
maven setting only set  localRepository and proxy 
<img width="57" alt="image" src="https://github.com/NVIDIA/spark-rapids/assets/76621090/315b2797-d7bf-42ea-9f4e-334ab06df50c">
<img width="776" alt="image" src="https://github.com/NVIDIA/spark-rapids/assets/76621090/37caaf16-c744-432d-877a-527a77031155">

**Comment by yongster** [comment]
We want to make some modifications to the source code, but while reading the source code, we found that important implementations like SparkShimImpl are all marked in red.

**Comment by jlowe** [comment]
Have you gone through the [IDE setup steps in the contribution guide](https://github.com/NVIDIA/spark-rapids/blob/branch-24.06/CONTRIBUTING.md#setting-up-an-integrated-development-environment)?  It's not mentioned which IDE, but from the screenshot my guess is Visual Studio Code.  cc: @gerashegalov who is more familiar with that IDE environment.

**Comment by gerashegalov** [comment]
Thanks for tagging @jlowe . I believe it is the New UI option in IntelliJ IDEA. The dependencies highlighted are from different Maven profiles for Spark 3.2.1 and a CDH release based on 3.2.1.  All these `releaseXYZ` profiles are mutually exclusive, we activate one at a time to develop and test against a particular Spark release. The default profile is release311. 

It looks like once you have followed the instructions Jason linked above and you have worked with enough shims all dependencies will be cached and appear as resolved. The once that have never been touched by any previously activated profiles will continue to appear unresolved.

**Comment by yongster** [comment]
> It looks like once you have followed the instructions Jason linked above and you have worked with enough shims all dependencies will be cached and appear as resolved. The ones that have never been touched by any previously activated profiles will continue to appear unresolved.

I followed the configuration instructions in the aforementioned link, but many classes still cannot be found. For example, import org.apache.spark.sql.rapids.shims.{GpuAscii, GpuMapInPandasExecMeta, GpuTimeAdd} and SparkShimImpl. It seems that some JAR files were not downloaded, but IDEA indicates that the dependencies have been successfully retrieved. Additionally, I successfully ran mvn install. I am using IntelliJ IDEA 2021.3.3 Release 331.

**Comment by yongster** [comment]
in class  com.nvidia.spark.rapids.GpuOverrides.scala. 

> > It looks like once you have followed the instructions Jason linked above and you have worked with enough shims all dependencies will be cached and appear as resolved. The ones that have never been touched by any previously activated profiles will continue to appear unresolved.看起来一旦您按照上面链接的 Jason 说明操作并且使用了足够的填充程序，所有依赖项都将被缓存并显示为已解决。那些从未被任何先前激活的配置文件触及的问题将继续显示为未解决。
> 
> I followed the configuration instructions in the aforementioned link, but many classes still cannot be found. For example, import org.apache.spark.sql.rapids.shims.{GpuAscii, GpuMapInPandasExecMeta, GpuTimeAdd} and SparkShimImpl. It seems that some JAR files were not downloaded, but IDEA indicates that the dependencies have been successfully retrieved. Additionally, I successfully ran mvn install. I am using IntelliJ IDEA 2021.3.3 Release 331.我按照上述链接中的配置说明进行操作，但仍然找不到许多类。例如，导入 org.apache.spark.sql.rapids.shims.{GpuAscii, GpuMapInPandasExecMeta, GpuTimeAdd} 和 SparkShimImpl。看起来有些JAR文件没有下载，但IDEA表明依赖项已成功检索。此外，我成功运行了 mvn install。我正在使用 IntelliJ IDEA 2021.3.3 版本 331。

in class GpuOverrides.scala 。maven version is 3.8.x.  As a result, we cannot thoroughly read the logic of much of our code, which hinders our ability to debug and make modifications.

**Comment by jlowe** [comment]
These steps work for me in IDEA:
- Go to the Maven settings (typically accessible via the right sidebar) and check the release profile matching the version of Spark you want to target during development (e.g.: select release341 for Spark 3.4.1).  Make sure no other release* profiles are checked.
- Perform a mvn build (e.g.: mvn clean install -DskipTests -Dbuildver=341,  if we're continuing with the Spark 3.4.1 example)
- Click the Reload All Maven Projects button in the Maven settings window to refresh IDEAs view of the poms
- Click the Generate Sources and Update Folders For All Projects button (right next to the Reload All Maven Projects button).  This may take a little bit.

After those steps complete, IDEA is able to recognize and find the shim classes for the specified Spark version (e.g.: Spark 3.4.1 in the example above).  This is with IDEA 2024.1 (IC-241.14494.240).

**Comment by yongster** [comment]
> These steps work for me in IDEA:
> 
> * Go to the Maven settings (typically accessible via the right sidebar) and check the release profile matching the version of Spark you want to target during development (e.g.: select release341 for Spark 3.4.1).  Make sure no other release* profiles are checked.
> * Perform a mvn build (e.g.: mvn clean install -DskipTests -Dbuildver=341,  if we're continuing with the Spark 3.4.1 example)
> * Click the Reload All Maven Projects button in the Maven settings window to refresh IDEAs view of the poms
> * Click the Generate Sources and Update Folders For All Projects button (right next to the Reload All Maven Projects button).  This may take a little bit.
> 
> After those steps complete, IDEA is able to recognize and find the shim classes for the specified Spark version (e.g.: Spark 3.4.1 in the example above). This is with IDEA 2024.1 (IC-241.14494.240).

It doesn't work. I can't solve this problem. It might be because my environment is Windows. When I run `mvn clean` locally, it reports an error: An Ant BuildException has occurred: Execute failed: java.io.IOException: Cannot run program "rm" (in directory "D:\workspace\spark-rapids"): CreateProcess error=2.

**Comment by jlowe** [comment]
Unfortunately we do not support Windows.  I'm sure with some effort the build environment could support Windows.  For example, for that specific failure, might be able to change the clean-all-modules antrun execution to use the Ant Delete task or use some other more portable approach rather than using the `rm` executable.  I don't know how many other Windows problems are lurking in the build beyond that.
