### ISSUE TITLE
[DOC]  v2402 already support spark342

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#10840]
We had a [pr](https://github.com/NVIDIA/spark-rapids/pull/9967) to add spark342 support, and I verified in local.
But in our [archive](https://nvidia.github.io/spark-rapids/docs/archive.html) doc, we don't mention we support spark342, is it a doc issue?
<img width="1103" alt="image" src="https://github.com/NVIDIA/spark-rapids/assets/84758614/87d17e35-2f76-4fd3-afdd-96449de7ba9b">

**Comment by SurajAralihalli** [comment]
fixed in: [PR 10984](https://github.com/NVIDIA/spark-rapids/pull/10984)
