### ISSUE TITLE
[FEA] Refine Spark UT Framework Part2: Use vectorized parameter to evaluate expressions where possible

### ISSUE THREAD

**Issue by binmahone** [NVIDIA/spark-rapids#10859]
This is a follow up issue of #10850

In #10850 ,  we proposed a simple and quick solution to to meet code freeze deadline.

The solution still has room for improvement as stated in https://github.com/NVIDIA/spark-rapids/pull/10851/files/aa23967c3f1b04124f464489c0998ae60c377c50#diff-05efb25cde1790862698b49252ef40c62afb031d869bbb85e51e280192b2fc1fR225

**Comment by tgravescs** [comment]
Please add a description of what this feature actually is then in description say its a followup from something.

**Comment by binmahone** [comment]
close this issue as it is solved by #10861
