### ISSUE TITLE
[FEA] Run nightly integration test on Azure Databricks 7.3 runtime

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#1085]
Run nightly integration tests on a multinode Azure Databricks cluster from our CI/CD pipeline.    For 0.3, the integration tests should run on Databricks 7.3.

**Comment by tgravescs** [comment]
note https://github.com/NVIDIA/spark-rapids/issues/502 added support for 7.3 and it added a jenkins files, so we just need to create a build based on it.
https://github.com/NVIDIA/spark-rapids/blob/branch-0.3/jenkins/Jenkinsfile.databricks301nightly

I tested it in the ci dev environment so it should be good.

**Comment by sameerz** [comment]
Tom's comment here was specific to AWS.  This issue is to make sure we test on Azure Databricks.

**Comment by NvTimLiu** [comment]
@sameerz Could you please share where I can access the Azure databricks cluster?

I suppose this one is for aws databricks only? https://dbc-9ff9942e-a9c4.cloud.databricks.com/?o=8721196619973675#setting/clusters . 
which I got from Tom's page: https://confluence.nvidia.com/display/SPARK/Developer+Docs

**Comment by sameerz** [comment]
Shared.

**Comment by NvTimLiu** [comment]
Blossom Jenkins created: https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/job/rapids_integration-AzureDatabricks/

Test scripts uploaded: https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/tree/main/databricks

Mark it closed
