### ISSUE TITLE
[FEA] Refine the test framework introduced in #10745

### ISSUE THREAD

**Issue by binmahone** [NVIDIA/spark-rapids#10850]
some offline feedbacks of https://github.com/NVIDIA/spark-rapids/issues/10745 shows that:

1. Many of the expression based suites are falling back to CPU execution even if the expression is already suppported in GPU, because RAPIDS does not support BoundReference(which UT test code will generate a lot) very well.
2. When falling back and Vanilla Spark's whole stage code gen is enabled (By default), compilation of generated code will fail because Vanilla Spark's UT did not pass enough type information for null fields
3. So they have to manually disable whole stage code gen to get such test case passed.

We think Item 3 is not a good idea, so we'll refine the framework to fix the root cause, i.e. Item 1 and Item 2

**Comment by jlowe** [comment]
@binmahone can you elaborate on what this is asking for?  It simply says "based on feedback of #10745," but when I go there, there's no feedback there.  Thus it's not clear what this is proposing to do or how one would know a PR stating it fixes it actually fixes it.

**Comment by binmahone** [comment]
@jlowe background updated in the issue description.
