### ISSUE TITLE
[FEA] Integration tests should stop immediately after failure.

### ISSUE THREAD

**Issue by liurenjie1024** [NVIDIA/spark-rapids#10853]
**Is your feature request related to a problem? Please describe.**

Currently we use `pytest` as our integration tests framework, which by default runs all tests without regarding task failure. In our long running ci, it should stop as long as some test failed.

**Describe the solution you'd like**

`pytest` accepts an `-x` argument to stop after test failure, we just need to add it to our test scripts.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by revans2** [comment]
Why? We have the tests continue after a failure so we can get a more complete picture of what failed. If a change broke 10 tests do you really want to run the test framework 10 times to find that out fixing each one of the tests one at a time?

**Comment by jlowe** [comment]
I agree with @revans2.  Most developers want to run the tests and know everything that's currently broken with their PR.  run_pyspark_from_build.sh will pass its command line arguments to pytest, so if a developer wants to stop at the first test failure ,they can pass -x on the command-line to stop the tests after the first test failure.
