### ISSUE TITLE
[BUG] Qualification tool labels app run on Databricks as Not Applicable because of failed stages but there were cancelled

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#10869]
**Describe the bug**
I ran an event log through the qualification tool and it got labelled as not applicable because it had failed stages. Those failed stages though were cancelled by AQE runs.

We should take this into account in the qual tool.  

The reasons in task show up as: Stage cancelled... 
The stage failure reason shows: Job 243 cancelled

**Comment by amahussein** [comment]
Can we please move this to rapids-user-tools repo?

**Comment by tgravescs** [comment]
closing in favor of https://github.com/NVIDIA/spark-rapids-tools/issues/1032
