### ISSUE TITLE
[FEA] Explore NVIDIA MPS Daemon for pytest-xdist testing

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1089]
I have not tested this but it has been suggested that we could reduce the context switch overhead by using the NVIDIA MPS daemon to avoid some overhead in the tests.  I am a little skeptical how much this will speed things up because from what I have seen we tend to be more CPU bound than GPU bound most of the time, but I don't know for sure where the slowness in the context switches manifest themselves.

**Comment by jlowe** [comment]
Agree, I don't think the additional complexity of setting up MPS is worth it.
