### ISSUE TITLE
[BUG]Cast from string to float using hand-picked values failed in CastOpSuite

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#10986]
**Describe the bug**
Cast from string to float using hand-picked values in CastOpSuite is failing in latest nightly build.
Failure seen on all Spark version so it doesn't look any Spark version specific.

```
- Cast from string to float using hand-picked values *** FAILED ***
07:12:29    Mismatch casting string [+nAn] to FloatType. CPU: null; GPU: NaN (CastOpSuite.scala:244)
```

**Comment by res-life** [comment]
Both nightly JDK11 and JDK17 shows this error.

**Comment by firestarman** [comment]
it is breaking the premerge build now

**Comment by Feng-Jiang28** [comment]
Cauased by https://github.com/NVIDIA/spark-rapids-jni/pull/2063, I will fix it.
