### ISSUE TITLE
[FEA] Persist/unpersist support

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#11]
**Is your feature request related to a problem? Please describe.**
cache/persist/unpersist can take a very long time. It would be great to GPU accelerate this.

**Describe the solution you'd like**

Cache stores data that can exist between different jobs, some of which might have GPU acceleration disabled. So, for now we will need to keep the same storage format and same storage locations (host memory/disk) when we cache the data. That means what we can do is write kernels that can transform rapids data to/from the Spark specific format. If this works well we can probably do a SPIP to add in more plugable support, both for storage location, so we can keep it in GPU memory, and for the format.

The basic format for most of what we care about is a NOOP.

byte, short, int, long, float, double all are just as we store them right now.

Strings are a 32-bit length followed by the contents of the string as UTF8 repeated for each string.  I suspect that this is going to be hard to decode on the GPU, but possibly not too bad to encode it.

Decimals that we don't support yet are the raw 64-bit representation of a decimal.  If it does not fit in 64 bits then it is a different format, which we will probably not support in the first version of decimal so we are okay.

 Nulls are very odd though. They don't use a validity buffer or anything like that.  They are a separate array of 32 bit integers.  The first is the null count, and all the others are the indexes of which entries are null.

 
There are several different options for compression too.  If compression is enabled by the config `spark.sql.inMemoryColumnarStorage.compressed`

Spark will pick a compression scheme that fits with the data type being compressed and that offers the best compression. If none of the schemes are supported for this data type or non of the compression schemes think that they will compress the data, then if falls back to PassThrough compression, which is essentially a NOOP.

Boolean -> BitSetE

- ncoding
- Int, Long, String -> Dictionary Encoding
- Int -> IntDelta
- Long -> LongDelta
- Int, Long, Short, Byte, String, Boolean -> RLE

So the final output format looks like

 

NULL_COUNT | NULL_ARRAY | COMPRESSION_ID | PAYLOAD 
---------------------|---------------------|-----------------------------|----------------
 32 - bits           | NC * 32-bits     | 32 - bits                     | ???           

So for this to work at a minimum we are going to need something that can convert our null encoding to/from the spark null encoding, and a way to convert to/from the string format.

After that we can start to add in support for the different compression techniques.  I would not have our version on by default until we can support all of the compression techniques.  The issue is that because so many of these formats are spark specific we likely will not be able to put them into cudf itself, and will need to work out how to make some spark specific kernels.   It is doable, but work that we have not done yet.

**Comment by sameerz** [comment]
This is superseded by issue #444.
