### ISSUE TITLE
[BUG] numpy2 fail fastparquet cases: numpy.dtype size changed

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#11070]
**Describe the bug**
numpy has just released 2.0.0 to pip and conda, we found that it would fail our fastparquet cases (pip install on different ENV could result non-deterministic versions)

**py3.8/3.9** still use pandas 2.0.x + numpy 1.2x 
but **py3.10** use pandas 2.2.x + numpy 2.0
as pip install defaults. But all the defaults would eventually be upgraded to use numpy 2.0+

```
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

during ENV preparation
```
Downloading numpy-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.3 MB)

numpy==2.0.0
├── fastparquet==0.8.3 [requires: numpy>=1.18]
├── pandas==2.2.2 [requires: numpy>=1.22.4]
│   └── fastparquet==0.8.3 [requires: pandas>=1.1.0]
└── pyarrow==16.1.0 [requires: numpy>=1.16.6]
```

Please help determine if we should xfail the cases to wait for compatibility support (or adjust existing deps versions) or we explicitly limit numpy version to <2.0.0 for now

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**
Pass the tests with numpy2 

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by pxLi** [comment]
merged workaround https://github.com/NVIDIA/spark-rapids/pull/11072 to unblock CI

**Comment by amahussein** [comment]
We faced the same issue with the user-tools.
I submitted a fix that supports [3.8, 3.12] https://github.com/NVIDIA/spark-rapids-tools/pull/1128

**Comment by mythrocks** [comment]
It's been a while since I worked on `fastparquet`. 
My understanding is that we don't currently have a direct dependency on `numpy` (beyond the transitive dependency via `fastparquet`).  

One option might be an upgraded version of `fastparquet`.  Have we tried running the `fastparquet` compatibility tests with an updated version?

**Comment by pxLi** [comment]
according to https://github.com/numpy/numpy/issues/26191
the minimal required version of fastparquet should be `2024.5.0`, 

let me try to update all occurrences of `fastparquet == 0.8.3` or `fastparquet==0.8.3` in the repo to `2024.5.0` https://pypi.org/project/fastparquet/#history to verify it first

**Comment by pxLi** [comment]
BTW numpy2 and fastparquet both **Requires: Python >=3.9**, as the current spark still has py3.8 support. 

Please let me know if we still need to test fastparquet in py3.8 ENV (hardcode to 0.8.3 only in python3), or can we skip the cases while py3.8 as the version (0.8.3) we use could be too old to cover the current scenarios? cc @mythrocks @sameerz

**Comment by mythrocks** [comment]
@pxLi:  Sorry for the delayed response.  I suspect that the Python version will not have a material effect on the behaviour of fastparquet.  I'm +1 on this change to update to a new version.

If required, we can skip the tests when testing on 3.8.
