### ISSUE TITLE
[BUG] --help flag unusable spark_rapids_user_tools dataproc qualification 

### ISSUE THREAD

**Issue by matthewthekramer** [NVIDIA/spark-rapids#11085]
**Describe the bug**
The `--help` flag errors for the `spark_rapids_user_tools dataproc qualification` command
**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.
`spark_rapids_user_tools dataproc qualification --help`
**Expected behavior**
A printout of the available arguments for the qualification command
**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue
dataproc
**Additional context**
error message:
```
Processing...⣾2024-06-20 14:26:23,960 ERROR rapids.tools.qualification: Eventlogs list is empty. The cluster Spark properties may be missing "spark.eventLog.dir". Re-run the command passing "--eventlogs" flag to the wrapper.
2024-06-20 14:26:23,960 ERROR root: Qualification. Raised an error in phase [Process-Arguments]
```

**Comment by matthewthekramer** [comment]
Found the issue, fix:
`spark_rapids_user_tools dataproc qualification -- --help`

**Comment by amahussein** [comment]
Thanks @matthewthekramer for reaching out!
It is recommended to use the `spark_rapids` cmd  as the `spark_rapids_user_tools` is going to be deprecated soon.

https://docs.nvidia.com/spark-rapids/user-guide/24.06/qualification/quickstart.html#command-options

```
spark_rapids qualification -- --help
```

**Comment by amahussein** [comment]
@matthewthekramer let me know if you need any help with using the user-tools cmd.
There is a github repo for the user-tools. A couple of useful links:

- Quick start with the `spark_rapids qualification CLI`: https://docs.nvidia.com/spark-rapids/user-guide/latest/qualification/quickstart.html
- rapids-user-tools repo : https://github.com/NVIDIA/spark-rapids-tools/issues
