### ISSUE TITLE
[FEA] Adopt UCX 1.17

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#11104]
**Is your feature request related to a problem? Please describe.**
Adopt the UCX 1.17 bugfix release

**Describe the solution you'd like**
Upgrade from UCX 1.16 to UCX 1.17

**Describe alternatives you've considered**
N/A

**Additional context**
UCX 1.17 has additional configs for Grace Hopper: https://github.com/openucx/ucx/blob/004eadf7c9fde8378d77e0e122714d02001761a3/config/ucx.conf#L4

**Comment by abellina** [comment]
We should follow a similar set of diffs than what was done from 1.15 to 1.16 https://github.com/NVIDIA/spark-rapids/pull/10292 and we should install it in our clusters from the packages in https://github.com/openucx/ucx/releases/tag/v1.17.0

**Comment by zpuller** [comment]
Going to mark this as complete. I have done the following:

- upgrade to ucx 1.17 in spark rapids repo
- upgrade ucx libs on spark-egx-06 and verified that UCX tests pass
- upgrade ucx libs on spark2a and run ucx_perfest
- upgrade ucx libs on sparkgh and run NDS queries with UCX shuffle enabled
- build the sample docker images and run ucx_perftest on them

**Comment by sameerz** [comment]
Adding the `invalid` tag as this change was reverted.  We will target updating UCX when https://github.com/openucx/ucx/pull/9863 is merged into a UCX release.  That is likely to be UCX 1.18.
