### ISSUE TITLE
[BUG] Update nightly tests for Scala 2.13 to use JDK 17 only

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#11114]
As part of https://github.com/NVIDIA/spark-rapids/pull/10994 and to support Spark 4.0 using a single JDK we added a restriction for Scala 2.13 to be only built by JDK17.

We need to make sure the nightly tests all follow the above restriction

**Comment by NVnavkumar** [comment]
This is also important for the GCP Dataproc Serverless Platform as those environments are also all Scala 2.13/JDK17 only

**Comment by NvTimLiu** [comment]
For the nightly build and tests for scala2.13,
Nightly build: currently we build scala2.13 dist jar with JDK8, are we going to build the scala2.13 dist (start from spark-3.3.x to 4.0.x)  or only spark4.0 jar against JDK17?
Nightly tests: currently we run IT with JDK8 runtime, need we change to tests scala2.13 dist jar with JDK17 java runtime?

@razajafri

**Comment by NvTimLiu** [comment]
Discussing thread: https://github.com/NVIDIA/spark-rapids/pull/10994#issuecomment-2202424461

**Comment by NvTimLiu** [comment]
Close this issue, PR [11144 Build the Scala2.13 dist jar with JDK17](https://github.com/NVIDIA/spark-rapids/pull/11144) fixed it
