### ISSUE TITLE
[FEA] Separate Scala/Java "build" (JDK17 xcompiled to JDK8) from "test" steps run on JDK8

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#11121]
**Is your feature request related to a problem? Please describe.**
As we potentially embrace the approach from https://github.com/NVIDIA/spark-rapids/pull/10994#issuecomment-2195667822

It is necessary to separate the bytecode-producing from testing such that we can run integration tests (PyTests) and ScalaTests with JAVA_HOME pointing to JDK8 whereas the bytecode has been generated with JAVA_HOME pointing to JDK17 

Related to https://github.com/scalatest/scalatest-maven-plugin/issues/26

**Comment by NvTimLiu** [comment]
For Scala2.12 dist jar, we both build and test shims against JDK8(JAVA_HOME=8)，I think this is good for us


----------------------

For Scala2.13 dist jar, we're building shims with JDK17(JAVA_HOME=17 xcomplied to JDK8 bytecode), 
and we're running IT matrix : 334+343+351 X JDK17 

@gerashegalov  @razajafri  @jlowe  @sameerz Any thought what **matrix(spark shims X JDK versions X OS versions)** we'll need for Scala2.13 ITs?

**Comment by gerashegalov** [comment]
@NvTimLiu I would like to see at least one Scala 2.13 shim running tests with JDK8

**Comment by sameerz** [comment]
For OS versions, let's test against Ubuntu 22.04 and Rocky 8.

**Comment by NvTimLiu** [comment]
Thanks for your advices @gerashegalov  @sameerz 

Sounds good to me, let me update our Scala2.13 shims IT against JDK8 on Ubuntu 22.04 and Rocky 8.

I'll update the status here after the IT pipeline get updated, thanks!

**Comment by NvTimLiu** [comment]
Enabled nightly IT for the combination of "Rocky8 + JDK17", "Ubuntu22 + JDK8" environments.

**Comment by NvTimLiu** [comment]
Are there any other concerns, or are we good to close this issue? @sameerz  @gerashegalov  @jlowe 

Our nightly IT CI jobs with "Rocky8 + JDK17", "Ubuntu22 + JDK8" combinations have been done for a week

**Comment by sameerz** [comment]
No concerns, closing the issue.
