### ISSUE TITLE
[test] Add "select current_version();" to print version hashes in databricks runtimes

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#11195]
**Is your feature request related to a problem? Please describe.**
due to https://github.com/NVIDIA/spark-rapids/issues/11184

we may add spark.sql command to print "https://docs.databricks.com/en/sql/language-manual/functions/current_version.html#returns" while run test on databricks for debug purpose

**Describe the solution you'd like**
print `select current_version();` if databricks runtimes

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by mattahrens** [comment]
Dup of https://github.com/NVIDIA/spark-rapids/issues/8587
