### ISSUE TITLE
Handle cache for scala2.13 build dependencies

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#11199]
We need to handle caching of dependencies for Scala 213 builds in the GitHub workflows

_Originally posted by @gerashegalov in https://github.com/NVIDIA/spark-rapids/pull/10994#discussion_r1678823123_

**Comment by pxLi** [comment]
I take care of this later

**Comment by pxLi** [comment]
cc @YanxuanLiu to help

**Comment by YanxuanLiu** [comment]
> cc @YanxuanLiu to help

OK, I'll work on this issue
