### ISSUE TITLE
[DOC] Advanced_configs page is broken

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#11273]
## Report incorrect documentation

**Location of incorrect documentation**

https://github.com/NVIDIA/spark-rapids/blob/branch-24.08/docs/additional-functionality/advanced_configs.md

and search(CTRL+F) for string
```
We only support Databricks Runtime 13.3 and Deltalake 2.4.
```
Then you can find the content below this line is not in table format anymore.

![image](https://github.com/user-attachments/assets/c4e155fe-6b32-420e-a1e5-b8c4c17075a3)

**Comment by jlowe** [comment]
Looks like this was triggered by #10979.  Looks like the newlines added in the config description breaks the table entry.
