### ISSUE TITLE
[FEA] Enable Parquet DataSource tests in Spark UT on Spark 3.3.0

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#11297]
**Is your feature request related to a problem? Please describe.**
Enable Parquet DataSource tests in Spark UT on Spark 3.3.0.
It helps us to find the problems when reading Parquet as the data source.

**Describe the solution you'd like**
We already have enabled [some suites](https://github.com/NVIDIA/spark-rapids/tree/branch-24.08/tests/src/test/spark330/scala/org/apache/spark/sql/rapids/suites) in Spark 3.3.0.
We can add more suites in [datasources/parquet](https://github.com/apache/spark/tree/v3.3.0/sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/parquet).

**Comment by Feng-Jiang28** [comment]
closed by https://github.com/NVIDIA/spark-rapids/pull/11366

**Comment by wjxiz1992** [comment]
Not all suites in this [datasources/parquet](https://github.com/apache/spark/tree/v3.3.0/sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/parquet) are migrated, should we consider re-opening it? Or I should create new individual issue for each suite that has not been migrated?

**Comment by wjxiz1992** [comment]
## DataFrameSetOperationsSuite Migration Update

Migrated `DataFrameSetOperationsSuite` with the following results:

**Test Results**:
- Total tests: 39
- Passed: 38 (97.4%)
- Excluded: 1 (2.6%)

**Excluded Test**:
1. `SPARK-37371: UnionExec should support columnar if all children support columnar` - Test checks CPU-specific physical plan nodes (InMemoryTableScanExec, UnionExec) which differ in GPU execution

**Issue Created**: Will be filed as separate issue for tracking
