### ISSUE TITLE
[FEA] Support FIRST/LAST without grouping expressions

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#113]
**Is your feature request related to a problem? Please describe.**

The `FIRST` and `LAST` aggregate functions are supported when used in conjunction with grouping 
expressions but are not currently supported on the GPU in other cases.

For example, this is supported ...

```sql
SELECT dept, FIRST(first_name) FROM employee GROUP BY dept
```

... but this is not supported:

```sql
SELECT FIRST(first_name) FROM employee
```

**Describe the solution you'd like**
I would like to be able to use FIRST/LAST on the GPU without grouping expressions.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by jlowe** [comment]
This has been fixed.
