### ISSUE TITLE
[BUG] TIMESTAMP_MILLIS not handled in isDateTimeRebaseNeeded

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1130]
**Describe the bug**
Looks like we aren't properly handling spark.sql.legacy.parquet.datetimeRebaseModeInWrite=TIMESTAMP_MILLIS in isDateTimeRebaseNeeded when we run with spark.sql.parquet.outputTimestampType=EXCEPTION.

The good thing is it fails because of the assert at https://github.com/NVIDIA/spark-rapids/blob/6478c9700c05d83c16258d9e93b6bcf08605a3bd/sql-plugin/src/main/scala/com/nvidia/spark/RebaseHelper.scala#L40 
but it should be throwing a SparkUpgradeException instead.

Note from Bobby on this vs the existing MICROS handling:
it gets to be a little more difficult because spark only provides cutoff values in microseconds, because that is what all of the data types are written in.  The conversion to millis or what ever else for spark happens after this check has occurred.  I would think that we want to do the same thing, just so we don't have issues with trying to do the conversion on the CPU for the checks.

test that reproduced this is a new parquet_write_test I'm working on, should be something like:

====
```
def writeParquetCatchException(spark, df, data_path, spark_tmp_table_factory, ts_rebase, ts_write):
    spark.conf.set('spark.sql.legacy.parquet.datetimeRebaseModeInWrite', ts_rebase)
    spark.conf.set('spark.sql.parquet.outputTimestampType', ts_write)
    with pytest.raises(Exception) as e_info:
        df.coalesce(1).write.format("parquet").mode('overwrite').option("path", data_path).saveAsTable(spark_tmp_table_factory.get())
    assert e_info.match(r".*SparkUpgradeException.*")

parquet_ts_write_options = ['TIMESTAMP_MILLIS']

@pytest.mark.parametrize('ts_write', parquet_ts_write_options)
@pytest.mark.parametrize('ts_rebase', ['EXCEPTION'])
def test_ts_write_fails_datetime_exception(spark_tmp_path, ts_write, ts_rebase, spark_tmp_table_factory):
    gen = TimestampGen(start=datetime(1590, 1, 1, tzinfo=timezone.utc))
    data_path = spark_tmp_path + '/PARQUET_DATA'
    with_gpu_session(
            lambda spark : writeParquetCatchException(spark, unary_op_df(spark, gen), data_path, spark_tmp_table_factory, ts_rebase, ts_write))

```

**Comment by sameerz** [comment]
Agreed to change the `assert` to `require` as a short term fix.
