### ISSUE TITLE
[FEA] Spark3.1.0 test spark.sql.legacy.parquet.int96RebaseModeInRead

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1135]
**Is your feature request related to a problem? Please describe.**
Spark 3.1.0 added some configs for int96 rebase spark.sql.legacy.parquet.int96RebaseModeInRead and spark.sql.legacy.parquet.int96RebaseModeInWrite.  Make sure we support and test accordingly

**Comment by jlowe** [comment]
I think we need to support this ASAP, since we try to honor `spark.sql.legacy.parquet.datetimeRebaseModeInRead` and `spark.sql.legacy.parquet.datetimeRebaseModeInWrite` and these new INT96 configs override the old datetime versions when using INT96 timestamps.

**Comment by tgravescs** [comment]
reopen because reverted due to build failures and not up to date with latest shim changes:
https://github.com/NVIDIA/spark-rapids/pull/3627
