### ISSUE TITLE
[BUG] Missing numRows in the ColumnarBatch created in GpuBringBackToHost

### ISSUE THREAD

**Issue by jihoonson** [NVIDIA/spark-rapids#11364]
**Describe the bug**
`GpuBringBackToHost` creates the `ColumnarBatch` without `numRows`, which will be set to 0 in this case. This can confuse any logic relying on the `numRows `metric during the query processing, such as adaptive query optimizer. The `ColumnarBatch` returned would be always regarded as if it were an empty batch. 

**Expected behavior**
The right number of rows should be retrieved from the `hostColumns` and then set for the `ColumnarBatch` before it is returned.

**Comment by revans2** [comment]
@jihoonson great catch. Could you also check other places that we create a ColumnarBatch to be sure there are no other issues like this? The API is kind of bad because you can create a ColumnarBatch and then set the number of rows afterwards.

**Comment by jihoonson** [comment]
@revans2 I have checked other places, and did not see any. I agree that this API does not have the best design. I wonder if we should do something about it, such as adding safe wrappers, e.g., `rapids.ColumnarBatches.empty()` and `rapids.ColumnarBatches.create(ColumnVector[] columns, int numRows)`, and forbidding unsafe APIs.

**Comment by jihoonson** [comment]
Regarding forbidding the use of unsafe APIs, I meant that we could use the [forbidden API checker](https://github.com/policeman-tools/forbidden-apis) to catch them during the build.

**Comment by jihoonson** [comment]
Filed https://github.com/NVIDIA/spark-rapids/issues/11369.
