### ISSUE TITLE
[AUDIT] Handle IgnoreNulls Expressions for Window Expressions

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#11392]
As part of https://github.com/apache/spark/commit/80223bb190a there has been a change to simplify the Column API. 

As part of this change another Expression parameter is passed to `CaseWhen` `Lead` `Lag` etc which is then converted to a Boolean literal.

This may not be a very involved change as the only Expression allowed when writing this issue is a `BooleanLiteral` anything else will throw an Exception.

**Comment by sameerz** [comment]
@mythrocks can you please review this and see if it is a feature we need to implement, or do we need to write a test case for the plugin?

**Comment by mythrocks** [comment]
This will be a feature to implement.  It appears this will have an effect on existing window functionality, for all aggregations.

**Comment by mythrocks** [comment]
This looks like new functionality for LEAD/LAG.  Should not have impact on the other aggregations.

The CUDF LEAD/LAG aggregation will need modification, along with the rolling window implementation.  I'll have to think on how we might implement this without performance impact.

**Comment by revans2** [comment]
@mythrocks @sameerz I am really confused here https://issues.apache.org/jira/browse/SPARK-33443 added in LEAD/LAG ignore nulls/respect nulls in 3.2.0, which is the minimum we support. We don't need to support it fully we just need to fall back to the CPU if we see one that we cannot support.  This is not an audit issue, this is a bug/missed requirement from a long time ago.

**Comment by mythrocks** [comment]
>> This looks like new functionality for LEAD/LAG.

> this is a bug/missed requirement from a long time ago.

Sorry, yes.  I should have said that this will need new code in `libcudf`'s LEAD/LAG kernels, to skip nulls. Thank you for the correction, @revans2.  

@cindyyuanjiang has verified that this does fall back to CPU, if `IGNORE NULLS` is specified.  i.e. [this code](https://github.com/NVIDIA/spark-rapids/blob/branch-24.10/sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/OffsetWindowFunctionMeta.scala#L101) fires. (Thank you, @cindyyuanjiang.)

At the moment, all that comes to mind is the brute force approach to skip nulls.  We can take a crack at it, depending on priority.

**Comment by revans2** [comment]
This is an AUDIT issue. If we are falling back to the CPU, then we are doing the right thing. Did the default change in 4.0, or is there some other forcing factor that I don't know about? Otherwise there should be nothing to do.

**Comment by mythrocks** [comment]
> Did the default change in 4.0, or is there some other forcing factor...

No, this change should be fine.  Based on @cindyyuanjiang's testing on Spark 4.0, the plugin is compiling correctly, and falling back to the CPU in this case.  We should be fine.

I'll raise a separate issue to track support for implementing `IGNORE NULLS`.
