### ISSUE TITLE
[FEA] Support format 'yyyyMMdd' in GetTimestamp operator

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#11445]
**Is your feature request related to a problem? Please describe.**
From a customer, related settings are: 
```
spark.sql.legacy.timeParserPolicy=LEGACY
spark.rapids.sql.incompatibleDateFormats.enabled=true
```

**Describe the solution you'd like**
Maybe first convert `yyyyMMdd` to the format that cuDF supports.

**Comment by firestarman** [comment]
`DateFormatClass` is also missing the support of `yyyyMMdd` format.
```
!Expression <DateFormatClass> date_format(cast(date_sub(cast(gettimestamp(finish_date#3148, yyyyMMdd, TimestampType, Some(Asia/Shanghai), false) as date), 30) as timestamp), yyyyMMdd, Some(Asia/Shanghai)) cannot run on GPU because LEGACY format 'yyyyMMdd' is not supported on the GPU.
```

**Comment by res-life** [comment]
> `DateFormatClass` is also missing the support of `yyyyMMdd` format.
> 
> ```
> !Expression <DateFormatClass> date_format(cast(date_sub(cast(gettimestamp(finish_date#3148, yyyyMMdd, TimestampType, Some(Asia/Shanghai), false) as date), 30) as timestamp), yyyyMMdd, Some(Asia/Shanghai)) cannot run on GPU because LEGACY format 'yyyyMMdd' is not supported on the GPU.
> ```

Supported yyyyMMdd for date_format when it's **LEGACY** mode after the corresponding PR.

Below test passed:
```
def test_legacy_mode_yyyyMMdd_format():
    gen = StringGen("[0-9]{3}[1-9](0[1-9]|1[0-2])(0[1-9]|[1-2][0-9])")
    assert_gpu_and_cpu_are_equal_sql(
        lambda spark : unary_op_df(spark, gen),
        "tab",
        "SELECT  date_format(date_sub(to_date(a, 'yyyyMMdd'), 30), 'yyyyMMdd') AS formatted_date from tab",
        {
            'spark.sql.legacy.timeParserPolicy': 'LEGACY',
            'spark.rapids.sql.incompatibleDateFormats.enabled': True})
```

Related code:
```scala
(a, conf, p, r) => new UnixTimeExprMeta[DateFormatClass](a, conf, p, r) {
  ......
  override def convertToGpu(lhs: Expression, rhs: Expression): GpuExpression =
    GpuDateFormatClass(lhs, rhs, strfFormat, a.timeZoneId)
}

In UnixTimeExprMeta:
  strfFormat = DateUtils.tagAndGetCudfFormat(this,
    sparkFormat, expr.left.dataType == DataTypes.StringType)
```

**Comment by firestarman** [comment]
If `from_unixtime` works, I think, we are OK to revert this PR for `from_unixtime`.

**Comment by res-life** [comment]
> If `from_unixtime` works, I think, we are OK to revert this PR [#10023](https://github.com/NVIDIA/spark-rapids/pull/10023) for `from_unixtime`.

Seems PR [#10023](https://github.com/NVIDIA/spark-rapids/pull/10023) is for non-LEGACY mode.
This [PR](https://github.com/NVIDIA/spark-rapids/pull/11449) only handles `LEGACY`

**Comment by firestarman** [comment]
> Seems PR https://github.com/NVIDIA/spark-rapids/pull/10023 is for non-LEGACY mode.

No, it is for all the modes
