### ISSUE TITLE
Reconsider using `cd` in shell scripts if avoidable

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#11444]
I find the scripts relying on `cd` fragile. I prefer that all scripts are executed under a constant PWD. There is almost always a way to do it such as `mvn -f scala2.13`

From @NvTimLiu:

We use `cd scala2.13` in our build scripts/docs/CICD instead of `maven -f scala2.13` as below everywhere,

 do you think need we file a following up issue to the updating? @gerashegalov 

https://github.com/NVIDIA/spark-rapids/tree/branch-24.10/scala2.13#building-with-scala-213

https://github.com/NVIDIA/spark-rapids/blob/branch-24.10/build/buildall#L236

https://github.com/NVIDIA/spark-rapids/blob/branch-24.10/.github/workflows/mvn-verify-check.yml#L307

https://github.com/NVIDIA/spark-rapids/blob/branch-24.10/jenkins/spark-nightly-build.sh#L29

https://github.com/NVIDIA/spark-rapids/blob/branch-24.10/jenkins/spark-premerge-build.sh#L194

_Originally posted by @NvTimLiu in https://github.com/NVIDIA/spark-rapids/issues/11427#issuecomment-2335196874_

**Comment by NvTimLiu** [comment]
@gerashegalov Thanks for help creating the issue

I'm working on v24.10, I suppose the issue is not impact v24.10 release, 

Let me target it to 24.12, I'll handle it later, 

Thanks!
