### ISSUE TITLE
[FEA] Add in support for setting row group sizes for parquet

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#11442]
**Is your feature request related to a problem? Please describe.**
https://github.com/rapidsai/cudf/pull/16750 appears like it is going to change the default settings for parquet row groups in CUDF. We currently have no way to set these through java/scala and we should add that in so that we can maintain compatibility with Spark/move to new settings when we see/feel that it is ideal.

**Comment by ttnghia** [comment]
Closed by https://github.com/rapidsai/cudf/pull/16805.
