### ISSUE TITLE
[FEA] enable prune_columns for from_json

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#11458]
**Is your feature request related to a problem? Please describe.**
CUDF has a feature that was added for us to prune out columns that were not in the schema. We should enable this. It will give us some performance boost, but not nearly as much as it will in the future when it is done and the pruning happens on the device side.

**Comment by mattahrens** [comment]
Dependency: https://github.com/rapidsai/cudf/issues/16797

**Comment by revans2** [comment]
This was done as a part of 24.10
