### ISSUE TITLE
[BUG] spark400 build failed do not conform to class UnaryExprMeta's type parameter

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#11479]
**Describe the bug**

It appears that Spark 400 has updated the function signature. We have seen 2 occurrences today,
https://github.com/NVIDIA/spark-rapids/actions/runs/10918070452/job/30303402686
https://github.com/NVIDIA/spark-rapids/actions/runs/10915156719/job/30294484216

```
Error: ] /home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:2406: 
type arguments [org.apache.spark.sql.catalyst.expressions.Rand] 
do not conform to class UnaryExprMeta's type parameter bounds 
[INPUT <: org.apache.spark.sql.catalyst.expressions.UnaryExpression]
```

**Steps/Code to reproduce bug**
build with spark400

**Expected behavior**
Pass the build and test

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by pxLi** [comment]
related to change https://github.com/apache/spark/pull/48004

**Comment by abellina** [comment]
I am taking a look
