### ISSUE TITLE
[AUDIT][SPARK-46037][SQL] Correctness fix for Shuffled Hash Join build left without codegen

### ISSUE THREAD

**Issue by parthosa** [NVIDIA/spark-rapids#11488]
**Describe the bug**
This PR fixe a join correctness bug for Shuffled Hash Join build left. We should check our implementation in `GpuHashJoin`

https://github.com/apache/spark/commit/af5e0a267e5

**Comment by mattahrens** [comment]
The plugin doesn't execute with codegen off so this doesn't impact us.
