### ISSUE TITLE
[BUG] IT script failed get jars as we stop deploying intermediate jars since 24.10

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#11502]
**Describe the bug**
first seen in rapids_integration-scala213-dev-github run:248

as we stop deploying intermediate jars https://github.com/NVIDIA/spark-rapids/pull/11301
the https://github.com/NVIDIA/spark-rapids/blob/branch-24.10/jenkins/spark-tests.sh#L40-L59 would fail to find required pom files due to mvn get process (many trivial checks)

lets refactor them to use wget to fetch required jars directly for nightly spark-tests script in 24.12

**Steps/Code to reproduce bug**
jenkins/spark-tests.sh

**Expected behavior**
download required jars correctly

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by NvTimLiu** [comment]
working on the issue
