### ISSUE TITLE
[BUG]Add databricks 3.0.1 shim layer for GpuWindowInPandasExec.

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1151]
**Describe the bug**
https://github.com/NVIDIA/spark-rapids/pull/1124 added shim layers but missed the spark301db for databricks runtime 7.3. We need to add this as the tests are failing.

**Comment by tgravescs** [comment]
@firestarman I assume this is fixed by https://github.com/NVIDIA/spark-rapids/pull/1152?
please make sure to link when the pr is put up so this gets closed

**Comment by firestarman** [comment]
closed
