### ISSUE TITLE
Fix orc_test.py on Databricks 14.3

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#11528]
Build the plugin against Databricks 14.3 cluster using #11467. Once built successfully run the ORC tests by `TESTS=orc_test.py jenkins/databricks/test.sh` 

The following tests fail 
```
[gw0] [ 77%] FAILED ../../src/main/python/orc_test.py::test_project_fallback_when_reading_hive_fixed_length_char
```

**Comment by mythrocks** [comment]
Investigating this one.  This might just be another skip, just like on 13.3.
