### ISSUE TITLE
Fix JSON Matrix tests on Databricks 14.3

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#11533]
Build the plugin against the Databricks 14.3 cluster using #11467. Once built successfully run the JSON matrix tests by `TESTS=json_matrix_test.py jenkins/databricks/test.sh` 

The following tests fail 
```
[gw3] [ 38%] FAILED ../../src/main/python/json_matrix_test.py::test_from_json_long_structs
[gw3] [ 38%] FAILED ../../src/main/python/json_matrix_test.py::test_scan_json_long_structs
```

**Comment by mythrocks** [comment]
I have filed https://github.com/NVIDIA/spark-rapids/issues/11711 for the change in behaviour of `from_json` on Databricks 14.3.  This will need version-specific handling.

**Comment by revans2** [comment]
Generally what I have been doing for JSON matrix, and I think is the proper course is to split up data for tests that are failing so we can continue to have coverage for the parts that work and mark the ones that fail with a clear error message so we know what is happening there.

In the case of #11711, I don't know what the priority is going to end up being so splitting up the tests is probably the best way to get around the issue. I also don't think that #11711 is really all that much of a blocker. There are very few cases where a top level null is going to be treated differently from a struct with two nulls in them.
