### ISSUE TITLE
Fix String tests on Databricks 14.3

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#11535]
Build the plugin against the Databricks 14.3 cluster using #11467. Once built successfully run the String tests by `TESTS=string_test.py jenkins/databricks/test.sh` 

The following tests fail 
```
[gw3] [ 95%] FAILED ../../src/main/python/string_test.py::test_startswith
```

**Comment by mythrocks** [comment]
This failure should be addressed by #11669.
