### ISSUE TITLE
[FEA] Reimplement $ transpilation using cuDF new line terminator support

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#11554]
**Is your feature request related to a problem? Please describe.**

cuDF added support for multiple new-line characters in https://github.com/rapidsai/cudf/pull/15961, which allows support for the different Java unicode line terminator characters. This requires passing a flag to the cuDF regex APIs to enable this mode, and updating the transpiler to a more simplified implementation of $ (which only needs to add support for the `\r\n` combination in addition to the individual characters already supported by cuDF:

* `\n` line-feed (already supported)
* `\r` carriage-return
* `\u0085` next line (NEL)
* `\u2028` line separator
* `\u2029` paragraph separator

**Additional context**

This might fix failing tests here:
* https://github.com/NVIDIA/spark-rapids/issues/10641
* https://github.com/NVIDIA/spark-rapids/issues/9731

Also, can look into a possible solution for:
* https://github.com/NVIDIA/spark-rapids/issues/10764

**Comment by SurajAralihalli** [comment]
We should start by adding `EXT_LINE` to the `RegexFlag.java` file to enable support for multiple newline characters to JAVA APIs, as introduced in https://github.com/rapidsai/cudf/pull/15961. See [RegexFlag.java, line 27](https://github.com/rapidsai/cudf/blob/98eef67d12670bd592022201b3c9dcc12374a34a/java/src/main/java/ai/rapids/cudf/RegexFlag.java#L27), small adjustments will be needed in the cuDF repo.

After this, we can begin migrating the Spark Regex APIs. This involves updating the transpiler function in the `RegexParser` to remove the workaround used for previous cuDF’s multiple line delimiter limitation, see [RegexParser.scala#L850](https://github.com/NVIDIA/spark-rapids/blob/b5c28681cb81eaf4863b3a29d41ac7cd9373eb92/sql-plugin/src/main/scala/com/nvidia/spark/rapids/RegexParser.scala#L850). Additionally, we must modify all Spark GPU Regex API expressions, such as `GpuRegExpExtract`, to incorporate cuDF’s fix. See [stringFunctions.scala#L1419:GpuRegExpExtract](https://github.com/NVIDIA/spark-rapids/blob/b5c28681cb81eaf4863b3a29d41ac7cd9373eb92/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala#L1419).

**Comment by wjxiz1992** [comment]
follow-up for the two-char `\r\n` case that the single-char EXT_NEWLINE work (#15961) left out: rapidsai/cudf#22762 + PR rapidsai/cudf#22763. lets us drop the residual `(\r\n)?` transpile too.
