### ISSUE TITLE
[BUG] Fix regression supporting to_date on GPU with Spark 3.1.0

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#1157]
**Describe the bug**
Prior to Spark 3.1.0, `to_date` gets translated to `CAST(unix_timestamp(expr, format, timezone) AS date)` which we support on GPU, but since 3.1.0 it instead gets translated to `CAST(gettimestamp(expr, format, timezone) AS date)` which we do not support on GPU.

**Steps/Code to reproduce bug**
Remove the `execsAllowedNonGpu` from the relevant tests in com.nvidia.spark.rapids.ParseDateTimeSuite

**Expected behavior**
We should support to_date on GPU with 3.1.0 by supporting `gettimestamp` on GPU.

**Comment by tgravescs** [comment]
reference https://github.com/apache/spark/commit/75d342858a71293b7c2cbbd5cec2eb417ed3852c
this was an optimiation which really changed it from 
Cast(SecondsToTimestamp(UnixTimestamp(left, format)), DateType)) to
Cast(GetTimestamp(left, format), DateType))

I'm moving this to a P1 as I thought we had a lot of queries using to_date, if not we should move back to p2

**Comment by tgravescs** [comment]
I think we have everything we need to implement this.

Note we could knock back down to P2  since spark.rapids.sql.castStringToTimestamp.enabled is off by default.
