### ISSUE TITLE
[BUG] Spark 4.0 build failure - value cannotSaveIntervalIntoExternalStorageError is not a member of object org.apache.spark.sql.errors.QueryCompilationErrors

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#11611]
**Describe the bug**
Spark 4.0.0 Scala 2.13 nightly build is failing with:
` [ERROR] [Error] /home/jenkins/agent/workspace/jenkins-rapids_scala213_nightly-dev-github-290/sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuDataSource.scala:126: value cannotSaveIntervalIntoExternalStorageError is not a member of object org.apache.spark.sql.errors.QueryCompilationErrors`

Looks like Spark 4.0 removed that function - https://github.com/apache/spark/commit/560748c2b1482836f1fbc117ebb88cee1371554c

We need to create a shim for that file.

**Comment by jlowe** [comment]
PR is up at #11610
