### ISSUE TITLE
[BUG] likely leak in device memory

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#1168]
I am seeing that RMM memory is increasing after two tries for one of the TPCDS queries. I expect memory to go back to some known initial quantity. Normally that's ~500MBs, but in this query:

We start at:
```
20/11/19 21:27:17 WARN GpuShuffleEnv: RMM alloc 536870912. Device store amnt: 0
```

Then after iteration 1 completes (and we have unregistered shuffle):
```
20/11/19 21:27:44 WARN GpuShuffleEnv: RMM alloc 912163328. Device store amnt: 0
```

After iteration 2 completes (also after shuffle is unregistered):
```
20/11/19 21:28:32 WARN GpuShuffleEnv: RMM alloc 1293498880. Device store amnt: 0
```

Finally we OOM after this case. This is with the RAPIDS shuffle. But if a query fit on iteration 1 it should fit in the next iteration, provided we cleaned up everything that needed to be cleaned up.

**Comment by abellina** [comment]
At this point this has been attributed to accumulating broadcast, and broadcast derived batches (during a join). So this is a known issue somewhat.

The solution is to make the broadcast spillable, since we can't control the lifetime of the broadcast in spark. We also want to figure out how to deal with the projections from this broadcast variable, as we are seeing this data size get fairly large in comparison with the original batch that was broadcasted.

**Comment by jlowe** [comment]
So do we close this as a duplicate of #836 ?

**Comment by abellina** [comment]
Yes that works for me. The slight difference is that so far the broadcast variable size << than the rest of the memory used when using the broadcast variable to produce inputs into the join. So I'll just carry this to the other issue.
