### ISSUE TITLE
[BUG] 24.12 Precommit fails with wrong number of arguments in `GpuDataSource`

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#11684]
**Describe the bug**
Precommit build fails with the following error for PRs targeted to 24.12 

```
/home/runner/work/spark-rapids/spark-rapids/sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuDataSource.scala:87: wrong number of arguments for pattern org.apache.spark.sql.execution.datasources.LogicalRelation(relation: 
org.apache.spark.sql.sources.BaseRelation, output: Seq[org.apache.spark.sql.catalyst.expressions.AttributeReference], catalogTable: Option[org.apache.spark.sql.catalyst.catalog.CatalogTable], isStreaming: Boolean, stream: Option[org.apache.spark.sql.connector.read.streaming.SparkDataStream])
```
This looks related to Spark 4. 0 changes. 

I am unable to reproduce this locally -- will update when I can 

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by gerashegalov** [comment]
To repro locally run:

JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64  mvn verify -f scala2.13  -Dbuildver=400  -DskipTests

Spark 4.0.0 needs dedicated Shimming recently
