### ISSUE TITLE
[AUDIT][SPARK-48348][SPARK-48376][SQL] Introduce LEAVE and ITERATE statements

### ISSUE THREAD

**Issue by cindyyuanjiang** [NVIDIA/spark-rapids#11686]
Spark introduced two new statements - `LEAVE` and `ITERATE`. We should check if we want to support them.

https://github.com/apache/spark/commit/9676b1c48cb

**Comment by revans2** [comment]
I think that these are a part of SQL scripting, which sits outside of the normal sql that we typically support on the GPU.
