### ISSUE TITLE
[BUG] Getting empty data if there is array type data in the input of GpuWindowInPandas .

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#1171]
**Describe the bug**
The plan `GpuWindowInPandas ` will return empty data if there is array type data in the input and referred by Python UDF.
Looks like the cuDF arrow IPC writer could not deal with array type correctly for now.

**Expected behavior**
The plan should return the correct data.

**Additional context**
This is low priority since we plan to support ArrayType only for Python UDF output now. Filed this issue to track this bug.

**Comment by sameerz** [comment]
Need to create a reproduceable case and to file a follow up against cudf.

**Comment by jlowe** [comment]
@firestarman is this still an issue?

**Comment by firestarman** [comment]
> @firestarman is this still an issue?

I verified it and it should be no longer an issue now. I add tests for it by https://github.com/NVIDIA/spark-rapids/pull/10275.
