### ISSUE TITLE
[BUG] Orc writes don't fully support Booleans with nulls

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#11736]
**Describe the bug**
Customer reported a job failing with the error:

`Caused by: ai.rapids.cudf.CudfException: CUDF failure at: /home/jenkins/agent/workspace/jenkins-spark-rapids-jni-release-39-cuda11/thirdparty/cudf/cpp/src/io/orc/[writer_impl.cu](http://writer_impl.cu/):940: There's currently a bug in encoding boolean columns. Suggested workaround is to convert to int8 type. Please see https://github.com/rapidsai/cudf/issues/6763 for more information.
`

as the error suggests it points to https://github.com/rapidsai/cudf/issues/6763, which states that cudf doesn't support writing booleans with nulls that don't align on 8 bit boundaries.  It requires writing at least 2 row groups where the first rows group has doesn't fully align with 8 bits and leaves unused bits.

**Comment by tgravescs** [comment]
We either need to fix the cudf issue or fallback to the CPU if the plugin detects this.

**Comment by kuhushukla** [comment]
Also related on the tests side of things -- https://github.com/NVIDIA/spark-rapids/issues/11735

**Comment by kuhushukla** [comment]
I will stopgap this with a fallback fix in a PR soon and open a follow on for actual support.
