### ISSUE TITLE
[FEA] Update rapids JNI and private dependency version to 25.02.0-SNAPSHOT

### ISSUE THREAD

**Issue by nvauto** [NVIDIA/spark-rapids#11755]
Keep the rapids JNI and private dependency version at 24.12.0-SNAPSHOT until the nightly CI for the branch-25.02 branch is complete.

**Comment by pxLi** [comment]
@YanxuanLiu @NvTimLiu please help close if the issue is done, thanks

**Comment by YanxuanLiu** [comment]
Fixed in https://github.com/NVIDIA/spark-rapids/pull/11772
