### ISSUE TITLE
[BUG] mismatch CPU and GPU result in test_months_between_first_day[DATAGEN_SEED=1733006411, TZ=Africa/Casablanca]

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#11798]
**Describe the bug**
first seen in rapids_it-non-utc-dev, run:277

failed cases,
```
src.main.python.date_time_test.test_months_between_first_day[DATAGEN_SEED=1733006411, TZ=Africa/Casablanca]
src.main.python.date_time_test.test_months_between_last_day[DATAGEN_SEED=1733006411, TZ=Africa/Casablanca, INJECT_OOM]
src.main.python.date_time_test.test_months_between_first_day_round[DATAGEN_SEED=1733006411, TZ=Africa/Casablanca, APPROXIMATE_FLOAT]
src.main.python.date_time_test.test_months_between_last_day_round[DATAGEN_SEED=1733006411, TZ=Africa/Casablanca, INJECT_OOM, APPROXIMATE_FLOAT]
```

the value,
```
AssertionError: GPU and CPU float values are different [1062, "months_between(a, TIMESTAMP '2024-01-01 00:00:00', false)"]
...
cpu = -86.0433927, gpu = -86.04473678
float_check = <function get_float_check.<locals>.<lambda> at 0x7faaf72f2a70>
path = [1062, "months_between(a, TIMESTAMP '2024-01-01 00:00:00', true)"]
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by revans2** [comment]
Okay so it looks like I am calculating the months diff the same as the CPU, but when we get to calculate the seconds within a day to compute a sub-month difference then I calculate the day value incorrectly. I am rounding down to the start of a day using the timestamp that was converted to a different time zone. But if there is a time zone transition between the timestamp and the start of the day, the UTC calculation to round down is not going to be correct. I am not 100% sure how to do this for another time zone, so I am going to just restrict this to only UTC for now and file a follow on issue to understand how to do it properly for other time zones.

**Comment by pxLi** [comment]
follow up at https://github.com/NVIDIA/spark-rapids/issues/11800
