### ISSUE TITLE
[FEA] Support TruncDate expression

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#11804]
**Is your feature request related to a problem? Please describe.**
```
   ! <TruncDate> trunc(cast(my_field#860 as date), MM) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.TruncDate
```
**Describe the solution you'd like**
Customer query shows this fallback, timezone is UTC and GMT

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by revans2** [comment]
@kuhushukla So is it only 'MM' ('MONTH') that is needed? 

https://spark.apache.org/docs/latest/api/sql/index.html#date_trunc supports

   * YEAR
   * QUARTER
   * MONTH
   * WEEK
   * DAY
   * HOUR
   * MINUTE
   * SECOND
   * MILLISECOND
   * MICROSECOND

DAY and below we should be able to support with existing CUDF operators. Beyond that it is probably best if we write a custom kernel for most of it. We could come up with a way to put together a string representation of the timestamp we need by extracting year, month, day, etc and parsing it back with CUDF, but that feels really wasteful. I would rather just do it in a kernel ourselves based on the same kind of logic.

**Comment by kuhushukla** [comment]
Currently I have only encountered month. I can update further in the next couple days, but MM would be a good start for the customer query in question.

**Comment by ttnghia** [comment]
Fun facts:
 * `trunc(date, fmt)` is used for date type, while `date_trunc(fmt, timestamp)` is used for timestamp type.
 * They have opposite order of parameters.

**Comment by ttnghia** [comment]
I changed my plan: will try to support all. This is a binary expression, and `fmt` can only be checked at run time, not planning time. As such, if we don't fully support it we won't be able to fallback but will throw exception.

**Comment by revans2** [comment]
@ttnghia it is perfectly acceptable for us to only support a scalar `fmt`, and in those cases we can check it a planning time. That is what we do for all of the regular expression commands.

In the type checks you can mark a type as `TypeSig.lit`

https://github.com/NVIDIA/spark-rapids/blob/738c8e38fc23c1634667443864b80f085f2737ac/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala#L3352-L3361

That makes it so we would fall back for anything that is not a literal value. Then you can use some pattern matching APIs to pull out the value.

https://github.com/NVIDIA/spark-rapids/blob/738c8e38fc23c1634667443864b80f085f2737ac/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala#L582-L587

**Comment by ttnghia** [comment]
That is fine. I've completed the implementation to support all, as it is fairly simple.
