### ISSUE TITLE
[BUG] Generated files for `spark350db143` are missing and incomplete

### ISSUE THREAD

**Issue by cindyyuanjiang** [NVIDIA/spark-rapids#11815]
**Describe the bug**
[/tools/generated_files/350db143](https://github.com/NVIDIA/spark-rapids/tree/branch-24.12/tools/generated_files/350db143) should contain supported CSV files. It is missing `operatorScore.csv`, `supportedExecs.csv`, `supportedExprs.csv`, and the only existing `supportedDataSource.csv` in the folder is empty. These files should be automatically generated by the build.

**Comment by gerashegalov** [comment]
@cindyyuanjiang if it is for 24.12 , DBR 14.3 is not building for the release. It will "come back" for 25.02 #11749

**Comment by mattahrens** [comment]
Closing as dup of https://github.com/NVIDIA/spark-rapids/issues/11749
