### ISSUE TITLE
[AUDIT] Support Hive 4.0 metastore

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#11831]
**Is your feature request related to a problem? Please describe.**
There are few PR's merged in Spark-4.0 branch to support Hive 4.0 metastore. Filing the issue to check if we need to do something to support this in the plugin.

Apache Spark changes:
https://github.com/apache/spark/pull/43064
https://github.com/apache/spark/pull/45801
https://github.com/apache/spark/pull/48823

**Comment by mythrocks** [comment]
This took a little bit of time to investigate.  It doesn't look like there are any `spark-rapids` changes necessitated by the Spark changes.

`spark-rapids` works through Apache Spark's `HiveClientImpl` only.  The support for 4.0 should work behind the scenes.
