### ISSUE TITLE
[BUG] test_window_aggregate_udf_array_from_python fails on databricks 3.0.1

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1184]
**Describe the bug**
test_window_aggregate_udf_array_from_python test is failing on databricks.

11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[No_Partition-Byte][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[No_Partition-Short][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[No_Partition-Integer][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Unbounded-Byte][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Unbounded-Short][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Unbounded-Integer][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Unbounded_Following-Byte][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Unbounded_Following-Short][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Unbounded_Following-Integer][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Unbounded_Preceding-Byte][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Unbounded_Preceding-Short][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Unbounded_Preceding-Integer][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Lower_Upper-Byte][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Lower_Upper-Short][IGNORE_ORDER]
11:37:59  FAILED src/main/python/udf_test.py::test_window_aggregate_udf_array_from_python[Lower_Upper-Integer][IGNORE_ORDER]

**Comment by firestarman** [comment]
not sure how long it wil take to fix this strange issue,  for now xfail these tests by this PR https://github.com/NVIDIA/spark-rapids/pull/1191 , but keep this issue open untill finding the root cause and fixing the faliures.
