### ISSUE TITLE
[FEA] kernel for date_trunc and trunc that has a scalar format

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#11860]
**Is your feature request related to a problem? Please describe.**
The current implementation of trunc and date_trunc use a kernel where the format is a column.

This works great. In my tests I saw a 180x speedup over the CPU (16 cores).  But we could save a lot of memory if the format is a scalar, which I think is the most common case.

In the best case where the format string is "DD", a new kernel we would save about 6 bytes per row of input. On a date that is 150% increase in memory usage. For a timestamp that is only a 75% increase in memory usage.  But for the worst case on a date it is "QUARTER" or a 275% increase in memory usage. For a timestamp it is "MICROSECOND", which would be 187.5% increase in memory usage.  This is probably minor, but it would be nice.

**Comment by ttnghia** [comment]
The current JNI implementation is already optimized for memory. Although the scala is promoted into a column, such column has only one row thus there is no change in memory usage.

However, I agree that we can optimize further in term of performance. Currently, a column format is parsed when processing every row. We can do better by parsing the scalar format (on host) before calling the kernel, saving time for the GPU by not doing so again. I'll post a JNI PR shortly.
