### ISSUE TITLE
[AUDIT][SPARK-47009][SQL] Enable create table support for collation

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#11872]
See https://github.com/apache/spark/commit/298134fd5e9#diff-393a0ad195d66fb094f2dca3669c1317b7f57a6637f6e95241b57bc6550ce49a

There are some updates to Cast here. Since StringType requires a collation parameter, any pattern match that checks for `StringType` would need to instead check for `_: StringType` to handle the new definition, plus should fallback to CPU in case the collation is not the UTF8 default.

**Comment by NVnavkumar** [comment]
See https://github.com/NVIDIA/spark-rapids/issues/10687

**Comment by mattahrens** [comment]
Plugin doesn't support collation
