### ISSUE TITLE
[BUG] LIKE does not work if null chars are in the string

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#119]
**Describe the bug**
This is a very odd corner case, but if a null char '\0' is in the string like sees it as the end of the string.  So 'A\0FOO BAR' will  match '_'.  This is a very odd and rare corner case so we probably can ignore it for now, but we need to have it documented. I think this impacts all cudf regular expressions and we need to probably file a follow on issue with them to look into it.

**Comment by sameerz** [comment]
Need to document this behavior for the 0.2 release.  The fix / change can be in a subsequent release.

**Comment by revans2** [comment]
I filed https://github.com/rapidsai/cudf/issues/6196 for this.
