### ISSUE TITLE
[BUG] No data size in Input column in Stages page from Spark UI when using Parquet as file source

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#1199]
**Describe the bug**
No data size numbers are shown in the `input` column in `Stages` page from Spark UI. like:
![image](https://user-images.githubusercontent.com/20476954/100175172-d84b7600-2f08-11eb-8627-acf8dff4848f.png)

**Steps/Code to reproduce bug**
```
scala> df = spark.read.csv("/data/mortgage/parquet-data")
df: org.apache.spark.sql.DataFrame = [_c0: string, _c1: string ... 26 more fields]
scala> df.count()
20/11/25 10:11:27 WARN package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
res0: Long = 2058241
```

**Expected behavior**
I can see input data size in Input column in Stages page. like:
![image](https://user-images.githubusercontent.com/20476954/100174418-5c9cf980-2f07-11eb-835a-7215415c8aa5.png)

**Environment details (please complete the following information)**
 - Environment location: Local mode
 - Spark configuration settings related to the issue

```
export CUDF=/home/allen/.m2/repository/ai/rapids/cudf/0.17-SNAPSHOT/cudf-0.17-SNAPSHOT-cuda10-1.jar
export PLUGIN=/home/allen/work/github/spark-rapids/dist/target/rapids-4-spark_2.12-0.3.0-SNAPSHOT.jar

$SPARK_HOME/bin/spark-shell --master local[6] \
--driver-memory 35G \
--conf spark.sql.warehouse.dir="${OUT}" \
--conf spark.sql.catalogImplementation=in-memory \
--jars ${CUDF},${PLUGIN} \
--conf spark.executor.extraClassPath=${CUDF}:${PLUGIN} \
--conf spark.driver.extraClassPath=${CUDF}:${PLUGIN} \
--conf spark.plugins=com.nvidia.spark.SQLPlugin \
--conf spark.driverEnv.LIBCUDF_KERNEL_CACHE_PATH=$CTMP \
--conf spark.executorEnv.LIBCUDF_KERNEL_CACHE_PATH=$CTMP \
--conf spark.rapids.sql.exec.CollectLimitExec=true \
--conf spark.rapids.sql.explain=ALL \
--conf spark.rapids.sql.udfCompiler.enabled=false \
--conf spark.rapids.memory.gpu.allocFraction=0.8 \
--conf spark.rapids.memory.gpu.pooling.enabled=true \
--conf spark.rapids.memory.pinnedPool.size=4G \
--conf spark.executor.extraJavaOptions="-Dai.rapids.cudf.prefer-pinned=true" \
--conf spark.executor.resource.gpu.amount=1 \
--conf spark.rapids.sql.variableFloatAgg.enabled=true \
--conf spark.rapids.sql.incompatibleOps.enabled=true

```

**Additional context**
git pos: commit b2f03e0eae642c7999122c00127cd045627520dc (HEAD, origin/branch-0.3)

This bug doesn't happen to CSV files, I think you can repro this case with any parquet files.

**Comment by jlowe** [comment]
This is tied to the multithreaded readers added in #677.  Setting spark.rapids.sql.format.parquet.reader.type=PERFILE fixes the issue.  Spark's input metrics setup by DataSourceRDD assume the current thread is the one performing the filesystem reads, but that's not the case when using multithreaded readers.
