### ISSUE TITLE
[FEA] Accelerate the scan speed for coalescing parquet reader when reading files from multiple partitioned folders

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#1200]
**Is your feature request related to a problem? Please describe.**
When reading parquet data from a "well" partitioned dataset, the GPU scan takes longer than CPU:
![image](https://user-images.githubusercontent.com/20476954/100176240-e1d5dd80-2f0a-11eb-97a7-088596abe60b.png)
![image](https://user-images.githubusercontent.com/20476954/100176264-ebf7dc00-2f0a-11eb-942b-88d4c5a05610.png)

There're totally 10,200 files in my job but the log `Partition values for the next file ...` appeared 9700+ times. I'm not sure if the scan really benift from the "parallel" reader.
![image](https://user-images.githubusercontent.com/20476954/100176440-3e38fd00-2f0b-11eb-8016-281f8554e428.png)

**Comment by tgravescs** [comment]
the use case here is reading from hdfs, correct? Did you try forcing the multi-threaded reader?

**Comment by tgravescs** [comment]
try setting spark.rapids.sql.format.parquet.reader.type="MULTITHREADED"

**Comment by wjxiz1992** [comment]
> try setting spark.rapids.sql.format.parquet.reader.type="MULTITHREADED"

Thanks. This type helps. Closing this feature.

**Comment by tgravescs** [comment]
that is purely a work around. There is still a performance problem with coalesce with partitioned files that we can improve so reopening this
