### ISSUE TITLE
[QST]When will spark-rapids for ML be released for trial use?

### ISSUE THREAD

**Issue by YeahNew** [NVIDIA/spark-rapids#1230]
**What is your question?**
The rapids library has implemented many ML methods through the cuml module, but currently it is not possible to call cuml through spark-rapids. I know that you have been working hard to open up this area, and I have been paying attention to this. So I want to know how the progress is, and when will the ML feature be released? Even just implement some simple Logistics Regression and K-means algorithms.
In addition, I wonder if you are considering re-implementing rapids or cuml through scala or java for use in the form of jar packages. The use of rapids is just like directly importing the corresponding module in python.
Looking forward to your answer.

**Comment by krajendrannv** [comment]
Hi, I have a couple of clarifying questions:
1. Are you looking to use SparkMLlib APIs that leverages cuML algorithm similar to Spark-rapids leveraging cuDF?
2. If not, are you looking to use cuML libraries inside a Spark cluster, similar to this blog post (https://medium.com/rapids-ai/managing-and-deploying-high-performance-machine-learning-models-on-gpus-with-rapids-and-mlflow-753b6fcaf75a)? 
Thanks
Karthik

**Comment by YeahNew** [comment]
> 
> 
> Hi, I have a couple of clarifying questions:
> 
>     1. Are you looking to use SparkMLlib APIs that leverages cuML algorithm similar to Spark-rapids leveraging cuDF?
> 
>     2. If not, are you looking to use cuML libraries inside a Spark cluster, similar to this blog post (https://medium.com/rapids-ai/managing-and-deploying-high-performance-machine-learning-models-on-gpus-with-rapids-and-mlflow-753b6fcaf75a)?
>        Thanks
>        Karthik

Yes，I want to use the cuml library, similar to spark-rapids calling cudf. Instead of using cuml through python.

**Comment by krajendrannv** [comment]
Thanks for the clarification. 
This has not been our priority so far primarily because we haven't got any customer requests for this feature. 
Let me do some due diligence to understand the effort level on this request.

**Comment by SHUIGUYU** [comment]
> Thanks for the clarification.
> This has not been our priority so far primarily because we haven't got any customer requests for this feature.
> Let me do some due diligence to understand the effort level on this request.

Thank you for your reply, so you have not considered providing ML plugin to accelerate SPARK ML via cuml of rapids.

**Comment by jlowe** [comment]
This is now a separate project, see https://github.com/NVIDIA/spark-rapids-ml
