### ISSUE TITLE
[BUG] CSV/JSON Parsing some float values results in overflow

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#124]
**Describe the bug**
Parsing `-3.4028234663852886e+38` as a  float32 results in `-Inf`.

**Steps/Code to reproduce bug**
There is an integration test added for this.

**Expected behavior**
It should parse to the corresponding supported value.

**Comment by wbo4958** [comment]
Json reader also has the same issue. Changed the title
