### ISSUE TITLE
[FEA] Add spark.sql.caseSensitive integration tests

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1255]
There should be integration tests that verify the handling of the `spark.sql.caseSensitive` config for the Parquet and ORC readers.

**Comment by andygrove** [comment]
These tests have already been implemented:

- parquet_test.py / test_parquet_read_case_insensitivity
- orc_test.py / test_read_with_more_columns
- csv_test.py / test_csv_read_case_insensitivity
