### ISSUE TITLE
[FEA] jars should be published to Github releases page

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1257]
**Is your feature request related to a problem? Please describe.**
Some users are using the Github releases page, like [the releases page for the 0.2 release](https://github.com/NVIDIA/spark-rapids/releases/tag/v0.2.0), to download the plugin jars.  The jars aren't available there, and the links to download the artifacts are not prominent in the documentation (e.g.: no links to downloads off of the README where many would expect to find it).  It should not be difficult to find the artifacts of a release.

**Describe the solution you'd like**
Minimally the plugin jars should be linked to the Github releases page as another artifact.  We should also discuss if we should attach or link to cudf jars as well.

I'd also like to see links to the download page be more prominent in the documentation.  Links to the download page should be easy to find on the README page, and the download page should be probably called `Download` rather than `Version`.

**Comment by sameerz** [comment]
A link to the jars for 0.3.0 is published on the release page: https://github.com/NVIDIA/spark-rapids/releases
