### ISSUE TITLE
[FEA] Update build pipelines for Spark 3.1.0, add pipeline for Spark 3.2.0

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1277]
**Is your feature request related to a problem? Please describe.**
Apache Spark recently created `branch-3.1` in the Spark repository in preparation for burndown to the official Apache Spark 3.1.0 release.

**Describe the solution you'd like**
Our builds that track Apache Spark 3.1.0-SNAPSHOT will need to be updated to track the new branch.
In addition we should add a pipeline to track and test against Apache Spark 3.2.0-SNAPSHOT.

**Comment by NvTimLiu** [comment]
The nvspark/spark nvmaster branch is for Apache Spark 3.2.0-SNAPSHOT.
The nvspark/spark nv-branch3.0 branch is for Apache Spark 3.0.2-SNAPSHOT. 

So we need a new nv-branch3.1 mirroring Apache Spark branch3.1 for 3.1.0-SNAPSHOT.

**Comment by GaryShen2008** [comment]
@jlowe Do we need a nv-branch-3.1.0 with an auto-merge job from upstream's branch-3.1.0?

**Comment by tgravescs** [comment]
yes and we will have to pull in the build script changes

**Comment by NvTimLiu** [comment]
create nv-branch-3.1 : https://gitlab-master.nvidia.com/nvspark/spark/-/tree/nv-branch-3.1

**Comment by NvTimLiu** [comment]
Build scripts merged to nv-branch-3.1
MR to create NGCC pipeline: https://gitlab-master.nvidia.com/ngcc/cicd/infra/-/merge_requests/691

**Comment by NvTimLiu** [comment]
Pipelines are on NGCC now. @jlowe @tgravescs, could we close the this issue? 

spark-3.0.2 SNAPSHOT pipeline:  https://ci.ngcc.nvidia.com/job/spark/job/spark3.0_nightly
spark-3.1.0 SNAPSHOT pipeline:  https://ci.ngcc.nvidia.com/job/spark/job/spark3.1_nightly/
spark-3.2.0 SNAPSHOT pipeline: https://ci.ngcc.nvidia.com/job/spark/job/sparkmaster_nightly/

**Comment by jlowe** [comment]
Yes, I think this is done.  Thanks, @NvTimLiu!
