### ISSUE TITLE
ParquetCachedBatchSerializer allocates a bunch of Tables upfront. 

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#1286]
This has the drawback of creating a bunch of leakable resources up front. I believe this will be easier to maintain and read if we construct the one table we need to perform the write then close that table rather than creating them all up-front first.  The code that writes a single table can be refactored into a separate method so it's easy to call from this split case and the non-split case rather than needing to fall-through to common-code.

_Originally posted by @jlowe in https://github.com/NVIDIA/spark-rapids/pull/1265#discussion_r536442577_

**Comment by kuhushukla** [comment]
May I suggest renaming the pr title to :
`ParquetCachedBatchSerializer allocates a bunch of Tables upfront. `
