### ISSUE TITLE
[FEA]Add tests for reading and writing to delta on Databricks

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1314]
**Is your feature request related to a problem? Please describe.**
We need more integration tests to test the reading and writing of delta files on Databricks to make sure plugin working properly with it.

for instance #1197

**Comment by revans2** [comment]
We probably should do this for open source delta as well. It is just a jar that we download and add as a plugin like our own.

**Comment by sameerz** [comment]
Adding a list of other issues related to Delta testing:

- [ ] https://github.com/NVIDIA/spark-rapids/issues/5977
- [ ] https://github.com/NVIDIA/spark-rapids/issues/5978
- [ ] https://github.com/NVIDIA/spark-rapids/issues/5966
