### ISSUE TITLE
[FEA] Explore support for DECIMAL32

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1317]
**Is your feature request related to a problem? Please describe.**
Currently the very limited decimal support that we have is all built around DECIMAL64 it would be great if we could start to also support DECIMAL32 as it would save memory in the long term.  The big issue is making sure that we don't hit any corner cases with overflow when trying to use a DECIMAL32, and also updating the code that goes to/from rows so that we get the correct type back.

**Comment by razajafri** [comment]
Is being addressed by #1717

**Comment by sameerz** [comment]
@razajafri can this be closed?

**Comment by razajafri** [comment]
Yes, I thought adding [this](https://github.com/NVIDIA/spark-rapids/issues/1317#issuecomment-778391264) will close it automatically.

**Comment by jlowe** [comment]
> Yes, I thought adding this will close it automatically.

Github doesn't recognize that syntax.  Simply mentioning a PR won't close it.  It needs to be of the form "Fixes #...", "Closes #...", "Resolves #...", etc. to trigger the automatic close behavior.  https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
