### ISSUE TITLE
[FEA] Support Parquet Read of Decimal FIXED_LENGTH_BYTE_ARRAY

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1324]
**Is your feature request related to a problem? Please describe.**

https://github.com/rapidsai/cudf/issues/6909 was filed to support reading FIXED_LENGTH_BYTE_ARRAY decimal values.  Older versions of Spark store decimal this way so we do want to support this before we can merge decimal reading support.

https://github.com/NVIDIA/spark-rapids/pull/1294 is a PR that covers most of reading decimal, but not everything.

**Comment by sperlingxx** [comment]
I am willing to take this task to support reading FIXED_LENGTH_BYTE_ARRAY decimal values if necessary.

**Comment by sperlingxx** [comment]
I think we can close this issue because corresponding [cuDF side task](https://github.com/rapidsai/cudf/pull/6969) has been merged. And I have manually verified this feature with spark-rapids.

**Comment by sameerz** [comment]
@sperlingxx do we have automated integration test cases to read FIXED_LENGTH_BYTE_ARRAY decimal values?

**Comment by revans2** [comment]
This appears to be done
