### ISSUE TITLE
[FEA] Support Decimal Casts

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1330]
**Is your feature request related to a problem? Please describe.**
Cudf supports casting decimal to/from double, float, int, long, etc.  We should support these too.  We need to be careful to test double/float especially because there can be round off issues that we need to test to see if they are correct.

**Comment by sameerz** [comment]
Tagging @sperlingxx on this issue.

**Comment by sameerz** [comment]
PR #1438 addresses casting with the exception of decimal to decimal casts, we need one more PR to address decimal to decimal casting.
