### ISSUE TITLE
Optimize unnecessary columnar->row->columnar transitions with AQE

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1341]
**Is your feature request related to a problem? Please describe.**
Sometimes AQE processing can lead to a query plan with what appears to be a degenerate columnar->row->columnar transition like this:
![image](https://user-images.githubusercontent.com/1360766/101564968-b4207800-3991-11eb-9de8-4d1dc544d778.png)

It would be great if this wasteful transition between formats could be avoided, keeping the data on the GPU throughout.

**Describe the solution you'd like**
Plugin transition overrides recognizes this situation and removes unnecessary transitions when possible.

**Comment by viadea** [comment]
Here is one minimum reproduce which can trigger similar issue when AQE is on:

```
val df = Seq(1).toDF()
df.write.format("parquet").mode("overwrite").save("/tmp/testaqe")
spark.read.parquet("/tmp/testaqe").createOrReplaceTempView("df")
# No GpuColumnarToRow or GpuRowToColumnar
val out=spark.sql("select value from df group by value")
out.write.format("parquet").mode("overwrite").save("/tmp/testaqe_out")
 
# When ACQ is on, one pair of GpuColumnarToRow or GpuRowToColumnar is introduced.
spark.conf.set("spark.sql.adaptive.enabled", true)
out.write.format("parquet").mode("overwrite").save("/tmp/testaqe_out")
```

Basically to trigger this I need to make sure all of below 3 requirements are met:

- AQE is on
- There is aggregation before writing to parquet files
- Write to parquet files eventually

**Comment by andygrove** [comment]
I've been investigating this and I think it is pretty likely that we will want to modify Spark by adding the following methods to AdaptiveSparkPlanExec:

```scala
override def supportsColumnar: Boolean = initialPlan.supportsColumnar

override protected def doExecuteColumnar(): RDD[ColumnarBatch] = {
  val rdd = getFinalPhysicalPlan().executeColumnar()
  finalPlanUpdate
  rdd
}
```

I am working on getting one example working end to end based on this.

**Comment by andygrove** [comment]
The `supportsColumnar` is tricky because we need it to be based on the final physical plan rather than the initial plan but we don't want a call to this method to trigger creating the final plan. I'll know more once I get the initial test working.

**Comment by andygrove** [comment]
I was able to get the test case to work by adding this method to Spark's AdaptiveSparkPlanExec:

```scala
def doExecuteMaybeColumnar(): Either[RDD[ColumnarBatch], RDD[InternalRow]] = {
  val plan = getFinalPhysicalPlan()
  if (plan.supportsColumnar) {
    val rdd = plan.executeColumnar()
    finalPlanUpdate
    Left(rdd)
  } else {
    val rdd = plan.execute()
    finalPlanUpdate
    Right(rdd)
  }
}
```
