### ISSUE TITLE
[BUG] Host columnar decimal conversions are failing

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1348]
As reported in #1279 and #1280 there are issues converting columnar host decimals to GPU decimals.  Those issues were "fixed" by disabling the decimal type by default, but the root cause needs to be investigated and fixed.

**Comment by revans2** [comment]
Found the bug.  In our conversion code we passed in the full 64 bit precision, but that the onheap column vector could store the data as a 32 bit value, which is why we got the errors.

I'll put up a fix tomorrow.
