### ISSUE TITLE
[BUG] mergeSchema on ORC reads does not work

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#135]
**Describe the bug**
This is a lot like #60 but for ORC files.  If you try to use `mergeSchema` or provide your own reader schema that has more columns than the orc file does it results in an error.

**Steps/Code to reproduce bug**
an integration test is being added for this.

**Comment by revans2** [comment]
Marking this for us to look at again because it is related to #5445 in parquet.

**Comment by firestarman** [comment]
Here is the feature list I can think of to support user specified schema.

1. Add columns missing in the file.
2. Remove columns being not required but existing in the file.
3. Reorder columns according to the read schema.
4. Support casting between compatible types. Here is [full type casting list](https://github.com/apache/orc/blob/main/java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java#L2204-L2325) we need to support.
