### ISSUE TITLE
Improve GpuRangePartitioning implementation

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#1355]
**Is your feature request related to a problem? Please describe.**

As mentioned in the conversation on https://github.com/NVIDIA/spark-rapids/pull/1350 there is no point in passing a `GpuRangePartitioner` into `GpuRangePartitioning` and we should clean this code up, Also, `GpuRangePartitioning` has an unused `rangeBounds` variable that can be removed.

**Comment by sameerz** [comment]
Completed by @revans2
