### ISSUE TITLE
[FEA] Add support for array_contains

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#1372]
**Is your feature request related to a problem? Please describe.**
Once the following cudf issues are done, we can add the plugin side changes for array_contains operator. 
   - [x] https://github.com/rapidsai/cudf/issues/6983
   - [x] https://github.com/rapidsai/cudf/issues/6944

**Comment by sameerz** [comment]
@kuhushukla assigning you on this issue for the plugin side work.
