### ISSUE TITLE
[FEA] Support new operators on the GPU

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#1374]
**Is your feature request related to a problem? Please describe.**
This issue tracks a number of sub-features that would add functionality in the plugin towards several customer queries with the operators listed below.
- [ ] array_contains 
   - [ ] https://github.com/rapidsai/cudf/issues/6944 
   - [ ] https://github.com/rapidsai/cudf/issues/6983 
   - [ ] https://github.com/NVIDIA/spark-rapids/issues/1372

- [ ] Hive UDF for urlDecoder 
   - [ ] https://github.com/rapidsai/cudf/pull/6972
   - [ ] https://github.com/NVIDIA/spark-rapids/issues/1352

- [ ] get_json_object 
   - [ ] https://github.com/rapidsai/cudf/issues/6985
   - [ ] https://github.com/rapidsai/cudf/issues/6986 
   - [ ] https://github.com/NVIDIA/spark-rapids/issues/166

**Comment by sameerz** [comment]
Closing as we will track the related issues separately.
