### ISSUE TITLE
[DOC] Benchmark docs need updating for spark-shell usage of TpcdsLikeBench

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#1379]
## Report incorrect documentation

**Location of incorrect documentation**
docs/benchmarks.md

**Describe the problems or issues found in the documentation**
```scala
scala> import com.nvidia.spark.rapids.tests.tpcds.TpcdsLikeBench
import com.nvidia.spark.rapids.tests.tpcds.TpcdsLikeBench
scala> val benchmark = new BenchmarkRunner(TpcdsLikeBench)
<console>:36: error: not found: value TpcdsLikeBench
       val benchmark = new BenchmarkRunner(TpcdsLikeBench)
```

**Steps taken to verify documentation is incorrect**
See above output from following the documentation.

**Suggested fix for documentation**

Update docs to reflect that `TpcdsLikeBench` is now a class with a parameter rather than an object. 

```scala
 val benchmark = new BenchmarkRunner(new TpcdsLikeBench(appendDat = true | false))
```

**Comment by sameerz** [comment]
@andygrove is this something that needs fixing in the 0.3 docs?  If not let's target it for our upcoming sprint.
