### ISSUE TITLE
[FEA] Faster transition from columns to rows

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#14]
**Is your feature request related to a problem? Please describe.**
The current columnar to row conversion code pulls back columnar data to the CPU and then walks through it.  We have seen a lot of issues with this and the cache.  It can be a real performance issue.

In the past we tried to create the unsafe row format for fixed width types using a cuda kernel and it worked.  The problem was that it used up a lot of memory. It might be good to explore some kind of a hybrid approach where we can create a more compressed row based format that can very easily be expanded out into unsafe row on the fly on the CPU, possibly using some code generation.

**Comment by sameerz** [comment]
Duplicate of #507
