### ISSUE TITLE
[BUG] spark-rapids 0.4.0-SNAPSHOT/cuDF 0.18-SNAPSHOT pytests on Databricks failed with "Could not initialize class com.nvidia.spark.rapids.GpuOverrides

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#1417]
**Describe the bug**
spark-rapids 0.4.0-SNAPSHOT/cuDF 0.18-SNAPSHOT pytests on Databricks failed with "Could not initialize class com.nvidia.spark.rapids.GpuOverrides"

Pipeline : https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/job/rapids_integration-AzureDatabricks/30/console
Test scripts: https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/blob/main/databricks/pytests-on-databricks.sh
Databricks cluster: https://adb-6905323869956636.16.azuredatabricks.net/?o=6905323869956636#setting/clusters/1119-070346-folio178/configuration

16:24:48  src/main/python/csv_test.py ssssssssssssssssssssssssFFFFFFFFFxxxFFFFFFFF [ 30%]
16:24:50  FFxxxF20/12/17 08:24:52 ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
16:24:50  java.lang.NoClassDefFoundError: Could not initialize class com.nvidia.spark.rapids.GpuOverrides$
16:24:50  	at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:2440)
16:24:50  	at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:2436)
16:24:50  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1(Columnar.scala:518)
16:24:50  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1$adapted(Columnar.scala:517)
16:24:50  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
16:24:50  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
16:24:50  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
16:24:50  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:517)
16:24:50  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:482)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$1(QueryExecution.scala:406)
16:24:50  	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
16:24:50  	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
16:24:50  	at scala.collection.immutable.List.foldLeft(List.scala:89)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution$.prepareForExecution(QueryExecution.scala:406)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:139)
16:24:50  	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:171)
16:24:50  	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:836)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:171)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:135)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:131)
16:24:50  	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.com$nvidia$spark$rapids$ExecutionPlanCaptureCallback$$captureIfNeeded(Plugin.scala:220)
16:24:50  	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.onFailure(Plugin.scala:302)
16:24:50  	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:153)
16:24:50  	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
16:24:50  	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
16:24:50  	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
16:24:50  	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
16:24:50  	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
16:24:50  	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:84)
16:24:50  	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
16:24:50  	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
16:24:50  	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
16:24:50  	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
16:24:50  	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
16:24:50  	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1523)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
16:24:50  20/12/17 08:24:52 ERROR Utils: throw uncaught fatal error in thread spark-listener-group-shared
16:24:50  java.lang.NoClassDefFoundError: Could not initialize class com.nvidia.spark.rapids.GpuOverrides$
16:24:50  	at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:2440)
16:24:50  	at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:2436)
16:24:50  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1(Columnar.scala:518)
16:24:50  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1$adapted(Columnar.scala:517)
16:24:50  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
16:24:50  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
16:24:50  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
16:24:50  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:517)
16:24:50  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:482)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$1(QueryExecution.scala:406)
16:24:50  	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
16:24:50  	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
16:24:50  	at scala.collection.immutable.List.foldLeft(List.scala:89)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution$.prepareForExecution(QueryExecution.scala:406)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:139)
16:24:50  	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:171)
16:24:50  	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:836)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:171)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:135)
16:24:50  	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:131)
16:24:50  	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.com$nvidia$spark$rapids$ExecutionPlanCaptureCallback$$captureIfNeeded(Plugin.scala:220)
16:24:50  	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.onFailure(Plugin.scala:302)
16:24:50  	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:153)
16:24:50  	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
16:24:50  	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
16:24:50  	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
16:24:50  	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
16:24:50  	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
16:24:50  	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:84)
16:24:50  	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
16:24:50  	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
16:24:50  	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
16:24:50  	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
16:24:50  	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
16:24:50  	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1523)
16:24:50  	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
16:24:50  Exception in thread "spark-listener-group-shared" java.lang.NoClassDefFoundError: Could not initialize class com.nvidia.spark.rapids.GpuOverrides$
16:24:51  	at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:2440)
16:24:51  	at com.nvidia.spark.rapids.GpuOverrides.apply(GpuOverrides.scala:2436)
16:24:51  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1(Columnar.scala:518)
16:24:51  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$1$adapted(Columnar.scala:517)
16:24:51  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
16:24:51  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
16:24:51  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
16:24:51  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:517)
16:24:51  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:482)
16:24:51  	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$1(QueryExecution.scala:406)
16:24:51  	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
16:24:51  	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
16:24:51  	at scala.collection.immutable.List.foldLeft(List.scala:89)
16:24:51  	at org.apache.spark.sql.execution.QueryExecution$.prepareForExecution(QueryExecution.scala:406)
16:24:51  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:139)
16:24:51  	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
16:24:51  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:171)
16:24:51  	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:836)
16:24:51  	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:171)
16:24:51  	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:135)
16:24:51  	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:131)
16:24:51  	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback$.com$nvidia$spark$rapids$ExecutionPlanCaptureCallback$$captureIfNeeded(Plugin.scala:220)
16:24:51  	at com.nvidia.spark.rapids.ExecutionPlanCaptureCallback.onFailure(Plugin.scala:302)
16:24:51  	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:153)
16:24:51  	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
16:24:51  	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
16:24:51  	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
16:24:51  	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
16:24:51  	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
16:24:51  	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:84)
16:24:51  	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
16:24:51  	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
16:24:51  	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
16:24:51  	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
16:24:51  	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
16:24:51  	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
16:24:51  	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
16:24:51  	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
16:24:51  	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
16:24:51  	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
16:24:51  	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
16:24:51  	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1523)
16:24:51  	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
16:25:06  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF [ 32%]
16:25:21  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF [ 34%]
16:25:24  FFFFFFFFFFFFFE                                                           [ 34%]

**Comment by tgravescs** [comment]
I manually built the repo and tests run fine.  I tried the same jars this integration build uses and it fails so I'm guessing theere is something wrong with those jars

**Comment by tgravescs** [comment]
I think this is jar mismatch, older databricks jar got pulled into newer spark rapids jar, rebuilding everything

**Comment by tgravescs** [comment]
latest build failed fo rknown issue and this error is gone. 
I think the databricks jar got built against an older version of the source code (before the change to Gpuoverrides for the documentation). That  mismatched when the newer code was built and just pulled in the prebuilt databricks jar.
