### ISSUE TITLE
[BUG] make shuffle exchange consistent error is wrong

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1429]
**Describe the bug**
https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala#L518

inside the makeShuffleConsistent() we return an error that says join needs to be on both when really it should be shuffle.

throw new IllegalStateException("Join needs to run on CPU but at least one input " +
            "query stage ran on GPU")

**Comment by sameerz** [comment]
@tgravescs can you confirm this error message was changed?  Or does this not need to be fixed / changed?  

https://github.com/NVIDIA/spark-rapids/blob/a61debcbb851b7139bb67d2873591d70a22d5675/sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsMeta.scala#L518

**Comment by tgravescs** [comment]
the error is actually fine, I misread originally.
