### ISSUE TITLE
[FEA]Improve the file reading by using local file caching

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#1435]
**Is your feature request related to a problem? Please describe.**
For a case of loading the same data files from remote data source by multiple times, it'll be significantly improved if there's a local file caching mechanism.

**Describe the solution you'd like**
[Alluxio](https://docs.alluxio.io/os/user/stable/en/Overview.html) is an open source project, which can do the exact caching thing for this case. We'd like to use Alluxio as the file caching service working with our plugin to provide a solution for the case of frequent remote reading.
We'd like to optimize the file reading and partitioning in our plugin according to the core of Alluxio.

Tasks:
- [x] Productionize plugin to work with different filesystems(AWS, Azure, GCP, DBFS)
- [ ] Create tests for Alluxio with different filesystems
- [x] Create a user guide for Alluxio settings
- [x] Verify Alluxio can run in an on-prem cluster

**Comment by wbo4958** [comment]
For now, we have merged PR https://github.com/NVIDIA/spark-rapids/pull/1562 for the V1 data source. And we will discuss if we need to add alluxio support for the V2 data source. So for now, just close the issue. I will re-open an another issue if we have plans to support V2 data source.

**Comment by tgravescs** [comment]
please open an issue to track the v2 data source, we can prioritize it as needed
