### ISSUE TITLE
[FEA] Add EMR integration test build to build  against EMR jars

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1440]
**Is your feature request related to a problem? Please describe.**
This relates to https://github.com/NVIDIA/spark-rapids/issues/1423 where on failure we hit an incompatibility with the EMR spark code and our plugin code.  This shouldn't be an issue with the official EMR release rapids jars because they build against their own jars.   
We should create a jenkins job that builds against their jars and run tests so that we are testing like EMR will so we can catching any issues early.

**Describe the solution you'd like**
1) Create an EMR cluster
2) checkout the spark rapids code
3) do the build once to download all the apache spark jars into the .m2
3) install the emr jars into the .m2 as if they are the apache spark 3.0.1 jars - see example script here: https://github.com/tgravescs/spark-rapids/blob/emrLikeFix/jenkins/install-emr - but install them into version 3.0.1 instead of 3.0.1-emr
4) rebuild the spark rapids jars and now it will build against the emr spark jars.
5) run the integration tests using the jars built above.

**Comment by tgravescs** [comment]
@GaryShen2008

**Comment by GaryShen2008** [comment]
@tgravescs 
We just need to run the build and test on EMR cluster. And it won't be included into our release pipeline, will it?

**Comment by tgravescs** [comment]
that is correct we won't include it in the release jars.

**Comment by NvTimLiu** [comment]
I'm checking this issue.

**Comment by NvTimLiu** [comment]
@tgravescs 
I've built and run integration tests on EMR cluster, here I have to 2 questions
1, Do we need to enable AQE for the integration tests `--conf spark.sql.adaptive.enabled=true` ?
2, I only run the pytest integraion, and it’s complicated to setup conda ENV on EMR cluster to run `cudf_udf` so I did not run `cudf_udf` tests: https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/jenkins/spark-tests.sh#L107

**Comment by NvTimLiu** [comment]
As my understanding, we also need a Blossom pipeline to run EMR build and IT nightly, right?

**Comment by tgravescs** [comment]
1) yes we should try to run with the same configs as EMR has by default, which means that is on, those should be picked up by default if you are using their spark version, can you verify?
2) That is fine we don't need to run cudf_udf here

Yes we should keep the blossom pipeline as well that uses our jar built against spark 3.0.1.

**Comment by NvTimLiu** [comment]
On 3.0.1 AQE is disable by default: https://github.com/apache/spark/blob/v3.0.1/docs/sql-performance-tuning.md
Enabled it with  --conf spark.sql.adaptive.enabled=true

**Comment by tgravescs** [comment]
yes but the EMR configs should have it on by default so if we are pointing to their configs it should be on.  Please verify that vs us setting as we really want to run with their configs

**Comment by NvTimLiu** [comment]
@tgravescs, I searched the spark config in the EMR cluster node  file (dir: /usr/lib/spark/conf) but did not found AQE enable configure in it, so I manually enabled it by --conf spark.sql.adaptive.enabled=true

Now the pipeline run 'mvn build' with Unit tests, and pytest IT on the 3.0.1 EMR cluster here:  https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/Testing/job/tim-Rapids-build-IT-on-EMR/

**Comment by NvTimLiu** [comment]
[MR39](https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/merge_requests/39) merged
https://blossom.nvidia.com/sw-gpu-spark-jenkins/job/rapids_build-on-EMR/

Suppose we can close this issue, there are still some optimizations, which we can make changes to later.
