### ISSUE TITLE
[BUG] Databricks 0.4 parquet integration tests fail

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1456]
**Describe the bug**
the integration tests on databricks in the parquet_test are failing with not everything on the GPU. We need to check to see if something we changed in 0.4 changed this. One thing to check on is the AQE fix for the shuffles.

06:59:10  E   pyspark.sql.utils.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.ColumnarToRowExec

06:59:10  FAILED src/main/python/parquet_test.py::test_read_round_trip[-reader_confs0-read_parquet_sql-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp, Array(Byte), Array(Long), Array(String), Array(Date), Array(Timestamp), Array(Decimal(18,0)), Array(Array(Byte)), Struct(['child0', Array(Byte)],['child1', Byte],['child2', Float],['child3', Decimal(18,0)]), Array(Struct(['child0', String],['child1', Double],['child2', Integer])), Map(String(not_null),String), Map(String(not_null),Array(String)), Map(RepeatSeq(not_null)(Integer(not_null)),Long), Map(Boolean(not_null),Boolean), Map(String(not_null),Map(String(not_null),String)), Decimal(18,0), Decimal(7,3), Decimal(10,10), Decimal(9,0), Decimal(18,15)]]
06:59:10  FAILED src/main/python/parquet_test.py::test_read_round_trip[-reader_confs1-read_parquet_sql-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp, Array(Byte), Array(Long), Array(String), Array(Date), Array(Timestamp), Array(Decimal(18,0)), Array(Array(Byte)), Struct(['child0', Array(Byte)],['child1', Byte],['child2', Float],['child3', Decimal(18,0)]), Array(Struct(['child0', String],['child1', Double],['child2', Integer])), Map(String(not_null),String), Map(String(not_null),Array(String)), Map(RepeatSeq(not_null)(Integer(not_null)),Long), Map(Boolean(not_null),Boolean), Map(String(not_null),Map(String(not_null),String)), Decimal(18,0), Decimal(7,3), Decimal(10,10), Decimal(9,0), Decimal(18,15)]]
06:59:10  FAILED src/main/python/parquet_test.py::test_read_round_trip[-reader_confs2-read_parquet_sql-[Byte, Short, Integer, Long, Float, Double, String, Boolean, Date, Timestamp, Array(Byte), Array(Long), Array(String), Array(Date), Array(Timestamp), Array(Decimal(18,0)), Array(Array(Byte)), Struct(['child0', Array(Byte)],['child1', Byte],['child2', Float],['child3', Decimal(18,0)]), Array(Struct(['child0', String],['child1', Double],['child2', Integer])), Map(String(not_null),String), Map(String(not_null),Array(String)), Map(RepeatSeq(not_null)(Integer(not_null)),Long), Map(Boolean(not_null),Boolean), 
...
and more

**Comment by tgravescs** [comment]
actually looks like parquet read not on GPU:

06:59:10  E   ColumnarToRow
06:59:10  E   +- FileScan parquet [_c0#308632,_c1#308633,_c2#308634,_c3#308635L,_c4#308636,_c5#308637,_c6#308638,_c7#308639,_c8#308640,_c9#308641,_c10#308642,_c11#308643,_c12#308644,_c13#308645,_c14#308646,_b1#308647,_b3#308648L,_b5#308649,_b7#308650,_b9#308651,_b11#308652,_b13#308653,key#308654] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex[file:/tmp/pyspark_tests/496612/PARQUET_DATA], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<_c0:tinyint,_c1:smallint,_c2:int,_c3:bigint,_c4:float,_c5:double,_c6:string,_c7:boolean,_c...
06:59:10

**Comment by tgravescs** [comment]
!Exec <FileSourceScanExec> cannot run on GPU because unsupported data types in output: DecimalType(9,0), DecimalType(10,10), DecimalType(7,3), DecimalType(18,15), DecimalType(18,0); GpuParquetScan does not support fields of type DecimalType(9,0); GpuParquetScan does not support fields of type DecimalType(7,3); GpuParquetScan does not support fields of type DecimalType(10,10); GpuParquetScan does not support fields of type DecimalType(18,0); GpuParquetScan does not support fields of type DecimalType(18,15)

**Comment by tgravescs** [comment]
I'm guessing https://github.com/NVIDIA/spark-rapids/pull/1294/files missed the databricks shim @sperlingxx

**Comment by sperlingxx** [comment]
> I'm guessing https://github.com/NVIDIA/spark-rapids/pull/1294/files missed the databricks shim @sperlingxx

Yes, it's my bad. Thank you for the fix :)
