### ISSUE TITLE
[FEA] Databricks shim properties file should contain commit version

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1467]
**Is your feature request related to a problem? Please describe.**
Recently there was an issue with a change that needed to be applied to the shims and it inadvertently didn't make it into the Databricks shim.  We later fixed that issue, but the nightly CI build still failed even though it was using a RAPIDS Accelerator jar whose rapids4spark-version-info.properties showed that it was using a git commit hash with the fix.  The issue turned out to be that the main code in the jar was using the correct version but the Databricks shim, which is built separately from the main code, was still on the older version.  There is a properties file specific to each shim, but unfortunately it does not contain the git hash and instead contains very little useful information in it.
 
**Describe the solution you'd like**
The shim property files (e.g.: spark-3.0.1-databricks-info.properties) should contain the git commit hash used when the shim was built.  This would help us track down issues where the main code and shim code are on different versions in a jar.

**Comment by sameerz** [comment]
This can be resolved with jobs being triggered properly in the build.

**Comment by GaryShen2008** [comment]
The main problem here is to make sure the git commit IDs are same when building databricks shim and rapids-4-spark nightly build, isn't it?

**Comment by jlowe** [comment]
Yes, that is the main goal.  It would be nice to have the plugin and shim builds encode the git commit hash into their respective property files so this can be verified in the resulting jar.

**Comment by pxLi** [comment]
The request sounds good to me. 

So can I assume you guys should be fine w/ that commits merged after the DB nightly get triggered will not be tested in today's whole integrations test pipelines? Cause we should keep the commit we use from the beginning (databrick build), then the total runtime could be around 8-10 hours

**Comment by jlowe** [comment]
> So can I assume you guys should be fine w/ that commits merged after the DB nightly got triggered will not be tested in today's whole integrations test pipelines?

Yes, assuming the alternative is to mash together a plugin and shims built on different commits.  The new commits will be picked up in the next nightly build.

**Comment by NvTimLiu** [comment]
Blossom pipeline changes:  Build databricks shim and spark-rapids jars using the same commit IDs
https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/merge_requests/40

**Comment by NvTimLiu** [comment]
The commit HEAD in databricks jars is missing, I'll add it in db jar.

**Comment by NvTimLiu** [comment]
We copy '.git' into databricks cluster to generate git commit info for the databricks shim jar. Fixed

**Comment by NvTimLiu** [comment]
As https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/merge_requests/40 got merged, I suppose we can close this issue now.
