### ISSUE TITLE
Adjust abstraction structure for join operators

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#1468]
**Is your feature request related to a problem? Please describe.**
Currently we have joins that are repeating code e.g. GpuCartesianProductExec and GpuBroadcastHashJoinExec

**Describe the solution you'd like**
The metrics code could be combined to an abstraction

**Reference**
For reference checkout [commit](https://github.com/apache/spark/commit/eba2076ca3) which drove a similar task in Spark

**Comment by revans2** [comment]
I really don't know how much code we could reuse between the two.  We already follow spark with most of the reuse between the various joins, but GpuCatesianProductExec and GpuBroadcastNestedLoopJoin are both really their own thing and there isn't a lot of overlap between them.
