### ISSUE TITLE
Support foldable args by `from_csv/json` and `schema_of_csv/json`

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#1469]
**Is your feature request related to a problem? Please describe.**
We should test if foldable args work for csv schema on GPU

**Describe the solution you'd like**
At a minimum a test should be created 

**Additional context**
Refer to [commit](https://github.com/apache/spark/commit/59f1e76b82) for more context

**Comment by sameerz** [comment]
We currently do not support `from_csv` or `schema_of_csv` for json.
