### ISSUE TITLE
[FEA] Improve handling of scalar expressions

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1471]
**Is your feature request related to a problem? Please describe.**
Currently the result of an expression is always converted into a `GpuColumnVector` so it can be placed in a `ColumnarBatch`.  This requires any scalar expressions to be replicated into a column vector.  This works, but it is inefficient both in terms of space and time.  In addition it precludes downstream expressions and execs from using optimized implementations if one of the inputs is a scalar.  For example, `GpuAdd` currently adds two columns together, despite libcudf supporting the addition of a scalar to a column without requiring the scalar to be splatted into a column of the same length as the other input.  Since `GpuAdd` always receives columns as input, it cannot easily know whether one of its inputs is really a scalar and use the more efficient scalar operation.

**Describe the solution you'd like**
One way to solve this is to have a new class that can hold either a `GpuColumnVector` or a `GpuScalar`, and it would be up to consumers of GPU columnar batches to detect whether there is a scalar and act accordingly.  The new class could have a `getAsColumn` method or something similar that automatically splats the scalar to a column for the cases where an operation can only operate on columns.

**Comment by chenrui17** [comment]
@jlowe  i am curious about this  will if improve performance if it's finished ?

**Comment by jlowe** [comment]
> this will improve performance if finished ?

It should improve performance if the libcudf operation receiving the scalar can operate on scalars directly.  For example, the binary operations in libcudf (e.g.: add, subtract, multiply, etc.) can operate on (column, scalar) or (scalar, column) input combinations _without manifesting the scalar value as a full column in memory first_.  This obviously saves on memory, but it also saves some time as it avoids the prerequisite splat.  It may also save time on the binary operation as well.  Many operations on the GPU are memory-bandwidth-bound, and loading a single scalar value will be much more cache-coherent than loading a full column of redundant values.

If the libcudf operation does not support scalar inputs then the plugin will need to expand the scalar to a full column as it does today so the libcudf operation can be invoked.

The biggest issue with this change is the scope of the change.  We need to update all the exec and expression implementations in the plugin to expect either a column or a scalar and act accordingly.  Currently the only GPU data that can appear in a `ColumnarBatch` input is column instances.

**Comment by jlowe** [comment]
Fixed by #8751. Expressions can now call columnarEvalAny instead of columnarEval which can produce a scalar if the child expression supports that as an output.
