### ISSUE TITLE
[FEA] Replace expression GpuTimeSub(l, r) with GpuTimeAdd(l -r)

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#1482]
TimeSub(l, r) was replaced with TimeAdd(l, -r)  in Apache Spark in JIRA https://issues.apache.org/jira/browse/SPARK-31586.
We may have to make corresponding changes for GPU expressions.

**Comment by tgravescs** [comment]
I thought we already did this @razajafri

**Comment by revans2** [comment]
Everything in the https://issues.apache.org/jira/browse/SPARK-31586 PR was in the logical plan.  We support both GpuTimeSub and GpuTimeAdd. I agree with @tgravescs I am not sure that there is anything more for us to do here.

**Comment by nartal1** [comment]
Thanks @tgravescs and @revans2,  I agree we support GpuTimeAdd and GpuTimeSub. The intent of this FEA was whether we need to incorporate minor change i.e remove `GpuTimeSub` from our code base(as TimeSub is removed in Apache Spark and hence GpuTimeSub will not be used). 
I will close it if it's okay to keep `GpuTimeSub` (as there is no issue if it stays). 
Please let me know your thoughts.

**Comment by razajafri** [comment]
Sorry for chiming in late. @nartal1 we should keep `GpuTimeSub` until we are supporting Spark-3.0.0

**Comment by nartal1** [comment]
Sounds good :) . Thanks @razajafri. 
Closing this issue.
