### ISSUE TITLE
[FEA] Add Apache Spark 3.2.0 shim layer

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1490]
**Is your feature request related to a problem? Please describe.**
Apache spark split the branch for the 3.1.X line which means master branch is now 3.2.0-SNAPSHOT. We need to add a shim layer for this.

**Comment by sameerz** [comment]
Spark 3.2.0 is not required for 0.4, but we should get the shim in place so we can start identifying potential breaking changes.

**Comment by sameerz** [comment]
Support for Spark 3.2.0 will come in the 0.5 version of the plugin.

**Comment by tgravescs** [comment]
Note the spark 3.0.2 vote passed so should be officially available in the next couple days
