### ISSUE TITLE
Decimal Type support for Parquet Write

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#1491]
**Is your feature request related to a problem? Please describe.**
We don't support Decimal support for Parquet in the plugin 

**Describe the solution you'd like**
Turning this on just for Parquet won't be as trivial as the others as `DataWritingCommandExec` handles all of the file types. To turn this on only for Parquet will require some changes to the framework.

**Comment by sameerz** [comment]
Duplicate of #1485
