### ISSUE TITLE
[BUG] Limit processing on Databricks performs poorly

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1507]
Performing a limit query on Databricks can run a lot slower than the CPU version.  In one example, a query on the CPU only ran a single task in a stage, whereas the GPU query ran over 2100 tasks in the same stage.  This particular query did not have a CollectLimitExec in the plan, yet it appears the CPU query ran with a similar ramp-up processing logic since it was able to only run one task.  Either that or it was able to push down the limit all the way into the input format and realize only one stage was necessary to execute.

**Comment by mattahrens** [comment]
Closing as won't fix for now
