### ISSUE TITLE
[FEA] Improve limit processing performance

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1508]
**Is your feature request related to a problem? Please describe.**
When running a query with a limit, an input task will often load the entire input file (or set of files if batching smaller files).  This can be inefficient if the limit is low and accessing the data is slow.  In those cases it is often faster to load much less data since only that amount of data is needed to satisfy the limit.

**Describe the solution you'd like**
I'm not sure how best to fix this, but I wanted to file an issue to track some ideas:
- Better limit push-down into the input formats, where we may be able to avoid running fully wide in the input stage.  This is likely a change best done in Apache Spark and is not specific to GPU processing.
- Automatic tuning of the input batch size so we're not so aggressive at batching large amounts of rows together for reduced overhead and therefore higher throughput.  For many limit queries, latency trumps throughput.
- Related to the previous, we could load fewer row groups from the input file when we see the number of rows loaded from the row group far exceed the limit (or some similar heuristic).  This could guess wrong and cause us to invoke the GPU parser once per rowgroup in vain attempts to hit the limit early, but it could be a nice win in other cases.

**Comment by mattahrens** [comment]
Closing as won't fix for now
