### ISSUE TITLE
[FEA] Customizable escape characters in LIKE regexes

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#1514]
Tangentially related to https://github.com/apache/spark/commit/54a73ab7bb.

Spark SQL allows escape characters in `LIKE` regex strings to be customizable:
https://docs.databricks.com/sql/language-manual/sql-ref-syntax-qry-select-like.html

E.g. 
```sql
SELECT * FROM person WHERE name LIKE '%$_%' ESCAPE '$';
```

This will need support from CUDF as well, to support in `spark-rapids`.

**Comment by revans2** [comment]
I think we already support this.

https://github.com/NVIDIA/spark-rapids/blob/291a20a742ca5510574579145f3ffbfc438f50a9/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala#L506

**Comment by sameerz** [comment]
We believe we already support this.
