### ISSUE TITLE
[FEA] Add tests for Datetimes with bad combination of year/month/day...

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#1517]
Related to audit of https://github.com/apache/spark/commit/1034815519 and https://github.com/apache/spark/commit/b9f2f78de5.

Failure cases for year/month/day combinations have been modified in ANSI mode. We need to add tests to verify `ANSI_ENABLED` behaviour. We should also check that the tests added in this commit work correctly with the `spark-rapids` plugin.
Must also verify that datetime parsing fails with bad pattern strings.

**Comment by sameerz** [comment]
@andygrove is there anything in https://github.com/apache/spark/commit/b9f2f78de5 that is more stringent but that we have on by default?

**Comment by andygrove** [comment]
I will take a look at this tomorrow. It is also related to https://github.com/NVIDIA/spark-rapids/issues/1117

**Comment by andygrove** [comment]
> @andygrove is there anything in [apache/spark@b9f2f78](https://github.com/apache/spark/commit/b9f2f78de5) that is more stringent but that we have on by default?

@sameerz Yes, the plugin currently returns `null` for the invalid dates instead of throwing an exception when ANSI mode is enabled

**Comment by andygrove** [comment]
I opened a PR to fix this for CAST and filed https://github.com/NVIDIA/spark-rapids/issues/1556 to do the same for the string to timestamp functions since this is a different code path.

https://github.com/NVIDIA/spark-rapids/issues/1556

**Comment by sameerz** [comment]
Closing this and tracking the follow up in #1556
