### ISSUE TITLE
[FEA] Add tests for LOCAL insert overwrite consistent with the CPU

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#1523]
**Is your feature request related to a problem? Please describe.**
We might be allowing LOCAL fs writes and since https://github.com/apache/spark/commit/657d151395 the behavior has changed and needs further investigation.

**Describe the solution you'd like**
Match CPU behavior as needed.

**Comment by sameerz** [comment]
This is a change to the sql parser, not to any other part of catalyst.  Closing.
