### ISSUE TITLE
Add test for AQE=on && repartition()

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#1527]
This arises from audit of https://github.com/apache/spark/commit/d1b4f06179.

Spark 3.1 has changed to disallow local shuffle reader substitution (by AQE), in case the query uses `repartition(num, col)`.

We need to verify that a query with `repartition()` works with `spark-rapids` when AQE is on.

**Comment by sameerz** [comment]
This can be tested manually and an ongoing test is not required, since we believe this change is in the realm of Spark's query planning and not the plugin's processing of the query plan.
