### ISSUE TITLE
Support Decimal and Struct for ParquetCachedBatchSerializer

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#1580]
Now that cudf supports Decimal and Struct, we should add support for it to the ParquetCachedBatchSerializer. 

It should just be a matter of whitelisting them in GpuOverrides

**Comment by razajafri** [comment]
This is fixed by #1596

**Comment by sameerz** [comment]
Struct support for ParquetCachedBatchSerializer is tracked in issue #1582
