### ISSUE TITLE
[FEA] Allow StructType as input and output type to InMemoryTableScan and InMemoryRelation

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#1582]
**Is your feature request related to a problem? Please describe.**
Need to test and add struct type to InMemoryTableScan and InMemoryRelation operators as output and input data types.

**Comment by razajafri** [comment]
closed by #1596

**Comment by razajafri** [comment]
I am reopening this because I should add tests before closing this

**Comment by razajafri** [comment]
This is dependent on [rapidsai/cudf/7230](https://github.com/rapidsai/cudf/pull/7230)

**Comment by sameerz** [comment]
Depends on https://github.com/rapidsai/cudf/pull/7998 and https://github.com/NVIDIA/spark-rapids/pull/1969

**Comment by sameerz** [comment]
@razajafri can this issue be closed?

**Comment by razajafri** [comment]
closed by #1969
