### ISSUE TITLE
[BUG] sort tests failing CI for floats and doubles

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1585]
**Describe the bug**
Bunch of CI builds failed last night with:

07:29:20  FAILED src/main/python/sort_test.py::test_single_orderby[Column<b'a ASC NULLS FIRST'>-Float(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_orderby[Column<b'a ASC NULLS FIRST'>-Double(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_orderby[Column<b'a ASC NULLS LAST'>-Float(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_orderby[Column<b'a ASC NULLS LAST'>-Double(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_orderby[Column<b'a DESC NULLS LAST'>-Float(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_orderby[Column<b'a DESC NULLS LAST'>-Double(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_orderby[Column<b'a DESC NULLS FIRST'>-Float(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_orderby[Column<b'a DESC NULLS FIRST'>-Double(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a ASC NULLS FIRST'>-Float(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a ASC NULLS FIRST'>-Double(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a ASC NULLS LAST'>-Float(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a ASC NULLS LAST'>-Double(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a DESC NULLS LAST'>-Float(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a DESC NULLS LAST'>-Double(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a DESC NULLS FIRST'>-Float(not_null)]
07:29:20  FAILED src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a DESC NULLS FIRST'>-Double(not_null)]

**Comment by revans2** [comment]
It looks like NaN and Inf values are getting mixed up some how. I am going to dig a bit deeper. It is also really odd that it only shows up if there are no null values.

**Comment by revans2** [comment]
So it looks like after rapidsai/cudf#7167 was merged in nan values are not longer > infinity, but instead almost random where they show up.

**Comment by revans2** [comment]
It sounds like cudf will revert the change for floating point values. I will file an issue against them for this.

**Comment by revans2** [comment]
I filed https://github.com/rapidsai/cudf/issues/7212 to cover this.

**Comment by revans2** [comment]
A fix went into CUDF for this
