### ISSUE TITLE
[FEA] Support for arrays and array operations

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#16]
**Is your feature request related to a problem? Please describe.**
Really would be great to support arrays as a part of the plugin.

**Comment by sameerz** [comment]
Depends in part on https://github.com/rapidsai/cudf/issues/4830 , https://github.com/rapidsai/cudf/issues/4831 , https://github.com/rapidsai/cudf/issues/4832 , https://github.com/rapidsai/cudf/issues/4833 .  Work will span 0.2 and 0.3.

**Comment by sameerz** [comment]
This issue is very broad.  Some progress has been made.  We need to break this up into additional tasks.

**Comment by jlowe** [comment]
Array types along with many array operations are supported.
