### ISSUE TITLE
[FEA] Support sorting on nested type keys

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#1605]
**Is your feature request related to a problem? Please describe.**
Once https://github.com/rapidsai/cudf/issues/7226 is implemented we would want to test and add functionality to the plugin to be able to sort on nested type keys.

**Comment by sameerz** [comment]
The PR that closed this issue supports single level sorting on these data types: BOOLEAN + BYTE + SHORT + INT + LONG + FLOAT + DOUBLE + DATE + TIMESTAMP + STRING + NULL + DECIMAL
