### ISSUE TITLE
[FEA] Allow RangePartitioning to work with structs

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#1607]
**Is your feature request related to a problem? Please describe.**
Once https://github.com/NVIDIA/spark-rapids/issues/1605 is in, we should allow nested types as input and output types to the RangePartitioner.

**Comment by gerashegalov** [comment]
this issue depends on `upper/lower_bound` implementation for structs in cuDF https://github.com/rapidsai/cudf/issues/7690

**Comment by sameerz** [comment]
Modifying this issue to focus on structs, rather than structs and lists.
