### ISSUE TITLE
[BUG] TPC-DS-like query 77 at scale=3TB fails with maxResultSize exceeded error

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#1626]
Running q77 at 3TB fails with:
```
21/01/29 16:55:30 ERROR TaskSetManager: Total size of serialized results of 24771 tasks (1053.8 MiB) is bigger than spark.driver.maxResultSize (1024.0 MiB)
```
This issue is likely related to: https://github.com/NVIDIA/spark-rapids/issues/1284. But this is being run with the released 0.3 version of the plugin. 

Upping the `spark.driver.maxResultSize` does help, but we still seem to see 20MB of output per task, which is adding up quickly.

**Comment by revans2** [comment]
So Apache Spark has mad this a little bit more difficult that I would like.  They are trying really hard to keep users from shooting themselves in the foot and creating an AccumulatorV2 that is not registered.  What is more when the accumulator is deserialized it auto registers it with the TaskContext. This means that I am going to have to put in an abstraction layer around GPU metrics to allow for a NOOP.

**Comment by jlowe** [comment]
Does it help the payload size if the metric is still created but never updated?  Wonder if they've optimized for the case where a metric reports zero.

**Comment by abellina** [comment]
The string labels for each of the metrics are being transmitted with every update, as far as I can tell. I think this is the bulk of it too.
