### ISSUE TITLE
Update CI builds for new udf-examples jar name

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1640]
After #1636 the udf-examples jar name changed.  All of the CI builds that are referencing the jar need to be updated.

**Comment by tgravescs** [comment]
I'm not sure all the builds got updated with the jar in the first place so we need to check missing as well.

**Comment by GaryShen2008** [comment]
I don't think we have any CI/CD to use the udf example right now.
We're trying to add the job for the query using urlDecode.
So, it may be no action item for now.

**Comment by jlowe** [comment]
> Does integration test use udf example jar?

Any CI/CD using a Spark built with Hive support and using `run_pyspark_from_build.sh` will add the udf-examples jar and run the urldecode integration tests.  This includes premerge CI and the primary nightly integration which is already running successfully with the new jar name.  I'm not sure about some of the integration tests specific to cloud environments.

**Comment by tgravescs** [comment]
I think we should update all the integration tests to use run_pyspark_from_build.sh if possible. This might mean changes to the script if we need to specify a different master. I didn't think that was supported.  This way any changes devs make should automatically be picked up.

**Comment by revans2** [comment]
> This might mean changes to the script if we need to specify a different master. I didn't think that was supported.

The scripts were set up to avoid making assumptions about what it was running on.  If you set `SPARK_CONF_DIR` to the configs for the cluster you want to run on it will pick them up and use them.  If you are running on a truly distributed cluster you need to either disable the parallel test run, or make sure that you have enough resources in your cluster to run N+1 applications in parallel. In that case too we probably need to copy the standard input files to the default distributed file system so that the tests can find them.

**Comment by NvTimLiu** [comment]
checking

**Comment by NvTimLiu** [comment]
Cloud environments changed to refer to the correct udf-examples jar: 
https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/blob/main/utils/download-jars.sh#L17
https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/blob/main/databricks/pytests-on-databricks.sh#L38
https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/blob/main/emr/pytests-on-emr.sh#L41
https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/blob/main/dataproc/pytests-on-dataproc.sh#L47

**Comment by NvTimLiu** [comment]
close as Clound environment changed to refer to the correct udf-examples jar
