### ISSUE TITLE
[DOC]Build instructions for Rapids plugin

### ISSUE THREAD

**Issue by KaixinLuo** [NVIDIA/spark-rapids#1647]
## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.
A command or instruction to build a single Jar like the Jar file in central maven. Since I would like to insert extra logs and run to see the UCX tag value.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken(on the project root directory):
maven verify
maven install -DSkipTests

**Comment by jlowe** [comment]
There are build instructions in the README, but they don't point to where the main jar is built.  It's under the `dist/target/` directory after a `package` build (or any build goal that is a superset of that, like `verify` or `install`).

I'll update the docs to point to where the distribution jar is built.
