### ISSUE TITLE
Validate the output of TPC-DS on GPU with nightly SNAPSHOT jars

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#1658]
**Is your feature request related to a problem? Please describe.**
We need a nightly job to validate the output of TPC-DS on GPU.

**Describe the solution you'd like**
We use Jenkins to set up a nightly job running with the latest SNAPSHOT jars.

**Comment by GaryShen2008** [comment]
@wjxiz1992 I think we have merged the PR to enable the data validation. Could you check it and close this issue if it's done?

**Comment by wjxiz1992** [comment]
Current approach:
Except for those failing queries, the total query set(100+ queries) is divided into 5 parts. Each part will be tested after daily run of TPC-DS benchmark on weekdays.
We will be seeing logs like:
```
16:26:43  [Data Validation] [3.1.1] [0.5.0-SNAPSHOT] [0.19-SNAPSHOT] [10-1] [tpcds-sf1k_parquet_data_validation] [gpu-aqe-on] [q1] match=YES
```

**Comment by wjxiz1992** [comment]
The cudf 0.19.2 has been ready, we're resuming the data validation from the testing scene of "nanosleep".

**Comment by sameerz** [comment]
This was completed.
