### ISSUE TITLE
Nightly run Mortgage ETL with AQE on/off on AWS EMR

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#1659]
**Is your feature request related to a problem? Please describe.**
Need a nightly job to run Mortgage ETL with both AQE on and off on AWS EMR.

**Describe the solution you'd like**
Create a Jenkins to run with the latest SNAPSHOT jars.

**Comment by NvTimLiu** [comment]
checking ...

**Comment by NvTimLiu** [comment]
As the mortgage ETL test [sample ](https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/integration_tests/src/main/scala/com/nvidia/spark/rapids/tests/mortgage/MortgageSpark.scala#L434) was hardcode to run test using parquet dataset, so we need to change it to support csv raw datasets

**Comment by NvTimLiu** [comment]
Pipeline is running!

**Comment by NvTimLiu** [comment]
Close as PR #1808  merged
