### ISSUE TITLE
[FEA] Support get_json_object

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#166]
**Is your feature request related to a problem? Please describe.**
Support https://spark.apache.org/docs/2.4.5/api/sql/index.html#get_json_object in RAPIDS Spark

**Describe the solution you'd like**
Enable get_json_object to run on the GPU.  

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sameerz** [comment]
Removing from Release 0.2 based on feedback regarding scope.  This will require writing a json parser.

**Comment by razajafri** [comment]
closed by #1893
