### ISSUE TITLE
[BUG] Some TPC-DS queries fail with AQE when decimal types enabled

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#1670]
**Describe the bug**
I just tried running q4 and q11 with AQE and decimal types enabled, and they fail with:

```
Caused by: java.lang.IllegalStateException: operating on canonicalized plan
	at org.apache.spark.sql.execution.adaptive.CustomShuffleReaderExec.$anonfun$shuffleRDD$2(CustomShuffleReaderExec.scala:79)
```

**Steps/Code to reproduce bug**

I am running against Spark 3.0.1 using the benchmark runner Python script with the following template:

```bash
$SPARK_HOME/bin/spark-submit \
  --master local[*] \
  --driver-memory 64G \
  --jars $SPARK_RAPIDS_PLUGIN_JAR,$CUDF_JAR \
  --conf spark.executor.extraJavaOptions="-Dai.rapids.cudf.prefer-pinned=true -Dai.rapids.cudf.nvtx.enabled=true -Dai.rapids.spark.semaphore.enabled=true -Dai.rapids.spark.memory.gpu.rmm.init.task=false" \
  --conf spark.eventLog.enabled=true \
  --conf spark.eventLog.dir=./spark-event-logs \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.rapids.sql.explain=ALL \
  --conf spark.rapids.sql.batchSizeBytes=50000000 \
  --conf spark.rapids.sql.reader.batchSizeBytes=50000000 \
  --conf spark.rapids.sql.concurrentGpuTasks=1 \
  --conf spark.rapids.sql.replaceSortMergeJoin.enabled=true \
  --conf spark.rapids.sql.variableFloatAgg.enabled=true \
  --conf spark.rapids.sql.castFloatToString.enabled=true \
  --conf spark.rapids.sql.decimalType.enabled=true \
  --conf spark.rapids.sql.hasNans=false \
  --conf spark.sql.adaptive.coalescePartitions.enabled=true \
  --conf spark.sql.adaptive.coalescePartitions.minPartitionNum=200 \
  --conf spark.sql.adaptive.skewJoin.skewedPartitionFactor=2 \
  --conf spark.sql.shuffle.partitions=400 \
  --conf spark.sql.optimizer.dynamicPartitionPruning.enabled=true \
  --conf spark.sql.optimizer.dynamicPartitionPruning.reuseBroadcastOnly=false \
  --conf spark.sql.optimizer.dynamicPartitionPruning.fallbackFilterRatio=0.1 \
  --conf spark.sql.adaptive.coalescePartitions.enabled=true \
  --conf spark.sql.legacy.parser.havingWithoutGroupByAsWhere=true \
  --conf spark.sql.sources.partitionOverwriteMode=DYNAMIC \
```

I am using this config:

```
spark.sql.adaptive.enabled=true
spark.rapids.enableCBO=false
```

**Expected behavior**
Query should not fail

**Environment details (please complete the following information)**
Desktop.

**Additional context**
Running with latest from branch-0.4 (2347b949d3bdbf57becc2fc8de1eb0883183d160)

**Comment by jlowe** [comment]
@andygrove did this used to work on an older codebase?  Curious if #1655 is related.

**Comment by andygrove** [comment]
@jlowe I had the same thought and tested with the commit before that and the issue is still there.

**Comment by sperlingxx** [comment]
I also ran q4 and q11 on desktop, and got warning message  "spark.sql.adaptive.enabled is enabled but is not supported for query".

**Comment by jlowe** [comment]
> I also ran q4 and q11 on desktop, and got warning message "spark.sql.adaptive.enabled is enabled but is not supported for query".

I believe this is relate to dynamic partition pruning which currently isn't compatible with AQE.  I was able to get past those messages by setting `spark.sql.optimizer.dynamicPartitionPruning.enabled=false`.  Despite the fact that it is explicitly enabled in the description, I suspect the dataset @andygrove is using isn't partitioned in a way that allows DPP to work on these queries, whereas it does on the local datasets I'm using.

**Comment by andygrove** [comment]
That's correct. I am not running against a partitioned data set.

**Comment by sperlingxx** [comment]
Hi @andygrove, I did some investigation on this issue. And I found it seems caused by incorrect GPU override rule of `CustomShuffleReader`.  In current, Rapids plugin won't replace `CustomShuffleReader` with GPU counterpart when it contains decimal types. Meanwhile, GPU replacement rules are effective to its child plan.
I created a pull request to fix this problem. I hope it is a right fix.

**Comment by andygrove** [comment]
I have enabled AQE on + decimals in the automated benchmarks in CI and can confirm that this is resolved
