### ISSUE TITLE
[FEA] Basic support for structs

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#17]
Basic functionality for struct support

- [x] Parquet reading of structs
- [x] CreateNamedStruct for non-nested children #78 
- [x] GetStructField
- [x] Shuffling of structs
- [x] Parquet writing of structs https://github.com/rapidsai/cudf/pull/7230
- [x] Broadcast of struct data

**Comment by sameerz** [comment]
Adding to 0.2, depending on the scope of the work, may continue to 0.3.

**Comment by sameerz** [comment]
Depends on https://github.com/rapidsai/cudf/issues/5700

**Comment by revans2** [comment]
@mythrocks realistically do we have any chance to get rapidsai/cudf#5700 in and JNI bindings on it by cudf-0.15?  If not we need to move this to release 0.3

**Comment by sameerz** [comment]
This issue is very broad.  Some progress has been made.  We need to break this up into additional tasks.

**Comment by revans2** [comment]
We are not going to support nested types for CreateNamedStruct yet because cudf does not support scalar values for nested types

**Comment by kuhushukla** [comment]
We allow structs to pass through shuffle and we don't support partitioning on structs.

**Comment by devavret** [comment]
it's https://github.com/rapidsai/cudf/pull/7461 now

**Comment by sameerz** [comment]
Closing this as we have basic support for structs.  We will open new issues for additional struct work.
