### ISSUE TITLE
[BUG] Scala UDF compiler can decompile UDFs with RAPIDS implementation

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1712]
Now that Scala UDFs have support for a RAPIDS implementation since #1636, there's the possibility that the Scala UDF compiler could end up compiling a user's Scala UDF into Catalyst expressions despite the fact that it already provides a RAPIDS columnar implementation.  The UDF compiler should detect and avoid trying to translate UDFs that implement the `RapidsUDF` interface.

**Comment by GaryShen2008** [comment]
Remove from v21.06. Let's target in 21.08.

**Comment by jlowe** [comment]
Fixed by #1712
