### ISSUE TITLE
[FEA] Enable remaining TPC-DS queries in automated benchmark suite

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#1733]
**Is your feature request related to a problem? Please describe.**
We currently have the following queries excluded from our internal CI benchmark runs of TPC-DS:

```
'q14a', 'q14b', 'q23b',  'q25', 'q39a', 'q39b', 'q64', 'q72', 'q78', 'q80', 'q95'
```

**Describe the solution you'd like**
We should enable these tests so that we can track progress with them.

**Comment by revans2** [comment]
TPC-H or TPC-DS?  TPC-H only has 21 queries. TPC-DS has the queries you have listed.

**Comment by andygrove** [comment]
Thanks. Yes, I meant DS.

**Comment by andygrove** [comment]
This has been implemented
