### ISSUE TITLE
[FEA] Fix NPE for static partition with null in GpuInsertIntoHadoopFsRelationCommand

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#1735]
**Is your feature request related to a problem? Please describe.**
Update GpuInsertIntoHadoopFsRelationCommand for [SPARK-34223][SQL] FIX NPE for static partition with null in  InsertIntoHadoopFsRelationCommand

We have copied  InsertIntoHadoopFsRelationCommand into  GpuInsertIntoHadoopFsRelationCommand so we need to apply similar fix: https://github.com/apache/spark/commit/f2ab524fca

**Comment by gerashegalov** [comment]
For some reason auto-close from #1744 did not work, closing manually as fixed by #1744
