### ISSUE TITLE
[BUG] Getting NoSuchMethod:canChangeNumPartitions when trying to repartition the dataframes

### ISSUE THREAD

**Issue by nareshr8** [NVIDIA/spark-rapids#1743]
**Describe the bug**
Unable to repartition the dataframe created in the GPU cluster

**Steps/Code to reproduce bug**

I was trying to get started with Spark GPU. Followed the procedure in [this](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-databricks.html) link and ran the [sample notebook](). In Command 4, we have a line 
`acq.repartition(2).write.parquet(tmp_acq_path, mode='overwrite')` which throws the error 

`java.lang.NoSuchMethodError: org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.canChangeNumPartitions()Z`

However I am able to write the data if I use `coalesce`

**Expected behavior**
The repartition should work and the end data should be written to appropriate table

**Environment details (please complete the following information)**
This is running on Azure Databricks.

Cluster configuration: 
Databricks Version: 7.6 ML
Cluster (Main and Worker): Standard_NC6s_V3
Number of nodes : 2

**Additional context**
I tried to avoid repartition and try the remaining. But I am also facing issue while trying to display one of my dataframe which is just reading the parquet file.

**Comment by tgravescs** [comment]
Which version of Spark are you using? Going by the link it looks like you are using Databricks so which version of the runtime? We only support DataBricks Runtime 7.3 ML with GPU.
 the thing its complaining about ShuffleExchangeExec.canChangeNumPartitions()Z was there in Spark 3.0 but removed later in Spark 3.1 so if you are using a later version of Databricks runtime that is based on spark 3.1 then you might see this.

**Comment by nareshr8** [comment]
The Spark version that Databricks 7.6 ML comes with is 3.0.1. I will try with Databricks 7.3 ML and see, though it also seems to come with spark 3.0.1 only

**Comment by nareshr8** [comment]
Seems 7.3 ML is working fine. Thanks for the help
