### ISSUE TITLE
[BUG] Databricks AWS CI/CD failing to create cluster

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1771]
**Describe the bug**
See the CI/CD for rapids_integration-AWSDatabricks.
08:29:59  parse error: Invalid numeric literal at line 1, column 6

The Azure one seems to be working. Need to see what is going on.

**Comment by tgravescs** [comment]
@NvTimLiu @GaryShen2008 please look at when back.

**Comment by tgravescs** [comment]
Note I tried to reproduce on local desktop but it works fine from there. Not sure if maybe databricks client changed or other 
parameter different.

**Comment by NvTimLiu** [comment]
Seems the DB token was expired and was auto deleted by in the DB webUI.

Recreate a new long term token, and update it in Blossom Jenkins. 

Re-trigger a job: https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/job/rapids_integration-AWSDatabricks/80/

Close it after the new build get PASS

**Comment by NvTimLiu** [comment]
close it as the token updated, expiration to 2023
