### ISSUE TITLE
[FEA] Spark 3.0.2 release available.

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1773]
**Is your feature request related to a problem? Please describe.**
Spark 3.0.2 passed so it will be released shortly, we should update shim to remove snapshot and make it official.

**Comment by tgravescs** [comment]
Note we should push official spark 3.0.2 tarball to repos for CI/CD, that should be available in the next few days - @NvTimLiu @GaryShen2008

**Comment by NvTimLiu** [comment]
Uploaded 3.0.2 tar ball to the CI/CD repos.

**Comment by NvTimLiu** [comment]
rapids IT against 3.0.0/3.0.1/3.0.2

**Comment by NvTimLiu** [comment]
close this as IT pipeline against 3.0.2 is running:
https://blossom.nvidia.com/sw-gpu-spark-jenkins/job/rapids_integration-dev-github/
https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/PRE-RELEASE/job/rapids_integration-pre_release-github/

The remaining shim layer issue is tracked by Issue #1782
