### ISSUE TITLE
[FEA] Shim layers to support spark versions

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#1782]
**Is your feature request related to a problem? Please describe.**

Per issue [#1773](https://github.com/NVIDIA/spark-rapids/issues/1771), after spark-3.0.2 got released, apache-spark3.0 release versions:
•	[3.0.0](https://archive.apache.org/dist/spark/spark-3.0.0/)
•	[3.0.1](https://archive.apache.org/dist/spark/spark-3.0.1/)
•	[3.0.2](https://archive.apache.org/dist/spark/spark-3.0.2/)
Meanwhile, we are building spark snapshot versions:
•	[spark-3.2.0-SNAPSHOT](https://gitlab-master.nvidia.com/nvspark/spark/-/blob/nvmaster/pom.xml#L29)
•	[spark-3.1.2-SNAPSHOT](https://gitlab-master.nvidia.com/nvspark/spark/-/blob/nv-branch-3.1/pom.xml#L29)
•	[spark-3.0.3-SNAPSHOT](https://gitlab-master.nvidia.com/nvspark/spark/-/blob/nv-branch-3.0/pom.xml#L29)
 
Currently our rapids-pluging shim layers supported below versions: 
•	spark300/
•	spark300emr/
•	spark301/
•	spark301db/
•	spark301emr/
•	spark302/
•	spark311/
 
@sameerz  @tgravescs  @jlowe  @revans2  Could you please help to confirm: our spark-rapids should support all these releases and SNAPSHOT? 
If yes, our shim layers need to:
•	[_spark302_ ](https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/pom.xml#L178)--> change 3.0.2-SNAPSHOT to 3.0.2
•	_Spark303_ --> Add shim layer
•	_spark311_ --> upgrade to spark312 SNAPSHOT
•	_spark320_ --> It Seems [#1704](https://github.com/NVIDIA/spark-rapids/pull/1704) work for it

scripts need to:
•	Change [Premerge ](https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/jenkins/spark-premerge-build.sh#L42)script to test against latest 3.0.2 release instead of 3.0.1
•	Change [Nightly ](https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/jenkins/spark-nightly-build.sh#L28)script to test against 3.1.2/3.2.0 SNAPSHOT instead of 3.1.1

**Comment by jlowe** [comment]
The existing spark302 shims already recognize 3.0.2, so no change is needed there.

A Spark 3.0.3 shim is needed but not in 0.4.

The spark311 shim stays as-is, recognizing both Spark-3.1.1-SNAPSHOT and Spark-3.1.1.  No change necessary.

A new spark312 shim is needed but not in 0.4.

> Change Nightly script to test against 3.1.2/3.2.0 SNAPSHOT instead of 3.1.1

I don't think we want to drop testing of 3.1.1.  These new Spark versions need to be added, not replacing other Spark versions unless we're willing to drop support of those versions.

The spark320 shim will be handled in #1704, again not for 0.4.

**Comment by jlowe** [comment]
Updating the Spark 3.0.2 shim to support the official 3.0.2 release is handled in #1831 
Updating the Spark 3.1.1 shim to support the official 3.1.1 release is handled in #1832 
The Spark 3.0.3 shim is being added in #1834 
The Spark 3.1.2 shim is being added in #1836 
The Spark 3.2.0 shim is being added in #1704 

Note the new shims are only being added to the nightly "run all the Spark test profiles" portion of the build.  No separate pipelines to run the integration tests against these new shims have been created yet.

**Comment by sameerz** [comment]
I believe we have updated all the relevant shim layers for the 0.5 release per this comment:

> Updating the Spark 3.0.2 shim to support the official 3.0.2 release is handled in #1831
Updating the Spark 3.1.1 shim to support the official 3.1.1 release is handled in #1832
The Spark 3.0.3 shim is being added in #1834
The Spark 3.1.2 shim is being added in #1836
The Spark 3.2.0 shim is being added in #1704
