### ISSUE TITLE
[BUG] Rapids pytest integration tests FAILED on Yarn cluster with unrecognized arguments: `--std_input_path=src/test/resources/`

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#1785]
**Describe the bug**
Run rapids pytest IT on EGX Yarn cluster
Rapids integration tests FAILED on Yarn cluster with unrecognized arguments: `--std_input_path=src/test/resources/` as below:
    _cd integration_tests/
    spark-submit --master --deploy-mode cluster runtests.py -std_input_path=src/test/resources/_
    _LOG: http://spark-egx-03:8088/cluster/app/application_1603128018386_6400_
        ERROR: usage: runtests.py [options] [file_or_dir] [file_or_dir] [...]
        runtests.py: error: unrecognized arguments: --std_input_path=src/test/resources/

If we remove `--deploy-mode cluster`, the tests can PASS.
    _spark-submit --master runtests.py -std_input_path=src/test/resources/_
    _LOG: http://spark-egx-03:8088/cluster/app/application_1603128018386_6399_

        src/main/python/struct_test.py::test_orderby_struct[Struct(['first', String],['second', Array(String)],[  'third', Array(String)])] PASSED [ 95%]
        src/main/python/struct_test.py::test_orderby_struct_2[Struct(['first', String],['second', Array(String)]  ,['third', Array(String)])] PASSED [100%]
============================= 23 passed in 41.09s ==============================

****Detailed scripts: timl@spark-egx-03:/home/timl/yarn-IT/submit-yarn.sh****
#!/bin/bash
set +ex
export SPARK_CONF_DIR=/usr/hdp/current/spark2-client/conf/
export HADOOP_HOME=/usr/hdp/3.1.0.0-78/hadoop
export HADOOP_CONF_DIR=/usr/hdp/3.1.0.0-78/hadoop/conf
export SPARK_HOME=/home/timl/spark-3.0.0-bin-hadoop3.2
export PATH=$SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH

export PYSPARK_PYTHON=/usr/bin/python3.6
export PYSPARK_DRIVER_PYTHON=/usr/bin/python3.6

OS_TYPE=ubuntu18
CUDA_NAME=cuda11.0
CUDA_DOCKER_TAG=${CUDA_NAME/./-}

CUDA_CLASSIFIER=${CUDA_NAME/./-}

FINAL=${CUDA_CLASSIFIER: -2}
if [ "$FINAL" == "-0" ]; then
 CUDA_CLASSIFIER=${CUDA_CLASSIFIER%-0}
fi
echo $CUDA_CLASSIFIER
export CUDF_JAR="hdfs:/jars/tim-test/cudf-0.18-SNAPSHOT-${CUDA_CLASSIFIER}.jar"
export PLUGIN_JAR="hdfs:/jars/tim-test/rapids-4-spark_2.12-0.4.0-SNAPSHOT.jar"

DOCKER_IMAGE=quay.io/nvidia/spark:${OS_TYPE}${CUDA_DOCKER_TAG}-yarn3

SUBMIT_ARGS="
    --master yarn --deploy-mode cluster \
    --num-executors 8 \
    --driver-memory 40G --executor-memory 100G \
    --conf spark.driver.extraJavaOptions=-Duser.timezone=UTC \
    --conf spark.executor.extraJavaOptions=-Duser.timezone=UTC \
    --conf spark.sql.session.timeZone=UTC \
    --conf spark.executor.cores=10 --conf spark.task.cpus=1 \
    --conf spark.sql.files.maxPartitionBytes=4294967296 \
    --conf spark.yarn.maxAppAttempts=1 \
    --conf spark.executor.extraJavaOptions=-Dai.rapids.cudf.prefer-pinned=true \
    --conf spark.rapids.memory.pinnedPool.size=8g \
    --conf spark.rapids.sql.concurrentGpuTasks=2 \
    --conf spark.executor.resource.gpu.amount=1 \
    --conf spark.task.resource.gpu.amount=0.1 \
    --conf spark.plugins=com.nvidia.spark.SQLPlugin \
    --conf spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh \
    --files $SPARK_HOME/examples/src/main/scripts/getGpusResources.sh \
    --conf spark.executorEnv.PYSPARK_PYTHON=/usr/bin/python3.6  \
    --conf spark.executorEnv.YARN_CONTAINER_RUNTIME_TYPE=docker \
    --conf spark.executorEnv.YARN_CONTAINER_RUNTIME_DOCKER_MOUNTS=/etc/passwd:/etc/passwd:ro,/etc/group:/etc/group:ro,/etc/hadoop/conf:/etc/hadoop/conf:ro \
    --conf spark.executorEnv.YARN_CONTAINER_RUNTIME_DOCKER_IMAGE=$DOCKER_IMAGE \
    --conf spark.yarn.appMasterEnv.YARN_CONTAINER_RUNTIME_TYPE=docker \
    --conf spark.yarn.appMasterEnv.YARN_CONTAINER_RUNTIME_DOCKER_MOUNTS=/etc/passwd:/etc/passwd:ro,/etc/group:/etc/group:ro,/etc/hadoop/conf:/etc/hadoop/conf:ro \
    --conf spark.yarn.appMasterEnv.YARN_CONTAINER_RUNTIME_DOCKER_IMAGE=$DOCKER_IMAGE \
    --conf spark.yarn.appMasterEnv.PYSPARK_PYTHON=/usr/bin/python3.6 \
    --conf spark.driver.PYSPARK_DRIVER_PYTHON=/usr/bin/python3.6 \
    --jars $CUDF_JAR,$PLUGIN_JAR \
"

cd /home/timl/yarn-IT/jars/integration_tests && spark-submit $SUBMIT_ARGS  \
     --archives /home/timl/yarn-IT/jars/integration_tests.zip#sampletests \
     runtests.py --std_input_path="src/test/resources/" src/main/python/struct_test.py -v -rfExXs

**Comment by revans2** [comment]
pytest needs to have [`conftest.py`](https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/integration_tests/conftest.py) in the `--rootdir` argument passed in or it will not know what test specific arguments to use.  From what I can see in the script `"$SCRIPTPATH"` is not set.  This is used in three places in the script. To set the rootdir to find conftest.py. To set where to find the tests to run, and when setting `--std_input_path`. We probably need to fix it so that teh tests and conftest.py are both found, and also make `std_input_path` configurable, because what it points to needs to be data in the distributed file system, not in the local file system.

**Comment by NvTimLiu** [comment]
Yes, seems --rootdir does only support local file path?

  --rootdir=ROOTDIR     Define root directory for tests. Can be relative path: 'root_dir', './root_dir',
                        'root_dir/another_dir/'; absolute path: '/home/user/root_dir'; path with
                        variables: '$HOME/root_dir'.

ERROR: Directory '/hadoop_disks/disk0/local/usercache/timl/appcache/application_1603128018386_6402/container_e87_1603128018386_6402_01_000001/hdfs:/jars/tim-test/integration_tests' not found. Check your '--rootdir' option.

**Comment by NvTimLiu** [comment]
@revans2 

I added `SCRIPTPATH=sampletests/integration_tests`, 
1,  `--rootdir` argument to find `conftest.py`
2,  `$SCRIPTPATH/src/main/python/` to find the tests
3,  `--std_input_path="$SCRIPTPATH/src/test/resources/"`

`_SCRIPTPATH='sampletests/integration_tests'
spark-submit $SUBMIT_ARGS  \
     --archives /home/timl/yarn-IT/jars/integration_tests.zip#sampletests \
     /home/timl/yarn-IT/jars/integration_tests/runtests.py  --rootdir=$SCRIPTPATH $SCRIPTPATH/src/main/python/   --std_input_path="$SCRIPTPATH/src/test/resources/" -v -rfExXs_`

now the `unrecognized arguments:` issue is fixed,

**Comment by NvTimLiu** [comment]
But the resource PATH `--std_input_path` on yarn cluster was wrongly referenced,  

Detailed log: http://spark-egx-03:8088/proxy/application_1603128018386_6435/

`>   ???
E   pyspark.sql.utils.AnalysisException: Path does not exist: hdfs://spark-egx-02:8020/user/timl/sampletests/integration_tests/src/test/resources/timestamp-date-test.orc;`


The 
 correct PATH should be the `workdir` as below on Yarn, which we set by ` --std_input_path="$SCRIPTPATH/src/test/resources/"`

`/hadoop_disks/disk0/local/usercache/timl/appcache/application_1603128018386_6435/container_e87_1603128018386_6435_01_000001/sampletests/integration_tests/src/test/resources/`

/hadoop_disks/disk0/local/usercache/timl/appcache/application_1603128018386_6437/container_e87_1603128018386_6437_01_000001
total 2060
-r-x------  1 timl timl 1112410 Feb 22 03:03 Acquisition_2007Q3.txt
-r-x------  1 timl timl  958180 Feb 22 03:03 Performance_2007Q3.txt_0
drwx------  2 timl timl    4096 Feb 23 12:54 SPARK-32639
-r-x------  1 timl timl    1213 Feb 22 03:03 log4j.properties
drwx------  2 timl timl    4096 Feb 23 12:54 parquet_acq
drwx------  2 timl timl    4096 Feb 23 12:54 parquet_perf
-r-x------  1 timl timl    1348 Feb 22 03:03 people.csv
-r-x------  1 timl timl     110 Feb 22 03:03 str.csv
-r-x------  1 timl timl     806 Feb 22 03:03 timestamp-date-test.orc
drwx------ 10 timl timl    4096 Feb 23 12:54 tpch
-r-x------  1 timl timl      69 Feb 22 03:03 ts.csv
End of LogType:stdout.This log file belongs to a running container (container_e87_1603128018386_6437_01_000001) and so may not be complete.

**Comment by NvTimLiu** [comment]
BTW, if we set HDFS path by `--std_input_path=hdfs:/jars/tim-test/integration_tests/src/test/resources/`

It can PASS:  `http://spark-egx-03:8088/proxy/application_1603128018386_6433/`

**Comment by revans2** [comment]
On a distributed cluster I would expect someone to copy the data under std_input_path to a directory on HDFS and then have --std_input_path point to the directory in HDFS.  Typically I would want them to pass in an full path `hdfs:/...` so there is no ambiguity in the data, but using a relative path is probably okay too.  The test script was written for running from maven, and will likely need to be extended so it can support running in a distributed cluster.

**Comment by NvTimLiu** [comment]
thanks a lot @revans2 

Relative PATH does not work for --std_input_path, and HDFS path does not work for --rootdir
So the best way is to put resource & testcases `integration_tests` onto every yarn node, then refer the the absolute PATH of on the yarn node.

**Comment by revans2** [comment]
> Relative PATH does not work for --std_input_path, and HDFS path does not work for --rootdir
> So the best way is to put resource & testcases `integration_tests` onto every yarn node, then refer the the `absolute` PATH of on the yarn node.
I really would prefer it if we copy the data from the local std_input_path to the distributed file system (in this case HDFS), and then have an environment variable that you can set that would override std_input_path from being the default  `"$SCRIPTPATH"/src/test/resources/` to whatever it is that we need it to be.

**Comment by NvTimLiu** [comment]
> > Relative PATH does not work for --std_input_path, and HDFS path does not work for --rootdir
> > So the best way is to put resource & testcases `integration_tests` onto every yarn node, then refer the the `absolute` PATH of on the yarn node.
> 
> I really would prefer it if we copy the data from the local std_input_path to the distributed file system (in this case HDFS), and then have an environment variable that you can set that would override std_input_path from being the default `"$SCRIPTPATH"/src/test/resources/` to whatever it is that we need it to be.

Yes, in this case, we can overwrite `$CRIPTPATH' to whatever we need

**Comment by NvTimLiu** [comment]
We are using the common test script `run_pyspark_from_build.sh`, which override the `$CRIPTPATH' to  script path by 
`LOCAL_JAR_PATH=$CLUSTER_WORKDIR`

So we can close this issue now.

https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/blob/main/databricks/pytests-on-databricks.sh#L38
https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/blob/main/emr/pytests-on-emr.sh#L41
https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/blob/main/dataproc/pytests-on-dataproc.sh#L47

**Comment by NvTimLiu** [comment]
close
