### ISSUE TITLE
[FEA] GPU support for the plan RunningWindowFunctionExec on db

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#1791]
**Is your feature request related to a problem? Please describe.**
On databricks, the plan `RunningWindowFunctionExec `, which has not been supported by GPU, will be applied instead of the `WindowExec` when matching some requirements. Then some window related IT tests will fail. 
Some related ssues: https://github.com/NVIDIA/spark-rapids/issues/1680 https://github.com/NVIDIA/spark-rapids/issues/203

**Describe the solution you'd like**
Replace the plan `RunningWindowFunctionExec` with a new or existing GPU plan correctly.

**Additional context**
`RunningWindowRunctionExec` does not exist outside of Databricks, and will NOT be used when

- window function is a SizeBasedWindowFunction, or
- window function is a OffsetWindowFunction, or
- window function is a PythonUDF, or
- window frame specification is not SpecifiedWindowFrame(RowFrame, UnboundedPreceding, CurrentRow)

Since databricks is not open source, so it may not be easy to understand what `RunningWindowRunctionExec` does and how to support it on GPU perfectly.

**Comment by mythrocks** [comment]
For reference, we need the following window spec to reproduce the problem:
```sql
... OVER (PARTITION BY id ORDER BY dt ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
```
Hence, the term `RunningWindowFunctionExec`. Reversing the boundaries (i.e. `CURRENT ROW AND UNBOUNDED FOLLOWING`) does not suffice, for some reason.
