### ISSUE TITLE
[BUG]Running TPCx-BB Query22 (SF1000) failed, when set spark.sql.adaptive.enabled to true

### ISSUE THREAD

**Issue by zhnin** [NVIDIA/spark-rapids#1800]
**Describe the bug**
With AQE enabled (`spark.sql.adaptive.enabled=true`), run  `Q22Like.apply(spark).collect` would stuck and not have any error.
Data size: SF1000. 

**Steps/Code to reproduce bug**
Running `spark-shell --master spark://master:7077`, and
```scala
import com.nvidia.spark.rapids.tests.tpcxbb._
TpcxbbLikeSpark.setupAllParquet(spark, "file:///mnt/vdb/data")
Q22Like.apply(spark).collect
```

**Environment details (please complete the following information)**
 - Environment location: Spark3.0.0, Standalone
 - spark-rapids: branch-0.4, f45a3b7a62cd44830cb285d669f89695faa6e98b
 - Spark configuration
 ```sh
spark.executor.resource.gpu.amount                  1
spark.driver.memory                                 4g
spark.executor.memory                               16g
spark.executor.cores                                10
spark.task.cpus                                     1
spark.task.resource.gpu.amount                      0.10
spark.plugins                                       com.nvidia.spark.SQLPlugin

spark.shuffle.manager                               com.nvidia.spark.rapids.spark300.RapidsShuffleManager
spark.shuffle.service.enabled                       false
spark.rapids.shuffle.transport.enabled              true
spark.executorEnv.UCX_TLS                           cuda_copy,cuda_ipc,tcp,sockcm
spark.executorEnv.UCX_ERROR_SIGNALS
spark.executorEnv.UCX_MAX_RNDV_RAILS                1
spark.executorEnv.UCX_MEMTYPE_CACHE                 n
spark.executorEnv.UCX_RNDV_THRESH                   auto
spark.executorEnv.UCX_CUDA_IPC_CACHE                y

spark.driver.extraClassPath                         /mnt/vdb/spark-rapids/jars/*:/opt/ucx/lib
spark.executor.extraClassPath                       /mnt/vdb/spark-rapids/jars/*:/opt/ucx/lib

spark.sql.adaptive.enabled                          true
```

**Additional context**
If not set `spark.shuffle.manager=com.nvidia.spark.rapids.spark300.RapidsShuffleManager`, it can run with AQE. 

**Expected behavior**
Success running Q22 with UCX and AQE enable.

**Comment by abellina** [comment]
> With AQE enabled (spark.sql.adaptive.enabled=true), run Q22Like.apply(spark).collect would stuck and not have any error.

With `spark.sql.adaptive.enabled=false` does the issue go away?

1. It would useful if you can confirm that there are no errors in the executor logs (both stderr and stdout), as that's where you'd see issues most likely. 
2. I see that you are setting `sockcm` in the `UCX_TLS` settings, why is that? We normally run with `cuda_ipc,cuda_copy,rc,tcp` or `cuda_ipc,cuda_copy,tcp`. It would be worth to figure out if `sockcm` is related.
3. Could you also provide some info as to what GPUs you are using?

**Comment by zhnin** [comment]
> With `spark.sql.adaptive.enabled=false` does the issue go away?
> 
> 1. It would useful if you can confirm that there are no errors in the executor logs (both stderr and stdout), as that's where you'd see issues most likely.
> 2. I see that you are setting `sockcm` in the `UCX_TLS` settings, why is that? We normally run with `cuda_ipc,cuda_copy,rc,tcp` or `cuda_ipc,cuda_copy,tcp`. It would be worth to figure out if `sockcm` is related.
> 3. Could you also provide some info as to what GPUs you are using?
> 4. I assume your network here is TCP and not using Mellanox nics for Infiniband/RoCE.

- Set `spark.sql.adaptive.enabled=false`, it can success run with ucx.
1. Both stderr and stdout has no errors in executor logs. 
2. I delete 'sockcm' from 'UCX_TLS', and set `spark.sql.adaptive.enabled=true`,  it will stuck (always keep shuffle read in stage 26). In the screenshot below you could find shuffle read is 583G in stage 26, and it will increase over time, but shuffle write is 39G. 
3. My environment: 
    - Instance: aliyun ecs.gn6e-c12g1.24xlarge (96vCPU 736GB 8*V100-32GB NVLink)
    - Numbers: single node
![image](https://user-images.githubusercontent.com/14870906/109096682-f4a1bd80-7758-11eb-9b4e-87afc9b145c0.png)

**Comment by zhnin** [comment]
When set `spark.rapids.sql.explain=ALL`, I got some output about "cannot run on GPU". I am not sure it is useful for solving this issue.
```
  *Exec <ProjectExec> will run on GPU
    !Exec <BroadcastHashJoinExec> cannot run on GPU because the broadcast for this join must be on the GPU too
      @Expression <AttributeReference> inv_date_sk#592L could run on GPU
      @Expression <AttributeReference> d_date_sk#152L could run on GPU
      *Exec <ProjectExec> will run on GPU
        !Exec <BroadcastHashJoinExec> cannot run on GPU because the broadcast for this join must be on the GPU too
          @Expression <AttributeReference> inv_warehouse_sk#594L could run on GPU
          @Expression <AttributeReference> w_warehouse_sk#486L could run on GPU
          *Exec <ProjectExec> will run on GPU
            !Exec <BroadcastHashJoinExec> cannot run on GPU because the broadcast for this join must be on the GPU too
              @Expression <AttributeReference> inv_item_sk#593L could run on GPU
              @Expression <AttributeReference> i_item_sk#62L could run on GPU
              !Exec <CustomShuffleReaderExec> cannot run on GPU because Unable to replace CustomShuffleReader due to child not being columnar

```

**Comment by abellina** [comment]
Thanks for providing more info. I agree, it's absolutely weird that we wrote 39.5GiB and are reading 10x that much. That seems like an issue with the plan.

One thing that would help is to get the stack trace of the executors. In the spark UI, while the job is running: Executors tab > find an executor that seems busy > click "Thread dump". This is during the shuffle read stage. Given that this stage ran for at least 14 minutes, it seems to be going above the `spark.network.timeout` which is set to 2 minutes by default (unless it has been tweaked here). I believe this job has two problems: one is that it's re-reading the shuffle input several times, and 2 is that the tasks are likely blocked _spilling_ and not transferring data. 

Note that our support for AQE started with Apache Spark 3.0.1 ([from here](https://nvidia.github.io/spark-rapids/docs/download.html#release-v020)):

> The RAPIDS Accelerator v0.2 introduces Adaptive Query Execution (AQE) for GPUs and leverages columnar processing SPARK-32332 starting from Spark 3.0.1.

Could you retry with spark 3.0.1? And keep in mind the stack trace question above.

**Comment by zhnin** [comment]
> Could you retry with spark 3.0.1? 

Yes, using Spark 3.0.1 can solved my problem. 
Thanks for your help.
