### ISSUE TITLE
[BUG] nightly sort test failure

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1803]
**Describe the bug**
We recently saw one of the nightly 0.4.0 integration test fail against SPARK-3.0.0.

```
src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a DESC NULLS FIRST'>-Decimal(not_null)(7,7)]
```

It passed for all of the other versions of Spark, and nothing has changed recently related to sort, so it appears that this was a very odd case.

It might be related to executor loss, but it is a little hard to tell for sure.  This showed up in the logs.

```
23:48:28  src/main/python/sort_test.py::test_single_sort_in_part[Column<b'a DESC NULLS FIRST'>-Decimal(not_null)(7,7)] 21/02/24 05:48:51 WARN HeartbeatReceiver: Removing executor 0 with no recent heartbeats: 144454 ms exceeds timeout 120000 ms
23:48:28  21/02/24 05:48:51 ERROR TaskSchedulerImpl: Lost executor 0 on XX.XX.XX.XX: Executor heartbeat timed out after 144454 ms
```

**Steps/Code to reproduce bug**
Not sure might have to hack spark to make an executor start to fail heartbeats, but even then I have no idea if it is really related.

**Expected behavior**
It passes all the time, even in the face of failures.

**Comment by sameerz** [comment]
Have not seen this reproduce in the CI environment.  We need to try to manually reproduce the problem.

**Comment by sameerz** [comment]
Have not seen a repro of this failure in the tests.
