### ISSUE TITLE
[BUG] Developer build with local modifications fails during verify phase

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1817]
**Describe the bug**
When performing a `mvn verify` build as a developer, the build will fail if there are any checkouts.  This check was added by #1809 but should only happen on precommit builds, not developer builds.  This behavior should be controlled via a Maven profile that is not enabled by default.

**Steps/Code to reproduce bug**
Make some changes and try to build with `mvn verify`

**Expected behavior**
Developer builds succeed despite checkedout files which are common in developer environments.

**Comment by pxLi** [comment]
sounds reasonable, let me add a profile for it

**Comment by sameerz** [comment]
Closed by #1820
