### ISSUE TITLE
[BUG] branch-0.5 nightly IT FAILED on the The mortgage ETL test "Could not read footer for file: file:/xxx/xxx.snappy.parquet"

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#1844]
**Describe the bug**
The branch-0.5 nightly IT FAILED mortgage ETL test FAILED on  "Could not read footer for file: file:/xxx/xxx.snappy.parquet"

**Steps/Code to reproduce bug**
Run Mortgage ETL in the nightly IT pipeline

**Expected behavior**
Test should PASS

**Additional context**
Related PR https://github.com/NVIDIA/spark-rapids/pull/1808

**Comment by sameerz** [comment]
Will wait for the nightly builds to pass before closing this.

**Comment by NvTimLiu** [comment]
Close the issue as PR merged, and nigthly/IT PASS.
