### ISSUE TITLE
[QST] Why were TPC Benchmarks Removed?

### ISSUE THREAD

**Issue by barnes88** [NVIDIA/spark-rapids#1846]
Recently the TPC benchmarks were [removed from the project repository](https://github.com/NVIDIA/spark-rapids/pull/1826). Why were the benchmarks and results removed? Are there any major modifications that were made to the tpc(like) benchmarks that were in this repo compared to official benchmark query templates or a framework like [this one from databricks?](https://github.com/databricks/spark-sql-perf)

**Comment by sameerz** [comment]
Hi @barnes88, thanks for the question.  We are still using industry standard benchmarks for this project.  We felt it best to keep the benchmarks outside of the repository for the time being and are considering where best to host them.  We did not make any major modifications compared to the queries that are in the databricks repository.
