### ISSUE TITLE
[BUG] SPARK-33723 in 3.2.0+ lets ANSI date parsing to throw exceptions

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1865]
**Describe the bug**
https://issues.apache.org/jira/browse/SPARK-33723 fixed an issue where casting a string to a date with an invalid format would just return null before, but now throws an exception. We need to make sure that we can match it.

**Steps/Code to reproduce bug**
This was found while trying to run 3.2.0 tests.

        "23:59:59.333666Z",
        "T21:34:56.333666Z"

are invalid date formats and they started to throw exceptions. This has been "fixed" in the tests, but no tests were added to be sure that we also throw exceptions in those cases.

**Comment by wjxiz1992** [comment]
I can take this and I also found a similar issue https://github.com/NVIDIA/spark-rapids/issues/1941

**Comment by HaoYang670** [comment]
Could we close this issue, as [PR 3396](https://github.com/NVIDIA/spark-rapids/pull/3396) has addressed the problem?
