### ISSUE TITLE
[FEA] Update GpuAlias to reflect changes made in SPARK-33071 / SPARK-33536

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#1880]
**Is your feature request related to a problem? Please describe.**

There were changes to `Alias` in [this commit](https://github.com/apache/spark/commit/a082f4600b) and we may need to make the same changes in `GpuAlias`.

```
[SPARK-33071][SPARK-33536][SQL] Avoid changing dataset_id of LogicalPlan in join() to not break DetectAmbiguousSelfJoin
```

**Comment by jlowe** [comment]
This was handled in #1272.
