### ISSUE TITLE
[FEA] SPARK-32976: Support column names in INSERT statement

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#1881]
**Is your feature request related to a problem? Please describe.**

Spark added support for column names in INSERT statements in [this commit](https://github.com/apache/spark/commit/2da72593c1) as part of [SPARK-32976](https://issues.apache.org/jira/browse/SPARK-32976).

We should add a test to make sure we also support this.

**Comment by sameerz** [comment]
Spark optimized the physical plan before handing it to the plugin, nothing for the plugin to do.
