### ISSUE TITLE
[FEA] Only copy tags to node with no tags [SPARK-32753]

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#1887]
**Is your feature request related to a problem? Please describe.**
This is to evaluate spark commit : https://github.com/apache/spark/commit/c43460cf82 . 
Need to understand the tags a bit more to see if we could lose tag information - either us tagging will not work on gpu or if we tag it perhaps we lose other tags

**Comment by sameerz** [comment]
Spark optimized the physical plan before handing it to the plugin, nothing for the plugin to do.
