### ISSUE TITLE
[FEA] Fail casting numeric to timestamp by default - [SPARK-31710]

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#1888]
**Is your feature request related to a problem? Please describe.**
Casting from numeric to timestamp is not a  non-standard. Spark added PR to fail casting from numeric to timestamp by default.
Need to check if we have to make changes.

[SPARK-31710][SQL] Fail casting numeric to timestamp by default - https://github.com/apache/spark/commit/f0e6d0ec13
[SPARK-31710][SQL][FOLLOWUP] Allow cast numeric to timestamp by default - https://github.com/apache/spark/commit/1261fac674

**Comment by sameerz** [comment]
Spark optimized the physical plan before handing it to the plugin, nothing for the plugin to do.
