### ISSUE TITLE
[FEA] Allow nested schema pruning through window/sort plans

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#1896]
**Is your feature request related to a problem? Please describe.**
This PR is solves schema pruning not working with window functions - https://github.com/apache/spark/commit/8323c8eb56 . We may need to add tests to see what schema is read on GPU.

**Comment by revans2** [comment]
The changes to this are completely in the logical plan optimizer we don't need to do anything in the plugin to deal with this.
