### ISSUE TITLE
[FEA] Fix the wrong references of the PartialMerge/Final AggregateExpression

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#1898]
**Is your feature request related to a problem? Please describe.**
We have copied code to GpuHashAggregateExec earlier. So need to evaluate if https://github.com/apache/spark/commit/338efee509 should be pulled in and test this.

**Comment by sameerz** [comment]
We need to evaluate the impact of this.  If it is in the hash aggregate, we need to address sooner than later.  After evaluation if we discover the impact is low we will reduce the priority.
