### ISSUE TITLE
[DOC] Benchmark docs need updating for can't find benchmark.py

### ISSUE THREAD

**Issue by qinaigonghe** [NVIDIA/spark-rapids#1900]
## Report incorrect documentation

**Location of incorrect documentation**
Provide links and line numbers if applicable.
https://github.com/NVIDIA/spark-rapids/blob/main/integration_tests/src/main/python/benchmark.py
**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.
Automating Benchmarks
For convenience, the benchmark.py script is provided, allowing benchmarks to be run in an automated way with multiple configurations. Example usage is provided in the documentation within the script.
![image](https://user-images.githubusercontent.com/38580039/110412933-fb6cf080-80c7-11eb-91c0-f2b624ed52bf.png)
https://github.com/NVIDIA/spark-rapids/blob/main/integration_tests/src/main/python/benchmark.py
**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by sameerz** [comment]
This will be updated when we update the gh-pages for 0.4

**Comment by sameerz** [comment]
This has been resolved, since we removed references to benchmarks from the 0.4 release.
