### ISSUE TITLE
[FEA] Group exception messages in catalyst/expressions

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#1924]
**Is your feature request related to a problem? Please describe.**
These PR's are mostly to  help with standardization of error messages and its maintenance. May not be required for us. Filed issue to get others' perspective.
https://github.com/apache/spark/commit/cde697a479, https://github.com/apache/spark/commit/b12e9a4ea6, https://github.com/apache/spark/commit/cc1d9d25fb, https://github.com/apache/spark/commit/6dca2e5d35

**Comment by sperlingxx** [comment]
IMHO, we can close this issue, since most of the error messages are compile-time ones. The only GPU related one is `QueryExecutionErrors.castingCauseOverflowError`. However, we can not apply this message because it is inconvenient to dump the exact overflow values in columnar execution.
