### ISSUE TITLE
Add new rule to push down the foldable expressions through CaseWhen/If

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#1952]
There is a change in the BinaryExpression that might lead to changes on our side.

**Additional context**
Please look at Spark [commit](https://github.com/apache/spark/commit/06b1bbbbab) for more details

**Comment by jlowe** [comment]
This is all at the logical plan level, does not affect the RAPIDS Accelerator which operates on the physical plan.
