### ISSUE TITLE
Follow on issues for GpuSize

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#1974]
The GpuSize work #1972 will fix the failing nightly tests, so we are going to merge it in fast, but there are a few things that should be fixed in follow on work.

1. cudf has an API to do exactly what we want. We should use that API instead of hacking together something ourselves.
2. The signature for the input parameters are not strictly correct.  They are not technically wrong either.  The problem is that they say that we can support anything as the child of a map or array, but we have not plumbed through a lot of things calendar interval, or UDT. For the types that we support we should either extend the tests to cover some examples of these, or we should remove them from the list of supported types.  Just so we are cautious and also so our documentation is as accurate as possible.

On a side note I should have a PR up shortly for `countElements` so we can get this done ASAP.

**Comment by revans2** [comment]
I just put up the PR https://github.com/rapidsai/cudf/pull/7651 in CUDF for the changes that are needed there to do this the right way.

**Comment by sperlingxx** [comment]
Thank you, @revans2. I've put up a PR to fix this.

**Comment by sameerz** [comment]
@sperlingxx is this resolved?  If so can you mark the issue closed?
