### ISSUE TITLE
Data validation of TPCDS q44

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#1979]
**Describe the bug**
q44 seems a non-deterministic query.
Both GPU and CPU got different outputs when running multiple times.
We should figure out how to validate our GPU output with CPU output.

**Steps/Code to reproduce bug**
Run TPCDS q44.

**Expected behavior**
Find a way to validate GPU output with CPU output.

**Comment by revans2** [comment]
It would be ideal to try and validate the answer against the official TPC-DS results.  But from what I can see they don't allow for ambiguity in the answer so we might need to do some more research.
