### ISSUE TITLE
[FEA] `GpuWindowInPandas` supports sending multiple groups to Python.

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#1980]
The same with Spark logic, currently `GpuWindowInPandas` sends only one group one time to Python, the performance is quite bad when there are too many small groups for GPU.
Thanks to the Python implementation, we can send multiple groups (a whole batch) to Python one time for bounded windows, without change in Python. It will be good to have this.

**Comment by jlowe** [comment]
@firestarman is this issue still relevant?

**Comment by firestarman** [comment]
I think we can close this now, since it is low priority and no plan for it. 
Closing
