### ISSUE TITLE
[FEA] More testing on Databricks

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#1989]
**Is your feature request related to a problem? Please describe.**
issue https://github.com/NVIDIA/spark-rapids/issues/1985 was discovered on databricks with a very simple command. It turns out it was related to job groups, but if we had more extensive testing through notebooks on databricks this likely would have been found before our release.

Our integration tests run on the cluster but I'm guessing its not the same environment as a notebook so perhaps we need more notebook type tests.

**Comment by GaryShen2008** [comment]
@tgravescs We have some LHA testings by using notebooks on Azure Databricks.
Do we need any other test cases?

**Comment by tgravescs** [comment]
ok, great, did it fail with https://github.com/NVIDIA/spark-rapids/issues/1985 or are those newer then that issue?

**Comment by tgravescs** [comment]
ok lets close this then
