### ISSUE TITLE
[QST] Issue in setting up GPU based Spark Cluster

### ISSUE THREAD

**Issue by gokulkrish21** [NVIDIA/spark-rapids#2004]
**What is your question?**
I am trying to setup the rapids on Spark and do some testing. Nvidia GPU installed in the VM is 
NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2

Without using Spark, I was able to test the GPU usage using the standalone sample code which uses cudf, cuml libraries.

However when I try to use the rapids on Spark Cluster, I am unable to setup the cluster properly. The executors are not staying up when I enable GPU using the following properties and run the code below. Here is the list of all properties, that has been set.

[('spark.locality.wait', '0s'),
 ('zeppelin.pyspark.useIPython', 'true'),
 ('spark.app.id', 'app-20210323164824-0056'),
 ('zeppelin.spark.concurrentSQL', 'true'),
 ('spark.plugins.internal.conf.com.nvidia.spark.SQLPlugin.spark.rapids.sql.concurrentGpuTasks',
  '1'),
 ('spark.driver.memory', '1g'),
 ('spark.webui.yarn.useProxy', 'false'),
 ('spark.useHiveContext', 'true'),
 ('spark.app.startTime', '1616532503834'),
 ('spark.master', 'spark://spark-master:7077'),
 ('spark.plugins.internal.conf.com.nvidia.spark.SQLPlugin.spark.rapids.sql.explain',
  'ALL'),
 ('PYSPARK_PYTHON', '/root/anaconda3/envs/rapids/bin/python'),
 ('spark.jars',
  'file:/zeppelin/interpreter/spark/spark-interpreter-0.9.0.jar'),
 ('spark.plugins.internal.conf.com.nvidia.spark.SQLPlugin.spark.rapids.shims-provider-override',
  'com.nvidia.spark.rapids.shims.spark301.SparkShimServiceProvider'),
 ('zeppelin.kotlin.shortenTypes', 'true'),
 ('zeppelin.interpreter.localRepo', '/zeppelin/local-repo/spark'),
 ('spark.rapids.shims-provider-override',
  'com.nvidia.spark.rapids.shims.spark301.SparkShimServiceProvider'),
 ('spark.driver.host', '09c700d9d5e5'),
 ('spark.driver.cores', '2'),
 ('zeppelin.spark.printREPLOutput', 'true'),
 ('zeppelin.spark.enableSupportedVersionCheck', 'true'),
 ('zeppelin.spark.maxResult', '1000'),
 ('spark.plugins.internal.conf.com.nvidia.spark.SQLPlugin.spark.rapids.memory.pinnedPool.size',
  '2G'),
 ('spark.executor.id', 'driver'),
 ('zeppelin.interpreter.connection.poolsize', '10'),
 ('spark.worker.resource.gpu.discoveryScript',
  '/notebook/getGpusResources.sh'),
 ('zeppelin.R.image.width', '100%'),
 ('spark.rapids.sql.explain', 'ALL'),
 ('spark.plugins', 'com.nvidia.spark.SQLPlugin'),
 ('zeppelin.spark.ui.hidden', 'false'),
 ('spark.sql.shuffle.partitions', '10'),
 ('zeppelin.spark.deprecatedMsg.show', 'true'),
 ('PYSPARK_DRIVER_PYTHON', '/root/anaconda3/envs/rapids/bin/python'),
 ('spark.executor.extraClassPath',
  '/spark/jars/cudf-0.18-cuda11.jar:/spark/jars/rapids-4-spark_2.12-0.3.0.jar'),
 ('zeppelin.spark.sql.interpolation', 'false'),
 ('spark.worker.resource.gpu.amount', '1'),
 ('spark.driver.extraClassPath',
  '/zeppelin/interpreter/spark/*:::/zeppelin/interpreter/zeppelin-interpreter-shaded-0.9.0.jar:/zeppelin/interpreter/spark/spark-interpreter-0.9.0.jar:/spark/jars/cudf-0.18-cuda11.jar:/spark/jars/rapids-4-spark_2.12-0.3.0.jar'),
 ('spark.sql.files.maxPartitionBytes', '512m'),
 ('spark.rapids.sql.enabled', 'true'),
 ('zeppelin.R.cmd', 'R'),
 ('spark.driver.port', '45411'),
 ('spark.plugins.internal.conf.com.nvidia.spark.SQLPlugin.spark.rapids.sql.enabled',
  'true'),
 ('spark.repl.class.uri', 'spark://09c700d9d5e5:45411/classes'),
 ('spark.rapids.memory.pinnedPool.size', '2G'),
 ('zeppelin.interpreter.output.limit', '102400'),
 ('spark.rapids.sql.concurrentGpuTasks', '1'),
 ('spark.executor.instances', '2'),
 ('spark.submit.deployMode', 'client'),
 ('zeppelin.R.knitr', 'true'),
 ('spark.driver.extraJavaOptions',
  ' -Dfile.encoding=UTF-8 -Dlog4j.configuration=file:///zeppelin/conf/log4j.properties -Dlog4j.configurationFile=file:///zeppelin/conf/log4j2.properties -Dzeppelin.log.file=/logs/zeppelin-interpreter-spark-shared_process--09c700d9d5e5.log'),
 ('zeppelin.spark.useHiveContext', 'true'),
 ('spark.executor.memory', '2g'),
 ('spark.sql.extensions',
  'com.nvidia.spark.rapids.SQLExecPlugin,com.nvidia.spark.udf.Plugin'),
 ('spark.repl.class.outputDir', '/tmp/spark4941082472165469018'),
 ('spark.scheduler.mode', 'FAIR'),
 ('zeppelin.R.render.options',
  "out.format = 'html', comment = NA, echo = FALSE, results = 'asis', message = F, warning = F, fig.retina = 2"),
 ('spark.app.initial.jar.urls',
  'spark://09c700d9d5e5:45411/jars/spark-interpreter-0.9.0.jar'),
 ('spark.executor.cores', '2'),
 ('spark.executor.resource.gpu.discoveryScript',
  '/notebook/getGpusResources.sh'),
 ('spark.app.name', 'spark-shared_process'),
 ('spark.executor.resource.gpu.amount', '1'),
 ('spark.task.cpus', '1'),
 ('spark.submit.pyFiles', ''),
 ('zeppelin.spark.concurrentSQL.max', '10'),
 ('zeppelin.spark.sql.stacktrace', 'true'),
 ('zeppelin.spark.scala.color', 'true'),
 ('SPARK_HOME', '/spark')]

When I execute the sample code, 
val df = sc.makeRDD(1 to 10000000, 6).toDF
val df2 = sc.makeRDD(1 to 10000000, 6).toDF

df.select( $"value" as "a").join(df2.select($"value" as "b"), $"a" === $"b").count

The 1st two lines executes and last line does not execute at all. It is waiting forever. When I check the Cluster UI, all the workers are running and alive on 8080. But on 4040, when I check the executors tab, I can see only the driver is up and all the executors are dead and they are trying to bring them up but no success.

On the executor nodes, this is the log I am seeing
21/03/23 16:54:23 INFO Worker: Executor app-20210323164824-0056/693 finished with state EXITED message Command exited with code 1 exitStatus 1
21/03/23 16:54:23 INFO ExternalShuffleBlockResolver: Clean up non-shuffle and non-RDD files associated with the finished executor 693
21/03/23 16:54:23 INFO ExternalShuffleBlockResolver: Executor is not registered (appId=app-20210323164824-0056, execId=693)
21/03/23 16:54:23 INFO Worker: Asked to launch executor app-20210323164824-0056/697 for spark-shared_process
21/03/23 16:54:23 INFO SecurityManager: Changing view acls to: root
21/03/23 16:54:23 INFO SecurityManager: Changing modify acls to: root
21/03/23 16:54:23 INFO SecurityManager: Changing view acls groups to:
21/03/23 16:54:23 INFO SecurityManager: Changing modify acls groups to:
21/03/23 16:54:23 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
21/03/23 16:54:23 INFO ExecutorRunner: Launch command: "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" "-cp" "/spark/jars/cudf-0.18-cuda11.jar:/spark/jars/rapids-4-spark_2.12-0.3.0.jar:/spark/conf/:/spark/jars/*" "-Xmx2048M" "-Dspark.driver.port=45411" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@09c700d9d5e5:45411" "--executor-id" "697" "--hostname" "172.19.0.2" "--cores" "2" "--app-id" "app-20210323164824-0056" "--worker-url" "spark://Worker@172.19.0.2:39207" "--resourcesFile" "/spark/work/app-20210323164824-0056/697/resource-executor-6836323275461957192.json"

How should I fix this issue? Any help would be much appreciated

**Comment by tgravescs** [comment]
the logs you have above look like the standalone worker logs, can you look at the actual executor logs? If they are dead, I would expect to see an error there. Its likely due to this:

'/spark/jars/cudf-0.18-cuda11.jar:/spark/jars/rapids-4-spark_2.12-0.3.0.jar'),

Those jars don't match, 0.3.0 release should use cuda 0.17, see the Download page for the supported versions.  We just released a 0.4 version you may want to pick up. that would use cudf 0.18.1

Also note you said that you are using cuda 11.2 - but that is the driver version. cudf only supports up to cuda 11.0. You can install the cuda 11.0 runtime while leaving the driver at 11.2 if you don't already have it installed.

**Comment by sameerz** [comment]
@gokulkrish21 did the above response help?

**Comment by gokulkrish21** [comment]
Yes. It did solve the issue. It is because of compatibility issues with the jar. Thanks for the suggestion
