### ISSUE TITLE
[FEA] Support creation of 2D array type

### ISSUE THREAD

**Issue by Dooyoung-Hwang** [NVIDIA/spark-rapids#2011]
### Creation of 2D array type with GPU plan

I request a feature to create a ArrayType[ArrayType[AtomicType]] by applying the Array function to ArrayType.

- Test code
```python
data = [(1,0.1, 0.4), (2, 0.2, 0.5), (3, -1.0, 2.2)]

schema = StructType([ \
    StructField("a",IntegerType(),True), \
    StructField("b",FloatType(),True), \
    StructField("c",FloatType(),True)
  ])

df1 = spark.createDataFrame(data=data,schema=schema).withColumn("arr1", array("b", "c")).withColumn("arrOfArray", array("arr1"))
print(df1._jdf.queryExecution())
```

- Output message from driver log.
  !Expression array(array(b#6029, c#6030)) cannot run on GPU because expression CreateArray array(b#6029, c#6030) produces an unsupported type ArrayType(FloatType,true); expression CreateArray array(array(b#6029, c#6030)) produces an unsupported type ArrayType(ArrayType(FloatType,true),false)

**Comment by revans2** [comment]
This should be doable.  There really is only one thing preventing this from fully being implemented #1902. This is not a blocker, because we could just disallow cases where we cannot make it work.

**Comment by sameerz** [comment]
Depends on https://github.com/rapidsai/cudf/issues/5887

**Comment by sameerz** [comment]
Depends on https://github.com/rapidsai/cudf/issues/8077

**Comment by wbo4958** [comment]
The current native CUDF has supported the nested List data type and the java bindings seems only support 1-D List build from ColumnVector. I can think of 2 solutions based on the above information.

The first one is to leverage the existing [makeList](https://github.com/rapidsai/cudf/blob/branch-0.20/java/src/main/native/src/ColumnVectorJni.cpp#L126) API to accept ArrayList<ArrayList<ColumnVector> > (2D ColumnVector), and then 
1. flatten the columns to 1D to leverage the cudf::interleave_columns to generate child data column
2. generate child offset according to dimensions of columns
3. create a nested child list column
4. generate the parent offset
5. create a parent list column

The second one is to ask cudf side to provide an API to create nested list columns.

the advantage of 1st solution is we don't depend on anything, the  disadvantage of 1st solution is we can support 2D, but we don't support 3D, 4D ...

The advantage of 2nd solution is we can support any dimensions array type. the disadvantage is we need to depend on cudf API.

Although I have a sketch to make the 1st solution work, I still prefer to the 2nd solution

@revans2 what's your opinion?

**Comment by sperlingxx** [comment]
Is [this work](https://github.com/rapidsai/cudf/pull/8046) helpful to current issue?

**Comment by wbo4958** [comment]
> Is [this work](https://github.com/rapidsai/cudf/pull/8046) helpful to current issue?

Wow, yeah, the PR is what the 2nd solution needs. Great.

**Comment by wbo4958** [comment]
This Feature should depend on https://github.com/rapidsai/cudf/pull/8046 and https://github.com/rapidsai/cudf/pull/8111
