### ISSUE TITLE
[FEA] A way for user to find out the plugin version and cudf version in REPL

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2018]
Currently, there is no way for a user to determine what version of plugin and cudf is the spark-shell started with. A user can list the jars if he is running Spark with jars loaded, but I think there should be a user-friendly way for the user to find the version like Spark allows by typing `sc.version`. 

We can also print the version when Spark-shell is first loaded if its an easy thing to do

**Comment by gerashegalov** [comment]
re: print in repl, it's relevant for non-interactive use cases too, so we should log it properly on the Driver and Executors. It will help speed up diagnostics of potential issues. Also in the past I used to build version inventory dashboards using log search engines

**Comment by jlowe** [comment]
Agree with @gerashegalov.  The plugin already emits a warning on startup that it's present, we should add the plugin version to that log message. Bonus points if it also emits the cudf version being used, which the plugin already looks up during startup.
