### ISSUE TITLE
[BUG] The result of casting string to decimal is not identical to Apache Spark

### ISSUE THREAD

**Issue by sperlingxx** [NVIDIA/spark-rapids#2019]
**Describe the bug**
Currently string to decimal type on the GPU might produce results which slightly differed from the correct results when the string 
represents any number exceeding the max precision that  the operation CAST_STRING_TO_FLOAT can keep. For instance, the GPU returns 99999999999999987 for input string "99999999999999999".

The cause of divergence is that we can not directly cast strings containing scientific notation to decimal via cuDF API. So, we have to cast strings to floats firstly. Then, cast floats to decimals. The first step may lead to precision loss.

**Steps/Code to reproduce bug**
Here are samples to produce inconsistent results:
* cast("99999999999999999" to Decimal(18, 0))
    * 99999999999999999(CPU) vs 99999999999999987(GPU)
* cast("999999999999999" to Decimal(18, -2))
    * 999999999999999.00(CPU) vs 999999999999999.10(GPU)

**Expected behavior**
The GPU runtime can produce exact same results as Apache Spark. 

**Additional context**
Current issue is related to issue #1625 and PR #1999.

**Comment by revans2** [comment]
Does this depend on https://github.com/rapidsai/cudf/issues/7665

**Comment by sameerz** [comment]
@razajafri @sperlingxx is this resolved since PR #4081 is closed?

**Comment by razajafri** [comment]
Yes, the PR even has `fixes 2019` in the description, it should've been autoclosed, no?
