### ISSUE TITLE
[TEST] run the pands udf using cudf on Databricks

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2026]
**Is your feature request related to a problem? Please describe.**
Right now we don't run the pandas udf using cudf tests on Databricks because we haven't setup the conda environment.

We should test this at some point at least manually during release process but ideally running nightly.

We have documentation on how to make that work here: https://confluence.nvidia.com/display/SPARK/How+to+enable+cuDF+Pandas+UDF+on+Azure+Databricks

If there is anything special the end user would need to do we should put in our regularly released documents.

**Comment by tgravescs** [comment]
docs should be covered by https://github.com/NVIDIA/spark-rapids/pull/2025

**Comment by NvTimLiu** [comment]
Working on the issue
