### ISSUE TITLE
[BUG] Window tests in qa_nightly_select_test.py fail on Databricks

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#203]
**Describe the bug**

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

Running the integration tests on Databricks fails with a new RunningWindowFunc not on the GPU;

e = IllegalArgumentException(‘Part of the plan is not columnar class com.databricks.sql.execution.window.RunningWindowFunc...:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:251)\n\tat java.lang.Thread.run(Thread.java:748)\n’, None

```
E   pyspark.sql.utils.IllegalArgumentException: Part of the plan is not columnar class com.databricks.sql.execution.window.RunningWindowFunctionExec
E   RunningWindowFunction [row_number() windowspecdefinition(dateF#72613, dateF#72613 ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) AS row_num#72647, dateF#72613], [dateF#72613], [dateF#72613 ASC NULLS FIRST]
E   +- GpuColumnarToRow false
E      +- !GpuSort [dateF#72613 ASC NULLS FIRST, dateF#72613 ASC NULLS FIRST], false, RequireSingleBatch, 0
E         +- GpuCoalesceBatches RequireSingleBatch
E            +- !GpuColumnarExchange gpuhashpartitioning(dateF#72613, 200), true, [id=#167268]
E               +- !GpuProject [dateF#72613]
E                  +- GpuRowToColumnar TargetSize(2147483647)
E                     +- Scan ExistingRDD[strF#72603,byteF#72604,shortF#72605,intF#72606,longF#72607L,floatF#72608,doubleF#72609,decimalF#72610,booleanF#72611,timestampF#72612,dateF#72613]
```

**Comment by tgravescs** [comment]
@sameerz  I don't think this should be P2 for the 0.2 release because all that happens is it falls back to the CPU and we don't have any customers currently hitting this issue.

**Comment by sameerz** [comment]
@tgravescs If we are safely falling back to the CPU then I will label it as P3.

**Comment by tgravescs** [comment]
duplicat eof https://github.com/NVIDIA/spark-rapids/issues/1791
