### ISSUE TITLE
[FEA] Audit  [SPARK-34152][SQL] Make CreateViewStatement.child to be LogicalPlan's children so that it's resolved in analyze phase

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2030]
Not totally sure if this is going to impact us or not.

My main concern is because if a CreateViewCommand is a part of the physical plan we might end up inserting a column to row transition needlessly which could effect queries that use the view.  They would not be incorrect, they would just be a lot slower than we want them to be.

https://github.com/apache/spark/commit/714ff73

**Comment by sperlingxx** [comment]
Hi @revans2, after running some demos, I found that `CreateViewCommand` did not occur in the subsequent queries who use the view created by itself.
IIUC, `CreateViewCommand` is only responsible for registering the temp view in the catalog. When we read the temp view in subsequent subquires, Spark analyzer resolves the relation as [`View`](https://github.com/apache/spark/blob/master/sql%2Fcatalyst%2Fsrc%2Fmain%2Fscala%2Forg%2Fapache%2Fspark%2Fsql%2Fcatalyst%2Fplans%2Flogical%2FbasicLogicalOperators.scala#L565) wrapped by [`SubqueryAlias`](https://github.com/apache/spark/blob/master/sql%2Fcatalyst%2Fsrc%2Fmain%2Fscala%2Forg%2Fapache%2Fspark%2Fsql%2Fcatalyst%2Fplans%2Flogical%2FbasicLogicalOperators.scala#L1287). And the View here will be eliminated by subsequent rules as well.
Below is a demo:
```scala
val df = (1 to 100000).toDF("a").selectExpr("a", "(a % 10) as b").groupBy(col("b")).agg("a" -> "sum")
df.createTempView("ttt")
val ret = spark.sql("select * from ttt")
ret.explain(true)
```

```
== Parsed Logical Plan ==
'Project [*]
+- 'UnresolvedRelation [ttt], [], false

== Analyzed Logical Plan ==
b: int, sum(a): bigint
Project [b#135, sum(a)#140L]
+- SubqueryAlias ttt
   +- View (`ttt`, [b#135,sum(a)#140L])
      +- Aggregate [b#135], [b#135, sum(a#133) AS sum(a)#140L]
         +- Project [a#133, (a#133 % 10) AS b#135]
            +- Project [value#130 AS a#133]
               +- LocalRelation [value#130]

== Optimized Logical Plan ==
Aggregate [b#135], [b#135, sum(a#133) AS sum(a)#140L]
+- LocalRelation [a#133, b#135]

== Physical Plan ==
*(2) HashAggregate(keys=[b#135], functions=[sum(a#133)], output=[b#135, sum(a)#140L])
+- Exchange hashpartitioning(b#135, 200), ENSURE_REQUIREMENTS, [id=#418]
   +- *(1) HashAggregate(keys=[b#135], functions=[partial_sum(a#133)], output=[b#135, sum#145L])
      +- *(1) LocalTableScan [a#133, b#135]
```

```
