### ISSUE TITLE
[BUG] NDS q14a fails with "GpuColumnarToRow does not implement doExecuteBroadcast"

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2042]
**Describe the bug**

NDS q14a fails with:

```
Caused by: java.lang.UnsupportedOperationException: GpuColumnarToRow does not implement doExecuteBroadcast
	at org.apache.spark.sql.execution.SparkPlan.doExecuteBroadcast(SparkPlan.scala:298)
	at org.apache.spark.sql.execution.InputAdapter.doExecuteBroadcast(WholeStageCodegenExec.scala:515)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeBroadcast$1(SparkPlan.scala:193)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.executeBroadcast(SparkPlan.scala:189)
	at org.apache.spark.sql.execution.joins.BroadcastHashJoinExec.prepareBroadcast(BroadcastHashJoinExec.scala:203)
	at org.apache.spark.sql.execution.joins.BroadcastHashJoinExec.prepareRelation(BroadcastHashJoinExec.scala:217)
```

**Steps/Code to reproduce bug**

- Spark 3.0.2 or 3.1.1
- SF=100 or SF=1000
- AQE on
- Decimal support disabled
- NDS data with Decimals in it

**Expected behavior**

Query should not fail.

**Comment by jlowe** [comment]
@andygrove can you run with `spark.rapids.sql.explain=ALL`?  I'm curious what the plans look like that could cause GpuColumnarToRow to be invoked in this context.  I'm assuming this query runs without problems with AQE=off, is that the case?

**Comment by andygrove** [comment]
Correct, the query works fine with AQE off. It also works fine with AQE on and decimal support enabled. The full log is quite large (6MB) but this portion may be helpful:

```
Caused by: java.util.concurrent.ExecutionException: org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
ShuffleQueryStage 3
+- Exchange SinglePartition, ENSURE_REQUIREMENTS, [id=#18032]
   +- *(4) HashAggregate(keys=[], functions=[partial_avg(CheckOverflow((promote_precision(cast(cast(quantity#869 as decimal(10,0)) as decimal(12,2))) * promote_precision(cast(list_price#870 as decimal(12,2)))), DecimalType(18,2), true))], output=[sum#981, count#982L])
      +- Union
         :- *(1) Project [ss_quantity#140 AS quantity#869, ss_list_price#142 AS list_price#870]
         :  +- *(1) BroadcastHashJoin [ss_sold_date_sk#130], [d_date_sk#492], Inner, BuildRight, false
         :     :- *(1) Filter isnotnull(ss_sold_date_sk#130)
         :     :  +- *(1) ColumnarToRow
         :     :     +- FileScan parquet [ss_sold_date_sk#130,ss_quantity#140,ss_list_price#142] Batched: true, DataFilters: [isnotnull(ss_sold_date_sk#130)], Format: Parquet, Location: InMemoryFileIndex[file:/mnt/tpcds-parquet-100GB-decimal/store_sales.dat], PartitionFilters: [], PushedFilters: [IsNotNull(ss_sold_date_sk)], ReadSchema: struct<ss_sold_date_sk:int,ss_quantity:int,ss_list_price:decimal(7,2)>
         :     +- GpuColumnarToRow false
         :        +- BroadcastQueryStage 0
         :           +- ReusedExchange [d_date_sk#492], GpuBroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, true] as bigint)),false), [id=#3229]
         :- *(2) Project [cs_quantity#18 AS quantity#871, cs_list_price#20 AS list_price#872]
         :  +- *(2) BroadcastHashJoin [cs_sold_date_sk#0], [d_date_sk#492], Inner, BuildRight, false
         :     :- *(2) Filter isnotnull(cs_sold_date_sk#0)
         :     :  +- *(2) ColumnarToRow
         :     :     +- FileScan parquet [cs_sold_date_sk#0,cs_quantity#18,cs_list_price#20] Batched: true, DataFilters: [isnotnull(cs_sold_date_sk#0)], Format: Parquet, Location: InMemoryFileIndex[file:/mnt/tpcds-parquet-100GB-decimal/catalog_sales.dat], PartitionFilters: [], PushedFilters: [IsNotNull(cs_sold_date_sk)], ReadSchema: struct<cs_sold_date_sk:int,cs_quantity:int,cs_list_price:decimal(7,2)>
         :     +- GpuColumnarToRow false
         :        +- BroadcastQueryStage 1
         :           +- ReusedExchange [d_date_sk#492], GpuBroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, true] as bigint)),false), [id=#3229]
         +- *(3) Project [ws_quantity#234 AS quantity#873, ws_list_price#236 AS list_price#874]
            +- *(3) BroadcastHashJoin [ws_sold_date_sk#216], [d_date_sk#492], Inner, BuildRight, false
               :- *(3) Filter isnotnull(ws_sold_date_sk#216)
               :  +- *(3) ColumnarToRow
               :     +- FileScan parquet [ws_sold_date_sk#216,ws_quantity#234,ws_list_price#236] Batched: true, DataFilters: [isnotnull(ws_sold_date_sk#216)], Format: Parquet, Location: InMemoryFileIndex[file:/mnt/tpcds-parquet-100GB-decimal/web_sales.dat], PartitionFilters: [], PushedFilters: [IsNotNull(ws_sold_date_sk)], ReadSchema: struct<ws_sold_date_sk:int,ws_quantity:int,ws_list_price:decimal(7,2)>
               +- GpuColumnarToRow false
                  +- BroadcastQueryStage 2
                     +- ReusedExchange [d_date_sk#492], GpuBroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, true] as bigint)),false), [id=#3229]

        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
        ... 108 more
```

Let me know if you want me to send you the full log.

**Comment by andygrove** [comment]
The issue appears to be related to exchange re-use. We have a `GpuBroadcastExchange` that is correctly used within a `GpuBroadcastHashJoin` but then gets reused later within a CPU `BroadcastHashJoin`.

**Comment by andygrove** [comment]
I also confirmed that the query completes successfully if I disable exchange reuse in Spark.

**Comment by andygrove** [comment]
For this query, one reason that this only happens with AQE on is that the re-used broadcast exchange is part of a BHJ that actually started out as a SHJ and got optimized by AQE. Turning off BHJ also makes the query run.

**Comment by andygrove** [comment]
@revans2 Could I get your opinion on this one when you have time? I don't have a solution for this issue.

**Comment by revans2** [comment]
@andygrove Sorry I am trying to get caught up on several things and you just were not noisy enough yet.

> For this query, one reason that this only happens with AQE on is that the re-used broadcast exchange is part of a BHJ that actually started out as a SHJ and got optimized by AQE. Turning off BHJ also makes the query run.

I don't know what that means. Is it because we are doing the broadcast already in another area, but then AQE decides it should become a broadcast join the broadcast is reused?

In all of the other places in the code we disallow a GpuBroadcastExchange from being used by a CPU BroadcastHashJoin, with exchange reuse or not.  The data that we send is just not the same.  On the GPU we just send the raw table.  On the CPU side it sends a hash table over that is already setup for probing the table.

**Comment by andygrove** [comment]
> I don't know what that means. Is it because we are doing the broadcast already in another area, but then AQE decides it should become a broadcast join the broadcast is reused?

Yes, exactly that.

**Comment by revans2** [comment]
So is the exchange reuse happening because AQE sees it all still on the CPU when it makes that decision?

**Comment by andygrove** [comment]
Yes, I think so. Here is the relevant code in `AdaptiveSparkPlanExec`:

```scala
var newStage = newQueryStage(newPlan)
if (conf.exchangeReuseEnabled) {
  // Check the `stageCache` again for reuse. If a match is found, ditch the new stage
  // and reuse the existing stage found in the `stageCache`, otherwise update the
  // `stageCache` with the new stage.
  val queryStage = context.stageCache.getOrElseUpdate(e.canonicalized, newStage)
  if (queryStage.ne(newStage)) {
    newStage = reuseQueryStage(queryStage, e)
  }
}
```

Our rules get applied in `newQueryStage` but then exchange re-use happens after that.

**Comment by andygrove** [comment]
I see now that the exchange re-use is based on the canonicalized plan of the original `Exchange` before we replace it so that maybe explains what is going on.

**Comment by andygrove** [comment]
This does seem to be a bug in Spark because it is re-using a columnar exchange where a non-columnar exchange is required. Fixing this very specific issue may be as simple as changing the Spark code to:

```scala
val queryStage = context.stageCache.getOrElseUpdate(e.canonicalized, newStage)
if (queryStage.ne(newStage) &&
    queryStage.supportsColumnar == newStage.supportsColumnar) {
  newStage = reuseQueryStage(queryStage, e)
}
```

I will try this out next. 

@tgravescs fyi on this potential Spark change.

**Comment by andygrove** [comment]
I filed an issue against Spark for this and am working on creating a PR there.

https://issues.apache.org/jira/browse/SPARK-35093

**Comment by andygrove** [comment]
I have a working solution now to work around this issue by supporting a compatible columnar-to-row transition for GPU broadcasts. I should have a PR up today.
