### ISSUE TITLE
[DOC] pandas udf section name confusing

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2053]
## Report incorrect documentation

the pandas udf documentation section name is called "GPU Scheduling For Pandas UDF".  

I'm wondering why we call this "Gpu Scheduling".  Should this just be GPU Support for Pandas UDF or something like that.  There is a scheduling aspect to it but this is a high level overview of how to enable pandas UDF to run with GPU support.

Shouldn't we also state what it is and how you use it?  I don't see a reason to document how to enable it without how to use it.

Also we have a section: 

Following configuration settings are also for GPU Scheduling for Pandas UDF

But say nothing about those configs settings, it might be nice to state what you might want to set them to.

**Comment by firestarman** [comment]
Yes, there is much things to do for the Pandas UDF doc. 

This section is moved from the get-started doc, so it should be updated accordingly.

**Comment by firestarman** [comment]
@wjxiz1992 will help on this.
