### ISSUE TITLE
[FEA] Consider contributing Spark changes to support columnar adaptive plans

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2067]
**Is your feature request related to a problem? Please describe.**

Spark's `AdaptiveSparkPlanExec` assumes row-based output (`supportsColumnar` returns `false` and `doExecute` is implemented but there is no `doExecuteColumnar` method).

In https://github.com/NVIDIA/spark-rapids/pull/2064 we are adding a workaround so that we can access columnar output from adaptive plans and write that output directly to disk without converting to rows but we should see if it makes sense to update Spark so that we can eventually avoid this workaround, which uses reflection to access private Spark methods.

**Describe the solution you'd like**
This needs more research. One option would be to make `getFinalPhysicalPlan` accessible so that we can execute the plan and then see if it is columnar or not, and call the appropriate execute methods directly on that plan.

**Comment by sameerz** [comment]
Removing the 0.5 project since the PR fix will go into Apache Spark.

**Comment by tgravescs** [comment]
Pr is merged into apache spark:
https://github.com/apache/spark/pull/32195#issuecomment-820673704
