### ISSUE TITLE
[DOC] Add documentation for using GPU Direct Storage for spilling

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#2070]
**Report needed documentation**
The 0.5 release will include functionality (in beta) for using GPU Direct Storage to spill data.  

**Describe the documentation you'd like**
Users need to understand what GDS is, what the minimum requirements are, how to install the additional required GDS libraries, and how to know whether GDS spilling is working.  This should go in the additional-functionality section of the documentation.  

**Steps taken to search for needed documentation**
https://docs.nvidia.com/gpudirect-storage/troubleshooting-guide/index.html

**Comment by sameerz** [comment]
Moving projects as we are going to target GDS to 0.6.

**Comment by sameerz** [comment]
@rongou is this closed by PR #2387 ?

**Comment by rongou** [comment]
Yes.
