### ISSUE TITLE
Make creation of a Scalar decimal value simpler

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2076]
So the original code that this was commented on is 
```
        if (DecimalType.is32BitDecimalType(dt)) {
          withResource(Scalar.fromDecimal(-scale, 0)) { scalar =>
            scalar.sub(input.getBase)
          }
        } else {
          withResource(Scalar.fromDecimal(-scale, 0L)) { scalar =>
            scalar.sub(input.getBase)
          }
        }
```

Is there a way to make an API where we could combine the two if blocks? 
_Originally posted by @revans2 in https://github.com/NVIDIA/spark-rapids/pull/1717#discussion_r605116802_

**Comment by kuhushukla** [comment]
We can add a generic `fromDecimal` is templated or uses `Object` and we pass the precision or some metadata bit to do this logic through the API.

**Comment by revans2** [comment]
The code in question is gone now. We already have a GpuScalar.from that does this and has replaced most calls. I think this is good enough.

**Comment by kuhushukla** [comment]
Thank u Bobby. Maybe we should use that [https://github.com/NVIDIA/spark-rapids/blob/branch-22.02/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/arithmetic.scala#L79]
