### ISSUE TITLE
Refactor the BinaryOperator code wrt Decimal types

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2077]
Right now we have some repeated code in the arithmetic.scala for binary operations using decimal. We should refactor some of it so its simpler and easier to follow

**Comment by kuhushukla** [comment]
@razajafri Can you elaborate on this a bit? Thanks for the report.

**Comment by razajafri** [comment]
> @razajafri Can you elaborate on this a bit? Thanks for the report.

This might be stale after all the good work that's been put in for Decimal 128, but I will look at this and update ASAP

**Comment by razajafri** [comment]
I couldn't find any occurrence of repeated code that I saw earlier. Looks like it was handled while working on the Decimal 128 work
