### ISSUE TITLE
[BUG] koalas.sql fails with java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#2079]
**Describe the bug**

Koalas.sql fails with java.lang.ArrayIndexOutOfBoundsException.
Sample stacktrace is:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ai.rapids.cudf.Table.<init>(Table.java:62)
	at com.nvidia.spark.rapids.GpuColumnVector.from(GpuColumnVector.java:498)
	at com.nvidia.spark.rapids.GpuWindowExpression.$anonfun$evaluateRowBasedWindowExpression$1(GpuWindowExpression.scala:188)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuWindowExpression.withResource(GpuWindowExpression.scala:132)
	at com.nvidia.spark.rapids.GpuWindowExpression.evaluateRowBasedWindowExpression(GpuWindowExpression.scala:187)
	at com.nvidia.spark.rapids.GpuWindowExpression.columnarEval(GpuWindowExpression.scala:167)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:35)
	at com.nvidia.spark.rapids.GpuAlias.columnarEval(namedExpressions.scala:93)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:35)
	at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:50)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:161)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:158)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:158)
	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:193)
	at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:49)
	at com.nvidia.spark.rapids.GpuProjectExec$.projectAndClose(basicPhysicalOperators.scala:40)
	at com.nvidia.spark.rapids.GpuWindowExec.$anonfun$doExecuteColumnar$1(GpuWindowExec.scala:149)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at com.nvidia.spark.rapids.GpuBaseLimitExec$$anon$1.next(limit.scala:67)
	at com.nvidia.spark.rapids.GpuBaseLimitExec$$anon$1.next(limit.scala:61)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:206)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:222)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

Minimum reproduce using .sql
```
import databricks.koalas as ks

kdf = ks.DataFrame({'a': [1, 2, 3],
                    'b': [4, 5, 6]})
ks.sql("SELECT * FROM {kdf} WHERE a > 1")
```

Some other Koalas functions also fail with similar stacktrace, 2nd example:
```
import numpy as np
import databricks.koalas as ks

kdf = ks.DataFrame({'A': np.random.rand(5),
                    'B': np.random.rand(5)})
                    
def square(x) -> ks.Series[np.float64]:
    return x ** 2
kdf.apply(square)
```

**Expected behavior**

Above 2 examples should work fine such as in CPU mode.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

Spark standalone cluster 3.1.1
Rapids accelerator 0.4.1
Koalas 1.7

**Additional context**

**Comment by GaryShen2008** [comment]
The explain log is as below.
== Parsed Logical Plan ==
Project [__index_level_0__#415L, a#396L, b#397L]
+- Project [__index_level_0__#415L, a#396L, b#397L, monotonically_increasing_id() AS __natural_order__#420L]
   +- Window [(cast(row_number() windowspecdefinition(_nondeterministic#416L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - cast(1 as bigint)) AS __index_level_0__#415L, a#396L, b#397L], [_nondeterministic#416L ASC NULLS FIRST]
      +- Project [a#396L, b#397L, monotonically_increasing_id() AS _nondeterministic#416L]
         +- Project [a#396L, b#397L]
            +- Project [a#396L, b#397L]
               +- Filter (a#396L > cast(1 as bigint))
                  +- SubqueryAlias koalas_139631428331984
                     +- Project [a#396L, b#397L]
                        +- Project [__index_level_0__#395L, a#396L, b#397L, monotonically_increasing_id() AS __natural_order__#401L]
                           +- LogicalRDD [__index_level_0__#395L, a#396L, b#397L], false

== Analyzed Logical Plan ==
__index_level_0__: bigint, a: bigint, b: bigint
Project [__index_level_0__#415L, a#396L, b#397L]
+- Project [__index_level_0__#415L, a#396L, b#397L, monotonically_increasing_id() AS __natural_order__#420L]
   +- Window [(cast(row_number() windowspecdefinition(_nondeterministic#416L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - cast(1 as bigint)) AS __index_level_0__#415L, a#396L, b#397L], [_nondeterministic#416L ASC NULLS FIRST]
      +- Project [a#396L, b#397L, monotonically_increasing_id() AS _nondeterministic#416L]
         +- Project [a#396L, b#397L]
            +- Project [a#396L, b#397L]
               +- Filter (a#396L > cast(1 as bigint))
                  +- SubqueryAlias koalas_139631428331984
                     +- Project [a#396L, b#397L]
                        +- Project [__index_level_0__#395L, a#396L, b#397L, monotonically_increasing_id() AS __natural_order__#401L]
                           +- LogicalRDD [__index_level_0__#395L, a#396L, b#397L], false

== Optimized Logical Plan ==
Window [(cast(row_number() windowspecdefinition(_nondeterministic#416L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - 1) AS __index_level_0__#415L, a#396L, b#397L], [_nondeterministic#416L ASC NULLS FIRST]
+- Project [a#396L, b#397L, monotonically_increasing_id() AS _nondeterministic#416L]
   +- Filter (a#396L > 1)
      +- LogicalRDD [__index_level_0__#395L, a#396L, b#397L], false

== Physical Plan ==
*(2) RunningWindowFunction [(cast(row_number() windowspecdefinition(_nondeterministic#416L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - 1) AS __index_level_0__#415L, a#396L, b#397L], [_nondeterministic#416L ASC NULLS FIRST]
+- GpuColumnarToRow false
   +- GpuSort [_nondeterministic#416L ASC NULLS FIRST], false, RequireSingleBatch, 0
      +- GpuCoalesceBatches RequireSingleBatch
         +- GpuShuffleCoalesce 2147483647
            +- GpuColumnarExchange gpusinglepartitioning$(), false, [id=#852]
               +- GpuProject [a#396L, b#397L, monotonically_increasing_id() AS _nondeterministic#416L]
                  +- GpuCoalesceBatches TargetSize(2147483647)
                     +- GpuFilter (a#396L > 1)
                        +- GpuRowToColumnar TargetSize(2147483647)
                           +- *(1) Scan ExistingRDD arrow[__index_level_0__#395L,a#396L,b#397L]

**Comment by GaryShen2008** [comment]
Explain for cpu running:
== Parsed Logical Plan ==
Project [__index_level_0__#62L, a#43L, b#44L]
+- Project [__index_level_0__#62L, a#43L, b#44L, monotonically_increasing_id() AS __natural_order__#67L]
   +- Window [(cast(row_number() windowspecdefinition(_nondeterministic#63L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - cast(1 as bigint)) AS __index_level_0__#62L, a#43L, b#44L], [_nondeterministic#63L ASC NULLS FIRST]
      +- Project [a#43L, b#44L, monotonically_increasing_id() AS _nondeterministic#63L]
         +- Project [a#43L, b#44L]
            +- Project [a#43L, b#44L]
               +- Filter (a#43L > cast(1 as bigint))
                  +- SubqueryAlias koalas_140316329691216
                     +- Project [a#43L, b#44L]
                        +- Project [__index_level_0__#42L, a#43L, b#44L, monotonically_increasing_id() AS __natural_order__#48L]
                           +- LogicalRDD [__index_level_0__#42L, a#43L, b#44L], false

== Analyzed Logical Plan ==
__index_level_0__: bigint, a: bigint, b: bigint
Project [__index_level_0__#62L, a#43L, b#44L]
+- Project [__index_level_0__#62L, a#43L, b#44L, monotonically_increasing_id() AS __natural_order__#67L]
   +- Window [(cast(row_number() windowspecdefinition(_nondeterministic#63L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - cast(1 as bigint)) AS __index_level_0__#62L, a#43L, b#44L], [_nondeterministic#63L ASC NULLS FIRST]
      +- Project [a#43L, b#44L, monotonically_increasing_id() AS _nondeterministic#63L]
         +- Project [a#43L, b#44L]
            +- Project [a#43L, b#44L]
               +- Filter (a#43L > cast(1 as bigint))
                  +- SubqueryAlias koalas_140316329691216
                     +- Project [a#43L, b#44L]
                        +- Project [__index_level_0__#42L, a#43L, b#44L, monotonically_increasing_id() AS __natural_order__#48L]
                           +- LogicalRDD [__index_level_0__#42L, a#43L, b#44L], false

== Optimized Logical Plan ==
Window [(cast(row_number() windowspecdefinition(_nondeterministic#63L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - 1) AS __index_level_0__#62L, a#43L, b#44L], [_nondeterministic#63L ASC NULLS FIRST]
+- Project [a#43L, b#44L, monotonically_increasing_id() AS _nondeterministic#63L]
   +- Filter (a#43L > 1)
      +- LogicalRDD [__index_level_0__#42L, a#43L, b#44L], false

== Physical Plan ==
*(2) RunningWindowFunction [(cast(row_number() windowspecdefinition(_nondeterministic#63L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - 1) AS __index_level_0__#62L, a#43L, b#44L], [_nondeterministic#63L ASC NULLS FIRST]
+- *(2) Sort [_nondeterministic#63L ASC NULLS FIRST], false, 0
   +- Exchange SinglePartition, true, [id=#119]
      +- *(1) Project [a#43L, b#44L, monotonically_increasing_id() AS _nondeterministic#63L]
         +- *(1) Filter (a#43L > 1)
            +- *(1) Scan ExistingRDD arrow[__index_level_0__#42L,a#43L,b#44L]

**Comment by GaryShen2008** [comment]
rapids.explain:
!NOT_FOUND <RunningWindowFunctionExec> cannot run on GPU because no GPU enabled version of operator class com.databricks.sql.execution.window.RunningWindowFunctionExec could be found
  @Expression <Alias> (cast(row_number() windowspecdefinition(_nondeterministic#23L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - 1) AS __index_level_0__#22L could run on GPU
    @Expression <Subtract> (cast(row_number() windowspecdefinition(_nondeterministic#23L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) - 1) could run on GPU
      @Expression <Cast> cast(row_number() windowspecdefinition(_nondeterministic#23L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) as bigint) could run on GPU
        @Expression <WindowExpression> row_number() windowspecdefinition(_nondeterministic#23L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) could run on GPU
          @Expression <RowNumber> row_number() could run on GPU
          @Expression <WindowSpecDefinition> windowspecdefinition(_nondeterministic#23L ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) could run on GPU
            @Expression <SortOrder> _nondeterministic#23L ASC NULLS FIRST could run on GPU
              @Expression <AttributeReference> _nondeterministic#23L could run on GPU
            @Expression <SpecifiedWindowFrame> specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$()) could run on GPU
              @Expression <UnboundedPreceding$> unboundedpreceding$() could run on GPU
              @Expression <CurrentRow$> currentrow$() could run on GPU
      @Expression <Literal> 1 could run on GPU
  @Expression <AttributeReference> a#3L could run on GPU
  @Expression <AttributeReference> b#4L could run on GPU
  @Expression <SortOrder> _nondeterministic#23L ASC NULLS FIRST could run on GPU
    @Expression <AttributeReference> _nondeterministic#23L could run on GPU
  *Exec <SortExec> will run on GPU
    *Expression <SortOrder> _nondeterministic#23L ASC NULLS FIRST will run on GPU
    *Exec <ShuffleExchangeExec> will run on GPU
      *Partitioning <SinglePartition$> will run on GPU
      *Exec <ProjectExec> will run on GPU
        *Expression <Alias> monotonically_increasing_id() AS _nondeterministic#23L will run on GPU
          *Expression <MonotonicallyIncreasingID> monotonically_increasing_id() will run on GPU
        *Exec <FilterExec> will run on GPU
          *Expression <GreaterThan> (a#3L > 1) will run on GPU
          !NOT_FOUND <RDDScanExec> cannot run on GPU because no GPU enabled version of operator class org.apache.spark.sql.execution.RDDScanExec could be found
            @Expression <AttributeReference> __index_level_0__#2L could run on GPU
            @Expression <AttributeReference> a#3L could run on GPU
            @Expression <AttributeReference> b#4L could run on GPU

**Comment by wbo4958** [comment]
Seems [boundRowProjectList](https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala#L159) didn't consider the orderBy column which results in empty Table from [project](https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuWindowExpression.scala#L187)
