### ISSUE TITLE
[BUG] using ParquetCachedBatchSerializer is slower then not using it

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2081]
**Describe the bug**
I was running a quick simple test to see if our gpu ParquetCachedBatchSerializer was faster then not enabling it and using the simple query below it was always slower. This was just running on a single node using spark local mode with 8 threads. ran multiple times with --conf spark.sql.cache.serializer=com.nvidia.spark.rapids.shims.spark311.ParquetCachedBatchSerializer and then without it.  I used the same data across all the runs.  

It took 6 seconds without it and 23 seconds with it.

The original code ran was:

```
import time
from pyspark.sql.types import *
from pyspark.sql.functions import *
from pyspark.sql import SparkSession
​
spark = SparkSession.builder \
        .appName('test').getOrCreate()
spark.sparkContext.setLogLevel("WARN")
​
data = spark.range(100000000).selectExpr(
        "cast(id as double) as col0",
        "cast(id - 100 as double) as col1",
        "cast(id * 2 as double) as col2",
        "rand(100) as col3",
        "rand(200) as col4")
​
num_buckets = 10
with_random = data.selectExpr("*", "cast(rand(0) * {} as int) as BUCKET".format(num_buckets)).cache()
​with_random.count()
for test_bucket in range(0, num_buckets):
    with_random.filter(with_random.BUCKET == test_bucket).drop("BUCKET").write.parquet(
            "/tmp/test_data/{}".format(test_bucket))
    with_random.filter(with_random.BUCKET != test_bucket).drop("BUCKET").write.parquet(
            "/tmp/train_data/{}".format(test_bucket))
```

Note the data out of with_random was saved off to parquet and then read back in and cached. 
```
with_random.write.parquet("out.parquet")
with_random = spark.read.parquet("out.parquet).cache()
```

Looking quick at the sql UI for spark, all execs seems slower, the coalesceBatch collect time is noticeable so it seems like the read from GpuInMemoryTableScan is just slower then the HostColumnarToGPU, but we would have to investigate further to verify.

**Comment by razajafri** [comment]
I ran the n_fold query on yarn and I saw the GPU with ParquetCachedBatchSerializer to be faster than the other three. As an initial sanity check I have timed it using ubuntu `time ...`

| Conf | Link to history | Wallclock time | 
| --- | ---- | ---- |
|on GPU with ParquetCachedBatchSerializer| http://spark-egx-01:18081/history/application_1603128018386_7436/jobs/ | 1m5.735s|
|On GPU with Default Serializer | http://spark-egx-01:18081/history/application_1603128018386_7435/jobs/ | 1m43.797s |
|On CPU with Default Serializer | http://spark-egx-01:18081/history/application_1603128018386_7434/jobs/ | 2m11.227s|
|On CPU with ParquetCachedBatchSerializer | http://spark-egx-01:18081/history/application_1603128018386_7433/jobs/ | 1m20.404s|

**Comment by tgravescs** [comment]
I wonder if I was hitting the nano sleep issue

**Comment by revans2** [comment]
@razajafri 
Have you tried disabling snappy compression on the GPU serializer like we do on the CPU version?

**Comment by razajafri** [comment]
> @razajafri
> Have you tried disabling snappy compression on the GPU serializer like we do on the CPU version?

No, I wanted to run it first with no changes. Let me do that now

**Comment by razajafri** [comment]
I have updated the table. GPU/ParquetCachedBatchSerializer is still faster but slower than with compression on, which is not what I expected

**Comment by revans2** [comment]
> I have updated the table. GPU/ParquetCachedBatchSerializer is still faster but slower than with compression on, which is not what I expected

For "on GPU with ParquetCachedBatchSerializer" I understand how you could distinguish between AUTO and no compression. 

For "On CPU with ParquetCachedBatchSerializer" did you update the CPU parquet writer to use compression? last time I looked it was set to no compression.

For the others with  DefaultSerializer. I assume there is no way for you to configure the compression, and it is probably just run to run variance. Is that true?

**Comment by razajafri** [comment]
> > I have updated the table. GPU/ParquetCachedBatchSerializer is still faster but slower than with compression on, which is not what I expected
> 
> For "on GPU with ParquetCachedBatchSerializer" I understand how you could distinguish between AUTO and no compression.
> 
> For "On CPU with ParquetCachedBatchSerializer" did you update the CPU parquet writer to use compression? last time I looked it was set to no compression.
> 
> For the others with DefaultSerializer. I assume there is no way for you to configure the compression, and it is probably just run to run variance. Is that true?

That was not the correct column heading. Yes, you are right, the only place where the compressionType will affect is the Gpu/ParquetCachedBatchSerializer pair, the rest are with no compression like you rightly said, and only variance in runs

**Comment by razajafri** [comment]
closing this because PCBS is faster while writing and a little faster than the Default Serializer
