### ISSUE TITLE
[DOC] Supported ops page differentiate type supported in key vs passed along

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2102]
## Report incorrect documentation

The supported ops page doesn't seem to indicate if a type is supposed as the main key (like joining on) vs just being able to be passed along as another columns.  Perhaps we should add a note for this.

**Comment by andygrove** [comment]
PR https://github.com/NVIDIA/spark-rapids/pull/3011 adds this information for types that cannot be usued as join keys in sort-merge, hash, and broadcast joins.

@tgravescs is that sufficient to address this issue or are there other types that need clarification?

**Comment by tgravescs** [comment]
so that sounds sufficient for joins but I wonder about other operations like hashAggregate, sorting, union, etc...

**Comment by revans2** [comment]
We can do the same thing for all of them. It is mostly a question of should the framework have a more generic way to do this, or should we add in one off solutions.

`SparkPlan`/Scala gives us a `productIterator` that we might be able to use to filter it to just expressions/sequences of expressions and then match those up with a pattern, similar to what we do when matching parameters to an Expression. That to me feels like a fairly generic way to make this work. But it is a lot of code compared to what is happening in #3011 along with the already existing check in the code.

```
    val keyDataTypes = (leftKeys ++ rightKeys).map(_.dataType)
    if (keyDataTypes.exists(dType =>
      dType.isInstanceOf[ArrayType] || dType.isInstanceOf[MapType])) {
      meta.willNotWorkOnGpu("ArrayType or MapType in join keys are not supported")
    }
```

So The difference would be something like



BroadcastHashJoinExec | Implementation of join using broadcast data | None | S | ... | S | NS | NS | PS* (Cannot be used as join key; missing nested BINARY, CALENDAR, ARRAY, MAP, STRUCT, UDT) | PS* (Cannot be used as join key; missing nested BINARY, CALENDAR, ARRAY, MAP, STRUCT, UDT) | PS* (Cannot be used as join key; missing nested BINARY, CALENDAR, ARRAY, MAP, STRUCT, UDT) | NS
-- | -- | -- | -- |  -- | -- | -- | -- | -- | -- | -- | --


vs



BroadcastHashJoinExec | Implementation of join using broadcast data | LeftKeys | None | S | ... | S | NS | NS | NS | NS | NS | NS
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BroadcastHashJoinExec | Implementation of join using broadcast data | RightKeys | None | S | ... | S | NS | NS | NS | NS | NS | NS
BroadcastHashJoinExec | Implementation of join using broadcast data | Output | None | S | ... | S | NS | NS | PS* (missing nested BINARY, CALENDAR, ARRAY, MAP, STRUCT, UDT) | PS* (missing nested BINARY, CALENDAR, ARRAY, MAP, STRUCT, UDT) | PS* (missing nested BINARY, CALENDAR, ARRAY, MAP, STRUCT, UDT) | NS

**Comment by sameerz** [comment]
The latter / more generic approach that @revans2 mentions above seems like the better way to go.
