### ISSUE TITLE
[BUG] Audit - [SPARK-33829][SQL] Renaming v2 tables should recreate the cache

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#2107]
It seems we should investigate more whether our caching work is impacted by this, and needs a similar fix/test.

https://github.com/apache/spark/commit/06075d849e

**Comment by razajafri** [comment]
IMO this doesn't affect our cache code because we don't modify the cacheManager. The only thing we do is how the cache is stored in memory before handing it back to spark to store it according to user specified `storageLevel`
