### ISSUE TITLE
Release checklist v0.5.0

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#2108]
Release checklist for v0.5.0: 

| Status | Task | Start | End |  Owner | 
| ------ | ---- | ----- | --- |  ----- | 
| Pre-release | 
| <ul><li> [X] </li></ul> | Notification to team of last feature sprint in milestone 2021-03-29 - 2021-04-09 | 2021-03-29 | 2021-03-29 | @sameerz | 
| <ul><li> [X] </li></ul> | Burndown (no new features for current release) | 2021-04-12 | 2021-04-23 | Team | 
| <ul><li> [X] </li></ul> | Update docs for current release in spark-rapids | 2021-04-12 | 2021-04-16 | Team |
| <ul><li> [X] </li></ul> | Get RAPIDS 0.20 cudf java build working | 2021-04-12 | 2021-04-16 |  @pxLi | 
| <ul><li> [X] </li></ul> | Open 0.6.0 branch, automerge from 0.5 to 0.6 | 2021-04-19 | 2021-04-19 | @pxLi | 
| <ul><li> [X] </li></ul> | Enable Jenkins builds (premerge, nightly, integration, performance) for 0.6.0 | 2021-04-20 | 2021-04-20 | @pxLi | 
| <ul><li> [X] </li></ul> | cudf 0.19.1 Java release to sonatype | 2021-04-22 | 2021-04-23 | @NvTimLiu | 
| <ul><li> [X] </li></ul> | Notify RAPIDS team of javadocs for 0.19.1 | 2021-04-26 | 2021-04-26 | @GaryShen2008 | 
| <ul><li> [X] </li></ul> | cudf 0.19.2 Java release to sonatype | 2021-04-28 | 2021-04-29 | @NvTimLiu | 
| Staging release | 
| <ul><li> [X] </li></ul> | Merge all remaining branch-0.5 PRs | 2021-04-23 |  2021-04-23 | Team | 
| <ul><li> [X] </li></ul> | <span style="color:red;background-color:yellow"> ~~Blocked pending issue #2244~~ |  2021-04-23 | 2021-04-28  |  |
| <ul><li> [X] </li></ul> | Create CHANGELOG.md | 2021-04-28 |  2021-04-29 | @pxLi | 
| <ul><li> [X] </li></ul> | Create a PR (not squashed) to merge from branch-0.5 to main.  Needs review from repository owner | 2021-04-29 | 2021-04-29 | @NvTimLiu | 
| <ul><li> [X] </li></ul> | Trigger the release Jenkins job on the main branch and deploy the jar to sonatype staging | 2021-04-29 | 2021-04-30 | @NvTimLiu | 
| <ul><li> [X] </li></ul> | Deliver packages to QA  | 2021-04-30 | 2021-04-30 | @NvTimLiu | 
| <ul><li> [X] </li></ul> | Make 0.6.0 the default branch | 2021-04-26 | 2021-04-26 | @jlowe  | 
| <ul><li> [X] </li></ul> | Virtual review  | 2021-04-30 | 2021-05-04 | @krajendrannv | 
| <ul><li> [X] </li></ul> | Run integration tests on staging jars with AQE on, UCX on, Databricks Azure, Databricks AWS, AWS EMR, Dataproc | 2021-04-30 | 2021-05-07 |  @NvTimLiu | 
| <ul><li> [X] </li></ul> | Run integration tests on staging jars with AQE on, A10/A40 manually | 2021-04-27 | 2021-05-07| @GaryShen2008 | 
| <ul><li> [X] </li></ul> | Run LHA tests on staging jars | 2021-04-27 | 2021-05-07 | @NvTimLiu | 
| <ul><li> [X] </li></ul> | Run pre-processing workflow for [DLRM sample use case](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Recommendation/DLRM#advanced) | 2021-04-27 | 2021-05-07 | @GaryShen2008 |
| <ul><li> [X] </li></ul> | QA testing on YARN, NGC with Volta and Ampere | 2021-04-27 | 2021-05-07 | @yuange98 | 
| Release | 
| <ul><li> [X] </li></ul> | Tag the release and deploy the staging artifacts to maven central repository | 2021-05-12  | 2021-05-12 | @NvTimLiu |
| <ul><li> [X] </li></ul> | Update gh-pages | 2021-05-12 | 2021-05-12 |  @sameerz |
| <ul><li> [X] </li></ul> | Update docs for current release in spark-xgboost-examples  | 2021-05-12 | 2021-05-12 | @GaryShen2008 | 
| <ul><li> [X] </li></ul> | Update `rapids.sh` in https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/rapids https://github.com/GoogleCloudDataproc/initialization-actions/pull/907 | 2021-05-13 | 2021-05-14 |  |

**Comment by GaryShen2008** [comment]
cuDF 0.19 jar release is postponed. We're waiting for cudf 0.19.1 native release.

**Comment by jlowe** [comment]
Are we calling it 0.19.1 and not shipping a 0.19 version?

**Comment by GaryShen2008** [comment]
> 
> 
> Are we calling it 0.19.1 and not shipping a 0.19 version?

Yes, we'll use the same version number 0.19.1 with cuDF native release and skip 0.19.0.

**Comment by GaryShen2008** [comment]
For the testing of DLRM, it requires us to set a new config "spark.rapids.sql.csv.read.integer.enabled=true", otherwise the ScanCsv will run on CPU.
