### ISSUE TITLE
[FEA] Offset Window changes in Spark 3.2.0

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#2110]
**Is your feature request related to a problem? Please describe.**
Check if we need to update window functions code related to https://github.com/apache/spark/commit/140538ea5b

**Comment by revans2** [comment]
We don't support NthValue yet. We do support Lead and Lag that are similar.  We don't currently support ignore nulls for lead or lag, and I just finished adding in support to fall back to the CPU for that.  This is not needed for the plugin right now.
