### ISSUE TITLE
[FEA] audit - Random function (Rand/ExpressionWithRandomSeed) changes in 3.2.0

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#2111]
There are a couple of changes around `Rand` and `ExpressionWithRandomSeed` that I think need a closer look (this is in 3.2.0 as part of audit):

1. [[SPARK-33857][SQL] Unify the default seed of random functions](https://github.com/apache/spark/commit/9c30116fb4)
2. [[SPARK-33909][SQL] Check rand functions seed is legal at analyer side](https://github.com/apache/spark/commit/3b1b209e90)

Especially the change to `ExpressionWithRandomSeed`, which we subclass. A new member was added (`seedExpression`) which is being used in some of the optimizer rules.

**Comment by revans2** [comment]
This was already done to get the 3.2 code to compile.
