### ISSUE TITLE
[FEA] audit - [SPARK-33861][SQL] Simplify conditional in predicate 

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#2113]
This is a task to check the logic in the conditional simplification here. I do not think this affects us (and it happens before our plugin kicks in), but I don't fully understand it yet.

[[SPARK-33861][SQL] Simplify conditional in predicate](https://github.com/apache/spark/commit/32d4a2b062)
[[SPARK-33861][SQL][FOLLOWUP] Simplify conditional in predicate should consider deterministic](https://github.com/apache/spark/commit/3aa4e113c5)

The PRs say it allows the conditional expression to be pushed down to the data source. I wonder if anything needs to be checked in the data source also to see if the new expression would break our code.

**Comment by sameerz** [comment]
These are changes to the SQL optimizer which is run before the plugin sees the plan.
