### ISSUE TITLE
[FEA] Support Array[Decimal] and struct of Decimal being passed along with join

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2134]
**Is your feature request related to a problem? Please describe.**
in https://github.com/NVIDIA/spark-rapids/issues/2103 we are adding support for arrays to be passed along with join (not the join key), but Array of Decimal was failing the tests so we need to investigate that further and figure out why it was failing.  I also left the struct of Decimals out of the check as it was easier, the struct of decimal tests were working so we just need to re-enable it and add the tests.

**Comment by sperlingxx** [comment]
This issue is out of date. Just close it.
