### ISSUE TITLE
[FEA] support GpuHashJoin on structs containing floats

### ISSUE THREAD

**Issue by sperlingxx** [NVIDIA/spark-rapids#2140]
**Is your feature request related to a problem? Please describe.**
We can not support GpuHashJoin on structs who contain child of float type, because the catalyst rule [NormalizeFloatingNumbers](https://github.com/apache/spark/blob/branch-3.1/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/NormalizeFloatingNumbers.scala#L136) transforms join expressions, whose data type is struct type containing float children, to pattern `KnownFloatingPointNormalized(If(IsNull(expr), Literal(null, struct.dataType), struct))`. And the expression `Literal(null, struct.dataType)` inside the pattern can not run on GPU, since cuDF scalar of StructType is yet supported.

For instance, if we run a simple sort-merge join with join key `StructType(a: FloatType)`, spark produce physical plan as below:
```
SortMergeJoin [knownfloatingpointnormalized(if (isnull(a#996)) null else named_struct(col1, knownfloatingpointnormalized(normalizenanandzero(a#996.child0)))), b#997], [knownfloatingpointnormalized(if (isnull(a#1000)) null else named_struct(col1, knownfloatingpointnormalized(normalizenanandzero(a#1000.child0)))), b#1001], Cross
:- Sort [knownfloatingpointnormalized(if (isnull(a#996)) null else named_struct(col1, knownfloatingpointnormalized(normalizenanandzero(a#996.child0)))) ASC NULLS FIRST, b#997 ASC NULLS FIRST], false, 0
:  +- Exchange hashpartitioning(knownfloatingpointnormalized(if (isnull(a#996)) null else named_struct(col1, knownfloatingpointnormalized(normalizenanandzero(a#996.child0)))), b#997, 2), true, [id=#2237]
:     +- Scan ExistingRDD[a#996,b#997]
+- Sort [knownfloatingpointnormalized(if (isnull(a#1000)) null else named_struct(col1, knownfloatingpointnormalized(normalizenanandzero(a#1000.child0)))) ASC NULLS FIRST, b#1001 ASC NULLS FIRST], false, 0
   +- Exchange hashpartitioning(knownfloatingpointnormalized(if (isnull(a#1000)) null else named_struct(col1, knownfloatingpointnormalized(normalizenanandzero(a#1000.child0)))), b#1001, 2), true, [id=#2238]
```
Among the physical plan, the `IfElse` expression can not run on GPU because the true expression is `Literal(null, StructType)`. We can not create Literal of StructType, since cuDF doesn't support Scalar of StructType.  

**Describe the solution you'd like**
This issue is relied on cuDF issue [#7990](https://github.com/rapidsai/cudf/issues/7790).

**Comment by tgravescs** [comment]
This is join key with structs? the linked issue is Scalar support so is this just with Scalars? please clarify and if possible add example.

**Comment by sperlingxx** [comment]
> This is join key with structs? the linked issue is Scalar support so is this just with Scalars? please clarify and if possible add example.

Hi Tom, I added an example to illustrate the problem.
