### ISSUE TITLE
[FEA] Range window-functions must support non-timestamp order-by expressions

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#216]
Window Functions in Rapids do not currently support non-timestamp `ORDER BY` expressions for `RANGE` based queries.
i.e. While the following query is supported:
```sql
SELECT MAX(score) OVER (PARTITION BY uid ORDER BY CAST(date AS TIMESTAMP) RANGE ...)
```
the following is not:
```sql
SELECT MAX(score) OVER (PARTITION BY uid ORDER BY date RANGE ...)
```

This will need rework in the CUDF primitives as well.

**Comment by tgravescs** [comment]
we are seeing an example of this that isn't falling back to the CPU for some reason filed https://github.com/NVIDIA/spark-rapids/issues/925

**Comment by sameerz** [comment]
Depends on https://github.com/rapidsai/cudf/pull/7866

**Comment by sameerz** [comment]
Fixed by https://github.com/NVIDIA/spark-rapids/pull/2020
