### ISSUE TITLE
[FEA] provide automated copyright header update

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#2167]
**Is your feature request related to a problem? Please describe.**
Contributors to RAPIDS Accelerator for Spark  are required to update the copyright header in the files modified in pull requests. This mundane task can be easily automated.

**Describe the solution you'd like**
A git commit hook that takes care of the copyright headers before submitting a pull request: 

e.g. : 

````bash
git diff origin/branch-0.5..HEAD |  grep -F "+++ b/" |  sed "s#+++ b/##g"  | 
   xargs -L1 sed -i -E "s/Copyright *\(c\) *([0-9,-]+)*-([0-9]{4}), *NVIDIA *CORPORATION/Copyright (c) \\1-`date +%Y`, NVIDIA CORPORATION/; /`date +%Y`/! s/Copyright *\(c\) ([0-9]{4}), *NVIDIA *CORPORATION/Copyright (c) \\1-`date +%Y`, NVIDIA CORPORATION/"
````
h/t @karthikeyann 

there are also 3rd party solutions 
- https://github.com/fwolf/copyright-year-updater.sh 

**Describe alternatives you've considered**
- manual updates as before 
- semi-manual with a separate script

**Comment by revans2** [comment]
I'm not sure that this is ideal.  It assumes that all contributions will come from NVIDIA, which I really hope is not the case. It also assumes that adding the copyright automatically is a good thing/ I think there may be some legal issues with it happening automatically without the author indicating that it is acceptable, just like with how we need to sign off on a patch for the CI to accept it.

I would love a script checked in that lets us add them automatically very easily. I would also love a precommit build check that gives us a warning if they have not been updated, but I personally don't think it should not be a requirement before commit.

**Comment by gerashegalov** [comment]
Thanks, @revans2! Local commit hook changes are part of the PR review, but I see from your comment that it can be more complicated than I realized initially.  We can make the pre-commit hook optional controlled by an environment variable with the default being "off". What do you think?

**Comment by revans2** [comment]
For me personally I think an environment variable that lets you opt in would be good enough.

**Comment by karthikeyann** [comment]
Is there a way we can get around updating the year by giving a reference to a document that says, copyright year is the last commit date?
Git log may not be carried forward for file moving (delete and add as different file instead of `git mv`), which may cause the problem in this case.

**Comment by revans2** [comment]
> Is there a way we can get around updating the year by giving a reference to a document that says, copyright year is the last commit date?
> Git log may not be carried forward for file moving (delete and add as different file instead of `git mv`), which may cause the problem in this case.

This is a lawyer question, and I am not one of them. But my guess would be no, just because I have not really seen it. But I could be wrong.

**Comment by gerashegalov** [comment]
> > Is there a way we can get around updating the year by giving a reference to a document that says, copyright year is the last commit date?
> > Git log may not be carried forward for file moving (delete and add as different file instead of `git mv`), which may cause the problem in this case.
> 
> This is a lawyer question, and I am not one of them. But my guess would be no, just because I have not really seen it. But I could be wrong.

I am not a lawyer but I too would guess merely referring to the commit date is not sufficient because the source code can be [redistributed](https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/LICENSE#L90) outside git, git history lost, or reset for some reason.
