### ISSUE TITLE
[BUG] CudaUtil should be removed

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#217]
CudaUtil is trampolining into the ai.rapids.cudf package to access `Cuda.memcpy` to copy between two `MemoryBuffer` objects regardless of whether they are host or device objects.  We should add a public `copy` method to cudf's `MemoryBuffer` and remove the `CudaUtil` class when we move to a cudf version containing that change.

**Comment by abellina** [comment]
https://github.com/rapidsai/cudf/issues/6697
