### ISSUE TITLE
[BUG] GpuParquetScan#readBufferToTable contains dead code

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#2171]
**Describe the bug**
This fragment
https://github.com/NVIDIA/spark-rapids/blob/87fc89772424668f7726045db4a4f069562e1765/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala#L1600-L1603
looks as if it is supposed to bail out of readBufferToTable with an empty option but it's not

**Expected behavior**
Add a  unit test for the zero `dataSize`, and either adjust or remove the dead code based on the confirmed behavior.

**Context** 
https://github.com/NVIDIA/spark-rapids/pull/2161#discussion_r614853325

**Comment by gerashegalov** [comment]
cc @abellina @jlowe

**Comment by tgravescs** [comment]
this is dead code and can just be removed, I'll put up pr

**Comment by tgravescs** [comment]
note its not needed because the code in Next() that calls readBatch that calls readBufferToTable handles the size of 0 and skips those.
