### ISSUE TITLE
[FEA] Support Negative timestamps to string

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#219]
**Is your feature request related to a problem? Please describe.**
Now that cudf supports the conversion of negative timestamps to strings as part of [this](https://github.com/rapidsai/cudf/pull/5452) we should make sure we support it too in Spark

**Describe the solution you'd like**
Add support to all the operators that convert timestamps to string or use it in the process.

**Comment by jlowe** [comment]
This is now supported.
