### ISSUE TITLE
[FEA] Uses a good iterator instead of the `RequireSingleBatch` goal.

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#2200]
Uses a good iterator instead of the `RequireSingleBatch` goal to keep the integrity for each group in `GpuFlatMapGroupsInPandasExec`, because we are very much trying to move away from anything that requires a single batch.

For windowing we are going to have to come up with a good iterator that can split batches on key boundaries, so it is not something that we have to do right now. But we should look at supporting it eventually.

This is from [the comment here](https://github.com/NVIDIA/spark-rapids/pull/2178#discussion_r615877485) .

**Comment by revans2** [comment]
This is something that we will likely have to write for the out of core window work at #1856
So whom ever writes this first should try to make it generic so it can be reused in multiple places.
