### ISSUE TITLE
[BUG] csv_test.py::test_csv_fallback FAILED on the EMR Cluster

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#2220]
**Describe the bug**
csv_test.py::test_csv_fallbac FAILED on the EMR Cluster
=================================== FAILURES ===================================
______ test_csv_fallback[spark.rapids.sql.format.csv.enabled-read_csv_df] ___

spark_tmp_path = '/tmp/pyspark_tests//818508/'
read_func = <function read_csv_df at 0x7f7b23de25f0>
disable_conf = 'spark.rapids.sql.format.csv.enabled'

    @allow_non_gpu('FileSourceScanExec')
    @pytest.mark.parametrize('read_func', [read_csv_df, read_csv_sql])
    @pytest.mark.parametrize('disable_conf', ['spark.rapids.sql.format.csv.enabled', 'spark.rapids.sql.format.csv.read.enabled'])
    def test_csv_fallback(spark_tmp_path, read_func, disable_conf):
        data_gens =[
            StringGen('(\\w| |\t|\ud720){0,10}', nullable=False),
            byte_gen, short_gen, int_gen, long_gen, boolean_gen, date_gen]
    
        gen_list = [('_c' + str(i), gen) for i, gen in enumerate(data_gens)]
        gen = StructGen(gen_list, nullable=False)
        data_path = spark_tmp_path + '/CSV_DATA'
        schema = gen.data_type
        updated_conf=_enable_all_types_conf.copy()
        updated_conf[disable_conf]='false'
    
        reader = read_func(data_path, schema)
        with_cpu_session(
                lambda spark : gen_df(spark, gen).write.csv(data_path))
        assert_gpu_fallback_collect(
                lambda spark : reader(spark).select(f.col('*'), f.col('_c2') + f.col('_c3')),
                'FileSourceScanExec',
>               conf=updated_conf)
integration_tests/src/main/python/csv_test.py[0m:292: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
integration_tests/src/main/python/asserts.py[0m:302: in assert_gpu_fallback_collect
    conf=conf)
integration_tests/src/main/python/spark_session.py[0m:95: in with_gpu_session
    return with_spark_session(func, conf=copy)

integration_tests/src/main/python/spark_session.py:68: in with_spark_session
c(_spark)
integration_tests/src/main/python/asserts.py:179: in <lambda>
k = lambda spark: limit_func(spark).collect()
integration_tests/src/main/python/csv_test.py:290: in <lambda>
ark : reader(spark).select(f.col('*'), f.col('_c2') + f.col('_c3')),
integration_tests/src/main/python/csv_test.py:180: in read_impl
bug_df(reader.csv(data_path))
integration_tests/src/main/python/data_gen.py:674: in debug_df
LLECTED\n{}'.format(df.collect()))
/mnt/yarn/usercache/hadoop/appcache/application_1618918487651_0003/container_1618918487651_0003_01_000001/pyspark.zip/pyspark/sql/dataframe.py:597: in collect
 = self._jdf.collectToPython()
/mnt/yarn/usercache/hadoop/appcache/application_1618918487651_0003/container_1618918487651_0003_01_000001/py4j-0.10.9-src.zip/py4j/java_gateway.py:1305: in __call__
elf.gateway_client, self.target_id, self.name)
/mnt/yarn/usercache/hadoop/appcache/application_1618918487651_0003/container_1618918487651_0003_01_000001/pyspark.zip/pyspark/sql/utils.py:134: in deco
    raise_from(converted)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

e = IllegalArgumentException('Part of the plan is not columnar class org.apache.spark.sql.execution.datasources.v2.BatchSc...:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\n', None)

>   ???
E   pyspark.sql.utils.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.datasources.v2.BatchScanExec
E   BatchScan[_c0#220142, _c1#220143, _c2#220144, _c3#220145, _c4#220146L, _c5#220147, _c6#220148] CSVScan DataFilters: [], Location: InMemoryFileIndex[hdfs://ip-172-31-7-149.us-west-2.compute.internal:8020/tmp/pyspark_tests/818508..., PartitionFilters: [], ReadSchema: struct<_c0:string,_c1:tinyint,_c2:smallint,_c3:int,_c4:bigint,_c5:boolean,_c6:date>, PushedFilters: []

<string>:3: IllegalArgumentException
----------------------------- Captured stdout call -----------------------------
### CPU RUN ###
COLLECTED
[Row(_c0='z0N1e99PS', _c1=53, _c2=-29908, _c3=None, _c4=2451761049700751885, _c5=True, _c6=datetime.date(5699, 9, 5)), Row(_c0='QzvqbD05AF', _c1=-24, _c2=-24633, _c3=-204549548, _c4=3368872244882951150, _c5=True, _c6=datetime.date(4, 2, 29)), Row(_c0='ZqJYqy\tVOF', _c1=53, _c2=31152, _c3=-673166729, _c4=-4519395617304985747, _c5=None, _c6=datetime.date(2138, 12, 29)), Row(_c0='5GGb0KP4D_', _c1=101, _c2=-19589, _c3=709206688, _c4=-5600721832451008419, _c5=True, _c6=datetime.date(1308, 4, 5)), Row(_c0='vAK8rs2Hod', _c1=40, _c2=-2435, _c3=857391859, _c4=-3384071289586606412, _c5=True, _c6=datetime.date(2340, 4, 19)), Row(_c0='jhWh7aw_NU', _c1=-71, _c2=682, _c3=-26756290, ...

**Steps/Code to reproduce bug**
Run pytests on EMR cluster with the script https://github.com/NVIDIA/spark-rapids/blob/branch-0.5/integration_tests/run_pyspark_from_build.sh#L129~L131

**Expected behavior**
All the python tests PASS

**Environment details (please complete the following information)**
 - Environment location: EMR Yarn cluster

**Comment by gerashegalov** [comment]
There are 4 instances of the parametrized test [test_csv_fallback](https://github.com/NVIDIA/spark-rapids/blob/branch-0.5/integration_tests/src/main/python/csv_test.py#L274).

2 of them are failing:
- csv_test.py::test_csv_fallback[spark.rapids.sql.format.csv.enabled-read_csv_df]
- csv_test.py::test_csv_fallback[spark.rapids.sql.format.csv.read.enabled-read_csv_df]

**Comment by gerashegalov** [comment]
For `spark.rapids.sql.format.csv.enabled-read_csv_df` with local Apache Spark 3.0.1 
We get a transformation from the CPU plan:
 ```
== Physical Plan ==
*(1) Project [_c0#21, _c1#22, _c2#23, _c3#24, _c4#25L, _c5#26, _c6#27, (cast(_c2#23 as int) + _c3#24) AS (_c2 + _c3)#42]
+- FileScan csv [_c0#21,_c1#22,_c2#23,_c3#24,_c4#25L,_c5#26,_c6#27] Batched: false, DataFilters: [], Format: CSV, Location: InMemoryFileIndex[file:/tmp/pyspark_tests/854806/CSV_DATA], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<_c0:string,_c1:tinyint,_c2:smallint,_c3:int,_c4:bigint,_c5:boolean,_c6:date>
```
to 
```
== Physical Plan ==
GpuColumnarToRow false
+- GpuProject [_c0#58, _c1#59, _c2#60, _c3#61, _c4#62L, _c5#63, _c6#64, (cast(_c2#60 as int) + _c3#61) AS (_c2 + _c3)#79]
   +- GpuRowToColumnar TargetSize(2147483647)
      +- FileScan csv [_c0#58,_c1#59,_c2#60,_c3#61,_c4#62L,_c5#63,_c6#64] Batched: false, DataFilters: [], Format: CSV, Location: InMemoryFileIndex[file:/tmp/pyspark_tests/854806/CSV_DATA], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<_c0:string,_c1:tinyint,_c2:smallint,_c3:int,_c4:bigint,_c5:boolean,_c6:date>
```

On EMR the same test  in the YARN cluster mode produces the plan with BatchScan
```
== Physical Plan ==
*(1) Project [_c0#21, _c1#22, _c2#23, _c3#24, _c4#25L, _c5#26, _c6#27, (cast(_c2#23 as int) + _c3#24) AS (_c2 + _c3)#42]
+- BatchScan[_c0#21, _c1#22, _c2#23, _c3#24, _c4#25L, _c5#26, _c6#27] CSVScan DataFilters: [], Location: InMemoryFileIndex[hdfs://ip-172-31-15-244.us-west-2.compute.internal:8020/tmp/pyspark_tests/89715..., PartitionFilters: [], ReadSchema: struct<_c0:string,_c1:tinyint,_c2:smallint,_c3:int,_c4:bigint,_c5:boolean,_c6:date>, PushedFilters: []
```
