### ISSUE TITLE
[BUG] GpuSort fails on tables containing arrays.

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#2225]
On `spark-rapids` `0.6` + `cudf-0.20`, when `GpuSort` is called on a table containing arrays, one sees the following failure:
```
21/04/21 19:31:14 WARN TaskSetManager: Lost task 5.0 in stage 3.0 (TID 43, 10.0.0.21, executor driver): ai.rapids.cudf.Cu
dfException: cuDF failure at: ../src/merge/merge.cu:246: Unsupported type for merge.
        at ai.rapids.cudf.Table.merge(Native Method)
        at ai.rapids.cudf.Table.merge(Table.java:1524)
        at com.nvidia.spark.rapids.GpuSorter.$anonfun$mergeSort$2(SortUtils.scala:204)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:55)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:53)
        at com.nvidia.spark.rapids.GpuSorter.withResource(SortUtils.scala:65)
        at com.nvidia.spark.rapids.GpuSorter.$anonfun$mergeSort$1(SortUtils.scala:200)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.GpuSorter.withResource(SortUtils.scala:65)
        at com.nvidia.spark.rapids.GpuSorter.mergeSort(SortUtils.scala:196)
        at com.nvidia.spark.rapids.GpuOutOfCoreSortIterator.$anonfun$mergeSortEnoughToOutput$2(GpuSortExec.scala:407)
...
```

I haven't boiled it down yet, but I _suspect_ that it's possible to reproduce this with a simpler case: On a large table containing an array column, run:
```sql
SELECT * FROM mytable ORDER BY non_array_column;
```

The following is a query where I see this occur:
```scala
val mybench = spark.read.parquet("/path/to/large.parquet")
mybench.createOrReplaceTempView("mytable")

val query = """
    SELECT uid, 
           SUM(dollars) 
               OVER ( PARTITION BY uid 
                       ORDER BY cast(dateLong/1000 AS TIMESTAMP) 
                       RANGE BETWEEN INTERVAL 14 DAYS PRECEDING AND CURRENT ROW) sum_dollars_14_days,
           COLLECT_LIST(dollars) 
               OVER ( PARTITION BY uid 
                       ORDER BY CAST(dateLong/1000 AS TIMESTAMP) 
                       RANGE BETWEEN INTERVAL 14 DAYS PRECEDING AND CURRENT ROW) collect_dollars_14_days
    FROM mytable
"""

val top_earners_query = s"""
  SELECT uid, collect_dollars_14_days, sum_dollars_14_days FROM ($query) ORDER BY sum_dollars_14_days DESC
""

sql(top_earners_query).show
```
Data schema:
```+--------+---------+-------+
|col_name|data_type|comment|
+--------+---------+-------+
|     uid|   bigint|   null|
|   uname|   string|   null|
|dateLong|   bigint|   null|
|      dt|     date|   null|
| dateStr|   string|   null|
| dollars|      int|   null|
+--------+---------+-------+
```

**Comment by mythrocks** [comment]
I have now confirmed that this fails with `rapids-4-spark*-0.5` + `cudf-0.19`, as well as `rapids-4-spark*-0.6` + `cudf-0.20`.

**Comment by revans2** [comment]
From the error you posted it looks like the merge sort API is not happy with arrays. I know it cannot support them as a key, but just going along for the ride I thought it would, but I should have done better testing.  I am not sure how it is implemented internally, but in either case we should file an issue against cudf for this, and also verify that structs work for it too. 

As a work around we can detect arrays in the table that we get to merge and switch to first concat the tables together and then sort them.  This is not going to be nearly as fast as merge is, but it will work in the short term.

**Comment by mythrocks** [comment]
> I know it cannot support them as a key, but just going along for the ride I thought it would...

I found this surprising as well. A trivial/hasty test with a nested-type table and a primitive sort key didn't reproduce the problem when I tried it. I'll need to spend a little longer trying to boil this down.
(For the moment, the test above does repro this reliably.)

**Comment by revans2** [comment]
Small sorts will not work because you need to do a merge sort.  The simplest way to do that is like with the new test that I added in recently.

https://github.com/NVIDIA/spark-rapids/blob/6274fadf2393ebf7d47ead7e322e672776cbefc1/integration_tests/src/main/python/sort_test.py#L165-L173

You would need to modify it to include another column with the type you want to test.

Or you could do some unit tests for merge itself.

**Comment by mythrocks** [comment]
Thanks for closing this, @revans2. I just confirmed that #2251 does fix the issue.
