### ISSUE TITLE
[BUG] hash_aggregate_test.py::test_hash_grpby_pivot FAILED on the Databricks Cluster

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#2232]
**Describe the bug**
  =================================== FAILURES ===================================
  _ test_hash_grpby_pivot[{'spark.rapids.sql.variableFloatAgg.enabled': 'true', 'spark.rapids.sql.hasNans': 'false', 'spark.rapids.sql.castStringToFloat.enabled': 'true'}-[('a', RepeatSeq(Decimal(7,3))), ('b', Decimal(5,2)), ('c', Decimal(8,3))]] _
  [gw3] linux -- Python 3.7.6 /databricks/conda/envs/databricks-ml-gpu/bin/python
  
  data_gen = [('a', RepeatSeq(Decimal(7,3))), ('b', Decimal(5,2)), ('c', Decimal(8,3))]
  conf = {'spark.rapids.sql.castStringToFloat.enabled': 'true', 'spark.rapids.sql.hasNans': 'false', 'spark.rapids.sql.variableFloatAgg.enabled': 'true', 'spark.sql.ansi.enabled': 'false'}
  
      @approximate_float
      @ignore_order(local=True)
      @incompat
      @pytest.mark.parametrize(data_gen', _init_list_no_nans_with_decimal, ids=idfn)
      @pytest.mark.parametrize(conf', get_params(_confs, params_markers_for_confs), ids=idfn)
      def test_hash_grpby_pivot(data_gen, conf):
          assert_gpu_and_cpu_are_equal_collect(
              lambda spark: gen_df(spark, data_gen, length=100)
                  .groupby(a')
                  .pivot(b')
                  .agg(f.sum(c')),
  >           conf=conf)
  
  ../../src/main/python/hash_aggregate_test.py:280: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  ../../src/main/python/asserts.py:360: in assert_gpu_and_cpu_are_equal_collect
      _assert_gpu_and_cpu_are_equal(func, COLLECT', conf=conf, is_cpu_first=is_cpu_first)
  ../../src/main/python/asserts.py:341: in _assert_gpu_and_cpu_are_equal
      run_on_gpu()
  ../../src/main/python/asserts.py:335: in run_on_gpu
      conf=conf)
  ../../src/main/python/spark_session.py:95: in with_gpu_session
      return with_spark_session(func, conf=copy)
  ../../src/main/python/spark_session.py:68: in with_spark_session
      ret = func(_spark)
  ../../src/main/python/asserts.py:179: in <lambda>
      bring_back = lambda spark: limit_func(spark).collect()
  /databricks/spark/python/pyspark/sql/dataframe.py:611: in collect
      sock_info = self._jdf.collectToPython()
  /databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py:1305: in __call__
      answer, self.gateway_client, self.target_id, self.name)
  /databricks/spark/python/pyspark/sql/utils.py:133: in deco
      raise_from(converted)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  e = IllegalArgumentException('Part of the plan is not columnar class org.apache.spark.sql.execution.aggregate.HashAggregat...:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:251)\n\tat java.lang.Thread.run(Thread.java:748)\n', None)
  

  E   pyspark.sql.utils.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.aggregate.HashAggregateExec
  E   HashAggregate(keys=[a#158109], functions=[finalmerge_pivotfirst(merge null#158226, 0.21#158227, 3.34#158228, 5.20#158229, 6.20#158230, 8.87#158231, 13.24#158232, 17.25#158233, 31.31#158234, 39.49#158235, 39.90#158236, 43.95#158237, 44.74#158238, 48.79#158239, 54.24#158240, 59.94#158241, 62.36#158242, 63.77#158243, 72.63#158244, 80.72#158245, 88.98#158246, 93.24#158247, 98.30#158248, 103.67#158249, 107.20#158250, 140.48#158251, 160.52#158252, 175.65#158253, 177.86#158254, 195.04#158255, 207.45#158256, 217.48#158257, 222.42#158258, 255.87#158259, 283.50#158260, 284.61#158261, 285.61#158262, 292.44#158263, 325.90#158264, 332.25#158265, 343.78#158266, 377.07#158267, 401.75#158268, 405.07#158269, 406.36#158270, 408.85#158271, 420.93#158272, 432.07#158273, 443.38#158274, 476.27#158275, 476.87#158276, 482.62#158277, 501.17#158278, 505.22#158279, 516.84#158280, 517.04#158281, 520.44#158282, 520.94#158283, 526.49#158284, 527.56#158285, 529.34#158286, 537.03#158287, 538.23#158288, 542.48#158289, 555.53#158290, 565.92#158291, 577.16#158292, 583.32#158293, 589.08#158294, 590.68#158295, 605.06#158296, 607.91#158297, 620.74#158298, 658.45#158299, 662.58#158300, 721.20#158301, 726.29#158302, 729.32#158303, 748.84#158304, 770.54#158305, 775.21#158306, 776.15#158307, 779.33#158308, 803.35#158309, 804.54#158310, 809.03#158311, 814.75#158312, 871.76#158313, 901.01#158314, 928.72#158315, 929.80#158316, 958.33#158317, 967.27#158318, 975.35#158319, 984.53#158320, 986.83#158321, 991.01#158322) AS pivotfirst(b#158110, sum(`c`)#158128, null, 0.21, 3.34, 5.20, 6.20, 8.87, 13.24, 17.25, 31.31, 39.49, 39.90, 43.95, 44.74, 48.79, 54.24, 59.94, 62.36, 63.77, 72.63, 80.72, 88.98, 93.24, ... 77 more fields)#158323], output=[a#158109, __pivot_sum(`c`) AS `sum(``c``)`#158324])
  E   +- GpuColumnarToRow false
  E      +- GpuShuffleCoalesce 2147483647
  E         +- GpuColumnarExchange gpuhashpartitioning(a#158109, 12), true, [id=#87328]
  E            +- GpuHashAggregate(keys=[a#158109], functions=[partial_gpupivotfirst(b#158110, sum(`c`)#158128, null, 0.21, 3.34, 5.20, 6.20, 8.87, 13.24, 17.25, 31.31, 39.49, 39.90, 43.95, 44.74, 48.79, 54.24, 59.94, 62.36, 63.77, 72.63, 80.72, 88.98, 93.24, 98.30, 103.67, 107.20, 140.48, 160.52, 175.65, 177.86, 195.04, 207.45, 217.48, 222.42, 255.87, 283.50, 284.61, 285.61, 292.44, 325.90, 332.25, 343.78, 377.07, 401.75, 405.07, 406.36, 408.85, 420.93, 432.07, 443.38, 476.27, 476.87, 482.62, 501.17, 505.22, 516.84, 517.04, 520.44, 520.94, 526.49, 527.56, 529.34, 537.03, 538.23, 542.48, 555.53, 565.92, 577.16, 583.32, 589.08, 590.68, 605.06, 607.91, 620.74, 658.45, 662.58, 721.20, 726.29, 729.32, 748.84, 770.54, 775.21, 776.15, 779.33, 803.35, 804.54, 809.03, 814.75, 871.76, 901.01, 928.72, 929.80, 958.33, 967.27, 975.35, 984.53, 986.83, 991.01)], output=[a#158109, null#158226, 0.21#158227, 3.34#158228, 5.20#158229, 6.20#158230, 8.87#158231, 13.24#158232, 17.25#158233, 31.31#158234, 39.49#158235, 39.90#158236, 43.95#158237, 44.74#158238, 48.79#158239, 54.24#158240, 59.94#158241, 62.36#158242, 63.77#158243, 72.63#158244, 80.72#158245, 88.98#158246, 93.24#158247, 98.30#158248, ... 74 more fields])
  E               +- GpuHashAggregate(keys=[a#158109, b#158110], functions=[gpusum(UnscaledValue(c#158111), LongType)], output=[a#158109, b#158110, sum(`c`)#158128])
  E                  +- GpuShuffleCoalesce 2147483647
  E                     +- GpuColumnarExchange gpuhashpartitioning(a#158109, b#158110, 12), true, [id=#87324]
  E                        +- GpuHashAggregate(keys=[a#158109, b#158110], functions=[partial_gpusum(UnscaledValue(c#158111), LongType)], output=[a#158109, b#158110, sum#158715L])
  E                           +- GpuRowToColumnar TargetSize(2147483647)
  E                              +- Scan ExistingRDD[a#158109,b#158110,c#158111]
  
  <string>:3: IllegalArgumentException
  ----------------------------- Captured stdout call -----------------------------
  ### CPU RUN ###
  ### GPU RUN ###
  ----------------------------- Captured stderr call -----------------------------
  21/04/22 10:48:57 WARN SQLExecution: Error executing delta metering
  java.lang.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.aggregate.HashAggregateExec
  HashAggregate(keys=[a#158109], functions=[finalmerge_pivotfirst(merge null#158226, 0.21#158227, 3.34#158228, 5.20#158229, 6.20#158230, 8.87#158231, 13.24#158232, 17.25#158233, 31.31#158234, 39.49#158235, 39.90#158236, 43.95#158237, 44.74#158238, 48.79#158239, 54.24#158240, 59.94#158241, 62.36#158242, 63.77#158243, 72.63#158244, 80.72#158245, 88.98#158246, 93.24#158247, 98.30#158248, 103.67#158249, 107.20#158250, 140.48#158251, 160.52#158252, 175.65#158253, 177.86#158254, 195.04#158255, 207.45#158256, 217.48#158257, 222.42#158258, 255.87#158259, 283.50#158260, 284.61#158261, 285.61#158262, 292.44#158263, 325.90#158264, 332.25#158265, 343.78#158266, 377.07#158267, 401.75#158268, 405.07#158269, 406.36#158270, 408.85#158271, 420.93#158272, 432.07#158273, 443.38#158274, 476.27#158275, 476.87#158276, 482.62#158277, 501.17#158278, 505.22#158279, 516.84#158280, 517.04#158281, 520.44#158282, 520.94#158283, 526.49#158284, 527.56#158285, 529.34#158286, 537.03#158287, 538.23#158288, 542.48#158289, 555.53#158290, 565.92#158291, 577.16#158292, 583.32#158293, 589.08#158294, 590.68#158295, 605.06#158296, 607.91#158297, 620.74#158298, 658.45#158299, 662.58#158300, 721.20#158301, 726.29#158302, 729.32#158303, 748.84#158304, 770.54#158305, 775.21#158306, 776.15#158307, 779.33#158308, 803.35#158309, 804.54#158310, 809.03#158311, 814.75#158312, 871.76#158313, 901.01#158314, 928.72#158315, 929.80#158316, 958.33#158317, 967.27#158318, 975.35#158319, 984.53#158320, 986.83#158321, 991.01#158322) AS pivotfirst(b#158110, sum(`c`)#158128, null, 0.21, 3.34, 5.20, 6.20, 8.87, 13.24, 17.25, 31.31, 39.49, 39.90, 43.95, 44.74, 48.79, 54.24, 59.94, 62.36, 63.77, 72.63, 80.72, 88.98, 93.24, ... 77 more fields)#158323], output=[a#158109, __pivot_sum(`c`) AS `sum(``c``)`#158324])
  +- GpuColumnarToRow false
     +- GpuShuffleCoalesce 2147483647
        +- GpuColumnarExchange gpuhashpartitioning(a#158109, 12), true, [id=#87453]
           +- GpuHashAggregate(keys=[a#158109], functions=[partial_gpupivotfirst(b#158110, sum(`c`)#158128, null, 0.21, 3.34, 5.20, 6.20, 8.87, 13.24, 17.25, 31.31, 39.49, 39.90, 43.95, 44.74, 48.79, 54.24, 59.94, 62.36, 63.77, 72.63, 80.72, 88.98, 93.24, 98.30, 103.67, 107.20, 140.48, 160.52, 175.65, 177.86, 195.04, 207.45, 217.48, 222.42, 255.87, 283.50, 284.61, 285.61, 292.44, 325.90, 332.25, 343.78, 377.07, 401.75, 405.07, 406.36, 408.85, 420.93, 432.07, 443.38, 476.27, 476.87, 482.62, 501.17, 505.22, 516.84, 517.04, 520.44, 520.94, 526.49, 527.56, 529.34, 537.03, 538.23, 542.48, 555.53, 565.92, 577.16, 583.32, 589.08, 590.68, 605.06, 607.91, 620.74, 658.45, 662.58, 721.20, 726.29, 729.32, 748.84, 770.54, 775.21, 776.15, 779.33, 803.35, 804.54, 809.03, 814.75, 871.76, 901.01, 928.72, 929.80, 958.33, 967.27, 975.35, 984.53, 986.83, 991.01)], output=[a#158109, null#158226, 0.21#158227, 3.34#158228, 5.20#158229, 6.20#158230, 8.87#158231, 13.24#158232, 17.25#158233, 31.31#158234, 39.49#158235, 39.90#158236, 43.95#158237, 44.74#158238, 48.79#158239, 54.24#158240, 59.94#158241, 62.36#158242, 63.77#158243, 72.63#158244, 80.72#158245, 88.98#158246, 93.24#158247, 98.30#158248, ... 74 more fields])
              +- GpuHashAggregate(keys=[a#158109, b#158110], functions=[gpusum(UnscaledValue(c#158111), LongType)], output=[a#158109, b#158110, sum(`c`)#158128])
                 +- GpuShuffleCoalesce 2147483647
                    +- GpuColumnarExchange gpuhashpartitioning(a#158109, b#158110, 12), true, [id=#87449]
                       +- GpuHashAggregate(keys=[a#158109, b#158110], functions=[partial_gpusum(UnscaledValue(c#158111), LongType)], output=[a#158109, b#158110, sum#158715L])
                          +- GpuRowToColumnar TargetSize(2147483647)
                             +- Scan ExistingRDD[a#158109,b#158110,c#158111]
  
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.assertIsOnTheGpu(GpuTransitionOverrides.scala:436)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.$anonfun$assertIsOnTheGpu$6(GpuTransitionOverrides.scala:449)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.$anonfun$assertIsOnTheGpu$6$adapted(GpuTransitionOverrides.scala:449)
  	at scala.collection.immutable.List.foreach(List.scala:392)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.assertIsOnTheGpu(GpuTransitionOverrides.scala:449)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.$anonfun$assertIsOnTheGpu$6(GpuTransitionOverrides.scala:449)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.$anonfun$assertIsOnTheGpu$6$adapted(GpuTransitionOverrides.scala:449)
  	at scala.collection.immutable.List.foreach(List.scala:392)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.assertIsOnTheGpu(GpuTransitionOverrides.scala:449)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.$anonfun$assertIsOnTheGpu$6(GpuTransitionOverrides.scala:449)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.$anonfun$assertIsOnTheGpu$6$adapted(GpuTransitionOverrides.scala:449)
  	at scala.collection.immutable.List.foreach(List.scala:392)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.assertIsOnTheGpu(GpuTransitionOverrides.scala:449)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.apply(GpuTransitionOverrides.scala:498)
  	at com.nvidia.spark.rapids.GpuTransitionOverrides.apply(GpuTransitionOverrides.scala:41)
  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$2(Columnar.scala:521)
  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.$anonfun$apply$2$adapted(Columnar.scala:520)
  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:520)
  	at org.apache.spark.sql.execution.ApplyColumnarRulesAndInsertTransitions.apply(Columnar.scala:482)
  	at org.apache.spark.sql.execution.QueryExecution$.$anonfun$prepareForExecution$1(QueryExecution.scala:406)
  	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
  	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
  	at scala.collection.immutable.List.foldLeft(List.scala:89)
  	at org.apache.spark.sql.execution.QueryExecution$.prepareForExecution(QueryExecution.scala:406)
  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:139)
  	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
  	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:171)
  	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)
  	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:171)
  	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:135)
  	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:131)
  	at com.databricks.sql.transaction.tahoe.metering.DeltaMetering$.reportUsage(ScanReport.scala:146)
  	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:167)
  	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:249)
  	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:101)
  	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)
  	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)
  	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:199)
  	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3707)
  	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3495)
  	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
  	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
  	at py4j.Gateway.invoke(Gateway.java:295)
  	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
  	at py4j.commands.CallCommand.execute(CallCommand.java:79)
  	at py4j.GatewayConnection.run(GatewayConnection.java:251)
  	at java.lang.Thread.run(Thread.java:748)
  =============================== warnings summary ===============================
  ../../../../../databricks/spark/python/pyspark/sql/context.py:77
  ../../../../../databricks/spark/python/pyspark/sql/context.py:77
  ../../../../../databricks/spark/python/pyspark/sql/context.py:77
  ../../../../../databricks/spark/python/pyspark/sql/context.py:77
  ../../../../../databricks/spark/python/pyspark/sql/context.py:77
  ../../../../../databricks/spark/python/pyspark/sql/context.py:77
  src/main/python/mortgage_test.py::test_mortgage[IGNORE_ORDER, INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(ANY), LIMIT(100000)]
  src/main/python/mortgage_test.py::test_mortgage[IGNORE_ORDER, INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(ANY), LIMIT(100000)]
    /databricks/spark/python/pyspark/sql/context.py:77: DeprecationWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
      DeprecationWarning)

**Steps/Code to reproduce bug**
Run pytests on Dataproc cluster with the script:
https://github.com/NVIDIA/spark-rapids/blob/branch-0.5/integration_tests/run_pyspark_from_build.sh#L125-L127

**Expected behavior**
All the python tests PASS

**Environment details (please complete the following information)**
 - [Databricks]

**Comment by nartal1** [comment]
Setting up on databricks to debug took most of the time.  I was able to reproduce it with a simple query.  The difference is in the decimal type, after  shuffle of partial_pivotfirst, `Alias` is added for `pivotFirst` as `__pivot_sum`. So later it complains that:
`unsupported data types in output: __pivot_sum(`Country`)` . 

On databricks(after partial_pivotfirst):
```
*Exec <CollectLimitExec> will run on GPU
  *Partitioning <SinglePartition$> will run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> cast(Product#16 as string) AS Product#62 will run on GPU
      *Expression <Cast> cast(Product#16 as string) will run on GPU
    *Expression <Alias> cast(__pivot_sum(`Country`) AS `sum(``Country``)`#53[0] as string) AS 100.00#63 will run on GPU
      *Expression <Cast> cast(__pivot_sum(`Country`) AS `sum(``Country``)`#53[0] as string) will run on GPU
        *Expression <GetArrayItem> __pivot_sum(`Country`) AS `sum(``Country``)`#53[0] will run on GPU
    *Expression <Alias> cast(__pivot_sum(`Country`) AS `sum(``Country``)`#53[1] as string) AS 200.00#64 will run on GPU
      *Expression <Cast> cast(__pivot_sum(`Country`) AS `sum(``Country``)`#53[1] as string) will run on GPU
        *Expression <GetArrayItem> __pivot_sum(`Country`) AS `sum(``Country``)`#53[1] will run on GPU
    !Exec <HashAggregateExec> cannot run on GPU because unsupported data types in output: __pivot_sum(`Country`) AS `sum(``Country``)`#53
      @Expression <AttributeReference> Product#16 could run on GPU
      @Expression <AttributeReference> Product#16 could run on GPU
      @Expression <AggregateExpression> finalmerge_pivotfirst(merge 100.00#50, 200.00#51) AS pivotfirst(Amount#17, sum(`Country`)#47, 100.00, 200.00, 0, 0)#52 could run on GPU
        @Expression <PivotFirst> pivotfirst(Amount#17, sum(`Country`)#47, 100.00, 200.00, 0, 0) could run on GPU
          @Expression <AttributeReference> Amount#17 could run on GPU
          @Expression <AttributeReference> sum(`Country`)#47 could run on GPU
      @Expression <AttributeReference> pivotfirst(Amount#17, sum(`Country`)#47, 100.00, 200.00, 0, 0)#52 could run on GPU
      @Expression <AttributeReference> Product#16 could run on GPU
      @Expression <Alias> pivotfirst(Amount#17, sum(`Country`)#47, 100.00, 200.00, 0, 0)#52 AS __pivot_sum(`Country`) AS `sum(``Country``)`#53 could run on GPU
        @Expression <AttributeReference> pivotfirst(Amount#17, sum(`Country`)#47, 100.00, 200.00, 0, 0)#52 could run on GPU
      *Exec <ShuffleExchangeExec> will run on GPU
        *Partitioning <HashPartitioning> will run on GPU
        *Exec <HashAggregateExec> will run on GPU
          *Expression <AggregateExpression> partial_pivotfirst(Amount#17, sum(`Country`)#47, 100.00, 200.00, 0, 0) AS (100.00#50, 200.00#51) will run on GPU

```


On local machine(after pivotfirst):

```
*Exec <CollectLimitExec> will run on GPU
  *Partitioning <SinglePartition$> will run on GPU
  *Exec <HashAggregateExec> will run on GPU
    *Expression <AggregateExpression> pivotfirst(Amount#17, sum(`Country`)#116, 100.00, 200.00, 0, 0) will run on GPU
      *Expression <PivotFirst> pivotfirst(Amount#17, sum(`Country`)#116, 100.00, 200.00, 0, 0) will run on GPU
    *Expression <Alias> cast(Product#16 as string) AS Product#131 will run on GPU
      *Expression <Cast> cast(Product#16 as string) will run on GPU
    *Expression <Alias> cast(pivotfirst(Amount#17, sum(`Country`)#116, 100.00, 200.00, 0, 0)#121[0] as string) AS 100.00#132 will run on GPU
      *Expression <Cast> cast(pivotfirst(Amount#17, sum(`Country`)#116, 100.00, 200.00, 0, 0)#121[0] as string) will run on GPU
        *Expression <GetArrayItem> pivotfirst(Amount#17, sum(`Country`)#116, 100.00, 200.00, 0, 0)#121[0] will run on GPU
    *Expression <Alias> cast(pivotfirst(Amount#17, sum(`Country`)#116, 100.00, 200.00, 0, 0)#121[1] as string) AS 200.00#133 will run on GPU
      *Expression <Cast> cast(pivotfirst(Amount#17, sum(`Country`)#116, 100.00, 200.00, 0, 0)#121[1] as string) will run on GPU
        *Expression <GetArrayItem> pivotfirst(Amount#17, sum(`Country`)#116, 100.00, 200.00, 0, 0)#121[1] will run on GPU
    *Exec <ShuffleExchangeExec> will run on GPU
      *Partitioning <HashPartitioning> will run on GPU
      *Exec <HashAggregateExec> will run on GPU
        *Expression <AggregateExpression> partial_pivotfirst(Amount#17, sum(`Country`)#116, 100.00, 200.00, 0, 0) will run on GPU
```

**Comment by revans2** [comment]
So it looks like Databricks moved the GetArrayItem out form inside the HashAggregate to outside of it, in a separate project. I think the first step is to allow HashAggregateExec to return an ArrayType.  After than we need to re-run the test and see if there is something else that is different.

**Comment by nartal1** [comment]
Thanks @revans2 .  Allowing DecimalType in HashAggregateExec's  nested type  made the test to pass.  I will put up a PR.
