### ISSUE TITLE
Optimize ParquetCacheBatchSerializer

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2234]
This is an uber issue to track optimizations needed in Cache Serializer

* Only pass the needed conf instead of broadcasting the Map
* Compression is AUTO right now which may compromise performance 
* Filter method is a noop at  the moment, this might impact performance

**Comment by sameerz** [comment]
Is this a duplicate of #1143?  If not, can this be combined with the already open issue?

**Comment by razajafri** [comment]
Yes, thanks for pointing that out @sameerz
