### ISSUE TITLE
Add nightly tests for UDF examples

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#2236]
We are starting to get more UDF examples checked in to the repository (for example PR #2226).  We need to add nightly tests for the UDF examples.

**Comment by GaryShen2008** [comment]
Ad Tim to confirm the udf example test cases will be ran automatically after merging to integration test.
If so, we don't need any action items here.

**Comment by jlowe** [comment]
The native UDF examples will not be run without extra work.  They are excluded from the build by default since not every Java build environment can provide the requisite components for a native build (currently requires cmake 3.18+, CUDA 11+, gcc 9+, etc.).  The `udf-native-examples` maven profile must be requested in order to build the native UDF example code.  In addition the `--rapids_udf_example_native` flag must be specified on the pytest cmdline to enable the native UDF example integration tests.

Note that adding native UDF examples to the build will increase the build time significantly, since it pulls in libcudf source and builds it as part of the process.

**Comment by NvTimLiu** [comment]
I'm checking this issue.

For build part: seems we need to set up an environment (cmake 3.18+, CUDA 11+, gcc 9+ ) to build both spark-rapids and cuDF jars, and with maven flag `-Dudf-native-examples`

For test part: we need a pytest flag `--rapids_udf_example_native`

Suppose we need to test it against all the spark release/SNAPSHOT envrionments

**Comment by jlowe** [comment]
> to build both spark-rapids and cuDF jars

Building the cudf jar is unnecessary for this.  The cudf jar will be pulled in via Maven dependencies as usual.  The only difference is that the `udf-examples` project will end up building libcudf so it can compile and link against it.  That build of libcudf won't be shipped in any jar, it's only used to produce the native code that is placed in the udf-examples jar.

> Suppose we need to test it against all the spark release/SNAPSHOT environments

Let's get it working against the minimum Spark version for now, we can expand to other environments after one of them is working.

**Comment by NvTimLiu** [comment]
@jlowe Thanks a lot for your reminding.

I've PASS the test locally as below, am setting up nightly Jenkins against it.

============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.2.3, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /spark-rapids/integration_tests, configfile: pytest.ini
plugins: xdist-2.2.1, forked-1.3.0
collecting ... collected 6351 items / 6348 deselected / 3 selected

../../src/main/python/rapids_udf_test.py::test_hive_simple_udf_native PASSED [ 33%]
../../src/main/python/rapids_udf_test.py::test_java_cosine_similarity_reasonable_range PASSED [ 66%]
../../src/main/python/rapids_udf_test.py::test_java_cosine_similarity_with_nans PASSED [100%]

=============================== warnings summary ===============================
../../../../usr/local/python3/lib/python3.8/site-packages/pandas/compat/__init__.py:97
  /usr/local/python3/lib/python3.8/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
    warnings.warn(msg)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================ 3 passed, 6348 deselected, 1 warning in 12.78s ================

**Comment by NvTimLiu** [comment]
Blossom Jenkins  created rapids_it-UDF-native

**Comment by NvTimLiu** [comment]
As Jenkins pipeline is running, suppose we are good to close the issue
