### ISSUE TITLE
[FEA] Audit CoalesceExec

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#227]
**Is your feature request related to a problem? Please describe.**

- Ensure Spark and Rapids plugin version of the exec match functionality.

- Verify Config specific to the operator match.

- Verify API is consistent and fully translated.

- Port relevant tests.

**Comment by razajafri** [comment]
Completed the analysis.

* functionality and API matches
* Some tests are ported for IO. Rest of the tests aren't ported.

**Comment by kuhushukla** [comment]
Can we look the follow on issue here for tests. Thanks!

**Comment by razajafri** [comment]
This issue tracks the coalesce tests #316
