### ISSUE TITLE
[FEA] Audit GenerateExec

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#228]
**Is your feature request related to a problem? Please describe.**

- Ensure Spark and Rapids plugin version of the exec match functionality.

- Verify Config specific to the operator match.

- Verify API is consistent and fully translated.

- Port relevant tests.

**Comment by kuhushukla** [comment]
@nartal1 can u list the configs that dont match here for completeness? Thanks!

**Comment by nartal1** [comment]
> @nartal1 can u list the configs that dont match here for completeness? Thanks!

Sorry missed this. It should have written "API is not translated fully" instead of configs.  Took a look again and we  are good on configs(no configs on Spark side).

**Comment by nartal1** [comment]
To make it work, we would need some operations support(explode, posexplode) from libcudf. 
There was already an issue filed for explode support. Created an issue for posexplode.
Depends on https://github.com/rapidsai/cudf/issues/2975 and https://github.com/rapidsai/cudf/issues/6025

**Comment by nartal1** [comment]
Removing it from current milestone.
@sameerz - I am not sure if we could complete it by `Release-0.2` as it depends on libcudf. 
Please let me know if we can remove this from `Release-0.2`.
