### ISSUE TITLE
[FEA] Can RTX 3080 be supported with plugin 0.6 and CUDA 11?

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2280]
**Is your feature request related to a problem? Please describe.**
I have previously been able to run version 0.5.0-SNAPSHOT of the plugin on an RTX 3080 but this no longer seems to be supported with the latest plugin code and CUDA 11. 

```
21/04/26 10:15:39.146 ScalaTest-main-running-HashAggregatesSuite INFO RapidsExecutorPlugin: cudf build: {version=0.20-SNAPSHOT, user=, date=2021-04-26T14:41:35Z, revision=6e1398844e682a9ebbe6d0e61a3f4522399e60a4, branch=HEAD}
21/04/26 10:15:39.151 ScalaTest-main-running-HashAggregatesSuite INFO RapidsExecutorPlugin: Initializing memory from Executor Plugin
21/04/26 10:15:41.910 ScalaTest-main-running-HashAggregatesSuite ERROR RapidsExecutorPlugin: Exception in the executor plugin
ai.rapids.cudf.CudaException: forward compatibility was attempted on non supported HW
        at ai.rapids.cudf.Cuda.getDeviceCount(Native Method)
        at com.nvidia.spark.rapids.GpuDeviceManager$.findGpuAndAcquire(GpuDeviceManager.scala:78)
```

**Describe the solution you'd like**
I would like to be able to run the plugin with an RTX 3080.

**Describe alternatives you've considered**
None

**Additional context**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3080    Off  | 00000000:42:00.0  On |                  N/A |
|  0%   39C    P8    12W / 320W |    477MiB / 10016MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by andygrove** [comment]
I will test against cuDF as well and file an issue there

**Comment by jlowe** [comment]
The [CUDA compatibility page](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#supported-gpus) mentions forward compatibility is only supported on Tesla cards.

What CUDA runtime(s) do you have installed?  It would be interesting to see if you can get it to work by installing the same CUDA runtime that was used when it was built.

**Comment by sameerz** [comment]
This needs to be documented in the 0.6 release.

**Comment by andygrove** [comment]
I was able to get tests to run by setting `CUDA_HOME` to point to the 11.0 version. I also had to modify RapidsConf to reduce `spark.rapids.memory.gpu.allocFraction` from 0.9 to 0.7 because I am using the RTX 3080 to drive my display. It would be nice to be able to set this from the command line when running Maven. I don't know if we have that capability or not but will take a look at that later today.

**Comment by jlowe** [comment]
> I also had to modify RapidsConf to reduce spark.rapids.memory.gpu.allocFraction from 0.9 to 0.7 because I am using the RTX 3080 to drive my display.

Another possibility may be to have the alloc fraction be relative to the free memory on the GPU rather than total memory.  Might be problematic to apply this to all GPU configs and therefore be confusing if it's not consistently applied to total.

**Comment by andygrove** [comment]
Here is one solution:

```scala
class RapidsConf(baseConf: Map[String, String]) extends Logging {

  private val conf = baseConf.map {
    case (k, v) => 
      k -> Option(System.getProperty(k)).getOrElse(v)
  }
```

This allows me to run:

```bash
mvn clean verify -DargLine="-Dspark.rapids.memory.gpu.allocFraction=0.7"
```

If this is acceptable, I can create a PR with updated docs.

**Comment by andygrove** [comment]
I created https://github.com/NVIDIA/spark-rapids/pull/2429 to implement the proposed change.

**Comment by andygrove** [comment]
> This needs to be documented in the 0.6 release.

I propose that we add content to the FAQ explaining that if the user sees `ai.rapids.cudf.CudaException: forward compatibility was attempted on non supported HW` then  they should set `CUDA_HOME` to point to the CUDA version that the plugin was compiled against.

I will create a PR for this.
