### ISSUE TITLE
[FEA] Optimize join followed by a project/drop

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#23]
**Is your feature request related to a problem? Please describe.**
There are cases, TPC-H query 17, where a join happens and then many of the columns are dropped.  It would be great if we could tell cudf not to bother materializing the columns that we know are not needed any more and will be dropped.

**Comment by jlowe** [comment]
This should be possible once https://github.com/rapidsai/cudf/issues/6480 is implemented.

**Comment by mattahrens** [comment]
Closing as won't fix for now
