### ISSUE TITLE
[FEA] Audit FilterExec 

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#230]
**Is your feature request related to a problem? Please describe.**

- Ensure Spark and Rapids plugin version of the exec match functionality.

- Verify Config specific to the operator match.

- Verify API is consistent and fully translated.

- Port relevant tests.

**Comment by nartal1** [comment]
Ensure Spark and Rapids plugin version of the exec match functionality.
- It does. 

Verify Config specific to the operator match.
- Verified and it looks good.

Verify API is consistent and fully translated.
- API is consistent. It takes the same number of arguments and all the Spark execs are translated to their corresponding GPUExecs.

Port relevant tests.
- We have covered Filter in other tests as well so it's been tested extensively. Need to add metrics related changes which will be covered in this  issue https://github.com/NVIDIA/spark-rapids/issues/198. 
Closing this as verified.
