### ISSUE TITLE
[BUG] v0.5.0 pre-release pytests join_test.py::test_hash_join_array FAILED on SPARK-EGX Yarn Cluster

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#2314]
**Describe the bug**

21:30:49  FAILED integration_tests/src/main/python/join_test.py::test_hash_join_array[Left-Array(String)][IGNORE_ORDER({'local': True})]
21:30:49  FAILED integration_tests/src/main/python/join_test.py::test_hash_join_array[Right-Array(String)][IGNORE_ORDER({'local': True})]
21:30:49  FAILED integration_tests/src/main/python/join_test.py::test_hash_join_array[Inner-Array(String)][IGNORE_ORDER({'local': True})]
21:30:49  FAILED integration_tests/src/main/python/join_test.py::test_hash_join_array[LeftSemi-Array(String)][IGNORE_ORDER({'local': True})]
21:30:49  FAILED integration_tests/src/main/python/join_test.py::test_hash_join_array[LeftAnti-Array(String)][IGNORE_ORDER({'local': True})]
21:30:49  FAILED integration_tests/src/main/python/join_test.py::test_hash_join_array[Cross-Array(String)][IGNORE_ORDER({'local': True})]
21:30:49  FAILED integration_tests/src/main/python/join_test.py::test_hash_join_array[FullOuter-Array(String)][IGNORE_ORDER({'local': True})]

  =================================== FAILURES ===================================
  ___________________ test_hash_join_array[Left-Array(String)] ___________________
  
  data_gen = Array(String), join_type = 'Left'
  
      @validate_execs_in_gpu_plan('GpuShuffledHashJoinExec')
      @ignore_order(local=True)
      @pytest.mark.parametrize('data_gen', single_level_array_gens_no_decimal, ids=idfn)
      @pytest.mark.parametrize('join_type', ['Left', 'Right', 'Inner', 'LeftSemi', 'LeftAnti', 'Cross', 'FullOuter'], ids=idfn)
      def test_hash_join_array(data_gen, join_type):
          def do_join(spark):
              left, right = create_nested_df(spark, short_gen, data_gen, 50, 500)
              return left.join(right, left.key == right.r_key, join_type)
  >       assert_gpu_and_cpu_are_equal_collect(do_join, conf=_hash_join_conf)
  
  integration_tests/src/main/python/join_test.py:147: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  integration_tests/src/main/python/asserts.py:359: in assert_gpu_and_cpu_are_equal_collect
      _assert_gpu_and_cpu_are_equal(func, 'COLLECT', conf=conf, is_cpu_first=is_cpu_first)
  integration_tests/src/main/python/asserts.py:340: in _assert_gpu_and_cpu_are_equal
      run_on_gpu()
  integration_tests/src/main/python/asserts.py:334: in run_on_gpu
      from_gpu = with_gpu_session(bring_back, conf=conf)
  integration_tests/src/main/python/spark_session.py:95: in with_gpu_session
      return with_spark_session(func, conf=copy)
  integration_tests/src/main/python/spark_session.py:68: in with_spark_session
      ret = func(_spark)
  integration_tests/src/main/python/asserts.py:179: in <lambda>
      bring_back = lambda spark: limit_func(spark).collect()
  /hadoop_disks/disk0/local/usercache/****/appcache/application_1603128018386_7467/container_e87_1603128018386_7467_01_000001/pyspark.zip/pyspark/sql/dataframe.py:596: in collect
      sock_info = self._jdf.collectToPython()
  /hadoop_disks/disk0/local/usercache/****/appcache/application_1603128018386_7467/container_e87_1603128018386_7467_01_000001/py4j-0.10.9-src.zip/py4j/java_gateway.py:1305: in __call__
      answer, self.gateway_client, self.target_id, self.name)
  /hadoop_disks/disk0/local/usercache/****/appcache/application_1603128018386_7467/container_e87_1603128018386_7467_01_000001/pyspark.zip/pyspark/sql/utils.py:128: in deco
      return f(*a, **kw)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  answer = 'xro139991'
  gateway_client = <py4j.java_gateway.GatewayClient object at 0x7f316b5df4e0>
  target_id = 'o139990', name = 'collectToPython'
  
      def get_return_value(answer, gateway_client, target_id=None, name=None):
          """Converts an answer received from the Java gateway into a Python object.
      
          For example, string representation of integers are converted to Python
          integer, string representation of objects are converted to JavaObject
          instances, etc.
      
          :param answer: the string returned by the Java gateway
          :param gateway_client: the gateway client used to communicate with the Java
              Gateway. Only necessary if the answer is a reference (e.g., object,
              list, map)
          :param target_id: the name of the object from which the answer comes from
              (e.g., *object1* in `object1.hello()`). Optional.
          :param name: the name of the member from which the answer comes from
              (e.g., *hello* in `object1.hello()`). Optional.
          """
          if is_error(answer)[0]:
              if len(answer) > 1:
                  type = answer[1]
                  value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                  if answer[1] == REFERENCE_TYPE:
                      raise Py4JJavaError(
                          "An error occurred while calling {0}{1}{2}.\n".
  >                       format(target_id, ".", name), value)
  E                   py4j.protocol.Py4JJavaError: An error occurred while calling o139990.collectToPython.
  E                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 33 in stage 2686.0 failed 4 times, most recent failure: Lost task 33.3 in stage 2686.0 (TID 109296, spark-egx-08.nvidia.com, executor 6): ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-cudf-release-9-cuda10.1/cpp/include/cudf/strings/detail/utilities.cuh:52: Invalid iterator range
  E                   	at ai.rapids.cudf.Table.partition(Native Method)
  E                   	at ai.rapids.cudf.Table.partition(Table.java:1285)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$partitionInternalAndClose$6(GpuHashPartitioning.scala:61)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$partitionInternalAndClose$5(GpuHashPartitioning.scala:60)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$partitionInternalAndClose$1(GpuHashPartitioning.scala:59)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.partitionInternalAndClose(GpuHashPartitioning.scala:51)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$2(GpuHashPartitioning.scala:82)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$1(GpuHashPartitioning.scala:81)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.columnarEval(GpuHashPartitioning.scala:78)
  E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$.$anonfun$prepareBatchShuffleDependency$3(GpuShuffleExchangeExec.scala:203)
  E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:224)
  E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:235)
  E                   	at scala.collection.Iterator.foreach(Iterator.scala:941)
  E                   	at scala.collection.Iterator.foreach$(Iterator.scala:941)
  E                   	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
  E                   	at org.apache.spark.sql.rapids.RapidsCachingWriter.write(RapidsShuffleInternalManagerBase.scala:97)
  E                   	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
  E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
  E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
  E                   	at org.apache.spark.scheduler.Task.run(Task.scala:127)
  E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
  E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
  E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
  E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  E                   	at java.lang.Thread.run(Thread.java:748)
  E                   
  E                   Driver stacktrace:
  E                   	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2059)
  E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2008)
  E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2007)
  E                   	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  E                   	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  E                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  E                   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2007)
  E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:973)
  E                   	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:973)
  E                   	at scala.Option.foreach(Option.scala:407)
  E                   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:973)
  E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2239)
  E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2188)
  E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2177)
  E                   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
  E                   	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:775)
  E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
  E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2120)
  E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2139)
  E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2164)
  E                   	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
  E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  E                   	at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
  E                   	at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
  E                   	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:385)
  E                   	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3450)
  E                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3618)
  E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
  E                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
  E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
  E                   	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
  E                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
  E                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3616)
  E                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3447)
  E                   	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
  E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  E                   	at java.lang.reflect.Method.invoke(Method.java:498)
  E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
  E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
  E                   	at py4j.Gateway.invoke(Gateway.java:282)
  E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
  E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
  E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
  E                   	at java.lang.Thread.run(Thread.java:748)
  E                   Caused by: ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-cudf-release-9-cuda10.1/cpp/include/cudf/strings/detail/utilities.cuh:52: Invalid iterator range
  E                   	at ai.rapids.cudf.Table.partition(Native Method)
  E                   	at ai.rapids.cudf.Table.partition(Table.java:1285)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$partitionInternalAndClose$6(GpuHashPartitioning.scala:61)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$partitionInternalAndClose$5(GpuHashPartitioning.scala:60)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$partitionInternalAndClose$1(GpuHashPartitioning.scala:59)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.partitionInternalAndClose(GpuHashPartitioning.scala:51)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$2(GpuHashPartitioning.scala:82)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$1(GpuHashPartitioning.scala:81)
  E                   	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
  E                   	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
  E                   	at com.nvidia.spark.rapids.GpuHashPartitioning.columnarEval(GpuHashPartitioning.scala:78)
  E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$.$anonfun$prepareBatchShuffleDependency$3(GpuShuffleExchangeExec.scala:203)
  E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.partNextBatch(GpuShuffleExchangeExec.scala:224)
  E                   	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExec$$anon$1.hasNext(GpuShuffleExchangeExec.scala:235)
  E                   	at scala.collection.Iterator.foreach(Iterator.scala:941)
  E                   	at scala.collection.Iterator.foreach$(Iterator.scala:941)
  E                   	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
  E                   	at org.apache.spark.sql.rapids.RapidsCachingWriter.write(RapidsShuffleInternalManagerBase.scala:97)
  E                   	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
  E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
  E                   	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
  E                   	at org.apache.spark.scheduler.Task.run(Task.scala:127)
  E                   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
  E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
  E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
  E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  E                   	... 1 more
  
  /hadoop_disks/disk0/local/usercache/****/appcache/application_1603128018386_7467/container_e87_1603128018386_7467_01_000001/py4j-0.10.9-src.zip/py4j/protocol.py:328: Py4JJavaError
  __________________ test_hash_join_array[Right-Array(String)] ___________________
  
  data_gen = Array(String), join_type = 'Right'
  
      @validate_execs_in_gpu_plan('GpuShuffledHashJoinExec')
      @ignore_order(local=True)
      @pytest.mark.parametrize('data_gen', single_level_array_gens_no_decimal, ids=idfn)
      @pytest.mark.parametrize('join_type', ['Left', 'Right', 'Inner', 'LeftSemi', 'LeftAnti', 'Cross', 'FullOuter'], ids=idfn)
      def test_hash_join_array(data_gen, join_type):
          def do_join(spark):
              left, right = create_nested_df(spark, short_gen, data_gen, 50, 500)
              return left.join(right, left.key == right.r_key, join_type)
  >       assert_gpu_and_cpu_are_equal_collect(do_join, conf=_hash_join_conf)
  
  integration_tests/src/main/python/join_test.py:147: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  integration_tests/src/main/python/asserts.py:359: in assert_gpu_and_cpu_are_equal_collect
      _assert_gpu_and_cpu_are_equal(func, 'COLLECT', conf=conf, is_cpu_first=is_cpu_first)
  integration_tests/src/main/python/asserts.py:340: in _assert_gpu_and_cpu_are_equal
      run_on_gpu()
  integration_tests/src/main/python/asserts.py:334: in run_on_gpu
      from_gpu = with_gpu_session(bring_back, conf=conf)
  integration_tests/src/main/python/spark_session.py:95: in with_gpu_session
      return with_spark_session(func, conf=copy)
  integration_tests/src/main/python/spark_session.py:68: in with_spark_session
      ret = func(_spark)
  integration_tests/src/main/python/asserts.py:179: in <lambda>
      bring_back = lambda spark: limit_func(spark).collect()
  /hadoop_disks/disk0/local/usercache/****/appcache/application_1603128018386_7467/container_e87_1603128018386_7467_01_000001/pyspark.zip/pyspark/sql/dataframe.py:596: in collect
      sock_info = self._jdf.collectToPython()
  /hadoop_disks/disk0/local/usercache/****/appcache/application_1603128018386_7467/container_e87_1603128018386_7467_01_000001/py4j-0.10.9-src.zip/py4j/java_gateway.py:1305: in __call__
      answer, self.gateway_client, self.target_id, self.name)
  /hadoop_disks/disk0/local/usercache/****/appcache/application_1603128018386_7467/container_e87_1603128018386_7467_01_000001/pyspark.zip/pyspark/sql/utils.py:128: in deco
      return f(*a, **kw)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

**Steps/Code to reproduce bug**
Run v0.5.0 integration tests on SPARK-EGX Yarn

**Expected behavior**
Should be PASS

**Environment details (please complete the following information)**
 - Environment location: [YARN]

**Additional context**
Pytests PASS on EMR and Dataproc Yarn cluster

**Comment by tgravescs** [comment]
should decide to either disable test and if people happen to hit it fails or if we want to fall back to cpu

**Comment by tgravescs** [comment]
link to https://github.com/NVIDIA/spark-rapids/issues/2279

**Comment by jlowe** [comment]
This should be fixed by #2319
