### ISSUE TITLE
[DOC] Discuss tuning spark.task.resource.gpu.amount in tuning guide

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#2328]
The tuning guide does not mention how to tune the `spark.task.resource.gpu.amount` setting when Spark is scheduling GPUs.  If this is left at the default of 1 then only 1 task per executor will run, likely wasting CPU cores and leading to suboptimal performance for parts of the query that are not GPU-bound.  For example, setting `spark.rapids.sql.concurrentGpuTasks` to 2 makes no sense if spark.task.resource.gpu.amount is 1, as only 1 task will ever run concurrently in the executor due to the GPU resource limit.

**Comment by jlowe** [comment]
When updating the tuning guide as part of this PR, we should also update existing documentation with examples using `spark.task.resource.gpu.amount=1`, either explicitly or via the default, to mention that this is probably a suboptimal setup and point to the relevant section of the tuning guide.

**Comment by tgravescs** [comment]
note we have some info here about this, but we should tie everything together: https://nvidia.github.io/spark-rapids/Getting-Started/#spark-gpu-scheduling-overview
