### ISSUE TITLE
[FEA] Audit DataWritingCommandExec 

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#233]
**Is your feature request related to a problem? Please describe.**

- Ensure Spark and Rapids plugin version of the exec match functionality.

- Verify Config specific to the operator match.

- Verify API is consistent and fully translated.

- Port relevant tests.

**Comment by razajafri** [comment]
I couldn't find any inconsistencies between us and the spark for the features that we currently support

**Comment by razajafri** [comment]
Follow-on from this audit are #430 #431

**Comment by kuhushukla** [comment]
Can we close this @razajafri ?
