### ISSUE TITLE
[FEA] Audit BroadcastExchangeExec

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#235]
**Is your feature request related to a problem? Please describe.**

- Ensure Spark and Rapids plugin version of the exec match functionality.

- Verify Config specific to the operator match.

- Verify API is consistent and fully translated.

- Port relevant tests.

**Comment by kuhushukla** [comment]
This is completed with no further follow ons CC: @nartal1 , please correct me if I missed anything.

**Comment by nartal1** [comment]
Yes @kuhushukla , It's done and no follow on's for this Exec.
