### ISSUE TITLE
[FEA] CBO: Implement costs for memory access and launching kernels

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2367]
**Is your feature request related to a problem? Please describe.**
In order to make the CBO cost model more realistic, we should add costs for memory access (CPU and GPU) and costs for launching GPU kernels.

**Describe the solution you'd like**
See https://github.com/NVIDIA/spark-rapids/pull/2323#pullrequestreview-654580746

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sameerz** [comment]
@andygrove is this closed by PR 2323?  If not, are there additional tasks that need to be tracked in this issue?
