### ISSUE TITLE
[FEA] Audit BroadcastHashJoinExec 

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#237]
**Is your feature request related to a problem? Please describe.**

- Ensure Spark and Rapids plugin version of the exec match functionality.

- Verify Config specific to the operator match.

- Verify API is consistent and fully translated.

- Port relevant tests.

**Comment by nartal1** [comment]
Ensure Spark and Rapids plugin version of the exec match functionality.
Funtionality matches.

Verify Config specific to the operator match.
Verified.

Verify API is consistent and fully translated.
Verified

Port relevant tests.
Created a PR to add few tests.

**Comment by nartal1** [comment]
PR merged. closing this.
