### ISSUE TITLE
[FEA]  Audit ShuffledHashJoinExec 

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#238]
**Is your feature request related to a problem? Please describe.**

- Ensure Spark and Rapids plugin version of the exec match functionality.

- Verify Config specific to the operator match.

- Verify API is consistent and fully translated.

- Port relevant tests.

**Comment by nartal1** [comment]
Ensure Spark and Rapids plugin version of the exec match functionality.
- Yes, functionality matches

Verify Config specific to the operator match.
- Verified

Verify API is consistent and fully translated.
- Translation required. Expression-> GpuExpression. Created PR https://github.com/NVIDIA/spark-rapids/pull/351

Port relevant tests.
- No new tests needs to be ported. All cases are covered.
