### ISSUE TITLE
[FEA] Audit SortMergeJoinExec

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#239]
**Is your feature request related to a problem? Please describe.**

- Ensure Spark and Rapids plugin version of the exec match functionality.

- Verify Config specific to the operator match.

- Verify API is consistent and fully translated.

- Port relevant tests.

**Comment by nartal1** [comment]
@kuhushukla Since we don't have Gpu version of SMJ and we replace SMJ with GpuShuffledHashJoin in the plan, can we close this?  There is a separate issue to audit ShuffledHashJoin https://github.com/NVIDIA/spark-rapids/issues/238.

**Comment by kuhushukla** [comment]
>Since we don't have Gpu version of SMJ and we replace SMJ with GpuShuffledHashJoin in the plan, can we close this? There is a separate issue to audit ShuffledHashJoin #238.
>
Feel free to close.
