### ISSUE TITLE
[FEA] Option to turn off slack notifications in Jenkins test builds

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2400]
**Is your feature request related to a problem? Please describe.**
Currently our jenkins jobs notify slack on failure, when we are testing new builds it would be nice just to have a check box or something when we launch the job as to whether it notifies slack so we don't put extra messages in slack chennel.

**Comment by tgravescs** [comment]
@GaryShen2008 @NvTimLiu @pxLi do you have any ideas if we can do something like this?

**Comment by GaryShen2008** [comment]
Yes, we have a parameter "MUTE_SLACK", if it's true, there won't be a slack notification if it failed.
If your job doesn't have this parameter, Tim can help to add it.
