### ISSUE TITLE
[BUG] EMR doesn't support cuda11 yet

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2415]
**Describe the bug**
 cudf 0.20 only supports cuda11 and currently EMR doesn't support that. The EMR build is disabled for now.

Once EMR supports it re-enable the build and test.

**Comment by NvTimLiu** [comment]
We installed cuda11 toolkit & cuda11 compat packge in EMR cluster, enabled EMR nightly build and IT.

So we can support cuda11 on EMR now.

Let's wait for tonight's test result.

**Comment by tgravescs** [comment]
emr test fails, but log didn't have an error message that I saw, I rekicked it, but perhaps you can take a look.

**Comment by NvTimLiu** [comment]
Checking

**Comment by NvTimLiu** [comment]
Debugging issue #2448

**Comment by sameerz** [comment]
This is an issue for AWS EMR to provide support in an upcoming EMR release.
