### ISSUE TITLE
[FEA] By default auto tune concurrent tasks and/or target batch size

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2424]
We need to update the documentation on memory management now that we have more out of core algorithms implemented. Those algorithms not perfect, so there will still be exceptions due to algorithms we have not made out of core yet, and because some operations require at least an entire key in memory and there will be data skew. As I was thinking about a simple formula to use so that users could set their target batch size and concurrency I realized that we could automate all of this.  The more I thought about it the more I realized that we should automate it by default to make the plugin simpler to use (an identical config could run well on both an a100 (80GB) and  a T4 (16GB), and it would help force us to get all of the algorithms working out of core to hit this kind of a goal.

Note that concurrently is set when a worker first comes up and the target batch size can be set per query so we could even play some games on a per query basis if we wanted to.  Also because of this it is not super simple to get the target batch size.  Right now most of that happens on the driver as it compiles the query. This would make us change it so that we picked it up more dynamically, with an override from the config.

I think the formula that we want is the following, but I am happy to adjust things. What I care more about is automating more of this.

```
target_batch_size = (rmm_max_pool_size/4)/concurrency
target_batch_size <= 2GB (but we probably want to try for 1GB if we can do it)
concurrency <= number_of_tasks_per_worker
```

I think when we initialize RMM in the worker we would look at the concurrency config. If it is set we compute a suggested target batch size from it.

```
target_batch_size = Math.min((rmm_max_pool_size/4)/concurrency, Integer.MaxValue)
```

We probably also want some warnings if the concurrency is really high so the target batch size is really small, and also a minimum on the target batch size, so we don't shoot ourselves in the foot (100 MiB?)

If concurrency is not set we look at the `target_batch_size`. If it is set we use it, if it is not set we go with a default (1GB??? or maybe 2GB if we want to be conservative on concurrency, but the main thing should be consistency so users are not surprised)

Then we calculate concurrency from the batch size and the pool size.

```
concurrency = (rmm_max_pool_size/4)/target_batch_size
```

If the concurrency is larger than the number of tasks and the batch size is not set we could recalculate the batch size based off of the number of tasks per worker.

The 4 in all of these algorithms comes from join, and we can tune/adjust this if we need to. The idea is that once we have spilling working for all algorithms that keep things in memory in between calls to next, that we need to look at the maximum memory used for a single operation.  That operation is going to be join, barring data skew and the other things I listed before.  For join we need a left hand side (1 batch size), a right hand side (1 batch size), a gather map (hopefully < 1 batch size, but we will see when we get that implemented), and the output batch. We can adjust this larger (because of fragmentation) or smaller (better algorithms).

So some examples to help show this.  If we are working on a 16GB T4 and we keep it at the defaults we would end up with a batch size of 1GB (ideal target size) and a concurrency of 3.  

```
16GiB * .9(rmm max alloc fraction) => 14.4 GiB
floor(14.4GiB/4/1GiB) => 3
```

But if we went with a default batch size of 2GiB, like we have right now the concurrency would be 1.

on an 80GiB a100 the parallelism would be 18 for 1GiB batches and 9 for 2GiB batches.

My biggest concern with this is predictability and consistency. I don't really want this to be magic. I want users to be able to understand what is happening and trust it from one release to the next.

**Comment by mattahrens** [comment]
Closing as won't fix for now
