### ISSUE TITLE
[FEA] Support nested types in CreateNamedStruct

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2436]
We have basic support for CreateNamedStruct but we cannot put nested types into a struct because cudf does not support scalars of nested types. That is slowly changing and we should add in support for Structs, Arrays, and Maps to be children of names structs.

**Comment by sperlingxx** [comment]
Hi @revans2, we have the support of `list_scalar` and `struct_scalar` in libcudf. And I am working on support GpuLiteral on StructType. But for MapType, it seems no easy to support it as children of `GpuCreateNamedStruct`, if I am not wrong.

**Comment by revans2** [comment]
CUDF does not support maps directly. We emulate a map as a list of key, value structs. So if we have a Scalar List that can hold structs we can support scalar maps.

**Comment by revans2** [comment]
I have a patch that I will put up tomorrow. Want to do a bit more testing on it.

**Comment by revans2** [comment]
Also struct literals are not supported just yet in cudf, but it should be very simple to add it in once that work is ready.
