### ISSUE TITLE
[FEA] Support literal arrays in case/when statements

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#2445]
This should also merge the test `test_case_when_array` with the test `test_case_when` .

**Comment by firestarman** [comment]
This is blocked because cudf only supports `column-column` for `copy_if_else`, while the `column-scalar`,  `scalar-column` and `scalar-scalar` are not supported.
Here is the details: https://github.com/rapidsai/cudf/blob/branch-21.06/cpp/src/copying/copy.cu#L238

**Comment by firestarman** [comment]
There should be a WAR in plugin, by expanding the Scalar to Column, then calling into the supported `column-column` API with the expanded column. 

@revans2  @mythrocks Is it acceptable ? Yes this probably requires some small refactor in the `columnarEval` of `GpuCaseWhen`.

**Comment by firestarman** [comment]
cudf does not expand the scalar, so better to wait for the cudf support of the nested type scalar for `copy_if_else`.

**Comment by firestarman** [comment]
Still not support https://github.com/rapidsai/cudf/blob/branch-21.06/cpp/src/copying/copy.cu#L238

**Comment by revans2** [comment]
The dependency I filed in cudf for this is https://github.com/rapidsai/cudf/issues/8361 when it is fixed this can be worked on.
