### ISSUE TITLE
[FEA] Avoid introducing GpuBroadcastToCpu with Spark 3.0.3, 3.1.2, and 3.2.0

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2450]
**Is your feature request related to a problem? Please describe.**
The fix for [SPARK-35093](https://issues.apache.org/jira/browse/SPARK-35093) has now been merged and will be part of Spark 3.0.3, 3.1.2, and 3.2.0. When running against these versions of Spark, we should no longer need the `GpuBroadcastToCpu` hack.

**Describe the solution you'd like**
Write tests and possibly update shim layers, if required, to confirm that we get the correct query plan.

**Describe alternatives you've considered**
None

**Additional context**
We saw the original issue with NDS q14a with AQE on and decimals disabled.

**Comment by jlowe** [comment]
@andygrove Is this still relevant after #4440?

**Comment by andygrove** [comment]
> @andygrove Is this still relevant after #4440?

No, I don't believe it is.
