### ISSUE TITLE
[BUG] 0.5GA fails on Dataproc 2.0 using 2.0-debian10 image.

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#2454]
**Describe the bug**

0.5GA fails on Dataproc 2.0 using 2.0-debian10 image.

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

```
export CLUSTER_NAME=testdebian
export GCS_BUCKET=<BUCKET>
export REGION=europe-west4
export ZONE=europe-west4-b
export NUM_GPUS=1
export NUM_WORKERS=2

gcloud dataproc clusters create $CLUSTER_NAME  \
    --region $REGION \
    --zone $ZONE \
    --image-version=2.0-debian10 \
    --master-machine-type n1-standard-4 \
    --master-boot-disk-size 200 \
    --num-workers $NUM_WORKERS \
    --worker-accelerator type=nvidia-tesla-t4,count=$NUM_GPUS \
    --worker-machine-type n1-standard-16 \
    --num-worker-local-ssds 1 \
    --initialization-actions gs://${GCS_BUCKET}/install_gpu_driver.sh,gs://${GCS_BUCKET}/rapids.sh \
    --optional-components=JUPYTER,ZEPPELIN \
    --metadata gpu-driver-provider="NVIDIA",rapids-runtime="SPARK" \
    --bucket $GCS_BUCKET \
    --subnet=default \
    --enable-component-gateway 
```

Note: the  `gpu/install_gpu_driver.sh` and `rapids/rapids.sh` you can get from the latest master branch of 
https://github.com/GoogleCloudDataproc/initialization-actions

Then just logon spark-shell on master node, and it will error out:
```
gcloud compute ssh $CLUSTER_NAME-m --project=rapids-spark --zone=$ZONE
spark-shell
```

We can get the error from the yarn log:
```
yarn logs -applicationId application_xxxx
```

Sample stacktrace from yarn log is:
```
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: /mnt/1/hadoop/yarn/nm-local-dir/usercache/xxx/appcache/application_1111111111_0001/container_e01_11111111111_0001_01_000001/tmp/nvcomp2309604893014216427.so: libcudart.so.11.0: cannot open shared object file: No such file or directory
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ai.rapids.cudf.NativeDepsLoader.loadNativeDeps(NativeDepsLoader.java:167)
	... 34 more
Caused by: java.lang.UnsatisfiedLinkError: /mnt/1/hadoop/yarn/nm-local-dir/usercache/xxx/appcache/application_1111111111_0001/container_e01_1111111111_0001_01_000001/tmp/nvcomp2309604893014216427.so: libcudart.so.11.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at ai.rapids.cudf.NativeDepsLoader.loadDep(NativeDepsLoader.java:184)
	at ai.rapids.cudf.NativeDepsLoader.loadDep(NativeDepsLoader.java:198)
	at ai.rapids.cudf.NativeDepsLoader.lambda$loadNativeDeps$1(NativeDepsLoader.java:161)
	... 5 more
```

**Expected behavior**

It should work fine even though debian10 is not in our supported OS list in the download page.
I tested 0.4.1GA on the exactly the same debian10 image, and it works fine.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

Dataproc 2.0 with debian 10 image.

**Additional context**

**Comment by viadea** [comment]
To troubleshoot, i can find this .so on the env:
```
# find . -name libcudart.so.11.0
./cuda-11.0/targets/x86_64-linux/lib/libcudart.so.11.0
```

**Comment by jlowe** [comment]
Couple of questions:
- Are both 0.4.1 and 0.5 using a cudf built for CUDA 11?
- Does 0.5 work if you use a cudf 0.19 built for 10.2?

The docs at https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/gpu imply that a metadata parameter needs to be specified if you want any CUDA version other than 10.1 or 10.2, but I don't see that being specified via something like `--metadata cuda-version=11.0`.

It seems like the ld-config cache wasn't updated in the image after the CUDA 11 install so the runtime library could be found.  I don't know offhand why cudf 0.18.1 for CUDA 11 could find the CUDA runtime library but cudf 0.19 for CUDA 11 cannot on the same system.

**Comment by viadea** [comment]
@jlowe I just did another around of test to prove the theory/doubt.
Firstly I used the 0.5GA init scripts to start a dataproc 2.0 debian env, and it fails with above errors.
Then I only changed the jars back to 0.4.1 on the SAME cluster, then it works fine.

The only thing I did is to:
```
sudo su - root
cd /usr/lib/spark/jars
mv cudf-0.19.2-cuda11.jar /tmp/cudf-0.19.2-cuda11.jar.bak
mv rapids-4-spark_2.12-0.5.0.jar /tmp/rapids-4-spark_2.12-0.5.0.jar.bak
wget https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark_2.12/0.4.1/rapids-4-spark_2.12-0.4.1.jar
wget https://repo1.maven.org/maven2/ai/rapids/cudf/0.18.1/cudf-0.18.1-cuda11.jar
```

So basically I think it is triggered by the jar.

**Comment by viadea** [comment]
@jlowe  to answer your questions:

> Couple of questions:
> 
>     * Are both 0.4.1 and 0.5 using a cudf built for CUDA 11?
> 

Answer: Correct. By default, it will install CUDA 11.0 on both tests. I even swapped jars on the same cluster to prove the only difference is the 2 jars.

>     * Does 0.5 work if you use a cudf 0.19 built for 10.2?
> 

I have not tried, but if you want, i can try to modify the init script to use 10.2 to have a try.

**Comment by viadea** [comment]
Thanks a lot @jlowe for the explanation.
We finally found the issue and root cause.

Basically in the init script of GCP, there is no `ldconfig` after GPU driver installation.
It caused that:
```
/tmp/cudf19/amd64/Linux# ldd * |grep -i cudart
	libcudart.so.11.0 => /usr/local/cuda/lib64/libcudart.so.11.0 (0x00007f5d482d1000)
	libcudart.so.11.0 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0 (0x00007f0e5c586000)
	libcudart.so.11.0 => not found
```

The same thing happened for 0.18 cudf jar, but since 0.18 cudf jar has many more .so files so the issue could be hidden there.

The fix is to add `ldconfig` after GPU driver installation and it works fine for me after the fix.
So https://github.com/GoogleCloudDataproc/initialization-actions/pull/909 is the fix.

**Comment by viadea** [comment]
Let me close this bug since the fix is found.
