### ISSUE TITLE
[DOC] Split UCX docker examples into dockerfiles and add CentOS example

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#2480]
We have some Dockerfile examples here: https://github.com/NVIDIA/spark-rapids/blob/branch-21.06/docs/additional-functionality/rapids-shuffle.md, in order to get a functional docker container that can be used for executors to run with UCX. The examples right now are limited to Ubuntu 18.04, this is to add a CentOS equivalent.

Main thing right now is getting rdma-core to build for CentOS, should be easy after that.

**Comment by sameerz** [comment]
@abellina will this document update be targeted for 21.06 or 21.08?
