### ISSUE TITLE
[BUG] scaladoc warning  GpuParquetScan.scala:727 "discarding unmoored doc comment"

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#2495]
**Describe the bug***
local build displays a warning 
```
<LOCAL_REPO_PATH>/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:727: warning: discarding unmoored doc comment
    /**
    ^
```

**Steps/Code to reproduce bug**
```
mvn clean scala:doc -pl sql-plugin
```

**Expected behavior**
build should produce as few distracting messages as possible

**Environment details (please complete the following information)**
- local dev environment

**Additional context**
N/A

**Comment by jlowe** [comment]
We ran into a similar issue before.  It looks like scaladoc has issues with nested functions like this, and we ended up moving the nested function up a level to a peer, private method to resolve the issue.
