### ISSUE TITLE
[FEA] Print out the GPU mode in the logs of the integration tests. 

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#2541]
**Is your feature request related to a problem? Please describe.**
`cudf_udf` tests will run multiple processes on a single GPU, requiring the GPU mode to be `default`. Otherwise the tests will failed, complaining the exception as below.
```Bash
  Caused by: java.io.EOFException
E                   	at java.io.DataInputStream.readInt(DataInputStream.java:392)
  ...
```
Now the `cudf_udf` tests are failing due to the same exception (tracking issue https://github.com/NVIDIA/spark-rapids/issues/2521), it will be good to know whether the failures are caused by the wrong GPU mode.

There is also an issue in cudf (https://github.com/rapidsai/cudf/issues/6363) to ask for the support of querying GPU mode, then the mode things can be handled in code.

**Comment by NvTimLiu** [comment]
We already have 'nvidia-smi' in Integration tests scripts:
https://github.com/NVIDIA/spark-rapids/blob/branch-21.06/jenkins/spark-tests.sh#L20
