### ISSUE TITLE
[FEA] Implement KnownNotNull on the GPU

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#2562]
**Is your feature request related to a problem? Please describe.**
Implement KnownNotNull on GPU

**Describe the solution you'd like**
When KnownNotNull is part of the plan, the plan stays on the GPU

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by firestarman** [comment]
@sameerz  May I know the case/sql for this `KnownNotNull ` ? Since I need a test case for this expression.

**Comment by firestarman** [comment]
I tried several cases and got this expression in logical plan, but it will be removed after optimization.
I will check the the native UDF.
