### ISSUE TITLE
[FEA] support collect_list and collect_set as groupby aggregation

### ISSUE THREAD

**Issue by sperlingxx** [NVIDIA/spark-rapids#2615]
**Is your feature request related to a problem? Please describe.**
The issue is a part of #2062, which is depended on cuDF issues: [Support MERGE_LISTS and MERGE_SETS for groupby::aggregate](https://github.com/rapidsai/cudf/issues/7839) and [provide Java bindings for aggregations: MERGE_LISTS and MERGE_SETS](https://github.com/rapidsai/cudf/issues/8445).

**Comment by sameerz** [comment]
Moving to 21.10 based on work in PR #2804
