### ISSUE TITLE
[BUG] No Job Found. Exiting.

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2652]
I was following the instructions at 

https://github.com/NVIDIA/spark-rapids/tree/branch-21.08/tools

It took a bit to be able to find where the event logs are stored (It was not obvious and took a but of digging), but when I had found them at that point everything in the directory is called something like `app-<timestamp>-number`. I had no idea what any of these apps were so I decided to use all of them

```
spark-submit --driver-memory 5g --class com.nvidia.spark.rapids.tool.qualification.QualificationMain ./tools/target/rapids-4-spark-tools_2.12-21.08.0-SNAPSHOT.jar spark-eventlog/*
```

And the logging is far from clear what happened or why there was an error.

```
21/06/09 12:51:51 INFO ApplicationInfo: Parsing Event Log File: .../spark-eventlog/app-20201029093814-0001
21/06/09 12:51:52 INFO ApplicationInfo: Total number of events parsed: 15
21/06/09 12:51:53 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('spark-warehouse').
21/06/09 12:51:53 INFO SharedState: Warehouse path is 'spark-warehouse'.
21/06/09 12:51:53 INFO CodeGenerator: Code generated in 153.741923 ms
21/06/09 12:51:54 INFO ApplicationInfo: No SQL Execution Found. Skipping generating SQL Execution DataFrame.
21/06/09 12:51:54 ERROR ApplicationInfo: No Job Found. Exiting.
```

From what I can tell `app-20201029093814-0001` didn't have any SQL execution in it. OK so skip it or print that out, but go on and process everything else that I passed in.  Don't exit.

**Comment by tgravescs** [comment]
I'm guessing the * at the end only expanded to the single event log, we should verify though.

Leave off the start to read all files in a directory or specify them individually.

**Comment by tgravescs** [comment]
>> It took a bit to be able to find where the event logs are stored (It was not obvious and took a but of digging),

Can you clarify this?  you didn't know where spark put them on just any application run?  If so we should perhaps document the spark configs used or point to spark docs

**Comment by revans2** [comment]
It would be good to point to the spark docs/etc. I had to look up in my config to again to find the directory. Not the end of the world, but it was not simple.

> I'm guessing the * at the end only expanded to the single event log, we should verify though.
>
> Leave off the star to read all files in a directory or specify them individually.

No it is expending out lots of files. The first file just happens to not have anything in it that this wants.  If I delete that file or say pick only files for 2021, then it will process a few files and then die with the same error.
