### ISSUE TITLE
[BUG] --help at the end does not print out help for tools

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2654]
I was following the instructions at https://github.com/NVIDIA/spark-rapids/tree/branch-21.08/tools and I wanted to get a help message to see what options there were, so I appended `--help` to the end of my current command.

```
spark-submit --driver-memory 5g --class com.nvidia.spark.rapids.tool.qualification.QualificationMain ./tools/target/rapids-4-spark-tools_2.12-21.08.0-SNAPSHOT.jar spark-eventlog/app-20210416112924-0000 --help
```
instead of getting a help message I got 

```
Exception in thread "main" java.io.FileNotFoundException: File --help does not exist
```

This is not a great user experience.

**Comment by tgravescs** [comment]
yeah it currently has to go before the eventlog parameter, agree could be better
