### ISSUE TITLE
[FEA] add file size check for pre-merge CI run

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#2674]
Do not allow large files (like > 50MiB) get merged to upstream branch.

Add check in pre-merge pipeline.

```bash
if (( $(git ls-tree --full-tree -r -l HEAD | sort -k 4 -n -r | head -1 | awk '{print $4}') > 52428800 )); then exit 1; fi
```

**Comment by revans2** [comment]
I am more than a little upset that we even have a 40 MB file in our repo. It seems ridiculous and we have 2 of them. I guess 50MB is an okay cutoff, but I really would have preferred to see something closer to 1.5MiB.  Could we explicitly allow the existing files that are over 1.5MiB and then set a limit of 1.5 MiB for anything new?

**Comment by pxLi** [comment]
sure, I will add the check in pre-merge CI using pre-commit tool, and make the default cutoff as 1.5MiB
