### ISSUE TITLE
[FEA] integration test framework should detect unintentionally failed executors

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#2698]
There has been a couple of instances I have seen where executors fail in our integration tests. For example: https://github.com/NVIDIA/spark-rapids/issues/1520 and https://github.com/NVIDIA/spark-rapids/issues/2477. 

https://github.com/NVIDIA/spark-rapids/issues/2477 was a test failure that was caused by an executor leaving the cluster. This would be the same for any test that performs partition-local operations (in this case it was sorting within partitions), and then expect all of the rows to match between the CPU and GPU, as Spark uses the number of cores available (# executors active * # cores/executor) to determine how many map partitions to use.

This issue is to add check if we expect a static number of executors, and we haven't explicitly killed an executor, during integration tests. This would help us narrow down issues that are causing executors to go away like memory or potentially the heartbeat failures seen in https://github.com/NVIDIA/spark-rapids/issues/1520.

**Comment by jlowe** [comment]
Seems like we would want to run with dynamic allocation explicitly disabled and task max attempts == 1 for most test setups, that way the test should fail if a task/executor fails.

**Comment by abellina** [comment]
We can turn off dynamic allocation, but we normally (I think exclusively) run without it, because you'd need the external shuffle service for it to be enabled.

On max task failures, yes that can be enabled. And it would mean our tests should fail quickly and likely not mistakenly succeed on a retry when we don't expect (i.e. if we have an XFAIL it is probably coded so that it fails each time). This seems like a good change @jlowe and it should help uncover flaky tests. In this case, we should see a prior failure helping us uncover the real issue.

**Comment by tgravescs** [comment]
dynamic allocation could be on in different CSPs or environments we run in, so if we are relying on it we should be explicit.
