### ISSUE TITLE
[BUG] dot file generation can go over the limits of dot

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2710]
**Describe the bug**
I recently hit a bug when trying to build a dot file generated by the tool for NDS query 24.

```
$ dot -Tsvg -O ./profile_output_171/*.dot
Error: ./profile_output_171/app-20210528152635-0280-query-24.dot: syntax error in line 3 scanning a quoted string (missing endquote? longer than 16384?)
String starting:"\lApplication: app-20210528152635-0280\lQuery: 24\l\l== Parsed Logical Plan ==\
```

I had to go in and delete the extra info from the label for the digraph.

It might be nice to detect this and avoid it, or even better come up with a different way to display the plans that would not violate this limit.

**Comment by gerashegalov** [comment]
thanks for finding this @revans2 . Looks like we are hitting a  compile-time limit https://gitlab.com/graphviz/graphviz/-/issues/796.

A few options I see
1. Truncate
1. Have a label that simply identifies application and query and defers to `Plan for SQL ID : $sqlId` in the --print-plans output, can even provide a pre-computed hyperlink in the HTML formatted label
1.  Hack multiple labels via subgraphs https://stackoverflow.com/questions/55735759/how-to-add-top-and-bottom-labels-for-dot-graph

Option 2 looks most uniform and scalable to me.

**Comment by tgravescs** [comment]
easiest seems like both 1 and 2.  truncate and put note to see full plan run with --print-plans option
