### ISSUE TITLE
[BUG] profiling tool does not error or warn if incompatible options are given

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2713]
I tried to do a compare and generate dot in the same command. But no dot files were generated. Looking at the code they are incompatible with one another. It really would be great to either get an error or warning early on if that happens. Or just fix it so they are compatible with each other.

**Comment by tgravescs** [comment]
ran this and its actually fixed now, at least it does generate dot files in compare mode as well.  It does also print a message saying graph and timeline don't compare apps it just generates them. So closing this.
