### ISSUE TITLE
Add ParquetCachedBatchSerializer test to pre-merge

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2714]
Currently the pre-merge doesn't run PCBS tests as a part of pre-merge which allows devs to merge features without fully testing the plugin

**Comment by jlowe** [comment]
Note that there are some tests that are run, for example the tests in Spark310ParquetWriterSuite.  I assume this is requesting the tests in `cache_test` to be run.

**Comment by razajafri** [comment]
Yes, this ticket is calling for running `cache_test` before we merge PRs

**Comment by tgravescs** [comment]
link https://github.com/NVIDIA/spark-rapids/issues/2731 .  If you have a reason, like it is regularly getting broken because its not run on premerge let me know, otherwise I say we close this as the premerge is to long as is

**Comment by razajafri** [comment]
@tgravescs yeah that's a very good point. I think the nightly build is good enough
