### ISSUE TITLE
Premerge build takes too long (3 hours)

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2731]
**Describe the bug**
At the end of 21.06 the premerge build was taking around 3 hours. This is too long to move quickly, especially if you have prs depending on other prs.    

I know part of the time is because we run the test on a bunch of various spark versions.

We should investigate to see if there are ways to make this run in a more timely manner.

Perhaps we move more spark versions to just run nightly, perhaps there is stuff we can parallelize more, etc..

**Comment by GaryShen2008** [comment]
Is it possible to skip the xfail cases to make it faster?

**Comment by tgravescs** [comment]
pytest has the skip functionality, we could go through and see if we can convert any to that, but we don't want to blanket do that,  some we want to explicitly show up as xfail.

**Comment by revans2** [comment]
I downloaded a recent log file and pulled out what maven reports for timing, and then summed things up.

| stage | time | percent total|
|--------|--------|-----------------|
|rapids-4-spark-api-validation | 00:00:19| 0.2%|
|rapids-4-spark-integration-tests_2.12| **01:07:22**| **41.7%**|
|rapids-4-spark-tests-next-spark_2.12| 00:01:17| 0.8%|
|RAPIDS Accelerator for Apache Spark Distribution| 00:00:16|0.2%|
|RAPIDS Accelerator for Apache Spark Root Project| 00:00:23|0.2%|
|RAPIDS Accelerator for Apache Spark Scala UDF Plugin|  00:04:13| 2.6%|
|RAPIDS Accelerator for Apache Spark Shuffle Plugin| 00:00:24|0.2%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Shim Aggregator| 00:00:06|0.1%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Shims| 00:00:07|0.1%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.1 EMR Shim| 00:00:21|0.2%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.1 Shim| 00:00:34|0.4%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.2 Shim| 00:00:22|0.2%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.0.3 Shim| 00:00:45|0.5%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.1 Cloudera Shim| 00:01:10|0.7%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.1 Shim| 00:00:51|0.5%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.2 Shim| 00:00:23|0.2%|
|RAPIDS Accelerator for Apache Spark SQL Plugin Spark 3.1.3 Shim| 00:00:51|0.5%|
|RAPIDS Accelerator for Apache Spark SQL Plugin| 00:02:30|1.5%|
|RAPIDS Accelerator for Apache Spark Tests| **00:48:48**|**30.2%**|
|RAPIDS Accelerator for Apache Spark tools| **00:24:13**|**15.0%**|
|RAPIDS Accelerator for Apache Spark UDF Examples|00:00:15|0.2%|
|Everything else|00:06:08|3.8%|

The total run time of this job was 02:41:38

From this it is clear that the python tests are a lot of the time, but we have already optimized them a lot.  The rest of the issues appear to be related to running things for multiple different versions of Spark. Tools appears to be a lot of this and I am not sure how much value there is in running those tests multiple times against different versions of Spark. Not even sure if it is running against multiple versions of Spark or if it is just running it against a single version of Spark.

**Comment by tgravescs** [comment]
The tools don't need to be run against other versions of Spark, we have integration tests that run nightly for that.

the tool tests take 2 minutes for me on my local box.   I guess if they get run for every spark version 2*5 (I thought we ran on 3.0.1, 3.0.3, 3.0.4, 3.1.2, 3.1.3)  is 10 minutes.  
Are these boxes that underpowered that it takes more then double?

I'm going to put up a PR just to remove some of the spark unit tests runs. We aren't making that much change to them, if we start seeing problems where they aren't caught then we can consider adding them back.  If objections comment here or on PR when I open it.

**Comment by pxLi** [comment]
We will also parallelly run UT (for spark minor versions 3.0.x, 3.1.x, 3.2.x ....) and IT in separate pods to speed up the whole process after we have 4 more GPU resources ready (should be available next week). @zhanga5 will help w/ this one later

**Comment by zhanga5** [comment]
I have been tried quick testing IT and UT from separate pods in parallel. The overall duration can be decreased to ~1 hr 20 mins including 4 Spark versions UT. The bottle-neck is IT that would take ~1 hr 18 mins.

The console log was messed up because of parallel build, however. This would break current log upload for external contributors and I'm working with Blossom to resolve it at present.

**Comment by tgravescs** [comment]
oh of my recent prs took 1 hour and 47 minutes after the above was merged and I think it was taking 2 hours so a little improvement but not as much as I hoped.  https://github.com/NVIDIA/spark-rapids/pull/3068

**Comment by revans2** [comment]
I think the only way to make it go any faster at this point is to split up the parallelism differently. Right now we have the testing split between run everything on the default Spark version, and run a smaller set of things on several other Spark versions.  This works okay, but the full set of python tests is taking the 1 hour and 47 min, while the others are taking about 1 hour.

Building the entire plugin from scratch without any tests takes about 4 - 7 mins depending on how fast of a network connection there is. I would love to see us look at trying to split things up into smaller portions, possibly one task for each version of Spark to run just the basic tests, and another set of tasks to run subsets of the python integration tests.

**Comment by zhanga5** [comment]
I will take a look how to split existed testings into smaller portions and execute them in parallel with smaller granularity. Any suggestions about this are welcome!

**Comment by revans2** [comment]
There are several options that we could use for the python tests.  

  1. We currently have a `@qarun` tag that we could use to disable the qa tests in a normal run. We could extend this concept and manually tag tests to be in specific groups.
  2. We could do something based off of the name of the file. We can look at the files under `./integration_tests/src/main/python/*_test.py` and split them up into N sets then use `pytest.TEST_TAGS` in maven (or probably more likely use -k directly in the test script) to pass one of those lists into the test framework to run.
  3. We could try and use another py.test plugin like https://pypi.org/project/pytest-split-tests/

The last one looks like the simplest option if it works out of the box with pytest.xdist.

**Comment by revans2** [comment]
There are still pending TODOs in the code and 3 out of the 4 test runs for the scala tests were commented out.  This is not done.

**Comment by pxLi** [comment]
> There are still pending TODOs in the code 

we have https://github.com/NVIDIA/spark-rapids/issues/3247 to tracking the TODO as another topic (Jenkinsfile compatibility)

> 3 out of the 4 test runs for the scala tests were commented out. This is not done.

I think @zhanga5 commented there in [thread](https://github.com/NVIDIA/spark-rapids/pull/3241#discussion_r690825925), there was https://github.com/NVIDIA/spark-rapids/pull/2833 to reduced UTs in pre-merge to save time since we have nightly pipelines to cover all shims UTs. If required, we could add them back which would increase around 30-40 mins for pre-merge CI

**Comment by revans2** [comment]
Yes he commented on it, someone resolved it (not me), but I never approved the PR.  That is the part I am upset/concerned about. I didn't think we had come to a conclusion on this and I come in the next day and it is merged in. I understand that we want to move fast on some of these things, and I don't think it is a blocker. But I still want to be sure that @tgravescs and @jlowe agree that for the pre-merge build that we will only run java tests on the first and last versions of Spark.

**Comment by tgravescs** [comment]
so what is the expected time at now?  I see times from an 1h 20min up to 2h 20 min on the last few premerge runs.

personally I'm ok leaving them out, it would be nice to run on the latest versions since that is where mostly likely things might be broken but as long as we aren't seeing to many issues I'm ok with leaving for nightly.

**Comment by revans2** [comment]
Sounds like the change is fine. I guess I just have to not be polite and if I am not done with a PR actually request changes instead of just comment.

**Comment by pxLi** [comment]
> Yes he commented on it, someone resolved it (not me), but I never approved the PR. That is the part I am upset/concerned about. I didn't think we had come to a conclusion on this and I come in the next day and it is merged in. I understand that we want to move fast on some of these things, and I don't think it is a blocker. But I still want to be sure that @tgravescs and @jlowe agree that for the pre-merge build that we will only run java tests on the first and last versions of Spark.

> Sounds like the change is fine. I guess I just have to not be polite and if I am not done with a PR actually request changes instead of just comment.

@revans2 Sorry, I think @zhanga5 resolved the thread by accident, looks like `git --amend and forced push the commit` and the thread became out of date and resolved. Yeah, we should wait for more insights before the merge, thanks for being polite and please help mark review as `request change` to help us know that one comment is a blocker as we are in different timezones, thanks!

> so what is the expected time at now? I see times from an 1h 20min up to 2h 20 min on the last few premerge runs.

@tgravescs That was due to some ephemeral URM network bandwidth issue which increased the artifacts download from ~10 mins to 1 hours+

**Comment by GaryShen2008** [comment]
Let's not use "git commit --amend" for any PR which is reviewing. For any comment, we should reply and wait for the commenter to verify and mark it resolved.

**Comment by revans2** [comment]
In general we don't want to ever force push to a commit that is being reviewed because of issues like this.
