### ISSUE TITLE
[FEA] Audit 3.2.0 - [SPARK-34906] Refactor TreeNode's children handling methods into specialized traits

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#2734]
**Is your feature request related to a problem? Please describe.**
Spark has refactored the code and we had copied the code(aggregations such as GpuAverage, GpuFirst and so on). I am not sure if we need to refactor or if it's okay to keep it as it is in this code. Filed the issue to get others' perspective on this.

https://github.com/apache/spark/commit/bd0990e
https://issues.apache.org/jira/browse/SPARK-34906

**Comment by gerashegalov** [comment]
In my branch `reshim-source-deps-classifier-and-parallel-classloader-spark320-2`,  this is resolved by introducing per-shim base traits:

- https://github.com/gerashegalov/spark-rapids/blob/reshim-source-deps-classifier-and-parallel-classloader-spark320-2/shims/spark301/src/main/scala/com/nvidia/spark/rapids/shims/TreeNode.scala
- https://github.com/gerashegalov/spark-rapids/blob/reshim-source-deps-classifier-and-parallel-classloader-spark320-2/shims/spark320/src/main/scala/com/nvidia/spark/rapids/shims/TreeNode.scala
- https://github.com/gerashegalov/spark-rapids/blob/reshim-source-deps-classifier-and-parallel-classloader-spark320-2/shims/spark311/src/main/scala/com/nvidia/spark/rapids/shims/TreeNode.scala
