### ISSUE TITLE
[FEA] Audit 3.2.0 - [SPARK-34862] Support nested column in ORC vectorized reader

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#2737]
**Is your feature request related to a problem? Please describe.**
This PR has improved performance in Apache Spark. I wasn't sure if this is needed in spark-rapids code. Created an issue to get opinions from others.

https://github.com/apache/spark/commit/1fc66f6
https://issues.apache.org/jira/browse/SPARK-34862

**Comment by sameerz** [comment]
This is CPU specific, we do not think there is anything to be done on the GPU side.
