### ISSUE TITLE
[FEA]Audit 3.2.0 - [SPARK-34856][SQL] ANSI mode: Allow casting complex types as string type

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#2738]
**Is your feature request related to a problem? Please describe.**
Allowing casting complex types as string type in ANSI mode was added in this PR. We should look into if we can add the same.

https://github.com/apache/spark/commit/0515f49
https://issues.apache.org/jira/browse/SPARK-34856

**Comment by firestarman** [comment]
I believed GPU does not have this issue, since I tried the test as below.
```

scala>  sql("select array(1, 2, 2)").show(false)
22/03/16 12:18:43 WARN GpuOverrides:
*Exec <ProjectExec> will run on GPU
  *Expression <Alias> [1, 2, 2] AS array(1, 2, 2)#3 will run on GPU
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec

+--------------+
|array(1, 2, 2)|
+--------------+
|[1, 2, 2]     |
+--------------+

```

**Comment by revans2** [comment]
Sounds good. @jlowe do you think it is worth adding in a test to verify that this works, or should we just rely on the non-ANSI tests?

**Comment by revans2** [comment]
It is the same. Spark just disabled it to match ANSI, and then apparently decided to switch it back.
