### ISSUE TITLE
[FEA]Audit 3.2.0 -  Read parquet unsigned types that stored as int32 physical type in parquet

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#2741]
**Is your feature request related to a problem? Please describe.**
This seems to be enhancement where support is added to read UINT_8 as ShortType, UINT_16 as IntegerType, UINT_32 as LongType to fit their range. Filed this issue to get opinion if there is any advantage in persuing similar to this for unsigned types.

https://github.com/apache/spark/commit/8c6748f
https://github.com/apache/spark/commit/820b465 - UINT_64

https://issues.apache.org/jira/browse/SPARK-34817

**Comment by res-life** [comment]
Background

Java does not have unsigned int primitives, such as uint_8, uint_16, uint_32 ......, so java developers often use larger int types to store these unsigned types.
The previous Spark just throws an exception when reading unsigned types: Parquet type not supported: INT32 (UINT_8).
This PR fixed this exception by casting to wider int: unit8 -> int16, uint16 -> int32, uint32->int64, uint64->decimal(20, 0), but spark-rapids now throw the exception like Type conversion is not allowed ColumnVector{type=UINT8} to ShortType.

Solution
I suggest adding upward casts for these types by using ColumnView.cast.

**Comment by res-life** [comment]
Now Spark CPU version reads UNIT8 as short int, I think Spark GPU version should align this.

**Comment by revans2** [comment]
Yes. I think we can fit this into the code that is used to downcast wider decimal types to the correct size. It also handles some aspects of schema evolution.

https://github.com/NVIDIA/spark-rapids/blob/9691bcee77e619aa71055a61a389fba41b17d207/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala#L609-L657

**Comment by res-life** [comment]
@revans2  UINT64 will be cast to Decimal(20, 0) which CUDF actually does not support.
Can we reopen this issue for trace after merged of uint8, uint16, uint32 support.

**Comment by revans2** [comment]
I would have us file a follow on issue for UINT64 instead. `Decimal(20, 0)` is not supported by CUDF or the plugin, so we will fall back to the CPU in that case. So this bug/feature will be as complete as it can be under the current code.

**Comment by res-life** [comment]
Will fall back to CPU when reading UINT64 and filed a new issue #3475.
