### ISSUE TITLE
[BUG]test_single_nested_sort_in_part integration test failure 21.08

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2746]
src/main/python/sort_test.py::test_single_nested_sort_in_part[STABLE-Column<b'a DESC NULLS LAST'>1-Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Null])]

test failed as part of integration tests. 

The cpu and gpu values returned were different

**Comment by jlowe** [comment]
Looks somewhat similar to #2477, although this is nested sort while the other is not. cc: @abellina

**Comment by abellina** [comment]
We can set `num_slices` for this test like we did for the other test. The main issue is an executor is dying, and the integration test that failed was using spark-3.0.2, which I've seen crash several times on the `isZero` issue from `CollectionAccumulator`. I am not able to access the executor logs right now, but I'll move forward with the `num_slices` pr.

**Comment by sameerz** [comment]
@abellina closing this, will reopen if we see another failure.
