### ISSUE TITLE
Add support to generate nested data_gen in integration tests

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2759]
We need a way to quickly generate nested data. Right now we should keep it limited to 3-level nesting simply because if nesting gets too deep, the data generation could potentially take a very long time.

**Comment by revans2** [comment]
What exactly did you have in mind?  It is fairly simple to do something like

```
ArrayGen(ArraGen(ArraGen(StringGen)))
```

We also have some pre-built options like `nested_array_gens_sample` that can be extended with deeper options.

**Comment by razajafri** [comment]
Yeah this is very straight forward and fairly simple but it gets complicated when you have structs nested within structs. 
e.g. 
```
StructGen([['child0', 
   StructGen([['child0', 
      StructGen([['child0', 
         StructGen([['child0', 
            StructGen([['child0', DecimalGen(7, 2)]])]])]])]])], ['child1', IntegerGen()]], nullable=False)
```
The problem gets more cumbersome if you want each level to have a different name to circumvent the [SPARK-35108](https://issues.apache.org/jira/browse/SPARK-35108)

**Comment by revans2** [comment]
That issue happens in the result of a computation.  (Spark result going back to Python) Not in the data that is generated.  What we need then is an API that can "fix" a nested dataframe so we don't run into those problems.  Not one that changes how the data is generated.
