### ISSUE TITLE
A deeper look into SPARK-35585

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2763]
https://github.com/apache/spark/commit/daf9d198dc changed some of the optimization rules in AQE.

I don't think that they will impact us.  They deal with propagating an  empty relation through project/filter commands.  But I would like an AQE expert to take a look at it.

**Comment by sameerz** [comment]
@andygrove can you take a look at this and see whether it impacts us?

**Comment by jlowe** [comment]
If there ends up being anything to do here for us, then there may be similar changes needed for the same type of change related to empty relations in joins, see https://github.com/apache/spark/commit/631077db08

**Comment by andygrove** [comment]
I did investigate this and I also do not think that this impacts us but it would be nice to have a test just to be sure. There is a test in Spark's AdaptiveQuerySuite that we can adapt (`test("SPARK-35585: Support propagate empty relation through project/filter")`).
