### ISSUE TITLE
Check if casting needed for Set and InSet after SPARK-35316

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2764]
https://github.com/apache/spark/commit/cfde117c6f

allows set and inset to have types that are slightly different for the needle and the haystack.  They eliminate the cast in cases where java can implicitly cast the values. This allows for predicate push down in some cases where it could not work before, but I don't think that cudf is that smart, so we might need to fix it up ourselves in some cases.  But we need to test it.

**Comment by sperlingxx** [comment]
I would like to pick this task, if no others are working on/going to work on  it.
