### ISSUE TITLE
[BUG] HashAggregateSuite failure when AQE is enabled

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#277]
**Describe the bug**
HashAggregateSuite has two failing test cases (`SortAggregateExec is translated correctly ENABLE_HASH_OPTIMIZE_SORT=true` and `SortAggregateExec is translated correctly ENABLE_HASH_OPTIMIZE_SORT=false`) when AQE is enabled

**Steps/Code to reproduce bug**
These tests are currently not run when AQE is enabled. Simply remove the conditional code in these tests that disables it.

**Expected behavior**
The test should execute without error and produce the correct result.

**Environment details (please complete the following information)**
Running `mvn clean verify` on desktop (Ubuntu).

**Additional context**
N/A

**Comment by nartal1** [comment]
This was resolved in https://github.com/NVIDIA/spark-rapids/pull/469
