### ISSUE TITLE
[DOC]Qualification and Profiling tools metrics explanations

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#2771]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/NVIDIA/spark-rapids/blob/branch-21.08/tools/README.md

**Describe the problems or issues found in the documentation**
I think it would be nice if all "Analysis metrics" have a more specific explanation like this:
numTasks: total tasks num of a job/stage
Duration: duration of a job/stage
duration_sum: sum of tasks duration 
duration_max: max value of tasks durations
duration_min: min value of tasks durations 
duration_avg: avg value of tasks durations
diskBytesSpilled_sum: The number of on-disk bytes spilled by tasks
executorCPUTime_sum: CPU Time the executor spends actually running tasks(including fetching shuffle data)
executorDeserializeCPUTime_sum: CPU Time taken on the executor to deserialize tasks
executorDeserializeTime_sum: Time taken on the executor to deserialize this task
executorRunTime_sum: Time the executor spends actually running tasks (including fetching shuffle data)
gettingResultTime_sum: The time that the driver spends fetching tasks results from workers.
input_bytesRead_sum: Bytes read from storage in this job/stage
input_recordsRead_sum: The number of read records in this job/stage
jvmGCTime_sum: Amount of time the JVM spent in garbage collection while executing tasks.
memoryBytesSpilled_sum: The number of in-memory bytes spilled by tasks.
output_bytesWritten_sum: Bytes written in storage in this job/stage
output_recordsWritten_sum: The number of written records in this job/stage
peakExecutionMemory_max: Peak memory used by internal data structures created during shuffles, aggregations and joins. The value of this accumulator should be approximately the sum of the peak sizes across all such data structures created in this task. For SQL jobs, this only tracks all unsafe operators and ExternalSort.
resultSerializationTime_sum: The time spent serializing tasks results on a executor before sending it back to the driver.
resultSize_max: The number of bytes tasks transmitted back to the driver as the TaskResult.
sr_fetchWaitTime_sum: The time spent on fetching data (local and remote)
sr_localBlocksFetched_sum: the number of blocks read locally
sr_localBytesRead_sum: the number of bytes read locally
sr_remoteBlocksFetched_sum: the number of blocks read remotely
sr_remoteBytesRead_sum: the number of bytes read remotely
sr_remoteBytesReadToDisk_sum: the number of bytes read from remote to local disk
sr_totalBytesRead_sum: Total shuffle bytes read, includes both data read locally and data read from remote executors
sw_bytesWritten_sum: the number of bytes written
sw_recordsWritten_sum: the number of records written
sw_writeTime_sum: the time spent on shuffle writing

**Comment by nvliyuan** [comment]
got from 
https://github.com/apache/spark/blob/v3.1.1/core/src/main/scala/org/apache/spark/executor/TaskMetrics.scala
https://spark.apache.org/docs/3.1.2/web-ui.html#content

**Comment by tgravescs** [comment]
thanks for the suggestion, I think it would be good for us to link to the Spark pages rather than duplicating the explanations again.  Hopefully that would make it more clear?

**Comment by sameerz** [comment]
@nvliyuan can you open a PR?

**Comment by nvliyuan** [comment]
> @nvliyuan can you open a PR?

yes, of course.
