### ISSUE TITLE
[FEA] Audit 3.2.0 - [SPARK-35110][SQL] Handle ANSI intervals in WindowExecBase

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2778]
**Is your feature request related to a problem? Please describe.**
Spark now supports `YearMonthIntervalType` or `DayTimeIntervalType` as the sort expression for window frame. We should add the same support.

**Describe the solution you'd like**
Add the same feature.

**Describe alternatives you've considered**
None

**Additional context**
See https://github.com/apache/spark/commit/6c587d2627

**Comment by sameerz** [comment]
Duplicate of issue #2778
