### ISSUE TITLE
[FEA] Databricks integration testing setup improvements

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#278]
- The integration tests run as part of the nightly and run differently then the normal integration build, do we want to commonize those and create a databricks integration build

**Comment by tgravescs** [comment]
Note that we also need a final integration test build for databricks that tests the released combined Rapids jar

**Comment by sameerz** [comment]
@tgravescs have we addressed the first two bullets since this issue was opened? 

> Right now we don't run the unit tests on databricks. They wouldn't easily run as other classes were missing. We could try to figure this out and run them
> The integration tests run as part of the nightly and run differently then the normal integration build, do we want to commonize those and create a databricks integration build

**Comment by tgravescs** [comment]
no they haven't.

**Comment by tgravescs** [comment]
split unit tests into: https://github.com/NVIDIA/spark-rapids/issues/1320

**Comment by tgravescs** [comment]
one of the main points to separate would be so you could use the integration test job to run againjst other versions os the jars. For instance once we did a staging for the 0.3 release could we just run the integration tests against those jars.  

But since the unit tests do not run right now I think I want to keep some testing with the build itself as well so I don't see a reason to change the existing build.

@GaryShen2008 @NvTimLiu what plans do we have for testing the release?  We could perhaps change this into create a separate integration build for that.

**Comment by GaryShen2008** [comment]
As my understanding, the existing integration test on Databricks is running by spark local mode.
Should we change it to run on the spark cluster of Databricks (I think it's a standalone cluster) as same as what a customer does?

**Comment by NvTimLiu** [comment]
@tgravescs   what plans do we have for testing the release? 
We can run IT against the staging 0.3.0 spark-rapids jars on both AWS and Azure Databricks cluster using CSP Jenkins pipelines on Blossom: https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/

I have the same concern that our integration tests on Databricks clus is spark local mode.
When running with spark standalone mode, there are some failures, as the issue shows: https://github.com/NVIDIA/spark-rapids/issues/1344, we still need some debug on it.

**Comment by tgravescs** [comment]
that's fine then if those integration builds just build against the jars we can close this. I'm not so worried about running standalone, its a nice to have but not a requirement.
