### ISSUE TITLE
[FEA] Audit 3.2.0 - [SPARK-34897][SQL] Support reconcile schemas based on index after nested column pruning

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2780]
**Is your feature request related to a problem? Please describe.**
I'm not sure if we need to do anything for this change in Spark but I think it needs further investigation just to be sure.

https://github.com/apache/spark/commit/e609395913

**Comment by sameerz** [comment]
Duplicate of issue #463
