### ISSUE TITLE
[FEA] Audit 3.2.0 - [SPARK-35026][SQL] Support nested CUBE/ROLLUP/GROUPING SETS in GROUPING SETS

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2781]
**Is your feature request related to a problem? Please describe.**
Add support for nested grouping sets.

User can write grouping analytics like
```
SELECT a, b, count(1) FROM testData GROUP BY a, GROUPING SETS(ROLLUP(a, b));
SELECT a, b, count(1) FROM testData GROUP BY a, GROUPING SETS((a, b), (a), ());
SELECT a, b, count(1) FROM testData GROUP BY a, GROUPING SETS(GROUPING SETS((a, b), (a), ()));
```

See https://github.com/apache/spark/commit/b22d54a58a

**Comment by sameerz** [comment]
Need to add tests for nested grouping sets and decide the next steps after that.
