### ISSUE TITLE
[BUG] In Comparison mode health check does not show the application id

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2790]
At least in comparison mode there is no way to know what application the task, stage, job, or query was a part of. It really only works if you are looking at a single application.  The health checks are just printed out one after another with no label for which application it is for.

**Comment by tgravescs** [comment]
https://github.com/NVIDIA/spark-rapids/pull/2762 added in the appIndex to the for the failed tables, but it does still look like the removed blockmanagers and removed executors table don't have the app index or id. from app index you can get id and app name.
