### ISSUE TITLE
Examine SPARK-35411 (Currying Product while serializing TreeNode to JSON)

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#2803]
SPARK-35411 (PR [here](https://github.com/apache/spark/pull/32557)) deals with how `TreeNode` is serialized to JSON, and how some info isn't serialized, to save memory.
(This was done in relation to the serialization of `Tuple`s and `Product`s, FWIW.)

It looks like this doesn't have direct impact on the plugin, but it warrants another look to confirm.

**Comment by revans2** [comment]
Yes this should have no real impact to us.
