### ISSUE TITLE
Investigate SPARK-35545 (Refactor of SubqueryExpression's members)

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#2808]
[SPARK-35545](https://github.com/apache/spark/pull/32687) refactored `SubqueryExpression`'s `children` field into two different members (`outerAttrs` and `joinCond`).

It doesn't look like the `spark-rapids` code makes direct reference to `SubqueryExpression`, so we shouldn't be affected. But it would be good to have a second opinion. The change isn't user facing, and no tests were modified for this change.

I'm hoping this does not necessitate an addition to the Shims.

**Comment by tgravescs** [comment]
the only thing I see here would be ScalarSubquery because we have a GpuScalarSubquery but it doesn't use the expressions from ScalarSubquery.
