### ISSUE TITLE
Make changes to support API change in SPARK-34246

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2813]
There is a change in API definition for `findTightestCommonTypes`. We need to make corresponding change in the plugin where we are calling this method

**Comment by revans2** [comment]
```
$ find . -type f -iname \*.scala | xargs grep -l findTightestCommonTypes
```

returns nothing.  We are not calling this directly.  That said we probably do want to add more tests for ANSI mode, and it might cause some issues because type corrosion is very different in ANSI vs non-ANSI mode.
