### ISSUE TITLE
SPARK-35243 has introduced support for ANSI interval types

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2814]
Add cache support for ANSI Interval types as in SPARK-35243

**Comment by res-life** [comment]
It's duplicated with #4148, and it has been fixed.
@razajafri  can we close it?

**Comment by res-life** [comment]
It's duplicated with #4148, and it has been fixed.
ANSI Interval types includes year-month and day-time. 
Note:  Only day-time is supported now.
@razajafri can we close it?

**Comment by razajafri** [comment]
Issue #4148 is for PCBS only. This ticket is a general one and for all the types introduced in Spark 3.3 including `YearMonthIntervalType`

**Comment by res-life** [comment]
Both ANSI year month type and ANSI day time type were supported.
