### ISSUE TITLE
SPARK-35349 adds more support for code-gen to SortMergeJoinExec 

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2824]
I don't think this affect us because we don't deal with CodeGen, but just make sure we aren't affected. 

https://github.com/apache/spark/commit/7bcadedbd2

**Comment by jlowe** [comment]
This only impacts code generation for this specific exec which has no impact on the RAPIDS Accelerator.  This code path is not used when using the RAPIDS Accelerator, and the nature of the changes do not apply.
