### ISSUE TITLE
[Audit][SPARK-35640][SQL] Refactor Parquet vectorized reader to remove duplicated code paths

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2831]
https://issues.apache.org/jira/browse/SPARK-35743
https://github.com/apache/spark/commit/e9ccf4a50c

This is just refactoring the parquet vector reader code, which we use some of in the ParquetCachedBatchSerializer. I think it should either just work or would fail or build/test, but filing this just to track

**Comment by wbo4958** [comment]
> > I just checked the ParquetCachedBatchSerializer, looks like it didn't use any parquet vector reader code.
> 
> See https://github.com/NVIDIA/spark-rapids/blob/branch-22.04/sql-plugin/src/main/311+-all/scala/com/nvidia/spark/rapids/shims/v2/ParquetCachedBatchSerializer.scala#L698-L701. There are other accesses to the Parquet vectorized column reader in that file.

Thx @jlowe, Looks like ParquetCachedBatchSerializer is using readBatch of VectorizedColumnReader by reflection. The recent Spark PR is reworking the readBatch, but we just use it, which seems ok. For other parts, ParquetCachedBatchSerializer tries to compose the code of initBatch into CurrentBatchIterator, which seems to be ok too.

**Comment by jlowe** [comment]
Sounds like we're good then.  Closing this as investigated with no need for further followup.
