### ISSUE TITLE
As a result of SPARK-34637 there is a change to AdaptiveSparkPlanExec when employing DPP and AQE

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2857]
For more info look at https://github.com/apache/spark/commit/b6d57b6b99

**Comment by tgravescs** [comment]
Note we should make sure to add tests for DPP and AQE.

Note this jira was required for a change we made to spark at https://github.com/apache/spark/pull/32195 (SPARK-35093), which I think is also linked to https://github.com/NVIDIA/spark-rapids/issues/2450
