### ISSUE TITLE
[FEA] [AUDIT] [SPARK-35264] AQE query stages should specify isRuntime=true in Statistics

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2864]
**Is your feature request related to a problem? Please describe.**
The AQE logical optimizer can now treat runtime statistics separately from plan-time statistics. See [SPARK-35264](https://github.com/apache/spark/commit/39889df32a) for one example of this, but we need to make the change more broadly so that any statistics returned from query stages have the new `isRuntime` attribute set to `true`.

**Describe the solution you'd like**
Any statistics that we return from AQE query stages need to have `isRuntime=true`.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sperlingxx** [comment]
Hi @andygrove, I am not sure what kinds of change we need to make in terms of rapids-plugin. I didn't find anything reference of `Statistic` in rapids-plugin except `GpuExchangeExec.runtimeStatistics`.

**Comment by andygrove** [comment]
Thanks @sperlingxx. I took another look at this and we don't have to make changes after all. Spark's `QueryStageExec` (which we don't replace) will take the statistics from our exchanges and automatically set `isRuntimeStatstics` to true.

```scala
  def computeStats(): Option[Statistics] = if (isMaterialized) {
    val runtimeStats = getRuntimeStatistics
    val dataSize = runtimeStats.sizeInBytes.max(0)
    val numOutputRows = runtimeStats.rowCount.map(_.max(0))
    Some(Statistics(dataSize, numOutputRows, isRuntime = true))
  } else {
    None
  }
```
