### ISSUE TITLE
[FEA][AUDIT][SPARK-35888][SQL] Add dataSize field in CoalescedPartitionSpec

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#2865]
In Spark 3.2.0 the `dataSize` field was added to `CoalescedPartitionSpec`. https://github.com/apache/spark/commit/622fc686e26e03e8a8ee16568cfd3189fbfaa41e

`CustomShuffleReaderExec` was changed to account for this. We have `GpuCustomShuffleReaderExec` which also needs the change minimally.

There's more to this change around skew we should take a look at during this issue to see if we need to make changes.

**Comment by revans2** [comment]
I am fairly sure that I fixed this as a part of #3459
