### ISSUE TITLE
[FEA] Support joins(SHJ and BHJ) on struct as join key with nested struct in the selected column list

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#2876]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish the RAPIDS Accelerator for Apache Spark would [...]
Support joins(SHJ and BHJ) on struct as join key with nested struct in the selected column list

Currently GSHJ fallback to SMJ:
```
!Exec <SortMergeJoinExec> cannot run on GPU because unsupported data types in input: StructType(StructField(n...
```

GBHJ falling back to BHJ: 
```
 !Exec <BroadcastHashJoinExec> cannot run on GPU because unsupported data types in input: StructType(Struc...
```

**Describe the solution you'd like**
GpuShuffledHashJoin and GpuBroadcastHashJoin can work on struct and nested struct.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by revans2** [comment]
So to be clear we do support joins on Structs as keys, but only a single level deep. What exactly are the requirements here? Is this doing a join on a deeply nested struct as a key? or are the deeply nested structs carried along in the join, but not a part of the join key? 

Do you need structs with arrays/more structs as children? This is likely going to be problematic to try and support in cudf if it is for join keys.

**Comment by viadea** [comment]
> So to be clear we do support joins on Structs as keys, but only a single level deep. What exactly are the requirements here? Is this doing a join on a deeply nested struct as a key? or are the deeply nested structs carried along in the join, but not a part of the join key?
> 
> Do you need structs with arrays/more structs as children? This is likely going to be problematic to try and support in cudf if it is for join keys.

It is join on a single-level struct as join key, but the selected columns has a struct-of-struct(just 2-levels).
struct-of-struct should have all primitive data types.

The mini repro I have is:
```
import org.apache.spark.sql.Row
import org.apache.spark.sql.types._

val data = Seq(
    Row(Row("Adam ","","Green"),"1","M",1000),
    Row(Row("Bob ","Middle","Green"),"2","M",2000),
    Row(Row("Cathy ","","Green"),"3","F",3000)
)

val schema = (new StructType()
  .add("name",new StructType()
    .add("firstname",StringType)
    .add("middlename",StringType)
    .add("lastname",StringType)) 
  .add("id",StringType)
  .add("gender",StringType)
  .add("salary",IntegerType))

val df = spark.createDataFrame(spark.sparkContext.parallelize(data),schema)
df.write.format("parquet").mode("overwrite").save("/tmp/testparquet")

val df2 = spark.read.parquet("/tmp/testparquet")
df2.createOrReplaceTempView("df2")

val nested_struct_df=spark.sql("select struct(name, struct(name.firstname, name.lastname) as newname) as col,name from df2")
nested_struct_df.createOrReplaceTempView("nested_struct_df")

// nested struct in selected columns while join key is a single level struct. -- fallback as BroadcastHashJoin.
spark.sql("select a.* from nested_struct_df a, nested_struct_df b where a.name=b.name").show
spark.sql("select a.* from nested_struct_df a, nested_struct_df b where a.name=b.name").explain

// nested struct in selected columns while join key is a single level struct. -- fallback as SortMergeJoin.
spark.conf.set("spark.sql.autoBroadcastJoinThreshold",1)
spark.sql("select a.* from nested_struct_df a, nested_struct_df b where a.name=b.name").show
spark.sql("select a.* from nested_struct_df a, nested_struct_df b where a.name=b.name").explain
```

**Comment by jlowe** [comment]
Technically we could do this outside of cudf by manually exploding the struct validity and child columns recursively as the join key columns, but since there's already a utility method that does this in libcudf that's leveraged for the sort case, I think it would be simplest and better performing to support this in libcudf directly.  If we do this in Java we'd have to manifest Java objects for all columns at every struct level as part of the explode logic.

**Comment by wbo4958** [comment]
I just enabled the struct of struct in the type checks, and seems it can work in the latest code.

``` console
*Exec <ProjectExec> will run on GPU
  *Exec <BroadcastHashJoinExec> will run on GPU
    *Exec <ProjectExec> will run on GPU
      *Expression <Alias> struct(name, name#0, newname, struct(firstname, name#0.firstname, lastname, name#0.lastname)) AS col#9 will run on GPU
        *Expression <CreateNamedStruct> struct(name, name#0, newname, struct(firstname, name#0.firstname, lastname, name#0.lastname)) will run on GPU
          *Expression <CreateNamedStruct> struct(firstname, name#0.firstname, lastname, name#0.lastname) will run on GPU
            *Expression <GetStructField> name#0.firstname will run on GPU
            *Expression <GetStructField> name#0.lastname will run on GPU
      *Exec <FilterExec> will run on GPU
        *Expression <IsNotNull> isnotnull(name#0) will run on GPU
        *Exec <FileSourceScanExec> will run on GPU
    *Exec <BroadcastExchangeExec> will run on GPU
      *Exec <ProjectExec> will run on GPU
        *Expression <Alias> struct(name, name#15, newname, struct(firstname, name#15.firstname, lastname, name#15.lastname)) AS col#14 will run on GPU
          *Expression <CreateNamedStruct> struct(name, name#15, newname, struct(firstname, name#15.firstname, lastname, name#15.lastname)) will run on GPU
            *Expression <CreateNamedStruct> struct(firstname, name#15.firstname, lastname, name#15.lastname) will run on GPU
              *Expression <GetStructField> name#15.firstname will run on GPU
              *Expression <GetStructField> name#15.lastname will run on GPU
        *Exec <FilterExec> will run on GPU
          *Expression <IsNotNull> isnotnull(name#15) will run on GPU
          *Exec <FileSourceScanExec> will run on GPU


*Exec <ProjectExec> will run on GPU
  *Exec <SortMergeJoinExec> will run on GPU
    #Exec <SortExec> could run on GPU but is going to be removed because replacing sortMergeJoin with shuffleHashJoin
      #Expression <SortOrder> name#0 ASC NULLS FIRST could run on GPU but is going to be removed because parent plan is removed
      *Exec <ShuffleExchangeExec> will run on GPU
        *Partitioning <HashPartitioning> will run on GPU
        *Exec <ProjectExec> will run on GPU
          *Expression <Alias> struct(name, name#0, newname, struct(firstname, name#0.firstname, lastname, name#0.lastname)) AS col#9 will run on GPU
            *Expression <CreateNamedStruct> struct(name, name#0, newname, struct(firstname, name#0.firstname, lastname, name#0.lastname)) will run on GPU
              *Expression <CreateNamedStruct> struct(firstname, name#0.firstname, lastname, name#0.lastname) will run on GPU
                *Expression <GetStructField> name#0.firstname will run on GPU
                *Expression <GetStructField> name#0.lastname will run on GPU
          *Exec <FilterExec> will run on GPU
            *Expression <IsNotNull> isnotnull(name#0) will run on GPU
            *Exec <FileSourceScanExec> will run on GPU
    #Exec <SortExec> could run on GPU but is going to be removed because replacing sortMergeJoin with shuffleHashJoin
      #Expression <SortOrder> name#57 ASC NULLS FIRST could run on GPU but is going to be removed because parent plan is removed
      *Exec <ShuffleExchangeExec> will run on GPU
        *Partitioning <HashPartitioning> will run on GPU
        *Exec <ProjectExec> will run on GPU
          *Exec <FilterExec> will run on GPU
            *Expression <IsNotNull> isnotnull(name#57) will run on GPU
            *Exec <FileSourceScanExec> will run on GPU
```

@jlowe, Would I ask if we are still waiting for the cudf supporting? if yes, Could you send me the cudf issue here?

**Comment by revans2** [comment]
@wbo4958 There was miscommunication.  When @ttnghia implemented the changes to cudf to support sorting on struct/etc we thought it would be for a single level, but he did recursively for all levels.  Just enabling the config and adding tests is probably enough to make this work.

Be aware that as I tried to enable nested types in joins for non-key columns I ran into https://github.com/rapidsai/cudf/issues/8929. This does not directly impact join, especially because who is going to join on a struct column with no children. But if you do end up hitting it in your tests be aware that I already filed something for it.

**Comment by ttnghia** [comment]
Alright, since @wbo4958 has also picked this plugin work and there is no cudf change required, what we (@wbo4958) need to do seems to just add tests. Feel free to tag me for any additional cudf work.

**Comment by jrhemstad** [comment]
As you've found, @hyperbolic2346 implemented this a while back.

**Comment by wbo4958** [comment]
@revans2 @ttnghia Thx for the information, I just had a PR #3158 to enable Joins on nested struct.
