### ISSUE TITLE
[FEA] Support Sort on nested struct

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#2878]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish the RAPIDS Accelerator for Apache Spark would [...]
Support Sort on nested struct.

Currently the Sort can only work on nested struct:
```
!Exec <SortExec> cannot run on GPU because not all expressions can be replaced
  !Expression <SortOrder> col#74 ASC NULLS FIRST cannot run on GPU because expression AttributeReference col#74 produces an unsupported type StructType(StructField(name,StructType(StructField(firstname,StringType,true)...
```

**Describe the solution you'd like**
GpuSort should work on nested struct.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by viadea** [comment]
This use case is to sort on a single-level struct or a two-level struct with primitive type.

**Comment by sameerz** [comment]
For this use case we will only support the default null ordering in Spark, and document that limitation.
