### ISSUE TITLE
[BUG] Stable sorting should be used when falling back to sort-based aggregation

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#2884]
#2859 adds the ability to fallback to a sort-based aggregation when the data is too large to aggregate all at once.  There are some aggregations, like first/last, that are sensitive to the ordering of the input, and the relative ordering of values for the same key could change when using an unstable sort.  This could result in an unpredictable result for the aggregation.

**Comment by revans2** [comment]
I filed https://github.com/NVIDIA/spark-rapids/issues/9275 as a long term proper fix for this so that we get stable sorting by default.

**Comment by jlowe** [comment]
closing in favor of #9275.
