### ISSUE TITLE
Release Checklist v21.08

### ISSUE THREAD

**Issue by Salonijain27** [NVIDIA/spark-rapids#2885]
Release Checklist for v21.10:

| Status  | Task | Start | End | Owner| 
| ------------- | ------------- | ------------- | ------------- | ------------- | 
|**Pre-release**| | | | |
|<ul><li>- [X] </li></ul> | Notification to team of last feature sprint in milestone 2021-07-05 - 2021-07-16 | 2021-07-05 | 2021-07-05 | @sameerz| 
|<ul><li>- [X] </li></ul> | Burndown (no new features for current release) | 2021-07-19 | 2021-07-30 | Team|  
|<ul><li>- [X] </li></ul> | Update docs for current release in spark-rapids | 2021-07-26| 2021-07-30 | Team| 
|<ul><li>- [X] </li></ul> | Get RAPIDS 21.10 cudf java build working.  | 2021-07-19 | 2021-07-23 | @pxLi | 
|<ul><li>- [X] </li></ul> | Create 21.10 branch | 2021-07-26 | 2021-07-26 | @pxLi | 
|<ul><li>- [X] </li></ul> | Automerge from 21.08 to 21.10 | 2021-07-26 | 2021-07-30 | @pxLi | 
|<ul><li>- [X] </li></ul> | Enable Jenkins builds (premerge, nightly, integration, performance) for 21.10 | 2021-07-26 | 2021-07-26 | @pxLi | 
|<ul><li>- [X] </li></ul> | Virtual review | 2021-08-02 | 2021-08-13 |@krajendrannv | 
|<ul><li>- [X] </li></ul> | [cudf 21.08] Java release to sonatype | 2021-08-05 | 2021-08-05 | @NvTimLiu | 
|<ul><li>- [X] </li></ul> | Notify RAPIDS team of javadocs for 21.08 | 2021-08-06 | 2021-08-06 | @GaryShen2008 | 
|**Staging release**||||
|<ul><li>- [X] </li></ul> | Make 21.10 the default branch | 2021-08-02 | 2021-08-02 | @jlowe | 
|<ul><li>- [X] </li></ul> | Merge all remaining branch-21.08 PRs | 2021-07-30 | 2021-07-30 | Team | 
|<ul><li>- [X] </li></ul> | Create CHANGELOG.md | 2021-07-30| 2021-07-30| @pxLi | 
|<ul><li>- [X] </li></ul> | Create a PR (not squashed) to merge from branch-21.08 to main. Needs review from repository owner | 2021-08-05 | 2021-08-05 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Trigger the release Jenkins job on the main branch and deploy the jar to sonatype staging | 2021-08-09 | 2021-08-09 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Deliver Snapshot packages to QA | 2021-08-02 | 2021-08-02 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Deliver final packages to QA | 2021-08-09 | 2021-08-09 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Run integration tests on staging jars with AQE on, UCX on, Databricks Azure, Databricks AWS, Dataproc | 2021-08-09 | 2021-08-13 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Run integration tests on staging jars with AQE on, A10/A30 manually | 2021-08-09 | 2021-08-13 | @GaryShen2008|
|<ul><li>- [X] </li></ul> | Run LHA tests on staging jars | 2021-08-09 | 2021-08-13 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Run pre-processing workflow for [DLRM sample use case](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Recommendation/DLRM#advanced)| 2021-08-09 | 2021-08-13 | @johnzhong |  
|<ul><li>- [X] </li></ul> | QA testing with Snapshot on YARN, NGC with Volta and Ampere | 2021-08-02 | 2021-08-06 | @yuange98|  
|<ul><li>- [X] </li></ul> | QA testing with final packages on YARN, NGC with Volta and Ampere | 2021-08-09 | 2021-08-13 | @yuange98|  
|**Release**| | | | |  
|<ul><li>- [X] </li></ul> | Tag the release and deploy the staging artifacts to maven central repository | 2021-08-18 | 2021-08-18 | @NvTimLiu|  
|<ul><li>- [X] </li></ul> | Update gh-pages | 2021-08-16 | 2021-08-18 | @viadea |  
|<ul><li>- [X] </li></ul> | Update docs for current release in spark-rapids-examples | 2021-08-16 | 2021-08-18| @GaryShen2008|  
|<ul><li>- [x] </li></ul> | Update rapids.sh in  https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/rapids https://github.com/GoogleCloudDataproc/initialization-actions/pull/921 for the plugin, pending update for xgboost | 2021-08-16 | 2021-08-18 | @viadea |

**Comment by GaryShen2008** [comment]
Enable Jenkins builds (premerge, nightly, integration, performance) for 21.10 | 2021-07-20 | 2021-07-20

It should be the same day when we open the new branch 21.10, I think.

**Comment by pxLi** [comment]
cudf 21.10 PR can not be merged which has been reported internally. I am still waiting for that to get ready before merge my version update https://github.com/rapidsai/cudf/pull/8765, this may delay setup 21.10.0 cudfJNI build until next week

**Comment by pxLi** [comment]
21.08.0 changelog has been init in https://github.com/NVIDIA/spark-rapids/pull/3083, we will do a final update before the real package build

**Comment by NvTimLiu** [comment]
As cudf has not be released yet, cudfjni 21.08.0 plans to release on Aug 5, we will update POM dependency after cudfjni 21.08.0 release. 
So I suppose we postpone the checklist item after cudfjni 21.08.0 release `Create a PR (not squashed) to merge from branch-21.08 to main.`
I agree that we can keep the development branch to stick w/ -SNAPSHOT, and only update doc to release branch (main)

**Comment by NvTimLiu** [comment]
Removed tests on `AWS EMR`, as our spark-rapids do not support EMR spark runtime currently.
