### ISSUE TITLE
Remove Spark version specific Serializers unless they need to override behavior

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2905]
Right now we have ParquetCachedBatchSerializer for every version of Spark since 3.1.1 e.g 312 311db and 311cdh. We need to come up with a way to avoid this unnecessary class.

**Comment by razajafri** [comment]
I am debating about whether this is really something that we should shim at the moment because there is only one implementation of the class. 

It doesn't make sense, as I understood the problem, to load the serializer dynamically as the user is going to specify the exact class that should be used as the serializer. I think the approach to this should be that we create the ParquetCachedBatchSerializer in the 311 shims outside of the 311 package i.e. `com.nvidia.spark.rapids`. The user can then specify this serializer for all the versions of Spark including and after 311 (when configurable serializer was enabled). 

Let me know what you guys think. I have a PR up already with the above fix so chime in on that

**Comment by tgravescs** [comment]
so what happens in that case if you need to shim for spark 3.2?   Will that never happen?
If you have to shim say 3.2 or 3.3 or Databricks, then that approach doesn't work then so you either have to go back to specifying a package name for different versions or make a generic class like we are asking if is possible now.

There are different approaches but it looks likeSpark just creates an instance of this based on the parameter and as long as it extends CachedBatchSerializer it is fine.

So can you make a Generic version that just loads the shim version and then calls into it:

val realSerialize = ShimLoader.getSparkShims.getCacheSerializer 
that would instantiate the correct shim version of the cache serializer.

Then all the function calls use realSerialize.function()

**Comment by jlowe** [comment]
Yep, as long as `CachedBatchSerializer`'s interface remains stable, even if we need to shim for certain versions we can always internally delegate from the generic class to a shim version for implementation.  Therefore the decision boils down to how stable do we think `CachedBatchSerializer`'s API will be over time?  If it changes in a future version of Spark then we may have no choice but to provide an alternate class and force the user to specify the correct class to match the Spark version.  That's what forced us down that path for the shuffle manager.

**Comment by razajafri** [comment]
> Yep, as long as CachedBatchSerializer's interface remains stable
@revans2 and @tgravescs can we assume the interface is not going to change in the near term?
