### ISSUE TITLE
Profiling tool compare mode missing rapids and cudf jars

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2913]
**Describe the bug**
The profile tool in normal mode prints the plugin and cudf jars, compare mode does not, we should add that to compare mode as well.

**Comment by nartal1** [comment]
This issue has already been addressed in this PR - https://github.com/NVIDIA/spark-rapids/pull/3342. I see rapids and cudf jars in the compare mode output as well. Closing.
