### ISSUE TITLE
[BUG] Dont ask users to rebase on a PR

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#2918]
**Describe the bug**
I just noticed that if a PR has merge conflicts the response from build says that they should rebase and try again.  We are asking users not to rebase but just to upmerge, because rebase can confuse github's review comments.  We should update this message to please upmerge and resolve the merge conflicts instead of rebase.

**Comment by pxLi** [comment]
Hi @revans2 , the message was submitted by blossom self-hosted runner when they saw merge conflict, I could ask them to modify the message if needed. But I don't quite get
> We are asking users not to rebase but just to upmerge, because rebase can confuse github's review comments.

upmerge create extra merge commit here, and rebase keep the history clean, and PR will not have the merge info after squash, how did rebase confuse people here?

**Comment by revans2** [comment]
> upmerge would create extra merge commit here, rebase could keep the history clean, and merged PR will not include the merge commit message after squash. I am curious in what cases rebase could confuse review comments here but upmerge would not? can you share some examples to help me understand? Thanks!

We always squash when we commit. What the history on the PR looks like does not matter.  It will end up as a single commit on the release branch.

I don't understand 100% what happens with github review comments or why they can get messed up. They appear to be tied to specific git hashes/line numbers and when a rebase happens the git hash they are tied to disappears so then github has to try and figure out where that line number went to put them.  In the past I have seen review comments totally disappear when this happens. Granted that was a while ago so github could be a lot better now. Generally we discourage people from rebasing their commits because it can mess up github comments and it provides to tangible benefit from the perspective of the project. So if we have a tool telling users to rebase which is the opposite of what we ask users to do then it looks bad.

This is a really minor thing and if it is not easily configurable then I don't want to time on it.  I was hoping it would be a single line that we could change somewhere so that we could be consistent. If it is not that simple then we can close this and just not fix it.

**Comment by jlowe** [comment]
The other reason we don't want people rebasing branches is they sometimes squash their branch commits in the process, and that makes re-reviews more difficult since you can't look at just the new commit to figure out what changed since the last time you reviewed it.

**Comment by pxLi** [comment]
fair enough. Since the blossom runner are shared by multiple teams, we cannot change it to `upmerge` from `rebase`. I submitted a MR to remove the merge conflict fix method in message, and I will close this issue after they merge and redeploy the self-hosted runner.

**Comment by pxLi** [comment]
MR merged internally, blossom plans to do a self-hosted runner redeployment on Jul 29. I will close this issue after the deployment

**Comment by pxLi** [comment]
fixed w/ self-hosted runner upgrade
