### ISSUE TITLE
Improve performance of large, inefficient partial aggregations

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#2921]
Sometimes partial aggregations can be particularly inefficient in terms of reducing the row count of the original input batch.  For example, computing a distinct result of many input batches that are already distinct.  In these situations, it may be more efficient to send the batched partial aggregations directly to the shuffle as they are computed rather than attempting to cache and merge them for minimal shuffle size savings.  The final merge after the shuffle will still have to do the merge, but the partial aggregation could be much more efficient for that scenario.

The row count of the batch aggregations could be compared to the original input batch row counts, and some heuristic could be used to determine that the input appears not worthy of merge-aggregating in the partial phase.  This could be made even more efficient if we realize the aggregated schema matches the input schema, meaning we could pass the input batches straight to the shuffle without attempting a partial aggregation at all.

**Comment by sperlingxx** [comment]
"we could pass the input batches straight to the shuffle without attempting a partial aggregation at all." 
DataBricks runtime did the exact thing: eliminating map-side combine under certain situations.

**Comment by mattahrens** [comment]
Closing as won't fix for now
