### ISSUE TITLE
[FEA] Add jupyter notebook for mortgage query

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#293]
We really should have the notebooks from the demo available for others to play around with.  It will need to be modified to say how to get the data, etc.

**Comment by revans2** [comment]
I was looking at doing this, and I can do the simple thing of adding in the notebook, but

1) It points to data in S3 that is not publicly accessible.  Do we want to change this to point to something else.  If so what?
2) We don't have a good way to be sure that the notebook is properly maintained. The data is in S3, like I said, so running it locally is not going to help unless we can change that.  Also do we want to hack together some things to verify that the output of the notebook is what we expected and that it ran entirely on the GPU?

**Comment by krajendrannv** [comment]
Bobby, would the recent PR help with this?

**Comment by revans2** [comment]
Yes it helps. That answered a lot of my questions about this.  One of my main concerns is that the mortgage queries in the notebooks do not match the one that we did the demo for.  They are all copied from the XGBoost repo and so have extra processing in them that has caused some issues with one customer. Not sure if that is going to be a problem or not.
