### ISSUE TITLE
[BUG] Profiling tool does not show "Potential Problems" for dataset API in section "SQL Duration and Executor CPU Time Percent"

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#2930]
**Describe the bug**
Profiling tool does not show "Potential Problems" for dataset API in section "SQL Duration and Executor CPU Time Percent".

But the "Lambda" keyword is found in the "SQL Plan HealthCheck" section.

Such as:
```
SQL Duration and Executor CPU Time Percent
+--------+-----------------------+-----+------------+-------------------+------------+------------------+-------------------------+
|appIndex|App ID                 |sqlID|SQL Duration|Contains Dataset Op|App Duration|Potential Problems|Executor CPU Time Percent|
+--------+-----------------------+-----+------------+-------------------+------------+------------------+-------------------------+
|1       |app-11111111111111-0000|0    |2980        |false              |37541       |null              |52.04                    |
|1       |app-11111111111111-0000|1    |543         |true               |37541       |null              |48.71                    |
+--------+-----------------------+-----+------------+-------------------+------------+------------------+-------------------------+
SQL Plan HealthCheck:
Unsupported SQL Plan
+--------+-----+------+--------+---------------------------------------------------------------------------------------------------+
|appIndex|sqlID|nodeID|nodeName|nodeDescription                                                                                    |
+--------+-----+------+--------+---------------------------------------------------------------------------------------------------+
|1       |1    |8     |Filter  |Filter $line21.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$Lambda$4578/0x00000008019f1840@4b63e04c.apply|
+--------+-----+------+--------+---------------------------------------------------------------------------------------------------+
```
**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

Profile an event log which contains dataset api (Lambda keyword) in the query plan.

**Expected behavior**

"Potential Problems" column in section "SQL Duration and Executor CPU Time Percent" should show the problematic dataset api.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

Using latest 21.08 snapshot jar for this tool. 

**Additional context**

**Comment by tgravescs** [comment]
the dataset was never listed as a potential problem, it purely took away from the sql dataframe duration time and then listed in Contains Dataset Op.
