### ISSUE TITLE
Qualification & Profiling tool: Add automated tests to run inside CSPs.

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#2954]
We need to add automated tests to run Qualification & Profiling tool inside CSPs -- Databricks/EMR/Dataproc, and also CDP at least once per week. 
We can rotate the CSPs/CDP envs each time.

The goal is to make sure the tool can be submitted inside those envs using their spark jars.

**Comment by zhanga5** [comment]
as @tgravescs refined both tools won't require using Spark and SQL any more, is this issue still valid?

**Comment by tgravescs** [comment]
We still require the Spark jars to be present since we use classes from them so I think this would still be good to do.

**Comment by zhanga5** [comment]
I see. Any idea about what kind of event logs and where to keep it for these testings?

**Comment by tgravescs** [comment]
I think for this if we are running inside the CSP we just run some jobs to generate the logs and then read them there.  That way no storing of event logs and we regenerate everytime and make sure CSP didn't change anything in formatting that would break us.  

As far as what to run we could either run some of the integration tests and then run on the event logs generated from that, let me look into that a bit more.

**Comment by tgravescs** [comment]
cdp part of this split out into https://github.com/NVIDIA/spark-rapids/issues/3360

**Comment by tgravescs** [comment]
We want to run on event logs generated by running jobs on those.  One thought is to start out with just running them on the integration test event logs.  Then I think we would want to add in a couple of more specific tests, which perhaps we can add into just the tools test suite area.

**Comment by zhanga5** [comment]
it's completed for Databricks environment while still in progress for Dataproc. It would be completed soon.

**Comment by zhanga5** [comment]
test from Dataproc environment is completed
