### ISSUE TITLE
Qualification & Profiling tool: Add automated tests to process different types of event logs.

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#2955]
We need to add automated tests to use Qualification & Profiling tool to process different types of event logs from Databricks/EMR/Dataproc/CDP. 
Some of the logs are already downloaded on the HDFS cluster.

The goal is to make sure both tools can process different types of Spark event logs.

**Comment by tgravescs** [comment]
all the logs have been added to the nightly
