### ISSUE TITLE
[BUG] Builds failing due to breaking changes in SPARK-36034

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#2957]
**Describe the bug**

There is a [breaking change](https://github.com/apache/spark/commit/ba7117224c797e3ade64a281b1a165cf5040c541) in Spark branch-3.1 

```
java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.parquet.ParquetFilters.<init>(Lorg/apache/parquet/schema/MessageType;ZZZZIZ)V
[2021-07-16T20:40:17.896Z] 	at com.nvidia.spark.rapids.GpuParquetFileFilterHandler.filterBlocks(GpuParquetScan.scala:269)
[2021-07-16T20:40:17.896Z] 	at com.nvidia.spark.rapids.GpuParquetMultiFilePartitionReaderFactory.$anonfun$buildBaseColumnarReaderForCoalescing$1(GpuParquetScan.scala:365)
```

**Steps/Code to reproduce bug**
We are seeing this in CI builds

**Comment by pxLi** [comment]
always reproducible w/ `mvn test -Pspark313tests,snapshot-shims` use the 3.1.X-SNAPSHOT shim test

**Comment by pxLi** [comment]
https://github.com/apache/spark/commit/e41ecef61b3f40b51d2d63056c826ef35b920791 also pushed to 3.0 branch, so it failed our 3.0.4-snapshot test, going to add shim to 304 as a following-up of https://github.com/NVIDIA/spark-rapids/pull/2961
