### ISSUE TITLE
[FEA] Hash Aggregate Cleanup to make closer to spark

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3]
**Is your feature request related to a problem? Please describe.**
A lot of the processing in the GPU aggregate operations are not as close to spark as they could be.  It would be nice to make it more similar to help reduce the possibility of bugs and to increase the possibility of code reuse.

**Comment by abellina** [comment]
This issue should have been closed by the work in #3910 and #4272.

In a nutshell, the `aggregate.scala` code was made simpler and more consistent between group-by and reduction, in addition to removing complicate code in `setupReferences` that was not required. In `AggregateFunctions.scala` the `GpuAggregateFunction` and `CudfAggregate` interfaces were better defined and documented and flexible enough for complicated operations like overflow checking for decimals.
