### ISSUE TITLE
[FEA] Qualification tool: Add filters based on Regex and user name.

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#3041]
**Is your feature request related to a problem? Please describe.**
1. As a user, I want to select log files for applications whose application name matches a given regular expression so that I can only qualify a subset of applications of interest.
2. As a user, I want to select log files for applications submitted by a specific user so that I can qualify only applications a particular user has submitted.

**Comment by tgravescs** [comment]
fixed by 3025
