### ISSUE TITLE
[FEA] Columnar (non-GPU) support for scala UDFs

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#306]
Scala UDFs are implemented using the `ScalaUDF` expression class.  It is unlikely that we are going to be able to support running these UDFs on the GPU in the near future.  So until then we should look at what it would take to pull back to the CPU just the columns we need to process the UDF.  Process it on the CPU in a tight columnar loop, and then send the result back to the GPU.

There is a lot of room for follow on work to look at things like.

We will need to do some performance tests to see if this is viable or if we should do something else.  Are there rules about when this is good and when this is bad, like if there are too many columns or the columns are not fixed width does it make since to do this?

**Comment by jlowe** [comment]
Has this been addressed by #3897?

**Comment by mattahrens** [comment]
Closing as work has been completed
