### ISSUE TITLE
Explore the possibility of using the new TimestampNTZType instead of TimestampType every where in the plugin

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#3103]
Spark 3.2 will be introducing a new TimestampNTZType. 
I could be wrong but won't it make sense to just use the TimestampNTZType across the plugin?

**Comment by revans2** [comment]
I don't think so because TypestampNTZType does not exist for all versions of Spark that we want to support (3.2+) and even then the user has the option to still use the old timestamp type. I also think that the old type is the default.

**Comment by sameerz** [comment]
Closing based on the above comment.
