### ISSUE TITLE
SPARK-35874 has removed an `mapOutputStatisticsFuture` API

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#3104]
We need to incorporate this change because there was an API removed

For more details read [SPARK-35874](https://github.com/apache/spark/commit/b8d3da16b1)

**Comment by andygrove** [comment]
I took a quick look at this. The main change is that `ShuffleExchangeLike.mapOutputStatisticsFuture` is now protected and called from a new `submitShuffleJob` method, which is `final`.

```
  final def submitShuffleJob: Future[MapOutputStatistics] = executeQuery {
    mapOutputStatisticsFuture
  }

  protected def mapOutputStatisticsFuture: Future[MapOutputStatistics]
```

Hopefully, we can get away with moving our class to the same package and continue to override this but we'll need to test this once we can compile and test with Spark 3.2.

**Comment by andygrove** [comment]
This isn't causing any test failures locally so I don't think this is a P1. We still need to look at this before we release 21.10 though.

**Comment by andygrove** [comment]
We do not override this method so this does not affect us after all
