### ISSUE TITLE
[BUG] Regression seen in `concatenate` in NDS with RAPIDS Shuffle Manager enabled

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#3135]
We noticed some regressions in our benchmarks with a recent run of 21.08 with RAPIDS Shuffle Manager. Q4, Q47, Q57 especially (I've seen up to 50% slower than without the RAPIDS Shuffle Manager). This affects version 21.08 of the plugin (21.06 doesn't have this issue).

While looking in to Q4 the main issue seems to be libcudf `concatenate` after the shuffle read. This is different than with Spark's built-in shuffle manager, where we perform the concatenate in the host, and not calling cudf.

Here's Q4 with 21.06 with a sample concatenate call (usually single digit millis):

<img width="1372" alt="Screen Shot 2021-08-04 at 9 23 54 AM" src="https://user-images.githubusercontent.com/1901059/128200173-69d12f88-5a3c-4360-a091-570d7dd4459a.png">

Q4 with 21.08 is > 100ms normally, here's a sample:

<img width="1397" alt="Screen Shot 2021-08-04 at 9 23 43 AM" src="https://user-images.githubusercontent.com/1901059/128200221-b77bf877-0d15-44e2-9850-e1e8715125ad.png">

The trace above is not showing all the memcpys, there are many more to the left, but it shows the relative times. There are essentially many D2H (pageable) 4-byte copies that are each getting synchronized. For Q4, I believe this added ~10 seconds to a 20 second run, so 50% slower. @jlowe believes the copies are used by cudf to determine the length of string columns, especially if the columns are views.

**Comment by abellina** [comment]
I am looking at a repro case in java/cudf and likely running the cudf concatenate benchmarks for 21.06 and 21.08.

**Comment by abellina** [comment]
@nvdbaranec has a patch that works (https://github.com/nvdbaranec/cudf/tree/concat_performance), I was able to test it in the same hardware and on Q4 (the time is back down to a normal amount):

<img width="1121" alt="Screen Shot 2021-08-04 at 4 04 59 PM" src="https://user-images.githubusercontent.com/1901059/128254710-dafb6846-9be4-4a75-908c-3008778939e0.png">

Filing a cuDF issue, will refer to it here

**Comment by nvdbaranec** [comment]
> 
> 
> I am looking at a repro case in java/cudf and likely running the cudf concatenate benchmarks for 21.06 and 21.08.

Note:  Fix is a one-liner.  Pretty safe (but should probably get reviewed by someone like David Wendt)

**Comment by abellina** [comment]
Q47, Q57 also suffered from this issue btw, and @nvdbaranec's fix addresses it.

**Comment by pxLi** [comment]
fix by https://github.com/rapidsai/cudf/pull/8968
