### ISSUE TITLE
[BUG] case when on some nested types can produce a crash

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3139]
**Describe the bug**
```
Caused by: ai.rapids.cudf.CudfException: cuDF failure at: /home/roberte/src/cudf/cpp/src/reshape/interleave_columns.cu:38: Called `interleave_columns` on none-supported data type.
E                   	at ai.rapids.cudf.ColumnVector.makeList(Native Method)
E                   	at ai.rapids.cudf.ColumnVector.makeList(ColumnVector.java:441)
E                   	at ai.rapids.cudf.ColumnVector.makeList(ColumnVector.java:410)
E                   	at ai.rapids.cudf.ColumnVector.empty(ColumnVector.java:1623)
E                   	at ai.rapids.cudf.ColumnVector.empty(ColumnVector.java:1630)
E                   	at ai.rapids.cudf.Scalar.listFromNull(Scalar.java:357)
E                   	at com.nvidia.spark.rapids.GpuScalar$.from(literals.scala:221)
E                   	at com.nvidia.spark.rapids.GpuScalar.getBase(literals.scala:442)
E                   	at com.nvidia.spark.rapids.GpuConditionalExpression.$anonfun$computeIfElse$3(conditionalExpressions.scala:42)
```

This happens when you do a case when statement and no default value is given.  The types involved are.

```
Array(Struct(key: String(not_null), value: Array(Struct(key: String(not_null), value: String))))
```

This is the same as a

```
Map(String(not_null),Map(String(not_null),String))
```

but we don't support maps on case when yet. I was trying to add them and ran into this.

**Comment by revans2** [comment]
This can also impacts GpuCoalesce and GpuLiteral.

**Comment by revans2** [comment]
I filed https://github.com/rapidsai/cudf/issues/9010 to fix this in cudf, but because this is a feature request (cudf does not claim to support this operation) we need to fix this in the short term by either disabling this in the plugin until we can make it work, or find an alternative way to do something in the cudf java APIs for null columns.

**Comment by firestarman** [comment]
Seems this is similar to https://github.com/rapidsai/cudf/issues/8927.

**Comment by revans2** [comment]
Yup I duplicated rapidsai/cudf#9010 to  rapidsai/cudf#8927. github search is just not as good as I would like it to be.

**Comment by ttnghia** [comment]
So should we close this?

**Comment by revans2** [comment]
> So should we close this?

After we add in tests to verify that it is working and does not break again.
