### ISSUE TITLE
[FEA] support nested structs in collect_set

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3152]
**Is your feature request related to a problem? Please describe.**
I filed the cudf issue https://github.com/rapidsai/cudf/issues/8972 to get cudf support for nested structs in collect_set and merge_set. When that is done we need to update the tests and the type checks for collect_set and verify that it works.

**Comment by ttnghia** [comment]
I'm not sure if this is duplicate issue: https://github.com/NVIDIA/spark-rapids/issues/3514

**Comment by ttnghia** [comment]
FYI: The cudf issue is addressed. Now we can start plugin work.
