### ISSUE TITLE
[FEA] Support decimal type in ORC reader

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#3177]
cuDF has added decimal type support in ORC reader by the PR https://github.com/rapidsai/cudf/pull/7970.

So we can enable the decimal support on plugin side now. Maybe just updating the type signature can have this done.

https://github.com/NVIDIA/spark-rapids/issues/3192 is for ORC writer

**Comment by sameerz** [comment]
Hi @firestarman can we split this into two issues, one for decimal reading, and one for writing?  Let's prioritize the reading work for 21.10 as P1.

**Comment by firestarman** [comment]
> Hi @firestarman can we split this into two issues, one for decimal reading, and one for writing? Let's prioritize the reading work for 21.10 as P1.

Sure, and done.
