### ISSUE TITLE
[FEA] look into using cudf::drop_duplicates for distinct phase of aggregations

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3181]
**Is your feature request related to a problem? Please describe.**
cudf has a few APIs dealing with distinct values, like `drop_duplicates` and `distinct_count`.  It would be good if we could measure the performance of these vs the performance of group_by without any aggregations, and in the case of `distinct_count` we probably need to think through a little better how to re-write the query to use it.

If the performance is a lot better than what we are doing now, then we should look into what kind of specializations or query-rewriting we can do to use it and improve performance.

**Comment by revans2** [comment]
I did a little bit of profiling and as soon as we start to shuffle at all the amount of time spent doing the aggregations becomes rather small.  So the priority is probably not super high right now.

**Comment by mattahrens** [comment]
Closing as won't fix for now
