### ISSUE TITLE
[BUG] Databricks parquetFilters build failure in db 8.2 runtime

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#3191]
**Describe the bug**
Looks like Databricks just applied the API change to 8.2, related to https://github.com/NVIDIA/spark-rapids/issues/3098
311db shims layer is still using old ParquetFilters func which inherited from Spark301Shims,
we will need to make an 311db shims layer update 

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 7813.0 failed 1 times, most recent failure: Lost task 0.0 in stage 7813.0 (TID 27101) (ip-10-59-168-175.us-west-2.compute.internal executor driver): 
java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.parquet.ParquetFilters.<init>(Lorg/apache/parquet/schema/MessageType;ZZZZIZ)V
[2021-08-10T21:50:01.141Z] at com.nvidia.spark.rapids.shims.spark301.SparkBaseShims.getParquetFilters(SparkBaseShims.scala:95)
```

db does not add the patch version for their runtime, this brings us many headaches

**Comment by pxLi** [comment]
we may need to target this to 21.06 and release 21.06.2 since it's long-term support version...

**Comment by tgravescs** [comment]
I tried on databricks aws 8.2 runtime using 21.08 and 21.06.01 and both write parquet fine, I"m not sure that is the issue here, investigating.

**Comment by tgravescs** [comment]
so the couple parquet writes I did worked but running the unit tests on 8.2 fail for both 21.10 and 21.08 and likely 21.06.01 as well.   Must be that in 8.2 the ParquetFilters is only hit in certain cases, which seems odd because I think only fallback tests pass, I thought on 7.3 any parquet write hit the issue.

**Comment by tgravescs** [comment]
So I was wrong, it does fail reading parquet on 8.2 with 21.06.01 in normal read case, I missed the failure.

**Comment by tgravescs** [comment]
pr merged
