### ISSUE TITLE
Custom native code support for plugin

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#3196]
**Is your feature request related to a problem? Please describe.**
Increasingly there has been a desire to have Spark-specific behavior in cudf kernels, but cudf is not a library specific to the RAPIDS Accelerator and therefore should minimize Spark-specific behaviors.  However this does not diminish the need on the RAPIDS Accelerator side, and we have often implemented the required behaviors by hacking together a series of kernels which often uses much more memory and performs worse.
 
**Describe the solution you'd like**
We need the ability to provide native GPU code with Spark-specific behaviors.  Like cudf, I think we will always have a CUDA classifier in the jar containing native code.  With that in mind, I'd like to see the RAPIDS Accelerator become a single jar, rather than the plugin+cudf combo jars we have today, that contains everything needed to run the plugin with Spark, i.e.
- Scala and Java code for the plugin
- Plugin-specific native code and CUDA kernels
- corresponding cudf jar contents
 
**Describe alternatives you've considered**
We could keep cudf as a separate, user-visible dependency as we do today and have the RAPIDS Accelerator jar add a cuda classifier.  However once the RAPIDS Accelerator jar also has a classifier like cudf, I do not see any reason to continue to keep these jars separate and make mismatched plugin+cudf jar combinations a possibility.

**Comment by ttnghia** [comment]
Currently, this is added into Release 21.12. I personally think it would probably take more time as having this requires a lot of work and fundamentally changes a lot of things in our plugin project.

**Comment by ttnghia** [comment]
Maybe I overcomplicated things. Of course, it is great to have it in an easy way :smiley:
