### ISSUE TITLE
[FEA] Support GpuFirst and GpuLast on nested types under reduction aggregations

### ISSUE THREAD

**Issue by sperlingxx** [NVIDIA/spark-rapids#3221]
**Is your feature request related to a problem? Please describe.**
`GpuFirst` and `GpuLast` support nested types, but only in group by aggregations. They don't support nested types under reduction aggregations, because nested scalars are not supported by cuDF.

**Comment by Salonijain27** [comment]
cuDF PR https://github.com/rapidsai/cudf/pull/9043

**Comment by GaryShen2008** [comment]
@Salonijain27  Should we remove it from 21.10? It's not in PRD.

**Comment by sperlingxx** [comment]
https://github.com/rapidsai/cudf/pull/9759
