### ISSUE TITLE
[FEA] Add maven compile/package plugin executions, one for each supported Spark dependency version

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#3224]
**Is your feature request related to a problem? Please describe.**
This feature contributes to #3223. Each version-independent module. i.e. all the source code outside the shim parent module, should produce a separate specifier-differentiated artifact  using a specific spark artifact version as a dependency

**Describe the solution you'd like**
1. Add non-default profiles, 1 per shim version, consistently named across modules such that they can be activated consistently across modules. Define properties that can activated related profiles at the same time, e.g. -Dreleased31x activates all 3.1.x, reuse existing properties if possible.
2. In each profile configure scala compile plugin execution with the spark.version overridden correspondingly, it should use a dedicated class output directory that is then consumed by a packaging plugin to create an artifact such as `sql-plugin/target/rapids-4-spark-sql_2.12-21.10.0-SNAPSHOT-spark312.jar` if we take sql-plugin module as example. Compilation fixed is necessary to make source build against the target version.
3. If there is a dependency from on plugin submodule A to another B this should now use specifiers to make sure that the dependency is consistent with respect to the Spark version.
3. To make sure that the current build is not disrupted the main artifact (without the shim specifier) is still manufactured with spark301.version 

**Describe alternatives you've considered**
 CI  scripts can be run multiple times, once per Spark version . For each supported release 3.x.y of Spark run the full build with 
mvn -Dspark.version=3.x.y …
After each iteration extract the spark-rapids uber jar into a separate directory. This solution has a number of drawbacks:
- on the developer machines, we might accidentally install "wrong" versions in the local repo. 
- manual steps to remember
- need to make sure that each module actually allows overriding spark versions.

Breakdown of tasks:

- [x] Initial build framework - Spark 3.0.1 and spark3.0.2
- [x] Add other Apache Spark build framework and copy shims - Spark 3.0.x, 3.1.x, cdh, emr - https://github.com/NVIDIA/spark-rapids/pull/3277
- [x] Add build framework for databricks 3.0.1 and 3.1.1 shims
- [x] Add build framework for Spark 3.2.0
- [ ] Optionally add build framework for databricks 8.3 runtime (3.1.2+)

**Comment by tgravescs** [comment]
I got something similar to above working but it wasn't pretty due to various issues.  It also seems building multiple jars in a single module isn't really recommended. Based on this I think we will create profiles and just build 1 version of spark per maven invocation. For dist it will have to build multiple times and install the classifier jars and then pull from there.  

The other option is create multiple modules per existing modules for each spark version, similar to shims layer now but that seems like a lot of directories and not sure the benefit there.

**Comment by tgravescs** [comment]
Also note to do this without affect currently build, we will have to duplicate all the code in the shims where it was inheriting before.  ie spark 3.0.2 shim can't inherit from spark 3.0.1 shim so we have to copy that code  over.

**Comment by tgravescs** [comment]
3.2.0 pr: https://github.com/NVIDIA/spark-rapids/pull/3323
