### ISSUE TITLE
[FEA] Upgrade the ORC version

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#3227]
Our plugin is using ORC `1.5.8` currently, however Spark 3.0 and 3.1 are using ORC `1.5.10` and `1.5.12` separately.
It will be better to upgrade it to at least` 1.5.10`.

**Comment by GaryShen2008** [comment]
@Salonijain27 As I confirmed with Liangcai, this is not important to 21.10.
I target it into 21.12.
