### ISSUE TITLE
orc + zstd compression support[FEA]

### ISSUE THREAD

**Issue by sauravdev** [NVIDIA/spark-rapids#3240]
**Is your feature request related to a problem? Please describe.**
zstd compression is often used as compression ratio is approx 2x than snappy , so it saves a lot of cost when data is in petabyte scale

**Describe the solution you'd like**
support zstd compression for ORC 

**Describe alternatives you've considered**
NA

**Additional context**
https://nvidia.github.io/spark-rapids/docs/compatibility.html

**Comment by jlowe** [comment]
Thanks for the feature request!  In order for the RAPIDS Accelerator to support Zstandard for ORC it must be supported in cudf, as cudf provides the GPU backend for ORC reads and writes.  I filed cudf issues https://github.com/rapidsai/cudf/issues/9057 and https://github.com/rapidsai/cudf/issues/9058 to track Zstandard support for ORC reads and writes, respectively.

Note that implementing a performant GPU version of the Zstandard codec will take some time.  Once the support is available in cudf, it should be very straightforward to support it in the RAPIDS Accelerator for Apache Spark.

**Comment by jlowe** [comment]
This has been implemented.
