### ISSUE TITLE
Stop using cudf readCSV method that uses strings for data types

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#3248]
https://github.com/rapidsai/cudf/issues/8240 is in the process of removing the deprecated cudf methods for reading CSV that take strings as the data types.  Once https://github.com/rapidsai/cudf/issues/9062 is completed, we need to update the plugin to use the new CSV reading API that takes cudf data types as the arguments rather than strings.

**Comment by revans2** [comment]
So to be clear that API is a hidden detail.  The java APIs do not expose it.

**Comment by jlowe** [comment]
Then what's up with the `ai.rapids.cudf.Schema` class?  That sure looks like a class that is taking strings as data types, and it's only used by `Table.readCSV`.  `GpuColumnVector.from(StructType)` returns this, and `BatchScanExec` is using it to read CSV by converting a Spark schema into a cudf schema that has strings for data types.

**Comment by jlowe** [comment]
Ah, I see that all the String stuff in `Schema` is private, the only public methods take `DType`, so we should be good.
