### ISSUE TITLE
[FEA] Make CreateMap duplicate key handling compatible with Spark and enable CreateMap by default

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#3250]
**Is your feature request related to a problem? Please describe.**
In https://github.com/NVIDIA/spark-rapids/issues/3229 we added support for CreateMap with multiple key-value pairs e.g. `map(key1, value1, key2, value2)`. We had to add a config flag to enable this option because our handling of duplicate values is not compatible with Spark.

**Describe the solution you'd like**
It would be nice if we could make duplicate handling compatible with Spark and enable CreateMap by default. See conversation at https://github.com/NVIDIA/spark-rapids/pull/3230#discussion_r689641323 for more information.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by revans2** [comment]
I closed rapidsai/cudf#9123 because after discussion on the issue we determined that we can do this today. It might not be the most optimal, but it should work.  The following pseudo-ish code should do it.

```
withResource(extractKeysFrom(mapCol)) { keyListView =>
    val dedupeCountCol = withResource(keyListView.dropDuplicates()) { dupsDropped =>
        dupsDropped.countElements()
    }
    val sameLengthCol = withResource(dedupeCountCol) { dedupeCountCol =>
        withResource(keyListView.countElements()) { origCount =>
           origCount.equals(dedupeCountCol)
        }
    }
    withResource(sameLengthCol) { sameLengthCol =>
        withResource(sameLengthCol.all()) { allSame =>
             allSame.getBoolean()
        }
    }
}
```
