### ISSUE TITLE
[AUDIT]  Spark 3.2 [SPARK-34859][SQL] Handle column index when using vectorized Parquet reader

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3265]
**Describe the bug**
https://issues.apache.org/jira/browse/SPARK-34859
https://github.com/apache/spark/commit/a5c886619dd1573e96bbba058db099b47f0c147c

Spark changed the vectorized parquet reader api in Spark 3.2

**Comment by tgravescs** [comment]
I was mistaken on the CDH version, it seem it has a different parameter then added in SPARK-34859, splitting that apart

**Comment by revans2** [comment]
The details here are important.  The new feature in Parquet 1.11/Spark 3.2 is a column index at a page level.  Spark uses this to filter out pages that it does not need to decode as a part of predicate push down.  The Spark columnar code reads the columns independently. Before this fix it tried to use the result of a predicate push down on one column (the columnar index) to skip pages in other columns. But the pages do not always align with each other, so one column's page index cannot be used directly to filter out pages for other columns.

Our predicate push down code works on a block level, not a page level.  Blocks are guaranteed to be aligned so they can be split independently.  This is why we don't need to worry about this right now. I am going to put in the tests, just so we can be sure that it stays working.
