### ISSUE TITLE
Scala collection issue occurring data transfer from plugin to spark 

### ISSUE THREAD

**Issue by ankushbindra** [NVIDIA/spark-rapids#329]
We are tried to run spark shell using following jars but it throws exception while reading any dataframe.

- cudf-0.15-20200701.080958-3-cuda10-1.jar
- rapids-4-spark_2.12-0.2.0-SNAPSHOT.jar

exception occur **java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.v2.csv.CSVScan,partitionFilters()()Lscala/collection/Seq**;

![image](https://user-images.githubusercontent.com/19852416/86912071-eada3400-c14e-11ea-9976-8de7660faf6d.png)

But if we remove property --conf spark.plugins=com.nvidia.spark.SQLPlugin from spark shell command then same code is working fine. We are running spark 3.0. Can you please help us to get this done.

Regards,
Ankush

**Comment by revans2** [comment]
@ankushbindra Are you sure that you are running with spark 3.0?  The missing API that the JVM is complaining about was added as a part of https://issues.apache.org/jira/browse/SPARK-30475 and went into spark at the end of January.  You might be on a preview release, or you might be on a runtime that is based on apache spark but is slightly different that we don't support yet.

**Comment by ankushbindra** [comment]
@revans2  thanks for you update on the same. Sure I will check spark 3 version but I got this code reference from spark example with rapidsai. When I tried to check spark 3 version code. Some jars reference, I am not able to find on internet and their repository URL mentioned is https://gpuwa.nvidia.com/artifactory/sw-spark-maven which does not resolve and says host not found. You can see their reference on https://github.com/rapidsai/spark-examples/blob/support-spark3.0/examples/apps/scala/pom.xml . Can you please help if it is correct repository URL?

![image](https://user-images.githubusercontent.com/19852416/86925110-f9cae180-c162-11ea-9bea-e5ac39f5752e.png)

**Comment by revans2** [comment]
Sorry about that.  We are still in the process of migrating from internal repositories to external ones.  You should be able to use the official spark release as described [here](https://nvidia.github.io/spark-rapids/docs/getting-started.html)

@GaryShen2008 what is being done to get the XGBoost code to compile outsize of the firewalls? We really need to be sure that it works out of the box.

**Comment by ankushbindra** [comment]
@revans2 , thanks for your support. We are able to run it using update spark versio 3.0. But we want to run sample code specified on https://github.com/rapidsai/spark-examples/tree/support-spark3.0 and it need _ai.rapids_xgboost4j_3.0_1.0.0-SNAPSHOT.jar_ and _ai.rapids_xgboost4j-spark_3.0_1.0.0-SNAPSHOT.jar_. Can you please share some link how we build those jars at end or can download from some public repository?

**Comment by revans2** [comment]
@ankushbindra could you try out https://github.com/NVIDIA/spark-xgboost-examples instead.  The repository has moved.

**Comment by ankushbindra** [comment]
@revans2 sure we can try this. Right now we are trying to run simple join on dataframe. But we are getting exception **could not load cuda jni library** on executor side. Can you please help if we are missing some thing.

![image](https://user-images.githubusercontent.com/19852416/87044491-29dcb800-c229-11ea-8ce4-905958217fda.png)

![image](https://user-images.githubusercontent.com/19852416/87044824-aa9bb400-c229-11ea-8674-68906fa5dc53.png)

**Comment by revans2** [comment]
`rmm` is the first library that we load into the JVM.  It looks like `libnvToolsExt` is the first library from the cuda tool kit that we load in rmm.

```
$ ldd amd64/Linux/librmm.so 
	linux-vdso.so.1 (0x00007fffbd382000)
	libnvToolsExt.so.1 => /usr/local/cuda-10.1/lib64/libnvToolsExt.so.1 (0x00007f9bb082e000)
	libcudart.so.10.1 => /usr/local/cuda-10.1/lib64/libcudart.so.10.1 (0x00007f9bb05b2000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f9baf391000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9baf008000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9baec6a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9baea52000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9bae661000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9bae45d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9bae23e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9bae036000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9bb0c3e000)
```

What version of cuda do you have installed on your executor nodes?  Where is it installed?  You might need to set LD_LIBRARY_PATH to find it.

```
$ echo $LD_LIBRARY_PATH
/usr/local/cuda-10.1/lib64
```

If that is true then we should update the documentation better.
