### ISSUE TITLE
[FEA] hypot SQL function

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#33]
**Is your feature request related to a problem? Please describe.**
would be really great to support the SQl function hypot.  We can probably do it initially with just 
```
sqrt((lhs * lhs) + (rhs * rhs))
```

This might not be good enough with overflows etc and we may need to look a little deeper in how to support it.

**Comment by NVnavkumar** [comment]
There are some equivalent forms that avoid overflow/underflow (see https://en.wikipedia.org/wiki/Pythagorean_addition). Will explore.

**Comment by revans2** [comment]
To be clear we have not tested for overflow etc in this at all to know what we can/should do.  The Spark code is using the java built in `Math.hypot`

https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#hypot-double-double-

Which indicates that it takes care of avoiding intermediate overflow and underflow. I am not sure how critical it is when Spark only supports Doubles as input, but it would be good to know.

**Comment by NVnavkumar** [comment]
It does look like the naive algorithm is much more prone to overflow because of the squares, I think we can use:

x * sqrt(1 + (y/x)^2), where x = max(abs(lhs), abs(rhs)) and y = min(abs(lhs), abs(rhs))
