### ISSUE TITLE
[BUG]Mortgage ETL input_file_name is not correct when using CPU's CsvScan

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#3333]
**Describe the bug**
When reading CVS without settting "--conf spark.rapids.sql.csv.read.long.enabled=true", the "quarter" column in Mortgage ETL will show empty value when selecting multiple columns, but it can be shown correctly when only selecting itself.
Related bug: https://github.com/NVIDIA/spark-rapids-examples/issues/15

**Steps/Code to reproduce bug**
The code is [XGBoostETL.scala](https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.08/examples/mortgage/scala/src/com/nvidia/spark/examples/mortgage/XGBoostETL.scala)

spark-shell --master spark://master_ip:7077 --conf spark.plugins=com.nvidia.spark.SQLPlugin --executor-memory 10G --executor-cores 5 --driver-memory 4G --conf spark.cores.max=5 --conf spark.executor.resource.gpu.amount=1 --conf spark.task.cpus=1 --conf spark.rapids.sql.incompatibleDateFormats.enabled=true

``` scala
scala> :paste

import org.apache.spark.sql.expressions.Window
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.apache.spark.sql.{Column, DataFrame, SparkSession}

object GetQuarterFromCsvFileName {
  // The format is path/TYPE_yyyy\QQ.txt followed by a (_index)* where index is a single digit number [0-9]
  // i.e. mortgage/perf/Performance_2003Q4.txt_0_1
  // So we strip off the .txt and everything after it
  // and then take everything after the last remaining _
  def apply(): Column = substring_index(
    substring_index(input_file_name(), ".", 1), "_", -1)
}

object CsvReader {

  def readPerformance(spark: SparkSession, paths: Seq[String], optionsMap: Map[String, String]): DataFrame = {
    val performanceSchema = StructType(Array(
      StructField("loan_id", LongType),
      StructField("monthly_reporting_period", StringType),
      StructField("servicer", StringType),
      StructField("interest_rate", DoubleType),
      StructField("current_actual_upb", DoubleType),
      StructField("loan_age", DoubleType),
      StructField("remaining_months_to_legal_maturity", DoubleType),
      StructField("adj_remaining_months_to_maturity", DoubleType),
      StructField("maturity_date", StringType),
      StructField("msa", DoubleType),
      StructField("current_loan_delinquency_status", IntegerType),
      StructField("mod_flag", StringType),
      StructField("zero_balance_code", StringType),
      StructField("zero_balance_effective_date", StringType),
      StructField("last_paid_installment_date", StringType),
      StructField("foreclosed_after", StringType),
      StructField("disposition_date", StringType),
      StructField("foreclosure_costs", DoubleType),
      StructField("prop_preservation_and_repair_costs", DoubleType),
      StructField("asset_recovery_costs", DoubleType),
      StructField("misc_holding_expenses", DoubleType),
      StructField("holding_taxes", DoubleType),
      StructField("net_sale_proceeds", DoubleType),
      StructField("credit_enhancement_proceeds", DoubleType),
      StructField("repurchase_make_whole_proceeds", StringType),
      StructField("other_foreclosure_proceeds", DoubleType),
      StructField("non_interest_bearing_upb", DoubleType),
      StructField("principal_forgiveness_upb", StringType),
      StructField("repurchase_make_whole_proceeds_flag", StringType),
      StructField("foreclosure_principal_write_off_amount", StringType),
      StructField("servicing_activity_indicator", StringType))
    )
    
    spark.read
      .options(optionsMap)
      .option("nullValue", "")
      .option("delimiter", "|")
      .option("parserLib", "univocity")
      .schema(performanceSchema)
      .csv(paths: _*)
      .withColumn("quarter", GetQuarterFromCsvFileName())
  }
}
val optionsMap = Map("header" -> "False")
val perfPaths = Seq("/data/jars/dataset/mortgage/raw/perf")
val perfDf = CsvReader.readPerformance(spark, perfPaths, optionsMap)

scala> perfDf.select(col("quarter"), col("loan_id")).show()
+-------+------------+
|quarter|     loan_id|
+-------+------------+
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
|       |100007365142|
+-------+------------+
only showing top 20 rows

scala> perfDf.select(col("quarter")).show()
+-------+
|quarter|
+-------+
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
| 2000Q1|
+-------+
only showing top 20 rows
```
**Expected behavior**
scala> perfDf.select(col("quarter"), col("loan_id")).show()
Should also show the correct value of column "quarter".

**Environment details (please complete the following information)**
 - Standalone cluster, single GPU, plugin v21.08.0, cudf v21.08.2, cuda 11.2
 - It can't be reproduced when adding "--conf spark.rapids.sql.csv.read.long.enabled=true" as below since loan_id is long type.
  spark-shell --master spark://10.19.183.153:7077 --conf spark.plugins=com.nvidia.spark.SQLPlugin --executor-memory 10G --executor-cores 5 --driver-memory 4G --conf spark.cores.max=5 --conf spark.executor.resource.gpu.amount=1 --conf spark.task.cpus=1 --conf spark.rapids.sql.incompatibleDateFormats.enabled=true --conf spark.rapids.sql.csv.read.long.enabled=true
But if you use another column "interest_rate"(Double type), it also requires to set spark.rapids.sql.csv.read.double.enabled=true.

**Comment by wbo4958** [comment]
This is the minimum repro code and data,

``` scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

      import spark.sqlContext.implicits._

      import org.apache.spark.sql.functions._
      import org.apache.spark.sql.types._

      val writeDf = Seq((1, 2), (3, 4)).toDS()
      writeDf.repartition(1).write.csv("/tmp/csv")

      val schema = StructType(
        Seq(
          StructField("a", IntegerType),
          StructField("loan_id", LongType)
        )
      )

      val optionsMap = Map("header" -> "False")
      val df = spark.read
        .options(optionsMap)
        .option("nullValue", "")
        .option("parserLib", "univocity")
        .schema(schema)
        .csv("/tmp/csv/")
        .withColumn("quarter", input_file_name())

      val dff = df.select(col("quarter"), col("loan_id"))
      dff.explain(true)
      dff.show(false)

// Exiting paste mode, now interpreting.

21/08/30 12:14:02 WARN GpuOverrides: 
!Exec <DataWritingCommandExec> cannot run on GPU because not all data writing commands can be replaced
  !Output <InsertIntoHadoopFsRelationCommand> cannot run on GPU because CSV output is not supported
  !Exec <ShuffleExchangeExec> cannot run on GPU because Columnar exchange without columnar children is inefficient
    @Partitioning <RoundRobinPartitioning> could run on GPU
    !NOT_FOUND <LocalTableScanExec> cannot run on GPU because no GPU enabled version of operator class org.apache.spark.sql.execution.LocalTableScanExec could be found
      @Expression <AttributeReference> _1#2 could run on GPU
      @Expression <AttributeReference> _2#3 could run on GPU

21/08/30 12:14:02 WARN GpuOverrides: 
*Exec <ProjectExec> will run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> input_file_name() AS quarter#16 will run on GPU
      *Expression <InputFileName> input_file_name() will run on GPU
    !Exec <FileSourceScanExec> cannot run on GPU because CSV reading is not 100% compatible when reading longs. To enable it please set spark.rapids.sql.csv.read.long.enabled to true.

== Parsed Logical Plan ==
'Project [unresolvedalias('quarter, None), unresolvedalias('loan_id, None)]
+- Project [a#12, loan_id#13L, input_file_name() AS quarter#16]
   +- Relation[a#12,loan_id#13L] csv

== Analyzed Logical Plan ==
quarter: string, loan_id: bigint
Project [quarter#16, loan_id#13L]
+- Project [a#12, loan_id#13L, input_file_name() AS quarter#16]
   +- Relation[a#12,loan_id#13L] csv

== Optimized Logical Plan ==
Project [quarter#16, loan_id#13L]
+- Project [loan_id#13L, input_file_name() AS quarter#16]
   +- Relation[a#12,loan_id#13L] csv

== Physical Plan ==
GpuColumnarToRow false
+- GpuProject [quarter#16, loan_id#13L]
   +- GpuProject [loan_id#13L, input_file_name() AS quarter#16]
      +- GpuRowToColumnar targetsize(2147483647)
         +- FileScan csv [loan_id#13L] Batched: false, DataFilters: [], Format: CSV, Location: InMemoryFileIndex[file:/tmp/csv], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<loan_id:bigint>

21/08/30 12:14:02 WARN GpuOverrides: 
!Exec <CollectLimitExec> cannot run on GPU because the Exec CollectLimitExec has been disabled, and is disabled by default because Collect Limit replacement can be slower on the GPU, if huge number of rows in a batch it could help by limiting the number of rows transferred from GPU to CPU. Set spark.rapids.sql.exec.CollectLimitExec to true if you wish to enable it
  @Partitioning <SinglePartition$> could run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> cast(loan_id#13L as string) AS loan_id#25 will run on GPU
      *Expression <Cast> cast(loan_id#13L as string) will run on GPU
    *Exec <ProjectExec> will run on GPU
      *Expression <Alias> input_file_name() AS quarter#16 will run on GPU
        *Expression <InputFileName> input_file_name() will run on GPU
      !Exec <FileSourceScanExec> cannot run on GPU because CSV reading is not 100% compatible when reading longs. To enable it please set spark.rapids.sql.csv.read.long.enabled to true.

+-------+-------+
|quarter|loan_id|
+-------+-------+
|       |2      |
|       |4      |
+-------+-------+
```

Rapids plugin can't replace FileScan-csv since incompatible long type. So, A new GpuRowToColumnar
is inserted to convert the Rows to the ColumnarBatch. In fact, the generated SpecificUnsafeRowToColumnarBatchIterator iterators over all Rows (From FileScanRDD) and convert to ColumnarBatch.

The iterator model of FileScanRDD is trying to read each row of each file sequentially. When FileScanRDD is reading 1 single file, it will set the current reading file name into the global static variable by `InputFileBlockHolder.set`. After finishing reading, InputFileBlockHolder will clear the static variable.

For input_file_name expression, Spark itself expects that the following operators can get the input file name
 from the global static variable by `InputFileBlockHolder.getInputFilePath` while the operators are handling one single row.

So the issue here is GpuRowToColumnar has looped over all files while getting input_file  are triggered in the following GpuProject operator.

**Comment by wbo4958** [comment]
The solution I can think of is splitting the files into different ColumnBatch in GpuRowToColumnar.

add a condition [here](https://github.com/NVIDIA/spark-rapids/blob/branch-21.10/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala#L598)  that compares if the current input file is equal to the previous input file.  If no, just break the loop, and generate ColumnBatch for the current file.

@revans2 @jlowe  Could you help to provide some ideas on this?

**Comment by revans2** [comment]
We disabled almost all the CSV parsing by default because we could not guarantee correct parsing in the corner cases.  You should be able to re-enable it with some configs.

https://github.com/NVIDIA/spark-rapids/blob/5290586fc49726963dc1282f62ebc2522cc3573e/sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala#L856-L900

The long-term plan is to tell CUDF to parse everything in the CSV as strings and then do the correct casting logic to turn them into the correct type. Spark uses the same code to cast strings to values as it does to parse them in CSV. But the String casting code we have right now is not complete and needs some performance improvements.  To make it work the way we want we are probably going to have to write customer kernels and for that we will need https://github.com/NVIDIA/spark-rapids/issues/3196. I wish it were a simple solution to make this work out of the box.




________________________________

**Comment by revans2** [comment]
Yes we should fix that. GpuTransitionOverrides should be doing this already and I thought we had tests for it. the method `disableCoalesceUntilInput` on GpuExpression is supported to inform the code not to coalesce batches.

**Comment by wbo4958** [comment]
Hi @revans2 

I just searched the input_file_name test cases and run it,

``` console
*Exec <ProjectExec> will run on GPU
  *Expression <Alias> input_file_name() AS input_file_name()#58 will run on GPU
    *Expression <InputFileName> input_file_name() will run on GPU
  *Expression <Alias> input_file_block_start() AS input_file_block_start()#59L will run on GPU
    *Expression <InputFileBlockStart> input_file_block_start() will run on GPU
  *Expression <Alias> input_file_block_length() AS input_file_block_length()#60L will run on GPU
    *Expression <InputFileBlockLength> input_file_block_length() will run on GPU
  *Exec <FilterExec> will run on GPU
    *Expression <And> (isnotnull(a#52L) AND (a#52L > 0)) will run on GPU
      *Expression <IsNotNull> isnotnull(a#52L) will run on GPU
      *Expression <GreaterThan> (a#52L > 0) will run on GPU
    *Exec <BatchScanExec> will run on GPU
      *Input <CSVScan> will run on GPU

PASSED          [ 50%]
../../src/main/python/csv_test.py::test_input_meta_xxx[csv] 21/08/30 22:13:36 WARN GpuOverrides: 
*Exec <ProjectExec> will run on GPU
  *Expression <Alias> input_file_name() AS input_file_name()#102 will run on GPU
    *Expression <InputFileName> input_file_name() will run on GPU
  *Expression <Alias> input_file_block_start() AS input_file_block_start()#103L will run on GPU
    *Expression <InputFileBlockStart> input_file_block_start() will run on GPU
  *Expression <Alias> input_file_block_length() AS input_file_block_length()#104L will run on GPU
    *Expression <InputFileBlockLength> input_file_block_length() will run on GPU
  *Exec <FilterExec> will run on GPU
    *Expression <And> (isnotnull(a#96L) AND (a#96L > 0)) will run on GPU
      *Expression <IsNotNull> isnotnull(a#96L) will run on GPU
      *Expression <GreaterThan> (a#96L > 0) will run on GPU
    *Exec <FileSourceScanExec> will run on GPU

PASSED       [100%]
```

The test case can pass because FileSourceScanExec **can run** on GPU.

Looks like the issue here is that FileSourceScanExec **can't** run on GPU, GpuRowToColumnar will be inserted to iterator all rows of all files into a ColumnarBatch beforehand, which will overwrite and unset InputFileBlockHolder before getting input_file_name in GpuProjectExec.

**Comment by revans2** [comment]
That makes sense and is a bug that I missed when I wrote this code :(

```
FileScan -> GpuRowToColumnar -> GpuProject(input_file_name())
```

Because the `FIleScan` is on the CPU we don't know when to split up the rows in the batch so that the `input_file_name` can work properly. The only way to make this happen is to force everything to be on the CPU between the `FileScan` and the `input_file_name`. If the `FileScan` is on the CPU.

Longer term I think we need to change how Spark works for this and have these be a part of FIleScan itself. There would need to be rules that would push `input_file_name` etc all the way up into FileScan and they would come out as columns on the rows there. If it is unable to push it up that high, for whatever reason, we have a config that either inserts a null literal there for backwards compatibility or returns an error.
