### ISSUE TITLE
[DOC] Instructions to setup IDEs

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3338]
With some of the more recent changes my IDE setup stopped working and started to show compile errors.  This is because I had to select specific maven profiles to make it happy. The only reason I knew this was because I was following along with many of the build changes.  We really should have clear instructions about how to set up an IDE, including what maven profiles to enable/disable in specific situations.

**Comment by sameerz** [comment]
We need to update https://github.com/NVIDIA/spark-rapids/blob/branch-21.10/docs/dev/README.md ( which gets displayed at https://nvidia.github.io/spark-rapids/developer-overview/  ) after we complete the Spark 3.2 shim work.
