### ISSUE TITLE
Automated testing CDP

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3360]
**Is your feature request related to a problem? Please describe.**
Figure out if we can run some sort of automated testing on CDP.  

In the very least be able to do it at release time to make sure we don't miss any of our regular testing:

- [X] integration tests (including the cache test)
- [x] integration tests (udf testing)
- [x] profiling tool testing
- [ ] qualification tool testing
- [X] ucx/shuffle testing

**Comment by sameerz** [comment]
Moving to 22.02 as we did not end up setting up automated CDP testing in 21.12, will continue to manually test this distribution.

**Comment by GaryShen2008** [comment]
We're trying to get the information about where to get the package and how to set up the CDP cluster. Also we need to request the instances. I think it'll take some times.

**Comment by GaryShen2008** [comment]
@zhanga5 I think we have the CDP test CI job. Can we close this issue?

**Comment by zhanga5** [comment]
yes, CI job was created and enabled weekly run for integration test on CDP including ucx/shuffle testing, however, still missing `profiling and qualification tool testing` and `udf testing` probably

**Comment by GaryShen2008** [comment]
Move to 22.06 to finish the profiling and udf testing.

**Comment by zhanga5** [comment]
now `udf testing` is included from weekly CI job and also would trigger profiling tool testing to test event logs generated from integration testing. Qualification tool testing is not included currently because it can't support GPU event logs. Not sure whether there's issue to track this (@tgravescs please help provide issue info if yes or I can create one if need)

**Comment by sameerz** [comment]
Closing, as the qualification and profiling tool validation is tracked in another issue.
