### ISSUE TITLE
Audit: SPARK-36217: CustomShuffleReaderExec renamed

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3362]
**Is your feature request related to a problem? Please describe.**
https://issues.apache.org/jira/browse/SPARK-36217

Renamed customerShuffleReaderExec which we look for for AQE Stuff:
https://github.com/apache/spark/commit/a77c9d6d1726ee6cacc8bb457c4df02e3f16231b#diff-6016c0f4838a0b2de3dd06855e3721c5e32f5ddc5dd47a57394cdb4d71d1e636

**Comment by tgravescs** [comment]
We may have fixed this with https://github.com/NVIDIA/spark-rapids/pull/3323/files, I missed it originally, but double check.

**Comment by gerashegalov** [comment]
right, this has been addressed in the prototype as soon as it went in July. All compile time issues like these renames are handled by #3323
