### ISSUE TITLE
[BUG] analysis tool cannot handle a job with no tasks.

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3364]
**Describe the bug**
In `Analysis.jobAndStageMetricsAggregation` there is a bunch of code to do aggregations and they all have this Option pattern when doing the aggregations.  But the problem is Option only becomes a None if a null is passed in. We are not passing in nulls in this case, we are passing in an empty ArrayBuffer if there are no tasks. For the sum aggregations it is not a problem and they still output 0 when summing an empty list.  But for max it throws an error. We need an alternative way to compute the max and return 0 when there are no values.  The Option code is doing nothing because there is no way to return a null from `tasksInJob.map(_.SOMETHING)` if tasksInJob is empty you get an empty list. If it is null you get an NPE from trying to call map on it.

**Comment by tgravescs** [comment]
this is actually fixed in https://github.com/NVIDIA/spark-rapids/pull/3342.. well at least the option pattern thing.

We should test with that patch.

**Comment by revans2** [comment]
I just tested with #3342 and it does fix this.
