### ISSUE TITLE
[FEA] Add support for Databricks 9.1 runtime

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3370]
**Is your feature request related to a problem? Please describe.**
Support databtricks 8.3 runtime.  It had some patches from spark 3.2 so we need those build changes first from https://github.com/NVIDIA/spark-rapids/issues/3224

**Comment by sameerz** [comment]
Changing this issue to support 9.1 since that will be a long term support release version.  We might do this as a patch to 21.10 or in 21.12.  Moving to 21.12 for now.
