### ISSUE TITLE
[BUG] minor deprecation warnings in a 3.2 shim build

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#3374]
**Describe the bug**
```
[WARNING] [Warn] GpuMultiFileReader.scala:87: method getAllStatistics in class FileSystem is deprecated: see corresponding Javadoc for more information.

[WARNING] [Warn] sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuParquetScan.scala:604: method getDecimalMetadata in class PrimitiveType is deprecated: see corresponding Javadoc for more information.

[WARNING] [Warn] sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala:121: method isDirectory in class FileSystem is deprecated: see corresponding Javadoc for more information.
```

**Steps/Code to reproduce bug**
```
$ mvn clean package -Dbuildver=320 -Dskip -DskipTests -pl integration_tests -am 
```

**Expected behavior**
build free of deprecation warnings

**Environment details (please complete the following information)**
local

**Additional context**
#3323

**Comment by jlowe** [comment]
These new warnings with 3.2 imply that we're not compiling against the Parquet jars that we're explicitly shading and including in the distribution jar.  Seems like there's an issue with the pom where we should be excluding the Parquet version Spark wants so we can use the version we bundle explicitly.

**Comment by res-life** [comment]
@gerashegalov Cannot find the warnings, please double check.

**Comment by gerashegalov** [comment]
After #4071 we no longer allow new warnings to be introduced without explicitly silencing them when necessary as part of the PR under review. Existing warnings are silenced, so this issue is now about looking into reducing the usage of  `@scala.annotation.nowarn`
