### ISSUE TITLE
[BUG] maven scalastyle checks don't appear to work for alterneate source directories

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3388]
**Describe the bug**
I have noticed a few bugs in the scala style that the IDE picks up on in the 20.10

https://github.com/NVIDIA/spark-rapids/blob/f774e1a231416aab7cacc86f06010ef797fc19c7/sql-plugin/src/main/spark320/scala/com/nvidia/spark/rapids/shims/v2/Spark32XShims.scala#L23
`There should be no empty line separating imports in the same group.`

and

https://github.com/NVIDIA/spark-rapids/blob/f774e1a231416aab7cacc86f06010ef797fc19c7/sql-plugin/src/main/spark320/scala/org/apache/spark/rapids/shims/v2/GpuShuffleBlockResolver.scala#L17
`Package name 'org.apache.spark.sql.rapids.shims.v2' does not correspond to the file path 'org.apache.spark.rapids.shims.v2' `

are some examples of this.

It looks like the scala style plugin is ignoring additional source code directories.

**Comment by gerashegalov** [comment]
scalastyle  maven plugin has the following short comings:
- it checks all files in the configured directories even if we don't change them slowing down the build significantly
- it doesn't see non-default source code root additions
- the violation in a module that is built late won't be revealed until this module is built and is usually blended with other output so it's hard to locate.

I propose we replace the scalastyle plugin  invocation and call the style check only on changed files via a script to the tune of:

```bash
git diff --name-only origin/branch-21.10...HEAD | grep '.scala$' | xargs java -jar ~/dist/scalastyle_2.12-1.0.0-batch.jar -c scalastyle-config.xml
```

If we find a way to invoke scalastyle using scala:run in maven we should be able to avoid explicit download of the batch cli

**Comment by revans2** [comment]
I am not trilled with the idea of rolling our own. Especially one that is aware of the version control system. I thought one of the first rules of the build system is that it should not depend on the VCS of the code, or else it fails to build when you switch VCS or just get the raw code from somewhere.  If we go this route we need to make sure that if the source code is not in git that it falls back to doing something reasonable. I also want to be sure that it will run by default as a part of the build. I personally would rather see us spend time to try and fix issue with the maven plugins in open source. But in the interest of time I can see why we might not go that route.

**Comment by gerashegalov** [comment]
The total time scalastyle takes is only 8 seconds (at least after consolidating it into a single  JVM invocation), so I think it's fine to leave it at that. In general having pre-commit checks like scalastyle executing only on files the developer changed is well within rules in my experience.

**Comment by revans2** [comment]
The difference is pre-commit check vs build. Pre-commit is a part of the version control system. Having it rely on the exact VCS in my opinion is fine, because it goes along with the VCS and is optional. The build system itself should be generic enough to build under any version control system or none at all. Otherwise it is a huge pain for someone to fork the software and use their preferred or employer mandated VCS.

But this brings up a separate point. Is style something that we want everyone to run or is it just those developers hard core enough to add the pre-commit hooks.  In my opinion small errors show up all the time and if are going to enforce it as a part of a pre-merge build we should be giving users an early warning and pre-commit hooks are not good enough for that. But that is just me and if the project goes all in on pre-commit hooks I could be persuaded. But from the previous discussions I don't think all of the team is the same way.

**Comment by gerashegalov** [comment]
Personally I'd like to not spend any time manually fixing  code style violations. Equally I'd like to not have code style discussed in the PR reviews. 

Personally I almost enjoy how my cudf PR submission gets auto-formatted in [cudf using a pre-commit hook](https://github.com/rapidsai/cudf/blob/branch-21.10/.pre-commit-config.yaml#L49), so I don't need to think about the arbitrary rules at all when I edit the code. 

One of typical counterpoints is that commit hooks are optional. But this is easily resolved via PR-checks in CI. Moreover instead of failing the PR check we can simply have  a CI job  reformatting, testing and merging approved PRs
