### ISSUE TITLE
[FEA] widen the rendered Jekyll pages

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#340]
The current `configs.html` (from `configs.md`) has scrollers to deal with the wide _Expressions_ table. I think we can probably make the site centered-left, and make the right pane fluid so it fills the rest of the page. Note that we are adding a column to this table, so it'll just get wider.

https://nvidia.github.io/spark-rapids/docs/configs.html

**Comment by sameerz** [comment]
I did some research on the sidebar width.  It is possible to reduce the sidebar.  It is difficult to reduce the sidebar to make the last column in the [Supported GPU Operators and Fine Tuning](https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/docs/configs.md#supported-gpu-operators-and-fine-tuning) section completely visible.  

The following settings in the _sass/color_schemes/emerald.scss theme file (which only exists in the gh-pages branch) get us close: 

$content-width: 1000px;
$nav-width: 264px;

Here is a brief explanation of what these do:

> For screen widths minimum 66.5rem, the .side-bar width is the (width of the parent element minus the $nav-width + $content-width ) / 2 plus the $nav-width
> To reduce the sidebar increase the $content-width variable, which is defined as 800px by default
> See also https://github.com/pmarsceill/just-the-docs/blob/master/_sass/layout.scss for the definition of .side-bar and the custom.scss file for default variable values
> The generated value in just-the-docs-default.css will be: 
> `@media (min-width: 66.5rem) { .side-bar { width: calc((100% - 1264px) / 2 + 264px); min-width: 264px; } }`
> 

Below are screenshots comparing the before and after width in jekyll on a 1280x800 display.  An alternative to address the problem with the *Expressions* table is to put the notes, which are very long but infrequent, as footnotes to the table.   

<img width="1280" alt="Screen Shot 2020-08-27 at 11 19 44 PM" src="https://user-images.githubusercontent.com/7036315/91528180-0692c880-e8bc-11ea-87aa-f942669325f0.png">

<img width="1280" alt="Screen Shot 2020-08-27 at 11 20 44 PM" src="https://user-images.githubusercontent.com/7036315/91528209-1a3e2f00-e8bc-11ea-9ac8-2e0c7ccbeaa0.png">
