### ISSUE TITLE
Release Checklist for 21.10

### ISSUE THREAD

**Issue by Salonijain27** [NVIDIA/spark-rapids#3402]
Release Checklist for v21.10:

| Status  | Task | Start | End | Owner| 
| ------------- | ------------- | ------------- | ------------- | ------------- | 
|**Pre-release**| | | | |
|<ul><li>- [X] </li></ul> | Notification to team of last feature sprint in milestone 2021-08-30 - 2021-09-10 | 2021-08-30 | 2021-09-10 | @sameerz| 
|<ul><li>- [X] </li></ul> | Burndown (no new features for current release) | 2021-09-13 | 2021-09-24 | Team|  
|<ul><li>- [X] </li></ul> | Update docs for current release in spark-rapids | 2021-09-20| 2021-09-24 | Team| 
|<ul><li>- [X] </li></ul> | Get RAPIDS 21.12 cudf java build working.  | 2021-09-23 | 2021-09-27 | @pxLi | 
|<ul><li>- [X] </li></ul> | Create 21.12 branch | 2021-09-17 | 2021-09-18 | @pxLi | 
|<ul><li>- [X] </li></ul> | Automerge from 21.10 to 21.12 | 2021-09-17 | 2021-09-18 | @pxLi | 
|<ul><li>- [X] </li></ul> | Enable Jenkins builds (premerge, nightly, integration, performance) for 21.12 | 2021-09-18 | 2021-09-28 | @pxLi | 
|<ul><li>- [X] </li></ul> | Virtual review | 2021-10-08 | 2021-10-15 |@krajendrannv | 
|<ul><li>- [X] </li></ul> | [cudf 21.10] Java release to sonatype | 2021-10-08 | 2021-10-08 | @NvTimLiu | 
|<ul><li>- [X] </li></ul> | Notify RAPIDS team of javadocs for 21.10 | 2021-10-11 | 2021-10-12 | @GaryShen2008 | 
|**Staging release**||||
|<ul><li>- [X] </li></ul> | Make 21.12 the default branch | 2021-10-04 | 2021-10-04 | @jlowe | 
|<ul><li>- [X] </li></ul> | Merge all remaining branch-21.10 PRs | 2021-09-24 | 2021-09-24 | Team | 
|<ul><li>- [X] </li></ul> | Create CHANGELOG.md | 2021-09-24 | 2021-09-24 | @pxLi | 
|<ul><li>- [X] </li></ul> | Deliver Snapshot packages to QA | 2021-09-24 | 2021-09-24 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Create a PR (not squashed) to merge from branch-21.10 to main. Needs review from repository owner | 2021-10-08 | 2021-10-08 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Trigger the release Jenkins job on the main branch and deploy the jar to sonatype staging | 2021-10-11 | 2021-10-18 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Deliver final packages to QA | 2021-10-18 | 2021-10-18 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Run integration tests on staging jars with AQE on, UCX on, Databricks Azure, Databricks AWS, Dataproc | 2021-10-18 | 2021-10-22 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Run LHA tests on staging jars | 2021-10-18 | 2021-10-22 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | QA testing with Snapshot on YARN, NGC with Volta and Ampere | 2021-10-04 | 2021-10-15 | @yuange98|  
|<ul><li>- [X] </li></ul> | Run pre-processing workflow for [DLRM sample use case](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Recommendation/DLRM#advanced)| 2021-10-18 | 2021-10-22 | @johnzhong |  
|<ul><li>- [X] </li></ul> | QA testing with final packages on YARN, NGC with Volta and Ampere | 2021-10-18 | 2021-10-22 | @yuange98|  
|**Release**| | | | |  
|<ul><li>- [X] </li></ul> | Tag the release and deploy the staging artifacts to maven central repository | 2021-10-28 | 2021-10-28 | @NvTimLiu|
|<ul><li>- [X] </li></ul> | CDH testing | 2021-10-25 | 2021-10-28 | @tgravescs | 
|<ul><li>- [X] </li></ul> | Update gh-pages | 2021-10-25 | 2021-10-28 | @nearodney  |  
|<ul><li>- [X] </li></ul> | Test [spark-rapids-examples repo](https://github.com/NVIDIA/spark-rapids-examples) with Spark-Rapids 21.10 | 2021-10-25 | 2021-10-28 | @nvliyuan  | 
|<ul><li>- [X] </li></ul> | Update docs for current release in spark-rapids-examples | 2021-10-25 | 2021-10-28 | @GaryShen2008|
|<ul><li>- [X] </li></ul> | Update rapids.sh in https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/rapids for the plugin| 2021-10-25 | 2021-10-28 | @viadea |

**Comment by pxLi** [comment]
> Create 21.12 branch 
> Automerge from 21.10 to 21.12
> Enable Jenkins builds (premerge, nightly, integration, performance) for 21.12
depends on
< Get RAPIDS 21.12 cudf java build working - which relies on cudf's plan

So I would recommend to finish those tasks after cudf 21.12 CI/CD gets setup, otherwise we will have plugin 21.12 snapshot using both cudfjni 21.10 for a period of time, and then 21.12 which could fail tests and confuse people

**Comment by pxLi** [comment]
21.10 changelog init has been merged, will do an update when all pending PRs and doc-update PRs gets merge.

**Comment by viadea** [comment]
Drafted https://github.com/GoogleCloudDataproc/initialization-actions/pull/942 for GCP init update.
