### ISSUE TITLE
[BUG] Document compression formats for readers/writers

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#341]
We should document the compression formats we support for readers/writers - parquet and orc for instance.

**Comment by tgravescs** [comment]
Also note that if there are formats we don't support we perhaps should put check in to make sure we fall back to cpu.

**Comment by sameerz** [comment]
Put information about supported compression for reading and writing in the Compatibility document.

**Comment by sameerz** [comment]
As of the 0.1 release: 

For Parquet reading we support `uncompressed`, `snappy` and `gzip`.  For Parquet writes we support `uncompressed` and `snappy`. 

For ORC reading we support `uncompressed`, `snappy` and `zlib`.  For ORC writes we support `uncompressed` and `snappy`.

**Comment by sameerz** [comment]
Related to issue #143

**Comment by sameerz** [comment]
closed by pr #550
