### ISSUE TITLE
[DOC] Document guidelines for handling new configs in upcoming Spark versions

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#3427]
As we add support for new Spark versions, sometimes new configuration settings need to be considered.  This often brings up a decision point: do we check for the new config setting even on older Spark versions or do we shim the config value lookup so it either defaults to a "safe" value for that Spark version or avoid performing any behavior related to the new config setting?  I don't think the answer is clear-cut, so it would be good to have documentation for devs and contributors to know how to properly handle a new config setting from Spark.

**Comment by sameerz** [comment]
Did not get to this in 21.12, will need to revisit.

**Comment by jlowe** [comment]
This is being handled on a case-by-case basis as part of auditing Spark changes.
