### ISSUE TITLE
[BUG] Profiling tool silently stops without producing any output on a Synapse Spark event log

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#3430]
**Describe the bug**
Profiling tool silently stops without producing any output on a Synapse Spark event log.

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

```
export SPARK_HOME=/xxx/spark
java -cp /xxx/rapids-4-spark-tools_2.12-21.10.0-SNAPSHOT.jar:$SPARK_HOME/jars/* com.nvidia.spark.rapids.tool.profiling.ProfileMain --csv \
/yyy/CPU_runs
```

**Expected behavior**
The profiling tool should either print a valid output or show the error.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

21.10 snapshot profiling tool.

**Additional context**

**Comment by viadea** [comment]
This turns out: If I increase the Java heap size (java -Xmx10G), then the profiling tool works fine.
I am ok if anybody thinks it is not a bug, or some enhancement to not let the tool exit silently without showing the OOM error.

**Comment by tgravescs** [comment]
Yeah we should at least print some info about any errors that occur

**Comment by sameerz** [comment]
Can we add some clarifying documentation to https://nvidia.github.io/spark-rapids/docs/additional-functionality/qualification-profiling-tools.html#how-to-use-qualification-tool about how to handle such an error, when we do eventually print it?  Or perhaps print this information in the error message that we display?

**Comment by viadea** [comment]
> Can we add some clarifying documentation to https://nvidia.github.io/spark-rapids/docs/additional-functionality/qualification-profiling-tools.html#how-to-use-qualification-tool about how to handle such an error, when we do eventually print it? Or perhaps print this information in the error message that we display?

In 21.10 tools doc: https://github.com/NVIDIA/spark-rapids/blob/branch-21.10/docs/additional-functionality/qualification-profiling-tools.md we do mention that customer should increase `-Xmx` if needed.

However the issue is: There is no any errors and the tool just stops silently. It may confuse users.

**Comment by tgravescs** [comment]
Check to see if Appbase where it catches throwable is the issue, switch to just catch exception.
