### ISSUE TITLE
[BUG] tools - test dsv1 complex and decimal test fails

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3435]
**Describe the bug**
it looks like tools tests weren't being run in premerge.

- test dsv1 complex and decimal *** FAILED ***

it looks like perhaps the Read File Format Score changed.

**Comment by nartal1** [comment]
Seeing this failure as the score changed due to ORC read support for map https://github.com/NVIDIA/spark-rapids/pull/3394 . I don' think tools tests are not run for pre merge builds. So it was not caught in CI.
