### ISSUE TITLE
[DOC] Document limitations of RAPIDS Accelerator on Databricks

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#3449]
There currently are some limitations of what types of operations and queries can be translated to the GPU depending on which features are enabled in Spark when running on the Databricks platform.  These limitations should be documented in the Databricks getting started section.

**Comment by viadea** [comment]
https://github.com/NVIDIA/spark-rapids/pull/3501 is drafted to add limitations for databricks.
