### ISSUE TITLE
[DOC]Update the Title Header for Fine Tuning

### ISSUE THREAD

**Issue by krajendrannv** [NVIDIA/spark-rapids#345]
**Suggested fix for documentation**

**Location of the suggested fix documentation**
https://nvidia.github.io/spark-rapids/docs/configs.html#fine-tuning

**Describe the documentation you'd like**
"Fine Tuning" as the header seems a little vague. 

Can we please update the heading to be something like: "Supported GPU Operators and Fine Tuning"
And the two lines below can be
"The RAPIDS Accelerator for Apache Spark can be further configured to enable or disable specific expressions that are currently supported. Enabling or disabling these expression allow users to control specific parts of the query execute using the GPU or the CPU respectively"

**Comment by sameerz** [comment]
@krajendrannv can I suggest the wording be: 

> _The RAPIDS Accelerator for Apache Spark_ can be configured to enable or disable specific 
> GPU accelerated expressions.  Enabling or disabling an expression controls which operators 
> run on the CPU or GPU.

**Comment by krajendrannv** [comment]
Your suggestion is much better.

**Comment by sameerz** [comment]
@abellina please review the text for accuracy and the PR for correctness.  If merged, I will open another PR for configs.md on the gh-pages branch.
