### ISSUE TITLE
[BUG] CastOpSuite and ParseDateTimeSuite failures spark 302 and others

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3478]
**Describe the bug**
running unit tests against spark 3.0.2 and the CastOpSuite has some failures:

- Cast from string to date using random inputs *** FAILED ***
  Mismatch casting string [12\rZ] to DateType. CPU: null; GPU: 0012-01-01 (CastOpSuite.scala:247)
- Cast from string to date using random inputs with valid year prefix *** FAILED ***
  Mismatch casting string [2021-9:] to DateType. CPU: null; GPU: 2021-09-01 (CastOpSuite.scala:247)

- Test all supported casts with in-range values *** FAILED ***
  Cast from StringType to DateType failed; ansi=false org.scalatest.exceptions.TestFaile

**Comment by tgravescs** [comment]
there are also failures in ParseDateTimeSuite:

- WITH DECIMALS: to_date yyyy-MM-dd *** FAILED ***
  Mismatch between CPU and GPU for the following rows:

  [- WITH DECIMALS: to_timestamp yyyy-MM-dd *** FAILED ***

**Comment by tgravescs** [comment]
looks like this fails on spark 3.0.1 as well

**Comment by abellina** [comment]
Just ran into this with `mvn verify`

**Comment by tgravescs** [comment]
something very weird because rolled back to yesterday and they still fail there

**Comment by andygrove** [comment]
perhaps the random data generation changes somehow and we are hitting test cases we haven't seen before? I'll take a look

**Comment by andygrove** [comment]
some of these failing tests do not use random data generation, so seems like something more build related somehow

**Comment by tgravescs** [comment]
its a change in cudf that causes this, I tried an older version and it works there.

Perhaps https://github.com/rapidsai/cudf/pull/9173  this

**Comment by revans2** [comment]
It looks like https://github.com/rapidsai/cudf/pull/9173 when into cudf and broke things. I am going to try and update the casing code to deal with this. It gives us some things that we want, and some things that we don't want all at once.

**Comment by revans2** [comment]
If someone else wants to disable those tests in the short term to unblock others I am fine with that.

**Comment by tgravescs** [comment]
working on disabling tests temporarily

**Comment by revans2** [comment]
Moved to @andygrove because he has been working on a fix and is further along than I was

**Comment by andygrove** [comment]
Fixed by https://github.com/NVIDIA/spark-rapids/pull/3496 and https://github.com/NVIDIA/spark-rapids/pull/3485
