### ISSUE TITLE
[DOC] Building from a rapids-compose setup

### ISSUE THREAD

**Issue by hyperbolic2346** [NVIDIA/spark-rapids#3484]
I ran into trouble when I was trying to bring a cudf build out of compose and into the plugin for testing. I thought I would document my process here to attempt to bring some light to the difficulty. I really like using the compose environment, but this means that I don't have gcc and cuda aligned with the internals of the docker container when outside of the container and that presents issues with building spark-rapids. I have cobbled together a workflow that isn't ideal, but is operational.

I first build cudf inside the container with `build-cudf-cpp -DCUDF_USE_ARROW_STATIC=ON` then I change into the `cudf/java` directory and build the maven package with `CONDA_PREFIX=/home/knobby/code/rapids/compose/etc/conda/envs/rapids/ CUDF_CPP_BUILD_DIR=/home/knobby/code/rapids/cudf/cpp/build/release mvn install -DskipTests`. This generates a `.m2/releases` directory inside the home directory, which is internal to the container and not a mounted volume. I then have to copy this directory to a mounted volume(`mv ~/.m2/releases ~/cudf/`) and move it to my home directory outside of the container(`~/code/rapids/cudf/releases ~/.m2`). From here I can go into the spark-rapids tree and use `mvn verify` to build and verify with my custom cudf.

Possible improvements

- [ ] Volume mount `~/.m2` into the container so the maven install ends up in the correct place

**Comment by jlowe** [comment]
Is this requesting a change to rapids-compose or just RAPIDS Accelertor dev documentation on setup flags to use when using rapids-compose?  Another alternative is you could extract the cudf jar and then manually install it via mvn into the local Maven repository with `mvn install:install-file`

**Comment by hyperbolic2346** [comment]
Sorry I wasn't clear here. I'm not sure the best fix and that is why this is an issue instead of a PR. I don't know if we want to add a documentation section in contributing on how to build the plugin if you use compose or not. In thinking through it well while I was writing, I think I'm going to ask if rapids-compose can mount the volume or have an option for mounting the volume for the .m2 directory. That would solve lots of the trouble I ran into.

Thanks for the hint about `mvn install:install-file`, I didn't know that was an option.

**Comment by sameerz** [comment]
Closing based on the above comment.
