### ISSUE TITLE
[BUG] Spark 3.2.0 TimeAdd/TimeSub fail due to new DayTimeIntervalType

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3502]
**Describe the bug**
Looking at integration test failures for spark 3.2 in https://github.com/NVIDIA/spark-rapids/issues/3483, the TimeAdd and TimeSub tests are failing because Spark now uses DayTimeIntervalType for some sql statements and our TimeAdd/Sub don't handle them properly. 

it looks pretty straight forward to add if we want to support it for those.

**Comment by tgravescs** [comment]
@wbo4958  were you working on this already?  I know you were doing some work with DayTimeIntervalType

**Comment by wbo4958** [comment]
@tgravescs, Yeah, I will take this one
