### ISSUE TITLE
[FEA] Support org.apache.spark.sql.catalyst.expressions.Sequence

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#3512]
**Is your feature request related to a problem? Please describe.**
I wish we can support org.apache.spark.sql.catalyst.expressions.Sequence which is for "Sequence" function.

**Describe the solution you'd like**
"Sequence" function can be supported.

**Describe alternatives you've considered**

**Additional context**

**Comment by wbo4958** [comment]
@viadea Do you have any code for this feature?

**Comment by wbo4958** [comment]
For now, Plugin has supported 

``` scala
spark.sql("select sequence(-1, 2, 1)")
```

and has not supported

``` scala
spark.sql("select sequence(start_col, end_col, step_col) from table").show()
```

I just filed an cudf dependency issue https://github.com/rapidsai/cudf/issues/9424
