### ISSUE TITLE
[BUG] Scaladoc warnings emitted during build

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#3520]
The following Scaladoc warnings appear in recent builds:
```
/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuListUtils.scala:27: warning: Could not find any member to link for "scala.IllegalArgumentException".
  /**
  ^
```
and
```
/spark-rapids/shims/spark301/src/main/scala/org/apache/spark/sql/rapids/execution/python/shims/spark301/GpuArrowEvalPythonExec.scala:484: warning: Could not find any member to link for "GpuPythonUDF".
/**
^
```

**Comment by firestarman** [comment]
I am wondering whether we could supress the warnings by add the option `-no-link-warnings` to scala plugin, if it was hard to fix this.

**Comment by jlowe** [comment]
These warnings occur because the classes aren't in the same module and Scaladoc often has difficulty linking across modules.  Simplest thing to do here is change the references to use backticks for monospacing rather than trying to link, as was done for other occurrences like this.

**Comment by firestarman** [comment]
And the warning log on GpuPythonUDF is no longer found in recent builds.
