### ISSUE TITLE
[BUG] support casts of decimal to numeric

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#3610]
This is something that @ttnghia found while working on tests for https://github.com/NVIDIA/spark-rapids/pull/3373, it looks like we cannot cast from decimal to other types (like Double) in his case:

```
scala> df.printSchema
root
 |-- value: decimal(5,1) (nullable = true)


scala> spark.sql("select cast(value as float) from foo").explain
21/09/22 20:56:49 WARN GpuOverrides: 
!Exec <ProjectExec> cannot run on GPU because not all expressions can be replaced
  @Expression <Alias> cast(value#0 as float) AS value#4 could run on GPU
    !Expression <Cast> cast(value#0 as float) cannot run on GPU because Cast from DecimalType(5,1) to FloatType is not supported
      @Expression <AttributeReference> value#0 could run on GPU
  *Exec <FileSourceScanExec> will run on GPU

== Physical Plan ==
*(1) Project [cast(value#0 as float) AS value#4]
+- GpuColumnarToRow false
   +- GpuFileGpuScan parquet [value#0] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex[file:/tmp/abellina], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<value:decimal(5,1)>
```

I am not entirely sure what types we want to enable, and we also need to add tests as suggested by @revans2

**Comment by revans2** [comment]
I am seeing failures when casting from Decimal(7,-3) to LongType.  That appears to be a bug in cudf, but there is no time to fix this in 12.10, so I will get a repro case and file the issue, but in the short term I think we have to not cast negative scale decimals.  Note that this appears to only be an issue when going to longs, and really just for scales up to 9.  It looks like the conversion is happening in 32-bit mode and then cast to 64-bits at the end, which does not really work.
