### ISSUE TITLE
[BUG] release312db profile pulls in 311until320-apache

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3613]
**Describe the bug**
somehow 311until320-apache got added into the release312db profile for databricks.  I take apache as meaning all Apache release which wouldn't include databricks, cdh, or other vendor specific implementation, we should remove that and move files as needed.

**Comment by gerashegalov** [comment]
Looking at the content, the directory has a single file `ShimVectorizedColumnReader.scala` that looks different only for CDH in the 311until320 set. So I think the right solution is to rename the dir and its references to 311until320-noncdh or something like that.
