### ISSUE TITLE
[BUG] Implement getReaderForRange in the RapidsShuffleManager

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#362]
If we have a skewed join that has GPU written output, we may end up with needing to read by range.

Currently the RapidsShuffleManager will "delegate" to the cpu shuffle for this, but this will fail (the output was written the catalog, not to files). 

This is to implement `getReaderForRange`

Note that in spark 3.1, `getReader` became final, and we should only use `getReaderForRange`.

**Comment by sameerz** [comment]
Closing in favor of issue #455
