### ISSUE TITLE
Refactor RapidsShuffle managers classes 

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#3624]
This issue is related to the review comments on #3602 

- There is a redundancy in the RapidsShuffle manager class hierarchy and delegation pattern between 
`ProxyRapidsShuffleInternalManagerBase` and `RapidsShuffleInternalManagerBase` . 
- VisibleShuffleManager should potentially be renamed according to its role as a tagging trait

**Comment by abellina** [comment]
I can take this for 21.12, if that's OK @gerashegalov

**Comment by gerashegalov** [comment]
thank you @abellina
