### ISSUE TITLE
[BUG] PCBS does not fully follow the pattern for public classes

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#3677]
**Describe the bug**
PCBS stands out in the series of similar classes in that 
- it calls ShimLoadernewInstanceOf directly https://github.com/NVIDIA/spark-rapids/blob/b3f977397336ed8530e211d8c8e9fce98fbc9aa5/sql-plugin/src/main/311%2B-all/scala/com/nvidia/spark/ParquetCachedBatchSerializer.scala#L55
- "manually" implements lazy wrapping without extending scala.Proxy trait

**Steps/Code to reproduce bug**
- inspect source code

**Expected behavior**
- Tighten ShimLoader API by making `newInstanceOf` and alike `private`
- Introduce a dedicated lazy Proxy trait to uniformly tag classes like PCBS and make them implment `lazy val self`

**Environment details (please complete the following information)**
 - local
 
**Additional context**
https://github.com/NVIDIA/spark-rapids/blob/384d956390702f4f3e9157cc85ecc21ecd50e2f3/shims/README.md#L97

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please guide me further ^_^

**Comment by gerashegalov** [comment]
Thanks for your interest @himanshu007-creator . You can look at https://github.com/NVIDIA/spark-rapids/blob/f4465cb798de2332c9931111c19b8649b1992d24/sql-plugin/src/main/scala/com/nvidia/spark/ExclusiveModeGpuDiscoveryPlugin.scala#L44 as an example

It calls a typed specific method `ShimLoader.newInternalExclusiveModeGpuDiscoveryPlugin()` that abstracts away the use of reflection behind the scenes. 

it does not invent a new name for the wrapped implementation but reuses scala.Proxy.self

**Comment by tgravescs** [comment]
Note that you can't put a new* function in ShimLoader itself for this because this class (CachedBatchSerializer) only exists in Spark 3.1.1 and ShimLoader has to compile against spark 3.0.x, that is the reason it wasn't put in there in the first place.

**Comment by gerashegalov** [comment]
> Note that you can't put a new* function in ShimLoader itself for this because this class (CachedBatchSerializer) only exists in Spark 3.1.1 and ShimLoader has to compile against spark 3.0.x, that is the reason it wasn't put in there in the first place.

we can return either Any or better create an internal tagging Trait
