### ISSUE TITLE
Add cache tests for different values of `StorageLevel` 

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#3688]
Storage level defines where the cache will be stored. e.g. DISK_ONLY, MEMORY_AND_DISK etc 

We need tests to make sure we support them and possibly catch any problems if any

**Comment by revans2** [comment]
@razajafri I am trying to understand a bit where this is coming from? Did we run into some errors with the other modes? This feels more like we are testing Spark instead of testing our code.

**Comment by razajafri** [comment]
I have been reached out to a few times asking if we support different storage modes. To me, it's clear that all modes should be supported but I thought adding a few tests would be sufficient to rest any doubts.

**Comment by sameerz** [comment]
Closing as I now understand that testing DISK would not actually test the plugin codepath.
