### ISSUE TITLE
[QST] Setting Exclusive_Mode on GPUs making it unavailable for ML workloads

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#3694]
**What is your question?**
I am running Spark on YARN without isolation and hence following the instructions in [this doc](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#yarn-without-isolation) by setting each GPU to `EXCLUSIVE_MODE`.
While this works for ETL workloads, this setting makes other ML (tensorflow, pytorch) workloads fail by giving the following error:

```
all CUDA-capable devices are busy or unavailable
```

Interestingly, this happens even if there is no active Spark job running on the cluster, which should ideally mean the GPUs are available to be used by other processes?
What is the recommended way to run ETL + ML workloads on the same YARN cluster such that GPUs can be shared?

**Comment by tgravescs** [comment]
are you using GPU scheduling on the YARN setup?
How many ML jobs are you running on a box and are they trying to share GPU's?  The easiest way to check this is to run the job, go to the host where it got the error and use nvidia-smi to see if the GPUs are already allocated to other processes.
For instance if you have 4 GPUs on a box and try to have 5 processes on that box use the GPUs, then one of them will fail.

**Comment by tgravescs** [comment]
No, something else is using your GPUs, if its not scheduling them through yarn then they will obviously conflict and hence why you get an error about the cuda devices not available.  Suggest you look to see what those processes are and if they are using GPU scheduling in yarn as well.

**Comment by tgravescs** [comment]
I don't understand the situation:
>  Spark job finishes
What exactly do you mean by this?  Is the spark application finishing or is this trying to run ML jobs within the same application?  ie one application uses the sql plugin to run etc jobs and then afterwards the same applications runs ML job.  Are these ML jobs python?

**Comment by Niharikadutta** [comment]
Closing this issue since this is by design,
