### ISSUE TITLE
[FEA] round and bround SQL functions

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#37]
**Is your feature request related to a problem? Please describe.**
It would be great to support the round and bround SQL functions.
https://github.com/rapidsai/cudf/issues/3790 was filed to implement them in cudf.

**Comment by tgravescs** [comment]
It looks like the cudf side has been implemented by https://github.com/rapidsai/cudf/pull/6685

**Comment by nartal1** [comment]
Yes, I was planning to start on cudf Java work on this once I am done with binary operations for decimal type.
