### ISSUE TITLE
[BUG] Change `nullOnDivideByZero` from runtime parameter to aggregate expression for `stddev` and `variance` aggregation families

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids#3705]
This is a follow-up issue for https://github.com/NVIDIA/spark-rapids/pull/3373. Currently, `stddev` and `variance` aggregation families access an expression `nullOnDivideByZero` that is a runtime parameter instead of the input expression. As such, the optimizer has a limited chance to optimize the execution of the aggregation based on different values of that parameter.

We should change that parameter from runtime parameter to input expression to have more chance of optimization for the planner.

**Comment by revans2** [comment]
Switched this over to a bug, because in really rare cases this might cause a problem. But it is unlikely enough that it is going to be a low priority.
