### ISSUE TITLE
[BUG] Implicitly catching all exceptions warning in GpuOverrides

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#3743]
A new compiler warning is emitted on recent builds:
```
[WARNING] /home/ubuntu/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:3654: This catches all Throwables. If this is really intended, use `case fatal : Throwable` to clear this warning.
[WARNING]       case fatal =>
[WARNING]            ^
```

**Comment by gerashegalov** [comment]
that slipped into my commit. I think we should add `-Xfatal-warnings` to scalac. https://github.com/NVIDIA/spark-rapids/blob/branch-21.10/pom.xml#L921,  and silence the existing warnings that are impossible / difficult to eliminate.

**Comment by jlowe** [comment]
> I think we should add -Xfatal-warnings to scalac.

Agreed.  We thought about this early on, but scalac doesn't provide a way to silence deprecation warnings.  It looks like Apache Spark is using com.github.ghik's silencer-plugin to help solve that shortcoming, so we may need to do something similar.
