### ISSUE TITLE
Improve batch coalesce logic

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#3750]
Currently the logic for coalescing a batch will pull in a new batch as long as the current total size of all held batches is below the target size regardless of how close we are to the target size or the size of the batches that have been seen.  This can cause a batch to be manifested in memory that cannot be added to the set of batches to coalesce for the next output batch, forcing it to be made spillable and adding undesired memory pressure.  The logic tries very hard to reach as close as it can to the target size, causing extra batches to be held in memory as a result.

The logic for coalescing should be a bit smarter, avoiding pulling in a new batch if it appears likely that the new batch will cause the next output batch to exceed the target size.  One idea is to track the maximum size of any batch seen so far and only fetch the next batch if there is enough room to accommodate another batch of that size for the next coalesced output batch.

**Comment by mattahrens** [comment]
Closing as won't fix for now
