### ISSUE TITLE
Add automated test for ExclusiveModeGpuDiscoveryPlugin

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3774]
**Is your feature request related to a problem? Please describe.**
we don't have an automated test for ExclusiveModeGpuDiscoveryPlugin, we should add one that at least sanity checks basic job works and it loads properly.

**Comment by NvTimLiu** [comment]
Created the pipeline in Blossom `rapids_it-WITHOUT-isolation` to run a sample test with `spark.resources.discoveryPlugin=com.nvidia.spark.ExclusiveModeGpuDiscoveryPlugin`. If this conf is not set, it will FAILED with "23:55:43  gpu -> [name: gpu, addresses: 0,1,2,3]"



We can run this job once a week.

**Comment by NvTimLiu** [comment]
@tgravescs  Could you please help to check if this job `rapids_it-WITHOUT-isolation` meet all the requirements?

**Comment by tgravescs** [comment]
it should be fine, but builds not working right now. I want to verify spark ui but it looks like this job doesn't save history , so I want to run it and see while running.

**Comment by NvTimLiu** [comment]
> it should be fine, but builds not working right now. I want to verify spark ui but it looks like this job doesn't save history , so I want to run it and see while running.

the failures are due to Artifact revisions are inconsistent,  cudf JNI jar downloaded from URM was inconsistent with the cuDF JNI building against rapids-4-spark jar.
You can skip consistent check by SKIP_REVISION_CHECK=true  in OVERWRITE_PARAMS

**Comment by tgravescs** [comment]
ok, verified that job looks good we can resolve, please just make sure its pinging slack and we have it documented

**Comment by NvTimLiu** [comment]
> ok, verified that job looks good we can resolve, please just make sure its pinging slack and we have it documented

We have pinged the test result to the slack notifications 

For the docs  `ExclusiveModeGpuDiscoveryPlugin` :  https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#yarn-without-isolation. Need we update other docs besides this one

**Comment by tgravescs** [comment]
Sorry I meant our internal spreadsheet for mapping builds to what its testing, confluence page

**Comment by NvTimLiu** [comment]
> Sorry I meant our internal spreadsheet for mapping builds to what its testing, confluence page

Thanks for remind, we have already have internal confluence page for all the pipelines. I also added description for the `ExclusiveModeGpuDiscoveryPlugin` pipeline

**Comment by NvTimLiu** [comment]
so let close this issue as the nightly pipeline runs well.
