### ISSUE TITLE
[FEA] Push decimal workarounds/cleanup back to cudf

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3793]
There are several places in the code where we need to work around overflow issues in cudf, or general data could be [cleaner](https://github.com/NVIDIA/spark-rapids/pull/3790#discussion_r726483594).  These should be pushed back to cudf itself.

**Comment by sperlingxx** [comment]
Hi @revans2, does this issue propose to "essentially push all of DecimalUtil back to CUDF once we have it working really well" ?

**Comment by sperlingxx** [comment]
I created a cuDF PR to push down the `round` stuff: https://github.com/rapidsai/cudf/pull/9809

**Comment by sperlingxx** [comment]
https://github.com/rapidsai/cudf/pull/10316, this fix is required for the cleanup.
