### ISSUE TITLE
[BUG]binary-dedup.sh script fails on mac

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3823]
**Describe the bug**
looks like xargs on mac doesn't support --arg-file option:
```

     [exec] + xargs --arg-file=/Users/tgraves/Documents/workspace/spark-rapids/dist/target/spark3xx-common.txt -P 6 -n 1 -I% bash -c 'remove_duplicates "$@"' _ %
     [exec] xargs: illegal option -- -
     [exec] usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
     [exec]              [-L number] [-n number [-x]] [-P maxprocs] [-s size]
     [exec]              [utility [argument ...]]
```

line`: xargs --arg-file="$SPARK3XX_COMMON_TXT" -P 6 -n 1 -I% bash -c 'remove_duplicates "$@"' _ %`

instead of using the --arg-file option I think we can just cat the the file and | it into xargs

Note there is a line at the end that uses it too:

`xargs --arg-file="$UNSHIMMED_LIST_TXT" -P 6 -n 100 -I% \
`
But that didn't fail so we probably have a bug where it should fail.

**Comment by gerashegalov** [comment]
and once I fix it it's incredibly slow,  probably need to just compile a single list of files to delete in larger batches
