### ISSUE TITLE
[BUG] Approx_percentile deserialize error when calling "show" rather than "collect"

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#3834]
**Describe the bug**
When running a `show` against an approx_percentile aggregate query, the query fails with a serialization error due to the partial aggregate running on GPU and the final aggregate running on CPU. The intermediate aggregate buffer is not in the expected format for CPU so deserialization fails.

The final stage falls back to the CPU due to a cast to string that is trigger by `show` and is not supported on GPU.

```
!Expression <Cast> cast(approx_percentile(v#476, [0.1,0.2], 10000, 0, 0)#479 as string) cannot run on GPU because Cast from ArrayType(DoubleType,false) to StringType is not supported
```

Example of the error stack trace:

```
Caused by: java.lang.NegativeArraySizeException
at org.apache.spark.sql.catalyst.expressions.aggregate.ApproximatePercentile$PercentileDigestSerializer.deserialize(ApproximatePercentile.scala:319)
```

**Steps/Code to reproduce bug**

I can reproduce with this integration test (added to `hash_aggregate_test.py`).

```python
@pytest.mark.parametrize('aqe_enabled', ['false', 'true'], ids=idfn)
@ignore_order(local=True)
@allow_non_gpu('TakeOrderedAndProjectExec', 'Alias', 'Cast', 'ObjectHashAggregateExec', 'AggregateExpression',
    'ApproximatePercentile', 'Literal', 'ShuffleExchangeExec', 'HashPartitioning', 'CollectLimitExec')
def test_hash_groupby_approx_percentile_double_show(aqe_enabled):
    conf = copy_and_update(_approx_percentile_conf, {
        'spark.sql.adaptive.enabled': aqe_enabled,
        'spark.rapids.sql.explain': 'ALL'
    })

    def foo(spark):
        df = gen_df(spark, [('k', StringGen(nullable=False)),
                                         ('v', DoubleGen())], length=100)
        df.createOrReplaceTempView("t")
        df2 = spark.sql("SELECT k, approx_percentile(v, array(0.1, 0.2)) from t group by k")

        # this "show" triggers the exception
        df2.show()

        return df2

    run_with_cpu_and_gpu(foo, 'COLLECT', conf)
```

**Expected behavior**
We should recognize that the final aggregate cannot run on GPU and force the partial aggregate to fall back to CPU as well.

**Environment details (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by revans2** [comment]
Please make sure that for any test in the future that we have some way to permanently force the second half onto the CPU.  It is very likely that we will support casting arrays to strings in the future.

**Comment by andygrove** [comment]
There are checks already that tag the partial aggregate to indicate that it should fall back to the CPU but then this tag was not being checked when planning the query stage containing the partial aggregate. I was able to confirm this by adding the following code to `GpuTypedImperativeSupportedAggregateExecMeta.tagPlanForGpu`.

```scala
override def tagPlanForGpu(): Unit = {
  super.tagPlanForGpu()
  
  // when AQE is enabled and we are planning a new query stage, we need to look at meta-data
  // previously stored on the spark plan to determine whether this aggregate can run on GPU
  wrapped.getTagValue(gpuSupportedTag).foreach(_.foreach(willNotWorkOnGpu))
```

However, it shouldn't be necessary to add this check on each meta class. We should be able to walk the plan during query stage planning to make sure this gets invoked on all nodes.
