### ISSUE TITLE
[BUG] In ANSI mode we can fail in cases Spark would not due to conditionals

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3849]
**Describe the bug**
When Spark evaluates an `if` or a `case/when` function it will do lazy evaluation of the children.  So the else clause of if/else is only evaluated if the condition is false.  For the cudf version we evaluate both sides no matter what.  This is fine when an operation has no side effects. But in ANSI mode many operations can have big side effects (failing  query). This can also be true for UDFs and for `assert_true/raise_error` which we do not support yet in non-ANSI mode.

**Steps/Code to reproduce bug**
```scala
spark.conf.set("spark.sql.ansi.enabled", "true")
val df = Seq((true, 0L), (false, Long.MaxValue)).toDF("cond", "val")
df.repartition(1).selectExpr("IF(cond, val + 1, null) as my_div").show
+------+
|my_div|
+------+
|     1|
|  null|
+------+
```

The above query works just fine on the CPU because the if/else avoids executing the overflow condition. On the GPU it fails.

**Expected behavior**
It should behave the same way as the CPU

I think in the short term we can just document this, and possibly fall back to the CPU if ANSI is enabled and we encounter any conditional statements like this.  Longer term I think we need to come up with a plan on how to address this.

**Comment by revans2** [comment]
Talking to @sameerz and @tgravescs I think the best way to try and fix this would be to have an optional boolean column passed with the batch when doing a project.  It would be a mask of which rows are actually being executed, and which ones are not.  That way in ANSI mode we could look at this mask and not throw exceptions if the row was not intended to be taken.  And in the case of #3855 we could just skip execution on that path and insert a null or some other default value instead as the result.

**Comment by firestarman** [comment]
> This is related to #3855 because it could happen for them too.

Hi @revans2, I am working on this issue 3855, but don't fully get what you mean here. Could you share an example ?
