### ISSUE TITLE
[BUG] ShimLoader.updateSparkClassLoader fails with openjdk Java11

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#3851]
**Describe the bug**
Originally reported by @abellina 

```
21/10/18 23:18:41 INFO ShimLoader: Updating spark classloader jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27 with the URLs:
 jar:file:/home/gshegalov/gits/NVIDIA/spark-rapids/dist/target/rapids-4-spark_2.12-21.12.0-SNAPSHOT.jar!/spark3xx-common/, jar:file:/
home/gshegalov/gits/NVIDIA/spark-rapids/dist/target/rapids-4-spark_2.12-21.12.0-SNAPSHOT.jar!/spark320/
21/10/18 23:18:41 ERROR CoarseGrainedExecutorBackend: Executor self-exiting due to : Unable to create executor due to No such method:
 addURL() on object: jdk.internal.loader.ClassLoaders$AppClassLoader
java.lang.NoSuchMethodException: No such method: addURL() on object: jdk.internal.loader.ClassLoaders$AppClassLoader
        at org.apache.commons.lang3.reflect.MethodUtils.invokeMethod(MethodUtils.java:231)
        at org.apache.commons.lang3.reflect.MethodUtils.invokeMethod(MethodUtils.java:184)
        at com.nvidia.spark.rapids.ShimLoader$.$anonfun$updateSparkClassLoader$3(ShimLoader.scala:216)
```

**Steps/Code to reproduce bug**

Set `JAVA_HOME` environment  to an openjdk java11 location and run code with the default `spark.rapids.force.caller.classloader=true`. 

Note this issue does not reproduce with the Microsoft Build of OpenJDK 11

**Expected behavior**
It should work.

- short term just add another [method name](https://github.com/openjdk/jdk/blob/6765f902505fbdd02f25b599f942437cd805cad1/src/java.base/share/classes/jdk/internal/loader/ClassLoaders.java#L203) to try in the reflection calls, although JDK module encapsulation [will not make it easy ](https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m) 
- long term potentially #3803

**Environment details (please complete the following information)**
local dev environment 

**Additional context**
N/A

**Comment by fcomte** [comment]
I have the same issue. I am running spark 3.2.0 on openjdk 11. I am unable to make nvidia spark rapids working

**Comment by gerashegalov** [comment]
@fcomte there are a few workarounds, if going to JDK8 is not an option, you can try `--conf spark.rapids.force.caller.classloader=false`  that uses a different mechanism, which works well in many situations.

**Comment by fcomte** [comment]
thx @gerashegalov  `--conf spark.rapids.force.caller.classloader=false` works

**Comment by gerashegalov** [comment]
I think we can use this issue to implement a RP that automatically falls back on the orginal default spark.rapids.force.caller.classloader=false call path https://github.com/NVIDIA/spark-rapids/pull/5356#discussion_r861345912
