### ISSUE TITLE
[FEA] Optimize Dynamic Partition Pruning queries

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#386]
**Is your feature request related to a problem? Please describe.**
Dynamic Partition Pruning (DPP) is a great feature for SQL planning, but it really would be great if we could optimize it for the GPU.

```
spark.sql(s"DROP TABLE IF EXISTS df2")
spark.sql(s"DROP TABLE IF EXISTS df1")
spark.range(1000).select(col("id"), col("id").as("k")).write.partitionBy("k").format("parquet").mode("overwrite").saveAsTable("df1")
spark.range(100).select(col("id"), col("id").as("k")).write.partitionBy("k").format("parquet").mode("overwrite").saveAsTable("df2")
sql("SELECT df1.id, df2.k FROM df1 JOIN df2 ON df1.k = df2.k AND df2.id < 2").collect()
```

triggers DPP.  The query runs correctly on the GPU, but the plan results in the broadcast table df2 being scanned twice. Exchange reuse does not kick in on the broadcast, because one of the broadcast operations is being fed to a subquery expression so the data is sent to the CPU before being broadcast. 

**Describe the solution you'd like**

Ideally we need some support for a sub-query expression that runs on the CPU as a pushed down filter to an input format.

There are other queries that also use a sub-query expression, but would need to be executed on the GPU (one of the TPCH queries is like this) so if we can support both that would be even better.

**Comment by tgravescs** [comment]
Note this came up in issue https://github.com/NVIDIA/spark-rapids/issues/1378 where they have further optimizations that require the broadcastexchanged to be a reused exchange.

Also a side note that AQE has support for DPP with broadcast hash joins in spark 3.2.0 -> https://issues.apache.org/jira/browse/SPARK-34168
