### ISSUE TITLE
[DOC] Document flow customers take when deciding apps to run with the plugin

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3877]
## Report incorrect documentation
Currently we have different methods/tools available for customers to use to decide which applications might be best fit for running on the plugin.
1) qualification tool
2) New explain api that can be run on CPU but requires code modification
3) Profiling tool
4) Run jobs with plugin on GPU

Different customers have different environments as well as might have different restrictions on modifying code or access files.  Try to document out different situations and which tool could be used to help get more information.
Along with this we might be need more documentation or just better tooling for customers not familiar with Spark, or perhaps information on where to get help in trying to decide, etc..

**Comment by viadea** [comment]
https://github.com/NVIDIA/spark-rapids/pull/4110 is drafted . Feel free to comment
