### ISSUE TITLE
[FEA] Decimal 128 Support: MurMur3 and HashPartitioning support.

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3878]
Spark hashes Decimal 128 values very differently from decimal 64 and below.  The existing MurMur3 hashing in CUDF is not correct for Spark. Once it is fixed we need to update the tests and make sure it is working.  Note that there are a number of integration tests in hash aggregate around distinct counts and such that cannot include decimal 128 values in them because this functionality is missing and the shuffle falls back to the CPU. As a part of this it would be nice to enable those tests, or have a follow on issue to enable them.

**Comment by nartal1** [comment]
https://github.com/NVIDIA/spark-rapids/pull/4470 adds decimal-128 support for Murmur3 and HashPartitioning. Closing.
