### ISSUE TITLE
[BUG] test_read_with_more_columns failed in UCX standalone run

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#3895]
This was caught by the UCX job, but it has nothing to do with UCX

```
 test_read_with_more_columns[true-orc-{'spark.rapids.sql.format.orc.reader.type': 'COALESCING'}-Struct(['child0', Byte],['child1', Short],['child2', Integer],['child3', Long],['child4', Float],['child5', Double],['child6', String],['child7', Boolean],['child8', Date],['child9', Timestamp],['child10', Decimal(18,0)],['child11', Decimal(7,3)],['child12', Decimal(7,7)],['child13', Decimal(12,2)])]
```

The results don't match the CPU:

```
cpu = Row(child0=-11, child1=-4772, child2=921035487, child3=-6176109636267555852, child4=-5.4437165886156436e-08, child5=2....926000), child10=Decimal('414277330024740582'), child11=Decimal('938.235'), child12=Decimal('0.0621528'), child13=None)
gpu = None
```

**Comment by abellina** [comment]
If I run the tests manually in the same environment, I haven't seen this occur yet. So it doesn't seem to be easily reproducible easily or it is indeed related to a race condition with another application.

**Comment by abellina** [comment]
I still can't get this to reproduce when executing normally. I tried killing executors at random and I don't see issues, I do get good failures where the job ends up failing due to too many task failures.

Out on a limb, I did set one of the 4 GPUs in this box to `PROHIBITED` execution mode, thinking this would induce some other types of failures, and I did get something different (sigh): 

```
ai.rapids.cudf.CudfException: for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
        at ai.rapids.cudf.Table.readORC(Native Method)
        at ai.rapids.cudf.Table.readORC(Table.java:943)
        at com.nvidia.spark.rapids.MultiFileOrcPartitionReader.$anonfun$readBufferToTable$10(GpuOrcScanBase.scala:1886)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.FilePartitionReaderBase.withResource(GpuMultiFileReader.scala:236)
```

The way the  test looks here is we have 4 executors (1 for each GPU) that start up. Then 1 one of them fails while getting on the GPU since I disabled one of the GPUs, so it fails and tasks are retried in other places. The executor tries to come back up again, and again it continues to fail. Note this is not a deterministic error, it happened 3 times out of ~10 times.

**Comment by abellina** [comment]
I was able to capture the parquet files we are reading at the time of one of the failures I can make happen, but I am able to read these same files outside of the test with the GPU. No root cause yet.

**Comment by sameerz** [comment]
Not sure if we are able to reproduce this reliably, we have not seen this happen recently.  Will reopen if it starts happening again.
