### ISSUE TITLE
IllegalArgumentException: features does not exit. [BUG]

### ISSUE THREAD

**Issue by gnani4444** [NVIDIA/spark-rapids#392]
Hi
I am trying to run XGBoost4j Spark 3.0 GPU version on the azure databricks.
I was following the procedure from [this post](https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/getting-started-guides/csp/databricks/databricks.md) .
While I was running [Mortage-gpu notebook](https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/examples/notebooks/python/mortgage-gpu.ipynb). I got this error "features does not exist". The code is expecting a feature with name "features".
![Capture](https://user-images.githubusercontent.com/19526142/87860091-2eefe480-c958-11ea-99a4-7a81c137c22e.PNG)

Can anyone help me with this ? I am running it on azure databricks with 7.0 ML GPU runtime, with NC6 GPU worker and driver node, as mention in the post.
Thanks in Advance

**Comment by revans2** [comment]
@GaryShen2008 @wbo4958 Could either of you help with this as the XGBoost code falls under you.  Did someone copy the benchmark incorrectly in the documentation?

**Comment by wbo4958** [comment]
Hi @gnani4444, As you have filed the same issue in https://github.com/NVIDIA/spark-xgboost-examples/issues/13. So let's close this issue in this repo.
