### ISSUE TITLE
[BUG] Release sql-plugin and udf examples jars

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#3931]
**Describe the bug**
If people want to use the RapidsUDF functionality we should be releasing the sql-plugin jar so they can put it as a dependency in their project.  Also the udf examples jar shouold be released if people are expected to just use the examples we provide in there.

Also we should have a test that what we release actually works.  Perhaps we need to split that into separate issue.

**Comment by jlowe** [comment]
The udf-examples jar should be published as part of moving it to a separate repo to fix #3971.  As for the sql-plugin, I think we agree that doesn't need to be published since it's public APIs should be available via the dist jar and users should depend on that directly.
