### ISSUE TITLE
[FEA] Aggregate (Min/Max/Count) push down for Parquet 

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#3951]
https://issues.apache.org/jira/browse/SPARK-36645 added min/max push downs to parquet in 3.3.0.  This feature is off by default, but it allows a metadata only query to run on the CPU.  It would be great if we could implement this feature, but at a minimum if we see it being used we should fall back to the CPU because there is little performance improvement that we will be able to do, as it is a meta data only query.

**Comment by HaoYang670** [comment]
I'd like to try

**Comment by HaoYang670** [comment]
Should we add a Spark 330+ shim layer for this feature, or enable this feature on all Spark versions?

**Comment by HaoYang670** [comment]
This feature is also added in Spark 3.2.0
