### ISSUE TITLE
[Audit] [FEA][SPARK-32986][SQL] Add bucketed scan info in query plan of data source v1

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#3952]
**Is your feature request related to a problem? Please describe.**
The PR adds info into `FileSourceScanExec` physical query plan output whether the table is read as bucketed table. Opening this issue to get feedback if we need to update GpuFileSourceScanExec.scala to include this change.
PR - https://github.com/apache/spark/commit/79515e4b6c

**Comment by jlowe** [comment]
I agree we should pull this in, but I don't think it needs to be shimmed.  We can just always output the bucketing format added in 3.3 on all Spark versions.

**Comment by HaoYang670** [comment]
I'd like to try.
