### ISSUE TITLE
As part of [SPARK-36594] supportBatch method is changed in OrcFileFormat

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#3955]
This might need a second look. `supportBatch` method is changed in `OrcFileFormat`. Although we don't seem to be using it another look may be needed just to make sure.

**Comment by jlowe** [comment]
This added a check against whole stage code gen to see if the number of columns exceeds the maximum number of fields codegen can support.  We don't use codegen nor this code path in the plugin.
