### ISSUE TITLE
[Audit][FEA] [SPARK-36070][CORE] Log time cost info for writing rows out and committing the task

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#3959]
**Is your feature request related to a problem? Please describe.**
This issue is just to keep GpuFileFormatWriter.scala in sync with changes in Apache Spark FileFormatWriter.scala. The PR is used to add logging which would help to debug. It doesn't affect functionality in anyway.
PR- https://github.com/apache/spark/commit/f5a63322de

Another trivial change - https://github.com/apache/spark/commit/2fc9c0bfb5 (change logInfo to logWarning)

**Comment by HaoYang670** [comment]
I'd like to try to fix it.

**Comment by HaoYang670** [comment]
Maybe the logging time has been added.
https://github.com/NVIDIA/spark-rapids/blob/branch-22.02/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatWriter.scala#L254

**Comment by HaoYang670** [comment]
Another related issue is #2123

**Comment by HaoYang670** [comment]
This is another PR that delect the code of apache/spark@f5a6332

https://github.com/apache/spark/commit/3ff8c9f9d651779f1eb7926eaa79271f7d3fecee#diff-03e7ff19e93cb270d82aca907ac0a1f87463ba6eb5dce78a407bb169b840a6cbL305-L311
