### ISSUE TITLE
[FEA] Add a pre-merge check to validate that a PR has been committed using git signoff

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#399]
**Is your feature request related to a problem? Please describe.**

We are introducing a contributor license agreement signoff requirement.  We need to ensure that commits are signed off with https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s .  If a PR is not signed off, it should fail a pre-merge check.  

**Describe the solution you'd like**
Pre-merge checks (builds?) fail without seeing a -s signoff from anyone committing to a PR.  If the author of a commit adds a single commit with a -s, that will be sufficient for the pre-merge build to pass.  

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/CONTRIBUTING.md#sign-your-work

**Comment by jlowe** [comment]
Fixed by #439
