### ISSUE TITLE
Can I turn on the spark speculation on rapids ? [QST]

### ISSUE THREAD

**Issue by rui911013** [NVIDIA/spark-rapids#400]
spark will improve performan about long task when set the spark.speculation=true , i don't know if I set this flag, it will geting better or getting worse.
I attemp to set the flag, and it can work corretly.

**Comment by rui911013** [comment]
according spark expericence ，my speculation conf is :
spark.speculation.quantile 0.9
spark.speculation true
spark.speculation.multiplier 3
spark.speculation.interval 1s

**Comment by jlowe** [comment]
Speculative execution in Spark is fine with the RAPIDS accelerator plugin.

As with all speculative execution, it may or may not be beneficial depending on the nature of why a particular task is slow and how easily speculation is triggered.  You should monitor your Spark jobs to see how often task speculation occurs and how often the speculating task (i.e.: the one launched later) finishes before the slow task that triggered speculation.  If the speculating task often finishes first then that's good, it is working as intended.  If many tasks are speculating but the original task always finishes first then this is a pure loss, the speculation is adding load to the Spark cluster with no benefit.

**Comment by rui911013** [comment]
got it, thanks
