### ISSUE TITLE
[FEA] Add regular expression support to GPU implementation of StringSplit

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4003]
**Is your feature request related to a problem? Please describe.**
We currently implement StringSplit but only support non-regexp patterns.

**Describe the solution you'd like**
We should support regular expressions in the split pattern, compatible with Spark.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
Depends on https://github.com/rapidsai/cudf/issues/9862

**Comment by ttnghia** [comment]
Depends on https://github.com/rapidsai/cudf/pull/10128 and https://github.com/rapidsai/cudf/pull/10139.

**Comment by sameerz** [comment]
Example from https://github.com/NVIDIA/spark-rapids/issues/4658#issue-1117811691 

> I wish we support split with regular expressions.
> 
> Mini repro:
> 
> val address = Seq((1,"abc.com"),
> (2,"...abc"),
> (3,".a.b.c"))
> 
> import spark.implicits._
> val df = address.toDF("id","txt")
> df.write.mode("overwrite").format("parquet").save("/tmp/testparquet")
> val df2=spark.read.parquet("/tmp/testparquet")
> df2.createOrReplaceTempView("df2")
> spark.sql("select id,txt, split(txt, '\\\\.')[0] AS new_txt from df2").show()
> 
> Not-supported-messages:
> 
> !Expression <StringSplit> split(txt#209, \., -1) cannot run on GPU because regular expressions are not supported yet
>
