### ISSUE TITLE
[FEA] Support First() in windowing context with Integer type

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#4005]
**Is your feature request related to a problem? Please describe.**
This is a feature request to support first() function in windowing context with double type.

For example:
```
import org.apache.spark.sql.Row
import org.apache.spark.sql.types._
import org.apache.spark.sql.functions._

val data = Seq(
    Row(Row("Adam ","","Green"),"1","M",1000, "2019-01-01",List("Java","Scala")),
    Row(Row("Bob ","Middle","Green"),"2","M",2000, "2019-01-02",List("Java","Python")),
    Row(Row("Cathy ","","Green"),"3","F",3000, "2019-01-03",List())
)

val schema = (new StructType()
  .add("name",new StructType()
    .add("firstname",StringType)
    .add("middlename",StringType)
    .add("lastname",StringType)) 
  .add("id",StringType)
  .add("gender",StringType)
  .add("salary",IntegerType)
  .add("birthdayStr",StringType)
  .add("language",ArrayType(StringType))
             )

val df = spark.createDataFrame(spark.sparkContext.parallelize(data),schema)
df.withColumn("birthday", to_date(col("birthdayStr"))).write.format("parquet").mode("overwrite").save("/tmp/testparquet")
val df2 = spark.read.parquet("/tmp/testparquet")
df2.createOrReplaceTempView("df2")
df2.printSchema

sql("""SELECT gender, first(salary,true) OVER (PARTITION BY gender ORDER BY salary) FROM df2""").collect


```

**Comment by viadea** [comment]
Driver log message:
```
      !Expression <WindowExpression> first(salary#174, true) windowspecdefinition(gender#173, salary#174 ASC NULLS FIRST, specifiedwindowframe(RangeFrame, unboundedpreceding$(), currentrow$())) cannot run on GPU because the type of orderBy column is not supported in a window range function, found DoubleType
```

**Comment by res-life** [comment]
Actually not support first function in window context.
CUDF does not support this currently.

**Comment by res-life** [comment]
@viadea  Order by in window only supports int and timestamp, does not supports double float, it's a constraint of CUDF.
Like Count does not support double, you can test:
      ```  
       SELECT gender, count(salary) OVER (PARTITION BY gender ORDER BY salary) FROM df2
      ```
So this issue will be:  Support First() in windowing context with int and timestamp.

**Comment by revans2** [comment]
All of these are going to require some CUDF changes to work.

`nth_element_aggregation` is not supported as a `rolling_aggregation` in cudf so we cannot implement it in a way that will be able to support null checks like the query above wants.

Cudf does not support range queries on floats or doubles yet.  We can add this in though.

**Comment by res-life** [comment]
Note: Still depends on cuDF: https://github.com/NVIDIA/spark-rapids/pull/6000#issuecomment-1188512673

**Comment by res-life** [comment]
- [ ] For IntegerType
- [ ] For Float/Double Type

**Comment by res-life** [comment]
Split this issue into 2, one for Integer, one for Double #6192

**Comment by res-life** [comment]
#6000 already supported Integer type.
