### ISSUE TITLE
[BUG] Why is the hash aggregate not handling empty result expressions

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#4017]
The hash aggregate is currently disabled for cases where there are no `resultExpressions`. This is something that was missed and has been in the hash aggregate code for a long time. 

https://github.com/NVIDIA/spark-rapids/blob/branch-21.12/sql-plugin/src/main/scala/com/nvidia/spark/rapids/aggregate.scala#L872

Prior issues reference the mortgage test as a potential repro case. I can imagine that without much effort this can be fixed and we can remove this special case.

**Comment by revans2** [comment]
```
spark.sql("SELECT c_birth_month, SUM(c_birth_year) as sum_year from customer where c_salutation rlike 'Mr.' group by c_birth_month").count()
```

Shows this on the TPCDS dataset. Although it is really just a bogus query.  Essentially it looks like in this situation there is a count as the output of the query so they don't want to materialize the output. Just get the number of rows of output there would be. So output a batch with no columns, just rows.

**Comment by abellina** [comment]
@revans2 thanks, the example reproduces locally

**Comment by viadea** [comment]
Thanks Bobby for the mini repro. Let me put the interested Spark driver log message here for future search:
```
!Exec <HashAggregateExec> cannot run on GPU because result expressions is empty
```
