### ISSUE TITLE
Release Checklist for 21.12

### ISSUE THREAD

**Issue by Salonijain27** [NVIDIA/spark-rapids#4018]
Release Checklist for v21.12:

| Status  | Task | Start | End | Owner| 
| ------------- | ------------- | ------------- | ------------- | ------------- | 
|**Pre-release**| | | | |
|<ul><li>- [X] </li></ul> | Notification to team of last feature sprint in milestone 2021-11-01 - 2021-11-12 | 2021-11-01 | 2021-11-12 | @sameerz| 
|<ul><li>- [X] </li></ul> | Burndown (no new features for current release) | 2021-11-15 | 2021-11-24 | Team|  
|<ul><li>- [X] </li></ul> | Update docs for current release in spark-rapids | 2021-11-29| 2021-12-03 | Team| 
|<ul><li>- [X] </li></ul> | Get RAPIDS 22.02 cudf java build working.  | 2021-11-08 | 2021-11-12 | @pxLi | 
|<ul><li>- [X] </li></ul> | Create 22.02 branch | 2021-11-22 | 2021-11-23 | @pxLi | 
|<ul><li>- [X] </li></ul> | Automerge from 21.12 to 22.02 | 2021-11-23 | 2021-11-26 | @pxLi | 
|<ul><li>- [X] </li></ul> | Enable Jenkins builds (premerge, nightly, integration, performance) for 22.02 | 2021-11-22 | 2021-11-26 | @pxLi | 
|<ul><li>- [X] </li></ul> | Virtual review | 2021-11-29 | 2021-12-10 |@krajendrannv | 
|<ul><li>- [X] </li></ul> | [cudf 21.12] Java release to sonatype | 2021-12-06 | 2021-12-06 | @NvTimLiu | 
|<ul><li>- [X] </li></ul> | Notify RAPIDS team of javadocs for 21.12 | 2021-12-06 | 2021-12-07 | @GaryShen2008 | 
|**Staging release**||||
|<ul><li>- [X] </li></ul> | Make 22.02 the default branch | 2021-11-29 | 2021-11-29 | @jlowe | 
|<ul><li>- [X] </li></ul> | Merge all remaining branch-21.12 PRs | 2021-11-24 | 2021-11-24 | Team | 
|<ul><li>- [X] </li></ul> | Update cudf JNI dependency version | 2021-12-03 | 2021-12-03 | @pxLi | 
|<ul><li>- [X] </li></ul> | Create CHANGELOG.md | 2021-12-03 | 2021-12-03 | @pxLi | 
|<ul><li>- [X] </li></ul> | Deliver Snapshot packages to QA | 2021-11-25 | 2021-11-25 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Create a PR (not squashed) to merge from branch-21.12 to main. Needs review from repository owner | 2021-12-03 | 2021-12-03 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Trigger the release Jenkins job on the main branch and deploy the jar to sonatype staging | 2021-12-06 | 2021-12-06 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Deliver final packages to QA | 2021-12-06 | 2021-12-06 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Run integration tests on staging jars with AQE on, UCX on, Databricks Azure, Databricks AWS, Dataproc | 2021-12-06 | 2021-12-10 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Run LHA tests on staging jars | 2021-12-06 | 2021-12-10 | @NvTimLiu| 
|<ul><li>- [x] </li></ul> | QA testing with Snapshot on YARN, NGC with Volta and Ampere | 2021-11-29 | 2021-12-06 | @yuange98|  
|<ul><li>- [X] </li></ul> | Run pre-processing workflow for [DLRM sample use case](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Recommendation/DLRM#advanced)| 2021-12-06 | 2021-12-10 | @johnzhong |  
|<ul><li>- [x] </li></ul> | QA testing with final packages on YARN, NGC with Volta and Ampere | 2021-12-06 | 2021-12-10 | @yuange98|  
|**Release**| | | | |  
|<ul><li>- [X] </li></ul> | Tag the release and deploy the staging artifacts to maven central repository | 2021-12-15 | 2021-12-15 | @NvTimLiu|
|<ul><li>- [X] </li></ul> | CDH testing | 2021-12-13 | 2021-12-15 | @tgravescs | 
|<ul><li>- [X] </li></ul> | Update gh-pages | 2021-12-13 | 2021-12-15 | @viadea   |  
|<ul><li>- [X] </li></ul> | Test [spark-rapids-examples repo](https://github.com/NVIDIA/spark-rapids-examples) with Spark-Rapids 21.12 | 2021-12-13 | 2021-12-15 | @nvliyuan  | 
|<ul><li>- [X] </li></ul> | Update docs for current release in spark-rapids-examples | 2021-12-13 | 2021-12-15 | @GaryShen2008|
|<ul><li>- [X] </li></ul> | Update rapids.sh in https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/rapids for the plugin (https://github.com/GoogleCloudDataproc/initialization-actions/pull/955)| 2021-12-13 | 2021-12-15 | @viadea |

**Comment by pxLi** [comment]
since cudf delayed the 21.12 code freeze, and cudfjni 22.02 is not ready yet, we will also delay the cudfjni 22.02 CICD setup

**Comment by viadea** [comment]
For GCP i filed https://github.com/GoogleCloudDataproc/initialization-actions/pull/955 instead. @nvliyuan  FYI.

**Comment by nvliyuan** [comment]
- tests spark-rapids-examples microbenchmark against v21.12 released jars on internal cluster, works well.
- draft [pr](https://github.com/NVIDIA/spark-rapids-examples/pull/64) to update doc
- thanks @viadea for updating GCP init script(I have some issue with google CLA with nvidia account and my [pr](https://github.com/GoogleCloudDataproc/initialization-actions/pull/952) is closed)
