### ISSUE TITLE
[FEA] Add support for HiveTableScanExec

### ISSUE THREAD

**Issue by sybest1259** [NVIDIA/spark-rapids#4025]
**Describe the bug**

**Steps/Code to reproduce bug**
**this is my configuration of pyspark shell**
``` console
pyspark --jars /root/hadoop/mysql-connector-java-5.1.37-bin.jar,/root/downloads/rapids-4-spark_2.12-21.10.0.jar,/root/downloads/cudf-21.10.0.jar,/root/downloads/rapids-4-spark-tools_2.12-21.10.0.jar,/root/downloads/xgboost4j_3.0-1.4.2-0.1.0.jar,/root/downloads/xgboost4j-spark_3.0-1.4.2-0.1.0.jar --master yarn --deploy-mode client  --num-executors 2 --executor-cores 1 --executor-memory 1g --driver-memory 1g \
--conf spark.sql.session.timeZone=UTC \
--conf spark.driver.extraJavaOptions=-Duser.timezone=UTC \
--conf spark.executor.extraJavaOptions=-Duser.timezone=UTC \
--conf spark.plugins=com.nvidia.spark.SQLPlugin         \
--conf spark.kryo.registrator=com.nvidia.spark.rapids.GpuKryoRegistrator \
--conf spark.resources.discoveryPlugin=com.nvidia.spark.ExclusiveModeGpuDiscoveryPlugin \
--conf spark.rapids.shims-provider-override=com.nvidia.spark.rapids.shims.spark312.SparkShimServiceProvider \
--conf spark.rapids.memory.gpu.pooling.enabled=true    \
--conf spark.rapids.python.memory.gpu.allocFraction=0.8 \
--conf spark.rapids.python.memory.gpu.maxAllocFraction=0.9 \
--conf spark.executor.resource.gpu.amount=1   \
--conf spark.task.resource.gpu.amount=0.5 \
--conf spark.executor.resource.gpu.discoveryScript=/root/hadoop/getGpusResources_executor.sh \
--conf spark.rapids.sql.enabled=true  \
--conf spark.rapids.sql.incompatibleOps.enabled=true \
--conf spark.rapids.sql.concurrentGpuTasks=2 \
--conf spark.rapids.sql.udfCompiler.enabled=true \
--conf spark.rapids.sql.format.csv.read.enabled=true \
--conf spark.rapids.sql.format.csv.enabled=true \
--conf spark.rapids.sql.variableFloatAgg.enabled=true \
--conf spark.rapids.sql.explain=ALL \
--conf spark.rapids.sql.batchSizeBytes=512M \
--conf spark.sql.hive.convertMetastoreParquet=true \
--py-files /root/downloads/sparkxgb.zip
```
**then I run sparksql(connect to hive, saprk thrift server)**
``` scala
df=spark.sql("""
select "1015a" `station`, t1.d1 `datetime`, cast(t1.`1015a_O3` as int) `O3`, cast(t2.`1015a_PM10` as int) `PM10`,
cast(t3.`1015a_PM25` as int) `PM25`,cast(t4.`1015a_SO2` as int) `SO2`,cast(t5.`1015a_NO2` as int) `NO2`,
cast(t6.`1015a_CO` as float) `CO`, cast(t7.`1015a_CO` as int) `target`
from
(select `datetime` as d1,`1053a` as `1015a_O3` from aq_station where  `type`="O3") t1
join 
(select `datetime` as d2,`1015a` as `1015a_PM10` from aq_station  where  `type`="PM10") t2
on (t1.d1=t2.d2)
join 
(select `datetime` as d3,`1015a` as `1015a_PM25` from aq_station  where  `type`="PM2.5") t3
on (t1.d1=t3.d3)
join 
(select `datetime` as d4,`1015a` as `1015a_SO2` from aq_station  where `type`="SO2") t4
on (t1.d1=t4.d4)
join 
(select `datetime` as d5,`1015a` as `1015a_NO2` from aq_station  where  `type`="NO2") t5
on (t1.d1=t5.d5)
join 
(select `datetime` as d6,`1015a` as `1015a_CO` from aq_station  where `type`="CO") t6
on (t1.d1=t6.d6)
order by `datetime`
""")
```
**I got such errors:**
``` console
 !NOT_FOUND <HiveTableScanExec> cannot run on GPU because no GPU enabled version of operator class org.apache.spark.sql.hive.execution.HiveTableScanExec could be found
                                                        @Expression <AttributeReference> datetime#3451 could run on GPU
                                                        @Expression <IsNotNull> isnotnull(type#3453) could run on GPU
                                                          @Expression <AttributeReference> type#3453 could run on GPU
                                                        @Expression <EqualTo> (type#3453 = PM10) could run on GPU
                                                          @Expression <AttributeReference> type#3453 could run on GPU
                                                          @Expression <Literal> PM10 could run on GPU
                                            *Exec <BroadcastExchangeExec> will run on GPU
                                              *Exec <ProjectExec> will run on GPU
                                                *Expression <Alias> datetime#5165 AS d3#4 will run on GPU
                                                *Exec <FilterExec> will run on GPU
                                                  *Expression <IsNotNull> isnotnull(datetime#5165) will run on GPU
```
**Expected behavior**
The code should work.

**Environment details (please complete the following information)**
 - Environment location: YARN, hadoop3.2.2, hive3.1.2, spark3.1.2, scala2.12.11
 - Spark configuration settings related to the issue

**Additional context**
I want to run the code on gpu, but now it is still run on cpu.

**Comment by sybest1259** [comment]
the spark settings above allocated two gpus, when I run sparksql, the volatile gpu-util of each gpu is 5%

**Comment by sybest1259** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:04:00.0 Off |                  N/A |
| 27%   30C    P8     5W / 260W |  10233MiB / 11019MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:05:00.0 Off |                  N/A |
| 27%   31C    P8    21W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:08:00.0 Off |                  N/A |
| 27%   31C    P8     5W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:09:00.0 Off |                  N/A |
| 27%   31C    P8    21W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:85:00.0 Off |                  N/A |
| 27%   33C    P8    21W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:86:00.0 Off |                  N/A |
| 27%   32C    P8     7W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  Off  | 00000000:89:00.0 Off |                  N/A |
| 27%   31C    P8     5W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:8A:00.0 Off |                  N/A |
| 27%   32C    P8     1W / 260W |      1MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      4091      G   /usr/lib/xorg/Xorg                 33MiB |
|    0   N/A  N/A      8262      C   ...0-openjdk-amd64//bin/java    10195MiB |
+-----------------------------------------------------------------------------+

**Comment by jlowe** [comment]
Thanks for the report, @sybest1259!

> The code should work.

To clarify, did the query not execute correctly even with the table scan being performed by the CPU?

**Comment by sybest1259** [comment]
**Thanks for your anwser, @jlowe**

**I run pysparkshell with 2 cpu cores and 2 gpu cards, the sql statement is simple, it took about 1 minute to finish the job with the warning above. GPU-Util is very low but cpu is very high.**

**I got jars from https://mvnrepository.com/: rapids-4-spark_2.12-21.10.0.jar, cudf-21.10.0-cuda11.jar**
when I check pom.xml in the source code of rapids-4-spark and cudf from https://github.com/NVIDIA/spark-rapids and https://github.com/rapidsai/cudf/tree/branch-21.10, I find that the default version of scala is 2.12.8, spark is 3.0.1. I wonder if I need to change their version to 2.12.11 and 3.1.2(I am using now), if that warning is  due to the incompatible compilation.

**Comment by sybest1259** [comment]
**I have tried to recompile rapids-4-spark_2.12-21.10.0.jar with spark3.1.2(I also have changed <hive.storage.api.version>2.8.1</hive.storage.api.version> in pom.xml), but it still do not work. I got the same warning :** !NOT_FOUND <HiveTableScanExec> cannot run on GPU because no GPU enabled version of operator class org.apache.spark.sql.hive.execution.HiveTableScanExec could be found

**Comment by sybest1259** [comment]
**when I use the command below, the job takes 10 seconds. So I think GPU is not really used**

pyspark --jars /root/hadoop/mysql-connector-java-5.1.37-bin.jar --master yarn --deploy-mode client  --num-executors 20 --executor-cores 2 --executor-memory 2g --driver-memory 10g

**Comment by jlowe** [comment]
> it took about 1 minute to finish the job with the warning above. GPU-Util is very low but cpu is very high.

So the query did complete successfully despite the warning?  That is the expected behavior.  The warning is not an error, it's just informing the user that the `HiveTableScanExec` in the query plan will not be replaced because the GPU does not support that query operation yet.  This warning would not be emitted at all with the default settings for `spark.rapids.sql.explain`.  It arguably should be an info-level message, but `spark-shell` by default suppresses all logging below warnings, so we decided to log it at a warning level so users would see it even in the shell.

> I wonder if I need to change their version to 2.12.11 and 3.1.2(I am using now), if that warning is due to the incompatible compilation.

The warning is not due to an incompatible compilation.  The message is correctly stating that there is no GPU override for `HiveTableScanExec`.  The RAPIDS Accelerator does not support that query operation, so it is falling back to the CPU implementation to ensure the query still runs.

It sounds like this query is operating properly (i.e.: producing the correct results) but processing it mostly on the CPU because the RAPIDS Accelerator does not yet support `HiveTableScanExec`.  If so, this is technically a feature request and not a bug, as the RAPIDS Accelerator does not claim that every query operation is supported by the RAPIDS Accelerator.  See the [supported operations document](https://nvidia.github.io/spark-rapids/docs/supported_ops.html) for details on what specific query operations and types are supported by the RAPIDS Accelerator.

I'm updating this to a feature request, and we can look into what it would take to support accelerating `HiveTableScanExec` with RAPIDS.

**Comment by sybest1259** [comment]
Thanks very much. @jlowe
Spark-rapids is quite a useful tool, it could bring us efficience and convenience.
As my team is working on sparksql-on-gpu, we look forward to the development of this function as soon as possible.
I‘d like to convey my heartfelt gratitude to all the developers.

**Comment by wbo4958** [comment]
@sybest1259 

I can't repro when just simply reading a hive and doing join. Could you provide a minimum repro step about how to create the hive table and the data?  Thx

**Comment by sybest1259** [comment]
**I created table in hive shell:**
CREATE external TABLE `aq_station` (`date` string,`hour` int,`1013a` string,`1014a`,...,`2882a` string, `datetime` TIMESTAMP) partitioned by(`year` int,`type` string);

**Then I imported data into table via pysaprk:**
from pyspark.sql import HiveContext
from pyspark import SparkContext
from pyspark import SparkConf
from pyspark.sql import SparkSession
spark = SparkSession.builder.config("hive.metastore.uris","thrift://10.1.11.114:9083").config("hive.exec.dynamic.partition.mode","nonstrict").config("spark.sql.storeAssignmentPolicy","LEGACY").appName("Python Spark").enableHiveSupport().getOrCreate()
spark.sql("use weatherpollution")
df = spark.read.format('com.databricks.spark.csv').options(header='true', inferschema='true').load("hdfs://mycluster/user/yjy2021/aq_station.csv",header=True)
df.write.insertInto('weatherpollution.aq_station', overwrite=False)

**Here is the sample data**
[aq_demo.csv](https://github.com/NVIDIA/spark-rapids/files/7535126/aq_demo.csv)

**Comment by wbo4958** [comment]
Thx @sybest1259, 

Previously,  Spark default to FileSourceScanExec when reading from hive table backended by Parquet (we can also tune the conf spark.sql.hive.convertMetastoreParquet to fallback to HiveTableScanExec). So I can't repro it. 

Now I tried with CSV, and can repro.

**Comment by wbo4958** [comment]
The hive table backed by parquet/orc will be converted to HadoopFsRelation by default which will finally be converted to FileSourceScanExec, and it can be replaced by GPU. 

But if the hive table is backed by other types will be converted to HiveTableRelation and finally be planed to HiveTableScanExec which is not supported by GPU for now.

@sybest1259, For now, maybe you can convert your data into parquet/orc, and alter your table stored as parquet or orc

**Comment by sybest1259** [comment]
Thx @wbo4958

Sorry for replying late, I just came back from a business trip.
I will follow your advice to rebuild the data. 
Thanks very much.

**Comment by sybest1259** [comment]
**I have rebuilt the table that backed by parquet:**

CREATE external TABLE aq_station (date string,hour int,1013a string,1014a,...,2882a string, datetime TIMESTAMP) partitioned by(year int,type string) STORED AS PARQUET;

**Now use FileSourceScanExec instead of HiveTableScanExec**

*Exec <TakeOrderedAndProjectExec> will run on GPU
  *Expression <SortOrder> datetime#15 ASC NULLS FIRST will run on GPU
  *Expression <Alias> 1015a AS station#13827 will run on GPU
  *Expression <Alias> cast(datetime#15 as string) AS datetime#13835 will run on GPU
    *Expression <Cast> cast(datetime#15 as string) will run on GPU
  *Expression <Alias> cast(O3#16 as string) AS O3#13828 will run on GPU
    *Expression <Cast> cast(O3#16 as string) will run on GPU
  *Expression <Alias> cast(PM10#17 as string) AS PM10#13829 will run on GPU
    *Expression <Cast> cast(PM10#17 as string) will run on GPU
  *Expression <Alias> cast(PM25#18 as string) AS PM25#13830 will run on GPU
    *Expression <Cast> cast(PM25#18 as string) will run on GPU
  *Expression <Alias> cast(SO2#19 as string) AS SO2#13831 will run on GPU
    *Expression <Cast> cast(SO2#19 as string) will run on GPU
  *Expression <Alias> cast(NO2#20 as string) AS NO2#13832 will run on GPU
    *Expression <Cast> cast(NO2#20 as string) will run on GPU
  *Expression <Alias> cast(CO#21 as string) AS CO#13833 will run on GPU
    *Expression <Cast> cast(CO#21 as string) will run on GPU
  *Expression <Alias> cast(target#22 as string) AS target#13834 will run on GPU
    *Expression <Cast> cast(target#22 as string) will run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> d1#0 AS datetime#15 will run on GPU
    *Expression <Alias> cast(1015a_O3#1 as int) AS O3#16 will run on GPU
      *Expression <Cast> cast(1015a_O3#1 as int) will run on GPU
    *Expression <Alias> cast(1015a_PM10#3 as int) AS PM10#17 will run on GPU
      *Expression <Cast> cast(1015a_PM10#3 as int) will run on GPU
    *Expression <Alias> cast(1015a_PM25#5 as int) AS PM25#18 will run on GPU
      *Expression <Cast> cast(1015a_PM25#5 as int) will run on GPU
    *Expression <Alias> cast(1015a_SO2#7 as int) AS SO2#19 will run on GPU
      *Expression <Cast> cast(1015a_SO2#7 as int) will run on GPU
    *Expression <Alias> cast(1015a_NO2#9 as int) AS NO2#20 will run on GPU
      *Expression <Cast> cast(1015a_NO2#9 as int) will run on GPU
    *Expression <Alias> cast(1015a_CO#11 as float) AS CO#21 will run on GPU
      *Expression <Cast> cast(1015a_CO#11 as float) will run on GPU
    *Expression <Alias> cast(1015a_CO#13 as int) AS target#22 will run on GPU
      *Expression <Cast> cast(1015a_CO#13 as int) will run on GPU
    *Exec <BroadcastHashJoinExec> will run on GPU
      *Exec <ProjectExec> will run on GPU
        *Exec <BroadcastHashJoinExec> will run on GPU
          *Exec <ProjectExec> will run on GPU
            *Exec <BroadcastHashJoinExec> will run on GPU
              *Exec <ProjectExec> will run on GPU
                *Exec <BroadcastHashJoinExec> will run on GPU
                  *Exec <ProjectExec> will run on GPU
                    *Exec <BroadcastHashJoinExec> will run on GPU
                      *Exec <ProjectExec> will run on GPU
                        *Exec <BroadcastHashJoinExec> will run on GPU
                          *Exec <BroadcastExchangeExec> will run on GPU
                            *Exec <ProjectExec> will run on GPU
                              *Expression <Alias> datetime#1734 AS d1#0 will run on GPU
                              *Expression <Alias> 1053a#65 AS 1015a_O3#1 will run on GPU
                              *Exec <FilterExec> will run on GPU
                                *Expression <IsNotNull> isnotnull(datetime#1734) will run on GPU
                                *Exec <FileSourceScanExec> will run on GPU
                          *Exec <ProjectExec> will run on GPU
                            *Expression <Alias> datetime#3448 AS d2#2 will run on GPU
                            *Expression <Alias> 1015a#1741 AS 1015a_PM10#3 will run on GPU
                            *Exec <FilterExec> will run on GPU
                              *Expression <IsNotNull> isnotnull(datetime#3448) will run on GPU
                              *Exec <FileSourceScanExec> will run on GPU
                      *Exec <BroadcastExchangeExec> will run on GPU
                        *Exec <ProjectExec> will run on GPU
                          *Expression <Alias> datetime#5162 AS d3#4 will run on GPU
                          *Expression <Alias> 1015a#3455 AS 1015a_PM25#5 will run on GPU
                          *Exec <FilterExec> will run on GPU
                            *Expression <IsNotNull> isnotnull(datetime#5162) will run on GPU
                            *Exec <FileSourceScanExec> will run on GPU
                  *Exec <BroadcastExchangeExec> will run on GPU
                    *Exec <ProjectExec> will run on GPU
                      *Expression <Alias> datetime#6876 AS d4#6 will run on GPU
                      *Expression <Alias> 1015a#5169 AS 1015a_SO2#7 will run on GPU
                      *Exec <FilterExec> will run on GPU
                        *Expression <IsNotNull> isnotnull(datetime#6876) will run on GPU
                        *Exec <FileSourceScanExec> will run on GPU
              *Exec <BroadcastExchangeExec> will run on GPU
                *Exec <ProjectExec> will run on GPU
                  *Expression <Alias> datetime#8590 AS d5#8 will run on GPU
                  *Expression <Alias> 1015a#6883 AS 1015a_NO2#9 will run on GPU
                  *Exec <FilterExec> will run on GPU
                    *Expression <IsNotNull> isnotnull(datetime#8590) will run on GPU
                    *Exec <FileSourceScanExec> will run on GPU
          *Exec <BroadcastExchangeExec> will run on GPU
            *Exec <ProjectExec> will run on GPU
              *Expression <Alias> datetime#10304 AS d6#10 will run on GPU
              *Expression <Alias> 1015a#8597 AS 1015a_CO#11 will run on GPU
              *Exec <FilterExec> will run on GPU
                *Expression <IsNotNull> isnotnull(datetime#10304) will run on GPU
                *Exec <FileSourceScanExec> will run on GPU
      *Exec <BroadcastExchangeExec> will run on GPU
        *Exec <ProjectExec> will run on GPU
          *Expression <Alias> datetime#12018 AS d7#12 will run on GPU
          *Expression <Alias> 1015a#10311 AS 1015a_CO#13 will run on GPU
          *Exec <FilterExec> will run on GPU
            *Expression <IsNotNull> isnotnull(datetime#12018) will run on GPU
            *Exec <FileSourceScanExec> will run on GPU

**But I still found a problem, I ran pyspark shell with 2 GPU cards(GeForce RTX 2080 Ti).
GPU-Util is still very low(1%-7%), the running time of the job is still a bit long, took about 1 minute. 
Are there some other configuration problems?**

**Comment by jlowe** [comment]
> GPU-Util is still very low(1%-7%), the running time of the job is still a bit long, took about 1 minute.

Without more information, my guess is that this query is I/O bound, i.e.: almost all of the time is spent accessing the input from the distributed filesystem.

Can you take a look a the Spark web UI for the job, specifically the SQL tab showing the graph of the query plan?  There should be metrics on each node showing how much time was spent in various steps of processing for the node (e.g.: buffering time, GPU decode time for the Parquet load).  It would be interesting to check how much time is being reported for the metrics and where all the time appears to be spent for the query.  With such a low GPU utilization I suspect you'll see it's almost all in buffer time (i.e.: time spent reading in the distributed filesystem data).

If you want to see low-level details of what's going on with the GPU, you can try capturing an Nsight Systems profile of an executor.  See the [developer docs on capturing Nsight Systems profiles](https://github.com/NVIDIA/spark-rapids/blob/branch-21.12/docs/dev/nvtx_profiling.md) for more information.  If you are not building your own custom cudf jar you can skip the first step since we now ship the official cudf artifact with NVTX code included.

**Comment by sybest1259** [comment]
![GpuScan](https://user-images.githubusercontent.com/41052224/144954112-f1bafa07-9ad7-40ca-a69f-7e9e0bfbed9f.JPG)

![GpuFilter](https://user-images.githubusercontent.com/41052224/144954124-0c51990f-6e5a-4c97-96b4-5807cb7153d2.JPG)

![GpuCoalesceBatches](https://user-images.githubusercontent.com/41052224/144954132-62f06f47-9c63-41df-b730-294d7c15bc0c.JPG)

![GpuProject](https://user-images.githubusercontent.com/41052224/144954148-45052808-8035-43f6-aa47-c3bcf2bcb9cf.JPG)

![GpuBroadcastExchange](https://user-images.githubusercontent.com/41052224/144954158-a920e1d8-3f4e-46d8-9fcf-e264c5edde71.JPG)

![GpuBroadcastHashJoin](https://user-images.githubusercontent.com/41052224/144954166-1cacdf32-074d-4c93-95c8-872a1b30c2fe.JPG)

**Comment by wbo4958** [comment]
The configuration "--executor-cores 1 --executor-memory 1g" may have restricted the parallel, which means at any time there is only 1 task running on each Executor.

You can change to "--executor-cores 12 --executor-memory 30g" according to your real physical env.
and then add the below configurations when submitting

``` console
  --conf spark.task.cpus=1
  --conf spark.executor.resource.gpu.amount=1
  --conf spark.task.resource.gpu.amount=0.08
  --conf spark.rapids.sql.concurrentGpuTasks=2
```
`spark.task.resource.gpu.amount=0.08` is calculated by `1/12`

**Comment by wbo4958** [comment]
@sybest1259 Have you tried the configurations I provided in https://github.com/NVIDIA/spark-rapids/issues/4025#issuecomment-987518881 ?

**Comment by sybest1259** [comment]
**Thx, @wbo4958** 
I have tried new configurations with your advice. As the CPU of nodes in the cluster is limited to 8 cores，I set **--conf park.task.resource.gpu.amount=0.125**  **--executor-cores** 12

**The entire configurations below**
pyspark --jars /root/hadoop/mysql-connector-java-5.1.37-bin.jar,/root/downloads/rapids-4-spark_2.12-21.10.0-SNAPSHOT.jar,/root/downloads/cudf-21.10.0-cuda11.jar,/root/downloads/xgboost4j-spark-gpu_2.12-1.6.0-SNAPSHOT.jar,/root/downloads/xgboost4j-gpu_2.12-1.6.0-SNAPSHOT.jar,/root/downloads/jpmml-xgboost-1.5.6.jar,/root/downloads/jpmml-sparkml-1.8.0.jar --master yarn --deploy-mode client  --num-executors 2 --executor-cores 8 --executor-memory 12g --driver-memory 10g \
--conf spark.sql.session.timeZone=UTC \
--conf spark.driver.extraJavaOptions=-Duser.timezone=UTC \
--conf spark.executor.extraJavaOptions=-Duser.timezone=UTC \
--conf spark.plugins=com.nvidia.spark.SQLPlugin         \
--conf spark.kryo.registrator=com.nvidia.spark.rapids.GpuKryoRegistrator \
--conf spark.resources.discoveryPlugin=com.nvidia.spark.ExclusiveModeGpuDiscoveryPlugin \
--conf spark.rapids.shims-provider-override=com.nvidia.spark.rapids.shims.spark312.SparkShimServiceProvider \
--conf spark.rapids.memory.gpu.pooling.enabled=true    \
--conf spark.task.cpus=1 \
--conf spark.rapids.python.memory.gpu.allocFraction=0.8 \
--conf spark.rapids.python.memory.gpu.maxAllocFraction=0.9 \
--conf spark.executor.resource.gpu.amount=1   \
--conf spark.task.resource.gpu.amount=0.125 \
--conf spark.executor.resource.gpu.discoveryScript=/root/hadoop/getGpusResources_executor.sh \
--conf spark.rapids.sql.enabled=true  \
--conf spark.rapids.sql.incompatibleOps.enabled=true \
--conf spark.rapids.sql.concurrentGpuTasks=2 \
--conf spark.rapids.sql.udfCompiler.enabled=true \
--conf spark.rapids.sql.format.csv.read.enabled=true \
--conf spark.rapids.sql.format.csv.enabled=true \
--conf spark.rapids.sql.variableFloatAgg.enabled=true \
--conf spark.rapids.sql.explain=ALL \
--conf spark.rapids.sql.batchSizeBytes=512M \
--conf spark.sql.hive.convertMetastoreParquet=true \
--conf spark.rapids.sql.castFloatToString.enabled=true \
--conf spark.rapids.sql.csv.read.float.enabled=true \
--conf spark.rapids.sql.castStringToFloat.enabled=true \
--py-files /root/downloads/sparkxgb2.zip 

**I ran the task 3 times，the task duration reduced to 11 seconds.**
![sparksql](https://user-images.githubusercontent.com/41052224/145913966-d71ec452-2595-4ecd-93b8-993122577e5d.JPG)
**But I still wonder if it's because of the increase of CPU.**

**Comment by wbo4958** [comment]
The configurations enable more spark tasks executed parallelly.  @sybest1259

**Comment by sybest1259** [comment]
Thx @wbo4958 
I'm testing now and  I'll ask you if I have any problems.
Thanks to all developers.
