### ISSUE TITLE
[AUDIT] SPARK-36351 not calling withFilters in 3.3.0

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#4026]
Apache Spark  SPARK-36351  isn't calling withFilters anymore in 3.3.0.  This implies we might not be getting the filters applied in Spark 3.3.0 because we don't implement the new api.

_Originally posted by @tgravescs in https://github.com/NVIDIA/spark-rapids/pull/4012#discussion_r741936020_

**Comment by nartal1** [comment]
Tested query with partioned and un-partitioned parquet files. 
For un-partitioned dataset, the datafilters are applied correctly in the query plan and only required columns are pushed down.
For partitioned dataset, both the datafilters and partition filters are applied correctly and the size of data read is smaller which confirms the pushdown is done correctly. 
Closing this issue as the filters are applied in the Rapids Accelerator as expected.
