### ISSUE TITLE
[FEA] support GpuCast from non-nested ArrayType to StringType

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#4028]
**Is your feature request related to a problem? Please describe.**

When selecting a non-nested ArrayType column and `show()` it, GpuCast doesn't support such casting:

```
!Expression <Cast> cast(feature_value_scale#1.values as string) cannot run on GPU because Cast from ArrayType(DoubleType,true) to StringType is not supported 
```

It seems all such non-nested array type castings are not supported. 

I'm asking this to understand the difficulty of the implementation, or do we have any plan for it? I didn't find any existing issue related.

**Additional context**
It's common to use `.show()` to take a quick look at the query results. But when the selected column is produced by a RapidsUDF and there's such an unsupported casting, the UDF will go to the row-wise process branch, which is unexpected.

```
  !Exec <ProjectExec> cannot run on GPU because not all expressions can be replaced
    @Expression <Alias> cast(transform(feature_value_scale#1.values) as string) AS pca_features#83 could run on GPU
      !Expression <Cast> cast(transform(feature_value_scale#1.values) as string) cannot run on GPU because Cast from ArrayType(DoubleTyp
        @Expression <ScalaUDF> transform(feature_value_scale#1.values) could run on GPU
          @Expression <GetStructField> feature_value_scale#1.values could run on GPU
            @Expression <AttributeReference> feature_value_scale#1 could run on GPU
    *Exec <FileSourceScanExec> will run on GPU

```

**Comment by sperlingxx** [comment]
If I am not wrong, we need cuDF to provide an API like 
`std::unique_ptr<cudf::column> make_string(const lists_column_view& list_column, const std::string& separator)`.

**Comment by HaoYang670** [comment]
![image](https://user-images.githubusercontent.com/59198230/141754955-58582203-ab58-4616-9b8b-c0651b44a135.png)
This is an example of casting from array of Integer to String. As the implementation of ArrayType in cudf is list_column, we need one method to cast elements in list_column to Char or string. Also we need a method to cast list_column to string column

**Comment by revans2** [comment]
The casting code can get a little complicated.  If you look at the code for casting a Struct to a String it recursively calls cast on each element in the struct and then will concatenate them for a final output.

https://github.com/NVIDIA/spark-rapids/blob/6de2378ab514a366988052887ba940370e309889/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala#L661-L679

We ideally want to do something similar.  Happily, the cast code already supports cast one array/list type to another.

https://github.com/NVIDIA/spark-rapids/blob/6de2378ab514a366988052887ba940370e309889/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala#L522-L527

So, I would suggest that you just call doCast​ recursively to cast the elements of the array to a String first.  And then you can call `stringConcatenateListElements` to create the list of values.

https://github.com/rapidsai/cudf/blob/49d1cc28648fe676dbddcf27c01939f87122ed8e/java/src/main/java/ai/rapids/cudf/ColumnView.java#L2392

or

https://github.com/rapidsai/cudf/blob/49d1cc28648fe676dbddcf27c01939f87122ed8e/java/src/main/java/ai/rapids/cudf/ColumnView.java#L2419

I think the second API will give you enough control to do everything you need to do. But if not there are ways to manipulate elements in an array/list separate from the list itself. If you hit that situation, just ask and I can show you how to do it.

I hope this helps,

Bobby

________________________________

**Comment by HaoYang670** [comment]
https://github.com/rapidsai/cudf/issues/9745
I create an issue on CUDF, discussing what stringConcatenateListElements should return when the input list contains all null elements

**Comment by HaoYang670** [comment]
One problem I meet is that, when `legacyCastToString = true`, the separator is `", "` for not null elements and `","` for null element. I am a little confused how to introduce 2 kinds of separators.
