### ISSUE TITLE
[FEA] Support spark.sql.parquet.binaryAsString=true

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#4040]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish the RAPIDS Accelerator for Apache Spark would [...]
Support spark.sql.parquet.binaryAsString=true.

```
!Exec <FileSourceScanExec> cannot run on GPU because GpuParquetScan does not support spark.sql.parquet.binaryAsString
```

**Comment by viadea** [comment]
1. Create a table with only int and string:

```
spark-sql> create table teststring2 stored as parquet  as select * from teststring;
spark-sql> select * from teststring2 ;
1	abcd

spark-sql> desc teststring2 ;
x	int	NULL
y	string	NULL
```

2. Enable spark.sql.parquet.binaryAsString and run the query:

```
spark-sql> set spark.sql.parquet.binaryAsString=true;
spark-sql> select * from teststring2 ;
21/11/05 07:01:37 WARN GpuOverrides:
!Exec <FileSourceScanExec> cannot run on GPU because GpuParquetScan does not support spark.sql.parquet.binaryAsString

1	abcd
Time taken: 0.146 seconds, Fetched 1 row(s)
```

**Comment by SurajAralihalli** [comment]
Adding Binary Type test

```
val ipaddr = Array[Byte](1,3,4)
Seq(ipaddr).toDF("name").write.format("parquet").mode("overwrite").save("/local/saralihalli/tmp/testParquet4/")
spark.read.parquet("/local/saralihalli/tmp/testParquet4/").createTempView("df4")
spark.conf.set("spark.sql.parquet.binaryAsString",false)
spark.sql("select * from df4").collect
spark.read.parquet("/local/saralihalli/tmp/testParquet4/").createTempView("df5")
spark.conf.set("spark.sql.parquet.binaryAsString",true)
spark.sql("select * from df5").collect
```

**Comment by NVnavkumar** [comment]
> Adding Binary Type test
> 
> ```
> val ipaddr = Array[Byte](1,3,4)
> Seq(ipaddr).toDF("name").write.format("parquet").mode("overwrite").save("/local/saralihalli/tmp/testParquet4/")
> spark.read.parquet("/local/saralihalli/tmp/testParquet4/").createTempView("df4")
> spark.conf.set("spark.sql.parquet.binaryAsString",false)
> spark.sql("select * from df4").collect
> spark.read.parquet("/local/saralihalli/tmp/testParquet4/").createTempView("df5")
> spark.conf.set("spark.sql.parquet.binaryAsString",true)
> spark.sql("select * from df5").collect
> ```
> 
> **For binary Type data**
> 
> Summary With `rapids-4-spark_2.12-22.08.0-20220714.123703-28.jar` and `spark.sql.parquet.binaryAsString` set to
> 
> 1. False: yes there is fallback
> 2. True: yes there is fallback
> 
> ```
> scala> val ipaddr = Array[Byte](1,3,4)
> ipaddr: Array[Byte] = Array(1, 3, 4)
> 
> scala> Seq(ipaddr).toDF("name").write.format("parquet").mode("overwrite").save("/local/saralihalli/tmp/testParquet4/")
> 22/07/14 18:57:18 WARN GpuOverrides:
> !Exec <DataWritingCommandExec> cannot run on GPU because not all data writing commands can be replaced; unsupported data types in input: BinaryType [name#21]
>   !Output <InsertIntoHadoopFsRelationCommand> cannot run on GPU because unsupported data types BinaryType [name] in write for Parquet
>   ! <LocalTableScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.LocalTableScanExec; not all expressions can be replaced
>     !Expression <AttributeReference> name#21 cannot run on GPU because expression AttributeReference name#21 produces an unsupported type BinaryType
> 
> 
> scala> spark.read.parquet("/local/saralihalli/tmp/testParquet4/").createTempView("df4")
> 
> scala> spark.conf.set("spark.sql.parquet.binaryAsString",false)
> 
> scala> spark.sql("select * from df4").collect
> 22/07/14 18:57:18 WARN GpuOverrides:
> !Exec <FileSourceScanExec> cannot run on GPU because unsupported data types in output: BinaryType [name#24]; unsupported data types BinaryType [name] in read for Parquet
> 
> res10: Array[org.apache.spark.sql.Row] = Array([[B@21249add])
> 
> scala> spark.read.parquet("/local/saralihalli/tmp/testParquet4/").createTempView("df5")
> 
> scala> spark.conf.set("spark.sql.parquet.binaryAsString",true)
> 
> scala> spark.sql("select * from df5").collect
> 22/07/14 18:57:20 WARN GpuOverrides:
> !Exec <FileSourceScanExec> cannot run on GPU because unsupported data types in output: BinaryType [name#29]; unsupported data types BinaryType [name] in read for Parquet
> 
> res13: Array[org.apache.spark.sql.Row] = Array([[B@3e94ff8a])
> ```

So the way this flag works in Spark is that is specifically for *backwards* compatibility with older versions of Parquet. When I ran this in Spark on the CPU, this meant that when I wrote a parquet file from Spark that included a BINARY column, it would always be read back as a BINARY column (even when `spark.sql.parquet.binaryAsString=true`). I would suggest running this test on Spark without the plugin to confirm the schema when you read the parquet back.
