### ISSUE TITLE
Follow on items for Regex 

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#4075]
1. Throw a specific exception for the `None` match. _Originally posted by @jlowe in https://github.com/NVIDIA/spark-rapids/pull/4071#discussion_r746601861_

2. Consider to tighten the test to check for the specific expected result. Right now the test succeeds even with typos.

**Comment by jlowe** [comment]
This is being handled by #4071 per [this discussion](https://github.com/NVIDIA/spark-rapids/pull/4071#discussion_r746855678) and corresponding change.
