### ISSUE TITLE
[FEA] Change Explain to not print NOT_FOUND and to have some known CPU only tasks

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#4088]
We have had some feedback that in some cases with explain the NOT_FOUND is confusing. We should change this to print something about "this operator is not supported"

Along with that there are some known operators, like JDBC where we know we can never optimize it on the GPU and we should make the message more clear about how this is not a problem.

**Comment by mythrocks** [comment]
> `NOT_FOUND` is confusing...

`NOT_ON_GPU`? (Shares terminology with the flag for `EXPLAIN`.)
`NOT_ACCELERATED`?
`RTX_OFF`? :]
