### ISSUE TITLE
[FEA] Provide a better way to set JIT cache

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#41]
**Is your feature request related to a problem? Please describe.**
 libcudf supports writing to a separate place via the LIBCUDF_KERNEL_CACHE_PATH environment variable, but the plugin would need to find a way to get this set properly from configs before the library is loaded.

**Describe the solution you'd like**
a spark conf that allows the user to set this.

**Describe alternatives you've considered**
We could just document how to set this when launching your application.

**Comment by sameerz** [comment]
Add documentation recommendation for different clouds.

**Comment by revans2** [comment]
After JIT for binary ops is removed by CUDF I don't think this really matters any more.

https://github.com/NVIDIA/spark-rapids/issues/3174 was even filed to remove the docs for setting JIT because it will not be required.
