### ISSUE TITLE
[FEA] JSON: Basic Reader for String type

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#4135]
This is probably one of the largest tasks.  Once we have a CUDF API #4133 we need to start using it. I think the first type we would want to support is just strings.  Even then it will likely need to be off by default for compatibility reasons.

This will need to 

1. Setup a basic JSON reader similar to the CSV reader that uses the Hadoop Line Reader and possibly normalizes the line separation as it produces batches of data.  Ideally as much of this batching as possible should be generalized to a common class/trait that can be shared by both the CVS and JSON code.
2. Check the JSON config, similar to the CSV config, to verify that all of the settings are things that we can support.  If we run into issues where a default setting is not something that we can really support we will need to evaluate if this is an incompatibility that we just document or if it is something we have to fix/have off by default. Note that I initially looked at these [here](https://github.com/NVIDIA/spark-rapids/issues/9#issuecomment-959803463), but this was from reading the code. All of these should be verified once we actually have java APIs we can play with.
3. An extensive set of tests to verify that the string reading is working, and that we fall back to the CPU in various cases covered by the configs.  This might be a little hard because Spark itself does not have a great set of tests.

**Comment by nartal1** [comment]
blocked by https://github.com/rapidsai/cudf/issues/9990

**Comment by wbo4958** [comment]
For now, the experimental JSON reader can work, https://github.com/NVIDIA/spark-rapids/issues/4135 is merged. Close this issue
