### ISSUE TITLE
[FEA] JSON: Support for basic non-string types

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#4136]
After we have basic support for String #4135 we should add in support for other types. This can be broken down further as needed by type.

What we have to worry about is parsing of these types and how java/spark handle parsing compared to how CUDF does it. For some types like boolean, and possibly integers CUDF will probably be fine because it should be defined by the JSON specification. For other types like date/time and Decimal types we might need to read them as Strings and then cast them to a final result. I am not sure about floating point.  All of these are things that we need to test and investigate. If we do run into situations where we are not compatible for a given type we might need to add configs, like for CSV, where we can control per type if it is enabled or not.

**Comment by nartal1** [comment]
Experimental JSON reader works for basic non-string types in https://github.com/NVIDIA/spark-rapids/pull/4485. Closing.
