### ISSUE TITLE
[FEA] JSON: Documentation

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#4137]
After we have a decent amount of support for the different types #4136 we need some good documentation on incompatibilities and what not.  Hopefully we are fairly complaint and it is just odd corner cases that we  are not compatible with.

**Comment by wbo4958** [comment]
Sine the initialized PR to support JSON reader has merged, it has doc-ed the limitations and the unsupported types. And I just closed the PR.
