### ISSUE TITLE
[Audit][FEA][SPARK-36920] Enable GPU overrides for ANSI interval types in arithmetics expressions.

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#4151]
Enable ANSI interval types for ABS, DIV ...

**Comment by res-life** [comment]
- [ ] Abs: abs(interval)
- [ ] UnaryMinus: -interval
- [ ] Add: interval + interval
- [ ] Subtract: interval - interval
- [ ] Positive: +interval

// 2 new added operators
- [ ] interval * number
- [ ] interval / number
