### ISSUE TITLE
[FEA] Another look at infinity checking on casting string to float

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#4152]
https://github.com/rapidsai/cudf/pull/9694 is supposed to make checking for Inf case insensitive.  This should let us totally remove the normalization for infinity using a regular expression when casting from strings to floats.

This might not matter if we make our own string to float casting at some point in the future.

**Comment by HaoYang670** [comment]
Sorry, I read the code of `castStringToFloats` and `sanitizeStringToFloat` but don't find where "infinity" normalization is.

**Comment by jlowe** [comment]
This has already been handled by #4259.  See https://github.com/NVIDIA/spark-rapids/pull/4259/files#diff-e981882f5ee2f922528de849ae5397dd30e5bfe9dd5fdbe3421de4733a0eae1aL206-L218.
