### ISSUE TITLE
[BUG] Fix Spark 3.1.0 integration tests

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#416]
Depends on https://github.com/NVIDIA/spark-rapids/pull/414/

There are some integration tests failing against 3.1.0 and we just need to investigate and fix those.

**Comment by tgravescs** [comment]
see failures https://ci.ngcc.nvidia.com/job/spark/job/rapids_it-3.1.0-SNAPSHOT-0.2-github/2/console

**Comment by sameerz** [comment]
Issue #382 is one of the tests that is failing.

**Comment by tgravescs** [comment]
tests currently failing:

FAILED integration_tests/src/main/python/arithmetic_ops_test.py::test_log[Double][APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/arithmetic_ops_test.py::test_log1p[Double][APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/arithmetic_ops_test.py::test_log2[Double][APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/arithmetic_ops_test.py::test_log10[Double][APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/date_time_test.py::test_timesub[(-584, 1563)]
FAILED integration_tests/src/main/python/date_time_test.py::test_timesub[(1943, 1101)]
FAILED integration_tests/src/main/python/date_time_test.py::test_timesub[(2693, 2167)]
FAILED integration_tests/src/main/python/date_time_test.py::test_timesub[(2729, 0)]
FAILED integration_tests/src/main/python/date_time_test.py::test_timesub[(44, 1534)]
FAILED integration_tests/src/main/python/date_time_test.py::test_timesub[(2635, 3319)]
FAILED integration_tests/src/main/python/date_time_test.py::test_timesub[(1885, -2828)]
FAILED integration_tests/src/main/python/date_time_test.py::test_timesub[(0, 2463)]
FAILED integration_tests/src/main/python/date_time_test.py::test_timesub[(932, 2286)]
FAILED integration_tests/src/main/python/join_test.py::test_broadcast_join_mixed[FullOuter][IGNORE_ORDER]
FAILED integration_tests/src/main/python/orc_test.py::test_input_meta - py4j....
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.byteF, test_table1.byteF FULL JOIN test_table1 ON test_table.byteF=test_table1.byteF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.shortF, test_table1.shortF FULL JOIN test_table1 ON test_table.shortF=test_table1.shortF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.intF, test_table1.intF FULL JOIN test_table1 ON test_table.intF=test_table1.intF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.longF, test_table1.longF FULL JOIN test_table1 ON test_table.longF=test_table1.longF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.floatF, test_table1.floatF FULL JOIN test_table1 ON test_table.floatF=test_table1.floatF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.doubleF, test_table1.doubleF FULL JOIN test_table1 ON test_table.doubleF=test_table1.doubleF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.booleanF, test_table1.booleanF FULL JOIN test_table1 ON test_table.booleanF=test_table1.booleanF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.strF, test_table1.strF FULL JOIN test_table1 ON test_table.strF=test_table1.strF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.dateF, test_table1.dateF FULL JOIN test_table1 ON test_table.dateF=test_table1.dateF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.timestampF, test_table1.timestampF FULL JOIN test_table1 ON test_table.timestampF=test_table1.timestampF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
= 25 failed, 2211 passed, 168 skipped, 49 xfailed, 1 xpassed, 10 warnings in 2780.07s (0:46:20) =

**Comment by tgravescs** [comment]
https://issues.apache.org/jira/browse/SPARK-32640 filed for arithmetic ops

**Comment by tgravescs** [comment]
https://github.com/NVIDIA/spark-rapids/issues/574 filed for time sub functions

**Comment by tgravescs** [comment]
join test failure: https://github.com/NVIDIA/spark-rapids/issues/575

**Comment by tgravescs** [comment]
orc test failure: https://github.com/NVIDIA/spark-rapids/issues/576

**Comment by tgravescs** [comment]
https://github.com/NVIDIA/spark-rapids/issues/577 for arithmetic test failures

**Comment by tgravescs** [comment]
https://github.com/NVIDIA/spark-rapids/issues/578 is for the full outer join in qa test

**Comment by tgravescs** [comment]
so with this I'm xfailing all the failing tests above and we have specific issues to followup with each.
