### ISSUE TITLE
[BUG] ParseDateTimeSuite UT failed

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#4176]
**Describe the bug**
mvn  -Dbuildver=302 clean package -DwildcardSuites=com.nvidia.spark.rapids.ParseDateTimeSuite
mvn  -Dbuildver=312 clean package -DwildcardSuites=com.nvidia.spark.rapids.ParseDateTimeSuite

```
ParseDateTimeSuite:
- to_date dd/MM/yy (fall back)
- to_date yyyy-MM-dd *** FAILED ***
  Mismatch between CPU and GPU for the following rows:

  [#40] CPU: [1999-12-29
  ,null]
  [#40] GPU: [1999-12-29
  ,1999-12-29] (ParseDateTimeSuite.scala:302)
- to_date yyyy-MM-dd LEGACY
- to_date yyyy/MM/dd LEGACY
- to_date dd/MM/yyyy
- to_date dd/MM/yyyy LEGACY
- to_date parse date
- to_date parse timestamp
- to_timestamp yyyy-MM-dd *** FAILED ***
  Mismatch between CPU and GPU for the following rows:

  [#35] CPU: [1999-12-29
  ,null]
  [#35] GPU: [1999-12-29
  ,1999-12-29 00:00:00.0] (ParseDateTimeSuite.scala:302)
- to_timestamp dd/MM/yyyy
- to_date default pattern
- unix_timestamp parse date *** FAILED ***
  Mismatch between CPU and GPU for the following rows:

  [#35] CPU: [1999-12-29
  ,null]
  [#35] GPU: [1999-12-29
  ,946425600] (ParseDateTimeSuite.scala:302)
```

**Comment by revans2** [comment]
This appears to be for 22.02.0-SNAPSHOT and is not failing on 21.12

**Comment by tgravescs** [comment]
the failure here is caused when there is a newline in the string:

`val ts = Seq("1999-12-29\n")`

**Comment by tgravescs** [comment]
I am not positive on this but this commit is dealing with newline and is about the time our test started to fail:

https://github.com/rapidsai/cudf/commit/c1bfb26715e0234f6d90aceac7a52caded2e9f9e
https://github.com/rapidsai/cudf/issues/9620

I will verify

**Comment by tgravescs** [comment]
so I confirmed that reverting 6dc7b1d16f0eecdc2f932a6f9b94af630db534c5  - Fix regex non-multiline EOL/$ matching strings ending with a new-line (#9715)

make the behavior go back and the test passes

**Comment by tgravescs** [comment]
cudf issue: https://github.com/rapidsai/cudf/issues/9764

**Comment by tgravescs** [comment]
PR up to temporarily disable the tests, they need to be re-enabled when cudf is fixed

**Comment by andygrove** [comment]
We should be able to re-enable these tests now.
