### ISSUE TITLE
Support String to Decimal with built in rounding

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#4182]
Currently, when we cast a String to Decimal, we cast to an intermediate Decimal value that will sometimes lead to cases where we will end up not supporting a number when we can if we directly round it up without needing to go to an intermediate type first.

_Originally posted by @revans2 in https://github.com/NVIDIA/spark-rapids/pull/4172#pullrequestreview-812900294_

**Comment by revans2** [comment]
To clarify a bit. Spark when casting a string to a decimal, if the scale is larger than can fit in the desired type it will round the result. To match this behavior we will cast the string to a value with a larger scale and then round the result. This results in us only being able to support up to a Decimal(37, *) value.  But if we have access to the raw string we should be able to look at the next digit when parsing and use that to decide if we need to round or not. This sounds like something that would be good to try and do in CUDF.

**Comment by jlowe** [comment]
Is this still relevant after #6616?

**Comment by revans2** [comment]
This is fixed now.
