### ISSUE TITLE
[BUG] discuss if GpuPartitioningUtils#getBasePaths should handle FileNotFoundException

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#4232]
_Originally posted by @res-life in https://github.com/NVIDIA/spark-rapids/pull/4223#r758042662_

Raising this issue only because the change in #4223 is not completely semantically equivalent FileSystem#isDirectory, where the missing path results in 
```
hrow new IllegalArgumentException(s"Option '$BASE_PATH_PARAM' must be a directory")
```
now we propagate `FileNotFoundException`.

**Comment by jlowe** [comment]
Closing this as a specific instance of the problem described in #4210.  This particular case is highly unlikely to cause a problem in practice.
