### ISSUE TITLE
[FEA] Add tests for configs in BatchScan Readers

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#425]
**Is your feature request related to a problem? Please describe.**
As part of audit some of the configs in parquet and orc seem stood out and we may want to test that they work on the GPU. Needs more triaging.
```
hadoopConf.set(ParquetInputFormat.READ_SUPPORT_CLASS, classOf[ParquetReadSupport].getName)
    hadoopConf.set(
      ParquetReadSupport.SPARK_ROW_REQUESTED_SCHEMA,
      readDataSchemaAsJson)
    hadoopConf.set(
      ParquetWriteSupport.SPARK_ROW_SCHEMA,
      readDataSchemaAsJson)
    hadoopConf.set(
      SQLConf.SESSION_LOCAL_TIMEZONE.key,
      sparkSession.sessionState.conf.sessionLocalTimeZone)
    hadoopConf.setBoolean(
      SQLConf.NESTED_SCHEMA_PRUNING_ENABLED.key,
      sparkSession.sessionState.conf.nestedSchemaPruningEnabled)

...
hadoopConf.setBoolean(
      SQLConf.PARQUET_BINARY_AS_STRING.key,
      sparkSession.sessionState.conf.isParquetBinaryAsString)
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by revans2** [comment]
`ParquetReadSupport.SPARK_ROW_REQUESTED_SCHEMA` and `ParquetWriteSupport.SPARK_ROW_SCHEMA` are part of a hacked up way to pass the row schema from one part of spark to another.  We can ignore them.

`SQLConf.SESSION_LOCAL_TIMEZONE` is a hacked up way to pass the time zone to another part of Spark when reading the data.  When we support any timezone besides UTC then we can look at supporting something like this.

`SQLConf.NESTED_SCHEMA_PRUNING_ENABLED` is for 
> Prune nested fields from a logical relation's output which are unnecessary in 
> satisfying a query. This optimization allows columnar file format readers to avoid
> reading unnecessary nested column data. Currently Parquet and ORC are the
> data sources that implement this optimization.

When we support reading structs we should look into this config.  Until then we can ignore it.

`SQLConf.PARQUET_BINARY_AS_STRING` is for
> Some other Parquet-producing systems, in particular Impala and older versions of 
> Spark SQL, do not differentiate between binary data and strings when writing out the 
> Parquet schema. This flag tells Spark SQL to interpret binary data as a string to provide 
> compatibility with these systems.

For now we don't support binary data, so we should verify that cudf converts binary data that it finds to a string when it is returned.

When we do support binary data, then we will need cudf to some how support this too.

I propose that we file follow on issues for schema pruning and binary as string as place holders for when we support those features.  For this issue we verify existing functionality for binary as string.  If we cannot support it then we need to fall back to the CPU if this config is set and we have a string column as input in the schema.

**Comment by revans2** [comment]
A little bit more information about this.  Spark stores the schema in the parquet output so setting PARQUET_BINARY_AS_STRING  has no impact on files produced by Spark.

**Comment by revans2** [comment]
I am currently stuck on getting a parquet file that can reproduce this issue.

**Comment by revans2** [comment]
So I read through the parquet reader code that we currently have in cudf and it is totally ignoring the UTF8 logical type and is only going off of the physical type for a string `BYTE_ARRAY` and `FIXED_LEN_BYTE_ARRAY`.  But I suspect that this is going to change in the future once we get support for reading Lists/arrays in.

Because I have been unable to find/make a parquet file that I can use to test this feature I am inclined to just fall back to the CPU in all cases where it is set, even though it should work with the current code.
