### ISSUE TITLE
[BUG] Unable to build RAPIDS jar using custom distro of Spark as dependency with 21.12

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#4276]
**Describe the bug**
Unable to build RAPIDS jar using custom distro of Spark as dependency with current `v21.12`.
With `v21.10`, we made this work by adding our internal repository holding the custom Spark artifacts in the main root project `pom.xml` through the `<repositories>`  tag (which got inherited as parent of the `dist/pom.xml`), and modifying the `spark-sql` version under dependencies in `dist/pom.xml` to match the internal version of our custom Spark distro.

When doing the same for building the latest changes from branch-21.12, I see all projects being built successfully till the Distribution project, which seems to not be able to locate the custom Spark artifacts because it is pulling from Central (public) repos and not our internal specified repo (other projects like the root and sql-plugin etc, are able to pull the custom artifacts from the repo successfully). I see there have been many project structuring changes in the latest version in `dist/pom.xml`, could something be affecting this?

**Steps/Code to reproduce bug**
Try pulling Spark artifacts from a different repo defined in the root `pom.xml` and building RAPIDS jar using that Spark as a dependency.

**Expected behavior**
Spark RAPIDS project should be built successfully.

**Comment by Niharikadutta** [comment]
@tgravescs Could you please help look into this and guide as to what I might be missing?

**Comment by tgravescs** [comment]
I assume you have a custom version on your Spark?  Is it looking for the custom version in the public repo and failing or is it looking for the apache spark version in the public repo?

if you are doing something like overriding an existing profile - lets say spark312 - make sure the spark version is updated in the top level pom.xml (spark312.version) to be your customer version.  for example 3.1.2.22.0. It sounds like most of the build works, does the sql-plugin module pull your custom Spark version?  

> modifying the spark-sql version under dependencies in dist/pom.xml to match the internal version of our custom Spark distro

I'm not quite sure I follow what you mean by this, the only spark-sql version in this pom is for cdh build, the other profiles pick it up from top level pom file and use spark.version.  If you added an entire profile like release311cdh that should work too but shouldn't be needed unless you need to add other dependencies.

Its hard for me to debug without more info about modifications and exact failure.

**Comment by Niharikadutta** [comment]
Thanks @tgravescs provided more information via email.

**Comment by Niharikadutta** [comment]
Closing the issue as it is resolved, thanks @tgravescs
