### ISSUE TITLE
[BUG] q9 regression between 21.10 and 21.12

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#4281]
We had a baseline of 25s for q9 in 21.10, but we have lost around 1.5 or 2 seconds in 21.12 when running in the spark2a environment.

This is to investigate the differences and figure out if we need to raise an issue in cuDF, the plugin or if there's an environmental issue.

  "queryTimes" : [ 26977 ],
  "queryTimes" : [ 27164 ],
  "queryTimes" : [ 27016 ],
  "queryTimes" : [ 26903 ],
  "queryTimes" : [ 26542 ],

**Comment by abellina** [comment]
Note that we have identified other issues with q9 that could yield significant performance improvements: https://github.com/NVIDIA/spark-rapids/issues/4189, https://github.com/NVIDIA/spark-rapids/issues/4186, https://github.com/NVIDIA/spark-rapids/issues/4164.

The issue here is somewhat separate from the other issues, but there may be some parallels.

**Comment by jbrennan333** [comment]
I believe the difference here may be due to enabling nvcomp compression/decompression by default in CUDF.  In branch-22.02, I got times similar to 21.10 when I disabled nvcomp:
```
spark.executorEnv.LIBCUDF_NVCOMP_POLICY=OFF
```
Results:
```
q9-22.02-nonvcomp/tpcds-testjtb_no_nvcomp-gpu-aqe-on-ucx-off-16-cores-decimals-false-q9-1638656812726.json:  "queryTimes" : [ 24593 ],
q9-22.02-nonvcomp/tpcds-testjtb_no_nvcomp-gpu-aqe-on-ucx-off-16-cores-decimals-false-q9-1638656886471.json:  "queryTimes" : [ 25379 ],
q9-22.02-nonvcomp/tpcds-testjtb_no_nvcomp-gpu-aqe-on-ucx-off-16-cores-decimals-false-q9-1638657043868.json:  "queryTimes" : [ 25976 ],
```

When I run branch-22.02 with default setting (LIBCUDF_NVCOMP_POLICY=STABLE).
I get:
```
q9-22.02/tpcds-testjtb-gpu-aqe-on-ucx-off-16-cores-decimals-false-q9-1638658371600.json:  "queryTimes" : [ 27203 ],
q9-22.02/tpcds-testjtb-gpu-aqe-on-ucx-off-16-cores-decimals-false-q9-1638658437224.json:  "queryTimes" : [ 27284 ],
q9-22.02/tpcds-testjtb-gpu-aqe-on-ucx-off-16-cores-decimals-false-q9-1638658657588.json:  "queryTimes" : [ 27032 ],

```

**Comment by jbrennan333** [comment]
This is the PR for enabling nvcomp in cudf: https://github.com/rapidsai/cudf/pull/9582

**Comment by abellina** [comment]
Same comment as I had for q88: https://github.com/NVIDIA/spark-rapids/issues/4280

**Comment by jbrennan333** [comment]
As noted in #4280, the change to nvcomp as the default snappy compressor is in branch-21.12.

**Comment by jbrennan333** [comment]
I think the difference reported here is explained by the change to make nvcomp the default snappy compressor in branch-21.12.   The nvcomp team is investigating that issue separately.  I think we can close this issue - any objections @abellina or @jlowe?

**Comment by jlowe** [comment]
> I think we can close this issue

No objection from me.

**Comment by abellina** [comment]
+1 closing this.
