### ISSUE TITLE
Remove unneeded Shim functions

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4304]
**Is your feature request related to a problem? Please describe.**
in SparkShims there are now a bunch of functions that aren't needed because they were there just to build in the old shims module to make sure the Type matched the Spark version, or to do some work on a type that was specific and then return a type that was common.

For instance there are: getPartitionedFiles, replacePartitionDirectoryFiles , getPartition* functions that were there just to build against the particular Spark version but then returned a type that was not changed in any Spark version.  These can now just be removed from the shim because we build the code against each version.

getArrowValidityBuf, getArrowDataBuf, getArrowOffsetsBuf may also be one as it was just picking up different Arrow versions
replaceWithAlluxioPathIfNeeded should be checked as I think again it was manipulating things specific to the spark version in side of it.
others possibly: registerKryoClasses

**Comment by jlowe** [comment]
Covered by #5005.
