### ISSUE TITLE
[DOC] Misc Doc improvements

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4319]
## Report incorrect documentation

**Location of incorrect documentation**

docs/additional-functionality/rapids-shuffle.md file:

References versions that are Spark snapshot versions, since we don't release them we should remove them from the table.

download.md file:

The plugin is tested on the following architectures mention V100, A100, etc
> maybe a nit and again fixed for later, but aren't the "architectures" really Ampere, Volta, Turing vs GPU models?

Requirements mention 	Apache Hadoop 2.10+ or 3.1.1+ (3.1.1 for nvidia-docker version 2)

> do we want to qualify this as its not really required if not using YARN and really these are only required if using docker/cgroups?

Version info mentioned Azure Synapse is 21.10 but not 21.12:

> we put Azure Synapse here, but they are in progress of upgrading did we want to put something for Azure and EMR that say see their pages for current version?

**Comment by viadea** [comment]
@tgravescs @nvliyuan 
I submitted https://github.com/NVIDIA/spark-rapids/pull/4472 for this to address item:
1. docs/additional-functionality/rapids-shuffle.md
2. The plugin is tested on the following architectures mention V100, A100, etc

For item:
3. Requirements mention Apache Hadoop 2.10+ or 3.1.1+ (3.1.1 for nvidia-docker version 2)
What is our suggestion for supported Hadoop version?

4. Version info mentioned Azure Synapse is 21.10 but not 21.12.
Currently the Azure Synapse only ships with 21.10. I talked with them and once 21.12 is updated officially, we need to remove it from 21.10 and add it to 21.12 download page.

**Comment by tgravescs** [comment]
for 3. we should either quantify it saying, for yarn deployments that want to use GPU scheduling requires Hadoop 2.10+....  Or alternatively we could remove it form here and say see the documentation for any requirements based on the deployment used.

4. do we really want to have to keep updating our docs based on this or could we just point to some Azure docs?

**Comment by viadea** [comment]
For 4, currently there is no Azure Doc mentioning the version of the plugin.  Maybe once it is there, we can point it to Azure doc. However if we do this for Azure Synapse, we may need to do this for EMR as well?

**Comment by tgravescs** [comment]
it might be a call for Sameer or Karthik, but to me it would be nice just to point to any third party docs since we don't control the versions.

**Comment by viadea** [comment]
For #3 https://github.com/NVIDIA/spark-rapids/pull/4512 is filed.
For #4, i will update it once Azure Synapse release new version of jars later.

**Comment by viadea** [comment]
I think we can close this one now.
