### ISSUE TITLE
[DOC] Provide shim class hierarchy information

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4320]
**Report needed documentation**
The shim layer is complex and the IDE doesn't help me much because I only have a subset of the shim classes on the classpath at any one time so I always spend quite a bit of time trying to determine where to add new shim code.

**Describe the documentation you'd like**
I would like either a class hierarchy diagram like the one below or a table telling me which traits or base classes are involved for each supported Spark version.

![shims](https://user-images.githubusercontent.com/934084/145060994-361c8802-df8f-4cb3-ad2c-2b0b58335f72.png)

**Steps taken to search for needed documentation**
I searched for the word "shim" under docs.

**Comment by tgravescs** [comment]
so if this is done it has to be updated with each PR (probably like config docs are now).  One PR could change this very quickly and we add and remove Spark versions pretty regularly.

**Comment by andygrove** [comment]
If we do this, I would expect it to be automated somehow. I'm not sure what the best approach would be though. It could be as crude as gripping the source files, which is basically what I did manually.

**Comment by jlowe** [comment]
@andygrove do you still need this with the new shimplify approach for implementing shims?

**Comment by andygrove** [comment]
> @andygrove do you still need this with the new shimplify approach for implementing shims?

No, I will go ahead and close this.
