### ISSUE TITLE
[DOC] Document DPP not working on Databricks

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4321]
## Report incorrect documentation

DPP doesn't work on databricks:
https://github.com/NVIDIA/spark-rapids/issues/3143

Another user hit a very similar issue so we should document it and recommend spark.sql.optimizer.dynamicPartitionPruning.enabled off.  We need to confirm if this happen in DB7.3 or just in 9.2

**Comment by viadea** [comment]
I think we have updated the limitation for databricks here:
https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-databricks.html

**Comment by tgravescs** [comment]
ok, I'll update that issue to be more specific about spark.sql.optimizer.dynamicPartitionPruning.enabled as a user saw that but still did not know how to work around.
