### ISSUE TITLE
[FEA] Profiling tool add option to filter based on filesystem date

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4323]
**Is your feature request related to a problem? Please describe.**
Internal NVIDIA user requested add an option to the profiling tool to be able to pick up all event logs starting at a certain date. Using the filesystem timestamp on files is fine. Basically they periodically run the tool and just want to pick up the logs from the last time they ran it.  If they pick up a few to many that isn't an issue.

**Comment by parthosa** [comment]
Qualification tools have a similar filter `--start-app-time` that filters event logs using application start time. Can a similar approach be used here i.e. use application start time to filter instead of filesystem time?
