### ISSUE TITLE
`InSet` operator produces an error for Strings

### ISSUE THREAD

**Issue by rui911013** [NVIDIA/spark-rapids#433]
![image](https://user-images.githubusercontent.com/33319780/88475548-7c291300-cf63-11ea-8227-52f1ede0e6a6.png)

**Comment by revans2** [comment]
Internally spark has a few different operators for "in".  There is both `In`, and `InSet`.  `InSet` is used when you have more then a set number of literal values.  It looks like you found a bug in our implementation of `InSet`.  It only happens for Strings as far as I can tell.

**Comment by revans2** [comment]
I am going to switch this over to a bug and see if I can fix it.

**Comment by revans2** [comment]
The config that controls this is `spark.sql.optimizer.inSetConversionThreshold` with the default value set to `10`. So if you have more then 10 literals you will see this issue.

**Comment by revans2** [comment]
@rui911013 as a work around you should be able to set `spark.sql.optimizer.inSetConversionThreshold` to be larger than the number of parameters you want to pass to the `IN` operator.
