### ISSUE TITLE
[BUG] GpuColumnarToRowExec will always be tagged False for exportColumnarRdd after Spark311 

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#4334]
**Describe the bug**
when using [ColumnarRdd](https://github.com/NVIDIA/spark-rapids/blob/branch-22.02/sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarRdd.scala#L47) in Spark 3.1.2 (all after), the Shim layer will always use the default value(false) for `exportColumnRdd` , e.g. https://github.com/NVIDIA/spark-rapids/blob/branch-22.02/sql-plugin/src/main/311until320-nondb/scala/com/nvidia/spark/rapids/shims/v2/Spark31XShims.scala#L457-L459

**Steps/Code to reproduce bug**
Calling ColumnarRdd in any version after 311, will cause this problem (XGBoost, PCA train):
![image](https://user-images.githubusercontent.com/20476954/145357391-4d0219aa-0135-4d91-8d54-e3493f70158a.png)

**Expected behavior**
There should not be "columnar to row" conversion.

**Environment details (please complete the following information)**
Spark 3.1.2 Standalone

**Additional context**
Version before 311 is fine.

**Comment by tgravescs** [comment]
this looks like its been broken since release 0.2, do we not have a test for this?  Do we have an idea of what exactly it causes?  If perf issue how much does it affect it.

**Comment by wjxiz1992** [comment]
Not clear about the XGBoost case. but for PCA case. with 4.6G parquet data , the column is of ArrayType(DoubleType) and the array size if 2048. the perf will drop from 6 seconds to 8 minutes in this case.

without the fix in 3.1.2, training is 8 minutes 
![image](https://user-images.githubusercontent.com/20476954/145425596-aaa1e6ea-f775-41f1-b884-3d6c47061e10.png)

but in 3.0.1: 6 seconds
![image](https://user-images.githubusercontent.com/20476954/145425630-297f4c55-2302-4382-9421-e9a2b06e1126.png)
