### ISSUE TITLE
Add a config to allow cast between Datetime and Numeric in ANSI mode

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#4342]
As part of https://github.com/apache/spark/commit/2afa52d203. Spark has added a config to cast numeric <> datetime. 

We should support this

**Comment by razajafri** [comment]
The config was removed as a part of https://github.com/apache/spark/pull/34985

**Comment by sameerz** [comment]
Is this related to PR https://github.com/NVIDIA/spark-rapids/pull/4819 ?

**Comment by razajafri** [comment]
The config was removed as a part of https://github.com/apache/spark/pull/34985
