### ISSUE TITLE
[FEA] Support LEGACY mode for parquet reads and writes

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#436]
**Is your feature request related to a problem? Please describe.**
This is follow on work to #144 and #435 it would be great if we could properly support 'LEGACY' mode for reading and writing parquet dates and timestamps.  There was some discussion about cudf supporting some of this, but with how spark supports it, being data driven, I think we can do something similar if we need to.

**Comment by jlowe** [comment]
Fixed by #9649 and #9132
