### ISSUE TITLE
[FEA] Implement Reverse function for GPU

### ISSUE THREAD

**Issue by laatopi** [NVIDIA/spark-rapids#4375]
**Is your feature request related to a problem? Please describe.**
`reverse` function should be implemented in Spark Rapids as [libcudf implementation already exists](https://docs.rapids.ai/api/libcudf/stable/group__column__copy.html#ga684cd03cda3c33a42de7e37e4231401a)

**Describe the solution you'd like**
A GPU supported function that corresponds to `reverse` function of the [Spark Dataframe implementation](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.functions.reverse.html).

**Comment by jlowe** [comment]
Thanks for the feature request!

The `reverse` in libcudf does not help implement Spark's `reverse`.  Spark's `reverse` function reverses the data within a row without modifying the order between rows, whereas the libcudf function reverses the order of rows but does not modify the data within each row.  For example, calling libcudf on a 3-row String column containing "abc", "123", "xyz" will return a column containing "xyz", "123", "abc", whereas the Spark reverse function returns "cba", "321", "zyx".

From what I've seen, the closest thing libcudf has to help implement this is a segmented gather for lists.  With the right segmented gather map, one could reverse the elements within a list column, and thus the elements in each row of a Spark `ArrayType` column.  The tricky part then is how to construct the proper segmented gather map.  I suspect we'll need libcudf help to implement this in the RAPIDS Accelerator.

@laatopi do you have a pressing need for this functionality in one or more of your workflows?  That would help us prioritize the request.

**Comment by laatopi** [comment]
Hey,

thanks for the correction, I had understood this clearly wrong.
There is no pressing need for this functionality, just threw it here as a nice to incorrectly assuming it would be a quick job.

**Comment by cindyyuanjiang** [comment]
Now issue #6885 is closed, should we consider closing this as well?

**Comment by revans2** [comment]
Yes, we should have lined them.
