### ISSUE TITLE
Release Checklist 22.02

### ISSUE THREAD

**Issue by Salonijain27** [NVIDIA/spark-rapids#4377]
Release Checklist for v22.02:

| Status  | Task | Start | End | Owner| 
| ------------- | ------------- | ------------- | ------------- | ------------- | 
|**Pre-release**| | | | |
|<ul><li>- [X] </li></ul> | Notification to team of last feature sprint in milestone 2021-12-13 - 2022-01-07 | 2021-12-13 | 2022-01-07 | @sameerz| 
|<ul><li>- [X] </li></ul> | Burndown (no new features for current release) | 2022-01-17 | 2022-01-28 | Team|  
|<ul><li>- [X] </li></ul> | Update docs for current release in spark-rapids | 2022-01-23| 2022-01-28 | Team| 
|<ul><li>- [X] </li></ul> | Get RAPIDS 22.04 cudf java build working.  | 2022-01-17 | 2022-01-21 | @pxLi | 
|<ul><li>- [X] </li></ul> | Create 22.04 branch | 2022-01-24 | 2022-01-28 | @pxLi | 
|<ul><li>- [X] </li></ul> | Automerge from 22.02 to 22.04 | 2022-01-26 | 2022-01-28 | @pxLi | 
|<ul><li>- [X] </li></ul> | Enable Jenkins builds (premerge, nightly, integration, performance) for 22.04 | 2022-01-24 | 2022-01-28 | @pxLi | 
|<ul><li>- [X] </li></ul> | Virtual review | 2022-01-31 | 2022-02-15 |@krajendrannv | 
|<ul><li>- [X] </li></ul> | [cudf 22.02] Java release to sonatype | 2022-02-07 | 2022-02-07 | @NvTimLiu | 
|<ul><li>- [X] </li></ul> | Notify RAPIDS team of javadocs for 22.02 | 2022-02-08 | 2022-02-08 | @GaryShen2008 | 
|**Staging release**||||
|<ul><li>- [X] </li></ul> | Make 22.04 the default branch | 2022-01-31 | 2022-01-31 | @jlowe | 
|<ul><li>- [X] </li></ul> | Merge all remaining branch-22.02 PRs | 2022-01-28 | 2022-01-28 | Team | 
|<ul><li>- [X] </li></ul> | Update cudf JNI dependency version | 2022-02-07 | 2022-02-07 | @pxLi | 
|<ul><li>- [X] </li></ul> | Create CHANGELOG.md | 2022-01-28 | 2022-01-28 | @pxLi | 
|<ul><li>- [X] </li></ul> | Deliver Snapshot packages to QA | 2022-01-28 | 2022-01-28 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Create a PR (not squashed) to merge from branch-22.02 to main. Needs review from repository owner | 2022-02-07 | 2022-02-07 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Trigger the release Jenkins job on the main branch and deploy the jar to sonatype staging | 2022-02-08 | 2022-02-08 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Deliver final packages to QA | 2022-02-08 | 2022-02-08 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Run integration tests on staging jars with AQE on, UCX on, Databricks Azure, Databricks AWS, Dataproc | 2022-02-08 | 2022-02-11 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | Run LHA tests on staging jars | 2022-02-08 | 2022-02-11 | @NvTimLiu| 
|<ul><li>- [X] </li></ul> | QA testing with Snapshot on YARN, NGC with Volta and Ampere | 2022-01-31 | 2022-02-05 | @yuange98|  
|<ul><li>- [X] </li></ul> | Run pre-processing workflow for [DLRM sample use case](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Recommendation/DLRM#advanced)| 2022-02-08 | 2022-02-11 | @johnzhong |  
|<ul><li>- [X] </li></ul> | QA testing with final packages on YARN, NGC with Volta and Ampere | 2022-02-08 | 2022-02-11 | @yuange98|  
|**Release**| | | | |  
|<ul><li>- [X] </li></ul> | Tag the release and deploy the staging artifacts to maven central repository | 2022-02-18 | 2022-02-18 | @NvTimLiu|
|<ul><li>- [X] </li></ul> | CDH testing | 2022-02-14 | 2022-02-18 | @tgravescs | 
|<ul><li>- [X] </li></ul> | Update gh-pages | 2022-02-14 | 2022-02-18 | @viadea   |  
|<ul><li>- [X] </li></ul> | Test [spark-rapids-examples repo](https://github.com/NVIDIA/spark-rapids-examples) with Spark-Rapids 22.02 | 2022-02-14 | 2022-02-18 | @nvliyuan  | 
|<ul><li>- [X] </li></ul> | Update docs for current release in spark-rapids-examples | 2022-02-14 | 2022-02-18 | @GaryShen2008|
|<ul><li>- [X] </li></ul> | Update rapids.sh in https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/rapids for the plugin (https://github.com/GoogleCloudDataproc/initialization-actions/pull/971)| 2022-02-14 | 2022-02-18 | @viadea |

**Comment by NvTimLiu** [comment]
Updated some of the strings `21.12` to `22.02`
