### ISSUE TITLE
[FEA] Enable StringLPad

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#438]
**Is your feature request related to a problem? Please describe.**
Support https://spark.apache.org/docs/latest/api/sql/#lpad .  CUDF provides a pad function: https://docs.rapids.ai/api/cudf/stable/api.html#cudf.core.column.string.StringMethods.pad 

**Describe the solution you'd like**
Allow Spark SQL queries to use the `lpad`  function on strings.

**Comment by revans2** [comment]
To make this work we are going to have to put in JNI bindings for `cudf::strings::pad_side`, `cudf::strings::pad`, and `cudf::strings::slice_strings` so we can match the truncate that spark does for strings that are too long.
