### ISSUE TITLE
[DOC]cannot index yarn-gpu.md

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#4380]
## Report incorrect documentation
Cannot index to get-started/yarn-gpu.md because there is no nav_order or parent in it.  The page can only be reached by https://nvidia.github.io/spark-rapids/docs/get-started/yarn-gpu.html url link.

**Comment by sameerz** [comment]
This page was relevant only to it's parent link in https://github.com/NVIDIA/spark-rapids/blob/branch-22.02/docs/get-started/getting-started-gcp.md , it does not need to be listed in the navigation bar.
