### ISSUE TITLE
[DOC] changing wording of Spark Profiling and Spark Qualification tools

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4398]
## Report incorrect documentation

We probably shouldn't be using the terminology Spark Profiling tool and Spark Qualification tool as it implies its a part of Spark. We should say Profiling tool for Apache Spark or something similar.

I think this is only issue with the docs as the its calling ProfileMain and QualificationMain in the code.

**Comment by amahussein** [comment]
This would break some links. for example docs/spark-qualification-tool.html
