### ISSUE TITLE
[FEA] Add in support for Maps

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#44]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to support maps.  It does not look like cudf has any support planed for maps right now, but once we have structs #17  and arrays #16 we can probably support a lot of maps with an array of a key value struct.  When adding in support for a new type we need to look at all existing operators and add in tests for those that support maps.  We should then file follow on issues for any operations that does not work properly with maps.

**Comment by sameerz** [comment]
This is an umbrella issue for maps support.  We will tag other map related issues to this one.

**Comment by jlowe** [comment]
Map types are supported.
