### ISSUE TITLE
[BUG]array_test.py::test_array_contains failures

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4401]
**Describe the bug**
The integration tests are failing on Spark 3.1.1:

15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[Byte] - Asser...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[Short] - Asse...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[Integer] - As...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[Long] - Asser...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[Float] - Asse...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[Double] - Ass...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[String] - Ass...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[Boolean] - As...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[Date] - Asser...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains[Timestamp] - ...
15:26:00  FAILED ../../src/main/python/array_test.py::test_array_contains_for_nans[Double]

cpu and gpu results are different, one example:

   AssertionError: GPU and CPU are not both null at [0, "array_contains(a, CAST(CAST(TIMESTAMP '0723-03-19 14:20:13.781' AS TIMESTAMP) AS TIMESTAMP))"]^[[0m

[2021-12-20T21:22:12.060Z] ^[[1m^[[31mE           AssertionError: GPU and CPU are not both null at [3, 'array_contains(a, 9.247723870123388E-295)']^[[0m

**Comment by abellina** [comment]
https://github.com/NVIDIA/spark-rapids/pull/4361 should fix this.

**Comment by sameerz** [comment]
Closed by #4361
