### ISSUE TITLE
[FEA] Add support for POSIX characters in regular expressions

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4413]
**Is your feature request related to a problem? Please describe.**

Spark regexp supports a number of POSIX character classes that we do not support on GPU (we currently fall back to CPU for any of these because we do not support `\p`).

```
POSIX character classes (US-ASCII only)
--
\p{Lower} | A lower-case alphabetic character: [a-z]
\p{Upper} | An upper-case alphabetic character:[A-Z]
\p{ASCII} | All ASCII:[\x00-\x7F]
\p{Alpha} | An alphabetic character:[\p{Lower}\p{Upper}]
\p{Digit} | A decimal digit: [0-9]
\p{Alnum} | An alphanumeric character:[\p{Alpha}\p{Digit}]
\p{Punct} | Punctuation: One of !"#$%&'()*+,-./:;<=>?@[\]^_`{\|}~
\p{Graph} | A visible character: [\p{Alnum}\p{Punct}]
\p{Print} | A printable character: [\p{Graph}\x20]
\p{Blank} | A space or a tab: [ \t]
\p{Cntrl} | A control character: [\x00-\x1F\x7F]
\p{XDigit} | A hexadecimal digit: [0-9a-fA-F]
\p{Space} | A whitespace character: [ \t\n\x0B\f\r]
```

Here is an example in Spark.

```
scala> spark.sql("SELECT s, s RLIKE '\\\\p{Lower}' FROM ss").show
+---+-----------------+
|  s|s RLIKE \p{Lower}|
+---+-----------------+
|  a|             true|
|  A|            false|
+---+-----------------+
```

**Describe the solution you'd like**
Add support for these, or document that we do not support them. If we chose to support this, we could transpile these to a form that cuDF understands.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by anthony-chang** [comment]
Related negated POSIX character class issue here: https://github.com/NVIDIA/spark-rapids/issues/5904
