### ISSUE TITLE
[FEA] Move udf-examples to spark-rapids-examples

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#4450]
**Is your feature request related to a problem? Please describe.**
We cannot fully test the UDF interface is working correctly without an external project.  Otherwise we risk tying the udf-examples build to the rapids-4-spark build, and that is very problematic (and triggered the desire to move this out in the first place). 

**Describe the solution you'd like**
Move the main part of udf-examples to spark-rapids-examples.
udf-examples depends on the release dist jar in Central Maven (Note the snapshot jar is not published to Central Maven).
Keep some simple cases in the original udf-examples.
Update the rapids code if necessary, such as:  
The udf-examples should only depend on dist, but it transitively depends on the sql-plugin module, and sql-plugin jar is not published to Central Maven, so should find the a way to build a clean dist jar that depends on no other jars.

**Describe alternatives you've considered**

**Additional context**
See #3934

**Comment by jlowe** [comment]
This is essentially a duplicate of #3971

**Comment by res-life** [comment]
Close this and keep #3971
