### ISSUE TITLE
[BUG] Regular expressions with hex digits not working as expected

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4486]
**Describe the bug**

I am seeing cuDF fail to match some hex digits correctly. Here is one example. I do not yet know if this is related to https://github.com/NVIDIA/spark-rapids/issues/4409 or whether this is a separate issue.

```
javaPattern=\xA9, cudfPattern=\xA9, input='©', cpu=true, gpu=false
```

**Steps/Code to reproduce bug**

```scala
  test("compare CPU and GPU: hex") {
    val patterns = Seq(raw"\x61", raw"\xA9", raw"\xa9")
    val inputs = Seq("a", "b", "\u00A9")
    assertCpuGpuMatchesRegexpFind(patterns, inputs)
  }
```

**Expected behavior**
Test should pass.

**Environment details (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by andygrove** [comment]
This is perhaps due to cuDF requiring UTF-8 and the fact that the copyright symbol has bytes 0xC2 0xA9 or 11000010 10101001 in UTF-8 encoding, and byte 0xA9 in ANSI encoding.

**Comment by andygrove** [comment]
Now that https://github.com/NVIDIA/spark-rapids/pull/4492 is merged, we fall back to CPU for now for hex digits.

**Comment by NVnavkumar** [comment]
With cuDF PR [#10220](https://github.com/rapidsai/cudf/pull/10220), at least 127 characters should be supported by the cuDF regex hex escape, so this should be re-enabled and tested.
