### ISSUE TITLE
[BUG] RegExp parse fails to parse character ranges containing escaped characters

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4505]
**Describe the bug**
The regular expression `[\a-z]` does not get parsed correctly because we currently only support character ranges with non-escaped characters. The transpiler then converts this to `[\a\-z]` when passing it to cuDF, resulting in incorrect results.

**Steps/Code to reproduce bug**
This was found by the new test code in https://github.com/NVIDIA/spark-rapids/pull/4504

**Expected behavior**
This expression should produce the same results on CPU and GPU.

**Additional context**
None

**Comment by anthony-chang** [comment]
Related to this issue: with the newly added support of predefined character classes (eg. `\s`, `\h`, `\v` etc), we need to handle the cases where these are nested in another character class (eg. `[abc\s]`). 

cuDF doesn't support nested character classes but we should be able to expand and flatten the nested predefined classes, ie. `[abc\s]` becomes `[abc \t\n\x0B\f\r]`
