### ISSUE TITLE
[FEA] Update HashSortOptimizerSuite to work with AQE

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#452]
**Is your feature request related to a problem? Please describe.**
HashSortOptimizerSuite tests fail when AQE is enabled, because they don't use the final execution plan when asserting that the plan is correct.

**Describe the solution you'd like**
I would like to be able to run the tests with AQE enabled.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sameerz** [comment]
Depends on PR #462
