### ISSUE TITLE
[FEA] Add support for regexp_replace with back-references

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4557]
**Is your feature request related to a problem? Please describe.**
Once https://github.com/NVIDIA/spark-rapids/pull/4556 is merged, we will fall back to CPU for `regexp_replace` with back-references. This is issue is for supporting this feature on GPU.

**Describe the solution you'd like**
Support `regexp_replace` with back-references on the GPU.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sperlingxx** [comment]
Can we leverage cuDF String method `stringReplaceWithBackrefs` to do regexp_replace with back-references?
