### ISSUE TITLE
[FEA] Encrypted Spill Support

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#46]
**Is your feature request related to a problem? Please describe.**
Spark supports encryption of intermediate results spilled to disk, and we will eventually need to support doing the same when GPU buffers are spilled to disk (e.g.: shuffles, broadcast data, etc).

Currently we only support spilling for shuffle.

**Comment by sameerz** [comment]
@krajendrannv can you help clarify the requirements from users for encryption?

**Comment by jlowe** [comment]
This has been implemented in #9454.
