### ISSUE TITLE
[FEA]JSON reader: support "allowNumericLeadingZero" option

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#4614]
From the [Spark JSON option](https://spark.apache.org/docs/latest/sql-data-sources-json.html#data-source-option),
"allowNumericLeadingZero",  Allows leading zeros in numbers (e.g. 00012).

Here the parser strips the leading zeros for numeric JSON types instead of marking them as corrupt entries, 
so if I had something like {"a": 0001, "b": 01.1000000000} both entries would cause the row to be marked as corrupt. 
Even if we provide a schema an ask for both a and b to be strings they show up as nulls because the values are technically corrupt. If I set the option to true they are parsed, but the leading and in the case of the float, 
trailing zeros are stripped from the resulting string.

Comments from Bobby:
My guess is that it is actually the other way around.  CUDF probably strips off the leading zeros and would not return an error if it saw them. If we ask CUDF to return them all as strings we might be able to implement a leading zero check, but I don't know if we want to. This is because of the oddness I talked abut in the last comment. I think if we have {"a": "01.100"} and ask Spark for a double it will not complain, but if we have the quotes off it will.  I am not 100% sure about that though.

**Comment by nartal1** [comment]
As per Bobby's observation, CUDF strips off the leading zeros by default. So the behavior is same as Spark's when this option is set to true.


When it is set to `false`(which is the default), there are couple of scenarios:

1. If there is only column in the json file and that column has leading zeros. AnalysisException is thrown :
```
scala> val df = spark.read.option("allowNumericLeadingZeros", "false").json("/home/nartal/json-reader/people-numericLeadingZero-1.json")
df: org.apache.spark.sql.DataFrame = [_corrupt_record: string]

scala> df.show
org.apache.spark.sql.AnalysisException: Since Spark 2.3, the queries from raw JSON/CSV files are disallowed when the
referenced columns only include the internal corrupt record column
(named _corrupt_record by default). For example:
spark.read.schema(schema).json(file).filter($"_corrupt_record".isNotNull).count()
and spark.read.schema(schema).json(file).select("_corrupt_record").show().
Instead, you can cache or save the parsed results and then send the same query.
For example, val df = spark.read.schema(schema).json(file).cache() and then
df.filter($"_corrupt_record".isNotNull).count().
```
2. If there is  more than 1 column in the json file, 
CUDF throws error that types for all columns must be specified(as column pruning is not supported yet for json reader in CUDF).

```
scala> df.printSchema
root
 |-- _corrupt_record: string (nullable = true)
 |-- name: string (nullable = true)

Caused by: ai.rapids.cudf.CudfException: cuDF failure at: ../src/io/json/reader_impl.cu:421: Must specify types for all columns
  at ai.rapids.cudf.Table.readJSON(Native Method)
  at ai.rapids.cudf.Table.readJSON(Table.java:925)
```

Where as Spark silently reads the corrupted data:

```
Input json file:
{"name":"Michael"}
{"name":"Andy", "age":0018}
{"name":"Justin", "age":00.1900}

scala> df.show
+--------------------+-------+
|     _corrupt_record|   name|
+--------------------+-------+
|                null|Michael|
|{"name":"Andy", "...|   null|
|{"name":"Justin",...|   null|
+--------------------+-------+


```
