### ISSUE TITLE
[FEA] Benchmark cuDF branch that uses global memory for regular expressions

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4621]
**Is your feature request related to a problem? Please describe.**
We want to benchmark the performance of https://github.com/rapidsai/cudf/pull/10094 to see if this is performant enough to use by default so that we can safely enable regular expressions on the GPU by default

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
I ran some benchmarks against a parquet file with 20,400,000 strings using the following query:

```sql
SELECT count(*) FROM item100 where i_item_desc RLIKE '\\.[ ]?([A-Z][aeiou][^aeiou])|([A-Z]([^aeiou][aeiou]))'
```

First, I ran the query with a new Spark shell each time to get the cost of the first time running the query.

All times are in milliseconds.

## Baseline results

```
6432
6316
6462
6380
6277
```

## cuDF branch using global memory

```
34747
34852
34705
34725
34735
```

I also ran the query multiple times within the same Spark shell.

## Baseline results

```
6277
4980
4867
4893
4806
```


## cuDF branch using global memory

```
34735
33342
33288
33278
33338
```

Conclusion: The global memory performance is ~5-7x slower than the baseline for this particular scenario.

**Comment by revans2** [comment]
5 to 7x slower is not good. At those speeds I suspect that the CPU might be beating us.

**Comment by andygrove** [comment]
> 5 to 7x slower is not good. At those speeds I suspect that the CPU might be beating us.

Yes, if we fall back to CPU for RLike then the query takes ~10 seconds for the first run and ~8 seconds for subsequent runs.

**Comment by sameerz** [comment]
@andygrove can you retest with the asnyc allocator enabled ( https://github.com/NVIDIA/spark-rapids/pull/4606 ) ?

**Comment by jlowe** [comment]
> can you retest with the asnyc allocator enabled?

To be clear, we're interested in the performance of the _original_ regex kernels, not the new version using global memory, when used in conjunction with the async allocator.  Since the async allocator operates at the driver level, it can "steal" unused memory in the pool for kernel launches.  That should prevent the CUDA OOM errors due to insufficient reserved memory when using the original regex kernels.

**Comment by andygrove** [comment]
I ran the query five times with the async allocator branch and the default cuDF. The times look good, about the same as the previous baseline results.

```
6132
4773
4671
4769
4655
```

**Comment by andygrove** [comment]
Closing this because we ran all the benchmarks we needed
