### ISSUE TITLE
Integration test scripts can run on stale jars

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#4667]
As seen in #4665, the nightly integration test script can run with an outdated plugin jar which can lead to failures and/or confusing behavior.  We should consider whether the scripts should be tied to the code that corresponds to the jars being downloaded to avoid situations where the scripts are incompatible with the jar being used.

**Comment by pxLi** [comment]
For nightly tests, we have a logic which use the same commit REF for the whole triggering graph. The nightly build and downstream tests pipelines should always use the same REF if they got trigger by the cron schedule.

I checked the failed one, it was triggered manually and did not change value of the REF param (default as upstream branch-22.02) to the corresponding code commit. So it failed as expected

**Comment by jlowe** [comment]
Thanks, @pxLi!  Looks like this was pilot error when the build was manually kicked.  Closing this.
