### ISSUE TITLE
[FEA][Audit] - [SPARK-37750][SQL] ANSI mode: optionally return null result if element not exists in array/map

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#4668]
**Is your feature request related to a problem? Please describe.**
This PR adds a config which controls whether it throws exceptions or returns null results  if array index is out of bound or map key does not exist for arrays and maps respectively. Have to check if we support ANSI mode for these types and if we want to match the same behavior as CPU.
PR: https://github.com/apache/spark/commit/08fd5013ad
Follow on PR to change config name: https://github.com/apache/spark/commit/0b9f120c99

**Comment by amahussein** [comment]
I am working on #4564 . I thought of adding new config as part of my fix, but I decided to keep those two separate.
It will be great to merge #4564 before this one.
