### ISSUE TITLE
[FEA][Audit] - [SPARK-37822][SQL] StringSplit should return an array on non-null elements

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#4671]
**Is your feature request related to a problem? Please describe.**
Trivial change for accurate return type of `StringSplit` as there isn't any case where the array can contain nulls. I am not sure if we really need to pull this in. 
PR - https://github.com/apache/spark/commit/db15b82be9

**Comment by HaoYang670** [comment]
Do we need to add this in the shim layer? The change is trivial and no new feature is introduced.

**Comment by revans2** [comment]
It was a small bug fix and like the logic stated there should be no cases where the null can be returned in the array, so I think we can just make the change and not worry about putting it under a shim.
