### ISSUE TITLE
[DOC] Fix missing url to pyspark description in integration-tests README

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#4679]
## Report incorrect documentation
The second paragraph in [integration_tests/README.md](https://github.com/NVIDIA/spark-rapids/blob/branch-22.04/integration_tests/README.md#rapids-plugin-for-apache-spark-integration-tests) is missing a link to pyspark description.

```
There are two sets of tests here. The pyspark tests are described here. The scala tests
are described [here](../tests/README.md)
```

There are two fixes for  ` The pyspark tests are described here.`:

- provide an external url to pyspark for example https://spark.apache.org/docs/latest/api/python/getting_started/index.html
- remove the entire sentence

**Comment by sameerz** [comment]
I think the wording is confusing.  The text `The pyspark tests are described here` ought to be clarified to say `The PySpark tests are described in this page`.
