### ISSUE TITLE
[DOC] what is `deterministic` used for in Spark, specifically around aggregate functions

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#4684]
https://github.com/NVIDIA/spark-rapids/pull/4677 introduced a change to align with Spark 3.3.0 where First/Last/Collect are now marked as deterministic. According to the referenced Spark PR, the change was made because First/Last/Collect were marked non-deterministic by mistake. Non-deterministic expressions are not eligible for certain optimizations, so that was the motivation for the PR to Spark. That said, the comments in [First.scala](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/First.scala#L35) and [Last.scala](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/Last.scala#L35) and [collect.scala](https://github.com/apache/spark/blob/58e07e0f4cca1e3a6387a7e0c57faeb6c5ec9ef5/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/collect.scala#L94) still say the operations are "non-deterministic", which seems at odds with the change to Spark.

This issue is for a research spike that looks at `deterministic` to determine what is used for, and propose a likely change to Spark to help change some of the docs around these aggregates.

**Comment by gerashegalov** [comment]
The purpose of deterministic is to prevent having inconsistent results of an expression in the context of a single query if the value is not memoized https://issues.apache.org/jira/browse/SPARK-8023.

**Comment by sameerz** [comment]
Our behavior is consistent with Spark, so additional documentation is not warranted.
