### ISSUE TITLE
[FEA] Optimization to the decode path of the cudf parquet reader

### ISSUE THREAD

**Issue by nvdbaranec** [NVIDIA/spark-rapids#4687]
Profiling of the Q9 TPC-DS query shows an unusual pattern in the cuDF parquet reader.  Normally the time is dominated by the decompress step, with the subsequent decode step being small.   In this particular case, the data is very tiny and stored in a dictionary so the decompression time is small but the decode time is relatively large. 

The NVComp team put together a test parquet reader that is significantly faster with non-dictionary type data.  We're going to experiment with adding dictionary support (as well as support for some other fixed-width types) to see if we can get these files loading quicker.  

If it works out, we might consider rolling this into the cuDF reader for the fixed-width path.   Eventually we might be able to adapt this for variable width types and nested types as well.

**Comment by sameerz** [comment]
Prototyping of this approach did not show a significant performance improvement.
