### ISSUE TITLE
[FEA] Support casting map to string

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids#4696]
Currently, we don't support casting map to string yet. As such, the following command can't work on GPU:
```
spark.sql("map(a, b)").show()
```

In order to show the content of the created map, I have to call either `map_keys` or `map_values` on the created map then show. It's inconvenient.

We should better support casting map to string. Assuming that we have supported casting array/struct to string, casting a map to string is just as simple as concatenating `cast_to_string(map_keys) + " -> " + cast_to_string(map_values)` pair by pair.

**Comment by HaoYang670** [comment]
I can work on it!
