### ISSUE TITLE
[BUG] Update the premerge and nightly tests after moving the UDF example to external repository

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#4704]
**Describe the bug**
After this PR https://github.com/NVIDIA/spark-rapids-examples/pull/94 is merged, should update the premerge and nightly tests accordingly.   

Seems it's rapids_build-it-UDF-native. 

Then we can merge this PR https://github.com/NVIDIA/spark-rapids/pull/4619.

Steps to run UDF examples including native tests:

```
git clone spark-rapids-examples
cd examples/RAPIDS-accelerated-UDFs
mvn clean verify -Pudf-native-examples
```

**Comment by jlowe** [comment]
@res-life did you mean to reference #4619 instead of #4408?  In either case, the PR that will break the nightly builds should be marked as a draft to prevent it from being accidentally merged even after it is approved until the nightly builds are ready for it to be merged.

**Comment by res-life** [comment]
Yes, referenced the wrong PR, updated.

**Comment by NvTimLiu** [comment]
working on the issue

**Comment by NvTimLiu** [comment]
Nightly pipeline against the new repo is ready, will remove the udf-examples source from spark-rapids GitHub, and update the old premerge/nightly jobs removing mvn build on udf-examples

**Comment by NvTimLiu** [comment]
nightly pipeline created : `examples-udf-examples-nightly`, `examples-udf-examples-native`

**Comment by res-life** [comment]
The PR from Tim is: https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/merge_requests/683

**Comment by res-life** [comment]
I've checked the pipelines, all are passed, so close this issue.

**Comment by jlowe** [comment]
I thought the intent of this issue was to update the premerge check of _this repository_, so that PRs proposed for the spark-rapids repository are tested against the udf-examples tests in the spark-rapids-examples repository.  Having separate nightly tests is fine, but it would be nice to not lose the UDF testing in the premerge.
