### ISSUE TITLE
[BUG] Read Parquet does not ignoreCorruptFiles

### ISSUE THREAD

**Issue by chawkm** [NVIDIA/spark-rapids#4727]
**Describe the bug**
On a CPU cluster when we set the following:
spark.conf.set("spark.sql.files.ignoreCorruptFiles", true)
Parquet files are then read and corrupt files are skipped over.

On GPU cluster with the same config corrupt files cause an exception to occur:
java.lang.RuntimeException:
`... is not a Parquet file expected magic number at tail 80 65 82 49 but found 00 00 00 00`

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.
1. Add a corrupt file to a directory of parquet files
2. Try and read directory of parquet files with ignoreCorruptFiles=true

**Expected behavior**
Corrupt files should be ignored.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

Databricks: 9.1 LTS ML (includes Apache Spark 3.1.2, GPU, Scala 2.12)
Init Script:
#!/bin/bash
sudo wget -O /databricks/jars/rapids-4-spark_2.12-21.12.0.jar https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark_2.12/21.12.0/rapids-4-spark_2.12-21.12.0.jar
sudo wget -O /databricks/jars/cudf-21.12.2-cuda11.jar https://repo1.maven.org/maven2/ai/rapids/cudf/21.12.2/cudf-21.12.2-cuda11.jar

spark config:
spark.task.resource.gpu.amount 0.0625
spark.sql.files.ignoreCorruptFiles true
executor.extraJavaOptions -Dlog4j2.formatMsgNoLookups=true
spark.plugins com.nvidia.spark.SQLPlugin
fs.s3a.acl.default BucketOwnerFullControl
spark.locality.wait 0s
fs.s3n.impl.disable.cache true
driver.extraJavaOptions -Dlog4j2.formatMsgNoLookups=true
spark.rapids.memory.pinnedPool.size 2G
spark.sql.adaptive.enabled false
fs.s3.impl.disable.cache true
fs.s3a.impl.disable.cache true
spark.databricks.delta.optimizeWrite.enabled false
spark.rapids.sql.concurrentGpuTasks 2

**Additional context**

**Comment by jlowe** [comment]
Thanks for the report, @chawkm!  Yes, this is a missed requirement in the Parquet read code.  Should be relatively easy to address by wrapping the access in a `try` block as the Spark code does.
