### ISSUE TITLE
[BUG] Plugin will crash with query > 100 columns on pascal GPU

### ISSUE THREAD

**Issue by hyperbolic2346** [NVIDIA/spark-rapids#4739]
**Describe the bug**
When [8444](https://github.com/rapidsai/cudf/pull/8444) was added to cuDF to support larger table conversion on the GPU, it added a dependency on hardware version > Pascal. The original design was for cuDF to crash and the plugin to detect this crash and fallback to the CPU for the conversion. This wasn't communicated clearly and the resulting fallback isn't implemented in the plugin, resulting in a crash. No data corruption, it simply won't work.

**Steps/Code to reproduce bug**
Run query with 22.02 plugin on a Pascal architecture GPU against a table with > 100 columns.

**Expected behavior**
The plugin continues to function, with or without gpu conversion of the data.

**Additional context**
The ultimate fix is to probably include Pascal compatible code in cuDF to handle the conversion on either side. This wouldn't be difficult to write as it can be a shim. This isn't something that can be handled in the 22.02 or 22.04 timeframe though.

**Comment by revans2** [comment]
I personally think that this is unlikely to show up in practice, but it would be something good to fix for 22.04

**Comment by sameerz** [comment]
Given the low likelihood of > 100 columns in a dataset, I am ok moving this to 22.04.

**Comment by mythrocks** [comment]
> The ultimate fix is to probably include Pascal compatible code in cuDF to handle the conversion on either side.

We did this in #10329. This should be resolved now.
