### ISSUE TITLE
[FEA] JSON reader should parse non-boolean values as null

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4779]
**Is your feature request related to a problem? Please describe.**
When parsing the following JSON file and specifying that the `number` column is a boolean type, Spark will produce the values `true` and `null`, but on GPU we would produce `true` for both rows (once https://github.com/NVIDIA/spark-rapids/pull/4780 is merged).

There is a similar issue with numeric values. 

```json
{ "number": true }
{ "number": "true" }
```

**Describe the solution you'd like**
We should have consistent behavior with Spark. We need to remove the XFAIL from the test in json_test.py that references this issue.

**Describe alternatives you've considered**
None

**Additional context**
Depends on https://github.com/rapidsai/cudf/issues/10283

**Comment by revans2** [comment]
This is true for from_json/JsonToStructs too
