### ISSUE TITLE
[FEA] JSON reader should parse quoted integer values as null

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4793]
**Is your feature request related to a problem? Please describe.**
Given the following JSON file, Spark will produce the values `1` and `null`, but on GPU we would produce `1` for both rows (once https://github.com/NVIDIA/spark-rapids/pull/4790 is merged).

```json
{ "number": 1 }
{ "number": "1" }
```

**Describe the solution you'd like**
We should have consistent behavior with Spark. We need to remove the XFAIL from the test in json_test.py that references this issue.

**Describe alternatives you've considered**
None

**Additional context**
Depends on https://github.com/rapidsai/cudf/issues/10283

**Comment by revans2** [comment]
I should clarify a bit here. This is true for integer types, ByteType, ShortType, IntegerType, and LongType when using ScanJson or JsonToStructs. It is not true for GetJsonObject or JsonTuple. It is not true for DecimalType, which happily accepts quoted strings.

**Comment by revans2** [comment]
This was fixed as a part of https://github.com/NVIDIA/spark-rapids/pull/10542 but one of the tests marked with it was still failing because of a separate regression related to how ints are parsed as dates. That test is being updated.
