### ISSUE TITLE
[FEA] Write integration test scripts for CDP

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4807]
**Is your feature request related to a problem? Please describe.**
If we can't get a full fledged jenkins setup for CDP we should write some automated scripts to run in their environment to make testing easier and more automated.

**Comment by GaryShen2008** [comment]
I think we just need to support running on CDP by changing a little in [run_pyspark_from_build.sh](https://github.com/NVIDIA/spark-rapids/blob/branch-22.04/integration_tests/run_pyspark_from_build.sh).
Assign to @zhanga5.

**Comment by zhanga5** [comment]
currently we enabled weekly integration test on CDP including UCX smoke test. Close this issue now
