### ISSUE TITLE
[FEA] Support org.apache.spark.sql.catalyst.expressions.ArrayExists

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#4815]
I wish we can support org.apache.spark.sql.catalyst.expressions.ArrayExists.

Mini repro:
```
import org.apache.spark.sql.types._
val arrayData = Seq(
    Row("John",List("apple","orange","banana"),1),
    Row("David",List("apple","orange","banana"),2),
    Row("Harry",List("apple","other"),1)
)

val arraySchema = new StructType().add("name",StringType).add("fruits", ArrayType(StringType)).add("favorite",IntegerType)

val df = spark.createDataFrame(spark.sparkContext.parallelize(arrayData),arraySchema)
df.write.mode("overwrite").format("parquet").save("/tmp/testparquet")
val df2=spark.read.parquet("/tmp/testparquet")
df2.createOrReplaceTempView("df2")

spark.sql("select name,exists(fruits,x -> x == 'other') as if_love_apple from df2").show()
```

Unsupported messages:
```
! <ArrayExists> exists(fruits#92, lambdafunction((lambda x#207 = other), lambda x#207, false)) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.ArrayExists
```

**Comment by revans2** [comment]
This should end up being an ArrayTransform on the lambda function followed by an array reduction using any.  We could hack it just like we do for array_max and array_min, but CUDF is putting in https://github.com/rapidsai/cudf/pull/9621 and we should be able to switch over to that instead.  They also support the any aggregation in that new API. Also the API is not specific to list/arrays so we could avoid copying the result of the higher order function into an array. We probably could just do the reduction directly on the result and the offsets in the input.

**Comment by gerashegalov** [comment]
IIUC we could implement ArrayAggregate on top of https://github.com/rapidsai/cudf/pull/9621.

`exists(arrayExpr, pred)` 
is equivalent to 
`aggregate(arrrayExpr, false, (acc, x) -> acc or pred(x))`
