### ISSUE TITLE
Add tests of UDF examples from spark-rapids-examples to premerge tests

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#4834]
The UDF examples jars have been moved to the spark-rapids-examples repository, but we should be testing against truly external UDFs in our premerge builds to verify we do not break this public API in a PR.  The premerge build can install the plugin snapshot jar into the local m2 repository, pull the spark-rapids-examples repo, and build and run the UDF tests from that repo against that installed plugin snapshot.  I don't think we need to build the full native builds, as that can be covered in nightly tests.  The build and test of the Java-only UDF examples should be quick and have only a small impact on the premerge runtime.

**Comment by jlowe** [comment]
I think we can get sufficient, relatively timely coverage from the nightly UDF example tests, assuming they are setup against the latest plugin snapshot jar.

**Comment by res-life** [comment]
@NvTimLiu is checking the nightly pipeline which testing agaist the Snapshot dist jar.  For per-merge pipeline, is it necessary?
