### ISSUE TITLE
[BUG] row-based_udf_test.py::test_hive_empty_* fail nightly tests

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4883]
**Describe the bug**
integration test are failing

FAILED ../../src/main/python/row-based_udf_test.py::test_hive_empty_simple_udf
FAILED ../../src/main/python/row-based_udf_test.py::test_hive_empty_generic_udf

with 

 pyspark.sql.utils.AnalysisException: Can not load class 'com.nvidia.spark.rapids.tests.udf.hive.EmptyHiveGenericUDF' when registering the function 'emptygeneric', please make sure it is on the classpath;[0m

**Comment by NvTimLiu** [comment]
Need to add ` integration-test-sparkxxxtests.jar` into the classpath for the integration tests. 

I'm working on it
