### ISSUE TITLE
[FEA] Hash partitioning on ArrayType

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#4887]
The RAPIDS Accelerator should support GPU acceleration of shuffles that partition on `ArrayType`.

**Comment by sameerz** [comment]
rapids/cudf issue: https://github.com/rapidsai/cudf/issues/10378

**Comment by razajafri** [comment]
Should be closed by #6066 
@jlowe can you confirm that I am not missing something you needed here?

**Comment by jlowe** [comment]
> can you confirm that I am not missing something you needed here?

Yep, this is fixed by #6066.

**Comment by jlowe** [comment]
Reopening since #6066 was reverted by #6679
