### ISSUE TITLE
Profiling tool: create a section to focus on I/O metrics

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4897]
**Is your feature request related to a problem? Please describe.**
See if we can groups metrics into one area that might help the user determine if they are I/O bound.  It won't be perfect but could make these metrics easier to find.
Things like read/write times for input and output, shuffle read and write times, executor cpu time, etc.

**Comment by mattahrens** [comment]
Also consider if there are metrics that can show how often similar data sets are read to determine if job would benefit from caching (e.g. Alluxio).

**Comment by mattahrens** [comment]
Requirements to enhance `data_source_information.csv` with additional metrics per row for analyzing I/O reads:

- [ ] Size: equivalent to size of files read in `sql_plan_metrics_for_application.csv`
- [ ] Read time: equivalent to scan time for GpuScan op in `sql_plan_metrics_for_application.csv`
- [ ] Count of reads: number of times the table/fields column was read in the entire application
- [ ] Start time when read occurred: TBD on how to extract that

Requirements for new `io_analysis.csv` output, generating a row per SQL (similar to `sql_level_aggregated_task_metrics.csv`):

- [ ] appIndex
- [ ] appId
- [ ] sqlID
- [ ] description
- [ ] numberOfReads: count of reads from data_source_information
- [ ] numberOfWrites: count of writes from data_source_information
- [ ] duplicateReads: count of reads that were in other sqlIDs
- [ ] spillDiskTotal: equivalent to diskBytesSpilled_sum in `sql_level_aggregated_task_metrics.csv`
- [ ] spillMemoryTotal: equivalent to memoryBytesSpilled_sum in `sql_level_aggregated_task_metrics.csv`

**Comment by nartal1** [comment]
Most of the metrics are done in PR https://github.com/NVIDIA/spark-rapids-tools/pull/74. Filed follow on issue https://github.com/NVIDIA/spark-rapids-tools/issues/110 to track pending items. Closing this issue.
