### ISSUE TITLE
[FEA][Audit] [SPARK-38314] - Fail to read parquet files after writing the hidden file metadata

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#4911]
**Is your feature request related to a problem? Please describe.**
We have copied FileFormatWriter code in GpuFileFormatWriter.scala so I suspect the bug exists in our code as well. Need to update the file to keep it in sync with Spark's code.

PR: https://github.com/apache/spark/commit/50520fe3eb

**Comment by firestarman** [comment]
GPU does not support writing hidden file meta, and will fall back to CPU writing. Could we have the case to reproduce this failure on GPU ?
