### ISSUE TITLE
[BUG] Parsing JSON dates in Spark 3.3.0 with timeParserPolicy=LEGACY produces wrong results in some cases

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#4912]
**Describe the bug**
Spark 3.3.0 has breaking changes in the way that dates are parsed from JSON files in legacy mode.

For now, I am making some tests in `json_test.py` with XFAIL, referencing this issue.

**Steps/Code to reproduce bug**
See json_test.py

**Expected behavior**
We should either fall back to CPU or match Spark

**Environment details (please complete the following information)**
N/A

**Additional context**
See https://github.com/apache/spark/commit/c1986204e59f1e8cc4b611d5a578cb248cb74c28

**Comment by revans2** [comment]
@andygrove the Spark commit you are referencing appears to have gone into 3.0.0. How is it related to 3.3.0 and what is the breaking change?

**Comment by andygrove** [comment]
So it turns out that the issue was with our tests not asserting that we fall back to CPU for LEGACY and for some reason in 3.3.0 we no longer fall back to CPU and produced different results to Spark, which led me to believe that Spark's behavior had changed.
