### ISSUE TITLE
[FEA] Drop support for Spark 3.0.1, 3.0.2, 3.0.3, Databricks 7.3 ML LTS

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#4915]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
We will drop support for older versions of Spark in 22.04.  The supported versions for 22.04 will be:

* Apache Spark 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, Cloudera CDP 7.1.6, 7.1.7, Databricks 9.1 ML LTS, 10.4 ML LTS Runtime and GCP Dataproc 2.0

We will support Apache Spark 3.3.0 in 22.04 if it is released before April 15.  Otherwise it will be a hotfix for 22.04 (if requested) or supported in 22.06.  

For reference the versions supported in 22.02 were here: https://nvidia.github.io/spark-rapids/docs/download.html#release-v22020

**Describe alternatives you've considered**
N/A

**Additional context**
We are removing older versions of Spark distributions.  In case anyone has a request for support for an older version please comment here.  

**Update**
We will keep support of 3.1.1 in 22.04, and remove it in a future release.

**Comment by pxLi** [comment]
are we going to support spark 3.0.4? or we are dropping all spark 30X versions?

**Comment by sameerz** [comment]
The plan is to remove support for Spark 3.0.x altogether.  

cc: @krajendrannv

**Comment by jlowe** [comment]
Fixed by #4988.
