### ISSUE TITLE
[BUG] Re-enable AQE integration tests

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#492]
**Describe the bug**
The recent merge of SPARK-32332 in 3.0.1 and 3.1.0 means that the plugin now gets called to optimize the Exchange node when AQE is enabled. Unfortunately, a validation check was added as part of this PR that validates that the resulting exchange node implements the appropriate BroadcastExchangeLike / ShuffleExchangeLike trait, and this is not currently the case.

AQE tests need to be re-enabled when we merge https://github.com/NVIDIA/spark-rapids/pull/462 which will resolve this issue.

There is also an argument for rolling back the validation check that was added.

**Steps/Code to reproduce bug**
Run the AQE integration tests.

**Expected behavior**
Tests should pass.

**Environment details (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by chenrui17** [comment]
@andygrove  for rapdis-0.2 , can be used AQE now? 
I attemp to set spark.sql.adaptive.enabled true in spark-default.conf with rapids-0.2 ,but it  seems not work

**Comment by andygrove** [comment]
@chenrui17 GPU-accelerated AQE support is implemented in https://github.com/NVIDIA/spark-rapids/pull/462 and requires a snapshot version of Spark 3.0.1 or 3.1.0.
