### ISSUE TITLE
[BUG] Test case in OpcodeSuite failed on Spark 3.3.0

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#4959]
**Describe the bug**
Test case failed in OpcodeSuite on Spark 3.3.0

```
- math functions - abs, ceil, floor *** FAILED ***
  [-0.5,1] did not equal [-0.5,1] (OpcodeSuite.scala:61)
```

**Steps/Code to reproduce bug**
```
mvn clean install -DskipTests -Dbuildver=330
cd udf-compiler
mvn test -Dbuildver=330
```

**Expected behavior**

**Environment details (please complete the following information)**

**Additional context**

**Comment by wjxiz1992** [comment]
I may need more suggestions here. @revans2 @nartal1 @abellina (related to https://github.com/NVIDIA/spark-rapids/issues/4913)

This issue only occurs in Spark 3.3.0 version after the change in [SPARK-37475](https://github.com/apache/spark/pull/34729) where [those code changes](https://github.com/apache/spark/pull/34729/files#diff-b5e6d03d9c9afbfa925e039c48e31078608ea749c193e6af3087b79eb701bc7cR1776-R1786) modified the Expression string from e.g. `Ceil(value)` to `ceil(value, 0)`. 
In the udf-compiler, the compiling rule is static, when it sees a math function `java.lang.Math.ceil(value)` in bytecode, it will convert it to Expression "CEIL(value)" without appending the scale parameter for Spark versions before the change mentioned above. see [code](https://github.com/NVIDIA/spark-rapids/blob/branch-22.04/udf-compiler/src/main/scala/com/nvidia/spark/udf/Instruction.scala#L591).

I am wondering if it requires a shim for this issue or there's another elegant solution. Please guide here.

**Comment by revans2** [comment]
I personally think this is a bug/inconsistency in Spark and I think there are some in the community that agree.

https://github.com/apache/spark/pull/34729#discussion_r761157050

The return type for `Ceil` is a Decimal type if the input is a decimal or a Long if the input is a Double or a Long.  Nothing else is supported as for input.

https://github.com/apache/spark/blob/61278786adf04c5652335ec438c55bdb9c47fbf8/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala#L243-L248

`RoundCeil`, however does not support any input type except Decimal. That means any Long or Double will be cast to a Decimal before being passed into it and then the output type is a Decimal.

https://github.com/apache/spark/blob/61278786adf04c5652335ec438c55bdb9c47fbf8/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala#L325-L333

I will put up a patch to Spark to fix it.

**Comment by revans2** [comment]
I filed https://github.com/apache/spark/pull/35913 as a PR and also https://issues.apache.org/jira/browse/SPARK-38604 as the SPARK JIRA for the problem.

**Comment by revans2** [comment]
My PRs into Spark were merged yesterday. We should check to see if it is still failing.

**Comment by wjxiz1992** [comment]
Fixed by https://github.com/apache/spark/pull/35913, verified in latest spark 3.3.0 and 3.4.0.
