### ISSUE TITLE
[FEA] Look at reading shuffle data in the background after the first batch

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#4964]
In a recent query I was profiling, that really was just a really large hash aggregate I noticed that if I configured the number of shuffle partitions to be too small the performance really fell off of a cliff. Part of the performance issue appears to be the fact that we got more than one input batch from shuffle per task. This means that we were holding the GPU semaphore while doing I/O.

I thought it might be good for us to launch a background thread in GpuShuffleCoalesceExec as soon as we have put the first batch of data on the GPU. That way we can try and overlap I/O and compute even on the same task as much as possible. This could be problematic, because it will increase CPU usage and host memory pressure, because shuffle decompression and I/O would be happening on a background thread.

**Comment by sperlingxx** [comment]
This issue sounds interesting to me. Could I pick it up?

**Comment by sperlingxx** [comment]
Hi @revans2, I built a demo with `OneSizeBuffer` which acts as a blocking queue holding single element.  `OneSizeBuffer` is supposed to minimize the memory cost on caching host buffer while running the CPU workloads asychronizely.
 
The first host batch is computed in main thread. If there exists subsequent host batches, they are processed in a separate thread.

```scala
class GpuAsyncShuffleCoalesceIterator(child: Iterator[HostConcatResult],
                                      dataTypes: Array[DataType],
                                      metricsMap: Map[String, GpuMetric])
  extends Iterator[ColumnarBatch] with Arm {

  private[this] val semWaitTime = metricsMap(GpuMetric.SEMAPHORE_WAIT_TIME)
  private[this] val opTimeMetric = metricsMap(GpuMetric.OP_TIME)
  private[this] val outputBatchesMetric = metricsMap(GpuMetric.NUM_OUTPUT_BATCHES)
  private[this] val outputRowsMetric = metricsMap(GpuMetric.NUM_OUTPUT_ROWS)

  @transient private lazy val buffer = new OneSizeBuffer()

  private var hostConcatThread: Thread = _

  private class OneSizeBuffer {
    private val lock = new util.concurrent.locks.ReentrantLock()
    private val notFull = lock.newCondition()
    private val notEmpty = lock.newCondition()
    @volatile private var deck: HostConcatResult = _
    @volatile private var childIsOpen = true

    def nonEmpty: Boolean = deck != null || (if (childIsOpen) {
        if (!hostConcatThread.isAlive) {
          val stackTraceMsg = hostConcatThread.getStackTrace.mkString("\n")
          throw new IllegalStateException(
            "The host concat thread crashed because: " + stackTraceMsg)
        }
        true
      } else {
        false
      })

    def offer(): Unit = {
      println("===== offer start =====")
      lock.lock()
      try {
        while (deck != null) notFull.await()
        deck = child.next()
        notEmpty.signal()
        println("===== offer end =====")
      } finally {
        lock.unlock()
      }
    }

    def take(): HostConcatResult = {
      println("===== take start =====")
      lock.lock()
      try {
        while (deck == null) notEmpty.await()
        val ret = deck
        deck = null
        notFull.signal()
        println("===== take end =====")
        ret
      } finally {
        lock.unlock()
      }
    }

    def closeHostIterator(): Unit = {
      childIsOpen = false
    }
  }

  private var isFirstBatch: Boolean = true
  private var childIsEmpty: Boolean = _

  private def convertHostBatchToDevice(hostConcatResult: HostConcatResult) = {
    GpuSemaphore.acquireIfNecessary(TaskContext.get(), semWaitTime)
    withResource(new MetricRange(opTimeMetric)) { _ =>
      withResource(hostConcatResult) { hostConcatBatch =>
        val batch = HostConcatResultUtil.getColumnarBatch(hostConcatBatch, dataTypes)
        outputBatchesMetric += 1
        outputRowsMetric += batch.numRows()
        batch
      }
    }
  }

  override def hasNext: Boolean = {
    if (isFirstBatch) {
      isFirstBatch = false
      if (child.hasNext) {
        buffer.offer()
        hostConcatThread = new Thread(() => {
          while (child.hasNext) buffer.offer()
          buffer.closeHostIterator()
        })
        hostConcatThread.start()
        childIsEmpty = false
      } else {
        childIsEmpty = true
      }
      !childIsEmpty
    } else {
      !childIsEmpty && buffer.nonEmpty
    }
  }

  override def next(): ColumnarBatch = {
    if (!hasNext) {
      throw new NoSuchElementException("No more columnar batches")
    }
    convertHostBatchToDevice(buffer.take())
  }
}
```

**Comment by revans2** [comment]
I think this might be because we have good I/O.  Either there is enough memory that reads always hit the page cache or the disks + network are fast enough that it is not a problem.

@jlowe and @abellina do you think it is worth spending more time trying to find a use case for this, or should we let it go until we are playing around with releasing the GPU Semaphore #4970? Just because I can see it helping there even if the I/O is not slow.

**Comment by abellina** [comment]
We may need to trigger a lot more than 1 batch concurrently to make them fit under the concat time. I do not think that host concat by itself is the bottleneck, but instead it's the high processing needed upstream closer to the actual network fetch, and by the time this runs we've already waited for the fetch and block decompress that seems to be the highest CPU consumer.

**Comment by revans2** [comment]
@abellina am I reading the code wrong? We are fetching and concating in a background thread. That would make it so that if we take longer to process the current batch than we do to fetch and concatenate on the CPU the next batch, then the fetch/concat is effectively free.  But if we take longer to fetch/concat, then the GPU processing time is effectively free.

If we concatenated the data on the main thread, and not the background thread, then you would be correct.

**Comment by abellina** [comment]
Oh I think I misunderstood @revans2. Then yeah, agree. The next gives you whatever it could fetch/concat first, then keeps pulling on the shuffle to fetch more.

Then I agree, if the batch you returned on next() takes a while to process, the next time you call next() it should be free.

**Comment by sperlingxx** [comment]
Hi @abellina @revans2, shall we move further on this issue ? If so, what should we do next ?

**Comment by revans2** [comment]
Closing this in favor of https://github.com/NVIDIA/spark-rapids/issues/11344
