### ISSUE TITLE
[FEA] Qualification tool should look into SQL plan metrics to prioritize queries

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#4979]
I wish Qualification tool can look into SQL plan metrics to prioritize queries/applications.

Currently Qualification tool mainly look at SQL/Data frame duration.

**Comment by tgravescs** [comment]
this seems a bit to broad, what metrics, do you have examples of useful ones?

**Comment by tgravescs** [comment]
I'm going to close this as I don't really know what it means by itself.  This to me is just another category under https://github.com/NVIDIA/spark-rapids/issues/3792 where we try to provide more information to user.
