### ISSUE TITLE
[QST]An error occurs when the SQLPlugin is submitted to yarn with GPU

### ISSUE THREAD

**Issue by YeahNew** [NVIDIA/spark-rapids#498]
**What is your question?**
Unable to create executor when I submit SQLPlugin on yarn by using GPU.
I follow the getting-started.md configurations in the docs file, and run rapids-4-spark_2.12-0.1.0.jar under Spark Standalone Cluster mode. But the terminal console shows "**ERROR scheduler.TaskSchedulerImpl: Lost an executor x (already removed): Ubable to create executor due to com.nvidia.spark.SQLPlugin**". On the other hand, I can see on the page that the yarn cluster has managed the GPU resources.
This troubles me a lot. Would you like to give me some solutions?

**Comment by jlowe** [comment]
Have you looked at the executor logs?  That likely will have a stacktrace showing the specifics of the error that caused the executor to fail.  Fro the error it sounds like the plugin encountered an error trying to initialize on the executor.  Maybe some dependency (e.g.: the proper version of the CUDA runtime libraries) were not able to be found on the node?

**Comment by jlowe** [comment]
@YeahNew any update on this?  Are you using a Spark cluster in standalone mode or on another cluster manager like YARN?  If you are running in standalone mode, you will need to make sure the plugin and cudf jars are in the classpath of the executor.  Spark currently requires executor plugins be available in the executor classpath.

**Comment by YeahNew** [comment]
> 
> 
> @YeahNew any update on this? Are you using a Spark cluster in standalone mode or on another cluster manager like YARN? If you are running in standalone mode, you will need to make sure the plugin and cudf jars are in the classpath of the executor. Spark currently requires executor plugins be available in the executor classpath.

Thank you very much for your enthusiastic help. I am sorry that I was attending the training recently and did not see your message. The problem was finally solved. Submitting in your way on my machine would fail. I finally modified the submitted parameter settings.
Here is your bin/spark-submit script:
$SPARK_HOME/bin/spark-shell \
       --master spark://${MASTER_HOST}:7077 \
       --conf spark.executor.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR} \
       --conf spark.rapids.sql.concurrentGpuTasks=1 \
       --driver-memory 2G \
       --conf spark.executor.memory=4G \
       --conf spark.executor.cores=4 \
       --conf spark.task.cpus=1 \
       --conf spark.task.resource.gpu.amount=0.25 \
       --conf spark.rapids.memory.pinnedPool.size=2G \
       --conf spark.locality.wait=0s \
       --conf spark.sql.files.maxPartitionBytes=512m \
       --conf spark.sql.shuffle.partitions=10 \
       --conf spark.plugins=com.nvidia.spark.SQLPlugin
Submitting according to the above method will prompt that the jar package cannot be found.

My submission script is as follows:
$SPARK_HOME/bin/spark-shell \
       --master spark://${MASTER_HOST}:7077 \
       --num-executor 1 \
       --conf spark.rapids.sql.concurrentGpuTasks=1 \
       --driver-memory 2G \
       --conf spark.executor.memory=4G \
       --conf spark.executor.cores=2 \
       --conf spark.task.cpus=1 \
       --conf spark.task.resource.gpu.amount=0.25 \
       --conf spark.executor.resource.gpu.amount=1 \
       --conf spark.rapids.memory.pinnedPool.size=2G \
       --conf spark.locality.wait=0s \
       --conf spark.sql.files.maxPartitionBytes=512m \
       --conf spark.sql.shuffle.partitions=10 \
       --conf spark.plugins=com.nvidia.spark.SQLPlugin \
       --conf spark.executor.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR} \
       --jars ${SPARK_CUDF_JAR},${SPARK_RAPIDS_PLUGIN_JAR}

Now， Now I am trying to submit in yarn mode.
I am very happy to discuss with you, would you like us to keep in touch?

**Comment by jlowe** [comment]
Glad to hear it's working for you!  Looks like the difference is the `--jars` option was added.  The [getting started guide for YARN](https://github.com/NVIDIA/spark-rapids/blob/main/docs/getting-started.md#running-on-yarn) shows this option, so it seems you were following the Spark Standalone guide instructions instead which does not have that option.

Closing this since it is working for you.  If there's something you feel should be improved with the documentation please feel free to reopen to discuss or file a PR with suggested changes.
