### ISSUE TITLE
[FEA] run integration tests without spark-avro jar in the classpath

### ISSUE THREAD

**Issue by wbo4958** [NVIDIA/spark-rapids#4984]
This is a follow up of https://github.com/NVIDIA/spark-rapids/pull/4956

PR 4956 introduced spark-avro jar in the test classpath, so every time when running integration tests, spark-avro jar will be involved which will be OK for avro test cases. But in fact, users may not include spark-avro in their user case, if some spark-avro code is involved by accident, then rapids plugin will throw exceptions.

So we need to add some checks to run integration tests without spark-avro jar to ensure no spark-avro code is involved. See [the comments ](https://github.com/NVIDIA/spark-rapids/pull/4956#discussion_r829458381)

**Comment by GaryShen2008** [comment]
Shall we run the avro test cases of integration test separately? So that only avro test cases require to add spark-avro.jar, and the others run without it.

**Comment by wbo4958** [comment]
good point, that seems doable

**Comment by wbo4958** [comment]
This is added in the https://github.com/NVIDIA/spark-rapids/pull/4956. So just close this issue
