### ISSUE TITLE
[FEA] Support AQE’s Dynamically optimizing skew joins feature

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#4985]
I wish we can support AQE’s Dynamically optimizing skew joins feature.

Since we do not support SMJ in GPU mode so this feature is not working.
I did some tests before on this, see http://www.openkb.info/2021/03/spark-tuning-adaptive-query-execution1_18.html for details.

**Comment by sperlingxx** [comment]
Hi @viadea, I am not sure why we need to "support a GPU version SMJ or be able to convert a GSHJ to GBHJ dynamically".

**Comment by viadea** [comment]
@sperlingxx I think that sentence is like a how-to-implement so let me remove that sentence to avoid any confusion.

Basically this feature is to support a AQE feature: Dynamically optimizing skew joins.

**Comment by tgravescs** [comment]
I don't think this makes sense right now since the spark feature is for SMJ and already stated we convert it to BHJ.  I think we can reopen in the future if needed
