### ISSUE TITLE
[FEA] Refactor pre-merge to run using branch specific Jenkinsfile

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#4991]
**Is your feature request related to a problem? Please describe.**

Plan to do not support compatibility in a single pre-merge Jenkinsfile.
1. New a upstream pipeline to take request from self-hosted runner
2. trigger downstream test pipelines w/ specific Jenkinsfile
3. honor jenkinfiles change in PR

**Comment by razajafri** [comment]
This seems related to #4920

**Comment by pxLi** [comment]
close this w/ https://github.com/NVIDIA/spark-rapids/pull/7238
