### ISSUE TITLE
[FEA] Support Adaptive Execution

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#5]
**Is your feature request related to a problem? Please describe.**
It would really be great to support Spark adaptive execution with the SQL plugin.

**Comment by sameerz** [comment]
Depends on https://github.com/apache/spark/pull/29134

**Comment by andygrove** [comment]
Now depends on https://github.com/apache/spark/pull/29262

**Comment by andygrove** [comment]
AQE is now supported, although it is not yet supported in conjunction with UCX, which is tracked in https://github.com/NVIDIA/spark-rapids/issues/455
