### ISSUE TITLE
[BUG] Implement hasSideEffects for all expressions that have side-effects

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#5041]
**Describe the bug**
In https://github.com/NVIDIA/spark-rapids/issues/3849 we implemented special handling in CASE WHEN for expressions with side-effects but this relies on all expressions with side-effects overriding the `hasSideEffects` method and we have not done this for all expressions (see https://github.com/NVIDIA/spark-rapids/issues/5023 for one example).

We should audit all expressions and implement `hasSideEffects` where appropriate.

Candidates:

- [x] GpuGetArrayItem - 
- [x] GpuElementAt
- [x]  GpuGetMapValue
- [x] GpuUnaryMinus
- [x] GpuAbs
- [ ] GpuSum

**Steps/Code to reproduce bug**
N/A

**Expected behavior**
Conditional expressions such as `IF` and `CASE` should not fail due to expressions with side-effects being evaluated and throwing exceptions.

**Environment details (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by revans2** [comment]
I just did a test with pure spark 3.2.0 and I can confirm that case/when does not stop a SUM in ansi from throwing an exception if the case/when is outside of the SUM.

ANSI DISABLED:
```
scala>  Seq((0L, Long.MaxValue), (0L, 100L), (1L, 100L)).toDF.groupBy("_1").agg(when(col("_1") === 1, sum("_2")).otherwise(0).alias("result")).show()
+---+------+
| _1|result|
+---+------+
|  0|     0|
|  1|   100|
+---+------+
```

ANSI ENABLED:
```
scala>  Seq((0L, Long.MaxValue), (0L, 100L), (1L, 100L)).toDF.groupBy("_1").agg(when(col("_1") === 1, sum("_2")).otherwise(0).alias("result")).show()
22/04/15 19:08:34 ERROR Executor: Exception in task 0.0 in stage 10.0 (TID 29)
java.lang.ArithmeticException: long overflow
	at java.lang.Math.addExact(Math.java:809)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doConsume_0$(Unknown Source)
...
```

If I move the case/when inside the SUM, then it does the right thing in both places...
```
scala>  Seq((0L, Long.MaxValue), (0L, 100L), (1L, 100L)).toDF.groupBy("_1").agg(sum(when(col("_1") === 1, col("_2")).otherwise(0)).alias("result")).show()
+---+------+
| _1|result|
+---+------+
|  0|     0|
|  1|   100|
+---+------+
```
