### ISSUE TITLE
[BUG] OOM for q18 of TPC-DS benchmark testing on Spark2a

### ISSUE THREAD

**Issue by zhanga5** [NVIDIA/spark-rapids#5048]
**Describe the bug**
Run TPC-DS benchmark testing on Spark2a with latest cuDF/plugin jars encountered q18 running time > 20m (usually ~30s). And found OOM error like following in executor logs:

```
Previous exception in task: Could not allocate native memory: std::bad_alloc: out_of_memory: RMM failure at:/home/jenkins/agent/workspace/jenkins-cudf_nightly-pre_release-github-135-cuda11/cpp/build/_deps/rmm-src/include/rmm/mr/device/arena_memory_resource.hpp:159: Maximum pool size exceeded
```

**Steps/Code to reproduce bug**
1. Run TPC-DS benchmark testing on Spark2a (Spark 3.1.2) by using benchmark CLI
2. Monitor applications status & logs from command line or web UI
3. Some query would run much longer time than usual and would find OOM errors from executor logs

**Expected behavior**
Complete TPC-DS benchmark testing ~1 hour without any errors

**Environment details (please complete the following information)**
 - Environment location: Standalone spark 3.1.2 on Spark2a
 - Spark configuration settings related to the issue: please refer to benchmark CLI

**Additional context**
This error also found from DLRM test job on Dataproc

**Comment by abellina** [comment]
Taking a look at this.

**Comment by abellina** [comment]
If I revert this, the issue goes away: https://github.com/NVIDIA/spark-rapids/pull/4976.

It looks to be that with #4976, we are reading a whole lot of data from parquet we didn't use to.

For example, this shows we loaded 35x more data in one part of the plan. On the plus side, it only got 15x slower (go GPUs!):

Before:

![Screenshot from 2022-03-25 08-51-16](https://user-images.githubusercontent.com/1901059/160133529-04c7977f-6f92-4fd2-a1c5-be0353cd88b0.png)

After: 

![Screenshot from 2022-03-25 08-51-09](https://user-images.githubusercontent.com/1901059/160133546-b01fb7c2-2799-4e50-b40e-3bf36e6d5582.png)

**Comment by abellina** [comment]
There's a second call to `PaquetFileReader.open` that takes `ParquetReadOptions`. I bet that's related.
