### ISSUE TITLE
Premerge CI should automatically run on Databricks if code touches Databricks shims

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#5049]
We currently have the ability to opt-in for Databricks runs in premerge CI with the `[databricks]` tag, but the developer has to remember to use it.  It would be nice if premerge automatically ran on Databricks if there are any changes to files in the Databricks shims, i.e.: code that only builds on Databricks instances.  Currently this would apply to any PR that has file paths matching against these regexp patterns:
- `sql-plugin/src/main/.*[0-9x-]db/`
- `databricks`

**Comment by pxLi** [comment]
nice, this is on my TODO list. I will enable the auto-trigger of above patterns later

**Comment by pxLi** [comment]
https://github.com/NVIDIA/spark-rapids/pull/5067
