### ISSUE TITLE
”NoSuchMethodError injectQueryStagePrepRule(Lscala/Function1;)V“ When I started spark3.0 [QST]

### ISSUE THREAD

**Issue by chenrui17** [NVIDIA/spark-rapids#505]
![image](https://user-images.githubusercontent.com/33319780/89286482-dec98f80-d684-11ea-96a9-56d9f45e319b.png)
I want to use rapid-0.2 in advance，but when I run spark shell, the error in the figure above ，is due to spark version ？
I tryed clone several commit id , and they all got this error.

**Comment by chenrui17** [comment]
driver log is :
![image](https://user-images.githubusercontent.com/33319780/89290728-e04a8600-d68b-11ea-931d-0edc005397dd.png)

**Comment by tgravescs** [comment]
There was a change that went into spark 3.0.1 recently (11 days ago) that added the function injectQueryStagePrepRule. My guess is your version of 3.0.1-SNAPSHOT is older than that and missing that function. Can you please try with a newer version of 3.0.1.

**Comment by chenrui17** [comment]
> There was a change that went into spark 3.0.1 recently (11 days ago) that added the function injectQueryStagePrepRule. My guess is your version of 3.0.1-SNAPSHOT is older than that and missing that function. Can you please try with a newer version of 3.0.1.

thansk a lot，The problem has been solved
