### ISSUE TITLE
[BUG] nvidia.spark.SQLPLugin results in Error

### ISSUE THREAD

**Issue by vinhdiesal** [NVIDIA/spark-rapids#509]
I followed the tutorial and set my `spark-defaults.conf` as follows: 
```
spark.driver.memory              35g
# spark.executor.extraJavaOptions  -XX:+PrintGCDetails -Dkey=value -Dnumbers="one two three"
spark.ui.prometheus.enabled        true
spark.executor.processTreeMetrics.enabled  true
spark.rapids.sql.concurrentGpuTasks             1
spark.rapids.memory.pinnedPool.size            2G
spark.locality.wait                             0s
spark.executor.cores                             4
spark.task.cpus                                  1
spark.sql.files.maxPartitionBytes              512m
spark.sql.shuffle.partitions                    10
spark.driver.memoryOverhead                     4G
spark.executor.memoryOverhead                   4G
spark.plugins                                   com.nvidia.spark.SQLPlugin
spark.task.resource.gpu.amount                  0.25
spark.executor.resource.gpu.discoveryScript    ./usr/local/spark/getGpusResources.sh
spark.executor.resource.gpu.amount              1
spark.worker.resource.gpu.amount                1
spark.worker.resource.gpu.discoveryScript      /usr/local/spark/getGpusResources.sh
#spark.jars                                     /usr/local/spark/cudf-0.14-cuda10-2.jar,/usr/local/spark/rapids-4-spark_2.12-0.1.0.jar
spark.executor.memory                           7g
#spark.python.worker.memory                      10g
```
However, when I try start up a Spark Context Session, it results in the following error regarding the spark.plugin: 
```
20/08/04 09:53:34 ERROR SparkContext: Error initializing SparkContext.
java.lang.ClassNotFoundException: com.nvidia.spark.SQLPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:206)
	at org.apache.spark.util.Utils$.$anonfun$loadExtensions$1(Utils.scala:2696)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2694)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:160)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:146)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:525)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tgravescs** [comment]
what cluster type?  If its standalone you need to specify extraClassPath as the standalone executor starts earlier then it downloads the jars:
       --conf spark.executor.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR} \

See the getting started guide and look at the standalone cluster section: https://nvidia.github.io/spark-rapids/docs/get-started/getting-started.html

**Comment by vinhdiesal** [comment]
I've tried adding that to the defaults, however I still get the same error. 

here is the modified defaults file: 
```
spark.executor.processTreeMetrics.enabled  true
spark.rapids.sql.concurrentGpuTasks             1
spark.rapids.memory.pinnedPool.size            2G
spark.locality.wait                             0s
spark.executor.cores                             4
spark.task.cpus                                  1
spark.sql.files.maxPartitionBytes              512m
spark.sql.shuffle.partitions                    10
spark.driver.memoryOverhead                     4G
spark.executor.memoryOverhead                   4G
spark.task.resource.gpu.amount                  0.25
spark.executor.resource.gpu.discoveryScript    ./usr/local/spark/getGpusResources.sh
spark.executor.resource.gpu.amount              1
spark.worker.resource.gpu.amount                1
spark.worker.resource.gpu.discoveryScript      /usr/local/spark/getGpusResources.sh
spark.jars                                     /Users/vinhdiesal/Downloads/postgresql-42.2.14.jar
spark.executor.memory                           7g
#spark.python.worker.memory                      10g
spark.executor.extraClassPath          /usr/local/spark/cudf-0.14-cuda10-2.jar,/usr/local/spark/rapids-4-spark_2.12-0.1.0.jar
spark.plugins                                   com.nvidia.spark.SQLPlugin
```
Do I need to specify spark.plugins? Because if I comment it out, then there are no errors with the Spark Context. 
Also, I was looking for instructions on how to construct the spark-cudf dataframe? or is it automatic when I perform functions like spark.read.csv? Is there any API documentation I can reference? 

Thanks, 

Vinh

**Comment by tgravescs** [comment]
what environment are you trying to run?  Are you running on YARN, k8s, or standalone?

Documentation is here: https://nvidia.github.io/spark-rapids/Getting-Started/

"This requires no API changes from the user. The plugin will replace SQL operations it supports with GPU accelerated versions. If an operation is not supported it will fall back to using the Spark CPU version. "

This means that you use the regular Spark DataFrame API and the plugin will change the operation to a GPU operation if it is able to.  Nothing special has to be done by you other then configure it on.

We don't have an exact list of all the API we support but you can infer it from https://nvidia.github.io/spark-rapids/docs/compatibility.html and https://nvidia.github.io/spark-rapids/docs/configs.html (by looking at the configs you can turn on and off for certain operations). In general we support the main operations - sorts, joins, groupbys, but may not support all types or data.

**Comment by YeahNew** [comment]
> 
> 
> I followed the tutorial and set my `spark-defaults.conf` as follows:
> 
> ```
> spark.driver.memory              35g
> # spark.executor.extraJavaOptions  -XX:+PrintGCDetails -Dkey=value -Dnumbers="one two three"
> spark.ui.prometheus.enabled        true
> spark.executor.processTreeMetrics.enabled  true
> spark.rapids.sql.concurrentGpuTasks             1
> spark.rapids.memory.pinnedPool.size            2G
> spark.locality.wait                             0s
> spark.executor.cores                             4
> spark.task.cpus                                  1
> spark.sql.files.maxPartitionBytes              512m
> spark.sql.shuffle.partitions                    10
> spark.driver.memoryOverhead                     4G
> spark.executor.memoryOverhead                   4G
> spark.plugins                                   com.nvidia.spark.SQLPlugin
> spark.task.resource.gpu.amount                  0.25
> spark.executor.resource.gpu.discoveryScript    ./usr/local/spark/getGpusResources.sh
> spark.executor.resource.gpu.amount              1
> spark.worker.resource.gpu.amount                1
> spark.worker.resource.gpu.discoveryScript      /usr/local/spark/getGpusResources.sh
> #spark.jars                                     /usr/local/spark/cudf-0.14-cuda10-2.jar,/usr/local/spark/rapids-4-spark_2.12-0.1.0.jar
> spark.executor.memory                           7g
> #spark.python.worker.memory                      10g
> ```
> 
> However, when I try start up a Spark Context Session, it results in the following error regarding the spark.plugin:
> 
> ```
> 20/08/04 09:53:34 ERROR SparkContext: Error initializing SparkContext.
> java.lang.ClassNotFoundException: com.nvidia.spark.SQLPlugin
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at org.apache.spark.util.Utils$.classForName(Utils.scala:206)
> 	at org.apache.spark.util.Utils$.$anonfun$loadExtensions$1(Utils.scala:2696)
> 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
> 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
> 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
> 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
> 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
> 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
> 	at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2694)
> 	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:160)
> 	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:146)
> 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:525)
> 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:238)
> 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
> 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Thread.java:748)
> ```

I have encountered such a problem, I have the latest reply, please see #498

**Comment by vinhdiesal** [comment]
@YeahNew 
I tried your advice, the notebook executes, but if I look at the terminal I get the following errors: 
20/08/10 05:51:57 ERROR TaskSchedulerImpl: Lost an executor 0 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
```
20/08/10 05:51:57 ERROR TaskSchedulerImpl: Lost an executor 1 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:51:59 ERROR TaskSchedulerImpl: Lost an executor 3 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:51:59 ERROR TaskSchedulerImpl: Lost an executor 2 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:01 ERROR TaskSchedulerImpl: Lost an executor 4 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:01 ERROR TaskSchedulerImpl: Lost an executor 5 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:03 ERROR TaskSchedulerImpl: Lost an executor 6 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:03 ERROR TaskSchedulerImpl: Lost an executor 7 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:04 ERROR TaskSchedulerImpl: Lost an executor 8 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:05 ERROR TaskSchedulerImpl: Lost an executor 9 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:07 ERROR TaskSchedulerImpl: Lost an executor 10 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:07 ERROR TaskSchedulerImpl: Lost an executor 11 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:08 ERROR TaskSchedulerImpl: Lost an executor 12 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:10 ERROR TaskSchedulerImpl: Lost an executor 13 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:10 ERROR TaskSchedulerImpl: Lost an executor 14 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:11 ERROR TaskSchedulerImpl: Lost an executor 15 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:12 ERROR TaskSchedulerImpl: Lost an executor 16 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:13 ERROR TaskSchedulerImpl: Lost an executor 17 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:14 ERROR TaskSchedulerImpl: Lost an executor 18 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:16 ERROR TaskSchedulerImpl: Lost an executor 19 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:16 ERROR TaskSchedulerImpl: Lost an executor 20 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:18 ERROR TaskSchedulerImpl: Lost an executor 21 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:18 ERROR TaskSchedulerImpl: Lost an executor 22 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:20 ERROR TaskSchedulerImpl: Lost an executor 23 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:20 ERROR TaskSchedulerImpl: Lost an executor 24 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:21 ERROR TaskSchedulerImpl: Lost an executor 25 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:22 ERROR TaskSchedulerImpl: Lost an executor 26 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:23 ERROR TaskSchedulerImpl: Lost an executor 27 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:24 ERROR TaskSchedulerImpl: Lost an executor 28 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:25 ERROR TaskSchedulerImpl: Lost an executor 29 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:25 ERROR TaskSchedulerImpl: Lost an executor 30 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:27 ERROR TaskSchedulerImpl: Lost an executor 31 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:27 ERROR TaskSchedulerImpl: Lost an executor 32 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:29 ERROR TaskSchedulerImpl: Lost an executor 33 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
20/08/10 05:52:30 ERROR TaskSchedulerImpl: Lost an executor 34 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
```
I looked at the spark dashboard and it results in dead workers.

**Comment by tgravescs** [comment]
What environment are you running - standalone mode?
it sounds like you aren't getting the plugin jars and Cudf jar in the environment when the executor starts.
In standalone mode this requires --conf spark.executor.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR}  and the paths to those jars have to be local on the worker where the executor can get to them.  If you are running on yarn then you have to pass in the --jars option.

**Comment by YeahNew** [comment]
> 
> 
> @YeahNew
> I tried your advice, the notebook executes, but if I look at the terminal I get the following errors:
> 20/08/10 05:51:57 ERROR TaskSchedulerImpl: Lost an executor 0 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 
> ```
> 20/08/10 05:51:57 ERROR TaskSchedulerImpl: Lost an executor 1 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:51:59 ERROR TaskSchedulerImpl: Lost an executor 3 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:51:59 ERROR TaskSchedulerImpl: Lost an executor 2 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:01 ERROR TaskSchedulerImpl: Lost an executor 4 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:01 ERROR TaskSchedulerImpl: Lost an executor 5 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:03 ERROR TaskSchedulerImpl: Lost an executor 6 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:03 ERROR TaskSchedulerImpl: Lost an executor 7 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:04 ERROR TaskSchedulerImpl: Lost an executor 8 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:05 ERROR TaskSchedulerImpl: Lost an executor 9 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:07 ERROR TaskSchedulerImpl: Lost an executor 10 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:07 ERROR TaskSchedulerImpl: Lost an executor 11 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:08 ERROR TaskSchedulerImpl: Lost an executor 12 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:10 ERROR TaskSchedulerImpl: Lost an executor 13 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:10 ERROR TaskSchedulerImpl: Lost an executor 14 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:11 ERROR TaskSchedulerImpl: Lost an executor 15 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:12 ERROR TaskSchedulerImpl: Lost an executor 16 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:13 ERROR TaskSchedulerImpl: Lost an executor 17 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:14 ERROR TaskSchedulerImpl: Lost an executor 18 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:16 ERROR TaskSchedulerImpl: Lost an executor 19 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:16 ERROR TaskSchedulerImpl: Lost an executor 20 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:18 ERROR TaskSchedulerImpl: Lost an executor 21 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:18 ERROR TaskSchedulerImpl: Lost an executor 22 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:20 ERROR TaskSchedulerImpl: Lost an executor 23 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:20 ERROR TaskSchedulerImpl: Lost an executor 24 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:21 ERROR TaskSchedulerImpl: Lost an executor 25 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:22 ERROR TaskSchedulerImpl: Lost an executor 26 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:23 ERROR TaskSchedulerImpl: Lost an executor 27 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:24 ERROR TaskSchedulerImpl: Lost an executor 28 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:25 ERROR TaskSchedulerImpl: Lost an executor 29 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:25 ERROR TaskSchedulerImpl: Lost an executor 30 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:27 ERROR TaskSchedulerImpl: Lost an executor 31 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:27 ERROR TaskSchedulerImpl: Lost an executor 32 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:29 ERROR TaskSchedulerImpl: Lost an executor 33 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> 20/08/10 05:52:30 ERROR TaskSchedulerImpl: Lost an executor 34 (already removed): Unable to create executor due to com.nvidia.spark.SQLPlugin
> ```
> 
> I looked at the spark dashboard and it results in dead workers.

I have encountered the same problem，you can  add the "export LD_LIBRARY_PATH=/**yourpath**/cuda/lib64:$LD_LIBRARY_PATH" for each node you need to start the worker.

**Comment by vinhdiesal** [comment]
@tgravescs I'm running a standalone spark cluster with 3 nodes. The cudf and rapids jar files are located in the same directory on all the nodes. The same problem occurs. 

@YeahNew The `export LD_LIBRARY_PATH` is in the spark-env.sh and it was also in my bashrc and I still have the same problem. 

I even tried `spark.rapids.sql.enabled                       true` still the same issue.

**Comment by tgravescs** [comment]
You have a typo in your file: "spark.executor.extraClassPath          /usr/local/spark/cudf-0.14-cuda10-2.jar,/usr/local/spark/rapids-4-spark_2.12-0.1.0.jar"

Classpath separate is a ":", not a ",". Fix that and it should work. If not please try passing the parameters on the command line like we state in the getting starting guide plus add in spark.driver.extraClassPath as well.

$SPARK_HOME/bin/spark-shell \
       --master spark://${MASTER_HOST}:7077 \
       --conf spark.executor.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR} \
       --conf spark.driver.extraClassPath=${SPARK_CUDF_JAR}:${SPARK_RAPIDS_PLUGIN_JAR} \
       --conf spark.rapids.sql.concurrentGpuTasks=1 \
       --driver-memory 2G \
       --conf spark.executor.memory=4G \
       --conf spark.executor.cores=4 \
       --conf spark.task.cpus=1 \
       --conf spark.task.resource.gpu.amount=0.25 \
       --conf spark.rapids.memory.pinnedPool.size=2G \
       --conf spark.locality.wait=0s \
       --conf spark.sql.files.maxPartitionBytes=512m \
       --conf spark.sql.shuffle.partitions=10 \
       --conf spark.plugins=com.nvidia.spark.SQLPlugin

**Comment by Niharikadutta** [comment]
@tgravescs I was facing a similar issue on my Spark standalone cluster and this answer helped unblock me, however I had a quick question about supplying the `spark-rapids` and `cudf` jars to the workers. Do they always have to be located locally, is it not possible to download them from a remote storage?

**Comment by tgravescs** [comment]
so they have to be local on each node for standalone cluster right now, until you have a Spark version that contains:
https://issues.apache.org/jira/browse/SPARK-32119 and you can specify them with the --jars option.
So for instances once spark 3.1.X comes out and if you are using that version you should be able to send those with your application submission with --jars option.

**Comment by tgravescs** [comment]
resolving this since I think original issue is resolved. If further questions re-open or feel free to file new one with other questions.
