### ISSUE TITLE
[BUG] Harden calls to `RapidsBuffer.free`

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#5098]
As @gerashegalov mentioned in https://github.com/NVIDIA/spark-rapids/pull/5093#pullrequestreview-926548173, there are various places in the code where `free` is called on a `RapidsBuffer` instance with the assumption that it does not throw.  We either should have something like a `safeFree` implicit utility function or appropriate `try...finally` blocks to ensure attempts to release other resources at the same time are not interrupted.

**Comment by HaoYang670** [comment]
Is it needed to implement `safeMap` for `safeFree`?
