### ISSUE TITLE
[FEA] Support ANSI mode for SQL functions/operators

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#5119]
**Is your feature request related to a problem? Please describe.**
Below is the list of SQL functions/operators which are currently supported by the plugin but don't support ANSI mode. We have to add ANSI mode support for these functions to have same behavior as Spark. We may have to check the Spark versions in which ANSI support for these functions were added.

Please note that there are other functions which support ANSI mode but not listed here as we don't support those SQL functions in RAPIDS Accelerator for Apache Spark.

## SQL functions/operators.
- [x] Pmod
- [x] Remainder
- [x] ToUnixTimestamp
- [x] UnixTimestamp
- [x] GetTimestamp
- [x] DateAddInterval

**Comment by res-life** [comment]
Finished.
