### ISSUE TITLE
[BUG] Spark 3.3 integration tests arithmetic_ops_test.py::test_div_overflow_exception_when_ansi failures

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5182]
**Describe the bug**
latest spark 3.3 integration test build failed with:

13:05:19  FAILED ../../src/main/python/arithmetic_ops_test.py::test_div_overflow_exception_when_ansi[true-CAST(-9223372036854775808L as LONG) DIV -1]
13:05:19  FAILED ../../src/main/python/arithmetic_ops_test.py::test_div_overflow_exception_when_ansi[true-a DIV CAST(-1 AS INT)]
13:05:19  FAILED ../../src/main/python/arithmetic_ops_test.py::test_div_overflow_exception_when_ansi[true-a DIV b]

**Comment by andygrove** [comment]
The issue appears to be caused by https://github.com/apache/spark/commit/c2ed15de94f611972c463ff8bba9268c1e93fd30 which changes the exception that Spark throws. The tests expect `java.lang.ArithmeticException` but Spark is now throwing `org.apache.spark.SparkArithmeticException`.
