### ISSUE TITLE
IncompatibleClassChangeError when I run sql [BUG]

### ISSUE THREAD

**Issue by chenrui17** [NVIDIA/spark-rapids#520]
![image](https://user-images.githubusercontent.com/33319780/89528541-c8a30700-d81d-11ea-80f3-f6822907f140.png)
it looks like #489 fixed this bug, but i am not sure; and picture shows that now rapdis-0.2 need spark3.1 ? 
and my question is :  how can i successfuly run rapids-0.2 with spark 3.0 ? it seems that i I always have the problem of matching the versions of rapids and spark .

**Comment by jlowe** [comment]
We are working on supporting multiple Spark versions with the same plugin jar, and doing this requires the use of shim code that is compiled against the specific Spark version.  In this case it appears the wrong shim was loaded for the Spark version you are using.

If you have a `log4j.properties` file in the Spark conf directory (or copy the `log4j.properties.template` to `log4j.properties` if you don't have one yet), you can edit that file to show the shim loader's logging even though the spark shell suppresses anything below WARN by default.  Add this line to the `log4j.properties` file:
```
log4j.logger.com.nvidia.spark.rapids.ShimLoader=INFO
```

Then the next time you startup `spark-shell` you should see a few more logging lines that look something like this:
```
20/08/06 09:23:37 INFO ShimLoader: Loading shim for Spark version: 3.0.1-SNAPSHOT
20/08/06 09:23:37 INFO ShimLoader: Found shims: List(com.nvidia.spark.rapids.shims.spark301.SparkShimServiceProvider@6d4502ca)
```

Could you post the logging output you're seeing?  That will help show if the shim loader is not identifying your Spark version properly.

**Comment by tgravescs** [comment]
when you start the shell it should print the spark version as well, can you please make sure that is 3.0.0:
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.0
      /_/

**Comment by jlowe** [comment]
To double-check the issue, I built the jars on the latest branch-0.2 and was able to run queries with broadcast hash joins on Spark 3.0.0.  We also run nightly integration tests of branch-0.2 against Apache Spark 3.0.0 which have not failed recently.

**Comment by chenrui17** [comment]
The problem has been solved. The spark version is too high 
thanks all ~
