### ISSUE TITLE
Support multiple datatypes in `TypeSig.withPsNote()`

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#5203]
This is a follow-up issue for #5184.

`TypeSig.withPsNote()` currently supports only one type per note. If there are multiple types that are partially supported for the same reason, the current signature requires that each entry be made separately:
```scala
          .withPsNote(TypeEnum.BOOLEAN, "Unsupported as array index. " +
            "Only Literals supported as map keys.")
          .withPsNote(TypeEnum.BYTE, "Unsupported as array index. " +
            "Only Literals supported as map keys.")
          .withPsNote(TypeEnum.SHORT, "Unsupported as array index. " +
            "Only Literals supported as map keys.")
```
It would be good for us to support multiple types in `withPsNote()`, so that the code is less verbose.

**Comment by HaoYang670** [comment]
I'd like to have a try!

**Comment by HaoYang670** [comment]
Hi, which API do you think is better:
```scala
def withPsNote(dataTypes: List[TypeEnum.Value], note: String): TypeSig
```
or 
```scala
def withPsNote(note: String, dataType: TypeEnum.Value*): TypeSig
```
?
