### ISSUE TITLE
[DOC] Remove references to Spark 3.0.x in shim documentation

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#5209]
## Report incorrect documentation

We no longer support Spark 3.0.x and should remove references to it. 

**Location of incorrect documentation**

https://github.com/NVIDIA/spark-rapids/blob/branch-22.06/docs/dev/shims.md

**Describe the problems or issues found in the documentation**

Doc refers to Spark 3.0.x, and the links https://github.com/NVIDIA/spark-rapids/blob/main/sql-plugin/src/main/post320-treenode/scala/com/nvidia/spark/rapids/shims/v2/TreeNode.scala#L23 and do not appear to work. 

**Steps taken to verify documentation is incorrect**

**Suggested fix for documentation**

**Comment by razajafri** [comment]
> Doc refers to Spark 3.0.x, and the links https://github.com/NVIDIA/spark-rapids/blob/main/sql-plugin/src/main/post320-treenode/scala/com/nvidia/spark/rapids/shims/v2/TreeNode.scala#L23 and do not appear to work.

I can't find the referenced link in the doc

**Comment by jlowe** [comment]
> I can't find the referenced link in the doc

The link was fixed in #5291.
