### ISSUE TITLE
[FEA] Support array_remove

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5225]
I wish we can support array_remove.

Eg:
```
from pyspark.sql.functions import *
df = spark.createDataFrame([(["a", "b", "a"], ["b", "c"]), (["a","a"], ["b", "c"]), (["aa"], ["b", "c"])    ], ['x', 'y'])
df.write.format("parquet").mode("overwrite").save("/tmp/testparquet")
df = spark.read.parquet("/tmp/testparquet")
df.select(array_remove(df.x, "a").alias("remove")).collect()
```

```
    ! <ArrayRemove> array_remove(x#72, a) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.ArrayRemove
```

**Comment by revans2** [comment]
This one we might be able to do without any help from CUDF, but it is probably simpler to get them involved.

I think the ideal way to do this would be to do a segmented filter, but that does not exist. There is a segmented gather, and we could build our own segmented_filter with it, but I would rather work with CUDF on it. Also there is a map_filter function that we could implement with this same functionality.
