### ISSUE TITLE
Test maven dependencies more often than right before release

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5237]
**Is your feature request related to a problem? Please describe.**
We need to be testing our maven dependencies and publishing more than right before the release.

We have had multiple issues where dependencies weren't quite right and had to be fixed right at end of the release.
One example: https://github.com/NVIDIA/spark-rapids/pull/5235

**Comment by gerashegalov** [comment]
This should be automated, and part of nightly/weekly tests IMO. These issues are easily reproduced by running a `deploy` against a local repo file:///path/to/repo or some internal repo, and running release qa scripts / checklists against this test release repo

**Comment by NvTimLiu** [comment]
Creating pipelines for weekly check of the SNAPSHOT tools/spark-met/rapids-4-spark jars' dependency tree

**Comment by NvTimLiu** [comment]
jobs ready.

**Comment by NvTimLiu** [comment]
Close the issue as `rapids-dependency-check` is running now
