### ISSUE TITLE
[BUG] case insensitive column reading might now work for parquet/CSV

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#5262]
**Describe the bug**
I don't have a repro case for this right now, but looking at the code it is clear that parquet, orc, and CSV look at spark.sql.caseSensitive to decide if the column names should be normalized or not. For parquet/orc we look at the names and normalize them to lower case when re-writing the files, but from what I can see we do not change the names of the columns in the files to be normalized, and CUDF does not support matching names in a case-insensitive way. The only place that I find this config even set is in an ORC test. At a minimum we need to test this for CSV and Parquet too.

**Comment by revans2** [comment]
Actually I just did a quick test and it looks like it does work for parquet. At a minimum thought we should have tests for it added.

**Comment by HaoYang670** [comment]
I'd like to have a try!
