### ISSUE TITLE
[BUG]markdown link check failed issue

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#5267]
the markdown link checker failed because of https://github.blog/2022-04-12-git-security-vulnerability-announced/
I try to work around it by following this [guide](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/132#issuecomment-1098020617) but it seems the markdown checker cannot access the reference links, see the [log](https://github.com/NVIDIA/spark-rapids/runs/6058480187?check_suite_focus=true).
this is the [link](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/132) to track, I will close this issue when it is fixed.

**Comment by sameerz** [comment]
Related PR https://github.com/NVIDIA/spark-rapids/pull/5276

**Comment by nvliyuan** [comment]
since pr #5276 merged, close this issue
