### ISSUE TITLE
[BUG] HashAggregateSuite "Avg Distinct with filter" no longer valid when testing against Spark 3.1.0

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#528]
**Describe the bug**

HashAggregateSuite "Avg Distinct with filter" has started failing against Spark 3.1.0 due to changes in Spark functionality in this commit:

https://github.com/apache/spark/commit/1597d8fcd4c68e723eb3152335298c7d05155643

The test is expecting an exception but the query now runs without throwing an exception.

**Steps/Code to reproduce bug**
Run the test suite against Spark 3.1.0.

**Expected behavior**
The test should not fail. It needs to be updated to reflect Spark 3.1.0 behavior.

**Environment details (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by jlowe** [comment]
Fixed by #557
