### ISSUE TITLE
Dist jar build should not need to unshim and dedup external dependencies

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#5294]
**Is your feature request related to a problem? Please describe.**
Currently external dependencies such as jucx and spark-rapids-jni are pulled in for every aggregator jar, and then the dist jar build ends up needing to ensure all the important parts of those jars are unshim'd and dedup'd to handle these dependencies properly.  This can cause problems when the aggregator jars pull in slightly different versions of those dependencies (e.g.: spark-rapids-jni snapshot changed during the build).

**Describe the solution you'd like**
We shouldn't pull in external dependencies into the aggregator jar unpack process.  Those should be handled separately.  Wondering if we can mark them as `<scope>provided</scope>` in the aggregator poms and directly depend on them in the `dist` pom, using the assembly plugin or something similar to bundle those dependencies in the dist jar directly rather than needing to manually ensure the parallel worlds build doesn't accidentally munge or needlessly duplicate their contents.

**Comment by pxLi** [comment]
One potential issue of above solution could be that different spark shims could still use inconsistent jni libs to compile/build aggregator, but at last we just pick one version in dist pkg for all shims.

Probably we could specify a jni version at the beginning of the build, and use it for all shims building?

**Comment by jlowe** [comment]
> Probably we could also specify a jni version at the beginning of the build, and use it for all shims building?

Agreed.  For any dependency, cudf or otherwise, we should try to avoid pulling in dynamic versions that can change across multiple builds like SNAPSHOT.

**Comment by NvTimLiu** [comment]
Let me check this issue.

**Comment by NvTimLiu** [comment]
mvn `-Dspark-rapids-jni.version=22.06.0-snap-id` seems not work well, as the e.g. `22.06.0-20220505.003730-22` will be transform to `22.06.0-SNAPSHOT` instead. Then mvn will download the latest jar instead of the one specified by  `-Dspark-rapids-jni.version=22.06.0-snap-id`

CLI of mvn tree

 **mvn -X  dependency:tree  -f sql_plugin**

```
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=4549700, ConflictMarker.markTime=1494517, ConflictMarker.nodeCount=1498, ConflictIdSorter.graphTime=1885996, ConflictIdSorter.topsortTime=677917, ConflictIdSorter.conflictIdCount=247, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=21676873, ConflictResolver.conflictItemCount=488, DefaultDependencyCollector.collectTime=2355298897, DefaultDependencyCollector.transformTime=31704346}
[DEBUG] com.nvidia:rapids-4-spark-sql_2.12:jar:22.06.0-SNAPSHOT
[DEBUG]    com.nvidia:spark-rapids-jni:jar:cuda11:22.06.0-20220503.004039-20:compile
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.30:compile
[DEBUG]    com.nvidia:rapids-4-spark-common_2.12:jar:22.06.0-SNAPSHOT:compile
[DEBUG]    org.scala-lang:scala-library:jar:2.12.15:provided
[DEBUG]    org.scalatest:scalatest_2.12:jar:3.0.5:test


[DEBUG] Writing tracking file /root/.m2/repository/com/nvidia/spark-rapids-jni/22.06.0-SNAPSHOT/spark-rapids-jni-22.06.0-20220505.003730-22-cuda11.jar.lastUpdated
[INFO] com.nvidia:rapids-4-spark-sql_2.12:jar:22.06.0-SNAPSHOT
[INFO] +- com.nvidia:spark-rapids-jni:jar:cuda11:22.06.0-SNAPSHOT:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] +- com.nvidia:rapids-4-spark-common_2.12:jar:22.06.0-SNAPSHOT:compile
```

**Comment by NvTimLiu** [comment]
When I tried to build rapids-plugin with  `-Dspark-rapids-jni.version=22.06.0-20220420.050427-10`, it would got below conflict:

In file rapids4spark-version-info.properties, jni version: `cudf_version=22.06.0-20220420.050427-10`

In file spark-rapids-jni-version-info.properties: `version=22.06.0-SNAPSHOT`



```
root@d03af8a1b975:/spark-rapids/dist/target/tmp# cat rapids4spark-version-info.properties
version=22.06.0-SNAPSHOT
cudf_version=22.06.0-20220420.050427-10
user=
revision=aa3dbab35832bb8a70b3daa13cbbdc1171825180
branch=branch-22.06
date=2022-05-10T07:20:48Z
url=https://github.com/NVIDIA/spark-rapids.git
root@d03af8a1b975:/spark-rapids/dist/target/tmp#
root@d03af8a1b975:/spark-rapids/dist/target/tmp# cat spark-rapids-jni-version-info.properties
version=22.06.0-SNAPSHOT
user=
revision=854d2dd1619ddcc8514c80081c656dff166ff4d7
branch=HEAD
date=2022-04-20T04:58:01Z
url=https://github.com/NVIDIA/spark-rapids-jni.git
root@d03af8a1b975:/spark-rapids/dist/target/tmp#
```

**Comment by NvTimLiu** [comment]
We can build rapids with a specified version of spark-rapids-jni now.

Still need to do:
1, Not shade spark-rapids-jni & jucx dependency jars into spark-shim of aggregator jars, but zip them into the final dist jar
2, Update test scripts to include spark-rapids-jni & jucx dependency jars if they have the dependency of aggregator jar.
