### ISSUE TITLE
[FEA] test flag to fill 0xDEADBEEF in to-be-freed buffers

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#5309]
**Is your feature request related to a problem? Please describe.**
I wish the RAPIDS Accelerator for Apache Spark would provide a way to populate buffers released to allocator with some debug sentinel value such as traditional `0xDEADBEEF` . This would allow to uncover subtle issues such as #5183

**Describe the solution you'd like**
Allow some specifying an environment variable when running integration tests to the tune of `RESET_BUFFER_ON_FREE` that fills the buffer with  `0xDEADBEEF` before returning it back to RMM allocator

**Describe alternatives you've considered**
We could implement it in RMM 

**Additional context**
#5183 #5232

**Comment by gerashegalov** [comment]
> What about running with unpooled memory (i.e.: the CUDA allocator rather than a pooling allocator)? Then an access to freed memory should generate a segfault.

I think this would do it as well. There may be an advantage in an allocator-independent solution so one not unnecessarily inclined to blame the allocator, however this suggestion is much lower complexity

**Comment by jlowe** [comment]
We already support running with a non-pooled CUDA allocator via `spark.rapids.memory.gpu.pool=NONE`.  Is there anything else to do here?

**Comment by GaryShen2008** [comment]
We have created the CI job to run with pool=None. Close this issue.
