### ISSUE TITLE
[FEA] Support window.rowsBetween(Window.unboundedPreceding, -1) 

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#5314]
**Is your feature request related to a problem? Please describe.**
In [DLRM ETL code](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Recommendation/DLRM/preproc/spark_data_utils.py#L92), we have a window operation as below.
`windowed = Window.partitionBy('column_id').orderBy('part_id').rowsBetween(Window.unboundedPreceding, -1)`

The explain log says:
!Expression <WindowExpression> sum(diff#143L) windowspecdefinition(column_id#120, part_id#123 ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), -1)) cannot run on GPU 
because upper-bounds behind the current row is not supported. Found -1

**Describe the solution you'd like**
GPU can support such window operation.

**Comment by mythrocks** [comment]
Addressed by https://github.com/NVIDIA/spark-rapids/pull/9229
