### ISSUE TITLE
[FEA]Sort the single block info by the header for AVRO coalescing reading. 

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#5347]
**Is your feature request related to a problem? Please describe.**
The parent of coalescing reading will sort the blocks according to the file path, so the same block in the same file can be at least coalesced. For your case, if the blocks are sorted like

FileA(Header_same) -> FileB( Header_different) -> FIleC(Header_same), the FileA, FileB, FileC can't be coalesced.

What if we sort them as below
FileA(Header_same) -> FIleC(Header_same) -> FileB( Header_different)

Then FileA, FileC can be coalesced.

This is from https://github.com/NVIDIA/spark-rapids/pull/5306#discussion_r859324354

**Comment by jlowe** [comment]
Is the reordering going to be OK in practice?  Worried about a case where data was written out in a sorted order, and user query is assuming data read by a task will be read in a sorted order.  If we reorder the files then we'll come up with a different data order than the CPU would for the task, and I'm wondering if we could potentially break some expectations.

**Comment by wbo4958** [comment]
Yeah, It indeed breaks this case as Jason said.
