### ISSUE TITLE
[BUG] Spark 3.3 cache_test test_passing_gpuExpr_as_Expr[failures

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5357]
**Describe the bug**
07:55:49  FAILED ../../src/main/python/cache_test.py::test_passing_gpuExpr_as_Expr[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'true'}][ALLOW_NON_GPU(CollectLimitExec)]
07:55:49  FAILED ../../src/main/python/cache_test.py::test_passing_gpuExpr_as_Expr[{'spark.sql.inMemoryColumnarStorage.enableVectorizedReader': 'false'}][ALLOW_NON_GPU(CollectLimitExec)]

**Comment by tgravescs** [comment]
these had failed once in the past but didn't happen again: https://github.com/NVIDIA/spark-rapids/issues/4960

**Comment by tgravescs** [comment]
@razajafri can we xfail these tests if we won't have a fix soon?

**Comment by razajafri** [comment]
@tgravescs please review this [PR](https://github.com/NVIDIA/spark-rapids/pull/5422)
