### ISSUE TITLE
[FEA] Scala UDF: Support for String replaceFirst()

### ISSUE THREAD

**Issue by krajendrannv** [NVIDIA/spark-rapids#540]
@seanprime7 
Built-in catalyst functions support needed for:
String replaceFirst() method

**Additional context**
Sample UDF:
import java.util.regex.{Matcher, Pattern}
.replace("\\", "\\\\")
      .replaceFirst("%Y", Matcher.quoteReplacement("(?<year>\\d{4})"))
      .replaceAll("%Y", Matcher.quoteReplacement("(\\d{4})"))

**Comment by seanprime7** [comment]
@krajendrannv can you close this ticket as per our discussion?

**Comment by krajendrannv** [comment]
dropping replaceFirst(), since it is not a catalyst func
