### ISSUE TITLE
[FEA]Binary Data Write support for Parquet

### ISSUE THREAD

**Issue by krajendrannv** [NVIDIA/spark-rapids#5409]
**Is your feature request related to a problem? Please describe.**
 I wish the RAPIDS Accelerator for Apache Spark would support Binary Data type write support for Parquet file format

@viadea

**Comment by krajendrannv** [comment]
@sameerz

**Comment by jlowe** [comment]
I filed https://github.com/rapidsai/cudf/issues/10778 to request cuio functionality for this.

**Comment by viadea** [comment]
The use case needs the Array[Binary] writing support as well. If I need to open a separate feature request , please feel free to let me know.

**Comment by revans2** [comment]
This is done
