### ISSUE TITLE
[FEA] Scala UDF:Support for null Value operands

### ISSUE THREAD

**Issue by krajendrannv** [NVIDIA/spark-rapids#541]
@seanprime7 
 UDF Support for Expressions that can process null value operands
isNaN, NaNvl, IfNull, IsNull, isNotNull, NullIf, Nvl, Nvl2

**Comment by seanprime7** [comment]
@krajendrannv On a separate discussion, you said we can remove NaNvl, IfNull, IsNull, isNotNull, NullIf, Nvl and Nvl2 from the request.  Would you please modify the ticket to reflect that?
