### ISSUE TITLE
[FEA] Support reading binary data types from Parquet as binary (not strings)

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5416]
**Is your feature request related to a problem? Please describe.**
Currently we support reading binary as String from parquet if the schema is specifically specified and the parquet file schema is binary type.  But CUDF doesn't support reading those binary columns as binary.    Once CUDF supports it we should add support and tests on the plugin side.

**Comment by viadea** [comment]
The use case needs the Array[Binary] reading support as well. If I need to open a separate feature request , please feel free to let me know.

**Comment by tgravescs** [comment]
Note filed https://github.com/rapidsai/cudf/issues/11044 to be able to read binary as binary and not strings

**Comment by razajafri** [comment]
Closed as part of #6292 

There is a follow-on #6480
