### ISSUE TITLE
Revert change to xfail cache tests

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#5423]
A couple of cache tests were set to xfail due to changes in Spark 3.3.0. 

They should be reverted back after the new changes have been merge as part of #5257

**Comment by tgravescs** [comment]
since this requires code changes on our part, won't this just happen as part of https://github.com/NVIDIA/spark-rapids/issues/5257 ?

**Comment by jlowe** [comment]
Agree, there shouldn't be a separate issue/PR to re-enable the tests unless the fix is entirely outside of the RAPIDS Accelerator (e.g.: a fix purely in cudf or Apache Spark).

**Comment by razajafri** [comment]
The way I see it, the fix for #5257 doesn't require us to re-enable the tests and the revert could be overlooked.
