### ISSUE TITLE
[BUG] Handle regexp_replace inconsistency from https://issues.apache.org/jira/browse/SPARK-39107

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#5456]
**Describe the bug**
When passing an empty string (`''`) and a regular expression containing only `?` or `*` repetitions, the output is not consistent between Spark and cuDF.  Note this is actually a pure inconsistency with Spark's `regexp_replace`, it actually does not apply to what Java does as a standard.  

**Steps/Code to reproduce bug**
PySpark Example Code:
```
from pyspark.sql import SparkSession

spark = SparkSession.builder \
      .master("local[*]") \
      .appName("regex_empty_match") \
      .config("spark.rapids.sql.regexp.enabled", "true") \
      .config("spark.rapids.sql.explain","ALL") \
      .config("spark.rapids.sql.castStringToTimestamp.enabled","true") \
      .config("spark.rapids.sql.exec.CollectLimitExec", "true") \
      .config("spark.rapids.sql.castFloatToString.enabled", "true") \
      .config("spark.rapids.sql.hasExtendedYearValues", "false") \
      .getOrCreate()  

df = spark.sparkContext.parallelize([[""],[""],["AAA"]]).toDF(["a"])
df.show()

df.selectExpr("regexp_replace(a,'A*','_REPLACED_')").show()
```

Spark (CPU) Output:
```
+------------------------------------+
|regexp_replace(a, A*, _REPLACED_, 1)|
+------------------------------------+
|                                                               |
|                                                               |
|                _REPLACED__REPLACED_  |
+------------------------------------+
```

Plugin (GPU) Output:
```
+-------------------------------------+
|regexp_replace(a, A*, _REPLACED_, 1)|
+-------------------------------------+
|                          _REPLACED_                |
|                          _REPLACED_                |
|                _REPLACED__REPLACED_   |
+------------------------------------+
```

**Expected behavior**

Empty string input should be short circuited in the plugin as this is what is expected in certain versions of Spark.

**Additional context**

This bug was originally reported to Spark in https://issues.apache.org/jira/browse/SPARK-39107, and the issue was fixed in apache/spark#36457 for newer patch versions of Spark in 3.1,3.2,3.3 and master, so shims will need to be created to handle the original faulty behavior.

**Comment by anthony-chang** [comment]
Depends on #5450 being merged first
