### ISSUE TITLE
[BUG] `mvn test -Dbuildver=330` fails

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#5467]
**Describe the bug**
Running `mvn clean test -Dbuildver=330` fails with the error:

```
[INFO]      [exec] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project rapids-4-spark_2.12: Couldn't download artifact: com.nvidia:rapids-4-spark-aggregator_2.12:jar:spark330:22.06.0-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of snapshots-repo has elapsed or updates are forced
```

The workaround is to install first:

``` bash
mvn install -Dbuildver=330 -DskipTests
mvn test -Dbuildver=330
```

**Steps/Code to reproduce bug**
`mvn clean test -Dbuildver=330`

**Expected behavior**
Should work

**Environment details (please complete the following information)**
Not relevant. Reproduced on multiple environments.

**Additional context**
None

**Comment by sameerz** [comment]
This is This appears to be a limitation of the shading system, and needs to be documented.
