### ISSUE TITLE
[BUG] Spark 3.2.1 arithmetic_ops_test failures

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5474]
**Describe the bug**
Integration test failures on Spark 3.2.1

12:05:10  FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_pmod_by_zero[pmod(cast(-12 as {}), cast(0 as {}))-Decimal(7,7)]
12:05:10  FAILED ../../src/main/python/arithmetic_ops_test.py::test_mod_pmod_by_zero[cast(-12 as {}) % cast(0 as {})-Decimal(7,7)]

This might be the ArtithmeticException mismatch.

Possibly caused by https://github.com/NVIDIA/spark-rapids/pull/5354

**Comment by tgravescs** [comment]
@HaoYang670 can you take a look

**Comment by HaoYang670** [comment]
Sure, I will work on this.

**Comment by HaoYang670** [comment]
The reason of this bug is that in Spark 3.2 `cannotChangeDecimalPrecisionError` throws `java.lang.ArithmeticException` but not `SparkArithmeticException`:
```scala
java.lang.ArithmeticException: Decimal(expanded,-12,2,0}) cannot be represented as Decimal(7, 7).
  at org.apache.spark.sql.errors.QueryExecutionErrors$.cannotChangeDecimalPrecisionError(QueryExecutionErrors.scala:97)
```
