### ISSUE TITLE
[FEA] Add 330 unit tests to 340

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#5495]
330 has some special unit tests under "tests/src/test/330", and they should also be tested on 340.

**Comment by nartal1** [comment]
@firestarman - Looks like we are already testing 330 tests in 340. Some tests are failing which we are tracking in https://github.com/NVIDIA/spark-rapids/issues/6987. Can this issue be closed?

```
<profile>
            <id>release340</id>
            <activation>
                <property>
                    <name>buildver</name>
                    <value>340</value>
                </property>
            </activation>
            <properties>
                <spark.shim.test.sources>${project.basedir}/src/test/330+/scala,${project.basedir}/src/test/320+-noncdh-nondb/scala</spark.shim.test.sources>
            </properties>
        </profile>
```

**Comment by firestarman** [comment]
Fine with me, but we need to add the tests to 331 and 332 now.

**Comment by nartal1** [comment]
> Fine with me, but we also need to add the tests to 331 and 332.

Thanks! Filed issue https://github.com/NVIDIA/spark-rapids/issues/7101 to track 331 and 332.
