### ISSUE TITLE
[BUG] `avg literals bools` is failing on 330

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#5496]
**Describe the bug**
HashAggregatesSuite:
- avg literals bools fail *** FAILED ***

**Steps/Code to reproduce bug**
`mvn clean test -Dbuildver=330`

**Comment by revans2** [comment]
I am not 100% sure what happened, but Spark assumes for aggregations that each aggregation has a name. The error we are getting in 3.3 indicates that `avg(true)` didn't have a name. When I give it a name, then we get the old error back. I guess a rule changed somewhere and is not assigning a name to this invalid case, but I don't know for sure.
