### ISSUE TITLE
[DOC] Remove Spark from our naming of Qualification Tool

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5516]
## Report incorrect documentation
Looks like we missed removing "Spark" from couple of our github pages for the Qualification Tool. See https://nvidia.github.io/spark-rapids/docs/spark-qualification-tool.html

 Originally tried to clean up in https://github.com/NVIDIA/spark-rapids/issues/4398 but missed some.  "Spark Qualification tool"

**Comment by amahussein** [comment]
The changes require changing some files which can break URLs referencing the pages `docs/spark-qualification-tool.html` and `docs/spark-profiling-tool.html`
