### ISSUE TITLE
[BUG] Investigate regexp failures with unicode input

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#5521]
**Describe the bug**
Investigate regexp issue discovered during testing https://github.com/NVIDIA/spark-rapids/pull/5450

The following test failed in CI but could not be reproduced locally. The issue appears to be specific to the superscript character `¹`.

``` scala
  test("issue 5450 ci failure") {
    val pattern = Seq("D?")
    val inputs = Seq("\u000E\u0011\u0006h¹TEST\ud720AA")
    assertCpuGpuMatchesRegexpReplace(pattern, inputs)
  }
```

**Steps/Code to reproduce bug**
See above.

**Expected behavior**
Behavior should be consistent between CPU and GPU or we should fall back to CPU.

**Environment details (please complete the following information)**
Failed in CI.

**Additional context**
None

**Comment by andygrove** [comment]
This should get fixed by https://github.com/NVIDIA/spark-rapids/pull/5627

**Comment by anthony-chang** [comment]
Fixed with https://github.com/NVIDIA/spark-rapids/pull/5776
