### ISSUE TITLE
[FEA] Automatically adjust spark.rapids.sql.format.parquet.multiThreadedRead.numThreads to the same as spark.executor.cores

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5524]
I wish we can automatically adjust spark.rapids.sql.format.parquet.multiThreadedRead.numThreads to the same as spark.executor.cores.

This is because default setting for spark.rapids.sql.format.parquet.multiThreadedRead.numThreads=20 which may be too low if each executor has many more CPU cores.

**Comment by tgravescs** [comment]
there are other things to take into consideration than the pure number of cores.  I/O being the biggest as well as memory usage. I think we need more data before just changing.

**Comment by jlowe** [comment]
If we're not using at least as many threads for multithreaded reading as there are concurrent tasks in the executor then we're going to suffer relative to even the PERFILE reader which would have the same memory concerns.

**Comment by tgravescs** [comment]
We discussed this in triage meeting and I think the first thing to do here is do the max(20, number of cores). This way we don't get worse performance if someone has < 20 cores and it will up it for people with more.

There is still a chance with lots of cores we use more memory but using the number of cores shouldn't use more then the perfile reader like Jason mentions.

Also note this should be general for all the multi-thread readers, not just parquet.

**Comment by sinkinben** [comment]
I found this description in `configs.md`

> The maximum number of threads, on the executor, to use for reading small Parquet files in parallel. This can not be changed at runtime after the executor has started. Used with COALESCING and MULTITHREADED reader, see spark.rapids.sql.format.parquet.reader.type. **DEPRECATED: use spark.rapids.sql.multiThreadedRead.numThreads**

Should we adjust `spark.rapids.sql.multiThreadedRead.numThreads` rather than `spark.rapids.sql.format.parquet.multiThreadedRead.numThreads`?

**Comment by jlowe** [comment]
> Should we adjust spark.rapids.sql.multiThreadedRead.numThreads rather than spark.rapids.sql.format.parquet.multiThreadedRead.numThreads?

Yes, this change was not there when this issue was filed.  It was changed in #5870.
