### ISSUE TITLE
[FEA][Audit] - Push down StringEndsWith/Contains to Parquet 

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#5553]
**Is your feature request related to a problem? Please describe.**
We have copied code to GpuParquetScan where we are using `pushDownStringStartWith` .  Below PR replaces that with `parquetFilterPushDownStringPredicate' . Need to evaluate if we will have to pull in this change.

Spark commit - https://github.com/apache/spark/commit/1b7c636445

**Comment by jlowe** [comment]
This has been fixed.
