### ISSUE TITLE
[FEA] `GpuGlobalLimitExec` and `GpuCollectLimitExec` support `offset`

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#5589]
A new parameter named `offset` is introduced in `GlobalLimitExec` and `CollectLimitExec` from Spark 340. Accordingly, our GPU versions should also support it.

```
case class GlobalLimitExec(limit: Int = -1, child: SparkPlan, offset: Int = 0)
  extends BaseLimitExec {
  assert(limit >= 0 || (limit == -1 && offset > 0))
  ...
}
```

Now they will fall back to CPU for non-zero offset.

**Comment by revans2** [comment]
For 3.4.0 we have to either implement this or fall back to the CPU if offset is not 0.

**Comment by jlowe** [comment]
Fallback to CPU should be handled in https://github.com/NVIDIA/spark-rapids/pull/5472/commits/5cad5b778a9d21efdc30032503047ccfab828558
