### ISSUE TITLE
[BUG] Update partition code to remove single-split workaround

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#56]
**Describe the bug**
https://github.com/rapidsai/cudf/issues/4656 has been merged, so contiguous_split should now support splitting correctly even when there is only 1 split (no split points).  The plugin partitioning workaround that was put in for the single-partition case can be removed.

https://github.com/NVIDIA/spark-rapids/blob/7ec7473d4de01caeea791b0cb08e2a9798d62884/sql-plugin/src/main/scala/ai/rapids/spark/GpuSinglePartitioning.scala#L41-L42

**Comment by jlowe** [comment]
Fixed by #432.
