### ISSUE TITLE
Qualification tool use expressions parsed in duration and speedup factors

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5618]
**Is your feature request related to a problem? Please describe.**
Once we have expression parsing in place from https://github.com/NVIDIA/spark-rapids/issues/5617 we need to update the duration and speedup factors to take those into account.

We also want to output all that information into a csv file so end user can see it.

**Comment by tgravescs** [comment]
there may not be much here to do if we just change whether the exec is supported, but we may also want to dump out which exprs weren't supported.

**Comment by mattahrens** [comment]
We don't have to modify scores based on expressions. Rather, it's whether we support all expressions within that Exec.  If atleast one of the expressions is not supported then we fall back to CPU. In the comment , it's mentioned that we should print unsupported expressions. We are doing that in https://github.com/NVIDIA/spark-rapids/issues/6264. We can close this issue. (per @nartal1 )
