### ISSUE TITLE
[FEA] Let CPU handle Delta table's metadata related queries

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5624]
I wish we can just let CPU handle Delta table's metadata related queries.

The reason is there are some CPU fallbacks for Delta table's metadata queries such as the one reading _delta_log(Json files).
If the _delta_log is huge(say millions of rows), then the CPU fallback's performance penalty is not trivial. 

If we can just let CPU handle those metadata queries,  then at least the metadata queries' performance should be similar to CPU run.

**Comment by andygrove** [comment]
Here is an example of some of the expensive transitions in a delta lake metadata query.

![delta-lake-meta](https://user-images.githubusercontent.com/934084/175554419-a55a835c-b088-4b78-bbaa-da69959e7851.png)

**Comment by andygrove** [comment]
Setting `spark.rapids.sql.optimizer.enabled=true` removes some of the overhead here by avoiding moving to GPU for the final projection:

![delta-lake-opt](https://user-images.githubusercontent.com/934084/175555329-ebcee6ee-8aaa-428a-b369-4883b42d8d6b.png)

**Comment by viadea** [comment]
@andygrove I checked the query plan and time before and after setting `spark.rapids.sql.optimizer.enabled=true` and the result is similar -- 30s or so.
The plan are different though.
