### ISSUE TITLE
Building plugin separately from tools

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#5640]
The tools build is starting to take a significant amount of time (>1 minute).  It would be nice when iterating on the plugin to not have to build the tools project, since the plugin and tools do not depend on each other in any way.

**Comment by GaryShen2008** [comment]
Shall we move tools module into a separate profile just like spark2-sql-plugin?

**Comment by jlowe** [comment]
> Shall we move tools module into a separate profile just like spark2-sql-plugin?

Maybe, although @tgravescs mentioned it used to be a completely separate build but was later folded into the main build by default.  I find it a bit odd since it's very rare for someone to want to build both the plugin and tools since they share almost no code and PRs rarely touch both.  They're almost completely separate projects (only the couple of classes in the common project are shared IIRC).

It is possible to avoid building the tools project by specifying `-pl '!tools'` on the Maven cmdline, and one can avoid building the plugin by specifying `-pl tools`.  We may just resort to that as the solution.

**Comment by tgravescs** [comment]
it wasn't completely separate but we only built it with 311.  See https://github.com/NVIDIA/spark-rapids/pull/4230 for the change to enable for all.  I'm fine with going back, users just need to check before submitting PR or deal with premerge catching it.

**Comment by GaryShen2008** [comment]
Hi @jlowe,
Since we moved tools module to spark-rapids-tools, I think this issue can be closed.

**Comment by jlowe** [comment]
Agreed, thanks @GaryShen2008!
