### ISSUE TITLE
[BUG] Minimize false positives when falling back to CPU for end of line/string anchors and newlines

### ISSUE THREAD

**Issue by anthony-chang** [NVIDIA/spark-rapids#5659]
**Describe the bug**
The changes in #5610 add very broad checks for patterns containing end of line anchor `$` immediately next to a newline, begin-of-line anchor `^` or repetition that could produce empty results. However, this results in false positives:
1. `$` and `^` inside character classes are being treated as anchors, eg. the pattern `0*[D$3]` has no string anchors but will still fallback to CPU.
2. We are checking the entire AST node before/after a `$`, meaning something like `\na$` is allowed, but `(\na)$` will fallback to CPU. We should instead check only the component in the group that is closest to the `$`.
3. We fallback to CPU for cases such as `^([a-z]*)([0-9]*)([a-z]*)$` which have no line terminator characters. 

**Steps/Code to reproduce bug**
Test with the above examples. 

**Expected behavior**
We should support these cases on GPU, and they should be consistent with CPU

**Environment details (please complete the following information)**
N/A

**Additional context**
None.

**Comment by andygrove** [comment]
Examples in RegularExpressionSuite that we want to support

```
  // https://github.com/NVIDIA/spark-rapids/issues/5659
  testGpuFallback("String regexp_extract regex 1",
    "ProjectExec", extractStrings, conf = conf,
    execsAllowedNonGpu = Seq("ProjectExec", "ShuffleExchangeExec")) {
    frame => frame.selectExpr("regexp_extract(strings, '^([a-z]*)([0-9]*)([a-z]*)$', 1)")
  }

  // https://github.com/NVIDIA/spark-rapids/issues/5659
  testGpuFallback("String regexp_extract regex 2",
    "ProjectExec", extractStrings, conf = conf,
    execsAllowedNonGpu = Seq("ProjectExec", "ShuffleExchangeExec")) {
    frame => frame.selectExpr("regexp_extract(strings, '^([a-z]*)([0-9]*)([a-z]*)$', 2)")
  }
  ```
