### ISSUE TITLE
[BUG] Inconsistency between the time zone in the fallback reason and the actual time zone checked in RapidsMeta.checkTImeZoneId

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#5678]
**Describe the bug**
`RapidsMeta.checkTImeZoneId` compares the default time zone of the JVM to UTC in order to fallback on CPU, but quotes the session time zone as the offending actual

**Steps/Code to reproduce bug**
1. Start a Spark REPL with an unsupported i.e., non UTC default time zone such as `GMT-8`:
```bash
pyspark --driver-java-options -Duser.timezone=GMT-8 \
  --packages com.nvidia:rapids-4-spark_2.12:22.04.0 \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.rapids.sql.explain=ALL
```
2. Set session's time zone to UTC
```python
>>> spark.conf.set('spark.sql.session.timeZone', 'UTC')
```

3. Execute a query with a TimestampType
And observe a confusing message `Only UTC zone id is supported. Actual zone id: UTC`
```python
>>> spark.createDataFrame([ ['2022-06-01 07:45'] ], 'a string').selectExpr('hour(a)').collect()
22/05/27 08:23:58 WARN GpuOverrides: 
!Exec <ProjectExec> cannot run on GPU because not all expressions can be replaced
  @Expression <Alias> hour(cast(a#4 as timestamp), Some(UTC)) AS hour(a)#6 could run on GPU
    !Expression <Hour> hour(cast(a#4 as timestamp), Some(UTC)) cannot run on GPU because input expression Cast cast(a#4 as timestamp) (TimestampType is not supported when the JVM system timezone is set to GMT-08:00. Set the timezone to UTC to enable TimestampType support); Only UTC zone id is supported. Actual zone id: UTC
      !Expression <Cast> cast(a#4 as timestamp) cannot run on GPU because the GPU only supports a subset of formats when casting strings to timestamps. Refer to the CAST documentation for more details. To enable this operation on the GPU, set spark.rapids.sql.castStringToTimestamp.enabled to true.; Cast from StringType to TimestampType is not supported; Parsing the full rage of supported years is not supported. If your years are limited to 4 positive digits set spark.rapids.sql.hasExtendedYearValues to false.
        @Expression <AttributeReference> a#4 could run on GPU
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> a#4 could run on GPU

[Row(hour(a)=7)]
```
**Expected behavior**
A clear actionable message after determining if we can support non-UTC session time zone provided that the JVM time zone is the supported UTC

**Environment details (please complete the following information)**
- Any

**Additional context**
rapidsai/cudf#2477
h/t @viadea

**Comment by firestarman** [comment]
Shall we require both of session time zone id and the JVM time zone id to be "UTC" ?

**Comment by gerashegalov** [comment]
> Shall we require both of session time zone id and the JVM time zone id to be "UTC" ?
+1 It was my vote too on the internal thread.

**Comment by firestarman** [comment]
> +1 It was my vote too on the internal thread.

Thanks for the information. Do we have a deal now ?

**Comment by gerashegalov** [comment]
Feel free to propose a PR @firestarman

**Comment by firestarman** [comment]
@gerashegalov  Here is the fix https://github.com/NVIDIA/spark-rapids/pull/5767, could you help review ?
