### ISSUE TITLE
remove 3.3.1 from 3.3.0 shim

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5698]
**Is your feature request related to a problem? Please describe.**
https://github.com/NVIDIA/spark-rapids/pull/5693#pullrequestreview-990466460 temporarily added 3.3.1 to 3.3.0 while they are working on the 3.3.0 release. Before we ship 22.06 we need to remove that.

**Comment by pxLi** [comment]
spark 3.3.0 is out, we will need to update shim to depends on spark 330
