### ISSUE TITLE
[FEA] Support INT96 for parquet reads and writes

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#57]
**Is your feature request related to a problem? Please describe.**
SPARK-31159 went back to INT96 as the default for timestamps in parquet.  We do not currently support INT96 for writes, and reads okay for anything after  approximately October 1582.

We should document the read incompatibility, along with tests for it, and see what we can do to add in support for writes.

**Comment by sameerz** [comment]
It important to make sure writes after 1900-01-01 00:00:00 work.  Fixing writes and read before that date can be fixed as a follow-on.

**Comment by sameerz** [comment]
Depends on getting a fix from Parquet reader / writer in cudf.

**Comment by revans2** [comment]
This has not even been started on the cudf side.  Moving to to 0.3 because cudf 0.15 is in burn down.

**Comment by sameerz** [comment]
Related issue https://github.com/rapidsai/cudf/issues/5096

**Comment by razajafri** [comment]
Is this issue being worked on in cudf? I might be looking in the wrong place but I don't see PR attached to [rapidsai/cudf#5096](rapidsai/cudf#5096)

**Comment by revans2** [comment]
> Is this issue being worked on in cudf? I might be looking in the wrong place but I don't see PR attached to [rapidsai/cudf#5096](https://github.com/rapidsai/cudf/issues/5096)

Yes it is being worked on.  I just don't think that the PR is ready yet.

**Comment by sameerz** [comment]
The related PR is https://github.com/rapidsai/cudf/pull/6625

**Comment by jlowe** [comment]
Support for INT96 writes was added in #1068.  Is there anything left to do here (e.g.: documentation)?

**Comment by razajafri** [comment]
Yes, documentation is remaining. Either myself or @sameerz will get to it before the end of this sprint :crossed_fingers:
