### ISSUE TITLE
[BUG] Continue debugging OOM after ensuring device store is empty

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#570]
We experienced OOM while running TPCx-BB in the last week or two where the shuffle device store was empty and in a re-run of the query we couldn't allocate. The scenario we saw this under was running both `System.gc` forced in the driver and forcing GC in the executors.

Some potential culprits:

1. Buffers that are not in the store anymore (`removeBuffer`), but have a positive ref count when leaving it. We don't see leak logs, so this seems interesting.
2. Broadcast variables. The broadcasts are not in the store and are at the mercy of GC. 
3. Semaphore racing. Unlikely, but having tasks holding on to memory and _not_ the semaphore could be an issue.
4. Fragmentation (again). We saw an issue with this in the past with cudf causing fragmentation, and at the time of that bug fix, the only fragmentation experienced went away after the bug fix (https://github.com/rapidsai/cudf/pull/5793).

**Comment by abellina** [comment]
As mentioned here (https://github.com/NVIDIA/spark-rapids/issues/559#issuecomment-675633416), treating this as a potential new leak in cudf-0.15, as an older version from end of July does not cause OOM.

**Comment by abellina** [comment]
At this point we don't see a leak in cudf and are still trying to root cause this issue.

**Comment by abellina** [comment]
We root caused the issue reported by #559 to PTDS being ON, and it increasing fragmentation. The fix so far is for branch-0.2 to turn off PTDS. That said, RMM is working on a change that will help this (https://github.com/rapidsai/rmm/pull/532), by merging free lists in different streams, and our tests with PTDS ON + this change indicate that it resolves the OOM due to multiple free lists, as a stop gap on OOM the lists are merged and this satisfied allocations in cases where we failed before.

There is more to fragmentation than PTDS. There is also a single-stream fragmentation issue, and there is other work ongoing for that. But I think now we have root caused part of the issue, we also have logging (https://github.com/rapidsai/rmm/pull/529) that can be turned on to detect actual maximum free block size from RMM.

**Comment by abellina** [comment]
Moved to Release 0.3 as this is ongoing. Note some of the fixes went into Release 0.2.

**Comment by sameerz** [comment]
No longer actively seeing this, will run again on an EGX cluster and validate.

**Comment by abellina** [comment]
Update to close this issue:

1. Buffers were being materialized up front for the loopback case: https://github.com/NVIDIA/spark-rapids/pull/892. This contributed to OOM since these were non-spillable batches now waiting to be consumed.

2. https://github.com/NVIDIA/spark-rapids/issues/1168, https://github.com/NVIDIA/spark-rapids/issues/836: the broadcast issue is the main thing pending here. We have ideas on how to proceed, but need to get a concrete design and solve some issues around reference counting at the executor level. It is an issue also without UCX, but it is definitely more acute when using it since we run closer to full GPU memory.

3. No evidence of semaphore issues. If anything we hold onto it too much.

4. Fragmentation: this is an effect, rather than a cause, which ends up causing OOM in some cases. So far the fix for the loopback case helps this, and the broadcast fixes we are planning should account for other memory not in the spillable store (or live with concurrent tasks). 

There will be other sources of memory not accounted in this ticket:

1. When we are receiving data from the shuffle, we are not making it spillable right now. It would require us to have spillable buffers that are not complete, and potentially have a modality where we start receiving against host-backed buffers after a spill. Currently we hold onto the semaphore while fetching blocks and we have the max in-flight limit, so we have a workaround, but we'd like to move away from holding the semaphore and more configs.

2. Anything related to task-data is not being considered here.

3. Other sources of memory: streams, events, or memory not tracked in RMM. It seems that RMM maximum threshold could be used to some degree. It seems we have less control over this one.
