### ISSUE TITLE
[BUG] Spark 3.1 FAILED join_test.py::test_broadcast_join_mixed[FullOuter][IGNORE_ORDER] failed

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#575]
**Describe the bug**
Run the integration tests against Spark 3.1 and the following test fails, need to investigate

FAILED integration_tests/src/main/python/join_test.py::test_broadcast_join_mixed[FullOuter][IGNORE_ORDER]

**Comment by jlowe** [comment]
Is this still a P1 for the 0.3 release if this is specific to Spark 3.1.0?

**Comment by tgravescs** [comment]
test is xfailed out so we need to investigate

**Comment by tgravescs** [comment]
ran the test against spark 3.1.1 rc2 and its passing now, we should just remove the xfail.
