### ISSUE TITLE
Add jenkins/integration test support for parquet-hadoop tests jar for testing parquet encryption

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5771]
**Is your feature request related to a problem? Please describe.**
Followup to https://github.com/NVIDIA/spark-rapids/pull/5761 to add integration test support to download the parquet-hadoop-tests jar and ship it to the cluster so we can test with jenkins.

**Comment by NvTimLiu** [comment]
let me take this issue.

**Comment by NvTimLiu** [comment]
Let keep it open until the nightly jars get uploaded, and will verify the latest integration-test.tgz with IT jobs to make sure all the spark-3.2.0 CI jobs PASS the  `test_parquet_read_encryption` test cases.

After CI MR914 get merged, then we can close the issue.

**Comment by pxLi** [comment]
Merged MR 914, will keep monitoring status of test runs

**Comment by pxLi** [comment]
passed in all nightly CI. Closing it
