### ISSUE TITLE
[BUG] TimestampSuite is run on Spark 3.3.0 only

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#5775]
While fixing a recent merge conflict, I noticed that there's a TimestampSuite file that appears to be applicable to any Spark >= 3.3.0.  However it's in the test/src/test/330/ directory (the only thing in that directory), but all other non-common files are in the 320+ or 330+ directories.

**Comment by firestarman** [comment]
This can be fixed by https://github.com/NVIDIA/spark-rapids/pull/5749.

**Comment by firestarman** [comment]
ok to close
