### ISSUE TITLE
[BUG] repeated runs of `mvn package` without `clean` lead to missing spark-rapids-jni-version-info.properties in dist jar

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#5777]
**Describe the bug**
If the user invokes repeatedly `mvn package` on dist without clean, the dist jar ends up with a missing spark-rapids-jni-version-info.properties and the Plugin refuses to initialize.

**Steps/Code to reproduce bug**
Clean just once: 
```
mvn clean
```

Run package for dist module using 
```
mvn package -pl dist -am -Dbuildver=321 -DskipTests
```

Check the resulting jar has the build info for spark-rapids-jni
```
jar tvf dist/target/rapids-4-spark_2.12-22.08.0-SNAPSHOT-cuda11.jar  | grep spark-rapids-jni-version-info.properties
   170 Tue Jun 07 14:28:34 PDT 2022 spark-rapids-jni-version-info.properties
```

Re-run package for dist module using the same command:
```
mvn package -pl dist -am -Dbuildver=321 -DskipTests
```

Recheck the build info for spark-rapids-jni, and observe it's missing
```
jar tvf dist/target/rapids-4-spark_2.12-22.08.0-SNAPSHOT-cuda11.jar  | grep spark-rapids-jni-version-info.properties
echo $?
1
```

**Expected behavior**
`mvn package` with the same parameters should be reproducible and result in equivalent artifacts without a clean

As a workaround use `mvn clean package/install ...` 

**Environment details (please complete the following information)**
 Any

**Additional context**
Maybe related to #5603
h/t @NVnavkumar @anthony-chang

**Comment by res-life** [comment]
Yes, it's related to https://github.com/NVIDIA/spark-rapids/pull/5603

**Comment by res-life** [comment]
ls -lh rapids-4-spark_2.12-22.08.0-SNAPSHOT-cuda11.jar

```
// first time
377M  6  8 10:41 rapids-4-spark_2.12-22.08.0-SNAPSHOT-cuda11.jar

// second time
7.2M  6  8 10:44 rapids-4-spark_2.12-22.08.0-SNAPSHOT-cuda11.jar
```
