### ISSUE TITLE
[BUG] Spark 3.1 qa_nightly_select_test.py Full join test failures

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#578]
**Describe the bug**

Tests were xfailed out for now, we need to investigate and fix.

FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.byteF, test_table1.byteF FULL JOIN test_table1 ON test_table.byteF=test_table1.byteF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.shortF, test_table1.shortF FULL JOIN test_table1 ON test_table.shortF=test_table1.shortF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.intF, test_table1.intF FULL JOIN test_table1 ON test_table.intF=test_table1.intF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.longF, test_table1.longF FULL JOIN test_table1 ON test_table.longF=test_table1.longF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.floatF, test_table1.floatF FULL JOIN test_table1 ON test_table.floatF=test_table1.floatF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.doubleF, test_table1.doubleF FULL JOIN test_table1 ON test_table.doubleF=test_table1.doubleF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.booleanF, test_table1.booleanF FULL JOIN test_table1 ON test_table.booleanF=test_table1.booleanF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.strF, test_table1.strF FULL JOIN test_table1 ON test_table.strF=test_table1.strF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.dateF, test_table1.dateF FULL JOIN test_table1 ON test_table.dateF=test_table1.dateF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]
FAILED integration_tests/src/main/python/qa_nightly_select_test.py::test_select_join[test_table.timestampF, test_table1.timestampF FULL JOIN test_table1 ON test_table.timestampF=test_table1.timestampF][IGNORE_ORDER({'local': True}), INCOMPAT, APPROXIMATE_FLOAT]

**Steps/Code to reproduce bug**
Run spark 3.1.0 integration tests.

**Expected behavior**
tests pass

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by revans2** [comment]
This appears to have been caused by a bug in Spark.  The latest Spark 3.1.0-SNAPSHOT no longer fails.
