### ISSUE TITLE
[FEA] Replace post-round cast over decimal round

### ISSUE THREAD

**Issue by sperlingxx** [NVIDIA/spark-rapids#5803]
**Is your feature request related to a problem? Please describe.**
This is a follow-up issue of #5766 and #5786. Post-round casts are conducted over decimal rounds to fit the output precision and scale: [code1](https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuCast.scala#L1479) [code2](https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/mathExpressions.scala#L593) .

**Describe the solution you'd like**
They are sort of workaround, which can be replaced by cuDF built-in support.

**Comment by jlowe** [comment]
cudf will short-circuit the cast if the cast ends up being a no-op (e.g.: DECIMAL64 -> DECIMAL64).  As such this is relatively minor and would only be a real cast in the case where the pre-cast for round ends up crossing a precision boundary (e.g.: DECIMAL32 -> DECIMAL64).

**Comment by jlowe** [comment]
Closing this as wont fix for now, this is likely not getting fixed in cudf and performance impact is likely negligible.
