### ISSUE TITLE
[FEA] Enable pre-merge build in Databricks environment

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#581]
We run a nightly job for the plugin in the Databricks environment.  We should run the plugin integration tests in the Databricks environment as part of the pre-merge build.  

The build job for Databricks should run in AWS.  The build job should create two Databricks environments on startup, one to build the jar, and the other environment in which to run the integration tests on the jars.  The reason for the second environment is to ensure there are no side effects from running the tests in the build environment.  

The build environment does not need to run tests or have GPUs.  After building the plugin jar, the jar should be stored in DBFS.  

The second clean environment should have GPUs and run all the integration tests with the jar built in the CPU environment.  The second environment will need to be restarted with the plugin jar built from the first environment.  

Given the length of time to spin up a GPU environment with Databricks, both environments should be created in parallel.  However the second environment in which the jar needs to be tested will need to be restarted once the rapids plugin jar is available, so it picks up the plugin jar to run.  

This issue should be done after we can parallelize the builds per issue #545 .  

Once this is done, we would file a follow up issue to allow developers to manually trigger the build and integration tests in Databricks from their local environment.  They should be able to ssh into the build / test environment to debug any failures.

**Comment by NvTimLiu** [comment]
https://github.com/NVIDIA/spark-rapids/pull/965
