### ISSUE TITLE
Create separate nightly build for the latest Spark feature version

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5823]
**Is your feature request related to a problem? Please describe.**
We want to be able to split out the building of the latest Spark feature/major version release when its early on in developoment so we don't block the other builds.

To allow this I think we should create a separate jenkins nightly build just for that version/versions.  feature/major versions would be like 3.4.0, 3.5.0 or 4,.0.0. These many times are getting many new features frequently and won't be released for quite a while.

Specifically right now we want to split out building of Spark 3.4.0

**Comment by tgravescs** [comment]
@pxLi @GaryShen2008 @NvTimLiu

**Comment by pxLi** [comment]
I will create an independent spark340 build&test pipeline

**Comment by pxLi** [comment]
closing this one. feel free to reopen if needed
