### ISSUE TITLE
markdown link checks always failing in PRs

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5825]
**Describe the bug**
I'm tired of seeing the mark down link checks fail in the PRs.  This is mostly due to updating docs to point to a not yet released 22.06.  its been failing a long time and people just ignore it so even if you break something users likely won't look.

Is there a way to exclude certain urls or docs from these checks?

**Comment by jlowe** [comment]
Another option is to avoid updating the docs to point to a non-existent download artifact until just before the artifact is released.  This also has the benefit of minimizing the window where we have docs with bad links.

**Comment by tgravescs** [comment]
Yeah I would be ok if it failed for a few days, but multiple weeks in my opinion makes the check useless and\ distracting and might as well turn it off.

**Comment by sameerz** [comment]
We will try to merge the documentation for 22.08 as close to the merge to main ( Aug 5, per the release checklist https://github.com/NVIDIA/spark-rapids/issues/5792 ) as possible to address this.  

cc: @viadea @nvliyuan

**Comment by viadea** [comment]
The plan is to update the non-link related docs firstly. say PR-A
Then I just need to stage a link-related docs PR and put it in draft+approved mode firstly. (say PR-B)

On the day when @NvTimLiu is doing the final merge request, he can merge the PR-B together with the final merge PR.

**Comment by NvTimLiu** [comment]
Are we good to close this issue? As https://github.com/NVIDIA/spark-rapids/pull/6345 got merge to branch-22.08
