### ISSUE TITLE
[FEA] Spark 3.4 Merge PromotePrecision and CheckOverflow into decimal binary arithmetic

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5827]
**Is your feature request related to a problem? Please describe.**
our Spark 3.4 build fails due to changes: Merge PromotePrecision and CheckOverflow into deci…
…mal binary arithmetic. 

https://issues.apache.org/jira/browse/SPARK-39316
https://github.com/apache/spark/commit/301a13963808d1ad44be5cacf0a20f65b853d5a2

```
[ERROR] [Error] /home/tgraves/workspace/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:892: not found: type PromotePrecision
[ERROR] [Error] /home/tgraves/workspace/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:896: not found: type PromotePrecision
[ERROR] [Error] /home/tgraves/workspace/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:927: not found: type PromotePrecision
```

**Comment by revans2** [comment]
This is good news. It means that we can probably remove many of our hacks to try and undo the PromotePrecision operations in the first place.

**Comment by rwlee** [comment]
Per @amahussein -- this bug now exists in Databricks 3.3
