### ISSUE TITLE
[BUG] Spark3.1 tpch failures

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#586]
Spark 3.1 integration test failures:

08:43:58  FAILED src/main/python/tpch_test.py::test_tpch_q16[conf0][ALLOW_NON_GPU(BroadcastNestedLoopJoinExec,Or,IsNull,EqualTo,AttributeReference,BroadcastExchangeExec)]
08:43:58  FAILED src/main/python/tpch_test.py::test_tpch_q16[conf1][ALLOW_NON_GPU(BroadcastNestedLoopJoinExec,Or,IsNull,EqualTo,AttributeReference,BroadcastExchangeExec)]
08:43:58  FAILED src/main/python/tpch_test.py::test_tpch_q17[conf0][APPROXIMATE_FLOAT]
08:43:58  FAILED src/main/python/tpch_test.py::test_tpch_q17[conf1][APPROXIMATE_FLOAT]
08:43:58  FAILED src/main/python/tpch_test.py::test_tpch_q18[conf0][INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(TakeOrderedAndProjectExec,SortOrder,AttributeReference)]
08:43:58  FAILED src/main/python/tpch_test.py::test_tpch_q18[conf1][INCOMPAT, APPROXIMATE_FLOAT, ALLOW_NON_GPU(TakeOrderedAndProjectExec,SortOrder,AttributeReference)]
08:43:58  FAILED src/main/python/tpch_test.py::test_tpch_q20[conf0] - py4j.protocol.Py4...
08:43:58  FAILED src/main/python/tpch_test.py::test_tpch_q20[conf1] - py4j.protocol.Py4...

The issue is:
               Caused by: java.io.InvalidClassException: org.apache.spark.sql.execution.joins.EmptyHashedRelation$; no valid constructor
08:43:58  E                   	at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:169)

changed: https://github.com/apache/spark/commit/c37357a09236b6580d54ac81c6524d16d2599278

**Comment by tgravescs** [comment]
Note you have to run this with a non-local mode cluster so that it actually does a broadcast.

**Comment by tgravescs** [comment]
Note that I have xfailed the tests for now under https://github.com/NVIDIA/spark-rapids/pull/588

**Comment by kuhushukla** [comment]
I was unable to repro this failure on 3.1 with latest plugin. Will update here after further triaging.

**Comment by revans2** [comment]
This appears to be caused by a bug in Spark 3.1.0 that we didn't have time to track down.  The latest 3.1.0-SNAPSHOT no longer fails.
