### ISSUE TITLE
[BUG] Profiling tool on taking a really long time for integration tests

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#5896]
**Describe the bug**
Our profiling tool integration tests are taking really long time now, we need to investigate. 

One example is `Took 1005559ms to process `where as that similar log file used to take 3944ms.

We recently checked in https://github.com/NVIDIA/spark-rapids/pull/5868 so perhaps something unexpected is happening with that.

**Comment by tgravescs** [comment]
I have a feeling the intersect we added here is very costly when number of accumulators gets large:
https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/tools/src/main/scala/com/nvidia/spark/rapids/tool/planparser/SQLPlanParser.scala#L85

**Comment by zhanga5** [comment]
temporarily disabled profiling tool test on CSPs as impacted by this issue
