### ISSUE TITLE
[Audit][FEA] Overflow/precision handling for Decimal in arithmetic ops/`SUM`/`AVERAGE` in Spark 3.4+

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#5907]
**Is your feature request related to a problem? Please describe.**
This PR changed how Spark handles overflow and precision for the Decimal type in arithmetic ops and `SUM` and `AVERAGE`. This could change certain edge cases with Decimal. Need to confirm test output for these cases, since overflow might not be checked until after the `SUM` or `AVERAGE` is fully computed.

Spark PR: https://github.com/apache/spark/commit/301a139638

**Comment by razajafri** [comment]
This was fixed as part of https://github.com/NVIDIA/spark-rapids/pull/7362
