### ISSUE TITLE
[FEATURE] Add GpuMedian

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#5921]
**Is your feature request related to a problem? Please describe.**
As part of Spark 3.4 Spark supports median function

**Describe the solution you'd like**
Add a GpuMedian

**Additional context**
For more context please see https://github.com/apache/spark/commit/9e6f2dd726

**Comment by sameerz** [comment]
Spark will replace `median` with percentile 0.5, so we would not see `median` in the plan.
