### ISSUE TITLE
[FEA] Need a way to trigger the checks without retriggering CI

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#5931]
**Is your feature request related to a problem? Please describe.**
There should be a way to re-trigger checks that don't trigger CI. 

**Describe the solution you'd like**
I have had a case where CI passed but the `mvn verify` failed because it ran a few days ago. It will be nice to re-trigger just the checks without having to push an empty commit. e.g. `rerun checks` will trigger the checks again. The state of the CI shouldn't be affected unless there has been a change to the state of the commits.

**Describe alternatives you've considered**
The only alternative right now is to push an empty commit which shouldn't be necessary and also, the CI state is affected by this.

**Comment by pxLi** [comment]
we could always go to https://github.com/NVIDIA/spark-rapids/actions, and found the corresponding runs and retrigger that check

e.g. https://github.com/NVIDIA/spark-rapids/actions/runs/2586484219
![image](https://user-images.githubusercontent.com/8086184/176572007-d294d300-fe63-405e-ba3c-08a802e8d494.png)

**Comment by sameerz** [comment]
@razajafri does @pxLi 's solution accomplish what you are asking for?
