### ISSUE TITLE
[FEA] Support multithreaded and coalescing read strategies for Apache Iceberg

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#5942]
#5941 adds the basic, per-file read strategy for Apache Iceberg.  Multithreaded and coalescing read strategies should be added to Iceberg reads as they have for Parquet, ORC, and Avro reads.

This should be relatively straightforward with a potential bit of refactoring of the existing multithreaded and coalescing read support for Parquet.  The files are currently read one-at-a-time via the columnar reader `BatchReader` created in `GpuSparkScan`.  `createColumnarReader` could be updated to check for config settings to create multithreaded or coalescing columnar readers instead of the per-file batch reader (or the batch reader could be extended to act multithreaded/coalescing).  The `ReadTask` has all of the files to be read in the `CombinedScanTask`.

Note that I would recommend _not_ creating Iceberg-specific configs to control whether the reads are multithreaded or coalescing.  We already have Parquet and ORC specific configs for this, and underneath Iceberg are these same file formats.  I recommend using the same configs we already have for Parquet to determine if Iceberg's Parquet files should be read multithreaded or coalescing.  I don't see a case where we'd want to treat Iceberg Parquet files differently than raw Parquet files from the same distributed filesystem.

**Comment by sameerz** [comment]
Moving to 22.10, as there is not yet a PR up and we are in burndown.

**Comment by firestarman** [comment]
> Moving to 22.10, as there is not yet a PR up and we are in burndown.

Because the PR depends on https://github.com/NVIDIA/spark-rapids/pull/5941, which was merged several hours before. Now it is OK to file PR for this, shall we ?

**Comment by firestarman** [comment]
https://github.com/NVIDIA/spark-rapids/pull/6110

**Comment by firestarman** [comment]
> Is there an ETA to implement the COALESCE reader support in Iceberg (for parquet at least)? My on-prem benchmarks with the MULTITHREADED reader only showed minimal (1-2%) E2E performance improvement.

Will try to file a PR this week.
