### ISSUE TITLE
[DOC] Add estimated speedup factors to qualification tools

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#5965]
## Report needed documentation

**Report needed documentation**
Currently, the speedup used to calculate the average GPU estimated speedup is not documented anywhere.

**Describe the documentation you'd like**
We need to add a link to where those estimated speedups could be found. Perhaps, some instructions on how to update them if necessary.

**Comment by tgravescs** [comment]
I'm not sure we need these in our docs at this point unless we have had a customer request it.  If we do It would definitely be in some advanced user section.

**Comment by amahussein** [comment]
Closing this issue as won't fix for now.
