### ISSUE TITLE
[FEA] Enable Delta Lake integration tests with more Spark versions

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#5966]
**Is your feature request related to a problem? Please describe.**
PR https://github.com/NVIDIA/spark-rapids/pull/5912 adds a Delta Lake integration test that only runs on Datbricks 9.1 where Delta Lake is already configured.

We should start testing Delta Lake with other Spark versions as well.

**Describe the solution you'd like**
We need a way to specify the following arguments to spark when running the tests:

```
--packages io.delta:delta-core_2.12:1.2.1 \
  --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension \
  --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog \
```

However, the configs as shown require Spark 3.2.1 or later so we can't use these configs with earlier versions so we need to figure out how to change the test scripts to accommodate this and let us specify different configs per Spark version.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jlowe** [comment]
This was fixed as part of #6700.
