### ISSUE TITLE
[FEA] Fall back to CPU for more Delta Lake queries

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#5978]
**Is your feature request related to a problem? Please describe.**
The following Delta Table operations result in queries that are largely unsupported on GPU so we should detect these and fall back to CPU:

- merge
- history

(there are probably more and I am in the process of testing all the supported features)

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jlowe** [comment]
Note that merge involves a full outer join, so I'm not sure it's clear that we want to fallback in all cases there.  As far as history is concerned, I believe that's already been addressed by #7022.  Merge will be handled by #7007.
