### ISSUE TITLE
[FEA] Avoid Alluxio integration init scripts with Databricks when using custom Docker

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5986]
I wish we do not need alluxio integration init scripts with Databricks when using custom Docker.

Assume in the Docker image, the alluxio binary is already inside.

It means:
a. The configuring NVME disk space part can be part of Spark RAPIDS plugin.
b. Spark RAPIDS plugin can start alluxio master and worker automatically.
etc.

**Comment by GaryShen2008** [comment]
Is there any reason that we can't start Alluxio service in Databricks' init_script?
I suppose it'll be hard for the plugin code to configure the Alluxio worker correctly before Spark runs executors.

**Comment by GaryShen2008** [comment]
@viadea With the Databricks docker container, we have integrated the init script into the customized docker.
The user just needs to set the init script by using a local file path. https://github.com/NVIDIA/spark-rapids-container/tree/dev/Databricks#usage Step 13.
Is that ok to close this issue?

**Comment by viadea** [comment]
sure i am fine for now.thx
