### ISSUE TITLE
[FEA] Move `debug` functions into JNI

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids#5993]
Sometimes, we need to debug unit tests in Java JNI code. In such cases, we may want to print the content of a column. In the plugin, we have some `debug` functions to do that (like [here](https://github.com/NVIDIA/spark-rapids/blob/branch-22.08/sql-plugin/src/main/java/com/nvidia/spark/rapids/GpuColumnVector.java#L57)), but Java code in cudf's JNI doesn't have such functions.

We can move these debug functions from this repo down to the JNI level in cudf. By doing so, we can call these functions at any level.

**Comment by jlowe** [comment]
This is implemented by ai.rapids.cudf.TableDebug in cudf.
