### ISSUE TITLE
[FEA][SPARK-39737][SQL] PERCENTILE_CONT and PERCENTILE_DISC should support aggregate filter

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6037]
**Is your feature request related to a problem? Please describe.**
Spark support ANSI aggregation function percentile_cont and percentile_disc.
Starting Spark3.4, the two aggregates function support aggregate filter.

**Describe the solution you'd like**
Support aggregate filter of the two functions in rapids.

**Describe alternatives you've considered**
- Update the tests so we match the new behavior
- Update the documentation if we are not supporting it

**Additional context**
https://github.com/apache/spark/commit/ab277e123c

**Comment by sameerz** [comment]
We do not support percentile_cont and percentile_disc today.  Will close and if a user requests it we can add the functions.
