### ISSUE TITLE
[BUG][SPARK-39751][SQL] Rename hash aggregate key probes metric

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6038]
**Describe the bug**
Since Spark-3.4  the SQL metric to record average probes per key is renamed from  "`avg hash probe bucket list iters`" to "`avg hash probes per key`".
The API also changed from `getAvgHashProbeBucketListIterations` to `getAvgHashProbesPerKey`.

**Steps/Code to reproduce bug**
This issue is minor and is filed to be on the safe side since the UT of the tools use sample eventlogs.
This means that the metric may have different name than expected depending on the Spark-version.

**Expected behavior**
Make sure that the tools can handle the metric name correctly corresponding to the spark version.

**Additional context**
https://github.com/apache/spark/commit/899f6c90eb

**Comment by sameerz** [comment]
Unlikely to effect us - we do not think this message appears in any of the unit tests today.
