### ISSUE TITLE
[FEA] Add signoff check to gh-pages repository

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#604]
Enable pre-merge check to validate that a PR has been committed using git signoff in the gh-pages branch.  This is similar to issue #399 and specific to the gh-pages branch.  

Additional context: 
https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/CONTRIBUTING.md#sign-your-work

**Comment by GaryShen2008** [comment]
@pxLi Could you please check this issue？

**Comment by pxLi** [comment]
sure, I will take a look at this later :)

**Comment by pxLi** [comment]
I have tested the `signoff` feature provided by Github.

So we can enable the signoff check on branch `gh-pages` by following [enabling-required-commit-signing](https://docs.github.com/en/github/administering-a-repository/enabling-required-commit-signing). And the committer should follow [gpg-commit-signature-verification](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification#gpg-commit-signature-verification) instructions to setup their local env.

The GPG signature will provide sth like ![image](https://user-images.githubusercontent.com/8086184/91248767-01346180-e788-11ea-9bb2-2c544e51e5e0.png)

This is a little bit different from our [sign-your-work](https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/CONTRIBUTING.md#sign-your-work) which is checking if `Signed-off-by:` is included in the commit message. I think that we would be fine to just setup GPG check for `gh-pages` branch, and keep development branches as what they are. any thoughts? @sameerz

**Comment by jlowe** [comment]
Cryptographically signed commits and signoff are fundamentally different concepts.  The former authenticates the commit was performed by the person claiming they performed it, the latter is more about adhering to the Developer Certificate of Origin, which should be a conscious decision on the behalf of the committer submitting the work.  The Github signoff feature does not address the latter which is the one we're more interested in here.

We need to know that any changes submitted to this branch meet the same contribution criteria as our normal development branches.  We just need the existing `Signed-off-by` CI check that's performed in development branches do be performed in the `gh-pages` branch as well.

**Comment by pxLi** [comment]
Yep, as simple `git commit --signoff` check is OK for our cases, I will make this happen first

we could do both if need in the future :)

**Comment by sameerz** [comment]
Closed by PR #615
