### ISSUE TITLE
[FEA][SPARK-39699][SQL] Make CollapseProject smarter about collection creation expressions

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6053]
**Is your feature request related to a problem? Please describe.**
In some situations collapsing projects would cause a duplicate an expensive expression.

**Describe the solution you'd like**
Quoting

> If `CreateStruct` expression (or its friends) is referenced more than once, we can still collapse projects if the `CreateStruct` is only referenced by `GetStructField` and all the accesses to it are cheap. Cheap here means the result expression after we optimize `GetStructField` and `CreateStruct` is simple.

**Describe alternatives you've considered**
I was not sure if this applies to the plugin, but I thought to be on safe side to keep track of this Spark's improvement.

**Additional context**
https://github.com/apache/spark/commit/8749c17c20

**Comment by sameerz** [comment]
The changes are in the optimizer, we do not think this impacts the plugin.
