### ISSUE TITLE
Multiple scans for same data source with TPC-DS query59 with delta format [BUG]

### ISSUE THREAD

**Issue by chenrui17** [NVIDIA/spark-rapids#606]
**Describe the bug**
![image](https://user-images.githubusercontent.com/33319780/91169722-63e71800-e70a-11ea-9bef-ff604c411609.png)
when I use delta format of TPC-DS , query59 occurs this problem , but it  becomes normal when I set the format to parquet.

**Steps/Code to reproduce bug**
tpcdsTables.genData(
     location = "/user/work/data_100G_gpu",
     **format = "delta"**
     overwrite = true,
     partitionTables = true,
     useDoubleForDecimal = true,
     clusterByPartitionColumns = true,
     filterOutNullPartitionValues = false,
     tableFilter = Set.empty,
     numPartitions = 300,
     toolsLocation = Some("./tpc_toolkit"))

**Expected behavior**
when I use parquet format, big table named store_sales only scan once

**Environment details (please complete the following information)**
rapids-0.2

**Comment by revans2** [comment]
We don't currently support delta as a format, and have not really tested it.  Are you running on your own delta setup, or is this on databricks?  What are you using to generate the data?  Is it https://github.com/databricks/spark-sql-perf

**Comment by chenrui17** [comment]
yeah, we are using our own delta setup . Is there a schedule for this job

**Comment by revans2** [comment]
I'll try to find some time today to reproduce it on top of the local file system. If I can then I'll start to debug it, but it may take a little while as this type of bug is kind of notorious.

**Comment by revans2** [comment]
Just as an update I have not been able to reproduce the issue yet.  I am running a 0.2 version against spark 3.1-SNAPSHOT.  I am also setting the data up using a temp view, which might be the difference here.  I'll keep trying to make it match closer to what spark-sql-perf is doing.

**Comment by revans2** [comment]
I still have not been able to reproduce the issue.  The open source spark-sql-perf that I have access to appears to have different APIs from the one that you have been using, so I don't know if there is something fundamentally different about how it works.

I have been running with scale factor of 10 for the data set, but I disabled broadcast joins, and I still don't see duplicate reads.  I will make one last attempt with a scale factor 100 data set like you have, but after that I am going to need more help in reproducing the issue.

**Comment by revans2** [comment]
OK I finally got it to reproduce. I'll start to dig into this.

**Comment by revans2** [comment]
I found the bug. I really hate these because spark does a lot of magic to make some of the operations work, and very subtle changes can break the magic.  In this case it is a one line bug in how `GpuAggregateExpression` sets it's children.

But along the way I found several other bugs with canonicalization that I am going to try and fix along with this too, so it may be a while before I get a PR up.

**Comment by JustPlay** [comment]
@revans2 

I have a question:

We want to run the TPC-DS benchmark (total 103 queries;  with PT, TT, LD, DM four kind testing)

Does rapids-0.2 fully support LD and DM (PT is under testing, TT I think will be like the PT test, but i'am not sure whether LD and DM are supported or not by rapids-0.2)

**Comment by revans2** [comment]
I'm not 100% sure what PT, TT, LD and DM refer to.
