### ISSUE TITLE
[SPARK-39806][SQL] Accessing _metadata on partitioned table can crash a query

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6073]
**Describe the bug**
Projection used in `FileScanRDD` removes the partitioning columns from the produced row. The latter had  different schema than expected by the consumers, and was missing part of the data, which resulted in query failure.

The new changes alter the projection used in `FileScanRDD` to attach file metadata to a row produced by the reader. 

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**
`FileScanRDD` should produce rows matching expected schema, and containing all the requested data. Queries should not crash due to internal errors.

**Additional context**
https://github.com/apache/spark/commit/385f1c8e40

**Comment by firestarman** [comment]
I think we do not need to fix this, since [hidden metadata columns are not supported on GPU](https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/sql-plugin/src/main/330%2B/scala/com/nvidia/spark/rapids/shims/Spark330PlusShims.scala#L71).

**Comment by firestarman** [comment]
I am going to close this, if any concern, you can reopen it.
