### ISSUE TITLE
[SPARK-37287][SQL] Pull out dynamic partition and bucket sort from FileFormatWriter

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6074]
**Is your feature request related to a problem? Please describe.**
This change intends to pulls out the physical sort added by `FileFormatWriter` into logical planning. It adds a new logical rule `V1Writes` to add logical Sort operators based on the required ordering of a V1 write command. This behavior can be controlled by the new config `spark.sql.optimizer.plannedWrite.enabled` (default: true).

**Describe the solution you'd like**
- Since the default flag is true, we may need to look deeper to investigate if this affects the plugin/tests

**Additional context**
1. https://github.com/apache/spark/commit/256227477b

2.  Spark PR Followup: https://github.com/apache/spark/commit/f98f9f8566 [[SPARK-40107](https://issues.apache.org/jira/browse/SPARK-40107)][SQL] Pull out empty2null conversion from FileFormatWriter

**EDIT**

- Spark PR followup: https://github.com/apache/spark/commit/19df569ba6 [[SPARK-37287](https://issues.apache.org/jira/browse/SPARK-37287)][SQL][FOLLOWUP] Only apply AQE on top of V1 write commands when planned write is enabled

**Comment by jlowe** [comment]
Fixed by #7167
