### ISSUE TITLE
[DOC] Configs should be clear if runtime changes are honored

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#6100]
It is not always clear which configs are changeable at runtime and which are only examined on startup.  The config documentation ideally should explicitly call out all configs whose values are only examined on Spark startup.

**Comment by abellina** [comment]
Yes this would be great to add. Not unlike `.internalConf` we should probably have a `.startupOnly` tag.

**Comment by GaryShen2008** [comment]
Is it ok to add a new column like "Type" at the right of the column "Default value", with value of Runtime/Startup into the configs.md?

**Comment by tgravescs** [comment]
either that or we separate them into separate sections, saying these are runtime settable and the others are startup.  
I'm not sure how many are only settable at startup?  Perhaps good to make the list first.  would be good to get others input @revans2 @sameerz 

If we go with the column, not sure "Type" would be the name I would pick. I unfortunately can't think of great name right now, but I would think something more like "When Applied", "Applicable at"... I'm sure someone can come up with better name.
