### ISSUE TITLE
Alluxio integration testing

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#6121]
**Is your feature request related to a problem? Please describe.**
We have instructions on using alluxio and have done manual basic testing if we are going to promote we need to have more comprehensive testing for different file type, setups, resource managers, csps, etc and automated testing to make sure it doesn't break.

For 22.10, we create notebooks on Databricks to run integration test with Alluxio and plan https://github.com/NVIDIA/spark-rapids/issues/6660 to automate the test in 22.12.

**Comment by tgravescs** [comment]
For 22.10 release we should concentrate on testing base functionality in Alluxio and testing:

https://github.com/NVIDIA/spark-rapids/issues/6508 and if possible https://github.com/NVIDIA/spark-rapids/issues/6456

**Comment by GaryShen2008** [comment]
I created https://github.com/NVIDIA/spark-rapids/issues/6660 to trace the test automation.
And for this issue, let's just manually run it for 22.10.

**Comment by res-life** [comment]
@tgravescs 
setups/resource managers should be Standalone, Yarn, K8s.
CSPs should be Databricks, Dataproc or EMR.
But for now, we only support Databricks(Standalone).
Is it ok to just test Databricks environment for 22.10?

**Comment by tgravescs** [comment]
yes Databricks only is fine for 22.10

**Comment by res-life** [comment]
I tested the IT notebook and it passed.
IT path is `/alluxio/IT/it`
The output of the IT is:
```
Success: negative cases
Success: read type is MULTITHREADED, replace algo is TASK_TIME
Success: read type is MULTITHREADED, replace algo is CONVERT_TIME
Success: read type is COALESCING, replace algo is TASK_TIME
Success: read type is COALESCING, replace algo is CONVERT_TIME
Success: query11
Success: query27
Success: query28

```

**Comment by GaryShen2008** [comment]
Close it since 22.10 test has been done.
