### ISSUE TITLE
[FEA] Add `Nan` handling in the `GpuMin`

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#6164]
**Is your feature request related to a problem? Please describe.**
Currently, the `min` kernel will fall back to CPU if `hasNan = true`. We should let the `GpuMin` support the `hasNan` situation.
This is a sub task of #5320.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by HaoYang670** [comment]
Hi @revans2 @abellina  @ttnghia I want to replace all `Nan`s with `null`s in the `inputProjection` stage:
```scala
  override lazy val inputProjection: Seq[Expression] = Seq(
    child, 
    GpuOr(GpuIsNan(child), GpuIsNull(child)),
    GpuIsNan(child),
    // Replace `Nan`s with `null`s in the column
  )
```
But I don't find there is such a compute kernel I could use.
Does it need to file a follow-up issue to add such functionality, for example naming it `GpuReplace`, `GpuIfElse` or `GpuMap`?

**Comment by revans2** [comment]
I think you want to use [GpuIf](https://github.com/NVIDIA/spark-rapids/blob/8d6f6f5cc115e44d3b6afcdf85f4207f35912a69/sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala#L180). It does the If/Else that you want.  There does appear to be an optimized [replace_nans](https://github.com/rapidsai/cudf/blob/11d40a01064c9b4846e6db7d7b299350d0ba5074/cpp/include/cudf/replace.hpp#L138) operation in cudf that you could write a new wrapper around.

**Comment by ttnghia** [comment]
Wait, there is `replace_nans` API in cudf. Let's just call it. You may need to add JNI for it.

**Comment by HaoYang670** [comment]
> I think you want to use [GpuIf](https://github.com/NVIDIA/spark-rapids/blob/8d6f6f5cc115e44d3b6afcdf85f4207f35912a69/sql-plugin/src/main/scala/com/nvidia/spark/rapids/conditionalExpressions.scala#L180). It does the If/Else that you want. There does appear to be an optimized [replace_nans](https://github.com/rapidsai/cudf/blob/11d40a01064c9b4846e6db7d7b299350d0ba5074/cpp/include/cudf/replace.hpp#L138) operation in cudf that you could write a new wrapper around.

Sorry, using `GpuIf` doesn't make sense to me. I don't want to replace an expression with another. I want to replace the 
`Nan` elements in the column with `null`s. So I guess using `replace_nans` is our only option.
