### ISSUE TITLE
[FEA] Automated CI checks for broken hyperlinks.

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#618]
**Is your feature request related to a problem? Please describe.**
There have been a number of changes to the markdown documentation that has inadvertently left broken hyperlinks.  It is tedious to manually verify all the links at least land on a valid page.

**Describe the solution you'd like**
CI checks should look for changes to the markdown and verify all hyperlinks are traversable.  I'm sure there's existing packages to do this somewhere, or worst-case we could traverse the page as rendered in Github on the PR branch.

Bonus points for having a standalone tool that can be run as part of the release process to verify that when we publish documentation for the entire release that all hyperlinks in the documentation are valid at the time.

**Comment by sameerz** [comment]
Related: https://github.com/marketplace/actions/markdown-link-check

**Comment by nvliyuan** [comment]
close since #4907 merged
