### ISSUE TITLE
[FEA] log whether libcudf and libcudfjni were built for PTDS

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#619]
Given queriable flags defined in:

- CUDF JNI: https://github.com/rapidsai/cudf/issues/6112
- CUDF: https://github.com/rapidsai/cudf/issues/6111

Produce a log at startup stating whether the plugin is running with PTDS enabled. Additionally, if there is a mismatch between these two flags (jni/libcudf) we should ERROR at least, and one could argue we show blow up... since we have a PTDS and not-PTDS.

**Comment by jlowe** [comment]
Once the libcudf API is implemented, the Java tests should automatically fail if JNI was not compiled in the same manner.  That should effectively prevent a cudf build from mismatching.
