### ISSUE TITLE
[FEA] `ExecutionPlanCaptureCallback` should support capturing multiple plans

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#6229]
**Is your feature request related to a problem? Please describe.**
`ExecutionPlanCaptureCallback` is used in tests to capture query plans and allow them to be inspected but it currently only supports capturing a single query. 

When executing queries against Delta Lake tables, the Delta Lake implementation executes many metadata queries behind the scenes, and we currently have no way of capturing those in tests to confirm whether they were executed as intended (such as falling back to CPU).

**Describe the solution you'd like**
I propose that we enhance `ExecutionPlanCaptureCallback` to support capturing multiple queries.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jlowe** [comment]
Implemented by #7342
