### ISSUE TITLE
[SPARK-39951][SQL] Update Parquet V2 columnar check for nested fields

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6263]
#### Spark-context

- 3.4: https://github.com/apache/spark/commit/b9bc3c7919
- 3.3: https://github.com/apache/spark/commit/a0242eabae

#### What changes were proposed in SPARK pull request?

Update the `supportsColumnarReads` check for Parquet V2 to take into account support for nested fields.

#### Why are the changes needed in Spark?

Match Parquet V1 in returning columnar batches if nested field vectorization is enabled:
`PARQUET_VECTORIZED_READER_NESTED_COLUMN_ENABLED`

#### Does this PR introduce _any_ user-facing change?

Parquet V2 scans will return columnar batches with nested fields if the config is enabled.

```
private val supportsColumnar = enableVectorizedReader && sqlConf.wholeStageEnabled &&
    !WholeStageCodegenExec.isTooManyFields(sqlConf, resultSchema)
```

#### Why it might affect RAPIDS?

Changes are done in the parquetFileFormat and partitionReader.
Scanning the parquet will have `supportsColumnar` equal to true with nested types.
The new flag `spark.sql.parquet.enableNestedColumnVectorizedReader` is set to true by default.
It requires `spark.sql.parquet.enableVectorizedReader` which is set to true by default.

#### Impact on Testing?

Yes

#### Requires Doc update?

Yes

**Comment by sameerz** [comment]
Likely just a performance improvement in areas of the code we do not use.
