### ISSUE TITLE
[FEA] Support Percentile

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6266]
I wish we can support function Percentile.

Eg:
```
select percentile(ss_wholesale_cost,0.1) from tpcds.store_sales limit 10;

    ! <Percentile> percentile(ss_wholesale_cost#82, 0.1, 1, 0, 0) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.aggregate.Percentile
```

**Comment by revans2** [comment]
We need some more information here. Is this just for a reduction. Is this needed for group by as well? What about a window operation? What are the data types we need to support.  (Everything is cast to a double so it might be okay, but casting decimal to doubles can be difficult in some cases)

**Comment by revans2** [comment]
I filed https://github.com/rapidsai/cudf/issues/13885 to support group by and reduction aggregations for this in CUDF. It will not cover window. We would still need to use this for plugin side changes and testing.
