### ISSUE TITLE
[BUG] `date_format` cannot output with subsecond

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids#6284]
Currently, `GpuDateFormatClass` (`date_format`) does this for conversion:
```
    withResource(lhs.getBase.asTimestampSeconds) { tsVector =>
      tsVector.asStrings(strfFormat)
    }
```

The conversion `asTimestampSeconds` essentially strips all the subsecond information before formatting. This is wrong and we should fix that.

**Comment by sameerz** [comment]
@ttnghia can you please include a reproduce case in this issue, comparing CPU to GPU?

**Comment by ttnghia** [comment]
Oh I forgot to link this issue to https://github.com/NVIDIA/spark-rapids/pull/6271. This was already fixed in that PR.
