### ISSUE TITLE
[FEA] support ConcatWs sql function

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#63]
**Is your feature request related to a problem? Please describe.**
it would be great to support the `concat_ws` SQL function

https://github.com/rapidsai/cudf/issues/3726 was filed to get support from cudf.

**Comment by sameerz** [comment]
Follow up work on cudf, concatenating arrays of strings: https://github.com/rapidsai/cudf/issues/7727

**Comment by tgravescs** [comment]
The Spark behavior of concatws:

Separator parameter Api differences:
- SQL can pass column of strings as separator
- python and scala api's, only string as separator

Null Behavior:
- if separator is NULL, columns are null
- if column value is null it leaves off separator and value
- if passing in array of all nulls, then its left out without separator
- if array contains a null, it skips it and leaves separator off

Behavior:
- 0 input columns with separate specified return column of empty strings
- 1 column just return column unless Null separator then need column of null match number of rows
- if column value is empty is puts on separator
- if passing in empty array, then its left off without separator
- if passing array with empty strings, separator included
- 2 or more columns add in separator between column values
- For SQL if column specified as separator, the separator in the corresponding row is used

**Comment by tgravescs** [comment]
Note that concat and concat_ws have different behavior for nulls when all rows are null:

```
+-------+
|nullcol|
+-------+
|   null|
|notnull|
+-------+

>>> spark.sql("select concat_ws('-', nullcol, nullcol) as res from df").show(truncate=False)
+---------------+
|res            |
+---------------+
|               |
|notnull-notnull|
+---------------+

>>> spark.sql("select concat(nullcol, nullcol) as res from df").show(truncate=False)
+--------------+
|res           |
+--------------+
|null          |
|notnullnotnull|
+--------------+
```

**Comment by tgravescs** [comment]
similar cudf behavior for arrays with nulls doesn't match Spark, cudf will put null if any elements in array null, spark skips them. if all nulls, then get empty string

```
>>> res = spark.sql("select concat_ws('-', array(1, 2, null, 4)) as res from df")
>>> res.show()
+-----+
|  res|
+-----+
|1-2-4|
|1-2-4|
+-----+

>>> spark.sql("select concat_ws('-', array(null, null)) as res from df").show(truncate=False)
+---+
|res|
+---+
|   |
|   |
+---+
```

**Comment by tgravescs** [comment]
I discovered another weird case with the CPU where is you are concatenating an empty array and then another value, it leaves off the separator:

```
+--------------+
|      arrnames|
+--------------+
|            []|
|[Alice2, Bob2]|
+--------------+

>>> spark.conf.set("spark.rapids.sql.enabled", "false")
>>> res = df.select(concat_ws('-', df.arrnames, lit('z')))
>>> res.show()
+-------------------------+
|concat_ws(-, arrnames, z)|
+-------------------------+
|                        z|
|            Alice2-Bob2-z|
+-------------------------+

```

**Comment by tgravescs** [comment]
another example of arrays with null in middle:

```
+--------------+
|      arrnames|
+--------------+
|[a, null, ccc]|
|[Alice2, Bob2]|
+--------------+

res = df.select(concat_ws('***',df.arrnames).alias('s'))

+-------------+
|            s|
+-------------+
|      a***ccc|
|Alice2***Bob2|
+-------------+
```

**Comment by tgravescs** [comment]
example of spark with array of nulls:

```
+-------+
|   name|
+-------+
|beatles|
|  romeo|
+-------+

dfnew.select(concat_ws("-", array(lit(null)), col("name"), lit('a')).alias("s")).show()
+---------+
|        s|
+---------+
|beatles-a|
|  romeo-a|
+---------+
```

**Comment by tgravescs** [comment]
cudf Java layer PR: https://github.com/rapidsai/cudf/pull/8289
