### ISSUE TITLE
[FEA] Add `Nan` handling in `GpuArrayMin`

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#6317]
**Is your feature request related to a problem? Please describe.**
This is a subtask of #5320

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by HaoYang670** [comment]
Blocked by https://github.com/rapidsai/cudf/issues/11530

**Comment by sameerz** [comment]
If we can remove the `hasNaNs` config altogether, we can close issue #6332 without fixing it.
