### ISSUE TITLE
[BUG] Markdown link check always fails during release process

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#6360]
The markdown link check on premerge keeps failing after we update the download links before we release.  It's a chicken-and-egg problem where we want to update the docs before tagging the final build candidate, but we don't want to release the final build candidate until all of the final QA testing has completed.  During that final testing of the release candidate, the markdown link keeps failing on that dev branch as well as the next release's dev branch (due to automerge of the download page update).

The problem with markdown link checks always failing is that developers stop looking into any failures because it routinely fails during the release process.  Ideally we should get to the point where these are not always failing and thus a failure would be rare and interesting to investigate.  One idea is to have the markdown link check be aware of release download links (i.e.: links to a RAPIDS Accelerator jar in Maven Central) and not complain about the link if it is for a build version that has not officially released yet.  Ideas for checking if a build version has been released include:
- checking the list of tags on the repo to see if the version has a corresponding tag
- checking the Github Pages version of the download doc and seeing if the same release download link appears there
If the build version does not appear to be released, the markdown link check would not complain about that link.

**Comment by nvliyuan** [comment]
I checked the markdown link checker document and seems it does not support customized conditions. And if we just disable checks for dev branch and there is a real link issue, we cannot find it in time. How about this:
We just ignore these maven links(add two ignore-patterns: https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark-tools_2.12/22.08.0/*   and https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark_2.12/22.08.0/*) before release, and after we final release, I just draft a pr to update the ignore patterns(update two ignore-patterns to: https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark-tools_2.12/22.10.0/*   and https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark_2.12/22.10.0/*).

**Comment by jlowe** [comment]
> We just make download link updates of plugin directly in to gh-pages

I like where @pxLi is going with this, but I think there should be some refinements:
- We should update the links as part of the merge to main PR.  IMO the gh-pages should always come from main, not some custom changes directly on gh-pages
- We need to update the download links in the next dev branch after the previous dev branch has been released.  People can visit our github page, which defaults to the latest dev branch, and it would be nice if the download page docs they browse there have links to the released artifacts.

> And if we just disable checks for dev branch and there is a real link issue, we cannot find it in time.

To clarify, I don't think anyone is proposing we disable link checks on a dev branch wholesale.

I think either idea works (only update main/gh-pages during release, or ignore download links during release).  I have a slight preference for the former, as I think it's less PRs overall to achieve the desired effect.

**Comment by viadea** [comment]
@jlowe I also prefer the former solution. It means each time, I did not put the download links in dev branch. 
Instead, @pxLi 's team to update the main branch with the new download links during release time. 
Once main is updated, @nvliyuan  can update the gh-pages based on the difference between main and gh-pages branches.

Sounds good to everybody?

**Comment by nvliyuan** [comment]
> Sounds good to everybody?

yes, already sync with @NvTimLiu

**Comment by sameerz** [comment]
I added a step in the 22.10 release checklist https://github.com/NVIDIA/spark-rapids/issues/6255 for creating a PR to update the release links in the `main` branch.

**Comment by jlowe** [comment]
I also added a step to the 22.10 release checklist to create a PR to update the next development branch with the links to the previous release.

**Comment by sameerz** [comment]
Is this a duplicate of https://github.com/NVIDIA/spark-rapids/issues/10834 ?

**Comment by jlowe** [comment]
Yes.
