### ISSUE TITLE
[BUG] missing zip utility on CI 

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#6363]
**Describe the bug**
Observing in premerge log for a PR https://github.com/NVIDIA/spark-rapids/runs/7899133024?check_suite_focus=true#step:2:3358
```
[2022-08-18T12:53:24.882Z] ./integration_tests/run_pyspark_from_build.sh: line 68: zip: command not found
```
The intent of tolerating non-zero exit code seems to be a missing log4j.properties rather than the absence of `zip` https://github.com/NVIDIA/spark-rapids/blob/91ee6a61cf52afb05a419975d736826a49b10478/integration_tests/run_pyspark_from_build.sh#L68

**Steps/Code to reproduce bug**
Run premerge using `build` comment

**Expected behavior**
Should delete log4j.properties if present in the jar

**Environment details (please complete the following information)**
 - Environment location: CI
 - Spark configuration settings related to the issue: N/A

**Additional context**
#6049

**Comment by gerashegalov** [comment]
cc @pxLi @GaryShen2008 @NvTimLiu

**Comment by pxLi** [comment]
> cc @pxLi @GaryShen2008 @NvTimLiu

Looks good to me, we can add `zip` in our premerge dockerfile. 
Seems we should also update the integration tests prerequisites to include zip
