### ISSUE TITLE
[BUG] Cannot grow BufferHolder by size 559976464 because the size after growing exceeds size limitation 2147483632

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6364]
CTAS query failed with:
```
Cannot grow BufferHolder by size 559976464 because the size after growing exceeds size limitation 2147483632
```
If we disable the "GPU accelerated row-column transpose" feature in `GpuColumnarToRowExec.scala` and built a new Spark RAPIDS jar myself, then the query works fine.

I can have a reproduce using NDS data in house. Below are my reproduce steps:
**Env:**
Spark 3.2.1 standalone cluster(single node)
rapids-4-spark_2.12-22.08.0-20220812.093657-44.jar
1 * Quadro RTX 6000
apache-hive-3.1.2

**Sample Data**
1. Firstly use [NDS2.0 tool](https://github.com/NVIDIA/spark-rapids-benchmarks/tree/dev/nds) to generate 10GB TPCDS data with decimal and converted it to parquet files.
Say`store_sales` parquet files are located in `/home/xxx/data/tpcds_parquet_10G/store_sales` directory.

2. Create a Hive external table on top of `store_sales`
```
CREATE EXTERNAL TABLE `nds`.`store_sales` (
  `ss_sold_time_sk` INT,
  `ss_item_sk` INT,
  `ss_customer_sk` INT,
  `ss_cdemo_sk` INT,
  `ss_hdemo_sk` INT,
  `ss_addr_sk` INT,
  `ss_store_sk` INT,
  `ss_promo_sk` INT,
  `ss_ticket_number` INT,
  `ss_quantity` INT,
  `ss_wholesale_cost` decimal(7,2),
  `ss_list_price` decimal(7,2),
  `ss_sales_price` decimal(7,2),
  `ss_ext_discount_amt` decimal(7,2),
  `ss_ext_sales_price` decimal(7,2),
  `ss_ext_wholesale_cost` decimal(7,2),
  `ss_ext_list_price` decimal(7,2),
  `ss_ext_tax` decimal(7,2),
  `ss_coupon_amt` decimal(7,2),
  `ss_net_paid` decimal(7,2),
  `ss_net_paid_inc_tax` decimal(7,2),
  `ss_net_profit` decimal(7,2),
  `ss_sold_date_sk` INT)
USING parquet
PARTITIONED BY (ss_sold_date_sk)
LOCATION 'file:/home/xxx/data/tpcds_parquet_10G/store_sales/';
```
Then run below to detect all Hive partitions automatically for this table.
```
MSCK REPAIR TABLE `nds`.`store_sales`;
```

3. Create another table with a new column with String type.
Here I try to create a task skew situation, so it only has a single value. 
```
create table testbyhao_src as select *, 'a string col' newcol from nds.store_sales limit 5000000;
```

4. Run below query to trigger the issue
```
set spark.rapids.sql.hasNans=false;
set spark.sql.files.maxPartitionBytes=256MB;
set spark.sql.shuffle.partitions=1000;
set spark.rapids.sql.castDecimalToString.enabled=true;
set spark.sql.adaptive.coalescePartitions.enabled=false;

create table testbyhao as 
select ss_sold_time_sk, 
ss_item_sk, 
concat('abcdef ', ss_customer_sk) as ss_customer_sk, 
ss_cdemo_sk, 
ss_hdemo_sk, 
ss_addr_sk, 
ss_store_sk,
max(COALESCE(ss_wholesale_cost,"abc")) as ss_wholesale_cost,
max(COALESCE(ss_list_price,'def')) as ss_list_price,
max(ss_sales_price),
case when min(ss_sales_price)=1 then 'abcdefgh' 
when min(ss_sales_price)=2 and MAX(COALESCE(ss_sales_price,0)) > 10 then 'abcdefgh' else 'abcdefghxyz' end as ss_sales_price,
max(COALESCE(ss_ext_discount_amt,'SOMEVALUEFORTEST')) as ss_ext_discount_amt,
max(COALESCE(ss_ext_sales_price,'SOMEVALUEFORTEST')) as ss_ext_sales_price,
max(COALESCE(ss_ext_wholesale_cost,'SOMEVALUEFORTEST')) as ss_ext_wholesale_cost,
max(COALESCE(ss_ext_list_price,'SOMEVALUEFORTEST')) as ss_ext_list_price,
max(COALESCE(ss_ext_tax,'SOMEVALUEFORTEST')) as ss_ext_tax,
max(COALESCE(ss_coupon_amt,'SOMEVALUEFORTEST')) as ss_coupon_amt,
max(COALESCE(ss_net_paid,'SOMEVALUEFORTEST')) as ss_net_paid,
max(COALESCE(ss_net_paid_inc_tax,'SOMEVALUEFORTEST')) as ss_net_paid_inc_tax,
max(COALESCE(ss_net_profit,'SOMEVALUEFORTEST')) as ss_net_profit,

cast(max(COALESCE(ss_wholesale_cost*2,'SOMEVALUEFORTEST')) as decimal(18,3)) as ss_wholesale_cost_2,
max(COALESCE(ss_list_price*2,'SOMEVALUEFORTEST')) as ss_list_price_2,
max(COALESCE(ss_sales_price*2,'SOMEVALUEFORTEST')) as ss_sales_price_2,
max(COALESCE(ss_ext_discount_amt*2,'SOMEVALUEFORTEST')) as ss_ext_discount_amt_2,
max(COALESCE(ss_ext_sales_price*2,'SOMEVALUEFORTEST')) as ss_ext_sales_price_2,
max(COALESCE(ss_ext_wholesale_cost*2,'SOMEVALUEFORTEST')) as ss_ext_wholesale_cost_2,
max(COALESCE(ss_ext_list_price*2,'SOMEVALUEFORTEST')) as ss_ext_list_price_2,
max(COALESCE(ss_ext_tax*2,'SOMEVALUEFORTEST')) as ss_ext_tax_2,
max(COALESCE(ss_coupon_amt*2,'SOMEVALUEFORTEST')) as ss_coupon_amt_2,
max(COALESCE(ss_net_paid*2,'SOMEVALUEFORTEST')) as ss_net_paid_2,
max(COALESCE(ss_net_paid_inc_tax*2,'SOMEVALUEFORTEST')) as ss_net_paid_inc_tax_2,
max(COALESCE(ss_net_profit*2,'SOMEVALUEFORTEST')) as ss_net_profit_2,

max(COALESCE(ss_wholesale_cost*3,'SOMEVALUEFORTEST')) as ss_wholesale_cost_3,
max(COALESCE(ss_list_price*3,'SOMEVALUEFORTEST')) as ss_list_price_3,
max(COALESCE(ss_sales_price*3,'SOMEVALUEFORTEST')) as ss_sales_price_3,
max(COALESCE(ss_ext_discount_amt*3,'SOMEVALUEFORTEST')) as ss_ext_discount_amt_3,
max(COALESCE(ss_ext_sales_price*3,'SOMEVALUEFORTEST')) as ss_ext_sales_price_3,
max(COALESCE(ss_ext_wholesale_cost*3,'SOMEVALUEFORTEST')) as ss_ext_wholesale_cost_3,
max(COALESCE(ss_ext_list_price*3,'SOMEVALUEFORTEST')) as ss_ext_list_price_3,
max(COALESCE(ss_ext_tax*3,'SOMEVALUEFORTEST')) as ss_ext_tax_3,
max(COALESCE(ss_coupon_amt*3,'SOMEVALUEFORTEST')) as ss_coupon_amt_3,
max(COALESCE(ss_net_paid*3,'SOMEVALUEFORTEST')) as ss_net_paid_3,
max(COALESCE(ss_net_paid_inc_tax*3,'SOMEVALUEFORTEST')) as ss_net_paid_inc_tax_3,
max(COALESCE(ss_net_profit*3,'SOMEVALUEFORTEST')) as ss_net_profit_3,

PERCENT_RANK() OVER(PARTITION BY max(COALESCE(newcol,'SOMEVALUEFORTEST')) ORDER BY max(COALESCE(newcol, 0))) AS aaaa
from testbyhao_src
group by 1,2,3,4,5,6,7
;
```

Note: Here I disabled `spark.sql.adaptive.coalescePartitions.enabled` because if the AQE feature kicks in, it may firstly fail with GPU OOM. So you may not see the expected error.
And also to-be-safe, I set `spark.sql.shuffle.partitions=1000` to large enough to avoid OOM of GPU memory as well.

If you read it here, you will get the error:
```
22/08/19 00:48:47 WARN TaskSetManager: Lost task 705.1 in stage 5.0 (TID 2022) (192.192.192.2 executor 0): org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:500)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:321)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$16(FileFormatWriter.scala:229)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Cannot grow BufferHolder by size 559976464 because the size after growing exceeds size limitation 2147483632
	at org.apache.spark.sql.catalyst.expressions.codegen.BufferHolder.grow(BufferHolder.java:71)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.grow(UnsafeWriter.java:63)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.writeUnalignedBytes(UnsafeWriter.java:127)
	at org.apache.spark.sql.catalyst.expressions.codegen.UnsafeWriter.write(UnsafeWriter.java:110)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.writeFields_0_2$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:92)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:304)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1496)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:311)
	... 9 more
```

Hope it is not too complex. 
I think I love NDS data so I used it as my data source. If you have better way to generate large enough data, that is fine too.

**Comment by sameerz** [comment]
Since the code that caused the issue was reverted, I am moving this to 22.10.

**Comment by amahussein** [comment]
I haven't made any changes to the block between (L920-L936)  [https://github.com/amahussein/spark-rapids/blob/333a508700859802c8fe22935212f4a091[…]c/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala](https://github.com/amahussein/spark-rapids/blob/333a508700859802c8fe22935212f4a091dae38e/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala#L920-L936).

```
    // We can support upto 2^31 bytes per row. That is ~250M columns of 64-bit fixed-width data.
    // This number includes the 1-bit validity per column, but doesn't include padding.
    // We are being conservative by only allowing 100M columns until we feel the need to
    // increase this number. Spark by default limits codegen to 100 fields
    // "spark.sql.codegen.maxFields".
    if ((1 until 100000000).contains(output.length) &&
        CudfRowTransitions.areAllSupported(output)) {
      val localOutput = output
      rowBased.mapPartitions(rowIter => GeneratedInternalRowToCudfRowIterator(
        rowIter, localOutput.toArray, localGoal, semaphoreWaitTime, streamTime, opTime,
        numInputRows, numOutputRows, numOutputBatches))
    } else {
      val converters = new GpuRowToColumnConverter(localSchema)
      rowBased.mapPartitions(rowIter => new RowToColumnarIterator(rowIter,
        localSchema, localGoal, converters,
        numInputRows, numOutputRows, numOutputBatches, semaphoreWaitTime, streamTime, opTime))
    }
```

Basically, that block checks if the number of columns in the schema is less than "100000000". If so, it will pick the optimized `InternalRowToCudf`
This check might lead to the crash because a schema containing strings may exceed the size  2^31 bytes.
However, this is not a simple fix. It is a fundamental design issue because in order to know the row size, we have to process the entire columns to get their sizes.

**Comment by jlowe** [comment]
To clarify, the problem that originally triggered this issue was 2^31 bytes *per row* was exceeded, not 2^31 bytes per batch (i.e.: the cudf limits).  It is very, very unlikely any valid data is going to exceed the 2GB row limit.  The problem that initially triggered the issue was pretty clearly a data corruption issue, as it was trying to build a _single row_'s value, and one of the string columns had a >100MB value that when added to the current size of the single row caused it to exceed the 2GB limit (implying earlier columns had already pushed it crazy far in size).  I suspect there's a problem with GPU-accelerated string column conversions that corrupted one or more string column values (e.g.: causing the character data across all rows in the string column to appear in one row or some similar type of row value expanding corruption).

**Comment by amahussein** [comment]
> To clarify, the problem that originally triggered this issue was 2^31 bytes _per row_ was exceeded, not 2^31 bytes per batch (i.e.: the cudf limits). It is very, very unlikely any valid data is going to exceed the 2GB row limit. The problem that initially triggered the issue was pretty clearly a data corruption issue, as it was trying to build a _single row_'s value, and one of the string columns had a >100MB value that when added to the current size of the single row caused it to exceed the 2GB limit (implying earlier columns had already pushed it crazy far in size). I suspect there's a problem with GPU-accelerated string column conversions that corrupted one or more string column values (e.g.: causing the character data across all rows in the string column to appear in one row or some similar type of row value expanding corruption).

Thanks @jlowe for the clarification.
Still, aren't we supposed to change this condition `output.length <= 100000000)` as String columns are being supported?

I believe I find a problem in the generated code that would potentially corrupt the data.
When the number of bytes remaining in the databuffer is less than the fixed width size of the row, then column meta could be written past the buffer end address.

The "done" condition in `GpuRowToColumnarExec-L818-L820` is set as follows: https://github.com/amahussein/spark-rapids/blob/333a508700859802c8fe22935212f4a091dae38e/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuRowToColumnarExec.scala#L818-L820

```
         |        done = !(currentRow < numRowsEstimate &&
         |            dataOffset < dataLength &&
         |            input.hasNext());
```

With variable sized rows, 

- `currentRow` might be lower than `numRowsEstimate` and
- `dataOffset` can be slightly less than dataLength.
Going through the next iteration, the generated code will be written into the buffer.
The bug is that the generated code checks for the variable data exceeding the buffer limit.

The fix is to change how `done` is being set.

```
         |        done = !(currentRow < numRowsEstimate &&
         |            (dataLength - dataOffset < estimatedRowSize) &&
         |            input.hasNext());
```

**Comment by jlowe** [comment]
> Still, aren't we supposed to change this condition output.length <= 100000000) as String columns are being supported?

I'm not sure why that check is there.  We don't support more than 2^31 bytes per row, but neither does Spark, as indicated by the BufferHolder error in the description of this issue.  Probably worth commenting in the code, but I don't see the need to explicitly check for some max number of columns, especially when the columns are variable sized (like strings, arrays, etc.)

**Comment by jlowe** [comment]
Closing old bug against code that has since been reverted.
