### ISSUE TITLE
[BUG] It's confusing that BASE_SPARK_VERSION in jenkins/databricks/build.sh, but BASE_SPARK_VER in databricks/test.sh

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#6368]
**Describe the bug**
We define BASE_SPAKR_VERSION in jenkins/databricks/build.sh, but use BASE_SPARK_VER in test.sh.
It's confusing the developers to run the build then run the test on Databricks.

**Expected behavior**
Let's use the same variable name.

**Comment by pxLi** [comment]
cc @NvTimLiu to help take a look, thx~
