### ISSUE TITLE
[BUG] Casting string to timestamp results in null

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids#6375]
The bug can be reproduced by the following example:
```
scala> val df = Seq("1997-02-28 10:30:00.012").toDF("v")
df: org.apache.spark.sql.DataFrame = [v: string]

scala> spark.conf.set("spark.rapids.sql.castStringToTimestamp.enabled", "true")

scala> val df2 = df.repartition(1).selectExpr("cast(v as timestamp)")
df2: org.apache.spark.sql.DataFrame = [v: timestamp]

scala> df2.show
22/08/20 02:23:23 WARN GpuOverrides: 
*Exec <CollectLimitExec> will run on GPU
  *Partitioning <SinglePartition$> will run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> cast(cast(v#4 as timestamp) as string) AS v#9 will run on GPU
      *Expression <Cast> cast(cast(v#4 as timestamp) as string) will run on GPU
        *Expression <Cast> cast(v#4 as timestamp) will run on GPU
    *Exec <ShuffleExchangeExec> will run on GPU
      *Partitioning <RoundRobinPartitioning> will run on GPU
      ! <LocalTableScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.LocalTableScanExec
        @Expression <AttributeReference> v#4 could run on GPU

+----+
|   v|
+----+
|null|
+----+

```

**Comment by ttnghia** [comment]
Of course Spark CPU can still output correctly:
```
scala> spark.conf.set("spark.rapids.sql.enabled", "false")

scala> val df = Seq("1997-02-28 10:30:00.012").toDF("v")
df: org.apache.spark.sql.DataFrame = [v: string]

scala> val df2 = df.repartition(1).selectExpr("cast(v as timestamp)")
df2: org.apache.spark.sql.DataFrame = [v: timestamp]

scala> df2.show(false)
+-----------------------+
|v                      |
+-----------------------+
|1997-02-28 10:30:00.012|
+-----------------------+

```

**Comment by ttnghia** [comment]
Found the reason. The cause of this is because the input is parsed only if it has the following formats:
 * `1997-02-28 10:30:00.012345Z`
 * `1997-02-28`
 * `1997-02`
 * `1997`

**Comment by ttnghia** [comment]
There are currently two places that do the same work of casting string to timestamp:
 * GpuCast#castStringToTimestamp
 * datetimeExpressions#GpuToTimestamp

If `cast(str as timestmap)` is called, or `to_timestamp` is called without an optional string format then `GpuCast#castStringToTimestamp` will be executed.

Maybe we can unify them into one place for consistency and easier maintenance.

**Comment by andygrove** [comment]
I think this is expected behavior per the documentation at https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/compatibility.md#string-to-timestamp, which states that `The timestamp portion must have 6 digits for milliseconds. Only timezone 'Z' (UTC) is supported. Casting unsupported formats will result in null values.`.

**Comment by ttnghia** [comment]
Alright, so this is actually not a bug but a "feature": We have limited support for the format of the input string.

This is not a big deal since we can always convert the input string given in other format to timestamp type by explicitly calling the function `to_timestamp(input, fmt)`.
