### ISSUE TITLE
[SPARK-40098][SQL] Format error messages in the Thrift Server

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6381]
#### Context

- Spark 3.4:
  - https://github.com/apache/spark/commit/abb4345073
  - [[SPARK-40180](https://issues.apache.org/jira/browse/SPARK-40180)][SQL] Format error messages by spark-sql https://github.com/apache/spark/commit/7046978949
- Other related error formatting auditing issues: https://github.com/NVIDIA/spark-rapids/issues/6293

#### What changes were proposed in SPARK pull request?

This PR introduces new SQL config `spark.sql.error.messageFormat` to control the format of Spark SQL error messages.
The config can have at least the following string values:
1. PRETTY - textual form of error messages including error class/sub-class, message itself + query context in text form.
2. MINIMAL - JSON representation of `SparkThrowable`. Compact form w/ minimal set of fields. Aims to be parsed machinery.
3. STANDARD - JSON form contains the same set of fields as MINIMAL + message.

#### Why are the changes needed in Spark?

- Spark SQL client tools need to parse out relevant information like parameters and positions in order
  to render messages to their liking. This makes the API fickle, hard to change, and limits degrees of
  freedom for UI.
- Updates to error message texts result in a need to discover and update QA tests being affected.
  This makes it expensive to improve error-messages and prevents e.g. tech writers from taking ownership
  down the road.

#### Does this PR introduce _any_ user-facing change?

Yes

Added new method `getMessage()` to `SparkThrowableHelper` which formats `SparkThrowable` + `Throwable` according to the requested format (see the SQL config). When the format is **MINIMAL** or **STANDARD**, the JSON record includes the following fields:
- `errorClass` - human-readable, unique, and consistent representation of the error category. It is a string.
- `errorSubClass` - optional sub-class of the error class as a string. **It may be missing** in the result string.
- `sqlState` - optional string w/ error identifier across SQL engines. **It may be missing** in the result string.
- `message` - the message template from `error-classes.json`. It is included to JSON when the format is STANDARD.
- `messageParameters` - a map of message parameter names to its values.
- `queryContext` - an array of query contexts of the error message which the following JSON fields. **If it is empty, the array is not outputted**:
    - `objectType` - the string represents the object type of the query which throws the exception. If the exception is directly from the main query, it should be **an empty string**.
    - `objectName` - the string represents the object name of the query which throws the exception. If the exception is directly from the main query, it should be **an empty string**.
    - `startIndex` - the integer represents the starting index in the query text which throws the exception. The index starts from 1. If the index is unknown, **the field is not outputted**.
    - `stopIndex` - the integer represents the stopping index in the query which throws the exception. The index starts from 1. If the index is unknown, **the field is not outputted**.
    - `fragment` - the string represents the corresponding fragment of the query which throws the exception. If the query fragment **cannot be identified, the string is empty.**

For example:

- MINIMAL:
  ```json
   {"errorClass":"DIVIDE_BY_ZERO","sqlState":"22012","messageParameters":{"config":"\"spark.sql.ansi.enabled\""}}
  ```

- STANDARD:
  ```json
    {
      "errorClass" : "DIVIDE_BY_ZERO",
      "message" : "Division by zero. Use `try_divide` to tolerate divisor being 0 and return NULL
                  instead. If necessary set <config> to \"false\" to bypass this error.",
      "sqlState" : "22012",
      "messageParameters" : {
        "config" : "\"spark.sql.ansi.enabled\""
      }
    },
  ```

When `errorClass` is `null`, Spark outputs the error message in the legacy form where:
- `errorClass` is `LEGACY`
- `messageParameters` is an array w/ only one elements as a string. The element contains textual error message.

In the case if the specified format is `PRETTY`, Spark follows existing behavior and outputs error message as plain text, for example:
  ```
  [DIVIDE_BY_ZERO] Division by zero. Use `try_divide` to tolerate divisor being 0 and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.
  == SQL(line 1, position 8) ==
  select 1 / 0
         ^^^^^
  ```

#### Why it might affect RAPIDS?

- the new configuration `spark.sql.error.messageFormat` is set to by default to `ErrorMessageFormat.PRETTY`.
- the error message of Spark depends on this configuration.

#### Impact on Testing?

Yes, comparing Errors may be affected.

#### Requires Doc update?

Yes

**Comment by jlowe** [comment]
Does not affect the plugin code.
