### ISSUE TITLE
[SPARK-40066][SQL] ANSI mode: always return null on invalid access to map column

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6383]
#### Context

- Spark 3.4: https://github.com/apache/spark/commit/95cbd61857
  - Followup: https://github.com/apache/spark/commit/fbc0edac58
- Other related error formatting auditing issues: https://github.com/NVIDIA/spark-rapids/issues/6293

#### What changes were proposed in SPARK pull request?

Change the syntax of map column access under ANSI mode: always return null results instead of
throwing `MAP_KEY_DOES_NOT_EXIST`  errors.
This PR also remove an internal `spark.sql.ansi.strictIndexOperator`.

#### Why are the changes needed in Spark?

PostgreSQL/Snowflake/Biguqery and all of them returns null return on map(json) key not exists.

#### Does this PR introduce _any_ user-facing change?

Yes.

Since Spark 3.4, when ANSI SQL mode(configuration `spark.sql.ansi.enabled`) is on, Spark SQL always
returns NULL result on getting a map value with a non-existing key.
In Spark 3.3 or earlier, there will be an error.

#### Why it might affect RAPIDS?

Yes, change of behavior in Ansi Mode.
- shims for 3.4+ need to be updated.

#### Impact on Testing?

Yes, need to update integration tests to match Spark Behavior

#### Requires Doc update?

No

https://github.com/NVIDIA/spark-rapids/issues/6383#tasklist-block-6d267eea-60b1-478b-bd81-4634ae979ff5

**Comment by nartal1** [comment]
build failure in Spark-3.4 due to this. So this should be fixed.
In the Spark PR, they have changed the constructor of GetMapValue and have removed `mapKeyNotExistError`. So we need to update 3.4+ shim to reflect this change.
```
06:03:09  [[1;31mERROR[m] [Error] /home/jenkins/agent/workspace/spark340_nightly-github/sql-plugin/src/main/330+/scala/org/apache/spark/sql/rapids/shims/RapidsErrorUtils.scala:38: value mapKeyNotExistError is not a member of object org.apache.spark.sql.errors.QueryExecutionErrors
```

**Comment by HaoYang670** [comment]
Hmm, it is always hard to remove a function in the shims. My advice is that we can preserve `mapKeyNotExistError` in our shims for spark340, but change the implementation to always throw `UnsupportedOperationException`

**Comment by HaoYang670** [comment]
I will create a PR to fix the build error

**Comment by HaoYang670** [comment]
This build error is also related to this issue: 
```
[ERROR] [Error] /home/remziy/working/rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:2596: value failOnError is not a member of org.apache.spark.sql.catalyst.expressions.GetMapValue
```

**Comment by HaoYang670** [comment]
I am trying to use conditional compilation to quickly fix the build error related to `failOnError`, such as 
```scala
  override def convertToGpu(map: Expression, key: Expression): GpuExpression =
    // compile this line when spark vesion is between 311 and 33X
    GpuGetMapValue(map, key, in.failOnError)
    // compile this line when spark vesion is between 311 and 33X
    GpuGetMapValue(map, key, false)
}),
```

But seems like that there is no clear way in Scala that I can compile different code pieces based on the value of some constant expression. 

Anyone has some ideas on it?

**Comment by jlowe** [comment]
This needs to be handled with a shim or reflection, with a shim being much preferred since it is checked at compile time.  The shim could be as simple as a method that extracts the result of the failOnError field (and returns false on >= Spark 3.4.0) or the shim could encompass the entire RapidsMeta class for MapValue.

**Comment by nartal1** [comment]
Sorry this shouldn't have been closed. I didn't know linking an issue would close even when there is no keyword(fixes, closes etc) in the description.

**Comment by HaoYang670** [comment]
I will remove the `build` label because the compile errors related to this ticket have been fixed.
