### ISSUE TITLE
[SPARK-40085][SQL] Use INTERNAL_ERROR error class instead of IllegalStateException to indicate bugs

### ISSUE THREAD

**Issue by amahussein** [NVIDIA/spark-rapids#6384]
#### Context

- Spark 3.4
  - https://github.com/apache/spark/commit/fab65f4e39   [[SPARK-40085](https://issues.apache.org/jira/browse/SPARK-40085)][SQL] Use INTERNAL_ERROR error class instead of IllegalStateException to indicate bugs
  - https://github.com/apache/spark/commit/a28880f3b9 [[SPARK-40102](https://issues.apache.org/jira/browse/SPARK-40102)][SQL] Use SparkException instead of IllegalStateException in SparkPlan

- Other related error formatting auditing issues: https://github.com/NVIDIA/spark-rapids/issues/6293

#### What changes were proposed in SPARK pull request?

Aims to use `SparkException` instead of `IllegalStateException` in `SparkPlan`

#### Why are the changes needed in Spark?

`IllegalStateException` was used in Spark to indicate Bugs. However, there is no standard java doc
indicating that `IllegalStateException` means bugs.
So, it would be better to report those exceptions as "INTERNAL_ERROR"

#### Does this PR introduce _any_ user-facing change?

Yes.

SparkPlan would throw SparkException with internal error instead of `IllegalStateException`.

#### Why it might affect RAPIDS?

Yes, change of exception class.

#### Impact on Testing?

Yes, Some unit tests will fail as it intercepts IllegalStateException 

#### Requires Doc update?

No

**Comment by sameerz** [comment]
It is likely that we will not see an INTERNAL_ERROR since it is a Spark internal assert, rather than something plugin specific.
