### ISSUE TITLE
[FEA] Remove the `hasNans` config from `GpuCollectSet`

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#6395]
**Is your feature request related to a problem? Please describe.**
This is a subtask of #5320 
`GpuCollectSet` has been improved to properly handle `Nan`s, (https://github.com/NVIDIA/spark-rapids/issues/5320#issuecomment-1222343510) so that we can remove the `hasNans` configuration from it.

**Describe the solution you'd like**
Remove the `hasNans` configuration from `GpuCollectSet` and update tests.

**Describe alternatives you've considered**
We could not do this.

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by HaoYang670** [comment]
Hi, @revans2, the `collect_set` expression currently cannot fully support float or double becuase of 2 reasons:
1. the `nan` handling, which will be fixed in this ticket
2. `-0.0 == 0.0` in cuDF, which has not been fixed yet I guess.

But there is not PSnote on the `collect_set` expression to say that we don't support `-0.0 != 0.0`: https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala#L3412-L3418, which means the users may get wrong answer.

My questions are:
1. Is there any way we could match the Spark's behavior now? 
2. If we can't, can we add a psnote to `collect_set`, so that the expression will fallback to CPU when having `-0.0`?

**Comment by HaoYang670** [comment]
Oh, I find the instruction in the compatibility: https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/compatibility.md#00-vs--00

**Comment by revans2** [comment]
At a minimum it would be good to update the docs to explicitly say that it does not support -0.0 the same as Spark. A psNote would be fine for that. It might also be good to file an issue against Spark if one does not exist already.

**Comment by HaoYang670** [comment]
Blocked by https://github.com/NVIDIA/spark-rapids/issues/6438
