### ISSUE TITLE
ClassNotFoundException: com.nvidia.spark.rapids.RapidsDriverPlugin

### ISSUE THREAD

**Issue by votruongduy** [NVIDIA/spark-rapids#6402]
**Describe the bug**
Error log:
```
 ERROR SparkContext: Error initializing SparkContext.
java.lang.ClassNotFoundException: com.nvidia.spark.rapids.RapidsDriverPlugin
```

**Steps/Code to reproduce bug**
When submit a task, I got the above issue, I am sure "rapids-4-spark_2.12-22.06.0.jar" is in classpath of spark, also verify download and it is good. I have checked classpath of spark UI (by removing spark.plugins=com.nvidia.spark.SQLPlugin config so it will as cpu mode), run it and it is there:

`/usr/local/lib/python3.8/dist-packages/pyspark/jars/rapids-4-spark_2.12-22.06.0.jar | System Classpath`

**Expected behavior**
Should run without error

**Environment details (please complete the following information)**
 - Pyspark version 3.3.0 (rapids-4-spark_2.12-22.06.0.jar) in k8s
 - Spark configuration settings related to the issue:
    --conf spark.executor.resource.gpu.vendor=nvidia.com \
    --conf spark.plugins=com.nvidia.spark.SQLPlugin \
    --conf spark.rapids.sql.enabled=true \

**Additional context**
It works with an older version of the library on an older version of pyspark

**Comment by votruongduy** [comment]
Same error if I set the jar like this:
--conf spark.driver.extraClassPath=$RAPIDS_JAR \
--conf spark.executor.extraClassPath=$RAPIDS_JAR \
--conf spark.jars=$RAPIDS_JAR \

I am sure the path is correct, as I tried with a wrong path and spark report FileNotFoundException.
With the correct path, it will show: Spark classLoader jdk.internal.loader.ClassLoaders$AppClassLoader@5bc2b487 updated successfully

**Comment by gerashegalov** [comment]
It looks like you may be using JDK11. Is it the case, can you try setting JAVA_HOME to a JDK8 install. 

If you require JDK9+ try to add  spark.rapids.force.caller.classloader=false to the submit conf. Don't mix spark.jars (--jars) and spark*extraClassPath. Chose either one for deterministic classloading. 

If this did not help try building the Plugin jar according to  https://github.com/NVIDIA/spark-rapids/blob/branch-22.06/CONTRIBUTING.md#building-and-testing-with-jdk9. If you have to go this route and don't mind trying bleeding edge SNAPSHOT I suggest using a current HEAD of branch-22.10 to build your own jar. Because we made improvements in this area that will be released with 22.10.  See #5646

**Comment by votruongduy** [comment]
@gerashegalov thanks for your answer, I used jdk 11 before with spark < 3.3.0, it just works perfectly.
Now I am using jdk 17 with spark 3.3.0
Any issue with jdk17?

**Comment by tgravescs** [comment]
we only support jdk8 at the moment.

**Comment by sameerz** [comment]
Hi @votruongduy was the issue resolved, or are there more questions we can help with?

**Comment by votruongduy** [comment]
> Hi @votruongduy was the issue resolved, or are there more questions we can help with?

I can make it work with jdk 8. I tried to build from source with jdk 11 but not success. Let me close this issue

**Comment by gerashegalov** [comment]
> I can make it work with jdk 8. I tried to build from source with jdk 11 but not success. Let me close this issue

Hi @votruongduy, I [documented steps for JDK9+][1] and specifically tested it with JDK11. Please file an issue if it no longer works or merely needs more details. 

[1]: https://github.com/NVIDIA/spark-rapids/blob/branch-22.06/CONTRIBUTING.md#building-and-testing-with-jdk9

**Comment by votruongduy** [comment]
@gerashegalov I tried with jdk 17 and it does not work, but ok with jdk 11.

**Comment by GaryShen2008** [comment]
To build with JDK 17, you may refer to the instructions in https://github.com/NVIDIA/spark-rapids/issues/6752
