### ISSUE TITLE
Refactor spark-tests script to follow PYSP_TEST configs pattern

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#6403]
Iceberg pytests are not scaled out using xdist because they have to use SPARK_SUBMIT_FLAGS as a workaround for #6351. With this being resolved we can rewrite the config as PYSP_TEST env and run Iceberg with TEST_PARALLEL >= 2

**Comment by gerashegalov** [comment]
Same applies to UCX shuffle tests

**Comment by pxLi** [comment]
To understand the requirement, 
1. we do not have iceberg_test in https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/jenkins/spark-premerge-build.sh
2. for nightly https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/jenkins/spark-tests.sh#L129 we disable xdist parallel, and instead we submit each test independently to spark cluster to cover normal app submit scenarios in nightly and avoid xdist usage
3. we have iceberg_test in databricks https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/jenkins/databricks/test.sh which could try enable TEST_PARALLEL>=2

Do you need us to update 3. only? Also I am not sure what does the `proper` mean here

**Comment by gerashegalov** [comment]
re: https://github.com/NVIDIA/spark-rapids/issues/6403#issuecomment-1237568091

Re 2. My assumption is/was that the only reason we have the tests not running via xdist is that it was impossible with tests requiring external sources such as Delta, Iceberg, etc  using the recommended / document deployment option via `--packages` and because conf containing `_` was not supported which we recently fixed #6358. 

Given the scarcity of CI resources I think it's in our best interest to run most of the tests using xdist and to leave a few single tests as smoke tests for the vanilla spark-submit call path.

1. is a too narrow of an interpretation for the issue. I generally meant all tests using TEST_PARALLEL=0 only due to prior limitations. Iceberg was singled out only because that's what I stumbled upon at first. We can generalize the scope to: update all tests using TEST_PARALLEL=0 and SPARK_SUBMIT_ARGS if it's not required to run them without xdist. 

Also note even if we have to leave some tests TEST_PARALLEL=0, the configs should be written uniformly for both  TEST_PARALLEL=0 and  xdist such that switching to parallel is a trivial matter of updating the TEST_PARALLEL value. We can achieve this either by:
- standardizing on PYSP_TEST as an interface
- supporting SPARK_SUBMIT_ARGS in both cases and translating SPARK_SUBMIT_ARGS to PYSP_TEST

I think the former is simpler.

> Can we close this one?

Once we converge to some common understanding of the issue we can close and potentially create more narrow actionable issues and close this or use it as an epic for the subtasks identified.

**Comment by pxLi** [comment]
> My assumption is/was that the only reason we have the tests not running via xdist is that it was impossible with tests requiring external sources such as Delta, Iceberg, etc using the recommended / document deployment option via --packages and because conf containing _ was not supported which we recently fixed https://github.com/NVIDIA/spark-rapids/pull/6358.

The nightly tests were submitted w/o xdist even before I joined the project as there were no tests requiring external resource like delta_lake or iceberg at that moment , e.g. for branch-0.2 https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/jenkins/spark-tests.sh. To speed up the nightly IT tests, I added `gnu-parallel` to support parallel submiting w/o breaking the original submit methods. (its actually take less time than xdist pytest run)

I am not seeing too much benefit to do the refactor for the script and all corresponding jenkinsfiles, 
but I am fine to switch it to xdist if most of developers agree on xdist should be used in nightly whatever it takes

**Comment by gerashegalov** [comment]
If I take the command from https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/jenkins/spark-tests.sh#L201-L209 it roughly translates to 

```
SPARK_HOME=~/dist/spark-3.2.2-bin-hadoop3.2 \
PYSP_TEST_spark_jars_packages="org.apache.iceberg:iceberg-spark-runtime-3.2_2.12:0.13.2" \ 
PYSP_TEST_spark_sql_extensions="org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions" \
PYSP_TEST_spark_sql_catalog_spark__catalog="org.apache.iceberg.spark.SparkSessionCatalog" \
PYSP_TEST_spark_sql_catalog_spark__catalog_type="hadoop" \
PYSP_TEST_spark_sql_catalog_spark__catalog_warehouse="$(mktemp -p /tmp -d spark-warehouse-XXXXXX)" \
./integration_tests/run_pyspark_from_build.sh --iceberg -m iceberg
 ```

On my box I get the following runtimes with 4 JVMs using various ways to achieve:

| TEST_PARALLEL | NUM_LOCAL_EXECS  | run time (sec) |
| - | --  | ---   |
| 0 (no xdist) |  4 | 447.88s |
| 2 |  2 | 360.07  |
| 4 |  0 | 203.57s |

**Comment by pxLi** [comment]
I have done the same benchmark locally w/ parallel command to split iceberg tests into cases. 
The result looks similar to yours

I see your point to have a consistent way for integration tests, let me rename this ticket first. 
I would like not to bind this one to specific release mark it as a good-to-have for now, I will get back to this later

**Comment by pxLi** [comment]
BTW I was trying run iceberg_test w/ PYSP_TEST_spark_jars_packages by using your command above,
but it returns me
```
WARN SparkSession: Cannot use org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions to configure session extensions.
java.lang.ClassNotFoundException: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:216)
	at org.apache.spark.sql.SparkSession$.$anonfun$applyExtensions$1(SparkSession.scala:1194)
	at org.apache.spark.sql.SparkSession$.$anonfun$applyExtensions$1$adapted(SparkSession.scala:1192)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
```

and for test case, it then fail and throw error
```
org.apache.spark.SparkException: Cannot find catalog plugin class for catalog 'spark_catalog': org.apache.iceberg.spark.SparkSessionCatalog
at org.apache.spark.sql.errors.QueryExecutionErrors$.catalogPluginClassNotFoundForCatalogError(QueryExecutionErrors.scala:1454)
at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:64)
at org.apache.spark.sql.connector.catalog.CatalogManager.loadV2SessionCatalog(CatalogManager.scala:66)
at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$2(CatalogManager.scala:85)
at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
```

I was on the latest commit of branch-22.10, @gerashegalov did I miss anything? thanks
