### ISSUE TITLE
[FEA] Fix decimal average to match Spark

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#6424]
**Is your feature request related to a problem? Please describe.**
Spark changed how they do a decimal divide in 3.4.0 to be closer to how we do a divide. It removes a lot of the ugliness that required it to have the lhs and rhs be the exact same type, including precision and scale.  Well as a part of doing an average Spark would first do a divide and then cast the result to the final output type, which is different from what divide thinks the output type should be.  Because of this there are often cases in average where the output value was rounded as a part of the divide and then cast to a larger scale, which resulted in the last digits being all zeros.  There is also theoretically the possibility where the opposite is true and the scale is reduced, but the rounding from the first divide changed a significant enough digit that the rounding from the cast resulted in a different final value.

This was all fixed in 3.4.0 so we need to undo the "fix" that I put in as a part of https://github.com/NVIDIA/spark-rapids/pull/6414.  It should be shimmed so on older versions of Spark we still do the same broken thing.

**Comment by razajafri** [comment]
This was fixed in #7362 as part of the effort to fix DB 11.3 test failures. I verified this and it seems to be matching the results from Spark3.4
