### ISSUE TITLE
[BUG] `GpuSortArray` doesn't match the behavior of Spark when handling `Nan`s

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#6438]
**Describe the bug**
When apply the `GpuSortArray` on an array containing `nan`s, the `nan` values aren't always sorted to the end of the array.

**Steps/Code to reproduce bug**
```
>>> import struct
>>> bytes1 = struct.pack('L', 0x7ff83cec2c05b870)
>>> bytes2 = struct.pack('L', 0xfff5101d3f1cd31b)
>>> bytes3 = struct.pack('L', 0x7c22453f18c407a8)
>>> nan1 = struct.unpack('d', bytes1)[0]
>>> nan2 = struct.unpack('d', bytes2)[0]
>>> other = struct.unpack('d', bytes3)[0]
>>> (nan1, nan2, other)
(nan, nan, 8.902585073221772e+289)

>>> data = [([nan2] + [other for _ in range(256)] + [nan1],)]
>>> df = sc.parallelize(data).toDF()

>>> spark.conf.set('spark.rapids.sql.enabled', 'false')
>>> df.selectExpr('sort_array(_1)').collect()
[Row(sort_array(_1, true)=[8.902585073221772e+289,  ..., 8.902585073221772e+289, 8.902585073221772e+289, 8.902585073221772e+289, nan, nan])]

>>> spark.conf.set('spark.rapids.sql.enabled', 'true')
>>> df.selectExpr('sort_array(_1)').collect()
22/08/29 12:26:35 WARN GpuOverrides: 
*Exec <ProjectExec> will run on GPU
  *Expression <Alias> sort_array(_1#18, true) AS sort_array(_1, true)#22 will run on GPU
    *Expression <SortArray> sort_array(_1#18, true) will run on GPU
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> _1#18 could run on GPU

[Row(sort_array(_1, true)=[nan, 8.902585073221772e+289, ..., 8.902585073221772e+289, 8.902585073221772e+289, nan])]
```
When enabling the GPU, one `nan` is sorted to the head, the other is sorted to the end.
I am not sure whether this is related to the different bit representations of `nan`. Or maybe this is a bug in cuDF.

**Expected behavior**
The `GpuSortArray` should always treat `nan`s as the max values. 

**Environment details (please complete the following information)**
 - Environment location: local
 - Spark configuration settings related to the issue
PySpark 3.3.0
spark-rapids 22.10

**Additional context**

**Comment by HaoYang670** [comment]
@ttnghia Could you please help to check whether the bug is related to cuDF?

**Comment by ttnghia** [comment]
The issue is due to having negative NaN in the input.

In cudf, there are several code paths that can sort lists (arrays) depending on which the negative Nan can be put at the beginning or the end of the arrray.

To get a consistent output, you have to call `normalize_nans_and_zeros` on the input before sorting.
