### ISSUE TITLE
[FEA] Consistent JNI builds

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#6445]
**Is your feature request related to a problem? Please describe.**
Recently we had a failure with rapids-cmake changed and broke our build. rapids-cmake is designed to always be updated, so if there are changes to it that require a specific version of CUDF then our builds will break and we have no good way to go back the the exact version of rapids-cmake that was used to build them.

I filed https://github.com/rapidsai/cudf/issues/11533 against CUDF for this and was pointed to the following documentation

https://github.com/rapidsai/rapids-cmake#overriding-rapidscmake

To be able to do this it looks like we are going to have to apply a patch to CUDF. That is far from ideal but we probably should do it so we can actually have reproducible builds. We should update the SHA on rapids-cmake similar to how we do it for cudf itself.

**Comment by jlowe** [comment]
This change needs to occur in spark-rapids-jni and is being handled by NVIDIA/spark-rapids-jni#1666
