### ISSUE TITLE
Alluxio reliability doc and scripts

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#6459]
**Is your feature request related to a problem? Please describe.**
With alluxio we should understand and document all the failures cases and also perhaps think about writing scripts or having documentation on how to restart the daemons on failures.   Is there a way to have it fall back and just go to the UFS (ie s3)?

More specifically:

1. what happens to spark job if the master fails?  
    * Do all of the tasks start failing and then job eventually fail or does it some how recover?
    * Is there any failure recovery for master - restart?  I think Alluxio has an HA mode but not sure we would want to use it because probably requires another node?
    * Can we have a service watching master and if fails restart it?
    * Document how a team running Alluxio would look at logs and find what wrongs and deal with a master failure? 
    * what are the timeouts and retry policies on connecting to the master?
2. What happens to the spark job when a worker fails? 
   * Do the tasks fail or do they fallback to talking to s3?
   * Is there any alluxio configurations to tell it to just go to s3 if worker is down?
   * Can we have a service watching the worker and if fails restart it?
   * Document how a team running Alluxio would look at logs and find what wrongs and deal with a worker failure? 
   * What are the timeouts and retry policy on connecting to the worker? 
3. how do we monitor alluxio performance?
   * What metrics are most important to see how Alluxio is doing?  things like cache capacity, cache hit ratio, GC stats....
4. What happens if we fail to auto mount s3 bucket?

**Comment by res-life** [comment]
Client cache is closed by default, see property `alluxio.user.client.cache.enabled`.
The client cache is stored in `/tmp/alluxio_cache` by default.
Because we already save cache in the path that `alluxio.worker.tieredstore.level0.dirs.path` defined, no need to save client cache to duplicate.
It's reasonable to keep client cache closed, and thus `alluxio.user.client.cache.timeout.duration` is useless.
If the client is not co-located with alluxio worker, client cache is useful.

**Comment by res-life** [comment]
> 3. how do we monitor alluxio performance?

@tgravescs let's handle this item in https://github.com/NVIDIA/spark-rapids/issues/6463
Please help review.
