### ISSUE TITLE
Figure out the best way to graph Alluxio metrics

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#6463]
**Is your feature request related to a problem? Please describe.**
Alluxio has a bunch of metrics and we should figure out which ones are critical to user and document and figure out the best way for them to view them.  

- normally alluxio has UI, this is not availalble by default on databricks, can we ssh tunnel or get it somehow?
- can look at metrics via command line: alluxio fsadmin report metrics
- should we save certain ones to csv in log files and then have a way to graph them?  We want to be careful about saving all to disk if it adds a lot of load to the disks.

Note:  `Find the critical metrics` part is moved to https://github.com/NVIDIA/spark-rapids/issues/7241

**Comment by GaryShen2008** [comment]
Are we going to save the alluxio metrics in Databricks usage? Would it be something configurable in our customized Docker image?

**Comment by res-life** [comment]
>normally alluxio has UI, this is not availalble by default on databricks, can we ssh tunnel or get it somehow?

We can use ssh tunnel to access the UI.

Assume we can login to alluxio master via an egx host:
For example:
```
ssh egx_user@egx_host
ssh ubuntu@ec2-34-211-208-96.us-west-2.compute.amazonaws.com -p 2200 -i <private_key_file_path>
```
Create a tunnel from localhost 39999 port to an egx host 29999 port,
then create a tunnel from egx host 29999 port to alluxio master port 19999.

Port forwarding path is:
localhost:39999 -> egx-host:29999 -> alluxio-master:19999

### Details:

#### Let assume:
egx_host=10.136.6.6
egx_user=chonggao
alluxio_master_host=ec2-34-211-208-96.us-west-2.compute.amazonaws.com
alluxio_master_user=ubuntu


#### step 1:
```
# forward the egx port 29999 to local 39999
# On your own machine
ssh -L 39999:localhost:29999 egx_user@egx_host
# check is listening to 39999 port on your own machine
netstat -anp | grep 39999 | grep LIS
(base) chongg@chongg-pc:~$ netstat -anp | grep 39999 | grep LIS
tcp        0      0 127.0.0.1:39999         0.0.0.0:*               LISTEN      24352/ssh           
```

#### step 2:
```
# forward the alluxio server 1999 port to the egx local port 29999
ssh egx_user@egx_host
# enter password of egx_user
ssh -L 29999:localhost:19999 alluxio_master_user@alluxio_master_host -p 2200 -i <private_key_file_path>
# check is listening to 29999 port on egx host
ssh egx_user@egx_host
chonggao@spark-egx-02:~$ netstat -an | grep 29999 | grep LIS
tcp        0      0 127.0.0.1:29999         0.0.0.0:*               LISTEN    
``` 

#### step 3:
```
# aceess the 39999 port on web browser
# On your own mathine
http://localhost:39999
```

![image](https://user-images.githubusercontent.com/8166419/200221574-f29ce572-817d-4e8e-a274-3efe821c7c7b.png)

**Comment by res-life** [comment]
> but we also need to handle case we can't ssh tunnel into the master node

Seems we can only save the metrics and then find a way to graph them.
It's the case you required in the following?

> should we save certain ones to csv in log files and then have a way to graph them?

**Comment by res-life** [comment]
> Are we going to save the alluxio metrics in Databricks usage? Would it be something configurable in our customized Docker image?

The latest version we do not.
The latest version has a  config to sync logs to dbfs file system.

Because the metric files are in the log path, if we enable metric files, then metric files can be synced together with log files.

Refer to the docker readme.md:
![image](https://user-images.githubusercontent.com/8166419/201020472-ce68c7ed-d9fd-4779-ad48-21d94d2877cb.png)

**Comment by tgravescs** [comment]
right so can we figure out which metrics are useful.  saving all the metrics adds disk load and if we have slow disks it makes it worse to save all the metrics.  It goes along with figure out which ones are useful and user should pay most attention to.

**Comment by res-life** [comment]
Close this issue as the following PRs were merged:

https://github.com/NVIDIA/spark-rapids/pull/7172
https://github.com/NVIDIA/spark-rapids-container/pull/24

Note: `Find the critical metrics` part is moved to https://github.com/NVIDIA/spark-rapids/issues/7241
