### ISSUE TITLE
[QST] OBS Data Source Support

### ISSUE THREAD

**Issue by lw-cxn** [NVIDIA/spark-rapids#6474]
Does the OBS Data Source Support?

**Comment by tgravescs** [comment]
Also note would love to hear the results if you try it out.  If you have any issues let us know or if it he multi-threaded works well we could update it to be in the spark.rapids.cloudSchemes by default.

**Comment by lw-cxn** [comment]
Okay, I'll try it.

**Comment by sameerz** [comment]
Feel free to contact us at spark-rapids-support@nvidia.com as well, we'd be happy to set up a discussion if needed.

**Comment by lw-cxn** [comment]
I have tried to use OBS as the data source and can be accessed normally. We will try to use OBS in the production environment in the future.

**Comment by sameerz** [comment]
> I have tried to use OBS as the data source and can be accessed normally. We will try to use OBS in the production environment in the future.

Good to know.  I am going to close this issue.  Do not hesitate to file other questions or issues as needed.
