### ISSUE TITLE
[FEA] should all the OPs after TakeOrderedAndProject be executed on CPU

### ISSUE THREAD

**Issue by JustPlay** [NVIDIA/spark-rapids#649]
**Is your feature request related to a problem? Please describe.**
`TakeOrderedAndProject` can not run on GPU (rapids-0.2), and this OP normally located near to the end of the DAG
The remaining data need to be procesed is very small, let those data be processed on CPU shoud be better (I think).

![image](https://user-images.githubusercontent.com/5866501/92091770-c96e8f00-ee03-11ea-9ed3-821c2dd86d2e.png)

**Comment by abellina** [comment]
Thanks @JustPlay that's absolutely right. We do have an issue to track this one, so I'll dupe this one on that other issue. 

https://github.com/NVIDIA/spark-rapids/issues/103

That said, we'll take the report into account though. It is a pretty trivial task so it should just happen.
