### ISSUE TITLE
[FEA] run_pyspark_from_build should use a clean run directory when running tests

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#6495]
**Is your feature request related to a problem? Please describe.**
I sometimes run the integration tests across multiple Spark versions.  If I run the tests against something like Spark 3.3.0 and then try to run tests against Spark 3.1.x, it will often fail complaining about the metastore version being incompatible.  This occurs because remnants from the first run are leaking into the second run via artifacts in the integration tests run directory.

**Describe the solution you'd like**
run_pyspark_from_build should remove the contents of the run directory before it runs.

**Describe alternatives you've considered**
Instead of cleaning, use a separate run directory for each run, although this will accumulate run directories which are unlikely to be needed.

**Comment by tgravescs** [comment]
it appears just cleaning it caused issues with our integration tests.  Perhaps we should create unique directory instead.

**Comment by gerashegalov** [comment]
> it appears just cleaning it caused issues with our integration tests. Perhaps we should create unique directory instead.

+1 for unique run dirs, in addition we can add logic to delete old directories (older than a configurable expiration period).
