### ISSUE TITLE
[BUG]cgroup directory permission get reverted on reboot

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#6501]
**Describe the bug**
If we run spark-rapids on yarn cluster, after one node rebooted, the /sys/fs/cgroup/directory permission get reverted because it is mounted on tmpfs, nodemanager failed to start on that node because of permission issue, 
```
2022-09-05 09:16:21,098 ERROR org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor: Failed to bootstrap configured resource subsystems!
org.apache.hadoop.yarn.server.nodemanager.containermanager.linux.resources.ResourceHandlerException: Unexpected: Cannot create yarn cgroup Subsystem:devices Mount points:/proc/mounts User:hdoop Path:/sys/fs/cgroup/devices/hdoop
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.linux.resources.CGroupsHandlerImpl.initializePreMountedCGroupController(CGroupsHandlerImpl.java:418)
``` 
we need to update the cgroup permission manually again.
```
chmod a+rwx -R /sys/fs/cgroup/cpu,cpuacct
chmod a+rwx -R /sys/fs/cgroup/devices
```

**Comment by abellina** [comment]
It looks like this issue is around adding documentation in this repo to help users with issues like the one documented here after reboot: @nvliyuan, is that right?  (e.g. updating this https://nvidia.github.io/spark-rapids/docs/get-started/yarn-gpu.html)

**Comment by nvliyuan** [comment]
yes, shall I draft a pr to update this [[page](url)](https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/get-started/yarn-gpu.md)?

**Comment by abellina** [comment]
> yes, shall I draft a pr to update this https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/get-started/yarn-gpu.md?

Sure. I suppose it is going to be fairly small, along the lines of "These directories are not persistent during reboot". Perhaps there's a persistent way to create cgroups? I am not 100% sure.

**Comment by tgravescs** [comment]
The idea of this instructions are basic setup and compatibility, a user needs to setup their environment to suite their needs, we should not document everything about other components.  If we want to add some basic sentence about seeing other instructions or something I"m fine with this, otherwise I think we should just close this.
