### ISSUE TITLE
[BUG] RapidsShuffleThreadedWriterSuite failed to delete itermitent failure

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#6515]
We saw a failure in CI in `RapidsShuffleThreadedWriterSuite` that looks to be intermittent. It happens on the `afterEach` of this suite which is try to clean up a temp dir, which from the looks of it, is not there anymore. I am not entirely sure why:

```
04:56:15  SUITE ABORTED - RapidsShuffleThreadedWriterSuite: Failed to delete: /home/jenkins/agent/workspace/jenkins-rapids_nightly-dev-github-622/tests/target/spark321/tmp/spark-e3c91a34-729d-482b-bee6-4f2bafb4d276/.nfs00000000e342c5f10008516f
04:56:15    java.io.IOException: Failed to delete: /home/jenkins/agent/workspace/jenkins-rapids_nightly-dev-github-622/tests/target/spark321/tmp/spark-e3c91a34-729d-482b-bee6-4f2bafb4d276/.nfs00000000e342c5f10008516f
04:56:15    at org.apache.spark.network.util.JavaUtils.deleteRecursivelyUsingJavaIO(JavaUtils.java:144)
04:56:15    at org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:118)
04:56:15    at org.apache.spark.network.util.JavaUtils.deleteRecursivelyUsingJavaIO(JavaUtils.java:128)
04:56:15    at org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:118)
04:56:15    at org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:91)
04:56:15    at org.apache.spark.util.Utils$.deleteRecursively(Utils.scala:1164)
04:56:15    at org.apache.spark.sql.rapids.RapidsShuffleThreadedWriterSuite.afterEach(RapidsShuffleThreadedWriterSuite.scala:233)
04:56:15    at org.scalatest.BeforeAndAfterEach.$anonfun$runTest$1(BeforeAndAfterEach.scala:234)
04:56:15    at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:379)
04:56:15    at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:375)
04:56:15    ...
```

**Comment by pxLi** [comment]
this could be related to ephemeral NFS issue. 

As in most of CI we will mount the workspace to the PVC storage so it may fail some test run if test would read from or write to PVC location and there is some ephemeral network or nfsd issue.

One thing that we can take a try is not make the test IO relying on PVC path, but to the docker local-mount path like to retarget the tmp path to `/tmp/<date>/XXX`

**Comment by abellina** [comment]
@pxLi, I am trying first to ignore this delete failure on cleanup https://github.com/NVIDIA/spark-rapids/pull/6640. If we still have issues we should look into the temp path change you mentioned, though that seems like a slightly bigger change + there could be some risks with filing up `/tmp`?

**Comment by pxLi** [comment]
> 

yeah, I think its fine to ignore for now. 
This kind of failures were mostly ephemeral. 

To mitigate, we could leverage tmp folder later. 
For IT, I think it should be well for disk size as the non-PVC host ephemeral volume mount of our CI is about 50 Gi
