### ISSUE TITLE
Alluxio - investigate if way to determine if data reading is cached 

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#6517]
**Is your feature request related to a problem? Please describe.**
Ideally when we are running with alluxio, we would use the multithreaded reader when the data is in s3 and the coalescing reader when its cached in alluxio.  I didn't see any easy api to determine this but we should investigate it further.

**Comment by res-life** [comment]
I tested small files scenario, s3 path is: `s3://nds20/nds2-sf2-parquet/store_sales`.
Cold reading from Alluxio(without cache) spent 4.5 seconds, 
while reading from s3 with multiple threads spent 3.24 seconds.
It's true we can get better performance when no caches in alluxio and reading from S3.
But the query of alluxio cache percentage spent about 400ms(I optimized to 300ms in [this alluxio PR](https://github.com/Alluxio/alluxio/pull/16404) ).
Since only the first query needs to optimize (the following queries will trigger hot read from alluxio).
I think it is not worth to add this optimization, since each query will spend extra 300ms.

**Comment by res-life** [comment]
@tgravescs  help to double-check.

**Comment by tgravescs** [comment]
Did you try large files?    That is where I saw streaming with the multi-threaded read be faster then reading alluxio and this was likely due to disk speed on alluxio cluster.

 I do expect some overhead in checking if data is cached and that is what we want to know what that costs (was thinking without alluxio changes).  Maybe we don't check all files but only a certain percentage and use some heuristics for instance.  or I wonder if we only check cache status for files over a certain size, do we know the number of files and size of each when we would need to change the reader?  I thought we did. ie300ms seems pretty small compared to some of the file reads I've seen which takes 30+ seconds to buffer.  
The main point I think is that you will always have the overhead even on hot reads but I think it depends on how many of your reads are hot.

I'm also surprised you are saying it only went from 400 to 300 ms by doing it on the server side. I would have expected us to be much worse then doing it on the server side.  On our side we just do a single query of everything then and so the only difference here is really in transferring the list status results vs just a percentage?

**Comment by res-life** [comment]
>I'm also surprised you are saying it only went from 400 to 300 ms by doing it on the server side. I would have expected us to be much worse then doing it on the server side. On our side we just do a single query of everything then and so the only difference here is really in transferring the list status results vs just a percentage?

Yes, for the [PR](https://github.com/Alluxio/alluxio/pull/16404),  the only difference is really whether the transferring the status list or not.
I expect the quering percentage is very fast, like 10ms, but it needs 300ms, it's because Alluxio acquires read-locks for all the inodes in a directory.

**Comment by tgravescs** [comment]
Based on this I think we can close this for now and concentrate on #6540

**Comment by res-life** [comment]
The following is the code for checking if data is cached.
Only 1 call to query the cache percentage, seems it's hard to do heuristic check.
``` java
import alluxio.AlluxioURI;
import alluxio.client.file.FileSystem;
import alluxio.client.file.URIStatus;
import alluxio.conf.InstancedConfiguration;
import alluxio.conf.PropertyKey;
import alluxio.conf.Source;
import alluxio.grpc.FileSystemMasterCommonPOptions;
import alluxio.grpc.ListStatusPOptions;
import alluxio.grpc.LoadMetadataPType;

import java.util.List;
import java.util.stream.Collectors;

public final class GetPercentage2 {
  public static void main(String[] args) throws Exception {
    String host = "127.0.0.1";
    int port = 19998;
    String path = "/liangcail/chongg-test";

    // create file system
    InstancedConfiguration conf = InstancedConfiguration.defaults();
    conf.set(PropertyKey.MASTER_HOSTNAME, host, Source.RUNTIME);
    conf.set(PropertyKey.MASTER_RPC_PORT, port, Source.RUNTIME);
    FileSystem fs = FileSystem.Factory.create(conf);

    // get status list including directories and files
    // Note: only need 1 call to get all the file status for a directory
    ListStatusPOptions options = ListStatusPOptions.newBuilder()
        // recursively
        .setRecursive(true)
        // never load meta from S3 to speedup the query
        .setLoadMetadataType(LoadMetadataPType.NEVER)
        // -1 means never sync from s3 to speedup the query
        .setCommonOptions(FileSystemMasterCommonPOptions.newBuilder().setSyncIntervalMs(-1))
        .build();
    List<URIStatus> files = fs.listStatus(new AlluxioURI(path), options);

    // calculate the information
    long totalLen = calLen(files);
    long totalPercentage = calculateCachePercentage(files);
    List<URIStatus> list = files.stream().filter(e -> !e.isFolder()).collect(Collectors.toList());
    System.out.println("Total file size is " + totalLen);
    System.out.println("Total files num is " + list.size());
    System.out.println("Total cached percentage is " + totalPercentage);

    // close file system
    fs.close();
  }

  private static long calLen(List<URIStatus> files) {
    long sumLen = 0L;

    for (URIStatus e : files) {
      if (!e.isFolder()) { // only stat files
        sumLen += e.getLength();
      }
    }

    return sumLen;
  }

  public static long calculateCachePercentage(List<URIStatus> files) {
    long sumLen = 0L;
    long cachedLen = 0L;

    for (URIStatus e : files) {
      if (!e.isFolder()) { // only stat files
        sumLen += e.getLength();
        cachedLen += e.getLength() * e.getInAlluxioPercentage() / 100L;
      }
    }

    // if sumLen == 0, the cache percentage is 100%
    return sumLen == 0 ? 100 : (cachedLen * 100L / sumLen);
  }
}
```

After moving the `calculateCachePercentage` to the Alluxio server side to avoid transferring the list, it still needs 300ms (formal 400ms)
