### ISSUE TITLE
[QST] How can I call replaceMultiRegex on ColumnVector in RapidsUDF, I cannot find any example. Please help!

### ISSUE THREAD

**Issue by mtsol** [NVIDIA/spark-rapids#6535]

**Comment by revans2** [comment]
Generally you would follow the examples on how to create your own UDF.

https://github.com/NVIDIA/spark-rapids-examples/tree/branch-22.10/examples/UDF-Examples/RAPIDS-accelerated-UDFs

I am not sure what regular expression you want to use, but I will assume that they are hardcoded. Then it would be just like the example for the URL-encode/decode but instead you would call `replaceMultiRegex`.

**Comment by mtsol** [comment]
@revans2 , thank you so much, I was actually looking forward to know which format of input replaceMultiRegex receives, Its 2nd argument is a ColumnView, and what values should I put in that ColumnView if I have an array of regex ["[^i*&2@]", "[2-9]|[12]\d|3[0-6]"] and I want to replace all the regex with empty string.

**Comment by jlowe** [comment]
The second argument to replaceMultiRegex should be a column of what the replacement values are corresponding to the input pattern array.  For example, the pattern at index N of the `patterns` array parameter has a replacement string that is row `N` of the `repls` column view parameter.  For your example, you would pass a column of two empty strings, e.g.: `ColumnVector.fromStrings("", "")` to have empty string as replacements for each of your two search patterns.  Make sure the replacement string input column is closed after the operation completes to avoid leaking native resources.

There's a unit test at https://github.com/rapidsai/cudf/blob/branch-22.10/java/src/test/java/ai/rapids/cudf/ColumnVectorTest.java#L5081-L5090 showing an example of how it behaves in practice.

**Comment by sameerz** [comment]
Hi @mtsol do the comments so far help?  Let us know if you have any other questions, or if this can be closed.
