### ISSUE TITLE
Delta Lake and AQE on Databricks 10.4 workaround

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#6539]
After https://github.com/NVIDIA/spark-rapids/pull/6461 is merged, this will enable Adaptive Query Execution (AQE) on Databricks. One issue that was observed earlier is that Delta Lake metadata queries on Databricks use the AQE functionality despite whether it is enabled or not in the Spark configuration.  A workaround was created using a flag in the Databricks shim (`AQEUtils.isAdaptiveExecutionSupportedInSparkVersion`) in the call `isDeltaLakeMetadataQuery` to handle these queries.

With AQE availability on the Databricks platform, this functionality should be re-tested and if Delta Lake metadata queries work, the workaround should be removed, as then the Databricks platform can proceed using AQE if necessary with Delta Lake metadata queries.

**Comment by tgravescs** [comment]
ok so the issue now is that if the user turns of aqe on Databricks 10.4, you can hit the original issue where they have a bug that still tries to use Databricks. We need to fix this in our code, likely we can just change it to be based on if AQE is enabled or not.

**Comment by NVnavkumar** [comment]
> ok so the issue now is that if the user turns of aqe on Databricks 10.4, you can hit the original issue where they have a bug that still tries to use Databricks. We need to fix this in our code, likely we can just change it to be based on if AQE is enabled or not.

So this means that the workaround should only be used if `spark.sql.adaptive.enabled` is false?

**Comment by tgravescs** [comment]
correct, because of the databricks bug that they still use AQE in certain situations even if the config is off, if the user turns it off we need the workaround in place.  I'm not sure if that happens on 9.1, we were seeing it in 10.4
