### ISSUE TITLE
Investigate improvement to Alluxio for large files

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#6540]
**Is your feature request related to a problem? Please describe.**
I'm seeing that we can stream from s3 faster then reading from alluxio for large files.  Investigate if anything can configure to improve this or if its just an issue with slower disks/network on the cluster vs bandwidth to s3.

**Comment by tgravescs** [comment]
so if we use g4dn.8xlarge where the size of physical nvme is larger and much faster, what is comparison?

**Comment by res-life** [comment]
The result of using g4dn.8xlarge * 3

### disable alluxio, directly read s3:
Spent 3.01 minutes runtime

### enable alluxio:
1st cold read spent: 2.84 minutes runtime
    hot reads  spent: 1.16 minutes runtime

The disk reading speed can reach up to 1.9G/s

## some ideas
The s3 bandwidth is as fast as the `g4dn.8xlarge` disk.
But directly reading from s3 spent more time.
I guess it's because of lots of backward seekings in the `hadoop-aws` client.

### Tested the seek performance of aws client:

install aws
aws configure set aws_access_key_id <access-key>
aws configure set aws_secret_access_key <secret-key>
cat ~/.aws/credentials

```java
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.S3Object;
import com.amazonaws.services.s3.model.S3ObjectInputStream;

import java.io.IOException;

// test performance of seeking to 100M
public class MyMain {
  public static void main(String[] args) throws IOException {
    AmazonS3ClientBuilder b = AmazonS3Client.builder();
    b.setRegion("us-west-2");
    AmazonS3 client = b.build();
    String bucket = "ndsv2-data";
    String key = "parquet_sf3000/store_sales/ss_sold_date_sk=2450965/" +
      "part-00142-7d4501b0-48c4-4c81-a21a-a7a1069ac7b7.c000.snappy.parquet";
    S3Object o = client.getObject(bucket, key);
    S3ObjectInputStream content = o.getObjectContent();
    long start = System.currentTimeMillis();
    content.skip(100L * 1024L * 1024L * 1024L); // seek to 100M
    long end = System.currentTimeMillis();
    System.out.println("OK");
    System.out.println("used time MS: " + (end - start));
  }
}
```

From databricks cluster, used time MS: 8,805
Note: the time 8,805 indicates the s3 seek is brutal seek.

See [s3 file system](https://github.com/apache/hadoop/blob/rel/release-3.3.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java#L197)

S3 invokes a http request to open s3 file and get the input stream
s3 reopen the file from a position if seek backward, see S3AInputStream [link1](https://github.com/apache/hadoop/blob/rel/release-3.3.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L180), [link2](https://github.com/apache/hadoop/blob/rel/release-3.3.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInputStream.java#L359).
reopen(reopen reason = "read from new offset", targetPos, len, false)

**Comment by res-life** [comment]
Seems it's an issue with slower disks on the cluster vs bandwidth to s3.

**Comment by res-life** [comment]
Others aws client performance doc:

https://github.com/apache/hadoop/blob/trunk/hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/performance.md

https://github.com/apache/hadoop/blob/trunk/hadoop-tools/hadoop-aws/src/site/markdown/tools/hadoop-aws/prefetching.md

I tested the `fs.s3a.experimental.input.fadvise` = `random`, did not get more performance improvement.

**Comment by tgravescs** [comment]
The only other thing we could experiment with is if we know we are on a node with slower nvme (cheat and experiment by just setting a config) and we are reading large files, just skip going to alluxio and use the multi-threaded reader. Which reader was used in the above experiments - coalescing or multi-threaded, or the default? ie s3 directly would be multithreaded but alluxio would be coalescing. 

>  The query directly from s3 spent 4.38 minutes, while the query from alluxio cache spent 6.24 minutes. (with 2xlarge)

So why we reading directly from s3 with the 8xlarge nodes that much better (1st cold read spent: 2.84 minutes runtime with 8xlarge).  I assume perhaps the network speed was also increased with the node size that explain that.  Did you run the experiment multiple times to make sure it didn't vary alot?

**Comment by res-life** [comment]
BTW, all the cases:
Please see the bottom 3 lines, it didn't vary a lot.

small files: total size is 298.10MB, the path is /nds20/nds2-sf2-parquet/store_sales
large files: total size is 439G, the path is /ndsv2-data/parquet_sf3000/store_sales

|File size|node type |read from where | used time (1st, 2nd, 3rd) | comments |
|-|-|-|-|-|
|small files| r5a.2xlarge * 1 + g4dn.2xlarge * 3 |Read from S3|10.31 seconds, 6.36 seconds, 5.65 seconds||
|small files| r5a.2xlarge * 1 + g4dn.2xlarge * 3 |Cold read from Alluxio|13.69 seconds| only 1 time running for cold read|
|small files| r5a.2xlarge * 1 + g4dn.2xlarge * 3 |Hot read from Alluxio|2.17 seconds, 2.37 seconds, 1.49 seconds |wait until all the files are 100% cached|
|small files| r5a.2xlarge * 1 + g4dn.8xlarge * 3 |Read from S3|7.57 seconds, 4.36 seconds, 3.73 seconds||
|small files| r5a.2xlarge * 1 + g4dn.8xlarge * 3 |Cold read from Alluxio|13.31 seconds|only 1 time running for cold read|
|small files| r5a.2xlarge * 1 + g4dn.8xlarge * 3 |Hot read from Alluxio|2.09 seconds,1.30 seconds,1.06 seconds|wait until all the files are 100% cached|
|large files| r5a.2xlarge * 1 + g4dn.2xlarge * 3 |Read from S3|5.13 minutes,5.06 minutes,5.35 minutes ||
|large files| r5a.2xlarge * 1 + g4dn.2xlarge * 3 |Cold read from Alluxio|5.61 minutes|only 1 time running for cold read|
|large files| r5a.2xlarge * 1 + g4dn.2xlarge * 3 |Hot read from Alluxio|6.27 minutes, 6.24 minutes, 6.25 minutes|wait until all the files are 100% cached|
|large files| r5a.2xlarge * 1 + g4dn.8xlarge * 3 |Read from S3|3.76 minutes,3.64 minutes,3.41 minutes||
|large files| r5a.2xlarge * 1 + g4dn.8xlarge * 3 |Cold read from Alluxio|4.36 minutes|only 1 time running for cold read|
|large files| r5a.2xlarge * 1 + g4dn.8xlarge * 3 |Hot read from Alluxio|1.14 minutes,1.14 minutes,1.14 minutes|wait until all the files are 100% cached|

**Comment by res-life** [comment]
Considering https://github.com/NVIDIA/spark-rapids/issues/6517 with this issue together.
We found the following:
For both small files and large files, reading from s3 is better than Cold reading from Alluxio.
For large files and low disk speed node types, reading from s3 is better than hot reading from Alluxio.

**Comment by tgravescs** [comment]
Nice, summary.  so I think there are a few things to investigate then.  

Since we need to read from alluxio in order to get it to cache, we want to do that whenever the hot read is faster. So we should investigate if there are any alluxio configs to help improve the cold reads. I know we had looked at this a long time back but seemed like still a small difference and if its only a few seconds then it might not be a big deal.

two is then if we know we are on slow disks and reading large files, then we should just skip alluxio altogether and just use the multi-threaded reader from s3.  Or for large files with the slow disks what is the alluxio  read time (both hot and cold) if we use the multi-threaded reader instead of the coalescing?

**Comment by res-life** [comment]
In this comment: https://github.com/NVIDIA/spark-rapids/issues/6517#issuecomment-1294931701

> Cold reading from Alluxio(without cache) spent 4.5 seconds,

But [the table](https://github.com/NVIDIA/spark-rapids/issues/6540#issuecomment-1298185479) in this issue shows:
It used 13.69 seconds for small files for cold reading.

It's because the 4.5s does not contain the mount time(Usually 6s~10s)
It's tested by 
```
// Skip the first query which automatically mounts the bucket.
./alluxio fs free <path>
query again.
```

The 13.69 seconds is just the time of the first query which automatically mounts the bucket.

**Comment by tgravescs** [comment]
ok so if we manually mount and use the regex we don't see that extra 6s-10s correct?
We may want to document this in our alluxio doc.

**Comment by res-life** [comment]
You mean `spark.rapids.alluxio.pathsToReplace` not `spark.rapids.alluxio.bucket.regex`?
`bucket.regex` is used by auto-mount.

I suppose you mean `pathsToReplace`.

Yes, we don't see that extra 6s-10s if we manually mount and set `pathsToReplace`

It takes 8.64 seconds for this scenario.

### My test step is:
- start cluster
- enable `auto-mount` and query a table in the bucket `s3a://ndsv2-data/`, this will warm up the JVM I think.
- set `pathsToReplace`, of cause this will override `auto-mount`.
Mount another bucket manually
```
./alluxio fs mount --readonly --option s3a.accessKeyId=xxx --option s3a.secretKey=xxx /nds20 s3a://nds20/
```
query the table in this bucket, it spends 8.64 seconds.

Note: If we do not warm up the JVM, the time is longer about 13s.

### other
I found an issue when enable `auto-mount` and `pathsToReplace` at the same time, see:
https://github.com/NVIDIA/spark-rapids/issues/7003

**Comment by tgravescs** [comment]
> Note: If we do not warm up the JVM, the time is longer about 13s.
What exactly do you mean by warm up the jvm?  Is it running anything else first or is it the first time this query runs?  ie even if you automount the very first query run is 13s?

**Comment by res-life** [comment]
>Or for large files with the slow disks what is the alluxio read time (both hot and cold) if we use the multi-threaded reader instead of the coalescing?

I tested it, the performance is almost the same. Seems the bottleneck is the disk speed and multi-threaded does not performance better.

**Comment by res-life** [comment]
> What exactly do you mean by warm up the jvm? Is it running anything else first or is it the first time this query runs?
Yes, running anything else first. 

I first test auto-mount to warm up the JVM, then test `pathsToReplace` and manual mount.
The second manual mount is against another bucket.

>   ie even if you automount the very first query run is 13s?
Yes, always, please see the test results in the above large table.
