### ISSUE TITLE
[FEA] Reverse "Normalize nans in GpuSortArray #6451"

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids#6588]
As libcudf is going to handle NaN natively, we should reverse the scala code in PR #6451 to gain better performance.

We should be able to proceed with it after the following cudf dependency merged:
 * https://github.com/rapidsai/cudf/pull/11703

**Comment by ttnghia** [comment]
CC @HaoYang670.

**Comment by HaoYang670** [comment]
This is blocked by https://github.com/rapidsai/cudf/issues/11630, right?

**Comment by ttnghia** [comment]
Yes. Sorry that I forgot to provide the dependency.

**Comment by ttnghia** [comment]
Dependency merged!

**Comment by HaoYang670** [comment]
Thank you for keep tracking this. I will update the plugin.
