### ISSUE TITLE
[FEA] Metrics to show time a task spent waiting for the GPU semaphore

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#659]
**Is your feature request related to a problem? Please describe.**
Some SQL nodes have a metric that measures time spent waiting for upstream nodes to complete, like the `collectTime` metric in GpuCoalesceBatches and the `buildTime` metric in GpuShuffledHashJoin.  Often these metrics can end up measuring a significant amount of time spent waiting for the GPU semaphore, and it would be nice to show a separate metric detailing just how much of a task's time was spent blocked by the GPU semaphore.

**Describe the solution you'd like**
It should be relatively straightforward for GpuSemaphore to track blocked time per task, as it already tracks acquisition state per task.  We can then add a new GpuSemaphore method, `getBlockedTime(TaskContext)` or something similar, that reports the amount of time spent blocked on the GPU semaphore for a specified task context.

SQL UI nodes can then call this new method and use the result to report blocked time in their metrics.

**Comment by JustPlay** [comment]
What the `blocked time on gpu semaphore` can guide us to do ?

We have add some `logInfo()` points into all the key path or operator in rapids-0.2 (for debug and performance analysis), we now have the time info when a task acquire and release the semaphore; how can we make the most  of this information？

**Comment by jlowe** [comment]
> What the blocked time on gpu semaphore can guide us to do ?

The main intent of this feature is to help explain when some other metric, like `collectTime`, seems large, how much of the time was the task itself being slow vs. the task waiting for other tasks via the GPU semaphore.

If the blocked time is very high then it indicates that increasing the concurrent task count could help improve performance, if there's sufficient GPU memory to handle the higher task concurrency.

**Comment by JustPlay** [comment]
Do we want a task-level or query-node-level metric?

**Comment by jlowe** [comment]
> Do we want a task-level or query-node-level metric?

I think a task-level metric is appropriate, at least initially.  Task-level metrics are already summarized into min/avg/max/total  stats, so we can see how long the average task spent waiting on the semaphore in that node and the worst-case situation.  If what you mean by, "query-node-level" is the total amount of time spent waiting for the semaphore across all tasks then that will be shown.

If instead you mean total wall-clock time spent waiting for the semaphore (i.e.: avoiding double-counting time while two tasks are waiting for the semaphore at the same time) then this is quite complex to calculate, as we'd have to not only coordinate the overlap between tasks within an executor but also across executors to avoid any double-counting of time spent waiting.

**Comment by JustPlay** [comment]
> > Do we want a task-level or query-node-level metric?
> 
> I think a task-level metric is appropriate, at least initially. Task-level metrics are already summarized into min/avg/max/total stats, so we can see how long the average task spent waiting on the semaphore in that node and the worst-case situation. If what you mean by, "query-node-level" is the total amount of time spent waiting for the semaphore across all tasks then that will be shown.
> 
> If instead you mean total wall-clock time spent waiting for the semaphore (i.e.: avoiding double-counting time while two tasks are waiting for the semaphore at the same time) then this is quite complex to calculate, as we'd have to not only coordinate the overlap between tasks within an executor but also across executors to avoid any double-counting of time spent waiting.

I think we can add the `gpu semaphore waiting time metric` to some key nodes which acquire the low-level java semaphore (the node on which the task acquire the semaphore for the first time); can you give  me the node list?

**Comment by jlowe** [comment]
If you search the callgraph of `GpuSemaphore.acquireIfNecessary` you'll see the types of exec nodes that are calling it.  Off the top of my head, here's places I can think of (probably not a complete list):
- Any input scan (e.g.: GpuBatchScanExec, GpuFileSourceScanExec) since that's typically the first operation in a query that needs GPU memory
- Shuffle nodes, as they acquire the GPU before placing received shuffle inputs into GPU memory
- RowToColumnarExec, as it needs to acquire the GPU before placing a columnar batch into GPU memory that was produced from a series of CPU-produced rows

**Comment by revans2** [comment]
@jlowe I think this is done now. If you agree we can close this.
