### ISSUE TITLE
[FEA] support OctetLength SQL operator

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#66]
**Is your feature request related to a problem? Please describe.**
It would be great to support the `octet_length` SQL function.

**Comment by revans2** [comment]
We probably can make this work by using count_elements like with #79, but it would require us to see if we can create a a list view from a string column, which I don't think is allowed.  Either way we will need some help from cudf.

**Comment by jlowe** [comment]
Implemented by #4611.
