### ISSUE TITLE
[FEA] CI premerge check should fail if build modifies files in the repository

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#661]
**Is your feature request related to a problem? Please describe.**
The `verify` build automatically updates `docs/configs.md` if necessary, based on the contents of `RapidsConf`.  Sometimes a PR may be submitted that should have modified generated documentation, but it was missed somehow.  The CI premerge check should catch this and flag the PR accordingly.

**Describe the solution you'd like**
At least as it is now, any build that starts with no modified repository files should complete without modifying repository files.  The CI premerge check should look for modified repository files after a build (e.g.: `git status -s | grep '^ M'`), and if any are found, it should flag an error during the premerge check.

**Comment by GaryShen2008** [comment]
For this issue, we should use 'git status' to check if configs.md has been changed in the building process. If so, the premerge should fail. Right?

**Comment by jlowe** [comment]
Yes, we can use `git status --porcelain` to get a script-friendly list of files different than the repo and grep that list for any modified files.  If there are modified files after a CI premerge build then that implies the PR is missing some files that should have been added (e.g.: `docs/configs.md` which is generated during the build).

Ideally this check should occur immediately after the build and before unit tests are run to avoid waiting for all tests to run just to fail the PR due to missing files.
