### ISSUE TITLE
[FEA] Qualification Tool: Print timestamp related functions. 

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6645]
I wish Qualification Tool can print timestamp related functions such as current_timestamp.
This can help us know in advance what timestamp related function are used by this job, just in case if user are running non-UTC timezone.

**Comment by tgravescs** [comment]
can you be more specific here?  We added unsupported execs and expressions to the output recently, not sure if those are included there. You want to see them even if supported?  How do you want them to show up to the user, it seems like a very specific thing for qualification.  Do you want them under potential problems and only in csv?

**Comment by viadea** [comment]
The reason for this request is if a user is using a non-UTC timezone, and suddenly all of the timestamp related functions will fallback to CPU.
We want the qualification tool can list ALL of the such potential problematic timestamp related functions in a CSV file, so that we can measure how much impact of the timezone fallback.

I do not think we should use it for the scoring system of Q tool, but just saving it somewhere.
