### ISSUE TITLE
[DOC] Incorrect cudf jar name compared to the one available in downloads 

### ISSUE THREAD

**Issue by vamseeyarla** [NVIDIA/spark-rapids#665]
## Report incorrect documentation

**Location of incorrect documentation**
https://nvidia.github.io/spark-rapids/docs/get-started/getting-started.html#download-the-rapids-jars

**Describe the problems or issues found in the documentation**
It is mentioned that the sample version of jar for CUDA-10.1 is cudf-0.15-SNAPSHOT-cuda10-1.jar but the one available in the download section is cudf-0.14-SNAPSHOT-cuda10-1.jar.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Correct the proper name accordingly.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by sameerz** [comment]
Closed by PR #637
