### ISSUE TITLE
[FEA] [Audit] -  [SPARK-40389][SQL] Decimals can't upcast as integral types if the cast can overflow

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#6673]
**Is your feature request related to a problem? Please describe.**
This is a bug fix where the condition is checked if it is safe to cast to Integral type. I think this change doesn't affect spark-rapids but I am not certain. It would be good if someone familiar with this code take a look. We could add a test if required.

Apache Spark commit: https://github.com/apache/spark/commit/17982519a7

**Comment by revans2** [comment]
You are correct that this should not really impact us. The check is mostly for automatic casting done in the logical planning stages.  The only possible impact would be that some queries/tests might need to have some explicit casts added that were not needed before, but I don't think that is very likely.

**Comment by sameerz** [comment]
Closing based on the above comment.
