### ISSUE TITLE
Support hashaggregate for Array[Any]

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#6680]
We reverted 122e107b977daa012479456794916e292aa1f6e4 as part of #6679 

The revert should be reverted when https://github.com/rapidsai/cudf/pull/11792 is merged. 

We also need to add tests for aggregates that were missed and use Sort based aggregation as per 
https://github.com/NVIDIA/spark-rapids/issues/6680#issuecomment-1265959724

**Comment by revans2** [comment]
We also need to add in more tests to cover the cases that https://github.com/rapidsai/cudf/pull/11792 now supports and to cover aggregations that were missed but require sort based operations.

**Comment by sameerz** [comment]
Depends on https://github.com/NVIDIA/spark-rapids/issues/7485 and https://github.com/NVIDIA/spark-rapids/issues/5430

**Comment by razajafri** [comment]
build
