### ISSUE TITLE
[FEA] Enhance profiler recommendations for key settings for performance tuning

### ISSUE THREAD

**Issue by mattahrens** [NVIDIA/spark-rapids#6696]
I wish the RAPIDS Accelerator for Apache Spark profiling tool would recommend optimal settings to improve application performance.  Key settings that would be relevant are:

- [ ] spark.sql.files.maxPartitionBytes: test out your latest changes with more benchmarks, also try to separate out CPU/GPU task sizes
- [ ] spark.sql.shuffle.partitions: look into more granular spill metrics for determining heuristic for increasing/decreasing
- [ ] spark.rapids.sql.batchSizeBytes: look into more granular spill metrics for determining heuristic for increasing/decreasing
- [ ] spark.rapids.sql.reader.batchSizeBytes: look into more granular spill metrics for determining heuristic for increasing/decreasing

**Comment by razajafri** [comment]
This is what I have found in my research on this topic. 

I ran a customer query by tweaking the `spark.sql.shuffle.partitions` manually and found that increasing the number from 200 to 400 eliminated the spill that we were experiencing, but upon further increasing the partition number to 1600 I saw a good perf gain. I was able to come up with a heuristic that would spit out a number close to 400 which could avoid the spillage, but going from that number to the higher performing number (1600) was not something that I worked on or achieved.

I did find good resources online that went over in great detail on how to tweak Spark jobs. Some of them are 

Autotuner - https://youtu.be/tSKQb5mavuk
Spark tuning by Aniya Bida - https://youtu.be/HBZuB3pPri0
Straggler tasks - https://youtu.be/h_LgEUPk1AY 

These videos also share some heuristics that could be used by us
