### ISSUE TITLE
[DOC] kubernetes guide dockerfile is outdated

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#6740]
I was trying to use `Dockerfile.cuda` referred here https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-kubernetes.html#docker-image-preparation, but it failed to build since it is trying to pull too old an image (CUDA 11.0) from the docker repositories (https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/get-started/Dockerfile.cuda#L17). 

I think all that we need to do is update that to pull something like 11.5+ (`FROM nvidia/cuda:11.8.0-devel-ubuntu18.04` seemed to work for me locally), but pointing out the file is stale and would like to know if someone with k8s experience can audit it to see if more changes need to happen.

**Comment by wjxiz1992** [comment]
Created a PR to do the update, and verified on our internal DGX k8s cluster.
