### ISSUE TITLE
[BUG] Always read old data from alluxio regardless of S3 changes when using CONVERT_TIME replacement algorithm 

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#6779]
**Describe the bug**
When using the CONVERT_TIME Alluxio replacement algorithm, auto mount method, and adding new files into s3, 
Spark rapids can't read the new files.
The query path is replaced with the Alluxio path, and Alluxio does not fetch new files from S3, thus this issue occurs.

For example:
Read from `s3://bucket/tab`, the replaced path is `alluxio://master_ip:19998/tab`
Adding files to `s3://bucket/tab` will reproduce this issue.

**Steps/Code to reproduce bug**
Read from an s3 path
``` scala
val base_path = "s3a://liangcail/chongg-test"
spark.conf.set("spark.rapids.alluxio.replacement.algo", "CONVERT_TIME")
spark.conf.set("spark.sql.adaptive.enabled", "false")

spark.read.parquet(base_path).createOrReplaceTempView("tbl")
spark.sql("select (sum(ws_sold_time_sk) + sum(ws_ship_date_sk)) / 3800809931000 / 2 from tbl").show()
```
Add files to the s3 path
```
aws s3 put x.parquet s3://liangcail/chongg-test/new_name.parquet
```

Logs:
```
22/10/13 09:57:47 DEBUG AlluxioUtils: 
Replace s3a://liangcail/chongg-test to alluxio://10.59.255.53:19998/liangcail/chongg-test
22/10/13 09:57:47 DEBUG AlluxioUtils: 
Automount replacing paths: AlluxioPathReplaceConvertTime(alluxio://10.59.255.53:19998/liangcail/chongg-test,Some(s3a://))

22/10/13 09:57:47 DEBUG FileSystemMasterClient: Exit (OK): ListStatus(path=/liangcail/chongg-test,options=loadMetadataType: ONCE
commonOptions {
  syncIntervalMs: -1
  ttl: -1
  ttlAction: DELETE
}
loadMetadataOnly: false
) in 5 ms
```

Seems Alluxio did not sync the directory list from S3 when doing ListStatus.

**Environment details (please complete the following information)**
Databricks with Alluxio open

**Additional context**
For the default installation of Alluxio, Alluxio will never synchronize the files list from S3 for any directories.
Seems The alluxio ListStatus operation also does not sync by default.

Note:  `createOrReplaceTempView` before each query also has this issue.

Adding the following config works:
```
alluxio.user.file.metadata.sync.interval=5s
```

Not sure about the delay time, maybe 2 ways:
- When the query running, immediately sync and the query result is correct.
- Query use old meta, thus query result is incorrect. Start an async thread to sync, after 5s the following query will be OK.

**Comment by tgravescs** [comment]
This seems like it works as designed in Alluxio.   did you try setting the metadata sync to 0?  I wouldn't expect a 5 second interval to work immediately unless the put happens in aws s3 and then you wait 5+ seconds for alluxio to do the sync and then after that it would work.

`When its value is set to 0, Alluxio will always resync with under storage whenever metadata is accessed. `

I also don't understand how that differs in CONVERT_TIME and TASK_TIME can you explain?  is it because the TASK_TIME doesn't do the list status so the metadata in Alluxio isn't filled in?  which I wouldn't expect since as soon as you actually read it I would think it would get filled in.

**Comment by tgravescs** [comment]
@res-life I still have questions above, please answer

**Comment by tgravescs** [comment]
@res-life  we should at least document the behavior of alluxio in our docs. Mention sync is disabled by default so it won't pick up changed files.  If you want to enable sync it has performance impact and here is what you need to do like I said:

 just removing the code to special case PartitioningAwareFileIndex and CatalogFileIndex and having ti do the list leaf files all the time to fix this issue and then allow locality to apply. 

Or are you now saying that your analysis in PR https://github.com/NVIDIA/spark-rapids/pull/6806 was incorrect with convert time?  Either way I don't want it removed, we can document the behavior of each.

**Comment by tgravescs** [comment]
@res-life  do you have another issue to document the sync setup?

**Comment by res-life** [comment]
OK, I'll file a follow-up issue to track.

**Comment by res-life** [comment]
The follow-up issue: https://github.com/NVIDIA/spark-rapids/issues/7079
