### ISSUE TITLE
[FEA] Investigate `GpuExpression` supporting an estimate API

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#6784]
As a part of tracking GPU memory usage, we believe that instrumenting execs with the potential maximum memory usage is key. This requires us to provide an estimate _per expression_, and that seems like the best place to begin (that's what this issue is really about).

One simple example is project. This exec can take any number of expressions and potentially explode the input in the number of columns. We know what expressions are about to be evaluated, so we could ask each expression to estimate, based on the column those expressions are referencing. 

So a first step here is to go through the expressions we have. I'd be curious to start with some complex ones like string manipulation expressions and figure out how a guesstimate can be made. We could break this issue into sub-issues as this investigation happens.

I believe the outcome of this issue is a proposal for an API, or just the implementation if it's further along.

**Comment by revans2** [comment]
https://github.com/NVIDIA/spark-rapids/issues/7257 is the plan for this.
