### ISSUE TITLE
Add JDK11 to the build matrix mvn-verify-check at least for one spark version

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#6788]
Build matrix supports up to 256 jobs https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

We could make jdk version an official dimension in the build matrix or have some ad-hoc entry for just one spark version. 

The point is to prevent regressions like #6692 with a short PR check

**Comment by pxLi** [comment]
cc @YanxuanLiu to help w/ this one, thanks~

I think initially we do not have to run it for all versions (matrix), simply add one step to do a sanity check would be fine~

**Comment by gerashegalov** [comment]
@sameerz if we were to cover only some shims for JDK11 which one should be prioritized for our users?

**Comment by sameerz** [comment]
Let's test Spark 3.1.2 and 3.2.1.  If we can add one more, then let's test with Spark 3.3.1, when it is available.
