### ISSUE TITLE
Add -Werror to javac args for scala-maven-plugin

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#6789]
Prevent Javac Xlint warnings from going unnoticed by using [-Werror][1]

With #6728 being fixed it should be added to scala.javac.args `<otherJavacArgs>|-Werror` 
 
[1]: https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html 

```
-Werror
      Terminate compilation if warnings occur.
```

This is to prevent  the code like fixed in #6730 from being merged to begin with

**Comment by pxLi** [comment]
This one would require to fix all existing warning before/along with enabling the lint config.

I would like to hear more feedbacks if any developer would like to help w/ this

**Comment by gerashegalov** [comment]
I think the main objective is to stop introducing new issue to the code base . 

When necessary the developer  will have to make it a conscious decision. They would have to use some sort of SuppressWarning annotation clearly visible during the reviews instead of silently sneaking it in.

To this end, the first PR can just enable the Werror and 
1. silence  every newly fatal error
2. Open an epic with issues to actually fix  anything found in 1 in future PRs

**Comment by pxLi** [comment]
cc @GaryShen2008 to help

For scala.javac.args, we could simply add the `-Werror` to https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/pom.xml#L1076

and suppress warnings for each xlint check by add annotation, @SuppressWarnings("<lint-warning>") like
@SuppressWarnings("unused")
@SuppressWarnings("unchecked")

Also we have https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/pom.xml#L1370 for scalac
```
<arg>-Xfatal-warnings</arg>
```
Per the scalac doc https://docs.scala-lang.org/overviews/compiler-options/index.html, the 2 options are the same thing, so we could also update the scala option at the same time to make it consistent

 ![image](https://user-images.githubusercontent.com/8086184/197659557-0842d5c1-c2d5-42e6-a0db-f1e7319d25ac.png)

thanks
