### ISSUE TITLE
Investigate other compression codecs and other serializers.

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#6794]
Spark allows users to set the compression codec via `spark.io.compression.codec` (`lz4`, `lzf` and `snappy`). 

It also allows users to set different serializers using `spark.serializer` (`org.apache.spark.serializer.JavaSerializer` or `org.apache.spark.serializer.KryoSerializer`).

This task is to run the regular shuffle and the multi-threaded shuffle with the test matrix above and obtain performance numbers. These could be used to suggest defaults to users.

**Comment by jbrennan333** [comment]
I've been doing some preliminary testing on dataproc.

Initial tests were using the regular shuffle manager, and varying the `spark.io.compression.codec`.   The default value is `lz4`, so I ran experiments between `lz4` and the other options.

Here is the base configuration template I used:
```
export SPARK_HOME=/usr/lib/spark
export SPARK_RAPIDS_PLUGIN_JAR=$SPARK_HOME/jars/rapids-4-spark_2.12-22.12.0-20221115.151307-42-cuda11.jar

$SPARK_HOME/bin/spark-submit \
--master yarn \
--conf spark.io.compression.codec=lz4 \
--conf spark.driver.maxResultSize=2GB \
--conf spark.executor.cores=12 \
--conf spark.locality.wait=0 \
--conf spark.rapids.sql.concurrentGpuTasks=4 \
--conf spark.executor.resource.gpu.amount=1 \
--conf spark.task.resource.gpu.amount=0.0833 \
--conf spark.executor.memory=16G \
--conf spark.driver.memory=50G \
--conf spark.sql.files.maxPartitionBytes=2gb \
--conf spark.driver.extraClassPath=$SPARK_RAPIDS_PLUGIN_JAR \
--conf spark.executor.extraClassPath=$SPARK_RAPIDS_PLUGIN_JAR \
--conf spark.rapids.memory.host.spillStorageSize=32G \
--conf spark.sql.adaptive.enabled=true \
--conf spark.plugins=com.nvidia.spark.SQLPlugin \
--conf spark.rapids.memory.pinnedPool.size=8G \
--conf spark.rapids.sql.incompatibleOps.enabled=true \
--conf spark.executor.instances=8 \
--conf spark.executor.memoryOverhead=16G \
--conf spark.scheduler.minRegisteredResourcesRatio=1.0 \
--conf spark.dynamicAllocation.enabled=false \
--conf spark.sql.autoBroadcastJoinThreshold=10m \
--files $SPARK_HOME/scripts/gpu/getGpusResources.sh \
--conf spark.executor.extraClassPath=$SPARK_RAPIDS_PLUGIN_JAR \
--jars $SPARK_RAPIDS_PLUGIN_JAR \
```

**Comment by jbrennan333** [comment]
Results for DATAPROC REGULAR SHUFFLE LZ4 vs SNAPPY
```
	Snappy is a wash
		Overall Speedup: 1.0
		Slower Queries:
			0.93 query14_part1
			0.92 query14_part2
			0.92 query23_part1
			0.94 query23_part2
			0.84 query65
			0.93 query82
		Faster Queries:
			1.06 query4
			1.09 query5
			1.02 query16
			1.03 query64
			1.09 query74
			1.14 query80
			1.07 query93
```

**Comment by jbrennan333** [comment]
For testing with multi-threaded shuffle on dataproc.  I added the following configuration properties:
```
--conf spark.executor.extraClassPath=$SPARK_RAPIDS_PLUGIN_JAR \
--conf spark.shuffle.manager=com.nvidia.spark.rapids.spark312.RapidsShuffleManager \
--conf spark.rapids.shuffle.multiThreaded.writer.threads=12 \
--conf spark.rapids.shuffle.multiThreaded.reader.threads=12 \
--conf spark.rapids.shuffle.mode=MULTITHREADED \
```

**Comment by jbrennan333** [comment]
Results for DATAPROC MULTI-THREADED SHUFFLE (12/12) LZ4 vs LZF
```
	lzf is significantly slower
		Overall Speedup: 0.78
		Slower queries:
			0.82 query1
			0.63 query4
			0.61 query5
			0.80 query8
			0.87 query10
			0.77 query11
			0.87 query14_part1
			0.88 query14_part2
			0.75 query16
			0.77 query17
			0.76 query23_part1 
			0.77 query23_part2
			0.65 query24_part1
			0.70 query24_part2
			0.73 query25
			0.63 query29
			0.79 query30
			0.88 query31
			0.88 query35
			0.84 query37
			0.78 query38
			0.72 query40
			0.59 query50
			0.62 query64
			0.66 query65
			0.75 query67
			0.83 query69
			0.96 query72
			0.74 query74
			0.76 query75
			0.88 query77
			0.58 query78
			0.68 query80
			0.88 query81
			0.83 query82
			0.73 query84
			0.82 query85
			0.77 query87
			0.60 query93
			0.70 query94
			0.71 query95
			0.56 query97
		Faster queries:
			none
```

**Comment by jbrennan333** [comment]
Results for DATAPROC MULTI-THREADED SHUFFLE (12/12) LZ4 vs SNAPPY
```
	  Snappy is a wash
		Overall Speedup: 1.0
		Slower Queries:
			0.96 query14_part1
			0.94 query14_part2
			0.94 query23_part1
			0.92 query23_part2
			0.89 query65
		Faster Queries:
			1.06 query4
			1.02 query64
			1.07 query93
```

**Comment by jbrennan333** [comment]
The dataproc cluster was 8 a2-highgpu-1g nodes, each with 8 local ssds, and using local HDFS for the data.

**Comment by jbrennan333** [comment]
Results for SPARK2A MULTI-THREADED SHUFFLE (12/12) LZ4 vs SNAPPY
```
	Snappy is a little faster
		Overall Speedup: 1.015
		Slower Queries:
			none
		Faster Queries:
			1.45 query40
			1.05 query78
			1.05 query95
```

**Comment by jbrennan333** [comment]
Results for SPARK2A MULTI-THREADED SHUFFLE (12/12) LZ4 vs ZSTD
```
	ZSTD is a bit slower
		Overall Speedup: 0.97
		Slower Queries:
			0.90 query11
			0.95 query14_part1
			0.91 query16
			0.88 query23_part1
			0.90 query23_part2
			0.92 query24_part1
			0.93 query24_part2
			0.88 query38
			0.84 query65
			0.90 query78
			0.92 query94
			0.93 query95
		Faster Queries:
			none
```

**Comment by jbrennan333** [comment]
Results for SPARK2A REGULAR SHUFFLE LZ4 vs LZF
```
	lzf is significantly slower
		Overall Speedup: 0.83
		Slower queries:
			0.73 query4
			0.63 query5
			0.84 query11
			0.95 query14_part1 
			0.72 query15
			0.78 query16
			0.83 query23_part1 
			0.86 query23_part2
			0.66 query24_part1
			0.66 query24_part2
			0.60 query29
			0.69 query30
			0.79 query34
			0.80 query37
			0.74 query40
			0.67 query45
			0.59 query50
			0.71 query54
			0.63 query64
			0.73 query65
			0.80 query67
			0.66 query73
			0.85 query74
			0.85 query75
			0.71 query78
			0.69 query80
			0.84 query82
			0.62 query93
			0.75 query94
			0.87 query95
			0.65 query97
		Faster queries:
			none
```

**Comment by jbrennan333** [comment]
Results for SPARK2A REGULAR SHUFFLE LZ4 vs SNAPPY
```
	Snappy is a wash
		Overall Speedup: 1.0
		Slower Queries:
			0.89 query44
		Faster Queries:
			none	
```

**Comment by jbrennan333** [comment]
Results for SPARK2A REGULAR SHUFFLE LZ4 vs ZSTD
```
	ZSTD is a bit slower
		Overall Speedup: 0.96
		Slower Queries:
			0.97 query4
			0.85 query11
			0.94 query14_part1
			0.92 query14_part2
			0.96 query16
			0.91 query23_part1
			0.92 query23_part2
			0.93 query24_part1
			0.96 query24_part2
			0.84 query30
			0.89 query67
			0.93 query75
			0.83 query78
			0.89 query87
			0.93 query95
		Faster Queries:
			none
```

**Comment by jbrennan333** [comment]
Summary of overall NDS2 Power Run speedups with different codecs.  Baseline is LZ4.
```
Summary			Regular Shuffle Speedup			Multithreaded Shuffle (12/12) Speedup
LZF Dataproc			0.76							0.78
SNAPPY Dataproc			1.00							1.00
LZF Spark2a			0.83							0.83
SNAPPY Spark2a			1.00							1.02
ZSTD Spark2a			0.96							0.97
```

Next I will see if using `org.apache.spark.serializer.KryoSerializer` makes any difference.

**Comment by jbrennan333** [comment]
I ran some benchmarks on spark2a to see if using KryoSerializer makes a noticeable impact.
These are the configuration properties I added:
```
spark.serializer=org.apache.spark.serializer.KryoSerializer
spark.kryo.registrator=com.nvidia.spark.rapids.GpuKryoRegistrator
spark.kryoserializer.buffer.max=512M
```
I saw no significant performance change when I added this, with or without multi-threaded shuffling.

**Comment by jbrennan333** [comment]
I have not run with KryoSerializing on dataproc, but based on the spark2a results, I'm not sure we need to.

Based on all of my experiments so far, it seems like we should keep using these default values:
```
spark.serializer=org.apache.spark.serializer.JavaSerializer
spark.io.compression.codec=lz4
```
Since these are defaults, we don't have to specify them.

@abellina do you think any more investigation into this is needed?

**Comment by abellina** [comment]
@jbrennan333 this looks great, I think it is exactly what we were looking for, and it seems that deviating from the default can cause slowness. Thank you for running all of these scenarios!

SNAPPY seems interesting that it was slightly slower with the serial shuffle, but faster with the MT shuffle (almost implying that it uses the CPUs less, so more decompression tasks can run at once, but serial speeds will suffer?). To me 1% if sustained is not bad, especially if some queries can see such dramatic changes as query40 (1.4x) => a user may be running something similar to query40. This may be something we should look at further, e.g. it would be nice to know what about query40 allows SNAPPY to give an advantage.

Kryo serialization not having an impact is somewhat more surprising (to me). Spark documentation goes as far as recommending one sets it for "network intensive operations" but that it is not the default due to the custom class registration. It may be that this particular benchmark scale isn't big enough to cause a difference with it. That said, I am glad no regressions happened with it enabled!

I think this issue serves as a reference (almost a lookup table) of what the expectations should be given different codecs/serializers for NDSv2 @ 3TB. I don't believe we should run more experiments right now, and I'd consider this task complete.

**Comment by jbrennan333** [comment]
Thanks @abellina.  I'm not sure there is anything significant to learn from query40 itself.  I tried running just query40, and found no significant difference in 5 runs each (lz4 vs snappy with mt shuffle).  When running just query40 by itself, it takes around 6.5 seconds in all cases.  As part of the power run, it only takes about 1.5 seconds for Snappy and about 1.9 seconds for lz4.   So there is only a measurable difference for query40 in the context of the full power run.
