### ISSUE TITLE
[FEA] flatten module structure when possible

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#681]
Currently we build a shuffle plugin and a udf plugin.

- For the shuffle plugin, the main reason to keep separate was that at the time jucx was not in maven, and now it is. So we can merge this into the sql plugin.
- For the udf plugin, currently it is separate, because it seemed easier to have it that way as it's a plugin that works in the logical plan, and targets specific functionality on UDFs. That said, it would simplify things having it under a single module. 

@revans2 @jlowe @tgravescs any thoughts on the above? concerns?

@seanprime7 @wjxiz1992 for visibility, let us know if you think the UDF module should be separate for reasons I am missing.

**Comment by revans2** [comment]
I am fine either way but I am leaning towards keeping things separate and then combine them together at the end.  I don't think the pros out-weigh the cons yet.

Pros:  Slightly less complexity in the build and other plugins could possibly take advantage of our shim layer in case those APIs change from release to release.
Cons: Less separation of concerns and more probability in coupling between components.

**Comment by seanprime7** [comment]
I don't really have any strong opinion here as long as the udf compiler can be turned off/on with a flag.
