### ISSUE TITLE
[Audit][SPARK-40667] Refactor File Data Source Options

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#6830]
**Is your feature request related to a problem? Please describe.**
https://github.com/apache/spark/commit/8e853933ba64bb43e02af78198bc36d471efaa18 refactored the File Data Source Options. For example, it moves the `BASE_PATH_PARAM` from `PartitioningAwareFileIndex` to `FileIndexOptions`.

We should move some values to the shim layer of spark340

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by nartal1** [comment]
Refactoring this to shim layer of Spark 340 will fix these build errors:

```
[ERROR] [Error] /home/nartal/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala:40: value BASE_PATH_PARAM is not a member of object org.apache.spark.sql.execution.datasources.PartitioningAwareFileIndex
[ERROR] [Error] /home/nartal/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala:87: not found: value BASE_PATH_PARAM
[ERROR] [Error] /home/nartal/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala:148: not found: value BASE_PATH_PARAM
[ERROR] [Error] /home/nartal/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/execution/datasources/rapids/GpuPartitioningUtils.scala:40: Unused import

```
