### ISSUE TITLE
[FEA] Support Databricks 11.3 ML LTS

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#6879]
**Is your feature request related to a problem? Please describe.**
Add support for Databricks 11.3 ML LTS in the 22.12 release

**Describe the solution you'd like**
Create a shim layer for Databricks 11.3 ML LTS so that users of the plugin can run on Databricks.  

**Describe alternatives you've considered**

**Additional context**
https://docs.databricks.com/release-notes/runtime/11.3ml.html

https://github.com/NVIDIA/spark-rapids/issues/6879#tasklist-block-796a6486-d728-4e3c-9bb1-e222ba112966

**Comment by mattahrens** [comment]
We will also want to remove support for 9.1. And we will need to ensure the recent addition of AQE + DPP continues to work in 11.3.
