### ISSUE TITLE
[FEA] Support RAPIDS Spark plugin on ARM

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#6881]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish the RAPIDS Accelerator for Apache Spark would run on ARM 

**Describe the solution you'd like**
Distribute a plugin jar that is functional on ARM-based architecture (including cudf binaries on ARM)

More details:
We need to distribute the spark-rapids-jni jar with 2 different classifers:

1. cuda11-amd64
2. cuda11-aarch64

And Spark-rapids may have 2 profiles, 
one is for amd64 to depend on jni's cuda11-amd64 classifier, 
another is for aarch64(arm) to depend on jni's cuda11-aarch64 classifier.

For amd64, we build on centos7.
For Arm, we'll build on ubuntu 18.04.
It would be nice if we can build jni jar with Dockerfile.
https://hub.docker.com/layers/nvidia/cuda/11.5.2-runtime-ubuntu18.04/images/sha256-05d99b36cccb63102dbb1f5d9e74daf07d49a62151175693a6146c6d0244dc10?context=explore

**Describe alternatives you've considered**

**Additional context**

**Comment by pxLi** [comment]
Let's keep this open

We will reapply CICD update after developers refactor modules structures for different cpu archs in plugin and JNI repos.

**Comment by abellina** [comment]
UCX tracking issue: https://github.com/openucx/ucx/issues/8762

**Comment by pxLi** [comment]
merged #9888, udpating internal pipelines. I will update this ticket no other issue
