### ISSUE TITLE
[FEA] Support instr

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6884]
I wish we can support function instr.

```
spark-sql> SELECT instr(a, 'SQL') from test_diff_schema_evo ;
    ! <StringInstr> instr(a#16, SQL) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.StringInstr
```

**Comment by revans2** [comment]
This looks fairly simple. CUDF has `cudf::strings::find` that would return exactly what we want after we add 1 to the result, which is `ColumnView.substringLocate` in java.

**Comment by ttnghia** [comment]
@viadea Please check if we only need the query like `instr(column, literal)`. Currently in cudf we don't have a supporting API to implement `instr(column, column)`.

**Comment by viadea** [comment]
> @viadea Please check if we only need the query like `instr(column, literal)`. Currently in cudf we don't have a supporting API to implement `instr(column, column)`.

For this specific customer job, correct only `instr(column, literal)` is needed
