### ISSUE TITLE
[FEA] support expressions parameter in substr function

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6887]
I wish we can support expressions parameter in substr function.

Eg:
```
CREATE TABLE `default`.`teststring` (
  `x` INT,
  `y` STRING)
USING parquet;

select substr(y, 1, length(x)-1 ) from teststring;

    !Expression <Substring> substr(y#32, 1, (length(cast(x#31 as string)) - 1)) cannot run on GPU because len only supports IntegerType if it is a literal value
```

**Comment by revans2** [comment]
Right now for substring we require that the position and length be scalar values. If we are going to fix this we probably want to support them as literals or as non-literal values. Looking at the code for substring this should be doable, but it will get rather complicated if we want to do it well. The following is the implementation for literal position and length.

https://github.com/NVIDIA/spark-rapids/blob/02852f981cfbf744d9c298bcc1135761d6f367e1/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/stringFunctions.scala#L490-L502

The main difference is that any input that is not a literal, then the if/else checks that involves them would have to be on the GPU.  Like in this case if `length` is not a scalar, but `position` is 1 then we would need to translate the expression into something that looks like.

```
if (len < 0,
  "",
  cudf_substring(1 - 1, 1 + len - 1))
```

I think.  If position is not a literal, then things get to be a lot more complicated.

```
if (len < 0,
  "",
  if (pos = 0,
    cudf_substring(pos, len),
    if (pos > 0,
      cudf_substring(pos - 1, pos + len - 1),
      cudf_substring(pos, Int.MaxValue)))
```

But we would need to do a lot of testing to verify that this is correct.
