### ISSUE TITLE
[FEA] Support Apache Spark 3.3.1

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#6896]
**Is your feature request related to a problem? Please describe.**
Support Apache Spark 3.3.1 in the 22.12 release

**Describe the solution you'd like**
Remove 3.3.1-SNAPSHOT and replace with 3.3.1 

**Describe alternatives you've considered**

**Additional context**
Apache Spark 3.3.1 RC4 pass: https://lists.apache.org/thread/zys6wylgmdq3gm47go306tsr0ovto0g3

**Comment by firestarman** [comment]
Spark 3.3.1-SNAPSHOT jars have not been updated since Sept. 14, due to the version being changed to 3.3.2-SNAPSHOT.
So the code of v3.3.1 shim may not be up to date.
I will run all the tests to verify it.

**Comment by firestarman** [comment]
The IT verification is blocked, because the Spark v3.3.1 binary is not ready yet for downloading.

**Comment by tgravescs** [comment]
binary is at: https://dlcdn.apache.org/spark/spark-3.3.1/
