### ISSUE TITLE
Spark-3.4 build failure in AggregateFunctions

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#6900]
**Is your feature request related to a problem? Please describe.**
Spark3.4 build is failing in AggregateFunctions with below errors. Need to fix these errors:

```
06:04:19  [[1;31mERROR[m] [Error] /home/jenkins/agent/workspace/spark340_nightly-github/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala:1084: value checkForNumericExpr is not a member of object org.apache.spark.sql.catalyst.util.TypeUtils
06:04:19  [[1;31mERROR[m] [Error] /home/jenkins/agent/workspace/spark340_nightly-github/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/AggregateFunctions.scala:1575: value checkForNumericExpr is not a member of object org.apache.spark.sql.catalyst.util.TypeUtils
```

**Comment by HaoYang670** [comment]
Related to https://github.com/apache/spark/commit/34754f00e7618fca43d5ae9aec2c8b3ab83c8771

**Comment by HaoYang670** [comment]
and https://github.com/apache/spark/commit/2c9b4ad02f2675b5929f2bd6c6e8cb6c8bc1e878

**Comment by HaoYang670** [comment]
I guess we should fix 
```
06:04:13  [�[1;31mERROR�[m] [Error] /home/jenkins/agent/workspace/spark340_nightly-github/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:2596: value failOnError is not a member of org.apache.spark.sql.catalyst.expressions.GetMapValue
```
in #6383. cc @nartal1

**Comment by nartal1** [comment]
> I guess we should fix
> 
> ```
> 06:04:13  [�[1;31mERROR�[m] [Error] /home/jenkins/agent/workspace/spark340_nightly-github/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:2596: value failOnError is not a member of org.apache.spark.sql.catalyst.expressions.GetMapValue
> ```
> 
> in #6383. cc @nartal1

Thanks @HaoYang670 ! Updated this issue to fix only `checkForNumericExpr` errors.
