### ISSUE TITLE
[FEA] run integration tests against SPARK-3.0.1

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#696]
Spark 3.0.1 is officially out.  We should set up CI to at least run the integration tests against 3.0.1 nightly, but ideally we should do it as a part of the pre-merge build in parallel with the 3.0.0 build we do today.

**Comment by tgravescs** [comment]
we have updated the versions and this should just work now but we need to test (or see what ci does tonight)

**Comment by tgravescs** [comment]
we needed to push the spark 3.0.1 to our urm repo but after that everything is working.
