### ISSUE TITLE
[BUG] Dynamic partition writer prevents GPU memory from being freed during write

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#6963]
ColumnarOutputWriter.write is designed so it closes the incoming batch during the write processing.  The batch gets closed after the GPU has finished encoding the data but before it is written to the distributed filesystem so we can release the GPU semaphore and allow other tasks to start/continue processing.  However the dynamic partition writer `writeBatch` method, which calls the columnar output writer, is written in a way where it expects the caller to close the incoming batch rather than the underlying writer. This means the underlying columnar output writer is unable to properly release the GPU memory of the batch, because there are still outstanding reference counts on the data.  That, in turn, leads to the GPU semaphore being released by the task when there's still unspillable GPU memory allocated by the task.  That can lead to GPU OOM errors, as releasing the semaphore will allow other tasks to start processing and allocating GPU memory, yet the GPU memory has not been properly freed up for the new task.

**Comment by HaoYang670** [comment]
Hi @jlowe, I can work on this.

**Comment by HaoYang670** [comment]
Also, I think we should update the doc of `ColumnarOutputWriter.write` to illustrate the reason of why we close the batch in the `write` function, so that new developers can avoid change that behavior.
