### ISSUE TITLE
[FEA] Support parse_url 

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#6969]
I wish we can support parse_url function.

eg:
```
spark-sql> select parse_url(c_customer_id,'HOST') from tpcds.customer limit 10;

      ! <ParseUrl> parse_url(c_customer_id#1, HOST, false) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.ParseUrl
```

**Comment by sameerz** [comment]
Discuss with the python cudf team whether they could benefit from a kernel for this functionality in libcudf.

**Comment by mattahrens** [comment]
Is it sufficient for the initial implementation that the 2nd and 3rd parameters are literals?

**Comment by viadea** [comment]
From the logs, i think it is good enough. I am also double checking with user.

**Comment by viadea** [comment]
The requirement is to support all 3 input parameter for this function including the KEY.

We need to support PATH, QUERY and HOST.

**Comment by hyperbolic2346** [comment]
Parse_url is now supported for Host with [this PR](https://github.com/NVIDIA/spark-rapids/pull/9845).
