### ISSUE TITLE
[BUG] Partitioned writes release GPU semaphore with unspillable GPU memory

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#6980]
Currently partitioned writes work with the following algorithm:
- Compute the split indices for the different partitions in the batch
- contiguous split the batch
- foreach contiguous table:
   - write out the table

The problem with this algorithm is that currently the "write out the table" step consists of the following steps internally:
- encode the data on the GPU
- transfer the encoded data to the host
- release the GPU semaphore (to avoid holding it while doing a potentially very slow, non-GPU operation in the next step)
- write the encoded data to the distributed filesystem

This means that if there's at least two partitions, we end up releasing the GPU semaphore with unspillable GPU memory still allocated.  This can allow other tasks to start allocating on the GPU and potentially run out of GPU memory due to the inability to free up GPU memory from a task not holding the semaphore.

**Comment by jlowe** [comment]
We need to split up the write logic into discreet methods for encoding the data vs. flushing the data to the filesystem so the writers can be more intelligent about the handling of GPU memory and the semaphore.  For example, if we're doing a simple (non-dynamic) partitioned write, it would be better to do an algorithm like:
- Split the table into partitions on the GPU
- For each table split:
  - encode the split on the GPU
  - transfer the encoded data to the host
  - free the encoded data on the GPU
- Release the GPU semaphore
- For each encoded split in host memory:
  - write the encoded split to the distributed filesystem

**Comment by HaoYang670** [comment]
cc @res-life, could you please take a look?

**Comment by HaoYang670** [comment]
Hi @jlowe, is it possible to use 2 threads, one encodes the data from GPU to host, the other concurrently writes the data from host to storage?

**Comment by res-life** [comment]
Related code: 
https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/sql-plugin/src/main/scala/com/nvidia/spark/rapids/ColumnarOutputWriter.scala#L144
```
GpuSemaphore.releaseIfNecessary(TaskContext.get)
```

Patterns like the following can be rewritten to what Jason said.
```
splits = table.contiguousSplit()
for each split in splits:
  writer.write(split)
```

**Comment by res-life** [comment]
@jlowe `GpuParquetWriter` is responsible to write a `Table` to disk via JNI `ParquetTableWriter`.
IIUC, the encoding and writing the encoded data are both on the cuDF side.
So this issue requires an cuDF PR to support?

**Comment by res-life** [comment]
Sorry I did not notice the `consumer`, do not need cuDF PR.
```
private ParquetTableWriter(ParquetWriterOptions options, HostBufferConsumer consumer) {
```

We can just collect all the `HostBuffer` before writing to the distributed file system.

**Comment by jlowe** [comment]
> is it possible to use 2 or more threads, one encodes the data from GPU to host, others concurrently writes the data from host to storage?

Yes, although this is not required to fix the problem reported here and is more complex.  IMO we should focus on fixing the problem first, and then worry about performance optimizations in followup PRs.

**Comment by abellina** [comment]
I am blocked a bit until https://github.com/NVIDIA/spark-rapids/pull/8243 gets resolved. I need to refactor the same code that @andygrove is touching in his PR in order to implement memory reducing changes and changes where every batch is spillable at a higher level.
