### ISSUE TITLE
[DOC] Update documentation to indicate support for DPP on Databricks

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#6982]
## Report incorrect documentation

Now that issue #3143 is closed, we should update the getting started guide on Databricks to indicate that DPP can be used.

**Location of incorrect documentation**
https://github.com/NVIDIA/spark-rapids/blob/branch-22.12/docs/get-started/getting-started-databricks.md#limitations

**Describe the problems or issues found in the documentation**
The first step indicates to disable DPP which is now unnecessary on Databricks

---

## Report needed documentation

**Describe the documentation you'd like**
The first indicating disable DPP can now be removed.

**Comment by tgravescs** [comment]
make sure to remove the spark.databricks.delta.optimizeWrite.enabled false config as well as that was turned off due to aqe/dpp not working
