### ISSUE TITLE
[BUG] `nz timestamp (MILLIS AND MICROS)` fails on Spark 3.4

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7039]
The unit test `nz timestamp (MILLIS AND MICROS)` fails on Spark 3.4.
```
- nz timestamp (MILLIS AND MICROS) NATIVE *** FAILED ***
  areEqual._1 was false VALUES NOT EQUAL 1970-01-01 00:00:01.0 1970-01-01T00:00:01
  VALUES NOT EQUAL 1970-01-01 00:00:00.000002 1970-01-01T00:00:00.000002 (ParquetFormatScanSuite.scala:264)
...
- nz timestamp (MILLIS AND MICROS) JAVA *** FAILED ***
  areEqual._1 was false VALUES NOT EQUAL 1970-01-01 00:00:01.0 1970-01-01T00:00:01
  VALUES NOT EQUAL 1970-01-01 00:00:00.000002 1970-01-01T00:00:00.000002 (ParquetFormatScanSuite.scala:264)
```

The reason is that on Spark 3.4, the return type is `LocalDateTime`, not `Timestamp`.

To reproduce:
```
mvn clean package -DwildcardSuites=org.apache.spark.sql.rapids.ParquetFormatScanSuite -Dbuildver=340
```

This is not related to our plugin because the test only runs on CPU, but we need to update our tests.

**Comment by HaoYang670** [comment]
cc @revans2

**Comment by revans2** [comment]
Looking. I think this is related to a config that was added that lets you pick what the output type is for these inputs. I will verify that the CPU is doing the same thing and see if I can update the test accordingly.
