### ISSUE TITLE
[BUG] regexp_test and many other test failures

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7041]
Many tests in regexp_test failed in the nightly build along with other tests.  Appears to be related to JNI/cudf code, since rolling back spark-rapids-jni by one day allows the test to pass.  All tests that failed:
- test_cast_timestamp_to_string
- test_json_ts_formats_round_trip
- test_str_to_map_expr_with_all_regex_delimiters
- test_regexp_replace_word
- test_predefined_character_classes
- test_regexp_split_unicode_support
- test_re_replace
- test_re_replace_repetition
- test_re_replace_backrefs
- test_re_replace_anchors
- test_re_replace_backrefs_escaped
- test_re_replace_escaped
- test_re_replace_null
- test_regex_replace
- test_regex_replace_chartacter_set_negated
- test_word_boundaries
- test_character_classes
- test_regexp_hexadecimal_digits
- test_regexp_whitespace
- test_regexp_horizontal_vertical_whitespace
- test_regexp_linebreak
- test_regexp_replace_digit
- test_window_ride_along
- test_cast_struct_to_string

**Comment by jlowe** [comment]
Tracked this down to rapidsai/cudf#11927.  The tests pass on the commit without this change, holding the plugin source constant.

**Comment by jlowe** [comment]
Verified this is fixed by the change pending in rapidsai/cudf#12119.

**Comment by pxLi** [comment]
Confirmed the cudf fix works after new JNI build, closing this ticket
