### ISSUE TITLE
[FEA] EvalMode.TRY Spark 3.4.0 testing and support

### ISSUE THREAD

**Issue by rwlee** [NVIDIA/spark-rapids#7046]
Follow on issue from #7025 

**Is your feature request related to a problem? Please describe.**
With the merging of Cast and ANSI Cast in Spark 3.4.0 the behavior of cast has changed. Supporting try cast or falling back to CPU when try cast is configured needs to be investigated/tested.

**Comment by NVnavkumar** [comment]
Fixed in #8179
