### ISSUE TITLE
[SPARK-39432][BUG] The test `test_array_element_at_zero_index_fail` fails on Spark 3.4

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7066]
**Describe the bug**
The test `test_array_element_at_zero_index_fail` fails on Spark 3.4.
Related Spark ticket: https://issues.apache.org/jira/browse/SPARK-39432

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.
```bash
./run_pyspark_from_build.sh -k array_test.py
```

**Expected behavior**
The test should pass.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by HaoYang670** [comment]
Another ticket related to this: https://issues.apache.org/jira/browse/SPARK-40205

**Comment by jlowe** [comment]
Fixed by #7075
