### ISSUE TITLE
[FEA] Add a shim layer for Spark 3.2.4

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#7094]
The branch-3.2 is now Spark 3.2.4, a shim layer is needed to support it.

**Comment by sameerz** [comment]
Based on https://spark.apache.org/versioning-policy.html "Maintenance releases and EOL" , 
> Feature release branches will, generally, be maintained with bug fix releases for a period of 18 months. 

Based on this, we are unlikely to see a Spark 3.2.4.

**Comment by tgravescs** [comment]
looks like Apache is going to do one last 3.2.4 release on the 3.2.x line
