### ISSUE TITLE
[FEA] Databricks build and test scripts should compute BASE_SPARK_VERSION

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7096]
**Is your feature request related to a problem? Please describe.**
In order to use the scripts under jenkins/databricks, one must first remember to set BASE_SPARK_VERSION (and of course know what proper value to use when setting it).  This is easy to forget and requires developers to know what values correspond to the various Databricks versions.

**Describe the solution you'd like**
We're already automatically detecting which Databricks version we're on in our shim provider by examining the value of `spark.databricks.clusterUsageTags.sparkVersion` in /databricks/common/conf/deploy.conf. The Databricks build and test scripts could do the same.  We can then maintain the mapping of Databricks version to proper Spark base version in the scripts directly rather than requiring a developer to maintain the lookup table in their head.

**Comment by gerashegalov** [comment]
I noticed the same, and proposed this PR #7097
