### ISSUE TITLE
[DOC] Databricks container doc put usage first

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7124]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/NVIDIA/spark-rapids-container/blob/main/Databricks/README.md

I think we should rearrange this to put the usage first and then after it put build instructions if they are needed. Most people should not need to build it.

**Comment by GaryShen2008** [comment]
I have updated the description to point to the usage section. Close.
