### ISSUE TITLE
[BUG] Followup to AQE issues with reused columnar broadcast exchanges

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#7133]
**Describe the bug**
Issue #7037 describes a scenario that causes a columnar (GPU) broadcast exchange under a GPU broadcast join to be reused in a broadcast join that falls back to running on the CPU for some reason.  PR #7110 addresses this by adding a `GpuBroadcastToRowExec` in order pull the broadcast data from the GPU to CPU to be used in the CPU broadcast join.  

This is a follow up issue to address a few still unresolved issues:

* The integration test relies on a specific scenario that falls back one of the joins to CPU while the other runs on the GPU. We need a way to make this scenario more repeatable by reliably falling back one of the joins to the CPU because if the underlying plugin limitation used in the test is fixed to run on the GPU (in fact the underlying limitation is captured in #7030). 

* We still don't have a scenario to test `HashedRelationBroadcastMode` which would happen if a BroadcastHashJoin is used instead of a BroadcastNestedLoopJoin

**Comment by mimaomao** [comment]
Will we fix this issue in 22.12?

**Comment by NVnavkumar** [comment]
From #6978, we now have a scenario that triggers the HashedRelationBroadcastMode case. Currently, we need GpuBroadcastToRow to also handle output that sends Broadcast[HashedRelation] in addition to Broadcast[Array[InternalRow]].
