### ISSUE TITLE
[AUDIT] Investigate support for correlated subqueries that yield non-deterministic Scalars 

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#7146]
**Description**
[SPARK-40862](https://github.com/apache/spark/commit/3feddec3d9) makes a change to how Spark handles/rewrites correlated subqueries that yield single (non-deterministic) rows.

It would be good to check the extent to `spark-rapids` supports correlated subqueries in general, and single row subqueries in particular.

The [query](https://github.com/apache/spark/commit/3feddec3d9#diff-adc3f627771dab40517626755090a97ce8d6ab3cec413b8fb88627e7049414e0) added to `SubquerySuite.scala` is a non-starter for `spark-rapids`:
```scala
sql("CREATE TEMP VIEW t1 AS SELECT ARRAY('a', 'b') a")
val func = udf(() => "a")
spark.udf.register("func", func.asNondeterministic())
// ...
sql("""
￼   |SELECT (
￼   |  SELECT array_sort(a, (i, j) -> rank[i] - rank[j])[0] || str AS sorted
￼   |  FROM (SELECT MAP('a', 1, 'b', 2) rank, func() AS str)
￼   |) 
    |FROM t1
￼   |""".stripMargin)
```
We'd need to find a representative query that stands a chance of acceleration.

**Comment by revans2** [comment]
I am not sure that this impacts us at all. The changes for this PR https://github.com/apache/spark/pull/38336/files were in a single logical plan optimization rule and also in tests for that rule. The fact that we might be bad at running the subquery really is a performance issue that is a separate issue entirely.

If I missed something please let me know and reopen this.
