### ISSUE TITLE
Stop building against any Spark snapshot versions in premerge script

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7159]
**Is your feature request related to a problem? Please describe.**
Spark snapshot versions can change at a whim, and those changes can break the plugin build.  When that happens, the premerge script fails, blocking any development until the snapshot version is fixed (or the build stubbed out temporarily).

**Describe the solution you'd like**
Builds against snapshot versions should be non-blocking Github action builds in the build matrix (I believe this is already happening, or something close to it).  That way the developer can see a build failed against a snapshot version, but it doesn't block merging the PR.  The premerge script should not build against any snapshot versions, leave that to the non-blocking build matrix. 
 Nightly scripts will still build and test against snapshot versions and report failures as normal.

**Comment by pxLi** [comment]
+10000, I will update this script next week
