### ISSUE TITLE
[BUG] Cast String to TimeStamp issues

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#716]
**Describe the bug**

We recently discovered that the config to turn off the string to timestamp cast was not being used.  We fixed that with https://github.com/NVIDIA/spark-rapids/pull/705.

But while investigating that it seemed like a few things might be off. the format we are using and is used in CUDF is "%Y-%m-%dT%H:%M:%SZ%f". Based on what we support it seems like the ms section should be %SZ.%f.  The pattern that we didn't match on but worked on the CPU was just: 2017-11-29 20:00:35. Ideally we would support this.

I think the regex's in this case are a pretty high performance overhead as well though so perhaps we should figure out different way to handle.

**Comment by tgravescs** [comment]
Note I have seen other formats for strings - such as 2020-09-07T01:05:57.840+0000
  that we also don't support.

**Comment by sameerz** [comment]
This is related to issue #987

**Comment by andygrove** [comment]
This is also related to https://github.com/NVIDIA/spark-rapids/issues/1117 which I am currently working on

**Comment by andygrove** [comment]
> Note I have seen other formats for strings - such as 2020-09-07T01:05:57.840+0000
> that we also don't support.

@tgravescs The main issue raised in this issue (using the wrong cuDF timestamp formats) was resolved by https://github.com/NVIDIA/spark-rapids/pull/1718 and there is now a separate issue for reducing the regex overhead (https://github.com/NVIDIA/spark-rapids/issues/1738).

We do not support the format `2020-09-07T01:05:57.840+0000` and this is documented. Should we file a separate issue for adding support?

**Comment by tgravescs** [comment]
yes I think we should file one to say supported more formats

**Comment by andygrove** [comment]
I filed https://github.com/NVIDIA/spark-rapids/issues/1748 for supporting additional formats.
