### ISSUE TITLE
[BUG] Fix integration test failures on Databricks 11.3

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#7184]
**Describe the bug**

Contingent on the final shape of #7152 this is a preliminary list of integration tests that needs to be fixed for Databricks 11.3

- [ ] test_abs_ansi_no_overflow_day_time_interval
- [ ] test_abs_ansi_overflow_day_time_interval
- [ ] test_addition
- [ ] test_addition_ansi_no_overflow
- [ ] test_add_overflow_with_ansi_enabled
- [ ] test_agg_nested_array
- [ ] test_agg_nested_map
- [ ] test_agg_nested_struct
- [ ] test_aqe_join_parquet
- [ ] test_aqe_join_parquet_batch
- [ ] test_aqe_join_reused_exchange_inequality_condition
- [ ] test_aqe_skew_join
- [ ] test_aqe_struct_self_join
- [ ] test_array_contains
- [ ] test_array_element_at_ansi_fail_invalid_index
- [ ] test_array_element_at_zero_index_fail
- [ ] test_array_item
- [ ] test_array_item_ansi_fail_invalid_index
- [ ] test_array_item_ansi_not_fail_all_null_data
- [ ] test_array_item_with_strict_index
- [ ] test_array_max_q1
- [x] test_avg_fallback_when_ansi_enabled
- [x] test_broadcast_join_with_condition_ast_op_fallback
- [x] test_broadcast_join_with_condition_ast_type_fallback
- [x] test_broadcast_nested_loop_join_with_conditionals_build_left_fallback
- [x] test_broadcast_nested_loop_join_with_condition_fallback
- [x] test_broadcast_nested_loop_with_conditionals_build_right_fallback
- [x] test_buckets_write_fallback
- [ ] test_cast_neg_to_decimal_err
- [x] test_cast_string_date_fallback
- [x] test_cast_string_timestamp_fallback
- [ ] test_ceil_scale_zero
- [ ] test_conditional_with_side_effects_array_index
- [x] test_count_fallback_when_ansi_enabled
- [x] test_cpu_fallback_map_scalars
- [x] test_csv_fallback
- [x] test_csv_save_as_table_fallback
- [ ] test_csv_scan_with_hidden_metadata_fallback
- [x] test_date_format_f
- [x] test_date_format_f_incompat
- [x] test_date_format_maybe
- [x] test_date_formats_round_trip
- [ ] test_day_time_interval_divided_by_zero
- [ ] test_day_time_interval_divided_by_zero_scalar
- [ ] test_day_time_interval_division_nan
- [ ] test_day_time_interval_division_number_no_overflow1
- [ ] test_day_time_interval_division_number_no_overflow2
- [ ] test_day_time_interval_division_overflow
- [ ] test_day_time_interval_division_round_overflow
- [ ] test_day_time_interval_multiply_number
- [ ] test_day_time_interval_scalar_divided_by_zero
- [ ] test_decimal_running_sum_window
- [ ] test_decimal_running_sum_window_no_part
- [ ] test_disorder_read_schema
- [ ] test_div_by_zero_ansi
- [ ] test_division
- [ ] test_division_mixed
- [ ] test_division_mixed_larger_dec
- [ ] test_div_overflow_exception_when_ansi
- [ ] test_dpp_bypass
- [ ] test_dpp_empty_relation
- [ ] test_dpp_from_swizzled_hash_keys
- [ ] test_dpp_like_any
- [ ] test_dpp_reuse_broadcast_exchange
- [ ] test_dpp_reuse_broadcast_exchange_cpu_scan
- [ ] test_dpp_skip
- [ ] test_dpp_via_aggregate_subquery
- [ ] test_element_at_map_string_col_keys_ansi_fail
- [ ] test_empty_broadcast_hash_join
- [ ] test_existence_join_in_broadcast_nested_loop_join
- [x] test_explain_only_sortmerge_join
- [x] test_floor_scale_nonzero
- [ ] test_floor_scale_zero
- [x] test_from_utc_timestamp_fallback
- [ ] test_get_array_struct_fields
- [ ] test_get_map_value_string_col_keys_ansi_fail
- [ ] test_groupby_std_variance
- [ ] test_groupby_std_variance_nulls
- [ ] test_groupby_std_variance_partial_replace_fallback
- [ ] test_grouped_sliding_window_array
- [ ] test_hash_avg_nulls_partial_only
- [x] test_hash_groupby_approx_percentile_partial_fallback_to_cpu
- [ ] test_hash_groupby_collect_partial_replace_with_distinct_fallback
- [x] test_hash_grpby_avg_nulls_ansi
- [ ] test_hash_grpby_pivot
- [ ] test_hash_grpby_pivot_without_nans
- [ ] test_hash_multiple_grpby_pivot
- [ ] test_hash_pivot_groupby_duplicates_fallback
- [x] test_hash_reduction_avg_nulls_ansi
- [ ] test_hash_reduction_pivot_with_nans
- [ ] test_hash_reduction_pivot_without_nans
- [x] test_hive_text_default_disabled
- [x] test_hive_text_fallback_for_unsupported_types
- [ ] test_int_division_mixed
- [x] test_json_read_invalid_dates
- [x] test_json_read_valid_dates
- [ ] test_map_arrow_apply_udf
- [ ] test_map_element_at_ansi_fail
- [ ] test_mod_pmod_by_zero
- [ ] test_multiplication
- [ ] test_multiplication_ansi_enabled
- [ ] test_multiplication_ansi_overflow
- [x] test_multiplication_fallback_when_ansi_enabled
- [ ] test_multiplication_mixed
- [x] test_nested_part_fallback
- [x] test_optimized_hive_bucketed_fallback
- [x] test_optimized_hive_ctas_configs_fallback
- [x] test_optimized_hive_ctas_options_fallback
- [x] test_orc_fallback
- [ ] test_orc_scan_with_hidden_metadata_fallback
- [x] test_orc_write_compression_fallback
- [x] test_parquet_fallback
- [ ] test_parquet_read_daytime_interval_cpu_file
- [ ] test_parquet_read_daytime_interval_gpu_file
- [ ] test_parquet_scan_with_hidden_metadata_fallback
- [x] test_parquet_write_compression_fallback
- [x] test_parquet_write_encryption_hadoopconfig_fallback
- [x] test_parquet_write_encryption_option_fallback
- [x] test_parquet_write_encryption_runtimeconfig_fallback
- [x] test_parquet_write_legacy_fallback
- [x] test_parquet_writeLegacyFormat_fallback
- [x] test_pmod_fallback
- [ ] test_pred_push_round_trip
- [ ] test_reduction_nested_array
- [ ] test_reduction_nested_map
- [ ] test_reduction_nested_struct
- [x] test_regexp_memory_fallback
- [x] test_re_replace_issue_5492
- [ ] test_right_broadcast_nested_loop_join_without_condition_empty_small_batch
- [x] test_rlike_fallback_empty_group
- [x] test_rlike_fallback_possessive_quantifier
- [x] test_round_robin_sort_fallback
- [ ] test_round_trip_for_interval
- [ ] test_running_float_sum_no_part
- [ ] test_running_window_function_exec_for_all_aggs
- [ ] test_scalar_subquery_array
- [ ] test_scalar_subquery_basics
- [ ] test_scalar_subquery_map
- [ ] test_scalar_subquery_struct
- [ ] test_simple_get_map_value_with_strict_index
- [x] test_single_nested_orderby_fallback_for_nullorder
- [x] test_single_nested_orderby_with_limit_fallback
- [ ] test_single_nested_orderby_with_processing_and_limit
- [x] test_sort_binary_fallback
- [x] test_sortmerge_join_struct_as_key_fallback
- [x] test_sortmerge_join_with_condition_ast_op_fallback
- [x] test_sortmerge_join_with_condition_ast_type_fallback
- [x] test_sortmerge_join_wrong_key_fallback
- [ ] test_special_decimal_division
- [x] test_split_regexp_disabled_fallback
- [x] test_split_unsupported_fallback
- [ ] test_struct_get_item
- [ ] test_struct_self_join
- [ ] test_subtraction
- [ ] test_subtraction_ansi_no_overflow
- [ ] test_subtraction_overflow_with_ansi_enabled
- [x] test_sum_fallback_when_ansi_enabled
- [ ] test_timeadd_daytime_column
- [ ] test_union_by_missing_field_name_in_arrays_structs
- [ ] test_union_struct_missing_children
- [ ] test_window_aggregate_udf_array_from_python
- [ ] test_window_aggregations_for_big_decimal_ranges
- [ ] test_window_aggregations_for_decimal_ranges
- [ ] test_window_aggs_for_rows
- [x] test_window_aggs_lag_ignore_nulls_fallback
- [x] test_window_aggs_lead_ignore_nulls_fallback
- [ ] test_window_ride_along
- [ ] test_window_running
- [ ] test_window_running_float_decimal_sum
- [ ] test_window_running_no_part
- [ ] test_window_running_rank
- [ ] test_window_running_rank_no_part
- [x] test_write_hive_bucketed_table_fallback
- [ ] test_delta_zorder
- [ ] udf_test.py
- [ ] udf_cudf_test.py

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.

```bash
./jenkins/databricks/test.sh > /tmp/dbtest.log
< /tmp/dbtest.log ansi2txt | \
  grep 'FAILED' | \
  cut -d/  -f 6 | \
  cut -d: -f 3 | \
  cut -d\[ -f 1 | \
  cut -d' ' -f 1 | \
  sort -u | \
  xargs printf '- [ ] %s\n'
```

**Expected behavior**

Integration tests should pass DB 11.3 unless can be skipped in a clearly documented way.

**Environment details (please complete the following information)**
Databricks 11.3

**Additional context**

**Comment by nartal1** [comment]
Will create a PR to XFAIL above tests for DB-11.3 so that we can get the DB-11.3 shim in.

**Comment by nartal1** [comment]
Closing this in lieu of https://github.com/NVIDIA/spark-rapids/issues/7325
