### ISSUE TITLE
[FEA] ParseToTimestamp

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#72]
**Is your feature request related to a problem? Please describe.**
It would be good to support the `to_timestamp` SQL function.

**Comment by revans2** [comment]
`ParseToTimestamp` at least in Spark 3.1 is runtime replaceable and gets turned into a combination of casting to a Timestamp and `GetTimestamp` which is being added right now as a part of #1742.  Once #1742 goes in we can probably close this.

**Comment by nartal1** [comment]
Added simple tests which includes `to_timestamp` in https://github.com/NVIDIA/spark-rapids/pull/1742

**Comment by nartal1** [comment]
https://github.com/NVIDIA/spark-rapids/pull/1742 is merged. Closing this.
