### ISSUE TITLE
[BUG] Explicitly check if the platform is supported

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#7208]
**Describe the bug**
https://github.com/NVIDIA/spark-rapids/discussions/7205 was filed because a user tried to use the plugin with an unsupported GPU.  The error message was very confusing.  We should have some explicit check on startup before RMM runs that will verify that the GPU meets the minimum requirements and returns a clear error if it cannot.

**Comment by jlowe** [comment]
This involves updating the plugin to call cudf's `Cuda.getComputeCapabilityMajor` method in the Java bindings and throw an exception if the device compute capability is too low (i.e.: < 6).
