### ISSUE TITLE
[BUG] The PCBS tests fail on Spark 340

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7216]
**Describe the bug**

**Steps/Code to reproduce bug**
1. `export PYSP_TEST_spark_sql_cache_serializer = "com.nvidia.spark.ParquetCachedBatchSerializer"` in `run_pyspark_from_build.sh`
2. Run `./run_pyspark_from_build.sh -k cache_test.py`
3. Get the test failure result:
```
======== 476 failed, 104 passed, 15737 deselected in 274.54s (0:04:34) =========
```

**Expected behavior**
The tests should pass.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by HaoYang670** [comment]
cc @nartal1

**Comment by HaoYang670** [comment]
One common error message is 
```
java.lang.IllegalArgumentException: For input string: "null"
```

**Comment by nartal1** [comment]
Related to https://github.com/apache/spark/pull/36158
