### ISSUE TITLE
[BUG] GpuFileSourceScanExec always generates all partition columns

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7226]
When reading from a partitioned table, GpuFileSourceScanExec is always generating columns for all partitioned columns in the underlying relation, as we blindly pass relation.partitionSchema as the partitionSchema to use.  It would be nice to only use the partition columns needed in the query, but unfortunately Spark appears to always ask for all partition columns even if the query doesn't need them.  Partition column value generation is relatively cheap for the CPU version, but we splat out the partition scalars to full columns on the GPU.  This wastes time and space for any partition columns that are not really needed by the query,

Since Spark appears to not be pruning the partition columns from FileSourceScanExec.output in the CPU version, we may need a more sophisticated examination of the plan downstream from FileSourceScanExec to know which partition columns, if any, are really necessary to manifest as columns.

**Comment by firestarman** [comment]
Checked several cases, seems Spark will use the `ProjectExec` to prune the partition columns accordingly.

```
scala> df.printSchema
root
 |-- a: integer (nullable = true)
 |-- b: string (nullable = true)
 |-- c: integer (nullable = true)

scala> df.groupBy("b").agg(max($"a")).collect
22/12/14 09:22:57 WARN GpuOverrides: 
*Exec <HashAggregateExec> will run on GPU
  *Expression <AggregateExpression> max(a#0) will run on GPU
    *Expression <Max> max(a#0) will run on GPU
  *Expression <Alias> max(a#0)#361 AS max(a)#362 will run on GPU
  *Exec <ShuffleExchangeExec> will run on GPU
    *Partitioning <HashPartitioning> will run on GPU
    *Exec <HashAggregateExec> will run on GPU
      *Expression <AggregateExpression> partial_max(a#0) will run on GPU
        *Expression <Max> max(a#0) will run on GPU
      *Exec <ProjectExec> will run on GPU
        *Exec <FileSourceScanExec> will run on GPU

res40: Array[org.apache.spark.sql.Row] = Array([s2,7], [s3,4], [s1,6])

scala> df.select("a").filter("a != 1").collect
22/12/14 09:24:02 WARN GpuOverrides: 
*Exec <ProjectExec> will run on GPU
  *Exec <FilterExec> will run on GPU
    *Expression <And> (isnotnull(a#0) AND NOT (a#0 = 1)) will run on GPU
      *Expression <IsNotNull> isnotnull(a#0) will run on GPU
      *Expression <Not> NOT (a#0 = 1) will run on GPU
        *Expression <EqualTo> (a#0 = 1) will run on GPU
    *Exec <FileSourceScanExec> will run on GPU

res41: Array[org.apache.spark.sql.Row] = Array([5], [6], [7], [2], [4], [3])
```

**Comment by firestarman** [comment]
> we can do something more targeted by explicitly checking for a ProjectExec immediately after the FileSourceScanExec and check for partition columns that are not referenced by any expression or output column in the project.

Yeah, that's what I am going to do for the first step according to what I have found so far.  We can use the output (or projectList) of the first ProjectExec after the FileSourceScanExec to prune the partition columns when doing the scan.



> This may be as simple as examining the FileSourceScanExec's parent node in the plan and filtering the partition schema based on the references and output in that parent node.

The FileSourceScanExec's parent node may not drop the parition columns that not required, e.g. the second filter case I post above. The FilterExec will output all the paritition columns, same as the FileSourceScanExec.

**Comment by jlowe** [comment]
> The FileSourceScanExec's parent node may not drop the parition columns that not required, e.g. the second filter case I post above. The FilterExec will output all the paritition columns the same as the FileSourceScanExec.

In that case, we should also adjust the FilterExec to not advertise the unused partition columns.  That could be the followup approach after the project, as filtering after a load will be _very_ common, possibly more common than just the project-only case.
