### ISSUE TITLE
[FEA] Update GpuHashAggregate to use OOM retry framework

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#7256]
**Is your feature request related to a problem? Please describe.**
This is very similar to https://github.com/NVIDIA/spark-rapids/issues/7254

**Describe the solution you'd like**
For hash aggregate operators we can run into situations where aggregates can use an exceptionally large amount of GPU memory, enough that we may need more memory than we get in the default lease.

We should do similar tasks as we are going to do with GpuWindowExec.

 * [ ] Do a high water mark estimation on how much memory will be needed in the worst case to complete the hash aggregate, given the input sizes and the aggregations being done.
 * [ ] Request a higher lease if needed.
 * [ ] Experiment with RMM high water mark tracking to see how good our estimate is, and verify that we are not missing something
 * [ ] Write scale testing to verify that our estimation code does not under estimate the amount of memory needed.

**Comment by abellina** [comment]
This was done in https://github.com/NVIDIA/spark-rapids/pull/7771
