### ISSUE TITLE
[BUG] Generated supported data source file is inaccurate for write data formats

### ISSUE THREAD

**Issue by mattahrens** [NVIDIA/spark-rapids#7284]
Generated [supportedDatasSource.csv](https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/tools/src/main/resources/supportedDataSource.csv) does not match the supporter operators listed in our documentation: https://nvidia.github.io/spark-rapids/docs/supported_ops.html.

Symptom is that the qualification tool will list write formats as unsupported even though they are.

**Comment by tgravescs** [comment]
so this is partly right, the NA for the write formats is actually intentional because we can't determine that from the eventlog.  It seems there is a bug in generating all the write types though and possibly on the Qualification tool side if its looking at the NA stuff. Needs more investigation.

**Comment by mattahrens** [comment]
Looks like root cause is parsing issue in the qualification tool where a column that has embedded commas is parsed incorrectly.
