### ISSUE TITLE
Qualification tool should be tested against queries with Delta Lake writes

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7294]
#7288 adds initial support for GPU acceleration of Delta Lake writes.  The qualification tool should be tested against queries with Delta Lake writes and checked that it is performing as expected with these queries.  This includes potentially adjusting the expected speedup of Delta Lake write operations that are expected to be accelerated.
```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/spark-rapids-tools/issues/323
- [ ] https://github.com/NVIDIA/spark-rapids-tools/issues/370
```

**Comment by jlowe** [comment]
Note that this has more general ramifications outside of Delta Lake writes.  Some Delta Lake writes happen to be implemented in terms of ExecutedCommandExec, but we do not support all forms ExecutedCommandExec can take.  It's an exec that is used for a very wide range of operations, and therefore a simple speedup factor would not make sense for it.  The tool will need to examine the command associated with ExecutedCommandExec to know whether the RAPIDS Accelerator could support it and what type of speedup factor might be appropriate for that command.

**Comment by amahussein** [comment]
Qualification tool marked delta operators as supported
