### ISSUE TITLE
[FEA] Support accelerated write to Hive delimited text

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#7314]
The Spark RAPIDS plugin does not currently support writing Hive delimited text files. It would be good to add this, so as to support queries like:

```sql
CREATE TABLE my_text_table AS SELECT ...
```

This should accelerate the write to `my_text_table`. For the moment, the supported types can be kept identical to those that have read support. i.e. All types except:
1. `STRUCT`
2. `ARRAY`
3. `MAP`
4. `BINARY`

**Comment by mythrocks** [comment]
This will involve adding CUDF JNI support for writing CSV files, assuming that this follows the same convention as the read path in its implementation.

**Comment by revans2** [comment]
If we are not doing an escape I think we can do a lot of this without that.  We can cast the columns to strings, and then concat the strings with the separator in between them, then finally concat the lines with a line separator.

The biggest problem is going to be with how we write out things like decimal values and floats.

**Comment by revans2** [comment]
Specifically using the APIs at

https://github.com/rapidsai/cudf/blob/b14f1dcce526fae74b4b41b1a5e431bf493925ba/java/src/main/java/ai/rapids/cudf/ColumnVector.java#L583

and

https://github.com/rapidsai/cudf/blob/b14f1dcce526fae74b4b41b1a5e431bf493925ba/java/src/main/java/ai/rapids/cudf/ColumnView.java#L1841

**Comment by mythrocks** [comment]
Argh. This is a dupe of #6419. I'll update there.
