### ISSUE TITLE
[BUG] Support DayTimeIntervalType in Databricks-11.3 to fix integration tests

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7324]
**Describe the bug**
Below tests are failing due to missing DayTimeIntervalType in 330db shim. 

- [ ] test_parquet_read_daytime_interval_cpu_file
- [ ] test_parquet_read_daytime_interval_gpu_file
- [ ] test_round_trip_for_interval
- [x] test_abs_ansi_no_overflow_day_time_interval
- [x] test_abs_ansi_overflow_day_time_interval
- [x] test_day_time_interval_division_nan
- [x] #7387
- [x] test_day_time_interval_division_number_no_overflow2
- [x] test_day_time_interval_division_round_overflow
- [x] test_day_time_interval_multiply_number
- [x] test_timeadd_daytime_column

Reason for failure(Exec name changes but the reason is same) - 
```
!Exec <FileSourceScanExec> cannot run on GPU because unsupported data types in output: DayTimeIntervalType(0,3) [_c1#5]
```

**Steps/Code to reproduce bug**
Build and run integration tests on Databricks-11.3 environment.
Build  steps - Pull in this PR locally if not merged - https://github.com/NVIDIA/spark-rapids/pull/7152 
                      /home/ubuntu/spark-rapids$ ./jenkins/databricks/build.sh

Test steps:  Modify the test.sh under jenkins/databrikcs to run a specific test.
                Example: Comment all lines starting from `export TEST_PARALLEL=${TEST_PARALLEL:-4}` in the file and add below lines:
                ```
                export TEST_PARALLEL=${TEST_PARALLEL:-1}
                TEST_NAME=$1
                bash /home/ubuntu/spark-rapids/integration_tests/run_pyspark_from_build.sh -k $TEST_NAME
               ```

Run Test -  `./jenkins/databricks/test.sh test_day_time_interval_division_nan `

**Expected behavior**
All above tests should pass on Databricks-11.3 shim

**Environment details (please complete the following information)**
Databricks-11.3 runtime.

**Additional context**

**Comment by rwlee** [comment]
#7370 resolves all issues except

- [ ] test_parquet_read_daytime_interval_cpu_file
- [ ] test_parquet_read_daytime_interval_gpu_file
- [ ] test_round_trip_for_interval
