### ISSUE TITLE
[BUG] Databricks-11.3 integration test failing due to IllegalStateException: the broadcast must be on the GPU too

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7328]
**Describe the bug**
Below integration tests are failing due to broadcast not being on GPU.

- [ ] test_aqe_join_parquet
- [ ] test_aqe_join_parquet_batch
- [ ] test_aqe_join_reused_exchange_inequality_condition
- [ ] test_aqe_skew_join
- [ ] test_aqe_struct_self_join
- [ ] test_dpp_bypass
- [ ] test_dpp_empty_relation
- [ ] test_dpp_from_swizzled_hash_keys
- [ ] test_dpp_like_any
- [ ] test_dpp_reuse_broadcast_exchange
- [ ] test_dpp_reuse_broadcast_exchange_cpu_scan
- [ ] test_dpp_skip
- [ ] test_dpp_via_aggregate_subquery
- [ ] test_empty_broadcast_hash_join
- [ ] test_existence_join_in_broadcast_nested_loop_join
- [ ] test_right_broadcast_nested_loop_join_without_condition_empty_small_batch

```
E                   : java.lang.IllegalStateException: the broadcast must be on the GPU too
com.nvidia.spark.rapids.GpuBroadcastJoinMeta.verifyBuildSideWasReplaced(GpuBroadcastJoinMeta.scala:52)
```

**Steps/Code to reproduce bug**
Build and run integration tests on Databricks-11.3 environment.
Build  steps - Pull in this PR locally if not merged - https://github.com/NVIDIA/spark-rapids/pull/7152 
                      /home/ubuntu/spark-rapids$ ./jenkins/databricks/build.sh

Test steps:  Modify the test.sh under jenkins/databrikcs to run a specific test.
                Example: Comment all lines starting from `export TEST_PARALLEL=${TEST_PARALLEL:-4}` in the file and add below lines:
                ```
                export TEST_PARALLEL=${TEST_PARALLEL:-1}
                TEST_NAME=$1
                bash /home/ubuntu/spark-rapids/integration_tests/run_pyspark_from_build.sh -k $TEST_NAME
               ```

Run Test -  `./jenkins/databricks/test.sh test_aqe_join_parquet`

**Expected behavior**
All above tests should pass on Databricks-11.3 shim

**Environment details (please complete the following information)**
Databricks-11.3 runtime.

**Additional context**

**Comment by nartal1** [comment]
Root cause: This happens when AQE is enabled. There is no BroadcastExchange in the SparkPlan of Databricks-11.3 rather it's `Exchange SinglePartition` now. Will check how to make the query run on GPU as we support these Execs as well.

On DB-10.4: 
```
== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- HashAggregate(keys=[], functions=[finalmerge_count(merge count#96L) AS count(1)#92L])
   +- Exchange SinglePartition, ENSURE_REQUIREMENTS, [id=#116]
      +- HashAggregate(keys=[], functions=[partial_count(1) AS count#96L])
         +- Project
            +- BroadcastHashJoin [a#88], [a#90], Inner, BuildRight, false
               :- Filter isnotnull(a#88)
               :  +- FileScan parquet [a#88] Batched: true, DataFilters: [isnotnull(a#88)], Format: Parquet, Location: InMemoryFileIndex(1 paths)[dbfs:/home/ubuntu/parquet-files/df1-parquet], PartitionFilters: [], PushedFilters: [IsNotNull(a)], ReadSchema: struct<a:int>
               +- BroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, false] as bigint)),false), [id=#111]
                  +- Filter isnotnull(a#90)
                     +- FileScan parquet [a#90] Batched: true, DataFilters: [isnotnull(a#90)], Format: Parquet, Location: InMemoryFileIndex(1 paths)[dbfs:/home/ubuntu/parquet-files/df2-parquet], PartitionFilters: [], PushedFilters: [IsNotNull(a)], ReadSchema: struct<a:in
```
On DB-11.3:

```
AdaptiveSparkPlan isFinalPlan=false
+- HashAggregate(keys=[], functions=[finalmerge_count(merge count#265L) AS count(1)#261L])
   +- Exchange SinglePartition, ENSURE_REQUIREMENTS, [plan_id=633]
      +- HashAggregate(keys=[], functions=[partial_count(1) AS count#265L])
         +- Project
            +- BroadcastHashJoin [a#257], [a#259], Inner, BuildRight, false
               :- Filter isnotnull(a#257)
               :  +- FileScan parquet [a#257] Batched: true, DataFilters: [isnotnull(a#257)], Format: Parquet, Location: InMemoryFileIndex(1 paths)[dbfs:/home/ubuntu/parquet-files/df1-parquet], PartitionFilters: [], PushedFilters: [IsNotNull(a)], ReadSchema: struct<a:int>
               +- Exchange SinglePartition, EXECUTOR_BROADCAST, [plan_id=628]
                  +- Filter isnotnull(a#259)
                     +- FileScan parquet [a#259] Batched: true, DataFilters: [isnotnull(a#259)], Format: Parquet, Location: InMemoryFileIndex(1 paths)[dbfs:/home/ubuntu/parquet-files/df2-parquet], PartitionFilters: [], PushedFilters: [IsNotNull(a)], ReadSchema: struct<a:int>
```

**Comment by jlowe** [comment]
After #7363, test_aqe_struct_self_join is now also failing with this error instead of the require assertion originally reported in #7352.  Updated the tasklist above to add that test.
