### ISSUE TITLE
[BUG]  Fix integration tests in Databricks-11.3 runtime by removing config spark.sql.ansi.strictIndexOperator

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7347]
**Describe the bug**
Below tests are failing due to this config -  spark.sql.ansi.strictIndexOperator in 330db shim. 

- [ ] test_element_at_map_string_col_keys_ansi_fail - Similar to https://github.com/NVIDIA/spark-rapids/pull/7095
- [ ] test_map_element_at_ansi_fail                          - Similar to https://github.com/NVIDIA/spark-rapids/pull/7095
- [ ] test_get_map_value_string_col_keys_ansi_fail  - Similar to https://github.com/NVIDIA/spark-rapids/pull/7095 
- [ ] test_simple_get_map_value_with_strict_index  - Similar to https://github.com/NVIDIA/spark-rapids/pull/7095
- [ ] test_array_element_at_ansi_fail_invalid_index    - Similar to https://github.com/NVIDIA/spark-rapids/pull/7067
- [ ] test_array_item_with_strict_index                       - Similar to https://github.com/NVIDIA/spark-rapids/pull/7067

Reason:
```
E               pyspark.sql.utils.AnalysisException: The SQL config 'spark.sql.ansi.strictIndexOperator' was removed in the version 3.4.0. This was an internal configuration. It is not needed anymore since Spark SQL always returns null when getting a map value with a non-existing key. See SPARK-40066 for more details.

```
**Steps/Code to reproduce bug**
Build and run integration tests on Databricks-11.3 environment.
Build  steps - Pull in this PR locally if not merged - https://github.com/NVIDIA/spark-rapids/pull/7152 
                      /home/ubuntu/spark-rapids$ ./jenkins/databricks/build.sh

Test steps:  Modify the test.sh under jenkins/databrikcs to run a specific test.
                Example: Comment all lines starting from `export TEST_PARALLEL=${TEST_PARALLEL:-4}` in the file and add below lines:
                ```
                export TEST_PARALLEL=${TEST_PARALLEL:-1}
                TEST_NAME=$1
                bash /home/ubuntu/spark-rapids/integration_tests/run_pyspark_from_build.sh -k $TEST_NAME
               ```

Run Test -  `./jenkins/databricks/test.sh test_element_at_map_string_col_keys_ansi_fail  `

**Expected behavior**
All above tests should pass on Databricks-11.3 shim

**Environment details (please complete the following information)**
Databricks-11.3 runtime.

**Additional context**

**Comment by HaoYang670** [comment]
I can work on this.
