### ISSUE TITLE
[BUG] Databricks-11.3 IT failures - IllegalArgumentException: requirement failed for complexTypeExtractors

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7352]
**Describe the bug**
Below tests are failing due to IllegalArgumentException. 
```
"org.apache.spark.sql.catalyst.expressions.ExtractValue
Need to fix ExtractValue shim        at org.apache.spark.sql.catalyst.expressions.ExtractValue.$init$(complexTypeExtractors.scala:152)
        at org.apache.spark.sql.rapids.GpuGetStructField.<init>(complexTypeExtractors.scala:35)
        at com.nvidia.spark.rapids.GpuOverrides$$anon$128.convertToGpu(GpuOverrides.scala:245"
```
- [ ] test_parquet_read_daytime_interval_cpu_file
- [x] test_agg_nested_array
- [x] test_agg_nested_map
- [x] test_agg_nested_struct
- [ ] test_aqe_struct_self_join
- [x] test_array_contains
- [x] test_array_item
- [x] test_array_item_ansi_fail_invalid_index
- [x] test_array_item_ansi_not_fail_all_null_data
- [x] test_array_max_q1
- [x] test_conditional_with_side_effects_array_index
- [ ] test_csv_scan_with_hidden_metadata_fallback
- [x] test_disorder_read_schema
- [x] test_get_array_struct_fields
- [x] test_grouped_sliding_window_array
- [x] test_hash_grpby_pivot
- [x] test_hash_grpby_pivot_without_nans
- [x] test_hash_multiple_grpby_pivot
- [x] test_hash_pivot_groupby_duplicates_fallback
- [x] test_hash_reduction_pivot_with_nans
- [x] test_hash_reduction_pivot_without_nans
- [ ] test_orc_scan_with_hidden_metadata_fallback
- [ ] test_parquet_scan_with_hidden_metadata_fallback
- [x] test_pred_push_round_trip
- [x] test_reduction_nested_array
- [x] test_reduction_nested_map
- [x] test_reduction_nested_struct
- [x] test_scalar_subquery_array
- [x] test_scalar_subquery_basics
- [x] test_scalar_subquery_map
- [x] test_scalar_subquery_struct
- [x] test_single_nested_orderby_with_processing_and_limit
- [x] test_struct_get_item
- [x] test_struct_self_join
- [x] test_union_by_missing_field_name_in_arrays_structs
- [x] test_union_struct_missing_children
- [x] test_window_aggregate_udf_array_from_python

**Steps/Code to reproduce bug**
Build and run integration tests on Databricks-11.3 environment.
Build  steps - /home/ubuntu/spark-rapids$ ./jenkins/databricks/build.sh

Test steps:  Modify the test.sh under jenkins/databrikcs to run a specific test.
                Example: Comment all lines starting from `export TEST_PARALLEL=${TEST_PARALLEL:-4}` in the file and add below lines:
                ```
                export TEST_PARALLEL=${TEST_PARALLEL:-1}
                TEST_NAME=$1
                bash /home/ubuntu/spark-rapids/integration_tests/run_pyspark_from_build.sh -k $TEST_NAME
               ```

Run Test -  `./jenkins/databricks/test.sh test_day_time_interval_division_nan `

**Expected behavior**
All above tests should pass on Databricks-11.3 shim

**Environment details (please complete the following information)**
Databricks-11.3 runtime.

**Additional context**

**Comment by jlowe** [comment]
There are still a few tests originally reported above that are still failing after the fix due to other issues.
- test_parquet_read_daytime_interval_cpu_file is covered by #7324.
- test_aqe_struct_self_join is covered by #7328
- the  *_with_hidden_metadata_fallback test failures are tracked by #7368
