### ISSUE TITLE
[FEA] handle peer timeouts in shuffle

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#737]
When UCX starts supporting peer error handling, this task is to pipe that in and cause a `RapidsShuffleFetchFailedException` or a `RapidsShuffleTimeoutException`.

This will help us report to the user, and the `MapOutputTracker` more accurate information at least for debugging/logs. Current logic in Spark indicates that a fetch failure from a peer will cause all output for such peer to be invalidated, but that certainly is not the case with the external shuffle service, but the error handling for non-ESS cases may change in the future, so we'll be prepared if we are implementing `FetchFailedException` as specified.

**Comment by sameerz** [comment]
This depends on UCX 1.10.
