### ISSUE TITLE
[BUG] CICD to build and test against db330 

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids#7389]
**Describe the bug**

CICD jobs to build db330 shim and to run integration tests against db330 

- [x] Pre-merge CI support build against db330 shim
- [x] Nightly build CI support build and deploy db330 shim, and aggregate db330 shim into dist jar
- [X] Enable integration tests for pre-merge and nightly build CIs, after all failed tests get fixed against db330 
- [X] Run nightly integration test CIs

**Comment by pxLi** [comment]
Looks like we are good to enable IT for premerge and nightly.

cc @NvTimLiu can you help create PR to enable premerge one first? If pass CI, we could then enable nightly test for 330db, thanks~

**Comment by NvTimLiu** [comment]
> Source/Doc update
> 
> There should be some doc and source update support DB330 from dev team, e.g.
> 
> * Missing 'spark330db.RapidsShuffleManager' in https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/docs/additional-functionality/rapids-shuffle.md ?
> 
> ```
> <html>
> <body>
> 
> 
> Databricks 11.3 | com.nvidia.spark.rapids.spark330db.RapidsShuffleManager
> -- | --
> 
> 
> </body>
> </html>
> ```
> 
> * Missing  source file : `spark330db.RapidsShuffleManager` under the path `sql-plugin/src/main/330db/scala/com/nvidia/spark/rapids/spark330db/` ?

Issue to follow up: https://github.com/NVIDIA/spark-rapids/issues/7517

**Comment by NvTimLiu** [comment]
all the issue got fixed, close this issue
