### ISSUE TITLE
[FEA] Support ToUnixTimestamp

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#74]
**Is your feature request related to a problem? Please describe.**
Would be good to support the `to_unix_timestamp` and `unix_timestamp` functions.

**Comment by revans2** [comment]
@razajafri ping?  At least part of this went into 0.1.0 could you file any needed follow on work and close this?

**Comment by razajafri** [comment]
#268 is a follow-on issue to this as we don't support column vectors for Java date/time patterns
