### ISSUE TITLE
How does spark-rapids support disticnt?

### ISSUE THREAD

**Issue by mjshare** [NVIDIA/spark-rapids#7419]
**What is your question?**
How does spark-rapids support disticnt?
Which interfaces of cudf are used to implement disticnt? Where is the specific code? Distinct is not displayed in the aggregation function.

**Comment by jlowe** [comment]
The answer can be tracked down by examining how Apache Spark plans a `distinct` operation.  Here's a toy example from a spark-shell session showing how the CPU plans a distinct operation:
```
scala> spark.conf.set("spark.rapids.sql.enabled", "false")

scala> val df = Seq("a", "a", "b", "a").toDF("s")
df: org.apache.spark.sql.DataFrame = [s: string]

scala> df.distinct.show
+---+
|  s|
+---+
|  a|
|  b|
+---+


scala> df.distinct.explain
== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- HashAggregate(keys=[s#20], functions=[])
   +- Exchange hashpartitioning(s#20, 200), ENSURE_REQUIREMENTS, [id=#258]
      +- HashAggregate(keys=[s#20], functions=[])
         +- LocalTableScan [s#20]
```

Note how the distinct is not implemented as a specific aggregation function but rather a hash aggregation with _no aggregation functions_.  In other words, it's simply a `groupBy` operation. All columns in the dataframe are part of the grouping keys, and therefore no other columns are leftover that would require an aggregation function.

The RAPIDS Accelerator for Apache Spark leverages the same plan, translating the CPU's HashAggregateExec to a GpuHashAggregateExec, similarly with no aggregation functions.  More specifically, it leverages the [groupby class](https://github.com/rapidsai/cudf/blob/branch-23.02/cpp/include/cudf/groupby.hpp#L94) in RAPIDS cudf to implement the hash aggregation, passing no aggregation operations, just like there are no aggregation operations in the CPU hash aggregate.

**Comment by revans2** [comment]
Distinct operations in Spark can get to be rather complicated. This is especially true if you start to do multiple different distinct aggregations on different columns, or if you do the distinct as a part of a group by operation.

```
scala> val df = Seq((1, "a"), (1, "a"), (1, "b"), (1, "a")).toDF("a", "s")
df: org.apache.spark.sql.DataFrame = [a: int, s: string]

scala> df.groupBy("a").agg(countDistinct(col("s"))).show()
+---+--------+
|  a|count(s)|
+---+--------+
|  1|       2|
+---+--------+


scala> df.groupBy("a").agg(countDistinct(col("s"))).explain
== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- HashAggregate(keys=[a#13], functions=[count(distinct s#14)])
   +- Exchange hashpartitioning(a#13, 200), ENSURE_REQUIREMENTS, [id=#165]
      +- HashAggregate(keys=[a#13], functions=[partial_count(distinct s#14)])
         +- HashAggregate(keys=[a#13, s#14], functions=[])
            +- Exchange hashpartitioning(a#13, s#14, 200), ENSURE_REQUIREMENTS, [id=#161]
               +- HashAggregate(keys=[a#13, s#14], functions=[])
                  +- LocalTableScan [a#13, s#14]
```

For group by operations Spark will first do a distinct on the keys of the group by and the value being counted. Then it will do a second aggregation to do the count. If you add in more aggregations on different columns, then Spark will insert in an `Expand` before the first aggregation so each aggregation operation gets their own line of input with the other aggregates columns set to null so they are not included in the final aggregation results. In the second aggregation the final results will be produced.

```
scala> val df = Seq((1, "a", "b"), (1, "a", "b"), (1, "b", "b"), (1, "a", "a")).toDF("a", "s1", "s2")
df: org.apache.spark.sql.DataFrame = [a: int, s1: string ... 1 more field]

scala> df.groupBy("a").agg(countDistinct(col("s1")), countDistinct(col("s2"))).show()
+---+---------+---------+
|  a|count(s1)|count(s2)|
+---+---------+---------+
|  1|        2|        2|
+---+---------+---------+


scala> df.groupBy("a").agg(countDistinct(col("s1")), countDistinct(col("s2"))).explain
== Physical Plan ==
AdaptiveSparkPlan isFinalPlan=false
+- HashAggregate(keys=[a#95], functions=[count(s1#148), count(s2#149)])
   +- Exchange hashpartitioning(a#95, 200), ENSURE_REQUIREMENTS, [id=#284]
      +- HashAggregate(keys=[a#95], functions=[partial_count(s1#148) FILTER (WHERE (gid#147 = 1)), partial_count(s2#149) FILTER (WHERE (gid#147 = 2))])
         +- HashAggregate(keys=[a#95, s1#148, s2#149, gid#147], functions=[])
            +- Exchange hashpartitioning(a#95, s1#148, s2#149, gid#147, 200), ENSURE_REQUIREMENTS, [id=#280]
               +- HashAggregate(keys=[a#95, s1#148, s2#149, gid#147], functions=[])
                  +- Expand [[a#95, s1#96, null, 1], [a#95, null, s2#97, 2]], [a#95, s1#148, s2#149, gid#147]
                     +- LocalTableScan [a#95, s1#96, s2#97]
```

I hope that this helps.  But as was said before we just follow what Spark is doing. We don't currently invent new ways of doing the aggregations.

**Comment by sameerz** [comment]
@mjshare please comment or re-open if you have further questions about distinct in spark-rapids.
