### ISSUE TITLE
[FEA] Investigate EXECUTOR_BROADCAST for Databricks-11.3

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7425]
**Is your feature request related to a problem? Please describe.**
This is a follow on issue of https://github.com/NVIDIA/spark-rapids/issues/7328#issuecomment-1352450826. The tests were failing because databricks added EXCUTOR_BROADCAST(which does executor side broadcast) instead of the driver broadcast(which is been done until now).
Spark Plan changes from BroadcastExchange to Exchange SinglePartition, EXECUTOR_BROADCAST, ... 

**Describe the solution you'd like**
This issue to track how we go about handling with EXECUTOR_BROADCAST. There could be 2 approaches
1. Do a regular Driver Side broadcast as we are doing until now. 
2. Support Executor side broadcast on GPU.

Ultimately, we need to support EXECUTOR_BROADCAST in 3 scenarios:

- [x] BroadcastHashJoinExec
- [x] SubqueryBroadcastExec
- [ ] BroadcastNestedLoopJoinExec

**Comment by NVnavkumar** [comment]
Apache Spark JIRA on this feature: https://issues.apache.org/jira/browse/SPARK-17556

**Comment by NVnavkumar** [comment]
A version of #7037 has now showed up with EXECUTOR_BROADCAST. Basically the executor broadcast code in DB 11.3 expects a ShuffleQueryStageExec as the direct child of the Join exec (in this BNLJ). We accomplished this earlier by incorporating the GPU shuffle coalesce in to the join itself. But in this case now the Join exec is on the CPU:

```
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o466.collectToPython.
E                   : org.apache.spark.SparkException: Unexpected build plan for Executor Side Broadcast Join: GpuColumnarToRow false
E                   +- GpuShuffleCoalesce 104857600
E                      +- ShuffleQueryStage 3, Statistics(sizeInBytes=98.0 B, rowCount=1, isRuntime=true)
E                         +- ReusedExchange [state_start#93], GpuColumnarExchange gpusinglepartitioning$(), EXECUTOR_BROADCAST, [plan_id=1805]
E
E                   	at org.apache.spark.sql.execution.joins.ExecutorBroadcast$.getShuffleIdFromPlan(ExecutorBroadcast.scala:161)
E                   	at org.apache.spark.sql.execution.joins.BroadcastNestedLoopJoinExec.executorBroadcast$lzycompute(BroadcastNestedLoopJoinExec.scala:91)
E                   	at org.apache.spark.sql.execution.joins.BroadcastNestedLoopJoinExec.executorBroadcast(BroadcastNestedLoopJoinExec.scala:89)
E                   	at org.apache.spark.sql.execution.joins.BroadcastNestedLoopJoinExec.prepareBroadcast(BroadcastNestedLoopJoinExec.scala:548)
E                   	at org.apache.spark.sql.execution.joins.BroadcastNestedLoopJoinExec.codegenLeftExistence(BroadcastNestedLoopJoinExec.scala:639)
E                   	at org.apache.spark.sql.execution.joins.BroadcastNestedLoopJoinExec.doConsume(BroadcastNestedLoopJoinExec.scala:529)
```
