### ISSUE TITLE
[BUG][SPARK-41713][SPARK-41726] Spark 3.4 build fails.

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7432]
**Describe the bug**
Meet two compile errors when building Spark 3.4
```
[ERROR] [Error] /home/remziy/working/rapids/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuOverrides.scala:3625: type arguments [org.apache.spark.sql.execution.command.CreateDataSourceTableAsSelectCommand] do not conform to method dataWriteCmd's type parameter bounds [INPUT <: org.apache.spark.sql.execution.command.DataWritingCommand]
[ERROR] [Error] /home/remziy/working/rapids/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/hive/rapids/HiveProviderImpl.scala:43: type arguments [org.apache.spark.sql.hive.execution.OptimizedCreateHiveTableAsSelectCommand] do not conform to method dataWriteCmd's type parameter bounds [INPUT <: org.apache.spark.sql.execution.command.DataWritingCommand]
[ERROR] two errors found
```

**Steps/Code to reproduce bug**
```
mvn package -Dbuildver=340 -DskipTests -s ./jenkins/settings.xml -f ./pom.xml
```

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by nartal1** [comment]
Related to this recent commit in Apache Spark - https://github.com/apache/spark/commit/4b40920e33176fc8b18380703e4dcf4d16824094

**Comment by HaoYang670** [comment]
The `CreateDataSourceTableAsSelectCommand` and `CreateHiveTableAsSelectBase` are now subtypes of `LeafRunnableCommand`, but not `DataWritingCommand`.

**Comment by HaoYang670** [comment]
It is better to wait https://issues.apache.org/jira/browse/SPARK-41726 to be merged.

**Comment by HaoYang670** [comment]
Also, I'm not sure whether DB11.3 will introduce this change, since it is a nice code clean-up

**Comment by nartal1** [comment]
> Also, I'm not sure whether DB11.3 will introduce this change, since it is a nice code clean-up

It is unlikely that this PR will be introduced in DB-11.3 since 11.3 is already released.  But we will monitor and see if the DB-11.3 build breaks due to this.
