### ISSUE TITLE
[FEA][SPARK-41096] Support reading parquet FIXED_LEN_BYTE_ARRAY type

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7449]
**Is your feature request related to a problem? Please describe.**
Spark 3.4 has supported reading parquet FIXED_LEN_BYTE_ARRAY type. We should also support it.
Related ticket: https://issues.apache.org/jira/browse/SPARK-41096

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by NVnavkumar** [comment]
Depends on https://github.com/rapidsai/cudf/issues/13304
