### ISSUE TITLE
[BUG][SPARK-41003] BHJ LeftAnti does not update numOutputRows when codegen is disabled

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7451]
**Describe the bug**
Spark 3.4 fixes a bug which the `numOutputRows` isn't updated in BHJ LeftAnti. We should check our plugin and decide whether we need to match this change.
Related ticket: https://issues.apache.org/jira/browse/SPARK-41003

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by revans2** [comment]
We do update the number of output rows in all cases. I don't think this is something that we have to worry about for the plugin.

**Comment by HaoYang670** [comment]
Thank you for the explanation! Then let me close the issue.
