### ISSUE TITLE
[FEA] Make `MAX_FILE_COUNTER` as a configuration

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7459]
**Is your feature request related to a problem? Please describe.**
https://github.com/NVIDIA/spark-rapids/blob/e9e605b7ac9aa7ac73a8f745fa3d6800729ba785/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuFileFormatDataWriter.scala#L53-L58

`MAX_FILE_COUNTER` is currently an internal constant value in `GpuFileFormatDataWriter`. I'd like to make it be a configuration so that users can modify it in some corner cases. Also with this configuration, we can test the behavior of `MAX_FILE_COUNTER` with less memory usage (related to #6822).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by HaoYang670** [comment]
Hi @jlowe, could you please take a look whether it makes sense to add this configuration?

**Comment by HaoYang670** [comment]
I meet the requirement to modify `MAX_FILE_COUNTER` to a small number when I'm writing test cases for #6822 to test an error should be returned when the number of files exceed this limit.

**Comment by jlowe** [comment]
I don't think it makes sense to add this config.  This code comes from Apache Spark, and IMO we should be matching the behavior there, not adding a plugin-specific config to change the behavior relative to Apache Spark.  Typically if the CPU writes N files then the GPU version should also be writing N files, we should be matching CPU behavior here.  Additionally a plugin-specific config will add confusion if Apache Spark adds their own config for this.

**Comment by HaoYang670** [comment]
Thank you for the explanation!
