### ISSUE TITLE
[BUG] cudf_udf_test.py is flakey

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#746]
All of the tests in cudf_udf_test.py fail periodically and need to be fixed.

**Comment by firestarman** [comment]
Any log  and the error snip ? I guess it could be OOM error.

**Comment by sameerz** [comment]
Marking as P2, @GaryShen2008 please confirm whether this test is required for the pandas cudf functionality.

**Comment by tgravescs** [comment]
reverting change with https://github.com/NVIDIA/spark-rapids/pull/813 due to tests failing in dev environment

**Comment by tgravescs** [comment]
also, even if these are off by default I would like to see proper documentation on how someone would run them as to what extra dependencies and commands are needed.

**Comment by GaryShen2008** [comment]
@firestarman It seems we only considered the docker environment and forgot the dev environment. May need more docs to explain how to run it or add some checking in test code.

**Comment by firestarman** [comment]
@shotai is working on it
