### ISSUE TITLE
[FEA] dynamic repartitioning of large/skewed hash joins

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#7471]
**Is your feature request related to a problem? Please describe.**
This is mostly a replacement for https://github.com/NVIDIA/spark-rapids/issues/2354.

Instead of falling back to a sort merge join, the idea is to try and partition the LHS and RHS. 

**Describe the solution you'd like**
The idea is fairly simple. If the inputs are too large, then partition the data into smaller partitions and do the join on the smaller data, just like Spark does to split the join up into smaller partitions. The hard part is to be able to dynamically decide on when to do this, and also how to split the data up.

My first idea for this is that we would start to pull data in from the build side. If the build side grows to be larger than the target batch size, then we need to split the data up, or we need to switch the build side.  Switching the build side would only work for a few join types that would allow it, and may get to be kind of complicated so that should be follow on work.

To split up the data we don't know how much data there is going to be so we don't have a good way to guess how many partitions we need. I think we want to do something similar to AQE and over-partition the data, and then use a heuristic to pull back together the pieces that we need. So perhaps we start with something like 8 or 16 partitions, but possibly have a config for this?? not sure. 

We would partition the data on the build side that we have already seen, and then stream through the rest of the build side. We make the output batches spillable as we partition the data.  Once the build side is done we look at the sizes of each of the partitions and can decide how we want to split up the partitions to find appropriate partitions to combine together. Ideally none of the build batches should be larger than the target batch size. If one single partition is too large for the target batch size we should have a follow on issue for how to deal with it properly. For now I think we just go with it, but in the future we might need some special case processing for it.

We now need to do something similar on the stream side and then do the joins. The question really is how do we want to do this. Do we want to stream through the entire stream side, as we partition it, and then do the joins, or do we want to try and do one of the joins as we look at the stream side.  The first one is definitely simpler to implement and I think we should start with it, but processing some of the data as we go could make this faster in some cases so it would like need to be follow on work to look into it.

**Describe alternatives you've considered**
Sort merge join, or something like that. We still might need some of this for highly skewed data.

**Additional context**
We probably want to think about how to refactor the join code to make this cleaner, and simpler to implement.

**Comment by firestarman** [comment]
Pls correct me if any is wrong.

This proposal seems to reduce the GPU peak memory only for executing the join, but the entire built table is still in GPU memory. 

The current implementation is based on one single built table, while this proposal will introduce multiple built tables because we split the data read from the build side up into multiple partitions, and each partition will have a coressponding built table. 

Then each batch (or partition if we partition the data) from the stream side will run the join multiple times due to multiple built tables.  After that, we coalesce the results of the joins as the final output, or return the results directly via an iterator.

**Comment by revans2** [comment]
If we make the data spillable as we partition the build and stream side into smaller pieces, then it is up to the spilling to decide if the data stays in memory or not.  So yes we will only be reducing the peak memory usage, but that is really the goal here. Perhaps I should include an example.

Let's say we are doing an inner join.

```
val df1 = Seq(1, 2, 3, 4, 5, 6, 7).toDF("A")
val df2 = Seq(2, 4, 6, 6, 8, 8).toDF("B")
df1.join(df2, col("A") === col("B")).show(100, truncate = false)
```

Just pretend that there is a lot more data, or the batch size is crazy small, whatever.

The join starts to pull in the build side `df2`

The first batch is `2, 4, 6`. This is small enough so we make it spill-able and go on to try and get the rest of the build side table.
The second batch is `6, 8, 8`. Now the data is too large to fit in a single target size batch so we want to do something to avoid using too much memory at one.  We then decide to repartition the data (and I am just making up partition numbers here).

`6, 8, 8` gets repartitioned first and turned into. PART 1 -> `6`, PART 5 -> `8, 8`. Each of those sub partitions are now spillable. We pull back in `2, 4, 6` and do the same thing. PART 0 -> `2`, PART 1 -> `6`, PART 3 -> `4`. We ask for the next partition and there is none, so our partitioned build side now looks like

  * 0 -> `2`
  * 1 -> `6`, `6` (two separate not merged sub batches)
  * 3 -> `4`
  * 5 -> `8, 8` (A single batch)

If there had been more batches on the build side we would have read them all and re-partitioned all of them.

We then repartition the entire stream side. It is very similar so I am not going to go into too many details but the results would be something like.

  * 0 -> `2`, `7`
  * 1 -> `5, 6`
  * 2 -> `3`
  * 3 -> `4`
  * 6 -> `1`

Because this is an inner join we could do an optimization and throw out all partitions on either side that don't have data on both sides.  But that could also be a follow on improvement. Depending on the type of join we can throw out batches on the left or right side if we cannot find them on both sides.  If we do implement this ideally we would throw out data on the stream side as soon as we could instead of waiting for both sides to finish. We are not going to do it in this example though.

We can then look at the batch sizes on the build side and decide how we want to combine partitions (assuming that we did over partition). So we say we want to combine partitions 0 and 3, but keep partitions 1 and 5 on their own.

We pull the data back from partitions 0 and 3 on the build side and combine them together into a new batch `2, 4`. We then start to pull data from partitions 0 and 3 on the stream side.  First we pull off `2` and `7` because that would not go over our target batch size. We combine them together into a single batch `2, 7` and do the join. The result is `A =2, B= 2`, which we would output.  When the next batch is requested we know that there is more data to stream for this build table so we pull out `4` from partition 3 and do the join.  The result is `A = 4, B = 4`. which we output, but we close the build side because we are done with that one.

The state now looks like 

BUILD
  * 1 -> `6`, `6`
  * 5 -> `8, 8`  

STREAM
  * 1 -> `5, 6`
  * 2 -> `3`
  * 6 -> `1`

We can then do the join on partition 1, just like we did on the combined 0/3 partition.  Combine the build side batches into a single batch `6, 6` and start to stream through the stream side data. `5, 6` which lets us output `(A = 6, B = 6), (A= 6, B = 6)`.  If the output table was decided to be too large we would have to do what we do today with the gather maps and output multiple smaller batches.

the state is now

BUILD
  * 5 -> `8, 8`  

STREAM
  * 2 -> `3`
  * 6 -> `1`

We then process partition 5 on the build side and create an empty table for the stream side to do the join against.

Then we work on the stream side creating an empty table for the build side to join against.

Things get complicated if after the first time we sub-partition the data the build side for one or more partitions is still too large.  In the short term I think we want to do the join for all of the other partitions first and then try to re-repartition the remaining data. But as a part of this we need to check if there is only 1 key in the given partition. If so no amount of re-partitioning is going to fix this. For now we should just cross our fingers and try to do the join.  In the future we might be able to swap the build and stream tables dynamically for a given partition depending on the type of join being done and the size of the stream side vs the build side.  We might even implement it in terms of a cross join for really bad cases where both sides are too large to fit in a single batch, or the join type makes it so this is not going to work.  But that should definitely be follow on work that we only do when a customer hits it.

Any time that we partition data that has already been partitioned we potentially run into a data skew problem. This is because all of the data for this task has already hashed to a given bucket. If we hash all of the data again using the exact same hash algorithm it is almost guaranteed that we will not get a good key distribution. We should either pick a separate hash implementation each time we need to do another layer of hashing, or we should pass in a different seed to the murmur3 hash. I would start with changing the seed, just because it means we don't have to be sure that the hash algorithm is correct for all of the data types we want to use it on. We have already tested this for murmur3 and we are good to go with it.

As a side note, the algorithm to re-partition the data based off of a hash is something that I think we might want to use as a fallback for hash aggregate. So if you could make the code separate so it can be called from elsewhere that would be great. But it is not a requirement.

**Comment by firestarman** [comment]
Looks like we need to read in all the data from the stream side in one Spark partition to do the sub-partitioning, but it would lead to taking more memory (host and device, or even disk), since the stream side usually has larger data than the build side.

Not sure the following would be better, which is similar as my first understanding (just a brainstorm). And it does not reqiure loading the whole data from the stream side.

We try to split the data up into multiple pieces evenly only for the build side, and the size of each piece is defined by a config (maybe), so we can do a simple `div` operation to get how many pieces there will be for an input batch.
Next, we begin to read the data from stream side batch by batch (same as the current behaivor). For each batch, we run the join with one piece of the build side each time. Let's assume there are 6 pieces, the join will execute 6 times for each batch from the stream side.
Compared to the current implementation, this idea can reduce the size of the build table for each join, without loading all the data of the stream side into (host and device) memory.

**Comment by firestarman** [comment]
temporarily unassign meself because I am going to take a long vacation for Spring Festival. Free to take over this if this issue becomes urgent.
I will work on this again aftere my vacation if it is still open and no one will be working on it.

**Comment by jlowe** [comment]
> We try to split the data up into multiple pieces evenly only for the build side

We cannot apply full stream side batches directly against sub partitions of the build side.  If we don't have all of a particular key value in the same stream and build batches, the join will produce the wrong results.  For example, consider a left outer join which produces rows with nulls for keys that are in the stream batch but not in the build sub-batch, but some other build sub-batch could have those missing keys.

**Comment by revans2** [comment]
> Looks like we need to read in all the data from the stream side in one Spark partition to do the sub-partitioning, but it appears to take more memory (host and device, or even disk), since the stream side usually has larger data than the build side.

That is mostly true and is why this is a fallback to handle a case when we don't have confidence that we could properly complete the join without doing this.

For a broadcast hash join we have high confidence that the build side will be small. For a regular hash join we have no guarantee like that. The build side can be set by the type of join being done and even in cases when either side could be the build side we end up just picking one with no real knowledge about how large that side is going to be. Often we are translating a sort merge join into a hash join. A sort merge join does not require a build side, so we just pick one that will work.

On a side note about resources a sort merge join is going to read in both join sides entirely to be able to sort the data before doing the join. Because of that the amount of memory/disk being used will not be any more than is used for a sort merge join, which is what the CPU is probably doing.

Your idea could work if we split up the build side into smaller pieces and then as we work if we do the hash partitioning as we read in the stream data.  i.e.

 
Build side is

```
0 -> 2
1 -> 6, 6 (two separate not merged sub batches)
3 -> 4
5 -> 8, 8 (A single batch)
```

We read in the first stream batch and partition it.

```
0 -> 2
2 -> 3
6 -> 1
```

We could then do three joins and output results, one for each of the smaller streamed batches that we just saw. And then do it again for the next streamed that is input.

There are a few downsides to this.

1) We are more likely to be doing joins on potentially really small batches. We might be able to mitigate some of this by doing a hybrid approach where we do the join only when there is enough data for a good sized batch on the stream side.
2) We might end up having a lot of churn on the build side. If both sides are large we are now going to potentially loop over the entire build side for each stream side batch that comes it. On paper this does not look like a big deal because we are not cacheing as much data on the stream side. But we don't have unspill (right @jlowe ?). Without unspill if we do spill one of the build side tables we are going to have to read it back in from disk or host memory each time.  That also can be fixed.
3) For joins like full outer join and existence joins we need to keep track of some state beyond just the regular join gather maps.  If we are effectively doing multiple joins at once in a single task it is going to increase the amount of memory used to hold that temporary state.

The hybrid join approach could have some real memory saving advantages, but I think we want to look at it as a follow on improvement.  Just because I don't want to complicate things too much. I would much rather get a generic approach to work,a dn then we can go back and optimize it when we have a better understanding of what is happening.

**Comment by jlowe** [comment]
> But we don't have unspill (right @jlowe ?)

Yes, we do have the ability to "unspill," meaning a buffer can be in multiple storage tiers simultaneously.  So when a buffer needs to be copied back from host memory to device memory, we no longer release the host memory buffer automatically as we did in the past.  Thereore if a device buffer needs to spill again, this is "free" since we already paid for the spill the first time.  Each "unspill" still costs, of course, since we need to copy the data back into device memory.

**Comment by revans2** [comment]
Then it sounds like we really should have a follow on issue to see if we can do the join on stream batches as soon as we see enough data to make it worth it. It might not be something that we do for all join types.

**Comment by firestarman** [comment]
> We cannot apply full stream side batches directly against sub partitions of the build side. If we don't have all of a particular key value in the same stream and build batches, the join will produce the wrong results. For example, consider a left outer join which produces rows with nulls for keys that are in the stream batch but not in the build sub-batch, but some other build sub-batch could have those missing keys.

Oh, yeah. You are right. I just missed the other join types, only focused on inner join.

**Comment by firestarman** [comment]
A relevant cudf PR https://github.com/rapidsai/cudf/pull/12715.
