### ISSUE TITLE
[BUG] Databricks test.sh no longer works on vanilla node

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7473]
**Describe the bug**
Prior to #7417, one could spin up a Databricks node with SSH access, hop on the node, and do a jenkins/databricks/build.sh followed by a jenkins/databricks/test.sh.  The latter no longer works because it cannot find pytest.  The script used to install all the necessary Python packages via pip, but that is no longer the case.  Without the needed packages, the script fails with an error trying to import pytest.

**Steps/Code to reproduce bug**
See above.

**Expected behavior**
databricks/jenkins/test.sh should "just work" on a Databricks node launched with default opts (other than the required SSH access).  If the necessary Python packages are not provided via some other means (e.g.: a conda env or already on the node) then the script should do what it takes to make those packages available rather than require the user to perform manual steps (that includes specifying an init script on cluster creation).

**Comment by NvTimLiu** [comment]
Suppose we're good to close this issue per #7789 got merged
