### ISSUE TITLE
[SPARK-41378] Support Column Stats in DS v2

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7479]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish the RAPIDS Accelerator for Apache Spark would [...]
Spark 3.4 has supported Column Stats in DB v2. We should check if we support it, either.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.
https://github.com/apache/spark/commit/96843850b4

**Comment by wjxiz1992** [comment]
a follow up change can also be included for this change: https://github.com/apache/spark/commit/e43b4be77a. Add it here.

**Comment by sameerz** [comment]
We do not overwrite relations so we should be ok.
