### ISSUE TITLE
[SPARK-41442]Only update SQLMetric value if merging with valid metric

### ISSUE THREAD

**Issue by HaoYang670** [NVIDIA/spark-rapids#7480]
**Is your feature request related to a problem? Please describe.**
This is a bug fix in Spark 3.4 to avoid merging invalid metrics to a valid metric.
We should check whether do we have this typo in the plugin.

https://github.com/apache/spark/commit/861a7710c9

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by sameerz** [comment]
We use `SQLMetric`, this change should not impact us.
