### ISSUE TITLE
[AUDIT][SPARK-41448][SQL] Make consistent MR job IDs in FileBatchWriter and FileFormatWriter

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#7491]
https://github.com/apache/spark/commit/7801666f3b added in some new code to keep consistency for MR job IDs. The plugin side should also include such change.

**Comment by rwlee** [comment]
Was fixed by @res-life in https://github.com/NVIDIA/spark-rapids/pull/7542. The addition of a shimmed 3.4+ GpuFileFormatWriter resolved the new approach to job IDs.
