### ISSUE TITLE
[BUG] udf_cudf_test::test_with_column fails with IPC error 

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#750]
**Describe the bug**
When running udf_cudf test with docker (centos7 cuda10.1), the operation with column (like plus one to one column) will throw 'OSError: Invalid IPC stream: negative continuation token'
**Steps/Code to reproduce bug**
1. enable test_with_column in udf_cudf_test.py
2. run the test case normally with pytest.
**Expected behavior**
The test will fail with exception:
'OSError: Invalid IPC stream: negative continuation token'
**Environment details (please complete the following information)**
 - Environment location: Docker (centos7 cuda 10.1) with standalone spark in it.
 - Spark configuration settings: need to enable udf support (spark.rapids.sql.python.gpu.enabled=true)
**Additional context**
All the settings of spark are already in test cases, you could use them directly.

**Comment by sameerz** [comment]
Marking as P2, @GaryShen2008 please confirm whether this test is required for the pandas cudf functionality.

**Comment by firestarman** [comment]
No more IPC error with the rapids jar from Sep, just hangs forever instead.

**Comment by firestarman** [comment]
Re-open due to not root cause. See PR 1343 https://github.com/NVIDIA/spark-rapids/pull/1343

**Comment by sameerz** [comment]
@firestarman can we move this to release 0.4?

**Comment by firestarman** [comment]
> @firestarman can we move this to release 0.4?

Yes please.

**Comment by firestarman** [comment]
I am closing this issue, since i found the root cause and[ the PR 1343](https://github.com/NVIDIA/spark-rapids/pull/1343) should be the best fix on the Spark plugin side.

The error is because GPU will send nothing about the arrow data to the python side when it is empty partition, but CPU still sends the `begin` and `end ` arrow packages to Python.
The [actual arrow writer inside a cuDF writer is created only in the method `write` ](https://github.com/rapidsai/cudf/blob/branch-0.18/java/src/main/native/src/TableJni.cpp#L230), but the method `write` will not be called when the partition data is empty. So nothing is sent to Python, even the `begin` and `end ` arrow package. Meanwhile the Python process expects at least the `begin` and `end ` arrow package, so it throws the IPC error due to negative continuation token.
