### ISSUE TITLE
[BUG] Update scripts to run Databricks-11.3 on various CSP's

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7526]
**Describe the bug**
This is follow up from comment https://github.com/NVIDIA/spark-rapids/pull/7522#pullrequestreview-1253848067 . We have updated scripts for nightly and pre-merge to include Databricks-11.3 but I am not sure if there are other scripts that needs to be updated too. Filing this issue for tracking additional tasks if any.

**Comment by NvTimLiu** [comment]
We have CI jobs(Azure/AWS) covered all the nightly premerge/build/integration tests for Databricks-11.3, close the issue
