### ISSUE TITLE
[BUG]Flaky test - udf_test.py::test_group_aggregate_udf

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#757]
This test fails periodically and need to be fixed.

**Comment by firestarman** [comment]
https://ci.ngcc.nvidia.com/job/spark/job/rapids_premerge-github/632/console

 =========================== short test summary info ============================
01:45:41  FAILED ../../src/main/python/udf_test.py::test_group_aggregate_udf[Long][IGNORE_ORDER, ALLOW_NON_GPU(AggregateInPandasExec,PythonUDF,Alias)]

**Comment by tgravescs** [comment]
do we have a follow up issue to actually fix or remove?  If note please file an issue so we track it.

**Comment by firestarman** [comment]
This issue is likely to have similar reason with the issue #740 .

**Comment by firestarman** [comment]
https://github.com/NVIDIA/spark-rapids/issues/740#issuecomment-784917512
