### ISSUE TITLE
[BUG] Databricks premerge failing with cannot find pytest

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7639]
The nightly build last night failed with a pytest import error, and now I'm seeing this on two successive tries to do a premerge build with databricks:
```
[2023-02-01T20:28:32.764Z] Traceback (most recent call last):
[2023-02-01T20:28:32.765Z]   File "/home/ubuntu/spark-rapids/integration_tests/runtests.py", line 17, in <module>
[2023-02-01T20:28:32.765Z]     from pytest import main
[2023-02-01T20:28:32.765Z] ModuleNotFoundError: No module named 'pytest'
```

Did someone change the premerge or nightly node init scripts recently?

**Comment by jlowe** [comment]
I was able to reproduce this with a Databricks 11.3 single-node instance, debugging.

**Comment by jlowe** [comment]
Looks like the init-cudf-udf init script is failing on 11.3 nodes with:
```
Looking for: ['cudatoolkit=11.0', 'cudf=23.02', 'findspark', 'pandas', 'pyarrow', 'pytest', 'pytest-order', 'pytest-xdist', 'requests', 'sre_yield']


Pinned packages:
  - python 3.9.*


Could not solve for environment specs
Encountered problems while solving:
  - package findspark-1.3.0-py_1 requires python, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

**Comment by jlowe** [comment]
I was unable to reproduce the init script problem manually, and now the premerge build seems to be properly finding pytest again.  At this point my guess is there was a bad package pushed to conda that was later corrected.

**Comment by pxLi** [comment]
Looks like conda nightly resolved the dependency issue for now. 
To refactor the databricks init logic and test scripts lets follow up in #7643 #7473

**Comment by pxLi** [comment]
started seeing this again for cudf 23.04 ENV init on databricks
reopen this to track cudf side dependencies fix of 23.04 (23.02 works fine)

**Comment by pxLi** [comment]
related to https://github.com/rapidsai/cudf/issues/12764

**Comment by pxLi** [comment]
this is not fixed yet

**Comment by tgravescs** [comment]
I'm going to change the databricks test.sh script back to just use pip install  and remove the cudf_udf tests for now.  We can track putting those back in with this issue.

**Comment by pxLi** [comment]
They are not supporting py-3.9 any more per https://github.com/rapidsai/cudf/issues/12764#issuecomment-1428131050

**Comment by pxLi** [comment]
https://github.com/NVIDIA/spark-rapids/pull/7758 merged to hardcode python version as 3.8
and currently skip udf_test and udf_cudf_test run for how to avoid failures of pandas version check

**Comment by NvTimLiu** [comment]
Suppose skipping cudf-udf test on DB113 is a temp workaround way with PR: https://github.com/NVIDIA/spark-rapids/pull/7758. Is there any issue following up pandas import failure on DB113? Or are we good not skipping it?

```
incorrect pandas version during required testing partially initialized 
module 'pandas' has no attribute '__version__' 
(most likely due to a circular import)
```

**Comment by pxLi** [comment]
> Suppose skipping cudf-udf test on DB113 is a temp workaround way with PR: #7758. Is there any issue following up pandas import failure on DB113? Or are we good not skipping it?
> 
> ```
> incorrect pandas version during required testing partially initialized 
> module 'pandas' has no attribute '__version__' 
> (most likely due to a circular import)
> ```

Yes, I think so. Filed https://github.com/NVIDIA/spark-rapids/issues/7773 to track the cudf-py ENV for databricks 11.3
