### ISSUE TITLE
[BUG] Databricks init scripts can fail silently

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7643]
Recently ran into a problem where the pytest module couldn't be imported (see #7639), and it turned out to be an issue with the conda environment not being able to be successfully resolved during the init script used for the cluster nodes.  This should have resulted in the cluster start failing, but instead the cluster was allowed to start, the build spent time compiling everything, and only when we finally got around to running the integration tests was it apparently something was wrong (but not clearly something wrong in the cluster init script).

If the cluster init script failed as it should have, the failure would have occurred much quicker and the error message would more directly implicate the source of the error.

**Comment by pxLi** [comment]
Our db runtime CI usually include build and test phases,
for build part, it does not require python/conda ENV
for pytest part, it fail instantly (~10s) after trying to run pytest.

Do you think it would be better to add a clearly error message to pytest script instead of fail at cluster init part? So we could still have the build + other mvn checks

**Comment by pxLi** [comment]
cc @NvTimLiu to help, thanks!

**Comment by jlowe** [comment]
> Do you think it would be better to add a clear error message to pytest script instead of fail at cluster init part?

I think the answer depends on what we want to prioritize.  From a cost perspective, it's more expensive to not fail fast.  Failing to setup the test environment will eventually fail the entire premerge/nightly run, and thus it's sort of a waste to spend dozens of minutes running up to a point you know much earlier eventually isn't going to work.  However by failing fast you are forgoing any early feedback you'd get on other errors that may be lurking in the parts that don't depend on the environment setup section that failed, but that's always going to be the case of failing fast vs. trying to soldier on.

> Or move the conda ENV setup part in databricks out of init script to test script?

This would be my preference.  The test script used to be the one-stop-shop for running the tests, but now you need to premeditate the init script in the cluster setup or it fails in a less than obvious way what went wrong.  Thus I filed #7473 since this used to work (except for cudf-udf).

**Comment by pxLi** [comment]
> > Do you think it would be better to add a clear error message to pytest script instead of fail at cluster init part?
> 
> I think the answer depends on what we want to prioritize. From a cost perspective, it's more expensive to not fail fast. Failing to setup the test environment will eventually fail the entire premerge/nightly run, and thus it's sort of a waste to spend dozens of minutes running up to a point you know much earlier eventually isn't going to work. However by failing fast you are forgoing any early feedback you'd get on other errors that may be lurking in the parts that don't depend on the environment setup section that failed, but that's always going to be the case of failing fast vs. trying to soldier on.
> 
> > Or move the conda ENV setup part in databricks out of init script to test script?
> 
> This would be my preference. The test script used to be the one-stop-shop for running the tests, but now you need to premeditate the init script in the cluster setup or it fails in a less than obvious way what went wrong. Thus I filed #7473 since this used to work (except for cudf-udf).

Got it! I think ideally we should have,
1. move pytest ENV setup in the test script, so we could get #7473
2. cluster init script should fail fast

**Comment by NvTimLiu** [comment]
Sounds good to me.
    If I remember correct, we only need conda to install cudf-udf python packages for cudf-udf integration tests, So for build stage we do not need this init_cudf_udf.sh  at all.
    init_cuda11_runtime.sh  is unnecessary as DB already installed cuda11 runtime for us.
That means we need not any init-scripts to create DB cluster now. Let me double confirm it.
may require your help investigate if we could fail fast if init script fail --> Good point, this should be supported by DB creating CLI, let me investigate it

**Comment by sameerz** [comment]
@jlowe mentioned we might be able to use the new RAPIDS pip packages instead of conda https://rapids.ai/pip.

**Comment by NvTimLiu** [comment]
> @jlowe mentioned we might be able to use the new RAPIDS pip packages instead of conda https://rapids.ai/pip.

Pip installing CUDF packages from https://rapids.ai/pip does not work for our udf-cudf test case. though it installs CUDF python packages, there are some dependencies like libarrow/arrow-cpp that are not available for pip, causing the below failure

```
Traceback (most recent call last):
  File "/home/ubuntu/rapids-4-spark_2.12-23.02.0-SNAPSHOT-cuda11.jar/rapids/daemon_databricks.py", line 132, in manager
  File "/home/ubuntu/rapids-4-spark_2.12-23.02.0-SNAPSHOT-cuda11.jar/rapids/worker.py", line 37, in initialize_gpu_mem
    from cudf import rmm
  File "/usr/local/lib/python3.9/dist-packages/cudf/_init_.py", line 12, in <module>
    from cudf import api, core, datasets, testing
  File "/usr/local/lib/python3.9/dist-packages/cudf/datasets.py", line 7, in <module>
    from cudf._lib.transform import bools_to_mask
  File "/usr/local/lib/python3.9/dist-packages/cudf/lib/init_.py", line 4, in <module>
    from . import (
  File "avro.pyx", line 1, in init cudf._lib.avro
  File "column.pyx", line 1, in init cudf._lib.column
  File "scalar.pyx", line 41, in init cudf._lib.scalar
  File "interop.pyx", line 1, in init cudf._lib.interop
AttributeError: module 'pyarrow.lib' has no attribute 'IpcReadOptions'
```

**Comment by NvTimLiu** [comment]
> > > Do you think it would be better to add a clear error message to pytest script instead of fail at cluster init part?
> > 
> > 
> > I think the answer depends on what we want to prioritize. From a cost perspective, it's more expensive to not fail fast. Failing to setup the test environment will eventually fail the entire premerge/nightly run, and thus it's sort of a waste to spend dozens of minutes running up to a point you know much earlier eventually isn't going to work. However by failing fast you are forgoing any early feedback you'd get on other errors that may be lurking in the parts that don't depend on the environment setup section that failed, but that's always going to be the case of failing fast vs. trying to soldier on.
> > > Or move the conda ENV setup part in databricks out of init script to test script?
> > 
> > 
> > This would be my preference. The test script used to be the one-stop-shop for running the tests, but now you need to premeditate the init script in the cluster setup or it fails in a less than obvious way what went wrong. Thus I filed #7473 since this used to work (except for cudf-udf).
> 
> Got it! I think ideally we should have,
> 
> 1. move pytest ENV setup to the test script, so we could also get [[BUG] Databricks test.sh no longer works on vanilla node #7473](https://github.com/NVIDIA/spark-rapids/issues/7473) work

> 2. cluster init script should fail fast

1, we need to change some CI files to move `conda install` into the test scripts, I'm thinking refactor DB CI scripts to better support update/change the DB cluster configurations

2, only need to add `-e` to the init script file here:  https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/jenkins/databricks/init_cudf_udf.sh#L21

According to : https://docs.databricks.com/clusters/init-scripts.html#cluster-scoped-init-scripts
```
If a cluster-scoped init script returns a non-zero exit code, the cluster launch fails. You can troubleshoot cluster-scoped init scripts by configuring [cluster log delivery](https://docs.databricks.com/clusters/configure.html#cluster-log-delivery) and examining the [init script log](https://docs.databricks.com/clusters/init-scripts.html#init-script-log).

{"code":"INIT_SCRIPT_FAILURE","type":"CLIENT_ERROR","parameters":{"instance_id":"i-09ebaa787fdf33f81","databricks_error_message":"Cluster scoped init script dbfs:/tim/test_init_fail.sh failed: Script exit status is non-zero"}},"init_scripts_safe_mode":false}
```

**Comment by jlowe** [comment]
> Pip installing CUDF packages from https://rapids.ai/pip does not work for our udf-cudf test case

Hmm, wondering if this is a bug and should be raised with the cudf team.

**Comment by NvTimLiu** [comment]
After double checking, this is more likely Databricks environment issue instead of pip dependencies/libs issue of https://rapids.ai/pip

1, I could install cudf-udf packages from https://rapids.ai/pip locally in a docker container, there was no dependencies/libs errors
2, On Databricks cluster, there were errors via pip installing from https://rapids.ai/pip, and diff DB runtime got diff errors, the above `module 'pyarrow.lib' has no attribute 'IpcReadOptions'` error was from DB11.3, the below `No such file or directory: '/usr/local/cuda/nvvm/libdevice'` error was from DB10.4
```
ubuntu@0212-153223-t5ia3g3c-10-59-237-67:~$ python -c "import cudf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/usr/local/lib/python3.8/dist-packages/cudf/utils/gpu_utils.py", line 95, in validate_setup
    cuda_runtime_version = runtimeGetVersion()
  File "/usr/local/lib/python3.8/dist-packages/rmm/_cuda/gpu.py", line 87, in runtimeGetVersion
    major, minor = numba.cuda.runtime.get_version()
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py", line 111, in get_version
    self.cudaRuntimeGetVersion(ctypes.byref(rtver))
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py", line 65, in __getattr__
    self._initialize()
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py", line 51, in _initialize
    self.lib = open_cudalib('cudart')
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/libs.py", line 59, in open_cudalib
    path = get_cudalib(lib)
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/libs.py", line 51, in get_cudalib
    libdir = get_cuda_paths()['cudalib_dir'].info
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cuda_paths.py", line 159, in get_cuda_paths
    'libdevice': _get_libdevice_paths(),
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cuda_paths.py", line 59, in _get_libdevice_paths
    candidates = find_file(re.compile(pat), libdir)
  File "/databricks/python3/lib/python3.8/site-packages/numba/misc/findlib.py", line 56, in find_file
    entries = os.listdir(ldir)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/nvvm/libdevice'
```

Cond install has no such issues. So need more investigate if we decided to turn to use `pip install` instead of `conda install` packages

**Comment by NvTimLiu** [comment]
As the issue https://github.com/rapidsai/cudf/issues/12772 mentioned, to install cudf package from PIP, the  CUDA Toolkit is required (conda help to install toolkit by `cudatoolkit =cuda11` but does not)

Currently on Databricks nodes, CUDA is a runtime environment missing the required toolkits like `nvcc`, some of `nvvm` libs.

Then we will need to manually install CUDA Toolkit if we want to install cudf via PIP. In this case, I suppose we are good to keep install via conda instead of PIP.

**Comment by NvTimLiu** [comment]
Will be fixed by https://github.com/NVIDIA/spark-rapids/pull/7789/

**Comment by NvTimLiu** [comment]
Fixed

https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/jenkins/databricks/init_cudf_udf.sh#L21
