### ISSUE TITLE
[FEA] Should we fallback to ARENA if RMM fails to start up an async pool

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#7649]
We currently try and detect if the driver/runtime support the async allocator: https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala#L1966.

That said, it doesn't appear this is a sufficient check: https://github.com/NVIDIA/spark-rapids/discussions/7636. The user reports RMM itself failing to start, which happens after we have decided that ASYNC is OK given the software versions. In the user's case, it looks like it is related to a vGPU setup.

I could see us keeping the current behavior, but perhaps catch the RMM exception and point to a FAQ page that describes each scenario where RMM would fail to start with async, and pointers to the pool config to set ARENA to unblock users. Or I could see us fallback to ARENA automatically, perhaps complaining in the logs (though chances are the log message will be ignored).

Either way, we could do better than letting the RMM exception be thrown on its own. I am wondering if others have preferences on which way to go, automatic fallback or error with pointers on how to proceed.

**Comment by sameerz** [comment]
An automatic fallback is preferred.  The plugin should probe to see whether ASYNC works and if not fall back to ARENA.
