### ISSUE TITLE
[FEA] Support ArrayContains

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#77]
**Is your feature request related to a problem? Please describe.**
once we support arrays #16 we should look at supporting `array_contains`

**Comment by sameerz** [comment]
Supported in 0.4, finishing work to support corner cases in https://github.com/rapidsai/cudf/pull/7349

**Comment by sameerz** [comment]
@mythrocks is there anything remaining for array_contains?

**Comment by kuhushukla** [comment]
I think now that the cudf change for nans is in, we should test it on the plugin side and remove the condition in gpuoverrides. @sameerz @mythrocks
