### ISSUE TITLE
[AUDIT][SPARK-42237] Change binaryType to unsupported type when writing CSV

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#7732]
**Is your feature request related to a problem? Please describe.**
In https://github.com/apache/spark/commit/02de5045a9 binary types are unsupported when writing CSV. We should make the same change for compatibility.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by revans2** [comment]
We don't support writing CSV. We have some basic support for hive text files, which are similar, but also different in the types that they can support.  We also don't support writing binary for these yet, or for CSV in general. I think we can just close this unless I am missing something.
