### ISSUE TITLE
[BUG] Join needs to grab semaphore when manifesting batches without new input batch

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#7743]
The join code is capable of manifesting new batches from its output iterator without obtaining a new batch from its input iterator, e.g.: when a join batch is split (either via the stream batch or the gather map) or when an "extra" batch is emitted like from the full join for the final batch.

Whenever a plan node emits a new batch without fetching from its input batch, it needs to obtain the semaphore because the last node in the stage usually releases the semaphore between batches (e.g.: write to shuffle or write to disk).  Normally the "input" nodes like read from shuffle or table scans will obtain the semaphore on behalf of all nodes processing a batch.  In the case of intermediate plan nodes creating new batches without new input batches, they are acting like the input nodes in that case and must obtain the semaphore for that new batch.

Note that the semaphore should _only_ be obtained when the plan node is creating a new input batch on its own.  Always obtaining the semaphore "just in case" can lead to suboptimal performance because the semaphore could be held while trying to perform I/O in upstream plan nodes.

**Comment by jbrennan333** [comment]
I am wondering if these cases are already covered because we are using `SpillableColumnarBatch`'s?
`SpillableColumnarBatchImpl.getColumnarBatch()` is acquiring the semaphore if necessary.

**Comment by jlowe** [comment]
Ah, yes that probably does cover it in practice.  Thanks, @jbrennan333!  I missed that acquisition when looking through the join code.

**Comment by jbrennan333** [comment]
For the pendingSplits, it looks like it could happen, because we are not marking them spillable.   If a pending batch is still cached, it won't acquire the semaphore.  I think the final batch for full batch join is covered though, because we always mark it spillable.
