### ISSUE TITLE
[BUG] Test in CastOpSuite fails on Spark-3.4

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#7752]
**Describe the bug**
`Test all supported casts with in-range values`  fails on Spark-3.4 with below error:
```
- Test all supported casts with in-range values *** FAILED ***
  Cast from BooleanType to TimestampType failed; ansi=true org.apache.spark.sql.AnalysisException: [DATATYPE_MISMATCH.CAST_WITH_CONF_SUGGESTION] Cannot resolve "CAST(c0 AS TIMESTAMP)" due to data type mismatch: cannot cast "BOOLEAN" to "TIMESTAMP" with ANSI mode on.
  If you have to cast "BOOLEAN" to "TIMESTAMP", you can set "spark.sql.ansi.enabled" as 'false'.;
  'Project [unresolvedalias(cast(c0#2746 as timestamp), None)]
  +- Repartition 1, true
     +- LocalRelation [c0#2746] (CastOpSuite.scala:294)

```

**Steps/Code to reproduce bug**
```
mvn clean install -pl tests -am -DskipTests
mvn test -Dbuildver=340  -pl tests -Dsuites='com.nvidia.spark.rapids.CastOpSuite'
```

**Expected behavior**
Above test should pass

**Comment by andygrove** [comment]
Prior to 3.4, Spark had separate expressions `Cast` and `AnsiCast` and in our `GpuOverrides` we had separate `ExprChecks` implementations for each.

Now `Cast` can support different modes (`LEGACY`, `ANSI`, `TRY`) so we will need to rework our `TypeChecks` / `GpuTypeShims` to accommodate this change.
