### ISSUE TITLE
[BUG] Integration test fails on spark 3.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#776]
**Describe the bug**
Integration test failed on spark 3.1.0-SNAPSHOT due to pyarrow (required by udf_test) version conflict between cudf's dependency and pyspark's.

![image](https://user-images.githubusercontent.com/8086184/93311583-c5e1fb80-f838-11ea-9a40-d4dcf1f72a5a.png)

**Steps/Code to reproduce bug**
Run the `rapids_it-3.1.0-SNAPSHOT-0.3-github` pipeline

**Expected behavior**
We should resolve the dependency issue to get the integration test passed

**Environment details (please complete the following information)**
spark 3.1.0-SNAPSHOT

**Additional context**
https://ci.ngcc.nvidia.com/job/spark/job/rapids_it-3.1.0-SNAPSHOT-0.3-github/2/console

**Comment by tgravescs** [comment]
we just need to update Jenkins file for this build, Spark updated version: https://issues.apache.org/jira/browse/SPARK-32312?jql=project%20%3D%20SPARK%20AND%20text%20~%20%22Arrow%201.0.0%22

**Comment by firestarman** [comment]
Let's skip the Pandas with cudf tests now, will try to figure out a solution for cudf Python and pyspark

**Comment by tgravescs** [comment]
I'm fine with either, this should just require the docker file being updated with the newer version.

**Comment by tgravescs** [comment]
The 3.1.0 integration tests are still failing, can you please take a look: https://ci.ngcc.nvidia.com/job/spark/job/rapids_it-3.1.0-SNAPSHOT-0.3-github/10/console

**Comment by tgravescs** [comment]
@firestarman @GaryShen2008  can we please get this fixed?  The longer this goes broken the more likely we are to miss other things that are breaking changes

**Comment by GaryShen2008** [comment]
> @firestarman @GaryShen2008 can we please get this fixed? The longer this goes broken the more likely we are to miss other things that are breaking changes

Sure. We'll fix it asap.

**Comment by firestarman** [comment]
I think this problem is caused by the branch-0.2 pipeline:
We  have both branch-0.2 and branch-0.3  IT pipelines, rapids_integration-0.2-github, rapids_integration-0.3-github
These 2 pipelines are uploading IT docker images [shared the same image name] for tests.
When rapids_it-3.1.0-SNAPSHOT-0.3-github ran, it pulled the latest branch-0.2 docker images
Solutions :
1, rename docker images to diff 0.2/0.3 IT, OR
2, Stop 0.2 pipelines

**Comment by firestarman** [comment]
@pxLi  @NvTimLiu Could you help on this?

**Comment by pxLi** [comment]
sure, just submitted a [MR](https://gitlab-master.nvidia.com/ngcc/cicd/infra/-/merge_requests/608) to delete outdated pipelines

**Comment by pxLi** [comment]
https://ci.ngcc.nvidia.com/job/spark/job/rapids_it-3.1.0-SNAPSHOT-0.3-github/20 passed
