### ISSUE TITLE
[FEA] Process Stuck on GPU Execution

### ISSUE THREAD

**Issue by mtsol** [NVIDIA/spark-rapids#7768]
**Is your feature request related to a problem? Please describe.**
my spark code with rapids enabled stucks here , without outputting anything, and sometimes on the same flow, throws gpu out of memory error. I think there are unnecessary stages planning on gpu: 

2023-02-14 12:25:20 WARN  GpuOverrides:69 - 
*Exec <HashAggregateExec> will run on GPU
  *Expression <AggregateExpression> count(1) will run on GPU
    *Expression <Count> count(1) will run on GPU
  *Expression <Alias> count(1)#1962L AS count#1963L will run on GPU
  *Exec <ShuffleExchangeExec> will run on GPU
    *Partitioning <SinglePartition$> will run on GPU
    *Exec <HashAggregateExec> will run on GPU
      *Expression <AggregateExpression> partial_count(1) will run on GPU
        *Expression <Count> count(1) will run on GPU
      !Exec <InMemoryTableScanExec> cannot run on GPU because ParquetCachedBatchSerializer is not being used

**Describe the solution you'd like**
I think we should have an indication for which operation we want to perform on gpu and which not. Like if we are calling count() on multiple occasions, then it should be cpu based it will save the data shifting cost.

**Comment by jlowe** [comment]
Closing this as answered.  Feel free to ask further questions here or open a new discussion/issue.
