### ISSUE TITLE
[BUG] udf test failed cudf-py 23.04 ENV setup on databricks 11.3 runtime

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#7773]
**Describe the bug**
As described in https://github.com/NVIDIA/spark-rapids/issues/7639

cudf-py is not supporting python 3.9 (which is the default python in databricks 11.3 runtime) anymore in 23.04 or newer https://github.com/rapidsai/cudf/issues/12764#issuecomment-1428131050

for now we just hardcode ENV as python3.8, 
and skip udf_test and udf_cudf_test due to pandas dependency broken https://github.com/NVIDIA/spark-rapids/pull/7758

We will need to find a better way to support re-enable udf tests, and also solution for setup cudf-py ENV which would not break pkg dependencies

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**
Pass all tests

**Comment by tgravescs** [comment]
So for this we want to change the regular tests back to not change the python version. We shouldn't be testing with a python version that isn't hte same as the user would use on Databricks. Personally I would rather see the tests.sh script back install pytest like in https://github.com/NVIDIA/spark-rapids/pull/7753 and just separate out the cudf_udf test to do something special there.

**Comment by tgravescs** [comment]
filed https://github.com/NVIDIA/spark-rapids/issues/7776 since I think this issue is tracking hte cudf issue.

**Comment by NvTimLiu** [comment]
moved cudf_udf tests out into the file  jenkins/databricks/cudf_udf_test.sh from  jenkins/databricks/test.sh; (either create cluster with or without init_cudf_udf.sh), hardcode python to 3.8 for DB11.3 to workaround cudf-udf conda install

```
jenkins/databricks/init_cudf_udf.sh
jenkins/databricks/cudf_udf_test.sh

......

../../src/main/python/udf_cudf_test.py::test_with_column[small data] PASSED [  9%]
../../src/main/python/udf_cudf_test.py::test_with_column[large data] PASSED [ 18%]
../../src/main/python/udf_cudf_test.py::test_sql PASSED (cudf_udf n...) [ 27%]
../../src/main/python/udf_cudf_test.py::test_select PASSED (cudf_ud...) [ 36%]
../../src/main/python/udf_cudf_test.py::test_map_in_pandas PASSED (...) [ 45%]
../../src/main/python/udf_cudf_test.py::test_group_apply PASSED (cu...) [ 54%]
../../src/main/python/udf_cudf_test.py::test_group_apply_in_pandas PASSED [ 63%]
../../src/main/python/udf_cudf_test.py::test_group_agg PASSED (cudf...) [ 72%]
../../src/main/python/udf_cudf_test.py::test_sql_group PASSED (cudf...) [ 81%]
../../src/main/python/udf_cudf_test.py::test_window PASSED (cudf_ud...) [ 90%]
../../src/main/python/udf_cudf_test.py::test_cogroup PASSED (cudf_u...) [100%]
============== 11 PASSED, 17684 deselected, 9 warnings in 16.16s ==============
```

**Comment by sameerz** [comment]
In the 23.06 release, RAPIDS will drop support for python 3.8 and add support for python 3.9.  RAPIDS will continue support for python 3.10.  

We will need to revert the changes for the Databricks 11.3 tests (since 3.9 will be supported), and make the same test changes for Databricks 10.4 (since 3.8 will be dropped).

**Comment by NvTimLiu** [comment]
Ok, I can help revert changes of install python3.8 cudf_udf packages in Databricks 11.3 

In Databricks 11.3, python3.8 is the default python for batch mode Databricks CLI (e.g., when running integration tests on DB11.3 cluster using DB CLI), we need to change default python to use 3.9 instead.

In Databricks 10.4, we need firstly to install python 3.9, then change default python to use 3.9.

So we may need to update our Databricks init_scripts to handle python version for both Databricks 11.3 and Databricks 10.4.

**Comment by pxLi** [comment]
> In Databricks 10.4, we need first to install python 3.9, then change default python to use 3.9.

@NvTimLiu Per above comment, we would just skip cudf udf test in databricks 10.4 for 23.06. 
No need to install extra python version

**Comment by NvTimLiu** [comment]
> > In Databricks 10.4, we need first to install python 3.9, then change default python to use 3.9.
> 
> @NvTimLiu Per above comment, we would just skip cudf udf test in databricks 10.4 for 23.06. No need to install extra python version

Got it, thanks!
