### ISSUE TITLE
Change Databricks premerge/nightly to not use different python version for tests

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7776]
**Describe the bug**
The databricks build got changed to require the cudf_udf init script and installed conda. Some of the builds have been changed to use different python version then what Databricks provides.  We want to change the regular tests back to not change the python version. We shouldn't be testing with a python version that isn't hte same as the user would use on Databricks. Personally I would rather see the tests.sh script back install pytest like in https://github.com/NVIDIA/spark-rapids/pull/7753 and just separate out the cudf_udf test to do something special there.

It also has the benefit a developer can just run test.sh like they used to without worrying about other steps.

**Comment by tgravescs** [comment]
@pxLi @NvTimLiu

**Comment by tgravescs** [comment]
note related to https://github.com/NVIDIA/spark-rapids/issues/7639

**Comment by jlowe** [comment]
> It also has the benefit a developer can just run test.sh like they used to without worrying about other steps.

Relates to #7473.

**Comment by NvTimLiu** [comment]
https://github.com/NVIDIA/spark-rapids/pull/7789 keep to use the default Databricks python in jenkins/databricks/test.sh for spark-rapids integration tests, only apply workaround of cudf_udf conda installing with python=3.8 for the file jenkins/databricks/cudf_udf_test.sh

So suppose we're good to close the issue as https://github.com/NVIDIA/spark-rapids/pull/7789 got merged.
