### ISSUE TITLE
[FEA] Add Spark 3.3.3-SNAPSHOT to shims

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#7784]
**Is your feature request related to a problem? Please describe.**
Spark 3.3.2 is released so update everything to use 3.3.3-SNAPSHOT

**Comment by gerashegalov** [comment]
This is a good test for https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/dev/shimplify.md#adding-a-new-shim to generate a skeleton of the new shim.

after `mvn install -DskipTests` execute:
```
mvn generate-sources -Dshimplify=true \
    -Dshimplify.move=true -Dshimplify.overwrite=true \
    -Dshimplify.add.shim=333 -Dshimplify.add.base=332
```

**Comment by pxLi** [comment]
can we target this FEA to 23.06? 
We will create branch-23.06 next week, 
it would nice to add snapshot shim directly to new dev branch, thanks!

**Comment by tgravescs** [comment]
found bug with shimplify that we need to work around - https://github.com/NVIDIA/spark-rapids/issues/7927
