### ISSUE TITLE
[FEA] Publish integration test jars to sonatype with release

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#779]
**Is your feature request related to a problem? Please describe.**
It would be nice to publish the integration test jar to sonatype with the release so that it can be used for testing the official release.   If we don't want it to go to sonatype for some reason then perhaps at least push to urm for internal testing.

**Comment by firestarman** [comment]
@NvTimLiu  Seems you have made a change to release tests jar to our internal repo, right ? please confirm.

**Comment by NvTimLiu** [comment]
The https://github.com/NVIDIA/spark-rapids/pull/793 is merged, so we can tag this issue fixed.

**Comment by tgravescs** [comment]
this went into 0.2
