### ISSUE TITLE
[FEA] Use Java APIs for full join 

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#7792]
Seems cudf Java already supports full join by these two APIs: [fullJoinGatherMaps](https://github.com/rapidsai/cudf/blob/branch-23.04/java/src/main/java/ai/rapids/cudf/Table.java#L2929) and [mixedFullJoinGatherMaps](https://github.com/rapidsai/cudf/blob/branch-23.04/java/src/main/java/ai/rapids/cudf/Table.java#L3035).

However [Plugin is still leveraging the LeftOuter join](https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/GpuHashJoin.scala#L514) to do the full join. It looks more complicated.

We would like to replace the WAR with the dedicated Java APIs if there aren't any known issues.

**Comment by jlowe** [comment]
The avoidance of the libcudf full join APIs is intentional.  We were using the libcudf full outer join APIs previously, but these only can work if a task can pull in both tables in their entirety to call those APIs.  That precludes batching the operation as is done for inner and left joins to avoid GPU OOM.  As such, the full join was changed to use an approach that can support batched operations within a task, see #7414.

**Comment by firestarman** [comment]
Thanks for this info.
However, it appears to work for the new sub partitioning algorithm, since we split the batches of both sides into small parts and join them pair by pair, meaning both tables are loaded on GPU when calling those APIs. What's your idea ?

**Comment by jlowe** [comment]
> we split the batches of both sides into small parts and join them pair by pair

If the sub-partitioning algorithm has a case where these are useful then yes, of course we could use them as part of that.  That would be covered by #7793, if that ends up being the case.  However sub-partitioning cannot always fully separate the input into small enough batches to fit in the memory budget. The batches on either side could consist of only a single key, and thus sub-partitioning does not end up splitting the partitions in practice.  In that case, we'd need to stream batches through, and then we're back to the algorithm implemented in #7414.

**Comment by firestarman** [comment]
>The batches on either side could consist of only a single key, and thus sub-partitioning does not end up splitting the partitions in practice. In that case, we'd need to stream batches through, and then we're back to the algorithm implemented in https://github.com/NVIDIA/spark-rapids/pull/7414.

Yeah, this is one of cases where this new algorithm may not work.
