### ISSUE TITLE
[BUG] buildall dist jar contains aggregator dependency

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#7826]
I recently build a dist jar using `build/buildall`, but the pom.xml in this jar has the dependencies section populated with the aggregator jar:

```
    <artifactId>rapids-4-spark_2.12</artifactId>
    <name>RAPIDS Accelerator for Apache Spark Distribution</name>
    <description>Creates the distribution package of the RAPIDS plugin for Apache Spark</description>
    <version>23.02.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.nvidia</groupId>
            <artifactId>rapids-4-spark-aggregator_${scala.binary.version}</artifactId>
            <version>${project.version}</version>
            <classifier>${spark.version.classifier}</classifier>
            <scope>compile</scope>
        </dependency>
    </dependencies>
```

But when I look at the published jar in maven, I see:

```
    <artifactId>rapids-4-spark_2.12</artifactId>
    <name>RAPIDS Accelerator for Apache Spark Distribution</name>
    <description>Creates the distribution package of the RAPIDS plugin for Apache Spark</description>
    <version>23.02.0</version>
    <dependencies>
    
    </dependencies>
```

Ideally we would like to see the same jar produced by the deploy scripts, as was addressed here https://github.com/NVIDIA/spark-rapids/pull/4265.

**Comment by gerashegalov** [comment]
for the - probably not very valid - reason of easier reasoning about the order of plugin executions I made patching of the pom run in the verify phase https://github.com/NVIDIA/spark-rapids/blob/5f9297973234546bac4d8a0d3e8fbfcf53e60879/dist/pom.xml#L426-L439

We should change it such that already the package phase produces the right content in the jar plugin the latest.

**Comment by abellina** [comment]
So is the change as simple as moving the `reduce-pom-deps-in-the-jar` to `<phase>package</phase>`?

**Comment by abellina** [comment]
> So is the change as simple as moving the reduce-pom-deps-in-the-jar to <phase>package</phase>?

I tried this locally, and the resulting rapids-4-spark_2.12 pom has no dependencies, so I think yes, but I do not know if it is as simple as that, especially given the other scripting around deploy. I'll wait for comment before putting up a PR.

**Comment by gerashegalov** [comment]
Away from real keyboard :) I would get rid of this step altogether. This zip update is expensive, and now it turns out not always helpful. 

So I would change the antrun where reduced Pom is produced to put in the final location instead of extra resources
