### ISSUE TITLE
[FEA] build with CUDA 12

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#7843]
**Is your feature request related to a problem? Please describe.**
Speed up the build process of spark-rapids to support cuda11 and cuda12.

**Describe the solution you'd like**
We're planning to support CUDA 12 build. So, we'll have a classifier "-cuda12" by packaging the spark-rapids-jni jar built for cuda 12. I suppose spark-rapids-jni will also have a classifier "-cuda12".
The scala/java codes in spark-rapids are not related to cuda 12. So, it doesn't need to build twice.
The difference between cuda11 and cuda12 will be only the native libraries, which are in spark-rapids-jni jar.
For now, we only package the spark-rapids-jni jar in the stage of building dist folder.

The ideal process of building spark-rapids for cuda11 and cuda12 will be:
1. Build the jars for the sub modules(except dist).
2. Package the dist with the sub modules and spark-rapids0-jni-cuda11 jar
3. Package the dist with the sub modules and spark-rapids0-jni-cuda12 jar

**Describe alternatives you've considered**
Without this, we simply can build the jars of sub modules twice but waste some time.

**Comment by jlowe** [comment]
Shouldn't this simply be a two step process?
1) Perform a clean build with -Dcuda.version=11
2) Perform a subsequent build _without_ cleaning using -Dcuda.version=12

The subsequent build should avoid rebuilding artifacts that are not dependent on the cuda.version setting.

**Comment by pxLi** [comment]
target this to 23.06, I will add cuda12 build later
