### ISSUE TITLE
[FEA] Arrow memory allocation from the pinned pool

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#786]
**Is your feature request related to a problem? Please describe.**
This is probably more for cudf, but because it is impacting performance here I thought I should file it here.  The current Arrow IPC code uses non-pinned memory.  This means that I/O with the GPU is limited to about 2GB/sec.  Profiling has shows for my contrived benchmarks that there is a lot of time spent doing I/O at a slower rate then I would like, but because inherently this is multi-threaded the I/O latency should be mitigated in many respects, so I don't know overall what the performance impact might actually be.

**Comment by JustPlay** [comment]
> The current Arrow IPC code uses non-pinned memory. This means that I/O with the GPU is limited to about 2GB/sec

If not using pin-memory，the H2D or D2H will not be async，so this will hart PTDS very much ?

**Comment by revans2** [comment]
> If not using pin-memory，the H2D or D2H will not be async，so this will hart PTDS very much ?

It would only be a problem if the copy inserted in a device synchronize instead of a stream synchronize at the end.  That is independent of an async copy truly being async or not, and from the traces I have seen I don't think it does.
