### ISSUE TITLE
[FEA] Allow checkpoint and restart on non-deterministic expressions

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#7865]
**Is your feature request related to a problem? Please describe.**
After https://github.com/NVIDIA/spark-rapids/pull/7864 goes in non-deterministic expressions are treated differently from deterministic ones, because there can be no retry on them. They don't produce the same result if called again.

But many of these operations, like GpuRandom, can have their state checkpointed and restored with a little work.  This is here to allow us to put in a framework to allow for checkpoint and restore of non-deterministic expressions, and to apply this specifically to GpuRandom. This will likely require us to copy the XOrShiftRandom from Spark into our code base so we can pull the seed out of it to checkpoint and restore.

This framework should also provide a way for a `GpuUserDefinedFunction` to also provide checkpoint and restore functionality along with all of the doc updates to explain what is happening and why

**Comment by firestarman** [comment]
Hi,
Do we already have any idea on how to implement the framework for this ? 
I am a little confused about the `framework` mentioned in the description, shouldn't we do it case by case ?

**Comment by revans2** [comment]
The idea is to have an interface that an expression can implement that would allow it to tell TieredProject that it can handle a checkpoint and restart. Then TieredProject would be responsible for calling the checkpoint/resort as needed to make it work.  Right now GpuRandom is the one that we want to do this for. But we want the interface to be sure that we could expose it to end users for GPU enabled UDFs that are non-deterministic. We don't have to do the UDF work here. Just start keep it in mind when designing the interface.
