### ISSUE TITLE
[FEA] Turn on spark.rapids.sql.castDecimalToString.enabled by default

### ISSUE THREAD

**Issue by mattahrens** [NVIDIA/spark-rapids#7870]
To help support customers with optimal performance out of the box, we want to enable the `spark.rapids.sql.castDecimalToString.enabled` setting to be true by default.  

The scope of this will involve any additional implementation and validation to be confident in the setting to be on by default.

Potential scope includes new spark-rapids-jni kernel and exhaustive validation.

- [x] Workaround value of 0 with 6 or more decimal places producing scientific notation in non-ansi mode

**Comment by hyperbolic2346** [comment]
PR for spark-rapids-jni is https://github.com/NVIDIA/spark-rapids-jni/pull/1168
