### ISSUE TITLE
[FEA] Add initial support for Databricks 12.2 ML LTS

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#7876]
**Is your feature request related to a problem? Please describe.**
Add support for Databricks 12.2 LTS https://docs.databricks.com/release-notes/runtime/12.2ml.html

**Describe the solution you'd like**

- [x] Add a shim layer for the new Databricks long term support version - https://github.com/NVIDIA/spark-rapids/pull/8282
- [x] https://github.com/NVIDIA/spark-rapids/issues/8319
- [x] https://github.com/NVIDIA/spark-rapids/issues/8423
- [x] https://github.com/NVIDIA/spark-rapids/issues/8756
- [x] https://github.com/NVIDIA/spark-rapids/issues/8660
- [x] https://github.com/NVIDIA/spark-rapids/pull/8810

There is a follow-on issue for items that were not implemented in the 23.08 release:

- https://github.com/NVIDIA/spark-rapids/issues/8860

**Describe alternatives you've considered**

**Additional context**

**Comment by jlowe** [comment]
Is this really done?  Seems to me we need to address most of the followup issues noted in #8282 before we can consider this done.

**Comment by mattahrens** [comment]
I interpreted this as done as the linked pull request was merged which enabled the original shim to be available.  If this issue is meant to track overall effort, then we can reopen it.  If so, we should have all the follow-on issues linked to this issue.

**Comment by andygrove** [comment]
Re-opened, with description updated to link to follow-on issues.

**Comment by andygrove** [comment]
Closing this since these items are complete, and the other items have been moved to a follow-on epic https://github.com/NVIDIA/spark-rapids/issues/8860.
