### ISSUE TITLE
[FEA] support order by string in windowing function

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#7883]
I wish we can support order by string in windowing function:

```
from pyspark.sql import SparkSession
from pyspark.sql.functions import sum, row_number
from pyspark.sql.window import Window
data = [(1, "A", 10, "regw"), (2, "A", 20, "reyw"), (3, "A", 30, "reuw"), (4, "B", 15, "resw"), (5, "B", 25, "redw"), (6, "B", 35, "rezw")]
df = spark.createDataFrame(data, ["id", "group", "value", "gorder"])
window = Window.partitionBy("group").orderBy("gorder")
yuadf = df.withColumn("aa", sum("value").over(window))
res = yuadf.withColumn("row_number", row_number().over(window)) \
                                .filter("row_number = 1") \
                                .drop("row_number")
res.show()
```
![image](https://user-images.githubusercontent.com/84758614/224712905-59385537-ca0e-4c45-bb94-99460a767673.png)

**Comment by mythrocks** [comment]
This will certainly need CUDF support. I'll add this, alongside support for float32/64.

The trick here is that we need to support `STRING` input, but only if the window bounds are `UNBOUNDED PRECEDING` - `UNBOUNDED FOLLOWING`/`CURRENT ROW`.

**Comment by mythrocks** [comment]
There are a couple of tasks in flight to support this in CUDF:
1. https://github.com/rapidsai/cudf/pull/13095: Prep to support non-numeric order-by columns.
2. https://github.com/rapidsai/cudf/pull/13143: CUDF support for `STRING` order-by.
