### ISSUE TITLE
Override `canonicalized` method to the Expressions

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#7898]
As part of https://github.com/apache/spark/pull/37851/files spark added the `canonicalize` method to Expressions but we haven't done that which causes the base method in TreeNode to be called. I don't know if we chose not to do this or if it's something that is missed. This might be something that Spark uses to consolidate commutative Expressions.

**Comment by NVnavkumar** [comment]
This bug fix was actually made in Spark 3.3.1 https://issues.apache.org/jira/browse/SPARK-40362
