### ISSUE TITLE
[FEA] better rlike function supported

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#7901]
I wish we can support end of line/string anchor in rlike function:

```
from pyspark.sql.functions import col
data = [("1", "123"), 
        ("2", "456"),
        ("3", "789"),
        ("4", "abc")]
df = spark.createDataFrame(data=data, schema=["id", "value"])
result = df.filter(col("value").rlike("^[0-9]*$"))
result.show()
```
![image](https://user-images.githubusercontent.com/84758614/226318816-67abd872-f811-4aa5-a3bc-583ead3e2dc6.png)

**Comment by NVnavkumar** [comment]
See related issue #5659. It looks like this is case that is caught up in one of the use cases mentioned there.

**Comment by nvliyuan** [comment]
> See related issue #5659. It looks like this is case that is caught up in one of the false positive use cases described there.
> 
> Unit test directly referenced there: [#5659 (comment)](https://github.com/NVIDIA/spark-rapids/issues/5659#issuecomment-1139130852)

Thanks for reminding, close this issue since duplicate with #5659
