### ISSUE TITLE
[BUG] UCX peer connection issue in multi-nic single node cluster

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#7940]
After upgrading to UCX 1.14 I see peer endpoint timeouts, and I don't see us being able to reconnect. So the test fails, timing out later. It seems the issue has two parts, one is the original timeout (I don't see indication on why that could be happening), but also we try to reconnect later and we can't. 

```
23/03/26 19:20:01 INFO UCX: Creating connection for executorId 2
23/03/26 19:20:01 INFO UCX: Creating connection for executorId 3
23/03/26 19:20:01 INFO UCX: Creating connection for executorId 1
23/03/26 19:20:02 INFO UCX: Established endpoint on ConnectionRequest for executor 1: UcpEndpoint(id=140486568354176, UcpEndpointParams{errorHandlingMode=UCP_ERR_HANDLING_MODE_PEER,connectionRequest/...:49576)
23/03/26 19:20:02 INFO UCX: Established endpoint on ConnectionRequest for executor 3: UcpEndpoint(id=140486568354112, UcpEndpointParams{errorHandlingMode=UCP_ERR_HANDLING_MODE_PEER,connectionRequest/...:49586)
23/03/26 19:20:02 INFO UCX: Established endpoint on ConnectionRequest for executor 2: UcpEndpoint(id=140486568354240, UcpEndpointParams{errorHandlingMode=UCP_ERR_HANDLING_MODE_PEER,connectionRequest/...:49578)
23/03/27 00:08:01 ERROR UCX: UcpListener detected an error for executorId 2: UCXError(-80,Endpoint timeout)
23/03/27 00:08:01 ERROR UCX: UcpListener detected an error for executorId 2: UCXError(-80,Endpoint timeout)
23/03/27 00:08:01 ERROR UCX: UcpListener detected an error for executorId 1: UCXError(-80,Endpoint timeout)
23/03/27 00:08:01 ERROR UCX: UcpListener detected an error for executorId 1: UCXError(-80,Endpoint timeout)
23/03/27 00:08:01 ERROR UCX: UcpListener detected an error for executorId 3: UCXError(-80,Endpoint timeout)
23/03/27 00:08:01 ERROR UCX: UcpListener detected an error for executorId 3: UCXError(-80,Endpoint timeout)
```
Re-attempts to connect:

```
23/03/27 00:34:06 INFO UCX: Creating connection for executorId 2
23/03/27 00:38:09 INFO UCX: Creating connection for executorId 3
23/03/27 00:38:10 INFO UCX: Established endpoint on ConnectionRequest for executor 1: UcpEndpoint(id=140486568354432, UcpEndpointParams{errorHandlingMode=UCP_ERR_HANDLING_MODE_PEER,connectionRequest/...:42810)
23/03/27 00:38:14 INFO UCX: Creating connection for executorId 1
```

Followed by the eventual timeout:
```
org.apache.spark.shuffle.rapids.RapidsShuffleTimeoutException: Timed out after 120 seconds while waiting for a shuffle batch.
```

**Comment by abellina** [comment]
I've been working with the UCX team and we have a workaround in this environment. It looks like it is a case where the tests are running for many hours and we have a period of inactivity of ~2 hours in the UCX sockets. When UCX starts up again, it gets the peer reset error. This is by no means a final solution, but this is the environment variable that helped: `UCX_TCP_KEEPINTVL=inf` (disabling keep alive..).

The other update is that this has nothing to do with 1.14, and it has been there before. I think our tests must have grown to the point we have more inactivity now (non-shuffle) and we end up hitting this scenario more often, but I am not 100% sure I saw it after upgrading.

**Comment by abellina** [comment]
For 23.06 we've documented the workaround, if users were to experience this (https://github.com/NVIDIA/spark-rapids/blob/branch-23.06/docs/additional-functionality/rapids-shuffle.md#known-issues). 

We hope to see a proper solution in 23.08

**Comment by pxLi** [comment]
we found another failure in rapids_it-UCX-egx06-standalone build ID: 826 w/ the workaround

Timed out after 120 seconds while waiting for a shuffle batch
```
FAILED ../../src/main/python/repart_test.py::test_repartition_df
```

I will update the known-issue part to make it clear that set `spark.executorEnv.UCX_TCP_KEEPINTVL=inf` may not completely fix this one

**Comment by abellina** [comment]
I haven't seen this issue in our environments for weeks now. We think it may be an environmental issue that we were not able to track down. The system showing this was also rebooted during this time. If we see it again we can reopen.
