### ISSUE TITLE
[DOC] Add references to qualification and bootstrap tools for EMR

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#7990]
I was told that we do support EMR in the qualification and bootstrap tools, yet they are not mentioned here: https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/get-started/getting-started-aws-emr.md. 

We should figure out if that's just a link to: https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/spark-qualification-tool.md and the documentation for the bootstrap tool.

**Comment by abellina** [comment]
Feel free to define what you'd like to see here @mattahrens and I can take care of it here if it makes sense: https://github.com/NVIDIA/spark-rapids/issues/7989.

**Comment by amahussein** [comment]
There is an open issue for that https://github.com/NVIDIA/spark-rapids-tools/issues/158

**Comment by mattahrens** [comment]
That's a different scope, in adding info about qualification user tools to the qualification page.  This issue is about adding EMR user tools info to the EMR Getting Started guide.
