### ISSUE TITLE
[DOC] getting started guide for dataproc is confusing

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#7991]
## Report <s>incorrect</s>confusing documentation

I did a review of https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/get-started/getting-started-gcp.md and it was really confusing.

* getting the python script installed is a pain. At least it was for me. I had python 3.8 installed, but it was not the default python version. I kept getting errors trying to install the script. Ultimately I had to go to a conda environment that had python 3.8 as the default and that worked. Not sure this is the best user experience. Especially on something that does not have python 3.8 as the default. Why do we need python 3.8 exactly???
* The first part of the docs assume that I have run something in google cloud already and have a cluster up and running.  This is fine. I am not sure if we want to distinguish between people who already have something up and running and want to migrate vs people who want to try out something on dataproc.  Later parts of the examples show trying something out on data proc and no clear link between them, so it feels a little odd.
* It feels odd that we have to run the qualification tool on a live CPU cluster. I assume that most people would not have the cluster live at that moment. They just want to know what jobs would be good to migrate.
* Is there a reason not all of my jobs showed up in the qualification tool. I had a few jobs that were very small or failed. The failed jobs I can see not showing up, but the really small ones feels odd that they wouldn't show up, unless there are so many other jobs that it is a bit much.
* The sections of the tutorial do not flow very well. The bootstrap tool comes before setting up a cluster. I got really confused because bootstrap to me feels like it is starting from nothing, but no it starts form a GPU cluster and updates it to be better. I was left wondering if I should use the options the qualifiaction tool spit out to create my cluster or if I should try to use the bootstap tool to create my cluster.  Only after looking ahead did I figure it out.
* By default dataproc does not use n1 nodes by default it uses n2 nodes (at least when trying to create the cluster from the UI).  The qualification tool said that I should just add T4s to my cluster request and everything would be fine. It was not. Some detection or warning about this would be good.
* The qualification tool predicted that my speedup would be 4x from 369 seconds to about 86 seconds. The actual number I got was close to 2 mins (at least according the the dataproc UI). After bootstrap and profiling this got down to 110. That is fairly decent. Good work
* It took forever to create the cluster.  The creation section mentioned this, but I ended up creating my cluster before I got there because the flow of the doc feels really odd.
* After I created the cluster and ran the qualification and profiling tool, then we get to the section on running notebooks and submitting jobs to the cluster.  Really??? There is no flow here.
* I really didn't like it that I had to compile the examples to try and run something on the cluster. I gave up after I had to also had to download/upload data to the cluster to try this out. I had already spent more than an hour on this. I really would like to see a flow that is different to the doc where we could be up and running in as little as a few mins.

**Comment by nvliyuan** [comment]
> * getting the python script installed is a pain. At least it was for me. I had python 3.8 installed, but it was not the default python version. I kept getting errors trying to install the script. Ultimately I had to go to a conda environment that had python 3.8 as the default and that worked. Not sure this is the best user experience. Especially on something that does not have python 3.8 as the default. Why do we need python 3.8 exactly???

maybe the reason the tool required python 3.8 and 3.10 from the [doc](https://github.com/NVIDIA/spark-rapids-tools/tree/dev/user_tools#getting-started) is the difference of supporting keywords across python versions. @mattahrens please correct me if anything wrong.

**Comment by nvliyuan** [comment]
> * Is there a reason not all of my jobs showed up in the qualification tool. I had a few jobs that were very small or failed. The failed jobs I can see not showing up, but the really small ones feels odd that they wouldn't show up, unless there are so many other jobs that it is a bit much.

not sure if the job has generated the eventlog successfully, if we have the eventlog, the result should show in the result table(I tried with starting some spark sessions but could not reproduce). @mattahrens any insights?

**Comment by mattahrens** [comment]
re: python version, we should say python-3.8 or higher.  it doesn't have to be exactly python-3.8.  @amahussein can confirm as well.

for qualification tool output in user tools, we default to only show recommended apps in the CLI output.  the full set of apps that were processed are available in the CSV output.
