### ISSUE TITLE
[DOC] Update Databricks getting started document

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#7993]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/get-started/getting-started-databricks.md

**Describe the problems or issues found in the documentation**
    https://github.com/NVIDIA/spark-rapids/pull/7712 enabled dynamic file pruning but did not update the getting started doc.  We need to remove step 6:

https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/get-started/getting-started-databricks.md?plain=1#L62-L64

The step on choosing node types needs to be updated: 

https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/get-started/getting-started-databricks.md?plain=1#L72-L75

There do not appear to be p2 or p3 nodes as options on AWS.  There are p4s (A100s) and g5s (A10s)

**Comment by nvliyuan** [comment]
> **Location of incorrect documentation**
> https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/get-started/getting-started-databricks.md

Not quite understand what locations is not correct, could you help input more info?

**Comment by nvliyuan** [comment]
> **Describe the problems or issues found in the documentation** #7712 enabled dynamic file pruning but did not update the getting started doc. We need to remove step 6:
> 
> https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/get-started/getting-started-databricks.md?plain=1#L62-L64

updated the steps/code/image

**Comment by nvliyuan** [comment]
> The step on choosing node types needs to be updated:
> 
> https://github.com/NVIDIA/spark-rapids/blob/branch-23.04/docs/get-started/getting-started-databricks.md?plain=1#L72-L75
> 
> There do not appear to be p2 or p3 nodes as options on AWS. There are p4s (A100s) and g5s (A10s)

Seems there are no p2 nodes but there are p3 nodes:
![image](https://user-images.githubusercontent.com/84758614/229401579-cb6c53a3-65d1-4b3b-a53e-8114281e6875.png)
p4 nodes only has an 8 GPU instance which is p4d.24xlarge instance, so it is not recommended
![image](https://user-images.githubusercontent.com/84758614/229401688-0c70133f-0a25-4797-90d5-069b48b9f8f0.png)
updated this part

**Comment by nvliyuan** [comment]
> Not quite understand what locations is not correct, could you help input more info?

Oh I got it, please ignore
