### ISSUE TITLE
[BUG] Spark-3.4 -  Integration tests failure due to missing InsertIntoHiveTable operator in GPU 

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#8016]
**Describe the bug**
Some of the integration tests are failing due to missing InsertIntoHiveTable

Failing tests:
- [x] test_basic_hive_text_write (fixed in https://github.com/NVIDIA/spark-rapids/pull/8144)
- [x] test_partitioned_hive_text_write (fixed in https://github.com/NVIDIA/spark-rapids/pull/8144)
- [ ] ~test_non_empty_ctas~ - moved to https://github.com/NVIDIA/spark-rapids/issues/8019

Failure reason:
```
!Exec <DataWritingCommandExec> cannot run on GPU because not all data writing commands can be replaced
  ! <InsertIntoHiveTable> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.hive.execution.InsertIntoHiveTable
  !Exec <WriteFilesExec> cannot run on GPU because WriteFilesExec can't run on GPU because parent can't run on GPU

```

**Comment by andygrove** [comment]
I moved the `test_non_empty_ctas` test to issue https://github.com/NVIDIA/spark-rapids/issues/8019 since it is  related to `GpuCreateDataSourceTableAsSelectCommand` rather than `InsertIntoHiveTable`. This issue can now be closed.
