### ISSUE TITLE
[FEA] Retry/SplitAndRetry on Parquet Writes

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8028]
**Is your feature request related to a problem? Please describe.**
Writing to Parquet with compression and everything can be very memory intensive. We add in support for ORC, but we should also enable it for Parquet once CUDF gives us the go ahead that the chunked writer API would not cause data corruption.

**Comment by ttnghia** [comment]
Depends on:
 * https://github.com/rapidsai/cudf/pull/13076
