### ISSUE TITLE
[FEA] Add support for MillisToTimestamp

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#8085]
This is a customer request to support `MillisToTimestamp`.

Per Spark documentation: "Creates timestamp from the number of milliseconds since UTC epoch." 

This is implemented in the CPU as:
```
    Math.multiplyExact(input.asInstanceOf[Number].longValue(), upScaleFactor)
```
with `upScaleFactor=1000` but it would be great if we can follow the Spark pattern and have this be a part of the base class, so we can support `MicrosToTimestamp` as well.

Because of `multiplyExact` we need to check for overflow in the multiply and throw `ArithmeticException` if we detect one.

**Comment by thirtiseven** [comment]
Completed in #8650
