### ISSUE TITLE
New OOM exceptions can be confusing to end user

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8090]
Saw the following exception on a recent run:
```
Job aborted due to stage failure: Task 33 in stage 1303.0 failed 4 times, most recent failure: Lost task 33.3 in stage 1303.0 (TID 37289) (10.59.128.149 executor 2): com.nvidia.spark.rapids.jni.SplitAndRetryOOM: Attempted to handle a split, but was not initialized with a splitPolicy.
```

The GPU ran out of memory, but the error message is not clear about that.  The error message reads like an internal assertion, implying something in the code was supposed to implement something and it didn't.  To a degree that's true, but essentially what happened here was a form of GPU OOM and it's not clear from the exception name nor the message that was the case.  Notably GPU does not appear anywhere.  It would be nice if the new GPU OOM exceptions were clear about the problem being a GPU OOM condition.

**Comment by abellina** [comment]
For spark-rapids-jni, we throw exceptions that may or may not be caught as well. For example, "task should retry operation" or "task should split input and retry operation". Should we just always say as the message "GPU OutOfMemory"? and rely on the type of the exception if we need to debug why we are getting this later?

An exception to this may be "retry limit exceeded" exception, but that one throws a Java OutOfMemory error, we may want that to become: "GPU OutOfMemory error: retry limit exceeded".
