### ISSUE TITLE
[BUG] 0.3 nightly is timing out 

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#811]
**Describe the bug**
the 0.3 nightly build is timing out. Its also not reporting to the cicd channel on slack.

If we need to increase timeout lets do it and fix reporting. The reason I noticed was the integration test gets killed. Can we decouple those timeouts as well?

**Comment by tgravescs** [comment]
@NvTimLiu @GaryShen2008 @pxLi

**Comment by pxLi** [comment]
I guess NGCC cluster was overloaded at that moment, so it failed to schedule executor. I will take a look
