### ISSUE TITLE
[DOC] Reduce visible configs to < 100

### ISSUE THREAD

**Issue by mattahrens** [NVIDIA/spark-rapids#8120]
Documented configs in public documentation is voluminous: https://nvidia.github.io/spark-rapids/docs/configs.html.  Let's reduce it to a usable set, starting with a set of < 100.

**Comment by thirtiseven** [comment]
Should we keep the "[Supported GPU Operators and Fine Tuning](https://nvidia.github.io/spark-rapids/docs/configs.html#supported-gpu-operators-and-fine-tuning)" Section on the config page, or move it to "advanced config" page, or move it to a new page?

**Comment by revans2** [comment]
> Should we keep the "[Supported GPU Operators and Fine Tuning](https://nvidia.github.io/spark-rapids/docs/configs.html#supported-gpu-operators-and-fine-tuning)" Section on the config page, or move it to "advanced config" page, or move it to a new page?

That feels advanced to me.

**Comment by mattahrens** [comment]
@thirtiseven can this issue be closed?

**Comment by thirtiseven** [comment]
> @thirtiseven can this issue be closed?

Yes, I think we can create follow-up issue for grouping advanced config and adding a tuning config page, if needed.
