### ISSUE TITLE
[FEA] Add Spark 3.5.0 shim layer

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#8121]
**Is your feature request related to a problem? Please describe.**
 Add Spark 3.5.0 shim layer.

We may want to hold off on this until 3.4 stable and decide when its useful.

**Comment by andygrove** [comment]
I started looking into this. There are some small refactors in 3.5.0 that affect us:

- LegacyBehaviorPolicy has moved out of SQLConf into a top-level class
- StructType.fromAttributes moved to DataTypeUtils
- BatchScanExec refactor to move some attributes to StoragePartitionJoinParams
- org.apache.spark.sql.execution.PartitionedFileUtil#splitFiles has extra param filePath

There are also some potentially more significant refactors that may be more work, but I haven't looked too closely yet:

- Hive UDF refactor
- Python UDF refactor and Arrow support
