### ISSUE TITLE
[FEA] Add spark 3.4.1 snapshot shim

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#8122]
**Is your feature request related to a problem? Please describe.**
Add spark 3.4.1 snapshot shim

**Comment by tgravescs** [comment]
3.4.1 is likely to be out in the next couple weeks.

**Comment by sameerz** [comment]
Spark 3.4.1 has been released: https://www.apache.org/dyn/closer.lua/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz
