### ISSUE TITLE
[BUG] dataproc init script does not fail clearly with newer versions of CUDA

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8149]
**Describe the bug**
I recently tried to use the init script

https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/spark-rapids/spark-rapids.sh

But provided a CUDA version for my cluster that was not in the DEFAULT_NVIDIA_DEBIAN_CUDA_URLS.  The error was really confusing and I needed to download the script to debug what was happening.

```
/etc/google-dataproc/startup-scripts/dataproc-initialization-script-0: line 61: DEFAULT_NVIDIA_DEBIAN_CUDA_URLS["${CUDA_VERSION}"]: unbound variable
```

It would really be nice if there were a cleaner error message saying something like the version of CUDA requested is not supported, please update your script or select a version that is Supported versions include (10.1, 10.2...

**Comment by nvliyuan** [comment]
Thanks for the info, just draft a [pr](https://github.com/GoogleCloudDataproc/initialization-actions/pull/1055) to fix the issue.

**Comment by revans2** [comment]
Looks good. But I am no bash expert.  Thanks for the fast fix.

**Comment by mattahrens** [comment]
PR was merged by Google, so we can close this issue.
