### ISSUE TITLE
[FEA] update release script and pipeline to support cuda12

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#8163]
**Is your feature request related to a problem? Please describe.**
Update plugin release scripts to support cuda 12 releasing after #8093 

Also make sure existing JNI release (cudf, plugin JNIs) setup work fine with extra cuda 12 artifact

**Comment by pxLi** [comment]
cc @NvTimLiu to help with this ticket, thanks!

**Comment by NvTimLiu** [comment]
Sure, let me check!
