### ISSUE TITLE
[FEA] Create integration test build against Dataproc

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#817]
**Is your feature request related to a problem? Please describe.**
We are supporting dataproc so we should create a integration build that spins up a cluster and runs the tests nightly.

**Comment by sameerz** [comment]
Need to test UCX on Dataproc to ensure there is a graceful fallback or obvious error in case Dataproc uses their own external shuffle.

**Comment by NvTimLiu** [comment]
Creating Blossom Jenkins pipeline for spark-rapids integration tests on Dataproc cluster:

**Comment by NvTimLiu** [comment]
pipeline: https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/job/rapids_integration-Dataproc/
Jenkins scripts: https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/tree/main/dataproc
mark it closed
