### ISSUE TITLE
[FEA] Refactor shims to remove dependency from 340 to 330db for cast/try_cast

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#8188]
**Is your feature request related to a problem? Please describe.**
This is a follow on issue related to https://github.com/NVIDIA/spark-rapids/pull/8179

The shim implementation for cast/try_cast is confusing and results in the 340 shim depending on the 330db shim.

See https://github.com/NVIDIA/spark-rapids/pull/8179#discussion_r1177922965 for more detail

**Describe the solution you'd like**
Refactor the shims for cast/try_cast so that 340 shim does not depend on 330db shim

**Describe alternatives you've considered**

**Additional context**

**Comment by revans2** [comment]
Actually I was wrong. It is confusing but I forgot about how complex the problem is that we are trying to solve. I think it is find the way it is.
