### ISSUE TITLE
[FEA]  Create Build and test setup for Amazon EMR

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#819]
**Is your feature request related to a problem? Please describe.**
Depending on what we discover with https://github.com/NVIDIA/spark-rapids/issues/818 create a build environment if we have to build against their jars and then also run integration tests against EMR nightly.

**Comment by GaryShen2008** [comment]
@NvTimLiu I think we have done it. Please update this issue.

**Comment by NvTimLiu** [comment]
@tgravescs  Seems we need not build spark-rapids on EMR cluster, as there is no spark-3.0.0 EMR runtime specified for spark-rapids 0.3.0. ? 

There is a blossom pipeline enabled on the aws EMR cluster for the pytests integration:
 https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/Testing/job/spark-rapids-integration-test-EMR/45/console

**Comment by tgravescs** [comment]
that is correct we don't need a build specific for EMR. We do have a shim layer for it, but it builds against the base Apache Spark.

As long as integration tests are setup we can close this then. Is it notifying slack, I didn't see any updates?

**Comment by NvTimLiu** [comment]
Pipeline: https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/job/rapids_integration-EMR/
Jenkins scripts: https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/tree/main/emr

Mark it closed
