### ISSUE TITLE
[AUDIT][SPARK-41219] IntegralDivide use decimal(1, 0) to represent 0 

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#8198]
**Is your feature request related to a problem? Please describe.**
Spark 3.5 changes the definition of decimal zero from `DecimalType.bounded(intDig, 0)` to `DecimalType.bounded(if (intDig == 0) 1 else intDig, 0)`.

**Describe the solution you'd like**
We have the same code in `org.apache.spark.sql.rapids.GpuIntegralDecimalDivide#resultDecimalType` so presumably we need to update this for 3.5 for consistency.

**Describe alternatives you've considered**

**Additional context**
https://github.com/apache/spark/commit/a056f69438

**Comment by razajafri** [comment]
We don't need to do this as we are not relying on `resultDecimalType` for calculating the return type. We directly call a kernel to do the division

**Comment by andygrove** [comment]
> We don't need to do this as we are not relying on `resultDecimalType` for calculating the return type. We directly call a kernel to do the division

So is `GpuIntegralDecimalDivide.resultDecimalType` even used? Should we remove it?

**Comment by revans2** [comment]
> So is GpuIntegralDecimalDivide.resultDecimalType even used? 

Just to clarify a bit `resultDecimalType` is called by `CudfBinaryArithmetic.dataTypeInteral` which becomes the `dataType` for the expression, except `GpuIntegralDivide` overrides `dataType` to be a long, so we really don't 

> Should we remove it?

We can, but if it ever is called we would get an exception. I think that is a risk I am willing to take, but it would be good to have a comment explaining it.

**Comment by razajafri** [comment]
> > So is GpuIntegralDecimalDivide.resultDecimalType even used?
> 
> Just to clarify a bit `resultDecimalType` is called by `CudfBinaryArithmetic.dataTypeInteral` which becomes the `dataType` for the expression, except `GpuIntegralDivide` overrides `dataType` to be a long, so we really don't
> 
> > Should we remove it?
> 
> We can, but if it ever is called we would get an exception. I think that is a risk I am willing to take, but it would be good to have a comment explaining it.

I think getting an Exception is better than the alternative. I will remove it.
