### ISSUE TITLE
[FEA] Update GpuCachedDoublePassWindowIterator to use OOM retry framework

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#8217]
**Is your feature request related to a problem? Please describe.**
In https://github.com/NVIDIA/spark-rapids/issues/7809 we implement OOM retry support for GpuWindowIterator and this is a follow-on issue to do the same for GpuCachedDoublePassWindowIterator

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by revans2** [comment]
This should include both retry and SplitAndRetry support if possible.
