### ISSUE TITLE
[BUG] Java agent crashed intermittently running integration tests

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#8235]
**Describe the bug**

**Updated 23.05.10:** 
Seems not only failed in databricks runtime, we saw error at JDK11-nightly build:295

We saw CI started failing from yesterday due to java gateway crashed ~in databricks runtimes (10.4 and 11.3)~
this has not been seen in other test ENVs yet

e.g.
rapids_premerge-github, build ID: 7100, 7102
rapids_databricks_nightly-dev-github, build ID: 712

```
 = 539 failed, 15676 passed, 954 skipped, 799 xfailed, 273 xpassed, 104 warnings in 6918.52s (1:55:18) =
```
failed only window_func/udf related cases in xdist parallel run, not sure if its related to OOM inject or some other issue like resource leak

**Steps/Code to reproduce bug**
run IT in databricks runtime (50% reproducible)
(run only window_func test may not be able to reproduce the error)

**Comment by pxLi** [comment]
we saw the error also failed in standalone tests
JDK11-nightly build ID: 295

**Comment by NVnavkumar** [comment]
Closing this issue for now since the crash has not shown up since https://github.com/NVIDIA/spark-rapids-jni/pull/1128 was merged. Will reopen if this shows up again.
