### ISSUE TITLE
[CI] It is not obvious where to find hs_err_pid files in CI

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#8269]
This issue is more of requirement gathering thing. We have seen a few CI failures that ended up being a segfault, but getting the `hs_err_pid` files is hard somehow, because each CI is writing those files to a specific location.

I think we should use `-XX:ErrorFile` to point it somewhere easy to find. @NVnavkumar suggested the workskace that jenkins is using and will copy out later, so these files would be carried along.

I am not an expert on all of the CI jobs, but I think we would want to set this per job since each job has its own paths.

**Comment by pxLi** [comment]
Yeah, this could go huge as we have too many different scenarios to run w/ JVM in CIs.


As this is good to have and would not block prod release, 
I will update the ticket when I have time, let's split this into multiple items and tackle them one by one later.

**Comment by pxLi** [comment]
removed bug tag as its not a BUG

**Comment by pxLi** [comment]
Nightly updates were applied in internal pipelines
