### ISSUE TITLE
[DOC] Suggestions for getting-started-on-prem.md

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#8280]
## Suggestions to Improve documentation

**Location of documentation**
[getting-started-on-prem.md](https://github.com/NVIDIA/spark-rapids/blob/branch-23.06/docs/get-started/getting-started-on-prem.md)

**Describe the issues found in the documentation**
These are some suggestions based on reading through the getting-started-on-prem documentation(excluding MIG on YARN), and following the instructions to run Rapids Acclerator on local mode, Spark standalone and YARN cluster.

Overall I could follow the instructions and run the example commands. There are few nits which would be good to address. Suggestions are based on the header in the document.

**Spark Deployment Methods**
(Nit)  This sentence can be rephrased: `The primary methods of deploy Spark`

**Apache Spark Setup for GPU**
(Nit) After installing GPU driver and CUDA toolkit, it would be good to provide instructions to check if cuda is installed successfully(nvidia-smi etc)  or point to the link which has info on how to verify. 

**Install Spark**
(Nit) I am not sure if the link "instructions" points to correct section. It points to launching cluster section. Need to update that if required. 

**Spark Standalone Cluster**
The scripts and conf names mentioned in the section for worker(s) has mention of slaves, slavesh.sh etc. Spark-3.1's documentation has replaced mention of slaves with workers. For example: $SPARK_HOME/sbin/start-slaves.sh with $SPARK_HOME/sbin/start-workers.sh and so on. This section should be updated accordingly.

**Running on YARN**
This section mentions that it assumes YARN already installed and setup. I was not aware that we had to set HADOOP_HOME and HADOOP_CONF_DIR before running the spark-shell command mentioned in this section. For a user not familiar with YARN, it might be diffificult to know these before running.

**Example Join Operation**
The SparkUI posted here is of Spark-3.0.0-SNAPSHOT. Rapids Acclerator doesn't support Spark-3.0 anymore and the output may confuse users. Would be good to update this with the Spark version which is supported.

**Comment by nvliyuan** [comment]
> Install Spark
(Nit) I am not sure if the link "instructions" points to correct section. It points to launching cluster section. Need to update that if required.

I assume this is ok, because in the doc we refer `install spark` both in standalone and yarn section, they are different type of cluster, so we point to `#launching-on-a-cluster` page section.

**Comment by nvliyuan** [comment]
> Running on YARN
> This section mentions that it assumes YARN already installed and setup. I was not aware that we had to set HADOOP_HOME and HADOOP_CONF_DIR before running the spark-shell command mentioned in this section. For a user not familiar with YARN, it might be diffificult to know these before running.

I assume this section is included in https://spark.apache.org/docs/latest/running-on-yarn.html#launching-spark-on-yarn in the [pr](https://github.com/NVIDIA/spark-rapids/pull/8510/files), so I just add the link to refer, not duplicate it in the doc.

**Comment by mattahrens** [comment]
Can this issue be closed?

**Comment by nvliyuan** [comment]
since #8510 merged, close this issue
