### ISSUE TITLE
[BUG] The metrics of "peak device memory" in Gpu parquet scan doesn't work when using coalesce reading

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#8297]
**Describe the bug**
I found the peak device memory showed 0 when using coalesce reading of GPU parquet scan.

**Steps/Code to reproduce bug**
Rapids-4-spark: 23.04
The bug happened when we ran the NDS test with Tencent COS.
Without adding the "cosn" in the spark.rapids.cloudSchemes, run the query to read a parquet dataset.

One example of the Spark UI SQL shows:
GpuScan parquet
number of files read: 1
scan time: 498 ms
output columnar batches: 1
**peak device memory: 0.0 B**
GPU decode time: 4 ms
metadata time: 1 ms
size of files read: 1825.5 KiB
output rows: 73,049
buffer time: 112 ms

**Expected behavior**
The metrics should show correctly.

**Environment details (please complete the following information)**
 - Environment location: Cloud, should happen on any environment.

**Additional context**
Suppose it can also be reproducible on S3 if we remove S3/S3a from the scheme config.

**Comment by mattahrens** [comment]
How are you intending to use the peak device memory metric?  We are thinking of ripping out the peak device memory metric so we'd like to understand its benefits.

**Comment by GaryShen2008** [comment]
I just filed it because it didn't show correctly on coalesce reading, but correct on multithread read.
If we're going to drop it, is there any issue? I can ask Haoyang to work on it.

**Comment by mattahrens** [comment]
Yes, there isn't a specific use case for it so we can remove that metric.
