### ISSUE TITLE
[FEA] Support window count for a column

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#838]
**Is your feature request related to a problem? Please describe.**
Now that https://github.com/rapidsai/cudf/pull/6287 is in some of the API limitations in java cudf that prevented us from doing this are gone and it should be possible.

**Comment by revans2** [comment]
It turns out that there is a bug in the cudf count code that makes it so we cannot turn this on.

@mythrocks have you filed an issue for that yet against cudf?

**Comment by sameerz** [comment]
https://github.com/rapidsai/cudf/pull/6344 will unblock this issue.
