### ISSUE TITLE
[BUG] Rollup Query fails in pytest with "year 0 is out of range"

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#842]
**Describe the bug**
The following test fails in python when using spark 3.1.0

```
@pytest.mark.parametrize('data_gen', all_gen, ids=idfn)
@ignore_order
def test_cache_expand_exec(data_gen):
    def op_df(spark, length=2048, seed=0):
        cached = gen_df(spark, StructGen([
            ('a', data_gen),
            ('b', IntegerGen())], nullable=False), length=length, seed=seed).cache()
        cached.count() # populate the cache
        return cached.rollup(f.col("a"), f.col("b")).agg(f.count(f.col("b")))
    assert_gpu_and_cpu_are_equal_collect(op_df)
```

**Steps/Code to reproduce bug**
write the above test in python or pyspark shell. 

**Expected behavior**
The test should pass

**Additional context**
Investigate why the above test is failing. The following error is reported

```
return datetime.datetime.fromtimestamp(ts // 1000000).replace(microsecond=ts % 1000000)
ValueError: year 0 is out of range
```
This makes it sound like the timestamp is going out of range which we have been circumventing by limiting the dates used for generating a timestamp in python tests

**Comment by razajafri** [comment]
@sameerz should we mark this as p1 as per @revans2 suggestion?

**Comment by revans2** [comment]
Until we know why it is failing and the extend of the possible data corruption we need to treat this as a P1

**Comment by jlowe** [comment]
Is this still a P1 for the 0.3 release if it's specific to Spark 3.1.0?

**Comment by razajafri** [comment]
This is no longer reproducible. We should keep this around as a lower priority until Spark 3.1 is released

**Comment by razajafri** [comment]
Unable to reproduce this error while running with the latest Spark-3.1.0-SNAPSHOT. We should de-prioritize this until the Spark-3.1.0 release

**Comment by razajafri** [comment]
Closing as this isn't reproducible
