### ISSUE TITLE
[FEA] Add the Spark 3.1.0 shim layer for GpuWindowInPandasExec

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#844]
**Is your feature request related to a problem? Please describe.**
Its parent class `WindowExecBase`, an abstract class in Spark 3.0.x, becomes a trait in Spark 3.1.0.

**Describe the solution you'd like**
 So need to add a shim layer to support Spark 3.1.0

**Comment by tgravescs** [comment]
reference https://issues.apache.org/jira/browse/SPARK-30765
