### ISSUE TITLE
[BUG] there are no logs for test failures in github any more

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8452]
**Describe the bug**
Recently something changed with the github pre-merge checks.  We used to get lots of log info out.  Now all I see is.

```
 ******** JOB LOGS with sensitive data redacted ************** 

****** Result of stage DB runtime 10.4 is FAILURE ******
****** Result of stage DB runtime 11.3 is FAILURE ******
****** Result of stage Dummy stage: blue ocean log view is FAILURE ******
****** Result of stage Premerge CI 2 is FAILURE ******
****** Result of stage mvn verify is FAILURE ******
```

Can we please find a way to show more or no one outside of NVIDIA will be able to debug test failures.  It is also a pain to have to go to the server and look up what job it was and try to link everything together for someone who does work at NVIDIA.

**Comment by pxLi** [comment]
I will work w/ blossom team to check if anything changed from their side which could affect our usages later

**Comment by pxLi** [comment]
also can you list me some examples that fail to upload jenkins logs,

I checked recent failed ones, they uploaded some as expected,
https://github.com/NVIDIA/spark-rapids/actions/runs/5194545721/jobs/9366318377
https://github.com/NVIDIA/spark-rapids/actions/runs/5193866038/jobs/9364929497
https://github.com/NVIDIA/spark-rapids/actions/runs/5194417338/jobs/9366053660

**Comment by pxLi** [comment]
closing this one. Please reopen if any new issue
