### ISSUE TITLE
[FEA] Restore null column caching feature in GpuExpandExec

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8468]
#8467 removed a broken optimization for caching of null columns in GpuExpandExec.  Ideally this optimization should be restored, reusing null columns already generated of the same datatype within the batch.  However it may not make sense to examine the result of `columnarEval` looking for a GPU scalar and examining the result, as that will involve tiny data transfer and synchronization with the GPU.  Instead it would be better to examine the Catalyst expressions to know when we're generating null columns and specifically duplicate null columns.  This not only avoids the synchronization problems of examining GPU scalar results but also avoids the synchronization of generating the null GPU scalars in columnarEval.

**Comment by revans2** [comment]
I did a quick test with this to see what would happen.  It was a very small patch to enable this in TieredProject

```
diff --git a/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressions.scala b/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressions.scala
index 41fb3d77b..0004f0b07 100644
--- a/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressions.scala
+++ b/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/catalyst/expressions/GpuEquivalentExpressions.scala
@@ -22,7 +22,7 @@ package org.apache.spark.sql.rapids.catalyst.expressions
 import scala.annotation.tailrec
 import scala.collection.mutable
 
-import com.nvidia.spark.rapids.{GpuAlias, GpuCaseWhen, GpuCoalesce, GpuExpression, GpuIf, GpuLeafExpression, GpuUnevaluable}
+import com.nvidia.spark.rapids.{GpuAlias, GpuCaseWhen, GpuCoalesce, GpuExpression, GpuIf, GpuUnevaluable}
 
 import org.apache.spark.TaskContext
 import org.apache.spark.sql.catalyst.expressions.{Attribute, AttributeReference, AttributeSeq, AttributeSet, CaseWhen, Coalesce, Expression, If, LeafExpression, PlanExpression}
@@ -191,7 +191,7 @@ class GpuEquivalentExpressions {
       expr: Expression,
       map: mutable.HashMap[GpuExpressionEquals, GpuExpressionStats] = equivalenceMap): Unit = {
     val skip = expr.isInstanceOf[LeafExpression] ||
-      expr.isInstanceOf[GpuLeafExpression] ||
+      expr.isInstanceOf[LambdaVariable] ||
       expr.isInstanceOf[GpuUnevaluable] ||
       (expr.isInstanceOf[GpuExpression] && expr.asInstanceOf[GpuExpression].hasSideEffects) ||
       // `LambdaVariable` is usually used as a loop variable, which can't be evaluated ahead of the
```

There was no performance diff that I could see.  I tested with NDS scale factor 200 store sales and did a rollup on the first N columns (where N is 1 to 5).  The performance difference was all in the noise.  The biggest time issue was in the aggregate itself.  The expand was almost not time at all.  We still might want to do something like because it would reduce memory in theory.  But even then I ma not sure it is worth it.
