### ISSUE TITLE
[FEA] Add retry to GpuShuffleCoalesceExec

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#8501]
**Is your feature request related to a problem? Please describe.**
We do not support retry in GpuShuffleCoalesceExec. We should be able to easily support retry.

**Comment by firestarman** [comment]
Seems `GpuShuffleCoalesceExec` already supports retry. According to the following call stack, we have already added retry support in `HostConcatResultUtil.getColumnarBatch`.

```
GpuShuffleCoalesceExec
-> GpuShuffleCoalesceIterator
   -> HostConcatResultUtil.getColumnarBatch
```

**Comment by abellina** [comment]
@firestarman, I am sorry I think you are right. Looking back at the report, it was for 23.08 but the line numbers aren't matching with what we have in `HostConcatResultUtil`. It looks like this was resolved in https://github.com/NVIDIA/spark-rapids/pull/8009. I'll close this!
