### ISSUE TITLE
[FEA] Support spark.sql.legacy.parquet.datetimeRebaseModeInWrite=LEGACY

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#8596]
I wish we can support spark.sql.legacy.parquet.datetimeRebaseModeInWrite=LEGACY.

One example is when using delta write on databricks, if spark.sql.legacy.parquet.datetimeRebaseModeInWrite=LEGACY, the delta write will fallback to CPU.

**Comment by tgravescs** [comment]
Note that the new config name to use for this is actually spark.sql.parquet.datetimeRebaseModeInWrite. The spark.sql.legacy.parquet.datetimeRebaseModeInWrite version works in 3.1 but was deprectaed in 3.2 for the spark.sql.parquet.datetimeRebaseModeInWrite.

**Comment by viadea** [comment]
This feature request is for both date and timestamp data types.

**Comment by ttnghia** [comment]
This is part of https://github.com/NVIDIA/spark-rapids/issues/436.
