### ISSUE TITLE
[FEA] look at reordering aggregation keys to match sort internally

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8634]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish the RAPIDS Accelerator for Apache Spark would [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by mattahrens** [comment]
Dup: https://github.com/NVIDIA/spark-rapids/issues/8635
