### ISSUE TITLE
[BUG] AWS Databricks 12.2 integration tests failed due to Iceberg check

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8636]
The AWS Databricks 12.2 integration test run failed with an error in run_it.sh
```
[2023-06-29T13:44:32.113Z] + [[ iceberg == \i\c\e\b\e\r\g ]]
[2023-06-29T13:44:32.113Z] ++ cut -d. -f1,2
[2023-06-29T13:44:32.113Z] ++ echo 3.3.2
[2023-06-29T13:44:32.113Z] + ICEBERG_SPARK_VER=3.3
[2023-06-29T13:44:32.113Z] + case "$SPARK_VER" in
[2023-06-29T13:44:32.113Z] Unexpected Spark version: 3.3.2
[2023-06-29T13:44:32.113Z] + echo 'Unexpected Spark version: 3.3.2'
[2023-06-29T13:44:32.113Z] + exit 1
```

**Comment by pxLi** [comment]
https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/jenkins/databricks/run_it.sh#L60-L70 (csputil usage)
is not synced up w/ 
https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/jenkins/databricks/test.sh#L80-L94

cc @NvTimLiu to help check if we could put this part in a common script

**Comment by NvTimLiu** [comment]
Let me follow up to put the shared script together for test.sh and run_it.sh

@jlowe  As we skipped iceberg tests on databricks : [ db-skip iceberg
](https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/integration_tests/src/main/python/conftest.py#L202-L203)
  
we can remove iceberg script, or keep it there for later use?

https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/jenkins/databricks/run_it.sh#L60-L70

https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/jenkins/databricks/test.sh#L80-L94

**Comment by NvTimLiu** [comment]
Close this issue as the iceberg script was removed from test files

Follow up https://github.com/NVIDIA/spark-rapids/issues/8636#issuecomment-1614100698 in the new issue https://github.com/NVIDIA/spark-rapids/issues/8779
