### ISSUE TITLE
[BUG] Dataproc spark-rapids.sh fails due to cuda driver version issue

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#8662]
**Describe the bug**
I'm trying to deploy to Dataproc but its failing with error:

E: Version '530.30.02-1' for 'cuda-drivers-535' was not found

It looks like we try to figure out the version to pass into cuda-drivers but the script is failing with the current versions.

$ dpkg-query -f '${Version}\n' -W nvidia-driver-535
535.54.03-0ubuntu0.20.04.4

Which doesn't match:

$apt-cache madison cuda-drivers | awk '{print $3}' | sort -r
535.54.03-1
530.30.02-1
525.85.12-1
525.60.13-1
525.125.06-1

The script check to find one that matches but instead of choosing 535.54.03-1 it tries 530.30.02-1 and fails.  If you use 535.54.03-1 that it works properly.

**Comment by tgravescs** [comment]
Note I'm using  --image-version=2.1-ubuntu20

**Comment by viadea** [comment]
@tgravescs What is the complete gcloud command you used for this issue? I am assuming you want to specific a specific NVIDIA driver version right?

**Comment by viadea** [comment]
@tgravescs  Did you disable secure boot when you create this cluster?

**Comment by viadea** [comment]
In https://github.com/NVIDIA/spark-rapids/pull/8632 , @rwlee added the steps to include `--no-shielded-secure-boot` option if it is Dataproc 2.1. I hope this can address this issue.

**Comment by tgravescs** [comment]
I was using AB scripts which do disable secure boot:

 if self.version == "2.1":
            cmd = cmd + " --no-shielded-secure-boot "

**Comment by viadea** [comment]
Recently @SurajAralihalli  has refactored the spark-rapids.sh and we have tested this script multiple times without any issues. Shall we close this bug? @tgravescs
