### ISSUE TITLE
[FEA] Support min and max for arrays

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8668]
**Is your feature request related to a problem? Please describe.**
Some changes went in recently where min and max hash aggregates were added for structs with arrays in them, but not arrays by themselves.

https://github.com/NVIDIA/spark-rapids/pull/8638

This covers most of https://github.com/NVIDIA/spark-rapids/issues/3153 but does not cover everything we need for a customer.  In the short term I can work around it by hacking things up and wrapping the array with a struct.  But that is not a good long term solution to the problem.

**Describe the solution you'd like**
I would like CUDF and us to support group by aggregations for min and max on arrays at the top level.

**Comment by ttnghia** [comment]
Depends on https://github.com/rapidsai/cudf/pull/13676.

**Comment by ttnghia** [comment]
BTW, this should be duplicate of https://github.com/NVIDIA/spark-rapids/issues/8668.
