### ISSUE TITLE
[AUDIT][SPARK-42779][SQL] Allow V2 writes to indicate advisory shuffle partition size

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#8680]
Below PR adds an API for data sources to indicate the advisory partition size for V2 writes. Even though this is applicable only when AQE is enabled and we don't have code where we support `advisorySize`, we may have to update the case class of GpuShuffleExchageExec for Spark-3.5+ since it's updated now
```
case class ShuffleExchangeExec(
    override val outputPartitioning: Partitioning,
    child: SparkPlan,
    shuffleOrigin: ShuffleOrigin = ENSURE_REQUIREMENTS,
    advisoryPartitionSize: Option[Long] = None)
```

Apache Spark commit - https://github.com/apache/spark/commit/59e0066dc7
Follow-on issue - https://github.com/apache/spark/commit/2fece076a3

**Comment by razajafri** [comment]
Fixed as part of https://github.com/NVIDIA/spark-rapids/pull/8969
