### ISSUE TITLE
Schema evolution: Test ORC reads after table schema changes

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#8692]
Test that ORC partitions written to tables after the main table's schema has changed are still readable.

- [x] Old partitions created before columns are appended to the table. New columns should have nulls in the old partitions.
- [ ] Old partitions created before columns are added in the middle of the table. New columns should have nulls in the old partitions.
- [ ] Old partitions created before columns are dropped at the end of the table. New columns should have nulls in the old partitions.
- [ ] Old partitions created before columns are dropped in the middle of the table. New columns should have nulls in the old partitions.
- [ ] Old partitions created before columns are renamed.
- [ ] Old partitions created before new columns are added with the names of previously dropped columns. New columns should have nulls in the old partitions.

**Comment by jlowe** [comment]
I can do the tests for adding columns, but I don't think we can do the other tests.  Dropping, renaming, or replacing columns requires DataSource V2 which Spark SQL does not support for raw ORC (or Parquet).
