### ISSUE TITLE
Add test for the timestamp error case described in SPARK-10177

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#8693]
Apache JIRA: https://issues.apache.org/jira/browse/SPARK-10177

Refer to [`ParquetHiveCompatibilitySuite.scala#L97`](https://github.com/apache/spark/blob/85e252e8503534009f4fb5ea005d44c9eda31447/sql/hive/src/test/scala/org/apache/spark/sql/hive/ParquetHiveCompatibilitySuite.scala#L97).

We just need to add a PySpark test to check that the following data is written/read the same on `spark-rapids` and Apache Spark:
```sql
CREATE TABLE ts_test STORED AS PARQUET
AS SELECT CAST("2015-01-01 00:00:00" AS TIMESTAMP) problem_timestamp;
```

**Comment by razajafri** [comment]
This seems like the bug was in DateTimeUtils as evident from the comment [here](https://issues.apache.org/jira/browse/SPARK-10177). Considering that is this still a valid test case that we need?

**Comment by mythrocks** [comment]
Hmm. In hindsight, probably not top priority. I'd still add it, just in case there's a similar bug in CUDF, since it can be tested with a single timestamp record.

**Comment by mythrocks** [comment]
Sorry for the red-herring in the description. I have corrected the suggested SQL to include a column alias.
