### ISSUE TITLE
[BUG] nightly integration test failed OOM kill in JDK11 ENV

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#8729]
**Describe the bug**
internal pipeline rapids_integration-dev-github #758 #762

the executor failed test cases due to lost executor.
After investigation, we found that the memory usage of testing w/ jdk11 is abnormal, and it exceeded the resource limitation of our test ENV.

all other combinations took around 45~50G memory at most, 
but jdk11 one consumed more than 55G and caused the OOM kill, this seems always reproducible
![image](https://github.com/NVIDIA/spark-rapids/assets/8086184/2772a1c9-aafb-4827-babb-0275c1dbcb4d)

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by andygrove** [comment]
The default garbage collector changed to G1 in JDK 11. JDK 8 default is Parallel Scan.

@pxLi Could you try setting `spark.executor.extraJavaOptions="-XX:+UseParallelGC"` and see if that helps?

**Comment by pxLi** [comment]
> The default garbage collector is different for different JDK versions:
> 
> * JDK 8 default is Parallel.
> * JDK 11 default is G1
> * JDK 12+ default is Shenandoah
> 
> @pxLi Could you try setting `spark.executor.extraJavaOptions="-XX:+UseParallelGC"` and see if that helps?

sure, I will take a try in the CI

**Comment by pxLi** [comment]
no more oom reporting. closing this for now
