### ISSUE TITLE
[FEA] Benchmark runs should record plugin and dependency versions

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#873]
**Is your feature request related to a problem? Please describe.**
When recording benchmark results, we should capture information about the version of the software that was used to produced these benchmarks.

**Describe the solution you'd like**
The JSON file should clearly show which version of the plugin and dependencies such as cuDF were used.

**Describe alternatives you've considered**
With the way my environment is set up, I do see the versions being used because I have environment variables such as `SPARK_RAPIDS_PLUGIN_JAR` and `CUDF_JAR` pointing the JARs that I am using. We could standardize on this approach.

**Additional context**
None.

**Comment by sameerz** [comment]
Perhaps we can use the log message added from https://github.com/NVIDIA/spark-rapids/issues/764

**Comment by jlowe** [comment]
The jar used is logged in the output log of the NDS benchmarks run.  Note that benchmarks have been moved to https://github.com/NVIDIA/spark-rapids-benchmarks.
