### ISSUE TITLE
ORC reads at scale with all null values: Like `OrcQuerySuite.scala#L173`, but with large number of rows.

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#8731]
Add test case according to [Spark test case](https://github.com/apache/spark/blob/v3.4.0/sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/orc/OrcQuerySuite.scala#L173)

```
  test("save and load case class RDD with `None`s as orc") {
    val data = (
      Option.empty[Int],
      Option.empty[Long],
      Option.empty[Float],
      Option.empty[Double],
      Option.empty[Boolean]
    ) :: Nil

    withOrcFile(data) { file =>
      checkAnswer(
        spark.read.orc(file),
        Row(Seq.fill(5)(null): _*))
    }
  }
```

**Comment by res-life** [comment]
It's from [#8666 ](https://github.com/NVIDIA/spark-rapids/issues/8666)

**Comment by mythrocks** [comment]
#8773 is a start, certainly. But it would be good to test this with a large number of rows. 

I was thinking, say 1M rows. (At 10K rows per group, by default, this should correspond to 100 row groups.)

We can test reading from the file in different scenarios/predicates:
1. `SELECT * FROM my_large_table`
2. `SELECT * FROM my_large_table WHERE value = 5`
3. `SELECT COUNT(*) FROM my_large_table WHERE value IS NOT NULL`
4. `SELECT * FROM my_large_table WHERE value IS NULL`
