### ISSUE TITLE
[BUG] [Databricks 12.2] RapidsDeltaWrite queries that reference internal metadata fail to run

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#8756]
**Describe the bug**
The plugin creates query plans that contain a `RapidsDeltaWriteExec` stub and later replaces it with a `GpuRapidsDeltaWriteExec`. However, if the entire query falls back to CPU before this replacement occurs then the query fails at runtime because `RapidsDeltaWriteExec` is not executable.

One use case that can trigger this is when the read query references internal metadata columns in a file scan, such as `_databricks_internal_edge_computed_column_skip_row`. There may be other use cases that we have yet to discover.

Example plan:

```
RapidsDeltaWrite
+- Project [a#15918, b#15919, c#15920]
   +- Filter (b#15919 >= d)
      +- Filter ((_databricks_internal_edge_computed_column_skip_row#16180 = false) AND UDF())
         +- FileScan parquet [b#15919,c#15920,_databricks_internal_edge_computed_column_skip_row#16180,a#15918] Batched: true, DataFilters: [], Format: Parquet, Location: TahoeBatchFileIndex(1 paths)[file:/tmp/pyspark_tests/0510-200844-r43n977z-10-59-236-39-master-122..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<b:string,c:string,_databricks_internal_edge_computed_column_skip_row:boolean>
```

Failure:

```
23/07/19 16:51:46 WARN GpuOverrides: Can't replace any part of this plan due to: Delta Lake metadata queries are not efficient on GPU
23/07/19 16:51:46 ERROR GpuFileFormatWriter: Aborting job 6b5305df-b442-4e05-92ba-3509be4f10a5.
java.lang.IllegalStateException: Should have been replaced with a GPU node before execution
```

**Steps/Code to reproduce bug**
Enable `test_delta_deletion_vector` test on Databricks 12.2

**Expected behavior**
Query should not fail.

**Environment details (please complete the following information)**
N/A

**Additional context**

**Comment by jlowe** [comment]
It was never intended for `RapidsDeltaWriteExec` to be executable.  If `RapidsDeltaWriteExec` is trying to be executed then that means there's a plan tagging bug in the code that decided to place that node in the plan.

**Comment by andygrove** [comment]
Here is some more information from some debugging I have been doing.

We see a `DeleteCommand` and convert it to GPU:

```
DeleteCommandEdgeMeta.tagSelfForGpu(): command=DeleteCommandEdge com.databricks.sql.transaction.tahoe.DeltaLog@238fe7dc, (b#2511 < d)
   +- SubqueryAlias spark_catalog.delta.`/tmp/pyspark_tests//0510-200844-r43n977z-10-59-160-63-master-21088-230952237//DELTA_DATA/GPU`
      +- Relation [a#2510,b#2511,c#2512] parquet
, target=SubqueryAlias spark_catalog.delta.`/tmp/pyspark_tests//0510-200844-r43n977z-10-59-160-63-master-21088-230952237//DELTA_DATA/GPU`
+- Relation [a#2510,b#2511,c#2512] parquet
```

During execution in `GpuDeleteCommand.performDelete()`, the query gets transformed to add a filter on `_databricks_internal_edge_computed_column_skip_row` and there is a call to `GpuOptimisticTransaction.writeFiles` which inserts a `RapidsDeltaWrite`, even though the query is no longer supported on GPU.

The child query of `RapidsDeltaWriteExec` at this point is the following CPU query:

```
*(1) Project [a#2510, b#2511, c#2512, _change_type#2708, isnotnull(_change_type#2708) AS __is_cdc#2714]
+- *(1) Project [a#2510, b#2511, c#2512, if ((b#2511 >= d)) null else delete AS _change_type#2708]
   +- *(1) Filter ((_databricks_internal_edge_computed_column_skip_row#2776 = false) AND UDF())
      +- *(1) ColumnarToRow
         +- FileScan parquet [a#2510,b#2511,c#2512,_databricks_internal_edge_computed_column_skip_row#2776] Batched: true, DataFilters: [], Format: Parquet, Location: TahoeBatchFileIndex(1 paths)[file:/tmp/pyspark_tests/0510-200844-r43n977z-10-59-160-63-master-247..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<a:int,b:string,c:string,_databricks_internal_edge_computed_column_skip_row:boolean>
```
