### ISSUE TITLE
Statistics tests for Parquet files written by GPU

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8762]
When the GPU writes a Parquet file, it's important to get the file, row group, and page statistics correct.  We should have better tests, ideally including tests at larger scale than a few thousand rows typical for unit/integration tests, for verifying the statistics written to the Parquet file are correct.

**Comment by res-life** [comment]
Filed a cuDF issue: [Parquet float/double statistic is wrong when float/double column contains NaN](https://github.com/rapidsai/cudf/issues/13948)

**Comment by res-life** [comment]
Filed an issue: [Writing Parquet map(map) column can not set the outer key as non-null](https://github.com/NVIDIA/spark-rapids/issues/9129)

**Comment by res-life** [comment]
build
