### ISSUE TITLE
Statistics tests for ORC files written by GPU

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8763]
When the GPU writes an ORC file, it's important to get the file, row group, and page statistics correct. We should have better tests, ideally including tests at larger scale than a few thousand rows typical for unit/integration tests, for verifying the statistics written to the ORC file are correct.

**Comment by res-life** [comment]
Found cuDF issue: https://github.com/rapidsai/cudf/issues/13837

**Comment by res-life** [comment]
Link other cuDF ORC statistic issues:
https://github.com/rapidsai/cudf/issues/13793
https://github.com/rapidsai/cudf/issues/13817
