### ISSUE TITLE
[AUDIT][SPARK-43302][SQL] Make Python UDAF an AggregateFunction

### ISSUE THREAD

**Issue by parthosa** [NVIDIA/spark-rapids#8767]
The PR introduces a new `PythonUDAF` expression, extending `AggregateFunction`, to handle PythonUDFs as normal aggregate functions. This change affects APIs of pandas related execs such as `AggregateInPandasExec`, `WindowInPandasExec`.

Apache Commit - [apache/spark@b496edb](https://github.com/apache/spark/commit/b496edb5d4#diff-727250955192fa5d47ccfc7a7c98d87e7cb410f5cd39a44d5498c938a5a98fb4)

**Comment by mattahrens** [comment]
Testing scope: verify fallback to CPU happens.
