### ISSUE TITLE
[BUG] FileCacheIntegrationSuite intermittent failure

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#8776]
**Describe the bug**

PR https://github.com/NVIDIA/spark-rapids/pull/8674 had the following build failure, which is unrelated to changes in the PR. The test only failed once and succeeded on the next run.

```
FileCacheIntegrationSuite:^[[0m
- filecache metrics v1 Parquet^[[0m
- filecache metrics v2 Parquet^[[0m
- filecache metrics v1 ORC *** FAILED ***^[[0m
  0 was not greater than 0 (FileCacheIntegrationSuite.scala:175)
```

**Steps/Code to reproduce bug**
I don't know how we can reproduce this.

**Expected behavior**
Should have consistent behavior

**Environment details (please complete the following information)**
CI

**Additional context**

**Comment by pxLi** [comment]
```
[2023-09-05T05:39:45.263Z] - filecache metrics v2 ORC *** FAILED ***
[2023-09-05T05:39:45.263Z]   Expected 1, but got 0 (FileCacheIntegrationSuite.scala:183)
```

seems more frequent than before

**Comment by firestarman** [comment]
I also met one.
e.g. rapids_premerge-github, build ID:7887

**Comment by andygrove** [comment]
It looks like this may still be happening? https://github.com/NVIDIA/spark-rapids/pull/9234#issuecomment-1718203479

**Comment by jlowe** [comment]
Odd, I cannot reproduce this locally.  However from the error message in the comment, I think I know what's going on.  I'll put up a PR shortly, apologies for the inconvenience.
