### ISSUE TITLE
[FEA] Match Spark's NaN handling in `collect_set` for nested type contains float/double

### ISSUE THREAD

**Issue by thirtiseven** [NVIDIA/spark-rapids#8808]
`collect_set` function currently does not support NaNs in struct[Array(Double)] or struct[Array(Float)] types. It is because Spark handling NaN's equality by different way for non-nested float/double and float/double in nested types. 

When we use non-nested versions of floats and doubles, NaN values are considered unequal, but when we collect sets of nested array versions, NaN is considered equal on the CPU.

```
>>> from pyspark.sql.functions import collect_set
>>> df1 = spark.createDataFrame([(1.0,), (float("nan"),), (float("nan"),)], ["value"])
>>> df1.agg(collect_set("value")).show(truncate=False)
+------------------+
|collect_set(value)|
+------------------+
|[1.0, NaN, NaN]   |
+------------------+

>>> df2 = spark.createDataFrame([([1.0, float("nan")],), ([1.0, float("nan")],), ([1.0, 2.0],)], ["value"])
>>> df2.agg(collect_set("value")).show(truncate=False)
+------------------------+
|collect_set(value)      |
+------------------------+
|[[1.0, 2.0], [1.0, NaN]]|
+------------------------+
>>>
```

In cuDF, we can determine `collectSet`'s `NaNEquality` to `UNEQUAL` or `ALL_EQUAL`. So we can't match Spark's different behaviors at the same time by directly calling cuDF.

**Comment by revans2** [comment]
We might be able to do some complicated checks and figure out which to set dynamically.

If we are doing a collect set on an float, then we set NaNEquality to UNEQUAL, but if we are doing a collect set on anything else we set it to ALL_EQUAL.  I don't think there is ever a case when we could have both in the same collect_set operation.
