### ISSUE TITLE
[TEST] Test dictionary encoding in ORC file for nested types with lots of rows.

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#8809]
**Describe the bug**
As Bobby said, we have run into situations where having too many rows in nested columns causes problems with the dictionary.
Create this issue to follow up.

This is from the [comment](https://github.com/NVIDIA/spark-rapids/pull/8798#discussion_r1273730824)
Linked into the epic issue #8666

**Comment by mythrocks** [comment]
Should the title read "Test Dictionary Encoding... "?

**Comment by res-life** [comment]
The default values of Orc conf are: 
|config|default|description|
|:-|:-|:-|
|orc.dictionary.key.threshold|0.8|If the number of distinct keys in a dictionary is greater than this fraction of the total number of non-null rows, turn off  dictionary encoding.  Use 1 to always use dictionary encoding.|
|orc.dictionary.early.check|true|If enabled dictionary check will happen after first row index stride (default 10000 rows) else dictionary check will happen before writing first stripe. In both cases, the decision to use dictionary or not will be retained thereafter.|
|orc.row.index.stride|10000|Define the default ORC index stride in number of rows. (Stride is the number of rows an index entry represents.)|

For more details, refer to [OrcConf](https://github.com/apache/orc/blob/v1.7.4/java/core/src/java/org/apache/orc/OrcConf.java)
Above configs means: 
If the cardinality is less than 0.8 * 10000 in the first stride, then use dictionary encoding. Here the 10000 is stride size.

And only String column will use dictionary encoding, other types do not use.
Refer to StringBaseTreeWriter and other writers in this [link](https://github.com/apache/orc/tree/v1.7.4/java/core/src/java/org/apache/orc/impl/writer)

IMO, for the nested types, we can skip to test the dictionary encoding.
@mythrocks @revans2

**Comment by res-life** [comment]
Close it via https://github.com/NVIDIA/spark-rapids/pull/8920
