### ISSUE TITLE
[FEA] Write entry point to generate data for scale testing.

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8813]
**Is your feature request related to a problem? Please describe.**
As a part of https://github.com/NVIDIA/spark-rapids/issues/8811 we should have some code that can generate a dataset at different scale factors and complexities for scale testing. The data should be generated using the big data gen framework in the integration tests jar, and should probably just sit next to it for simplicity sake.

When I say scale factor this is going to directly relate to the number of rows generated for various tables and will be called out for each table generated.

The complexity will change the number of keys in various key groups and the number of ride along columns for some operations. For simplicity sake the number will correspond to the number of columns. So a complexity of 300 means many of the queries will use 300 keys and/or 300 ride along columns. Some queries may only use a subset of the keys/columns. 

It is assumed that the scale tests and data being generated will change over time.  As the RAPIDs accelerator supports more nested types in joins or sorts new data types will be added to the definitions of the row groups and tables. As such a version number is also going to be a part of what is generated.

There is no attempt to map these tables or values directly to real world situations. This is a completely synthetic approach.

Before getting too much further, there will be a convention on where the tables are written so that multiple different versions can co-exist.  The base directory name will be `SCALE_${scale_factor}_${complexity}_${format}_${version}` and the tables will be written to child directories names with the same name as the table.

The version will correspond to an arbitrary version number that we use for consistency. We don't want to run tests against the wrong version of the data.  The format is the file format used. This could be parquet or orc to start out with, but formats such as deltalake, iceberg, or hudi could also be supported in the future.

Table naming:

Tables will be given a lower case letter prefix then an underscore followed by an arbitrary lower case suffix. The letter is there to limit us to 26 tables. If we need more than 26 we are doing something wrong.

Key group naming:

Key groups don’t have names, but are all assigned numeric IDs starting with 1. The key group id may or may not show up in the names of columns, but it should remain consistent when generating the data.

Column naming:

The names of key columns will be in a few forms. 
   * If the column is the primary key for a table, where it is a unique key per row, then it will be named `primary_${table_prefix}`.
   * If the column is intended to be joined with the primary key from another table it will be names `${table_prefix}_foreign_${foreign_table_prefix}`
   * If the key is a part of a keygroup that can be joined with other tables it will be named `${table_prefix}_key${key_group}_${column_number}` where `${column_number}` is the number of the column in the key group.
   * If a column is a data column, one that has processing done on it, or is just a ride-along column, then the name will be `${table_prefix}_data_${column_number}` where `${column_number}` is the number of the column in the set of data columns for the table.
   * If a data column has a very special purpose it can be named `${table_prefix}_data_${description}` instead to distinguish it.

It is assumed that if specific data types are needed for individual tests that the schema of the table will be used to find compatible columns.

Key Groups:

There are several different key groups that we want to test. They are listed below. What is not listed below is the overlap in key groups. That will be handled in the table descriptions themselves.
   1. The primary key for table a. In table a each row will be unique
   2. Adjusted key group. The number of columns will correspond to the complexity. The types of the columns should be selected from the set {string, decimal(7, 2), decimal(15, 2), int, long, timestamp, date, struct<num: long, desc: string>} 
   3. 3-column key group with the types string, date, long. 
   4. 1 column that is an int with a unique count of 5

Ride-along/Data Columns:

Unless specified columns are going to be generated with the default random value ranges. These data values should initially come from the set of types `{int, long, Decimal(7, 2), Decimal(19, 4), string, map<string, struct<lat: Decimal(7,4), lon: Deicmal(7, 4)>>, timestamp, date}` and should be selected in a deterministic way.

  1. `a_facts`: Each scale factor corresponds to 10,000 rows
      * `primary_a` the primary key from key group 1
      * key group 4
      * `a_data_low_unique_1` data column that is a long with a unique count of 5
      * `a_data_low_unique_len_1` data column that is a string with variable length ranging from 1 to 5 inclusive (even distribution of lengths)
      * `complexity` data columns
   2. `b_data`: Each scale factor corresponds to 1,000,000 rows. (The row group size should be configured to be 512 MiB when writing parquet or equivalent when writing ORC)
      * `b_foreign_a` Should overlap with `a_facts.primary_a` about 99% of the time
      * key group 3 with 3 columns (The unique count should be about 99% of the total number of rows).
      * 10 data columns of various types
      * 10 decimal(10, 2) columns with a relatively small value range
  3. `c_data`: Each scale factor corresponds to 100,000 rows.
      * `c_foreign_a` Should overlap with `a_facts.primary_a` about 50% of the time
      * key group 2 columns up to the complexity (each key should show up about 10 times)
      * `c_data_row_num_1` 1 data column that is essentially the row number for order by tests in window
      * 5 data columns
      * 5 numeric data columns
   4. `d_data`: Each scale factor corresponds to 100,000 rows.
      * key group 2 complexity columns (each key should show up about 10 time, but the overlap with `c_data` for key group 2 should only be about 50%)
      * 10 data columns
   5. `e_data`: Each scale factor corresponds to 1,000,000 rows.
      * key group 3 with 3 columns (the unique count should be about 99% of the total number of rows and overlap with `b_data` key group 3 by about 90%).
      * 10 data columns
   6. `f_facts`: Each scale factor corresponds to 10,000 rows
      * key group 4
      * `f_data_low_unqie_1` data column that is a long with a unique count of 5 but overlap with `a_data_low_unique_1` is only 1 of the 5.
      * `f_data_low_unique_len_1` data column that is a string with variable length ranging from 1 to 5 inclusive (even distribution of lengths)
      * `f_data_row_num_1` long column which is essentially the row number for window ordering
      * complexity/2 data columns
   7. `g_data`: Each scale factor corresponds to 1,000,000 rows. (The row group size should be configured to be 512 MiB)
      * key group 3 with 3 columns (should be skewed massively so there are a few keys with lots of values and a long tail with few).
      * `g_data_enum_1` 1 string column with 5 unique values in it (an ENUM of sorts)
      * `g_data_row_num_1` 1 long data column that is essentially the row number for range tests in window.
      * 20 byte data columns
      * 10 string data columns

**Comment by wjxiz1992** [comment]
Before making the PR, I'd like to show basic code structure, user input arguments design here so we won't have very large divergence when we see the code, and make it easy to modify.

code structure:
 - The code will be placed at `integration_tests/src/com.nvidia.spark.rapids/scaletest/`, 
 - The entry main function is at `DataGen` class.
 - In the class, it's more like a Spark application with big data gen tool. we will define the table schema one by one.

Initial supported input arguments:
 - `--scale_factor`, 
 - `--complexity`, 
 - `--tables`(be able to generate specific one or more tables, if not specified, generate all tables. current tables list: ..........)
 - `--output_dir`
 - `--format` (parquet, orc first)
 - `--version` (user define this by himself, but I doubt if we should just fix it with the plugin version e.g. 2308 2310 2312 etc ? I don't know)

The initial usage: 
- build:  the same `mvn package ...` used to build the big data gen tool
- submit: `spark-submit ..... --class com.nvidia.spark.rapids.scaletest.DataGen --scale_factor 100 --complexity 300 --output_dir s3a://<user's output_dir path>/SCALE_${scale_factor}_${complexity}_${format}_${version}`
  
please help review this design let me know if it's ok. If anything important missing, just ping me and I'll update.

**Comment by wjxiz1992** [comment]
Update: 
the DataGen tool has been moved to a separate module, so the new code will be put there in the new module along with the DataGen tool

**Comment by wjxiz1992** [comment]
When generating and writing a `date` value in parquet, the following error is thrown:
```
Caused by: org.apache.spark.SparkException: Task failed while writing rows.
        at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:655)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:358)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$22(FileFormatWriter.scala:266)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:136)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.spark.SparkUpgradeException: You may get a different result due to the upgrading to Spark >= 3.0:
writing dates before 1582-10-15 or timestamps before 1900-01-01T00:00:00Z
into Parquet INT96 files can be dangerous, as the files may be read by Spark 2.x
or legacy versions of Hive later, which uses a legacy hybrid calendar that
is different from Spark 3.0+'s Proleptic Gregorian calendar. See more
details in SPARK-31404. You can set "spark.sql.parquet.int96RebaseModeInWrite" to "LEGACY" to rebase the
datetime values w.r.t. the calendar difference during writing, to get maximum
interoperability. Or set "spark.sql.parquet.int96RebaseModeInWrite" to "CORRECTED" to write the datetime
values as it is, if you are 100% sure that the written files will only be read by
Spark 3.0+ or other systems that use Proleptic Gregorian calendar.

```

I tried to put the recommended config `spark.sql.parquet.int96RebaseModeInWrite=LEGACY` or `spark.sql.parquet.int96RebaseModeInWrite=CORRECTED` to suggested value but still getting the same error.


The weired thing is, I cannot reproduce this when creating a small dataframe:

shell command:
```
~/spark-3.3.2-bin-hadoop3/bin/spark-shell \
--jars ./target/datagen_2.12-23.10.0-SNAPSHOT-spark332.jar \
--master spark://allxu-System-Product-Name:7077 \
--conf spark.driver.memory=10G \
--conf spark.executor.memory=32G \
--conf spark.sql.parquet.datetimeRebaseModeInWrite=LEGACY
```

```
scala> import org.apache.spark.sql.tests.datagen._
import org.apache.spark.sql.tests.datagen._

scala> val dbgen = new DBGen()
dbgen: org.apache.spark.sql.tests.datagen.DBGen = org.apache.spark.sql.tests.datagen.DBGen@76ed5e7e

scala> val users = dbgen.addTable("users", "id date", 50)
users: org.apache.spark.sql.tests.datagen.TableGen = org.apache.spark.sql.tests.datagen.TableGen@61d4bc03

scala> val df = users.toDF(spark)
df: org.apache.spark.sql.DataFrame = [id: date]

scala> df.write.parquet("date_lipu_2")

scala> df.show()
+--------------+
|            id|
+--------------+
|-5498467-02-06|
|+1208993-08-19|
|-1953572-12-09|
|+1405162-08-27|
|-4204716-11-10|
|+1530054-04-28|
|-5781336-10-31|
|-1029497-03-21|
|+4910236-10-29|
|-2314681-09-08|
|-2804156-05-21|
|+1434434-01-29|
|-5072375-12-28|
| +664412-10-10|
|-5033259-11-23|
|-5084047-10-11|
|-2808020-05-09|
|-4269481-01-14|
|+2705652-08-26|
|-4050200-08-25|
+--------------+
only showing top 20 rows

```
No error thrown.
