### ISSUE TITLE
[FEA] Write Initial Set of scale test queries + application

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8814]
**Is your feature request related to a problem? Please describe.**
We need some tests if we are going to run scale tests. This is to write at least an initial round of them.

This depends on https://github.com/NVIDIA/spark-rapids/issues/8813, at least done enough that we can write a few tests.

Really a lot of this is to get any framework in place needed to execute these tests. But it should not be a lot.

Ideally we want to run each test as a stand alone application, but nothing should prevent us from running several queries one after another in a single application.

The application should take as input a base input location, the scale factor, complexity, and format of the test being run along with the query number(s). And a base output location.

It would use the same convention used by the data generation code (https://github.com/NVIDIA/spark-rapids/issues/8813) to know where to look for the data.

> The base directory name will be `SCALE_${scale_factor}_${complexity}_${format}_${version}` and the tables will be written to child directories names with the same name as the table.

The version should come from the code so that if there is any coupling between the data generated and the queries we can detect it early on.

Once that is done it should set up a a spark context, read the tables and setup the views to run the tests, then run the selected queries.

In the future we will want/need to extend this with some added monitoring.  For now we are really only going to care if the test ran or not.  Validating the results are correct will be separate from this too.

The initial queries I want to write here are the following, note that I am using pseudo SQL for some of these so please don't just copy/past the SQL and think that it all works. The results of these queries should be written out to the output location in a sub directory under it that is the same as the query number. The queries might need to be altered slightly so each column has a name that can be written out to parquet or orc.  By default the output written should match the input format used.

q1: Inner join with lots of ride along columns.
```
SELECT a_facts.*, b_data_{1-10} FROM b_data JOIN a_facts WHERE primary_a = b_foreign_a
```
q2: Full outer join with lots of ride along columns
```
SELECT a_facts.*, b_data_{1-10} FROM b_data FULL OUTER JOIN a_facts WHERE primary_a = b_foreign_a
```
q3: Left outer join with lots of ride along columns
```
SELECT a_facts.*, b_data_{1-10} FROM b_data LEFT OUTER JOIN a_facts WHERE primary_a = b_foreign_a
```

Other queries will be added later on in other issues.

**Comment by revans2** [comment]
I want to add that this should not try and set default configs in any way. That should be determined by the scripts that will call into this.

**Comment by revans2** [comment]
Also the application should ideally have a timeout associated with it per query.  If a single query takes longer than the specified timeout it should exit with an error code.

**Comment by wjxiz1992** [comment]
Some discussion for the application.
1. Python or Scala. The application is about running queries so I guess it should be put into `integration_tests` not the `datagen` folder, is that expected?  Which type of code do you prefer and to submit to Spark? a Python script or a jar?  According to previous experience, python is quick to write but not very well supported for any advanced development, for example when we want to add custom listener to Spark, we still need to write scala and then bridge them(https://github.com/NVIDIA/spark-rapids-benchmarks/tree/dev/nds/jvm_listener/src/main/scala/com/nvidia/spark/rapids/listener and https://github.com/NVIDIA/spark-rapids-benchmarks/tree/dev/nds/python_listener). But at the initial step, both of them are simple.
2. queries embeded into code or in external text file? In NDS test, the queries are generated into external files and python code will read the files to extract those queries. It's better to put them in external if we want to extend them easily. But if we don't want users to modify the queries we defined,  it's better to put them into code.
