### ISSUE TITLE
[AUDIT][SPARK-43039][SQL] Support custom fields in the file source _metadata column

### ISSUE THREAD

**Issue by parthosa** [NVIDIA/spark-rapids#8819]
This change allows `FileFormat` instances to define the schema of the `_metadata`. This enables custom file formats to add their own fields to the `_metadata` column. 

This change could affect our datasource classes.

Apache Commit - [apache/spark@a31ac0492a](https://github.com/apache/spark/commit/a31ac0492a#diff-2d7ec6604810e1be58ca7852ec389853c143b684894f2390ffe07f96701d2219)

**Comment by mattahrens** [comment]
Need to validate that we fallback properly.

**Comment by razajafri** [comment]
Since we don't support custom file formats on the GPU we should fallback. As per Matt's comment, this still needs to be verified.

**Comment by razajafri** [comment]
Upon looking into this further the change in FileFormat will impact it's children ParquetFileFormat but we should get the change for free. The change is also backward-compatible.

**Comment by razajafri** [comment]
Upon looking into this further the change in FileFormat will impact child class ParquetFileFormat but we should get the change for free. The change is also backward-compatible.

**Comment by razajafri** [comment]
This change in Spark not only changes the `FileFormat` it also makes changes to the `getPartitionedFile` which needs to be addressed for Spark 4.0
