### ISSUE TITLE
[BUG] Issue in memory allocation when using GPUs with 96+ GB of memory

### ISSUE THREAD

**Issue by mattahrens** [NVIDIA/spark-rapids#8837]
When running Spark RAPIDS with a GPU with 96 GB of memory, this issue occurs on start-up: 

```
GpuDeviceManager: Initializing RMM ASYNC pool size = 93347.8125 MB on gpuId 0
...
java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc: out_of_memory: CUDA error at: ...//spark-rapids-jni/thirdparty/cudf/cpp/build/_deps/rmm-src/include/rmm/mr/device/cuda_async_view_memory_resource.hpp:121: cudaErrorMemoryAllocation out of memory                                                                                           
        at ai.rapids.cudf.Rmm.newCudaAsyncMemoryResource(Native Method)                                                                                                                  
        at ai.rapids.cudf.RmmCudaAsyncMemoryResource.<init>(RmmCudaAsyncMemoryResource.java:35)                                      
        at ai.rapids.cudf.Rmm.initialize(Rmm.java:247)                                                                               
        at com.nvidia.spark.rapids.GpuDeviceManager$.initializeRmm(GpuDeviceManager.scala:353)                                       
        at com.nvidia.spark.rapids.GpuDeviceManager$.initializeMemory(GpuDeviceManager.scala:403)                                    
        at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpuAndMemory(GpuDeviceManager.scala:152)   
```

I can work around the issue by using the `spark.rapids.memory.gpu.allocSize` to a lower amount.  After debugging with RMM team, issue looks to be related to conversions between MB/MiB or GB/GiB values in our request for pool allocation.  

Here are relevant lines of code in GpuDeviceManager: https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala#L283-L284.

It is likely that this issue has always existed, but never encountered with previous GPUs with lower memory because of the GPU reserve memory that we allow.

**Comment by mattahrens** [comment]
Looks like Spark RAPIDS may be logging incorrectly in MB (instead of MiB) actual bytes it is allocating: https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDeviceManager.scala#L341-L342.  So this may be a lower-level issue related to bytes available returned by cuda in memGetInfo() call.  Needs more investigation.

**Comment by mattahrens** [comment]
Update: after working on a C++ repo, it looks like issue may be lower level.  Spark RAPIDS is properly requesting allocation for an amount based on amount of free memory returned by cudaGetMemInfo() minus a reserve (set by `spark.rapids.memory.gpu.reserve`, default of 640MB).

More investigation is pending.

**Comment by mattahrens** [comment]
Issue can be resolved by updating OS setting.  Steps:

```
# Need to do this before tests, it keeps a reference on the driver so we do not unload the SW state.
sudo nvidia-persistenced

# Initial value may be too high (e.g. in many GB)
cat /proc/sys/vm/min_free_kbytes 

# Update min free kbytes to be 1024 (1 MB)                                    
sudo sh -c 'echo 1024 > /proc/sys/vm/min_free_kbytes'

# New value of 1024 should show up
cat /proc/sys/vm/min_free_kbytes
```

**Comment by revans2** [comment]
I am really confused by this `min_free_kbytes`  is supposed to be for memory that is reserved by the system to handle interrupts or other threads that cannot block. This is CPU memory. I am really confused why having too much CPU memory reserved prevents us from allocating GPU memory.

**Comment by mattahrens** [comment]
Issue identified in CUDA driver, will be fixed in future CUDA release
