### ISSUE TITLE
[AUDIT][SPARK-42683] Automatically rename conflicting metadata columns

### ISSUE THREAD

**Issue by parthosa** [NVIDIA/spark-rapids#8842]
This PR fixes inaccessible metadata columns if they conflict with output column names. It automatically renames them and introducing a new `metadataColumn` method to access metadata columns. We should check if we need to handle similar scenario.

Apache Commit - [apache/spark@b85fe2bff3](https://github.com/apache/spark/commit/b85fe2bff3)

**Comment by mattahrens** [comment]
Need to verify we fallback properly.
