### ISSUE TITLE
[BUG] github actions CI messed up w/ JDK versions intermittently

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#8847]
**Describe the bug**
https://github.com/NVIDIA/spark-rapids/actions/runs/5685693307/job/15411113728 (should be jdk8 but running w/ jdk11)

not sure about the root cause here, seems a github action bug. 
I will try to setup an ENV to see if we could always repo and figure out the root cause

**Comment by pxLi** [comment]
in https://github.com/NVIDIA/spark-rapids/actions/runs/5687245548/job/15415371715

all targeting jdk11, but its still showing error `bootstrap class path not set in conjunction with -source 8`

```Run java -version && mvn --version && echo "ENV JAVA_HOME: $JAVA_HOME"
openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment Temurin-11.0.20+8 (build 11.0.20+8)
OpenJDK 64-Bit Server VM Temurin-11.0.20+8 (build 11.0.20+8, mixed mode)
Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)
Maven home: /usr/share/apache-maven-3.8.8
Java version: 11.0.20, vendor: Eclipse Adoptium, runtime: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.20-8/x64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.[15](https://github.com/NVIDIA/spark-rapids/actions/runs/5687245548/job/15415371715#step:4:16).0-1041-azure", arch: "amd64", family: "unix"
ENV JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.[20](https://github.com/NVIDIA/spark-rapids/actions/runs/5687245548/job/15415371715#step:4:21)-8/x64```

**Comment by gerashegalov** [comment]
This might be because according to the doc https://github.com/actions/setup-java#install-multiple-jdks

> All versions are added to the PATH. The last version will be used and available globally. Other Java versions can be accessed through env variables with such specification as 'JAVA_HOME_{{ MAJOR_VERSION }}_{{ ARCHITECTURE }}'.

we might need to set  `JAVA_HOME=JAVA_HOME_{{ java-version }}_AMD64` for Maven to pick up the right one.

**Comment by pxLi** [comment]
> 

we are installing JDK in different github runners, so they should not meet this issue. But if there is a bug or other host-level caching strategy, it may cause the issue

**Comment by pxLi** [comment]
I will keep monitoring the status for a couple of days

**Comment by pxLi** [comment]
seeing sth new in https://github.com/NVIDIA/spark-rapids/actions/runs/5692968262/job/15431096263

```
  Trying to resolve the latest version from remote
  Error: <html><script src="/cdn-cgi/apps/head/sfD1hm0FSHcO6eLRgBHEuNz74uc.js"></script><body><h1>408 Request Time-out</h1>
  Your browser didn't send a complete request in time.
  </body></html>
```
the error was saying request timeout, but I think there is some glitch w/ github CDH right now

**Comment by pxLi** [comment]
Degraded performance incidents for GitHub services everyday
https://www.githubstatus.com/history

**Comment by pxLi** [comment]
https://www.githubstatus.com/incidents/l59z35rhzdky another incident ongoing 🤷
