### ISSUE TITLE
[FEA] Provide CUDF java APIs for memory allocation

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8884]
**Is your feature request related to a problem? Please describe.**
There are a number of places in CUDF that will do host memory allocations. In many of these cases if we want to block an host allocation until it is ready we need a way in inject a layer of indirection in host memory allocations. Instead of trying to get a global RMM like allocation API in CUDF I think it is simpler to have CUDF support a basic host memory allocation interface, and then update the locations to do allocate host memory to use this interface along with a default implementation that does what it currently does today.

There are a number of other places where more API changes would be needed. Those will be done in other issues.

**Comment by gerashegalov** [comment]
Done. Follow up in https://github.com/rapidsai/cudf/issues/13940
