### ISSUE TITLE
[FEA] Dump host buffer on cuDF reader error

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#8912]
With: https://github.com/NVIDIA/spark-rapids/issues/8672 we have a point of entry where we can perform more in depth debugging, other than an exception that goes to the driver. There is currently a config `spark.rapids.sql.[parquet|orc|avro].debug.dumpPrefix` that will dump unconditionally (success or failure) to disk at a location given by `dumpPrefix`. What we would like is to add a dump config for "dump on error" where we use the path in dumpPrefix to deposit a host buffer that failed to decode.

We would include the path we dumped to (the full filename) in the same exception thrown here https://github.com/NVIDIA/spark-rapids/issues/8672 so we can see it easily in the driver.

As part of this we need to make sure that the dumpPrefix can be a distributed file system.

**Comment by jlowe** [comment]
Fixed by #8970
