### ISSUE TITLE
[BUG] Databricks - move init scripts off DBFS

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#8916]
**Describe the bug**
init scripts in DBFS will be deprecated sept 1 2023.  Update docs and move any internal testing/dev environments off of dbfs for init scripts.

**Comment by pxLi** [comment]
cc @NvTimLiu to help with this one, thanks

per the doc, Databricks recommends storing all cluster-scoped init scripts using workspace files.
https://docs.databricks.com/en/files/workspace-init-scripts.html
![image](https://github.com/NVIDIA/spark-rapids/assets/8086184/45915b2a-c24c-45e2-b49f-9fe7e5cceeae)

**Comment by sameerz** [comment]
> Update docs ...

Per @viadea our documentation is updated.

**Comment by viadea** [comment]
Yes it is updated by @nvliyuan in https://github.com/NVIDIA/spark-rapids/pull/8221

**Comment by pxLi** [comment]
merged #8961. lets close this ticket after all internal usages have been updated @NvTimLiu thanks~

**Comment by NvTimLiu** [comment]
I will remove all our internal deprecated Jenkinfiles pointing init scripts to DB workspace storage this week, thx~

**Comment by mattahrens** [comment]
Can this be closed?

**Comment by NvTimLiu** [comment]
Yes, the fixed PR has been merged on the GitHub, Let me close it

There are some CI script update in internal GitLab repo, which I'll file another issue to follow up
