### ISSUE TITLE
[FEA] Use custom kernel for parse_url

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#8963]
**Is your feature request related to a problem? Please describe.**
https://github.com/NVIDIA/spark-rapids-jni/issues/1326 was filed to add a custom kernel for URL/URI parsing. This is to update the parse_url SQL function to use it.

**Comment by NVnavkumar** [comment]
We should like this up to https://github.com/NVIDIA/spark-rapids/issues/6969

**Comment by hyperbolic2346** [comment]
Implemented
