### ISSUE TITLE
[FEA] Update changelog to include benchmarking label

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#897]
We added a new label `benchmark`.  We need to update the changelog creation tool to include issues and PRs labeled with benchmark.

**Comment by pxLi** [comment]
@sameerz Hey, just got back from holiday. Can you also provide the section priority of `benchmark` like https://github.com/NVIDIA/spark-rapids/issues/573#issuecomment-677053903? Thanks!

**Comment by sameerz** [comment]
Let's treat `benchmark` like `performance` and use the same deduplication rules that are already there for performance.
