### ISSUE TITLE
jupyter notebook example[QST]

### ISSUE THREAD

**Issue by alexxony** [NVIDIA/spark-rapids#8976]
**What is your question?**
Can I get some notebook example?

**Comment by jlowe** [comment]
Thanks for your interest!  Can you elaborate on what type of example you are seeking?  We have example notebooks for:

- [Mortgage ETL demos](https://github.com/NVIDIA/spark-rapids/tree/main/docs/demo).  These notebooks are referenced as part of overall [getting started instructions](https://nvidia.github.io/spark-rapids/Getting-Started) for [AWS-EMR](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-aws-emr.html), [Databricks](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-databricks.html), and [GCP](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-gcp.html).
- A number of example notebooks for various ML, DL, SQL, DataFrame, and UDF use cases in the [spark-rapids-examples](https://github.com/NVIDIA/spark-rapids-examples/tree/main/examples) repository.
- Demo notebooks for using the [qualification and profiling tools on Databricks](https://github.com/NVIDIA/spark-rapids-examples/tree/main/tools/databricks)

If these example notebooks are not what you're looking for, please let us know.
