### ISSUE TITLE
[FEA] Make databricks CI pipeline use a multi-shim jar.

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#9008]
**Is your feature request related to a problem? Please describe.**
As a Spark RAPIDS developer, I need the costly CI pipeline to catch Shim-related issues. Databricks environment requires most complicated shimming. but uses a single-shim jar.  Issues like the build failure #8962 and some runtime issues are caught only with a multi-shim build.

**Describe the solution you'd like**
Bulld at least a two-shim jar 311 + 3XYdb to be used in the Databricks test pipelines. 

**Describe alternatives you've considered**
- Manual testing 
- Delayed test coverage via nightly
- Release dedicated conventional jar artifacts for cloud environments

**Additional context**
#8962

**Comment by razajafri** [comment]
I want to also document this here that having `[databricks]` tag on a PR kicks off a pre-merge on Databricks but still doesn't create a multi-shim jar which is what this issue is talking about.
