### ISSUE TITLE
[FEA] Benchmark CSV to Parquet conversion should have explicit partitioning

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#902]
**Is your feature request related to a problem? Please describe.**
When we run the CSV to Parquet conversion for the TPC-* benchmarks, the number and size of the generated partitions can vary depending on the value of `spark.default.parallelism` which varies depending on the number of executors/cores used. We should specify an explicit number of partitions instead and document the suggested partition counts by scale factor.

**Describe the solution you'd like**
Update the csvToParquet code to either require an explicit number of partitions or calculate the number of partitions based on scale factor.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tgravescs** [comment]
it would be nice to have a parameter to specify partitioning as well if that is easy. This would help if we want to test with very small files for instance
