### ISSUE TITLE
[DOC] the default value of spark.rapids.memory.gpu.allocFraction

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#9026]
In the [Tuning guide Doc](https://nvidia.github.io/spark-rapids/docs/tuning-guide.html#pooled-memory), we said the default value of spark.rapids.memory.gpu.allocFraction is 0.9, but in the [Advanced Configuration Doc](https://nvidia.github.io/spark-rapids/docs/additional-functionality/advanced_configs.html), the default value is 1.0. It seems 1.0 is true from the [code snippets](https://github.com/NVIDIA/spark-rapids/blob/branch-23.10/sql-plugin/src/main/scala/com/nvidia/spark/rapids/RapidsConf.scala#L400). Do we want to update it to 0.9 or we need to update the tuning guide doc?

So did spark.rapids.memory.host.spillStorageSize， spark.rapids.sql.concurrentGpuTasks， spark.rapids.sql.batchSizeBytes

**Comment by mattahrens** [comment]
Default is 1.  We also need to explain that we always reserve a portion of the GPU (defaults to 640 MiB).

**Comment by nvliyuan** [comment]
closed since  #9053 merged
