### ISSUE TITLE
[FEA] create EMR 3.0.1 shim

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#905]
**Is your feature request related to a problem? Please describe.**
Add a shim layer for aws EMR being based on spark 3.0.1

**Comment by aluroid** [comment]
It's great to know spark-rapids is going to support EMR, is there an ETA of 0.3.0?
Also, latest EMR 6.1.0 is with Spark 3.0.0, so is this feature targeting a future release of EMR?

**Comment by sameerz** [comment]
We are working to see if we can get the 0.2.0 plugin on EMR 6.2.0, which should be available in November / December.  
The target for the 0.3.0 plugin is end of the year.

**Comment by Data-drone** [comment]
Cloudera Spark 3 release also runs on 3.0.1 so currently I run into:

```
20/10/14 01:13:34 ERROR repl.Main: Failed to initialize Spark session.
java.lang.IllegalArgumentException: Could not find Spark Shim Loader for 3.0.1.3.0.7110.0-81
	at com.nvidia.spark.rapids.ShimLoader$.detectShimProvider(ShimLoader.scala:45)
	at com.nvidia.spark.rapids.ShimLoader$.findShimProvider(ShimLoader.scala:52)
	at com.nvidia.spark.rapids.ShimLoader$.getSparkShims(ShimLoader.scala:64)
```

**Comment by Data-drone** [comment]
cheers that got it to boot but as you said there will be no guarantees that something won't break somewhere. How can I validate?

**Comment by sameerz** [comment]
You can run the integration tests in your environment (instructions here: https://github.com/NVIDIA/spark-rapids/tree/branch-0.3/integration_tests ).  We are going to work with Cloudera to ensure we are compatible in their environment.

**Comment by sameerz** [comment]
I confirmed with our Cloudera contact that CDS 3.0 is basically running Spark 3.0.1, so our plugin will work fine.  The workaround mentioned [above](https://github.com/NVIDIA/spark-rapids/issues/905#issuecomment-707783924) will work for now.  Longer term we will build a shim layer for Cloudera so the workaround is not required.
