### ISSUE TITLE
Clean up setSpillable/doSetSpillable

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9076]
The RapidsBufferStore has a setSpillable and a doSetSpillable, both with the same visibility.  One by default throws, while the other does not.  This is very confusing, especially since the code is not consistent in which version is called, e.g.: updateSpillability calls doSetSpillable rather than setSpillable.  IMO there should just be a single setSpillable function that should do nothing on stores that don't spill rather than have this confusing distinction.

**Comment by abellina** [comment]
Assigning this to myself and in this iteration. It is very small but it will improve the code and remove confusion. @mattahrens fyi. I also don't want to forget about it.

**Comment by abellina** [comment]
Related issue: https://github.com/NVIDIA/spark-rapids/issues/9121, more cleanup.
