### ISSUE TITLE
[BUG] NDS query 64 falls back to CPU only for a shuffle

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9092]
When running NDS query 64 at the 3k scale factor on AWS EMR 6.12, there is an unnecessary fallback to the CPU for a shuffle.  The node sequence in the plan UI is:
```
GpuHashAggregate(partial) ->
  GpuColumnarToRow ->
    AdaptiveSparkPlan ->
      Exchange ->
        ReusedExchange ->
          AQEShuffleRead ->
            GpuRowToColumnar ->
              GpuHashAggregate(final)
```

**Comment by sameerz** [comment]
Need to check for this in an on-premises cluster.  There were no notifications in the driver log.

**Comment by jlowe** [comment]
This is also happening in NDS query 23_part1, 23_part2, 24_part1, 24_part2, 47, and 57.
