### ISSUE TITLE
[FEA] Add Spark 3.3.4 support

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#9096]
**Is your feature request related to a problem? Please describe.**
Spark 3.3.3 was released, we should add 3.3.4-SNAPSHOT as a new shim.

Note that 3.3.0 was released  June 2022, according to Spark release schedule, its supported for 18 months, so we are getting close to that. It may be a question whether they would do a 3.3.4 release.

**Comment by tgravescs** [comment]
Fyi 3.3.4 is up for release vote. The intention is its the last release in the 3.3.X line

**Comment by razajafri** [comment]
Spark 3.3.4 is now released. Repurposing this issue for creating a 3.3.4 Shim and have updated the title.
