### ISSUE TITLE
Refactor unshimmed classes into a separate Maven module

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9104]
We've hit a few problems recently with unshimmed classes referencing shimmed classes directly which is problematic at runtime when the unshimmed class is not using the classloader that is parallel-world aware.  It would be nice to catch these issues at build time.  One way to do that is to refactor the code so that the shimmed and unshimmed classes are in separate Maven modules.  The shimmed module would depend on the unshimmed module but not vice-versa.  That way unshimmed classes are not allowed to reference shimmed classes except via the ShimLoader interface or similar reflection techniques, and the build will fail if attempting to reference them directly.

**Comment by gerashegalov** [comment]
looks like a duplicate of #6565

**Comment by jlowe** [comment]
Yes, completely!  Thanks @gerashegalov I missed that when I went searching for it earlier.
