### ISSUE TITLE
[BUG] Databricks Stages metrics don't show the amount of input data when reading from table

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#911]
**Describe the bug**
I saw a query reading from parquet from a table on Databricks and  when I went to the stages page it didn't show the amount of data input from that table whereas the CPU did.

**Expected behavior**
Input data size shown.

**Comment by jlowe** [comment]
@tgravescs is this still relevant?

**Comment by tgravescs** [comment]
no, at least last time I checked it was working.
