### ISSUE TITLE
[BUG] spark350 shim build failed in mvn-verify github checks and nightly due to dependencies not released

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#9116]
**Describe the bug**
spark 3.5.0 RC is still under voting. maven repo does not have required libs for building corresponding shims for now

Let's disable 350 build in nightly to unblock mvn-verify github checks and nightly artifact build, 
we can re-enable when available in the future

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Comment by andygrove** [comment]
@pxLi It could be a while before 3.5.0 is released, and we are already finding that PRs can be merged that break the current 3.5.0 build. Could we build the 3.5.0-rc3 artifacts ourselves and publish them to urm so that we can enable pre-merge against 3.5.0-rc3? We can then increment the version if there are future rc releases.

**Comment by pxLi** [comment]
> @pxLi It could be a while before 3.5.0 is released, and we are already finding that PRs can be merged that break the current 3.5.0 build. Could we build the 3.5.0-rc3 artifacts ourselves and publish them to urm so that we can enable pre-merge against 3.5.0-rc3? We can then increment the version if there are future rc releases.

yes, we could if needed. cc @NvTimLiu can you help deploy a pkgs and bin based on https://github.com/apache/spark/releases/tag/v3.5.0-rc3? So developers could start test against internal maven repo.

As 3.5 RC is still under voting, we will not enable https://github.com/NVIDIA/spark-rapids/blob/branch-23.10/pom.xml#L681-L682 but add a separate pipeline for 3.5 build and testing before the official release

@andygrove please also notify use whenever there is a new RC need to be built, we will need to update all corresponding CICD setups that are targeting RC-old to RC-new, thanks!

**Comment by andygrove** [comment]
Thanks @pxLi. I will keep you posted about new rc releases.
