### ISSUE TITLE
[BUG] Predicate pushdown doesn't work for parquet files written by GPU

### ISSUE THREAD

**Issue by thirtiseven** [NVIDIA/spark-rapids#9119]
**Describe the bug**

Predicate pushdown seems not to work at all for parquet files written by GPU. 

I didn't test all cases, but I tested several basic types and they all failed. My test code [here](https://github.com/thirtiseven/spark-rapids/blob/6287e321ed0c24d7845bc3034d0c033b63f4955e/tests/src/test/scala/org/apache/spark/sql/rapids/ParquetFilterSuite.scala), it follows the way spark tested PPD.

Things I know now:

1. In the physical plan, we can see that the predicate is pushed to pushedFilter: 
```
== Physical Plan ==
GpuColumnarToRow false
+- GpuFilter (gpuisnotnull(a#7) AND (a#7 = 500))
   +- GpuFileGpuScan parquet [a#7] Batched: true, DataFilters: [isnotnull(a#7), (a#7 = 500)], Format: Parquet, Location: InMemoryFileIndex[file:/home/haoyangl/spark-rapids/tests/target/spark341/tmp/spark-test-dc4dee0d-..., PartitionFilters: [], PushedFilters: [IsNotNull(a), EqualTo(a,500)], ReadSchema: struct<a:int>
```
But the actual results from Parquet after striping the Spark side filter is 1024, which means PPD is not working.

2. The CPU file's block metadata contains more statistics like min/max, while GPU file's block metadata contains min_value/max_value only.

GPU's metadata (first block only):
```
parquet-tools inspect --detail part-00000-0f7406a1-12b1-4ad4-bdbe-e812a74afe8c-c000.snappy.parquet
FileMetaData
■■■■version = 1
■■■■schema = list
■■■■■■■■SchemaElement
■■■■■■■■■■■■name = schema
■■■■■■■■■■■■num_children = 1
■■■■■■■■SchemaElement
■■■■■■■■■■■■type = 1
■■■■■■■■■■■■name = a
■■■■num_rows = 1024
■■■■row_groups = list
■■■■■■■■RowGroup
■■■■■■■■■■■■columns = list
■■■■■■■■■■■■■■■■ColumnChunk
■■■■■■■■■■■■■■■■■■■■meta_data = ColumnMetaData
■■■■■■■■■■■■■■■■■■■■■■■■type = 1
■■■■■■■■■■■■■■■■■■■■■■■■encodings = list
■■■■■■■■■■■■■■■■■■■■■■■■■■■■0
■■■■■■■■■■■■■■■■■■■■■■■■path_in_schema = list
■■■■■■■■■■■■■■■■■■■■■■■■■■■■a
■■■■■■■■■■■■■■■■■■■■■■■■num_values = 128
■■■■■■■■■■■■■■■■■■■■■■■■total_uncompressed_size = 532
■■■■■■■■■■■■■■■■■■■■■■■■total_compressed_size = 532
■■■■■■■■■■■■■■■■■■■■■■■■data_page_offset = 4
■■■■■■■■■■■■■■■■■■■■■■■■statistics = Statistics
■■■■■■■■■■■■■■■■■■■■■■■■■■■■max_value = b'\x80\x00\x00\x00'
■■■■■■■■■■■■■■■■■■■■■■■■■■■■min_value = b'\x01\x00\x00\x00'
■■■■■■■■■■■■total_byte_size = 532
■■■■■■■■■■■■num_rows = 128
```
CPU's metadata:
```
parquet-tools inspect --detail part-00000-77aa9430-86b8-429e-96bd-7f3943191636-c000.snappy.parquet
FileMetaData
■■■■version = 1
■■■■schema = list
■■■■■■■■SchemaElement
■■■■■■■■■■■■name = spark_schema
■■■■■■■■■■■■num_children = 1
■■■■■■■■SchemaElement
■■■■■■■■■■■■type = 1
■■■■■■■■■■■■name = a
■■■■num_rows = 1024
■■■■row_groups = list
■■■■■■■■RowGroup
■■■■■■■■■■■■columns = list
■■■■■■■■■■■■■■■■ColumnChunk
■■■■■■■■■■■■■■■■■■■■file_offset = 4
■■■■■■■■■■■■■■■■■■■■meta_data = ColumnMetaData
■■■■■■■■■■■■■■■■■■■■■■■■type = 1
■■■■■■■■■■■■■■■■■■■■■■■■encodings = list
■■■■■■■■■■■■■■■■■■■■■■■■■■■■4
■■■■■■■■■■■■■■■■■■■■■■■■■■■■0
■■■■■■■■■■■■■■■■■■■■■■■■path_in_schema = list
■■■■■■■■■■■■■■■■■■■■■■■■■■■■a
■■■■■■■■■■■■■■■■■■■■■■■■codec = 1
■■■■■■■■■■■■■■■■■■■■■■■■num_values = 127
■■■■■■■■■■■■■■■■■■■■■■■■total_uncompressed_size = 556
■■■■■■■■■■■■■■■■■■■■■■■■total_compressed_size = 561
■■■■■■■■■■■■■■■■■■■■■■■■data_page_offset = 4
■■■■■■■■■■■■■■■■■■■■■■■■statistics = Statistics
■■■■■■■■■■■■■■■■■■■■■■■■■■■■max = b'\x7f\x00\x00\x00'
■■■■■■■■■■■■■■■■■■■■■■■■■■■■min = b'\x01\x00\x00\x00'
■■■■■■■■■■■■■■■■■■■■■■■■■■■■max_value = b'\x7f\x00\x00\x00'
■■■■■■■■■■■■■■■■■■■■■■■■■■■■min_value = b'\x01\x00\x00\x00'
■■■■■■■■■■■■■■■■■■■■■■■■encoding_stats = list
■■■■■■■■■■■■■■■■■■■■■■■■■■■■PageEncodingStats
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■count = 1
■■■■■■■■■■■■total_byte_size = 556
■■■■■■■■■■■■num_rows = 127
```
3.  In parquet-format, min/max is deprecated and optional, so cuDF's behavior is valid. [code in parquet-format](https://github.com/apache/parquet-format/blob/1603152f8991809e8ad29659dffa224b4284f31b/src/main/thrift/parquet.thrift#L200)

4.  In parquet-mr, I can't find any logic to handle min_value/max_value. (Possibly) related [issue](https://issues.apache.org/jira/browse/PARQUET-1025) and [PR](https://github.com/apache/parquet-format/pull/46/files).

I doubt it's an issue in parquet-mr, but I'm not quite familiar with parquet, need to check this further before filing an issue.

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**
Predicate pushdown should work with parquet files written by GPU.

**Environment details (please complete the following information)**
Latest code. 
I tested 311, 321, 331 and 341, all can reproduce this issue.

**Additional context**
There is a similar issue for ORC, see [PR](https://github.com/NVIDIA/spark-rapids/pull/9068)

**Comment by res-life** [comment]
I filed an issue to support `parquet.block.size` https://github.com/NVIDIA/spark-rapids/issues/9126

@thirtiseven  you can do the following to test the row groups filtering.
- Generate one file only contains one row group, but set filter to not meet the [min, max] data range. This will filter out the only row group and test case can pass.
- Generate one file contains multipile row groups: update the code to support setting row group to a small value like 1M instead of 128M. Refer to above issue.

**Comment by thirtiseven** [comment]
I'm closing this because my testing issues are resolved by Bobby and we have issues to track PPD testing and `parquet.block.size` support.

Thanks @revans2 and @res-life !
