### ISSUE TITLE
[FEA] Support CalendarInterval while creating CachedBatches

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#913]
**Is your feature request related to a problem? Please describe.**
There are some types that spark parquet just does not support, and we are not testing those at all, i.e. calendar interval. Do we care? Is there a follow on issue to support them?

**Describe the solution you'd like**
Look into this more and suggest a solution

**Comment by tgravescs** [comment]
what happens when you try to read those types?

**Comment by revans2** [comment]
Currently if you configure the experimental cache manager it should fail, but I don't know how gracefully it does that.

**Comment by sameerz** [comment]
Can we create tests to make sure we can handle reading those unsupported types (like CalendarIntervalType)?  Please file an issue to track if needed.

**Comment by razajafri** [comment]
Yeah, waiting for this to be triaged and prioritized. Will see if I can get to this before that.

**Comment by razajafri** [comment]
Currently the cache serializer throws an exception and crashes. I am in the middle of working a solution by exploding the CalendarIntervalType to ints.
