### ISSUE TITLE
[DOC] Tuning guide duplicates default values from config docs

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9144]
#9143 is an example where it's easy to have documentation be out of date with respect to config defaults.  We may want to consider removing the defaults from the tuning guide and instead rely on links from the tuning guide to the config docs for specifics on the config like default values.  Or find a way to generate the tuning guide with the proper default values like we generate the config documentation.

**Comment by mattahrens** [comment]
Updates made in new tuning guide to link to configs docs for defaults instead of maintaining in two places: https://docs.nvidia.com/spark-rapids/user-guide/latest/tuning-guide.html.  Will be released with next push of User Guide on docs.nvidia.com.
