### ISSUE TITLE
[DOC] AWS EMR instructions for RAPIDS Accelerator disables all V1 readers

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9145]
The [AWS EMR instructions for adding the RAPIDS Accelerator](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-rapids.html) tells the user to explicitly disable all Spark DataSource V1 readers by setting `spark.sql.sources.useV1SourceList` to `""`.  That causes the CPU to plan some queries suboptimally, since not all predicate pushdowns are supported on V2 datasources as they are on V1.  The NDS benchmark is significantly slower when using Parquet with datasource v2, which is why we've been explicitly overriding this config to use V1 for Parquet when testing NDS on AWS EMR.

We should work with the AWS EMR team to update the documentation so it no longer recommends overriding the `spark.sql.sources.useV1SourceList` setting.

**Comment by sameerz** [comment]
FYI @kevnzhao

**Comment by mimaomao** [comment]
The recommended config in AWS EMR doc is not up to date. We'll update our doc to remove config `spark.sql.sources.useV1SourceList: ""`.

**Comment by mattf** [comment]
this can be closed.

![image](https://github.com/NVIDIA/spark-rapids/assets/112653/25ff4679-c15d-400c-9047-a2701bb6269d)
