### ISSUE TITLE
[AUDIT][SPARK-44266][SQL] Move Util.truncatedString to sql/api

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#9176]
In this commit https://github.com/apache/spark/commit/4cdb6d487e, `truncatedString` was moved to `SparkStringUtils`. We use this method in various places. I believe we want to place it under the `ShimLoader` and then load it from the appropriate place in Spark 3.5.0+

**Comment by mattahrens** [comment]
@andygrove did you already fix this?

**Comment by jlowe** [comment]
This is not fixed yet.  Code compiles against Spark 3.5 because Spark 3.5 left the API available in the old location as well, and it simply delegates to the new API location when called.  Not sure we really need to fix this, as compiler will tell us if they ever end up removing the old location.

**Comment by abellina** [comment]
Ok that makes sense, lets close this. Thanks @jlowe
