### ISSUE TITLE
[FEA][AUDIT][SPARK-44641] Incorrect result in certain scenarios when SPJ is not triggered

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#9180]
**Is your feature request related to a problem? Please describe.**

Some logic in BatchScanExec is updated in https://github.com/apache/spark/commit/5c7d1e2f8a#diff-f82edfef27867e1285af13f3603efbc5e77d81d715d427db4b51f0c3e3a0df14 and we have the same logic in GpuBatchScanExec, so we may need to make the same changes.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andygrove** [comment]
Hi @res-life did you have a chance to look at this? I tried writing a test to reproduce, it but have not succeeded yet.

**Comment by andygrove** [comment]
I am unable to reproduce the issue so far on the GPU. Here are the approaches I have tried.

## Approach 1

I created DataFrames and then saved them with `saveAsTable` since it is not possible to write directly as parquet with bucketing enabled. This resulted in the join query using a `FileSourceScanExec` rather than a `BatchScanExec`, so did not hit the code that has the bug.

```
      items.withColumn("arrive_time", col("arrive_time_str").cast(DataTypes.TimestampType))
        .drop("arrive_time_str")
        .write
        .bucketBy(8, "id")
        .mode(SaveMode.Overwrite)
        .saveAsTable("items")
```

## Approach 2

I ported over the test from Spark. This did result in `BatchScanExec` being used on CPU, but because the test uses a custom table catalog, the GPU test fell back to CPU, so again did not hit the problematic code.

## Approach 3

Finally, I tried using SQL to create the hive tables, using `CLUSTERED BY (key) INTO n BUCKETS`. This required explicitly enabling hive support in the configs and then I ran into ClassNotFound issues related to Hive.

**Comment by revans2** [comment]
I started to read the code and we need to have a V2 data source that supports `SupportsReportPartitioning` and we have to have enabled `spark.sql.sources.v2.bucketing.enabled` and the bucketing needs to somehow have duplicate partitions in it. I'm not 100% sure how to do that with existing Spark code. As of Spark 3.3.0 I didn't see anything in spark except tests that supported `SupportsReportPartitioning`, and the latest code does not look that much better.  https://github.com/search?q=repo%3Aapache%2Fspark%20SupportsReportPartitioning&type=code

I don't think in practice we can cause this to happen with out code. We probably should still fix it, but I don't know how to trigger it. @jlowe do you have any other ideas?

**Comment by jlowe** [comment]
IIUC we would be able to reproduce it if we can create a bucketed table and then hit it with a V2 read, correct?  Can you use the `path` option to specify where you want the bucketed table created?  For example:
```
items.withColumn("arrive_time", col("arrive_time_str").cast(DataTypes.TimestampType))
  .drop("arrive_time_str")
  .write
  .bucketBy(8, "id")
  .mode(SaveMode.Overwrite)
  .format("parquet")
  .option("path", "/my/custom/table/path")
  .saveAsTable("items")
```
and then load the table from /my/custom/table/path

**Comment by andygrove** [comment]
> IIUC we would be able to reproduce it if we can create a bucketed table and then hit it with a V2 read, correct? Can you use the `path` option to specify where you want the bucketed table created? For example:
> 
> ```
> items.withColumn("arrive_time", col("arrive_time_str").cast(DataTypes.TimestampType))
>   .drop("arrive_time_str")
>   .write
>   .bucketBy(8, "id")
>   .mode(SaveMode.Overwrite)
>   .format("parquet")
>   .option("path", "/my/custom/table/path")
>   .saveAsTable("items")
> ```
> 
> and then load the table from /my/custom/table/path

Thanks, that did the trick! I also had to disable v1 reads, which I had missed before. I now see BatchScanExecs :tada: but I have not reproduced the bug still, but this gets much farther along.

**Comment by andygrove** [comment]
I have now re-read comments from @revans2 and we still have the issue that a parquet scan does not implement `SupportsReportPartitioning` so I am still blocked on this. The Spark PR (linked in this PR description) implements a whole custom scan that implements the `SupportsReportPartitioning` trait.

**Comment by res-life** [comment]
Aslo, I can not reproduce it by `USING parquet CLUSTERED BY (id) INTO 8 BUCKETS`
