### ISSUE TITLE
[AUDIT][SPARK-44283][CONNECT] Move Origin to SQL/API

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#9184]
We use `Origin` in several files. In spark-3.5+, it was moved under a new module (`spark-sql-api_2.12`). We'll need to add this dependency only for 3.5+: https://github.com/apache/spark/tree/branch-3.5/sql/api

Patch that moved `Origin`: https://github.com/apache/spark/commit/7bd1353084#diff-2b0bd51d4eb6798d69876a78b0fe2097bda3cc973cd95df51b6bc6abfc893438

**Comment by jlowe** [comment]
I'm not sure we need to fix anything here, as we're already compiling against Spark 3.5.  We're getting the spark-sql-api module transitively via the spark-sql dependency.

**Comment by abellina** [comment]
Ah yes it looks like `spark-catalyst_2.12` pulls this already. Sorry!
