### ISSUE TITLE
[BUG] `from_json` fails with cuDF error `Invalid list size computation error`

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#9212]
**Describe the bug**

I am testing with a custom build of `spark-rapids-jni`, where I am specifying `RECOVER_WITH_NULL` in the `from_json` function that gets called from `extractRawMapFromJsonString`.

A simple test of `from_json` results in the cuDF error `Invalid list size computation error`.

**Steps/Code to reproduce bug**

```scala
scala> val df = Seq("{'a': '1'}\n{'a': '2'}\n").toDF("str").repartition(2)
df: org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [str: string]

scala> df.createOrReplaceTempView("t")

scala> spark.sql("select from_json(str, 'MAP<STRING,STRING>') from t").show()
```

Fails with 

```
ai.rapids.cudf.CudfException: CUDF failure at: /home/andy/git/nvidia/spark-rapids-jni/src/main/cpp/src/map_utils.cu:609: Invalid list size computation.
	at com.nvidia.spark.rapids.jni.MapUtils.extractRawMapFromJsonString(Native Method)
	at com.nvidia.spark.rapids.jni.MapUtils.extractRawMapFromJsonString(MapUtils.java:49)
	at org.apache.spark.sql.rapids.GpuJsonToStructs.doColumnar(GpuJsonToStructs.scala:153)
```

**Expected behavior**

Spark without plugin produces:

```
+--------+
| entries|
+--------+
|{a -> 1}|
+--------+
```

**Environment details (please complete the following information)**
N/A

**Additional context**

**Comment by mattahrens** [comment]
@ttnghia has worked on the json tokenization layer in spark-rapids-jni and can provide help as needed.

**Comment by ttnghia** [comment]
Will look into this.

**Comment by ttnghia** [comment]
This is not a bug but rather the limitation of the current implementation:
 * cudf JSON parse doesn't support single quote character.
 * `from_json` only works with input having one (string) JSON object per row.
 * Duplicates are not handled.

**Comment by andygrove** [comment]
I just tested this again, using the code from https://github.com/NVIDIA/spark-rapids/pull/9423, and it actually failed with a segmentation fault, which is concerning.

**Comment by ttnghia** [comment]
I can reproduce it with the latest cudf code:
```
scala> val df = Seq("{'a': '1'}").toDF("str").repartition(2)
df: org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [str: string]

scala> df.createOrReplaceTempView("t")

scala> spark.sql("select from_json(str, 'MAP<STRING,STRING>') from t").show()
....
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5975570710, pid=468146, tid=0x00007f596c39a640
#

```

**Comment by ttnghia** [comment]
I realize that the issue is due to having `repartition(2)`. Without it, the example is just fine:
```

scala> val df = Seq("{'a': '1'}\n{'a': '2'}\n").toDF("str")
df: org.apache.spark.sql.DataFrame = [str: string]

scala> df.createOrReplaceTempView("t")

scala> spark.conf.set("spark.rapids.sql.expression.JsonToStructs","true")

scala> spark.sql("select from_json(str, 'MAP<STRING,STRING>') from t").show()
23/10/31 22:55:33 WARN GpuOverrides: 
! <LocalTableScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.LocalTableScanExec
  @Expression <AttributeReference> entries#9 could run on GPU

+--------+
| entries|
+--------+
|{a -> 1}|
+--------+
```

So there should be something wrong with handling empty input in JSON reader.

**Comment by andygrove** [comment]
> I realize that the issue is due to having `repartition(2)`

Without the repartition the query is falling back to CPU (`cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.LocalTableScanExec`)

**Comment by ttnghia** [comment]
Got it. So this is indeed a bug in `from_json` in spark-rapids-jni. The issue is due to comparing signed vs unsigned integers when an exception is being thrown due to invalid token is detected.

I'll post a fix PR shortly.

**Comment by ttnghia** [comment]
Alright, that should be fixed by https://github.com/NVIDIA/spark-rapids-jni/pull/1536.

**Comment by andygrove** [comment]
I just tested this on latest branch-24.02 and it is no longer an issue
