### ISSUE TITLE
[FEA] Add running window fixer for first and last

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#9299]
**Is your feature request related to a problem? Please describe.**
Running window, unbounded preceding to current row, is a very common operation. First and last do show up here, but not that often. However, they should be very trivial to support so we should do it. Just make sure to take into account the null-ability of first and last.

**Comment by revans2** [comment]
First and last do not work for scan aggregations so this will only be a memory optimization.

**Comment by mythrocks** [comment]
At a future date, there will be value in adding support for `FIRST` and `LAST` to be implemented as `groupby_scan_aggregation` in `libcudf`. I'll leave that out of scope for this issue.

I'm tackling `FIRST` as a `ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW` window aggregation first. `RANGE` support can follow.

**Comment by mythrocks** [comment]
> I'm tackling FIRST as a ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW 

https://github.com/NVIDIA/spark-rapids/pull/9489

I'm working on the same, for `RANGE` queries.
