### ISSUE TITLE
[FEA] Improve Scala 2.13 build process to not require building against unstaged git changes

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#9331]
This is a follow on to #1525. The changes in #8592 do not address a concern in the build process in that the CI will build against unstaged git changes. See this thread:

https://github.com/NVIDIA/spark-rapids/pull/8592#discussion_r1240630240

We should generate the pom files directly, and we can put the generated pom files in gitignore, so the CI will be able to build against what it sees as a clean working copy.

Note the CI will not be building Scala 2.13 artifacts until this issue is addressed.

**Comment by gerashegalov** [comment]
[archetype](https://maven.apache.org/guides/mini/guide-creating-archetypes.html) could be an interesting option for pom generation
