### ISSUE TITLE
Improve diagnostics for `conv` fallback explain

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#9340]
When to_base or from_base are unsupported we print

```
conv(cast(a#2 as string), 10, -10) cannot run on GPU because only literal 10 or 16 for from_base and to_base are supported
```

consider printing the user-provided actual values when explaining a fallback

**Comment by mattahrens** [comment]
Explanation should explicitly say: `cannot run on GPU because <user-value> is not supported; only literal 10 or 16...`
