### ISSUE TITLE
[FEA] have murmur3 hash function that matches exactly with spark

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#937]
**Is your feature request related to a problem? Please describe.**
The murmur3 hashing sql function is used by spark for shuffle and bucketed writes #22.  If we want to really support these properly we need a murmur3 implementation that matches exactly what spark is doing.

**Comment by sameerz** [comment]
Related cudf PR https://github.com/rapidsai/cudf/pull/7024

**Comment by rwlee** [comment]
Ralted to issue https://github.com/rapidsai/cudf/issues/6863
