### ISSUE TITLE
[BUG] RapidsShuffleManager MULTITHREADED on Databricks, we see loss of executors due to Rpc issues

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#9397]
An issue was reported when MULTITHREADED shuffle is enabled in databricks where executors are dropping out with RPC failure (where the peer is another executor, all against one executor's IP as far as I remember). The odd part is that the stages we saw had 400+ shuffle partitions, which are by default bypassed by our shuffle (since we only replace the sort shuffle manager <= 200 partitions)

The customer had `spark.databricks.adaptive.autoOptimizeShuffle.enabled` enabled as well. We are not sure if this is related to the issue. For example, is there part of the ShuffleWriter/ShuffleReader API that databricks enabled in their shuffle? Are we conflicting with this autoOptimizeShuffle or are we getting triggered in MULTITHREADED mode when we shouldn't? The MULTITHREADED shuffle will use more host memory (configurable).

Overall, we need to test this on our own to see if we can replicate the RPC failures ourselves. We also need to inform the auto-tuner on whether it should still recommend our shuffle manager on databricks.

**Comment by abellina** [comment]
With autoOptimizeShuffle.enabled = false, we still see the issue. We are also seeing a FetchFailure from the RapidsShuffleManager for a stage that had 1000 partitions, so we would not expect the bypass-merge shuffle.

**Comment by tgravescs** [comment]
Does the above only happen with: sqlContext.setConf("spark.databricks.adaptive.autoOptimizeShuffle.enabled", "true") ?

**Comment by abellina** [comment]
No it happens with and without, @kuhushukla tested that.

**Comment by kuhushukla** [comment]
Yes @tgravescs , ack Alessandro's comment. That config does not matter for this case. Works the same way with on or off.

**Comment by kuhushukla** [comment]
Some more discussion around the reader logic with Alessandro and ran the query on local spark cluster as well. 

The reader code does not depend on merge threshold config and we use it irrespective of the number of partitions. For this particular issue we should try to set `spark.rapids.shuffle.multiThreaded.maxBytesInFlight` to 128MB , something that is an upcoming change in 23.10 and check if that resolves the rpc failure issues.
