### ISSUE TITLE
[BUG] Fix `STRUCT` comparison between Pandas and Spark dataframes in `fastparquet` tests

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#9399]
**Description**

This is a follow-up to NVIDIA/spark-rapids/pull/9366.

`STRUCT` row comparison between Pandas and Spark dataframes seems to fail, seemingly because of a notational difference.

Consider `fastparquet_compatibility_test.py::test_reading_file_written_by_spark_cpu`. For the `STRUCT` case, the differences look as follows:
```
--- CPU OUTPUT
+++ GPU OUTPUT
@@ -1 +1 @@
-Row(a.first=-341142443, a.second=3.333994866005594e-37)
+Row(a=Row(first=-341142443, second=3.333994866005594e-37))
```
The `Row` read from the GPU/Plugin contains a `Row`, which matches the behaviour of Apache Spark reads.  The same data when read through `fastparquet` and converted into a Spark dataframe does not have nested rows.

This test is `xfail`ed for `STRUCT`. It would be good to change the comparison code to account for this notational difference.

**Comment by res-life** [comment]
I'll update the `_assert_equal` in `asserts.py` to convert the flattened Row to nested Row of Row

**Comment by revans2** [comment]
> I'll update the `_assert_equal` in `asserts.py` to convert the flattened Row to nested Row of Row

@res-life I don't know if we want to do that generically everywhere. I would rather have a way to modify the collected data instead so that we can do it only for cases where we know that it should happen.

**Comment by res-life** [comment]
If we do not update `_assert_equal`, then we can add a new function like `assert_gpu_and_fastparquet_are_equal_collect`, in this new function we do some conversion after collect the Row list. 
Investigated, we can not update the `ParquetFile`.`to_pandas` and can not make `to_pandas` return nested Row of Row.

**Comment by revans2** [comment]
I like the converter function. It is generic and can default to an identity function in most cases.
