### ISSUE TITLE
[BUG] CDH build failed due to missing dependencies

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#9416]
**Describe the bug**
https://github.com/NVIDIA/spark-rapids/actions/runs/6466750226/job/17555441510?pr=9415

not sure if its ephemeral issue for cdh shims build

```
Error:  Failed to execute goal on project rapids-4-spark-sql-plugin-api_2.12: 
Could not resolve dependencies for project com.nvidia:rapids-4-spark-sql-plugin-api_2.12:jar:23.10.0-SNAPSHOT: 
Failed to collect dependencies at org.apache.spark:spark-hive_2.12:jar:3.2.1.3.2.7171000.0-3 
-> org.apache.calcite:calcite-core:jar:1.19.0.7.1.7.1000-141 -> com.jayway.jsonpath:json-path:jar:2.4.0: 
Failed to read artifact descriptor for 
com.jayway.jsonpath:json-path:jar:2.4.0: Could not find artifact 
org.eclipse.sensinact.gateway.nthbnd:parent:pom:1.5-SNAPSHOT in cloudera-repo 
(https://repository.cloudera.com/artifactory/cloudera-repos/) -> [Help 1]
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by tgravescs** [comment]
I don't see it available in https://repository.cloudera.com/artifactory/cloudera-repos/, rekicked that build to check and failed again. I can ask our Cloudera contact.

Looking at a PR from a few days ago, I see it downloading json-path 2.4.0 but not org.eclipse.sensinact.gateway.nthbnd

**Comment by shreelola** [comment]
Can you please try again now?
 org.eclipse.sensinact.gateway.nthbnd:parent:pom:1.5-SNAPSHOT was coming from eclipse json pom com.jayway.jsonpath:json-path:jar:2.4.0. 
 We have removed it and build should go fine now.

**Comment by tgravescs** [comment]
Its now passing, thanks @shreelola
