### ISSUE TITLE
Execution default of goal net.alchim31.maven:scala-maven-plugin:4.6.1:compile failed.

### ISSUE THREAD

**Issue by sonalickwa** [NVIDIA/spark-rapids#9426]
I am using scala-maven-plugin version 4.6.1
However I am getting below error when I try to compile code

[INFO] --- scala-maven-plugin:4.6.1:compile (default) @ commonutils ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: C:\Users\sonalic\.sbt\1.0\zinc\org.scala-sbt\org.scala-sbt-compiler-bridge_2.12-1.6.1-bin_2.12.15__65.0-1.6.1_20220117T214008.jar
[INFO] Compiler bridge file is not installed yet
error:
  bad constant pool index: 0 at pos: 48445
     while compiling: <no file>
        during phase: globalPhase=<no phase>, enteringPhase=<some phase>
     library version: version 2.12.15
    compiler version: version 2.12.15
  reconstructed args: -bootclasspath C:\Users\sonalic\.m2\repository\org\scala-lang\scala-library\2.12.15\scala-library-2.12.15.jar -classpath C:\Users\sonalic\.m2\repository\jline\jline\2.14.6\jline-2.14.6.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-compiler\2.12.15\scala-compiler-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-reflect\2.12.15\scala-reflect-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-sbt\compiler-interface\1.6.1\compiler-interface-1.6.1.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\modules\scala-xml_2.12\1.0.6\scala-xml_2.12-1.0.6.jar;C:\Users\sonalic\.m2\repository\org\scala-sbt\util-interface\1.6.1\util-interface-1.6.1.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-compiler\2.12.15\scala-compiler-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-library\2.12.15\scala-library-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-reflect\2.12.15\scala-reflect-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\modules\scala-xml_2.12\1.0.6\scala-xml_2.12-1.0.6.jar;C:\Users\sonalic\.m2\repository\jline\jline\2.14.6\jline-2.14.6.jar -d C:\Users\sonalic\AppData\Local\Temp\scala-maven-plugin-compiler-bridge-classes16469125524792742467

  last tree to typer: EmptyTree
       tree position: <unknown>
            tree tpe: <notype>
              symbol: null
           call site: <none> in <none>

== Source file context for tree position ==

error: scala.reflect.internal.FatalError:
  bad constant pool index: 0 at pos: 48445
     while compiling: <no file>
        during phase: globalPhase=<no phase>, enteringPhase=<some phase>
     library version: version 2.12.15
    compiler version: version 2.12.15
  reconstructed args: -bootclasspath C:\Users\sonalic\.m2\repository\org\scala-lang\scala-library\2.12.15\scala-library-2.12.15.jar -classpath C:\Users\sonalic\.m2\repository\jline\jline\2.14.6\jline-2.14.6.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-compiler\2.12.15\scala-compiler-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-reflect\2.12.15\scala-reflect-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-sbt\compiler-interface\1.6.1\compiler-interface-1.6.1.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\modules\scala-xml_2.12\1.0.6\scala-xml_2.12-1.0.6.jar;C:\Users\sonalic\.m2\repository\org\scala-sbt\util-interface\1.6.1\util-interface-1.6.1.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-compiler\2.12.15\scala-compiler-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-library\2.12.15\scala-library-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\scala-reflect\2.12.15\scala-reflect-2.12.15.jar;C:\Users\sonalic\.m2\repository\org\scala-lang\modules\scala-xml_2.12\1.0.6\scala-xml_2.12-1.0.6.jar;C:\Users\sonalic\.m2\repository\jline\jline\2.14.6\jline-2.14.6.jar -d C:\Users\sonalic\AppData\Local\Temp\scala-maven-plugin-compiler-bridge-classes16469125524792742467

  last tree to typer: EmptyTree
       tree position: <unknown>
            tree tpe: <notype>
              symbol: null
           call site: <none> in <none>

== Source file context for tree position ==

        at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
        at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
        at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
        at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.errorBadIndex(ClassfileParser.scala:386)
        at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getExternalName(ClassfileParser.scala:250)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.readParamNames$1(ClassfileParser.scala:841)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:847)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$7(ClassfileParser.scala:921)

**Comment by jlowe** [comment]
This looks like an internal error within scala-maven-plugin when it's trying to setup the compiler bridge file before it gets around to compiling the Scala files in the project.  Have you tried reporting this error to the scala-maven-plugin project?

**Comment by sonalickwa** [comment]
can you please share where I can report this? Interestingly nobody in my team is hitting this issue

**Comment by sonalickwa** [comment]
Thanks for the JDK pointer. After updating to the same version as my team it worked. Thanks!
