### ISSUE TITLE
[Audit] SPARK-44448 Wrong results for dense_rank() <= k

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#9428]
Apache spark fixed a bug in dense_rank (specifically in DenseRankLimitIterator), specifically an optimization that was introduced in Spark 3.5.0. We should verify the plugin GPU behavior is correct on future Spark 3.5.x releases, and that we are potentially consistent with the issue in 3.5.0.

https://github.com/apache/spark/commit/f35c814f9b

**Comment by revans2** [comment]
I manually ran the test and there were no issues. We still produced the correct answer, even with https://github.com/NVIDIA/spark-rapids/issues/8208 not being implemented. So no problems here.
