### ISSUE TITLE
[FEA] For hash joins where the build side can change use the smaller table for the build side

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#9442]
**Is your feature request related to a problem? Please describe.**
In some joins, like an inner join, we can pick either left or right as the build side. Right now we always pick the right table as the build side. That is not a good solution, but oddly it has worked out really well in most cases.  We should have the join code so that if it pulls from what we guessed the build side to be and it is larger than a single batch, then we try to pull from the other side to see if it is smaller.

This is not really ideal because after getting a single batch we don't know if it is the last batch or not. We have some optimized code where it in some cases we can tag a batch as the final batch, but it would be good to at least have a follow on issue to try and add in this same kind of functionality as a follow on piece.

**Comment by viadea** [comment]
The ask from the user is at least to make Full Outer Join choose the right build side. 
Of course, if we can make both inner join together with Full Outer Join make the right decision that is better

**Comment by sameerz** [comment]
build
