### ISSUE TITLE
[FEA] Refactor benchmark code to avoid code duplication

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#945]
**Is your feature request related to a problem? Please describe.**
We have three TPC-* benchmarks that have almost identical parameters and there is a lot of duplicated boilerplate code in each benchmark and this makes it expensive to maintain because new features have to be implemented 3 times.

**Describe the solution you'd like**
It would be good to have one main method for running benchmarks and introduce traits that each of the benchmarks implements to provide the functionality of registering the input parquet/csv/orc tables with the Spark session and for executing a query based on a query identifier. This would significantly reduce the amount of code and make it easier to add new TPC-style benchmarks.

**Describe alternatives you've considered**
None.

**Additional context**
N/A.

**Comment by jlowe** [comment]
Does #964 close this?

**Comment by sameerz** [comment]
@andygrove confirmed this is closed by #964
