### ISSUE TITLE
[FEA] fail tests if memory leaks

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#9484]
**Is your feature request related to a problem? Please describe.**
We have memory leak detection, which works surprisingly well. But to know if something leaked we have to scan through a bunch of logs manually.  Ideally we would have a way to configure the logs during testing so that they go to a know (or set of known) places that are specific to the leak detection code.

Then after the tests have all run we can have a script to look through all of those logs and validate that no data was leaked and fail the build if we do see a leak.

We do need to be careful though. There are some unit tests in spark-rapids-jni that leak on purpose to test the leak detection. So this would just be for the plugin.  We also want to be sure that we don't detect leaks from pools of memory that we expect to not be closed when the process exits.  This is mainly the pinned memory pool.

**Comment by mattahrens** [comment]
Dup of https://github.com/NVIDIA/spark-rapids/issues/6947
