### ISSUE TITLE
Add integration or manual tests for pyspark, spark-shell, and spark-submit

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#9497]
**Is your feature request related to a problem? Please describe.**
We need to make sure we are testing pyspark, spark-shell and spark-submit (both client and cluster mode) because each one could have different classloaders.    Some of these are interactive so not sure if we can have automated tests but at some point before release we need to make sure we are testing.

We just found an issue that only surfaces on spark-shell, the issue looks like its classloader related.

**Comment by gerashegalov** [comment]
duplicates #5704
