### ISSUE TITLE
[BUG] Spark 3.2+/ParquetFilterSuite/Parquet filter pushdown - timestamp/ FAILED  

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#9507]
**Describe the bug**

ScalaTest in ParquetFilterSuite "Parquet filter pushdown - timestamp" fails presumably for all  Apache Spark 3.2+, actually tried only for 3.1.3, 3.2.0 and 3.5.0  

```
- Parquet filter pushdown - timestamp *** FAILED ***
  1024 was greater than 1, but 1024 was not less than 1024 (ParquetFilterSuite.scala:80)
```

**Steps/Code to reproduce bug**
```bash
rm -rf .m2
mvn clean
mvn install -pl tests -am -Dbuildver=320 -Dskip -DskipTests -Dmaven.repo.local=$PWD/.m2
mvn test -pl tests -Dbuildver=320 -Dskip  -Dmaven.repo.local=$PWD/.m2 \
  -Dsuites='org.apache.spark.sql.rapids.ParquetFilterSuite @Parquet filter pushdown - timestamp'
```

Same command succeeds for 313, and fails for 350

**Expected behavior**
Should succeed 

**Environment details (please complete the following information)**
 - Environment location: local dev
 - Spark configuration settings related to the issue: self-contained test

**Additional context**
Seen in the premerge failure for #9506

**Comment by jlowe** [comment]
This appears to be related to recent changes in cudf related to GPU writes.  If I disable GPU writes in the test, the test passes.  Trying to isolate the cudf change now.

**Comment by jlowe** [comment]
Filed rapidsai/cudf#14315
