### ISSUE TITLE
[FEA] Audit_3.0.1: Check first/last functionality changes from d669dea

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#954]
Need to triage Commit ID: d669dea
 Unevaluable expr is set to FIRST/LAST ignoreNullsExpr in distinct aggregates

Since it fixes a couple issues with first and last aggregates wrt to nulls.

**Comment by revans2** [comment]
Looking at the code https://github.com/apache/spark/commit/d669dea shows that the changes happened in planning the query and the only changes we need to worry about is that one of the parameters to First and Last changed from an Expression to a Boolean.  That was already addressed by the initial shim layer support for First and Last.
