### ISSUE TITLE
[QST] How to properly configure VSCode to support stepping through a spark-rapids Scala test?

### ISSUE THREAD

**Issue by PhilDakin** [NVIDIA/spark-rapids#9542]
My goal is to step through a single test from the [CostBasedOptimizerSuite](https://github.com/NVIDIA/spark-rapids/blob/ccd9ee25bfd748a6af4eeed62a308962814bae7b/tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala#L35) using a debugger.

Here is what I am doing:

- Using an AWS EC2 instance with CUDA support.
- Using VSCode 1.83.1.
- Install JDK8 ("java-1.8.0-openjdk-devel.x86_64").
- Install Maven 3.6.3.
- Clone the spark-rapids repo.
- Check out a recent release `git checkout branch-23.04`.
- Build cleanly with `mvn -U clean install -DskipTests`. This passes.
- Run build with buildall script `./build/buildall --profile=311` This passes.
- Generate bloop info with `./build/buildall --generate-bloop --profile=311` This passes.
- Link the 311 bloop info to the default bloop location `ln -s .bloop-spark311 .bloop`.
- Install the VSCode Metals plugin, decline prompt to import the Maven build.

Then, I see Metals compile `rapids-4-spark-sql_2.12` in the Metals output log:

```
2023.10.25 18:39:13 INFO  compiling rapids-4-spark-sql_2.12 (357 scala sources and 59 java sources)
2023.10.25 18:39:51 INFO  time: compiled rapids-4-spark-sql_2.12 in 37s
```

Once this is complete, 2 errors show up `semanticdb-javac: bloop`:

<img width="594" alt="Screenshot 2023-10-25 at 2 40 26 PM" src="https://github.com/NVIDIA/spark-rapids/assets/15946757/5032f4ab-755a-4c16-9565-536b0f79ce13">

There is no additional information provided for these errors. The Metals doctor shows that the library is failing to compile, but that everything else is all good.

<img width="1058" alt="Screenshot 2023-10-25 at 2 40 56 PM" src="https://github.com/NVIDIA/spark-rapids/assets/15946757/088d9f14-8d56-42f5-9474-5f8a91b39ea4">

The error seems related to SemanticDB generation during the Bloop build. As I understand it, the SemanticDB files should be generated when I run `./build/buildall --generate-bloop --profile=311`. But, after running this command, which internally runs:
```
      $MVN -B clean install \
        ch.epfl.scala:bloop-maven-plugin:bloopInstall \
        -pl aggregator -am \
        -Dbloop.configDirectory="$bloopTmpConfigDir" \
        -DdownloadSources=true \
        -Dbuildver="$bv" \
        -DskipTests \
        -Dskip \
        -Dmaven.javadoc.skip \
        -Dmaven.scalastyle.skip=true \
        -Dmaven.updateconfig.skip=true
``` 
I don't see any SemanticDB files generated:
```
[ec2-user@ip-172-31-67-168 spark-rapids]$ ls .bloop
bloop.settings.json                       rapids-4-spark-shuffle_2.12.json
rapids-4-spark-aggregator_2.12.json       rapids-4-spark-shuffle_2.12-test.json
rapids-4-spark-aggregator_2.12-test.json  rapids-4-spark-sql_2.12.json
rapids-4-spark-delta-stub_2.12.json       rapids-4-spark-sql_2.12-test.json
rapids-4-spark-delta-stub_2.12-test.json  rapids-4-spark-udf_2.12.json
rapids-4-spark-parent.json                rapids-4-spark-udf_2.12-test.json
rapids-4-spark-parent-test.json
[ec2-user@ip-172-31-67-168 spark-rapids]$ find . | grep semantic
[ec2-user@ip-172-31-67-168 spark-rapids]$
```

I'm seeking advice on how to continue debugging this issue. Is anybody able to successfully set and enforce breakpoints in Scala tests using Metals for VSCode?

**Comment by PhilDakin** [comment]
Potential idea - I just noticed that the [boom issue](https://github.com/NVIDIA/spark-rapids/blob/ccd9ee25bfd748a6af4eeed62a308962814bae7b/CONTRIBUTING.md#javalangruntimeexception-boom) referenced in the contribution guide is an exception raised by SemanticDB. I previously ruled it out because I don't actually see the exception anywhere in the logs.

I will try JDK update to JDK11 next, and see if the issue is resolved.

**Comment by PhilDakin** [comment]
Switching to JDK11 fixes the issues in the "PROBLEMS" pane of VSCode, and more promisingly I now see Metals continue and compile the other modules:
```
2023.10.25 20:20:42 INFO  compiling rapids-4-spark-sql_2.12 (357 scala sources and 59 java sources)
2023.10.25 20:22:01 INFO  compiling rapids-4-spark-udf_2.12 (8 scala sources)
2023.10.25 20:22:01 INFO  compiling rapids-4-spark-delta-stub_2.12 (1 scala source)
2023.10.25 20:22:01 INFO  compiling rapids-4-spark-shuffle_2.12 (4 scala sources)
2023.10.25 20:22:01 INFO  compiling rapids-4-spark-sql_2.12-test (7 scala sources)
```

I can now visually debug code in these modules.

But, my goal [CostBasedOptimizerSuite](https://github.com/NVIDIA/spark-rapids/blob/ccd9ee25bfd748a6af4eeed62a308962814bae7b/tests/src/test/scala/com/nvidia/spark/rapids/CostBasedOptimizerSuite.scala#L35) is in the `tests` module. The command executed by `./build/buildall --generate-bloop --profile=311` only builds bloop for `aggregator`.

After modifying `buildall` to generate bloop for the `tests` target, I see Metals successfully compile the module, and I am able to run the CBOSuite 👍 😄.

<img width="447" alt="Screenshot 2023-10-25 at 4 44 19 PM" src="https://github.com/NVIDIA/spark-rapids/assets/15946757/183a78f6-f542-4ab3-8669-03f73a0369b0">

**Comment by gerashegalov** [comment]
Hi @PhilDakin. I'll create an issue to update the doc and buildall. I gave up on JDK since the "boom" exception

I generally run something like

```bash
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 \
  mvn -Pjdk11  install ch.epfl.scala:bloop-maven-plugin:bloopInstall \
  -DdownloadSources=true \
  -Dbuildver=311 -Dskip -DskipTests -Dmaven.scalastyle.skip \ 
  -Dmaven.repo.local=$PWD/.bloop-m2
```

I am also noticing a new problem: Somehow DAP server or whatever is behind Metals debugger finds only the source code line information  in the the bloop project for the `tests` and spark dependencies but not in `rapids-4-spark-sql_2.12` or any other production part of the project.   

![image](https://github.com/NVIDIA/spark-rapids/assets/3187938/050a55cf-b2ec-4dc5-9b71-4cd6dd32ad32)
