### ISSUE TITLE
Update buildall and doc to generate bloop projects for test debugging

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#9547]
- Require JDK11+ in doc and buildall for creating bloop projects
- make sure all sub-modules are included
- figure out why product classes when debugging a `tests` class are shown "unknown source" while Spark dependencies retrieved with `-DdownloadSources` are fine.   

h/t: originally reported by @PhilDakin

_Originally posted by @gerashegalov in https://github.com/NVIDIA/spark-rapids/issues/9542#issuecomment-1780070731_

**Comment by PhilDakin** [comment]
@gerashegalov depending on expected turnaround time, I'd be keen to take this on as a first contribution.

At the latest I would open a PR by 11/2.

**Comment by gerashegalov** [comment]
Thank you @PhilDakin, go for it!

**Comment by gerashegalov** [comment]
related to #9556

**Comment by PhilDakin** [comment]
buildall/doc changes are easy. Still looking into the "Unknown Sources" issue. See corresponding issue on the Metals project: https://github.com/scalameta/metals/issues/5807

**Comment by gerashegalov** [comment]
> buildall/doc changes are easy. Still looking into the "Unknown Sources" issue. See corresponding issue on the Metals project: [scalameta/metals#5807](https://github.com/scalameta/metals/issues/5807)

Thanks for bringing up the issue with the scalameta team. We can handle this in issues and PRs separate from "simple" changes to the build and documentation.

**Comment by gerashegalov** [comment]
This is fixed by #9615,

"Unknown source" is filed https://github.com/scalameta/metals/issues/5807
