### ISSUE TITLE
[FEA] Audit_3.0.1: Check time stamp overflow bug fix impact on plugin side

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#955]
Need to triage Commit ID: f349a78
Fix silent data change for timestamp parsing if f overflow happens

This may not really apply so much to us but we need to check if any timestamp related functionality changed from this that we need to be aware of.

**Comment by revans2** [comment]
After reading the code change 
https://github.com/apache/spark/commit/f349a78
and the bug
https://issues.apache.org/jira/browse/SPARK-32424
They reverted a change where they attempted to be able to support string formats for years that are larger than 7 (i.e. any year larger than 9999999) for both parsing dates/timestamps from a format and for printing those dates/timestamps.  We only support two year characters `yy` and four year characters `yyyy`.  So in theory when we stop supporting 3.0.0 we could drop a few entries from 

https://github.com/NVIDIA/spark-rapids/blob/c923bde0abfce3100f2dd29c9d446c6cf51fe7f0/sql-plugin/src/main/scala/com/nvidia/spark/rapids/DateUtils.scala#L31

But I don't think it is an issue.
