### ISSUE TITLE
[BUG] precommit regularly fails with error trying to download a dependency

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#9559]
**Describe the bug**
At very specific times of the day we see precommit builds fail to download a maven dependency. It is odd because some of the builds will download the data and others will not. If we ask github to rebuild the failed jobs they usually will pass after that. We should try and find a way to fix this. I'm not sure if there is a way to ask maven to try again to download dependencies, but if there isn't we can always use the maven dependency plugin to [go-offline](https://maven.apache.org/plugins/maven-dependency-plugin/go-offline-mojo.html) and do that with a maximum number of retries, possibly with some throttling in between.

**Comment by pxLi** [comment]
We have already add retries to the maven command, but maven service maintained by apache is quite unstable (literally would be out of service everyday for some minutes, even hours)

Lets try add some retry strategies to step-level with some throttling in between
