### ISSUE TITLE
[AUDIT][SPARK-45543][SQL] InferWindowGroupLimit causes bug if the other window functions haven't the same window frame as the rank-like functions

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#9561]
We should add some code that would exercise `InferWindowGroupLimit` to make sure we are covered, in case things change in the future (the PR from spark has a test case we should port):

https://github.com/apache/spark/commit/feb48dc146d

**Comment by mattahrens** [comment]
We don't support the WindowGroupLimit exec currently, so no action is needed.

**Comment by kuhushukla** [comment]
Customer Request for this operator. Re-opening for tracking.
