### ISSUE TITLE
[FEA] Implement GPU versions for all the sub operators of TimeZoneAwareExpression

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#9570]
**Is your feature request related to a problem? Please describe.**
Some of sub operators of TimeZoneAwareExpression do not have GPU version.
The following operators are currently not supported by spark-rapids:

|operator | comment|
|--|--|
| CsvToStructs | Needs a Gpu version, parsing timestamp string to timestamp needs time zone info |
| StructsToCsv | Needs a Gpu version |
| CurrentDate | Needs a Gpu version |
| DateAddInterval | Has GPUDateAddInterval, but has limitation: interval expr must be scalar|
| LocalTimestamp | Needs a Gpu version |
| MakeTimestamp | Needs a Gpu version |
| MonthsBetween | Needs a Gpu version |
| ParseToDate | Needs a Gpu version |
| ParseToTimestamp | Needs a Gpu version |
| SecondWithFraction | Needs a Gpu version |
| SubtractTimestamps | Needs a Gpu version |
| TimestampAdd | Needs a Gpu version |
| TimestampAddYMInterval | Needs a Gpu version |
| TimestampDiff | Needs a Gpu version |
| TruncTimestamp | Needs a Gpu version |

Other time zone related Expressions which is not inherited from `TimeZoneAwareExpression`

- ConvertTimezone

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
It's from this [link](https://github.com/NVIDIA/spark-rapids/pull/9482#issuecomment-1771176853)
It's a follow on issue.

**Comment by mattahrens** [comment]
Closing as no use case is depending on this.
