### ISSUE TITLE
[BUG] non-deterministic compiled SQLExecPlugin.class with scala 2.13 deployment

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#9571]
**Describe the bug**
We saw it failed in our CI `not bitwise-identical across shims` constantly.

```
[2023-10-29T11:34:31.265Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (create-parallel-world) on project rapids-4-spark_2.13: An Ant BuildException has occured: The following error occurred while executing this line:
[2023-10-29T11:34:31.265Z] [ERROR] /home/jenkins/agent/workspace/jenkins-rapids_scala213_nightly-dev-github-4/dist/maven-antrun/build-parallel-worlds.xml:124: exec binary-dedupe.sh failed, exit code is 255, error msg is com/nvidia/spark/rapids/SQLExecPlugin.class is not bitwise-identical across shims
```

after comparing the generated SQLExecPlugin.class in different spark shims, I found the only diff is that
mvn install
```
public <A$> Function1<A$, BoxedUnit> compose(final Function1<A$, SparkSessionExtensions> g) {
        return Function1.compose$(this, g);
    }

    public <A$> Function1<SparkSessionExtensions, A$> andThen(final Function1<BoxedUnit, A$> g) {
        return Function1.andThen$(this, g);
    }
```
after following mvn deploy:
```
    public <A> Function1<A, BoxedUnit> compose(final Function1<A, SparkSessionExtensions> g) {
        return Function1.compose$(this, g);
    }

    public <A> Function1<SparkSessionExtensions, A> andThen(final Function1<BoxedUnit, A> g) {
        return Function1.andThen$(this, g);
    }
```

`A$ vs A`

**Steps/Code to reproduce bug**
run with internal `rapids_scala213_nightly-dev-github` pipeline (dup a pipeline for testing)
**UPDATE:** local repro steps https://github.com/NVIDIA/spark-rapids/issues/9571#issuecomment-1784615813

**Expected behavior**
After build SQLExecPlugin.class should always have the identical sha value in different shims, 
or move SQLExecPlugin.class out of check

**Comment by pxLi** [comment]
After a couple of testing, the issue was showed after deploy command.
if only mvn install the package it would always be 
```
# A$
c45c081c347546be188c12cbd64620f9974a1a04 *com/nvidia/spark/rapids/SQLExecPlugin.class
```

but in nightly, after we do mvn deploy for aggregator artifacts, it would become
```
# A
361897d6318eadacacf6f46e7e827b19558e035e *com/nvidia/spark/rapids/SQLExecPlugin.class
```

which is weird

**Comment by jlowe** [comment]
Some simpler repro steps that do not require access to the internal repository, any CI Jenkins settings, and doesn't spend time building unrelated projects in the repo:
```
$ mvn clean install -pl sql-plugin -am -Dcuda.version=cuda11 -DskipTests -Dskip -Dbuildver=331
[... mvn output elided ...]
$ javap -cp sql-plugin/target/spark331/rapids-4-spark-sql_2.13-23.12.0-SNAPSHOT-spark331.jar com.nvidia.spark.rapids.SQLExecPlugin | grep compose
  public <A$> scala.Function1<A$, scala.runtime.BoxedUnit> compose(scala.Function1<A$, org.apache.spark.sql.SparkSessionExtensions>);
$ mvn deploy -pl sql-plugin -am -Dcuda.version=cuda11 -DskipTests -Dskip -Dbuildver=331 -DaltDeploymentRepository=tmplocalrepo::default::file:/tmp/tmplocalrepo
[... mvn output elided ...]
$ javap -cp sql-plugin/target/spark331/rapids-4-spark-sql_2.13-23.12.0-SNAPSHOT-spark331.jar com.nvidia.spark.rapids.SQLExecPlugin | grep compose
  public <A> scala.Function1<A, scala.runtime.BoxedUnit> compose(scala.Function1<A, org.apache.spark.sql.SparkSessionExtensions>);
```

**Comment by jlowe** [comment]
Verified this is not really the deploy goal that is directly problem but rather the fact that the deploy goal implicitly re-runs the install goal (and all previous goals like compile).  Here's even simpler repro steps:
```
$ mvn clean install -pl sql-plugin -am -Dcuda.version=cuda11 -DskipTests -Dskip -Dbuildver=331
[... mvn output elided ...]
$ javap -cp sql-plugin/target/spark331/rapids-4-spark-sql_2.13-23.12.0-SNAPSHOT-spark331.jar com.nvidia.spark.rapids.SQLExecPlugin | grep compose
  public <A$> scala.Function1<A$, scala.runtime.BoxedUnit> compose(scala.Function1<A$, org.apache.spark.sql.SparkSessionExtensions>);
$ rm sql-plugin/target/spark331/classes/com/nvidia/spark/rapids/SQLExecPlugin.class
$ mvn install -pl sql-plugin -am -Dcuda.version=cuda11 -DskipTests -Dskip -Dbuildver=331
[... mvn output elided ...]
$ javap -cp sql-plugin/target/spark331/rapids-4-spark-sql_2.13-23.12.0-SNAPSHOT-spark331.jar com.nvidia.spark.rapids.SQLExecPlugin | grep compose
  public <A> scala.Function1<A, scala.runtime.BoxedUnit> compose(scala.Function1<A, org.apache.spark.sql.SparkSessionExtensions>);
```

For some reason SQLExecPlugin and 22 other files are getting recompiled in the sql-plugin project as part of the prerequisite phases executed before the deploy phase, and it's during that recompile that the change occurs.  I verified from Maven `-X` output that we're passing the same scala compiler options in both cases, so it's not clear why it comes out different during a fresh compile but not during a recompile.

**Comment by jlowe** [comment]
I verified that if we avoid doing an install run first followed by a deploy and instead directly build everything during a single deploy build, we end up with `A$` instead of `A`.

**Comment by jlowe** [comment]
The affected functions are part of scala.Function1, so on a hunch, I looked for other classes in sql-plugin that are using that trait.  Other classes are affected by this if recompiled in isolation (e.g.: GpuLog) (i.e.: `A$` becomes `A` for the `compose` signature).  Oddly, removing ScalaStack.class to force it to recompile at the same time as the scala.Function1 descendants seems to fix it. For example, this slight modification to the above repro steps "fixes" the inconsistency:
```
$ mvn clean install -pl sql-plugin -am -Dcuda.version=cuda11 -DskipTests -Dskip -Dbuildver=331
[... mvn output elided ...]
$ javap -cp sql-plugin/target/spark331/rapids-4-spark-sql_2.13-23.12.0-SNAPSHOT-spark331.jar com.nvidia.spark.rapids.SQLExecPlugin | grep compose
  public <A$> scala.Function1<A$, scala.runtime.BoxedUnit> compose(scala.Function1<A$, org.apache.spark.sql.SparkSessionExtensions>);
$ rm sql-plugin/target/spark331/classes/com/nvidia/spark/rapids/SQLExecPlugin.class sql-plugin/target/spark331/classes/com/nvidia/spark/rapids/ScalaStack.class
$ mvn install -pl sql-plugin -am -Dcuda.version=cuda11 -DskipTests -Dskip -Dbuildver=331
[... mvn output elided ...]
$ javap -cp sql-plugin/target/spark331/rapids-4-spark-sql_2.13-23.12.0-SNAPSHOT-spark331.jar com.nvidia.spark.rapids.SQLExecPlugin | grep compose
  public <A$> scala.Function1<A$, scala.runtime.BoxedUnit> compose(scala.Function1<A$, org.apache.spark.sql.SparkSessionExtensions>);
```

**Comment by jlowe** [comment]
If I hack out the use of ScalaStack and have the code just use scala.collection.mutable.Stack directly for the 2.13 build, the `A$` goes away in all the uses in `compose` that I checked and instead become `A`.  A recompile leaves it at `A` as expected, so the problems seem related to ScalaStack somehow.
