### ISSUE TITLE
[FEA] Add oci:/ blobstore to our spark.rapids.cloudSchemes

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#9579]
**Is your feature request related to a problem? Please describe.**
We are starting to run on OCI, we should do some testing to verify that the multi-threaded reader performs better and  add oci:/ blobstore to our spark.rapids.cloudSchemes if it does.

**Comment by mattahrens** [comment]
Dup of https://github.com/NVIDIA/spark-rapids/issues/7332
