### ISSUE TITLE
[FEA] Audit_3.0.1: This might affect our Casting string to timestamp

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#959]
commit 4638402d4775acf0d7ff190ef5eabb6f2dc85af5
Author: Kent Yao <yaooqinn@hotmail.com>
Date:   Thu Jun 11 03:29:12 2020 +0000

    [SPARK-31939][SQL][TEST-JAVA11] Fix Parsing day of year when year field pattern is missing

**Comment by revans2** [comment]
So the changes themselves actually deal with `D`, `DD`, `DDD`, which corresponds to the day of the year, which we don't support.  This fixes some corner cases around it where you could specify it along with other date/month values that might conflict with one another, and verify that they fail.

One of the things that we do need to test is that when we parse a date if the year is not present that it defaults to 1970.

**Comment by razajafri** [comment]
This is a lower priority than the current goal of fixing all p1s. Will pick this up after the release
