### ISSUE TITLE
[DOC] Many sections in the document are disappeared.

### ISSUE THREAD

**Issue by zhangchenqi123** [NVIDIA/spark-rapids#9598]
It seems many sections in the [documents ](https://nvidia.github.io/spark-rapids/)are disappeared, like getting started, Tuning.

They have disappered three or four days ago. I have posted a comparison figure here.

Where are they?  I need them very much.

Thanks.

![image](https://github.com/NVIDIA/spark-rapids/assets/58100940/5f499f16-11c0-4809-9212-f6770224ae37)

**Comment by mattahrens** [comment]
I apologize for the confusion.  We recently launched our new User Guide on the docs.nvidia.com site and migrated some of our pages to that location.  You can view the User Guide here: https://docs.nvidia.com/spark-rapids/user-guide/latest/index.html.

We'll try to make it more clear on the github.io landing page for Spark RAPIDS that the User Guide is available.
