### ISSUE TITLE
[FEA] Audit_3.0.1: Repartition obeys initialPartitionNum when adaptiveExecutionEnabled

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#960]
commit b9a1cd8d4bb1241e27fd78c04a892c10f1a62147
Author: Yuming Wang <yumwang@ebay.com>
Date:   Tue Jun 9 16:07:22 2020 +0000

    [SPARK-31220][SQL] repartition obeys initialPartitionNum when adaptiveExecutionEnabled

**Comment by kuhushukla** [comment]
Please rename this issue as it doesn't tell us what it is about

**Comment by kuhushukla** [comment]
@razajafri Could you elaborate on how and why we need to audit this further?

**Comment by nartal1** [comment]
Looked at it closely, the change is in EnsureRequirements where if the config `spark.sql.adaptive.coalescePartitions.initialPartitionNum`  is set, then the same partition number is carried over for GROUP BY  aggregates. No changes required in RAPIDS Accelerator code.
