### ISSUE TITLE
[FEA] Audit_3.0.1: AQE changes to support Columnar exchanges

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#963]
commit 7c91b15c22fe875a44e08781caf3422bfca81b19
Author: Andy Grove <andygrove@nvidia.com>
Date:   Fri Jul 31 11:14:33 2020 -0500

    [SPARK-32332][SQL][3.0] Support columnar exchanges

**Comment by kuhushukla** [comment]
Can we please me the audit issues with what piece of code it is touching. The title is not very helpful

**Comment by andygrove** [comment]
This PR was the backport of SPARK-32332 to the 3.0 branch and was subsequently released in 3.0.1. There is nothing further that we need to do in the plugin related to this, as far as I know.

**Comment by kuhushukla** [comment]
Can we close this @andygrove ?

**Comment by andygrove** [comment]
Closing this as no further action needed.
