### ISSUE TITLE
[BUG] All parquet integration tests failed "Part of the plan is not columnar class" in databricks runtimes

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#9636]
**Describe the bug**
pyspark.errors.exceptions.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.ColumnarToRowExec

```
= 731 failed, 18859 passed, 1655 skipped, 670 xfailed, 305 xpassed, 946 warnings in 8711.99s (2:25:11) =
```

```
a = ('xro576720', <py4j.clientserver.JavaClient object at 0x7f830cba4d90>, 'o576717', 'collectToPython')
kw = {}, converted = IllegalArgumentException()

    def deco(*a: Any, **kw: Any) -> Any:
        try:
            return f(*a, **kw)
        except Py4JJavaError as e:
            converted = convert_exception(e.java_exception)
            if not isinstance(converted, UnknownException):
                # Hide where the exception came from that shows a non-Pythonic
                # JVM exception message.
>               raise converted from None
E               pyspark.errors.exceptions.IllegalArgumentException: Part of the plan is not columnar class org.apache.spark.sql.execution.ColumnarToRowExec
E               ColumnarToRow
E               +- FileScan parquet [a#105128,part#105129] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/tmp/pyspark_tests/1105-062535-xa8ofuw0-10-59-181-48-gw1-4283-158..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<a:timestamp,part:int>
```

**Steps/Code to reproduce bug**
Run parquet_test in databricks runtimes

**Expected behavior**
pass the tests

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by firestarman** [comment]
Is there ant log for the overrides explain, which can tell the specific reason why ColumnarToRowExec can not run on GPU ?

**Comment by pxLi** [comment]
> Is there any log for the overrides explaining, which can tell the specific reason why ColumnarToRowExec can not run on GPU ?

related to https://github.com/NVIDIA/spark-rapids/pull/9617, @ttnghia is working on this
