### ISSUE TITLE
[BUG] The problem of OpenJDK use almost of GRAMs

### ISSUE THREAD

**Issue by leehaoun** [NVIDIA/spark-rapids#9638]
**Describe the bug**
OpenJDK use almost of GRAMs when job is submitted

**Steps/Code to reproduce bug**
`from pyspark.sql import SparkSession
from pyspark import SparkConf
from pyspark import SparkContext as sc
import numpy as np
from spark_rapids_ml.regression import LinearRegression, LinearRegressionModel
from pyspark.ml.classification import LogisticRegression, LogisticRegressionModel
from pyspark.ml.linalg import Vectors
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.evaluation import MulticlassClassificationEvaluator 
from pyspark.ml import Pipeline 
from pyspark.sql.functions import col, pandas_udf, PandasUDFType, lit
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, FloatType, ArrayType, BinaryType
import tensorflow as tf
from functools import reduce 
from typing import Iterator
from pyspark.ml.linalg import Vectors , VectorUDT , DenseVector
import cv2
import pandas as pd
from pyspark.sql.functions import udf

def PandasDFtoNumpy(pdf, color_scheme=cv2.COLOR_BGR2RGB) :
        results = []
        for i in range(0, len(pdf)):
            width = pdf['width'].values[i]
            height = pdf['height'].values[i]
            nChannel = pdf['nChannels'].values[i]
            if width == -1 and height == -1 :
                print("width:", width)
                print("height:", height)
                print("nChannel:", nChannel)
                empty_array = cv2.cvtColor(np.zeros((224, 224, 1), dtype=np.uint8), color_scheme)
                results.append(empty_array)
            else:
                np_array = np.frombuffer(pdf['data'].values[i], dtype=np.uint8)
                results.append(cv2.cvtColor( np_array.reshape((height, width , nChannel)),color_scheme ) )
        return results

@pandas_udf(ArrayType(IntegerType()))
def resize_image(iterator: Iterator[pd.DataFrame]) -> Iterator[pd.DataFrame]:
    try:
        result = []
        temp1 = None
        temp2 = None
        for pdf in iterator:
            # reshape the array
            cv2_images = PandasDFtoNumpy(pdf)
            temp1 = pdf
            temp2 = cv2_images
            for img in cv2_images:
                if img is None:
                    print("resize fail")
                    result.append(None)
                else:
                    img = cv2.resize(img, (224, 224))
                    flat = img.flatten()
                    result.append(flat)
            res = pd.Series(result)
            yield res
    except TypeError:
            print("temp1:", temp1)
            print(len(temp1))
            print(str(type(temp1)))
            print("temp1:", temp2)
            print(len(temp2))
            print(str(type(temp2)))

def image_to_vector(image):
    return Vectors.dense(image)

def printAll(data):
    print(data)
    print(str(type(data)))
    try:
        print(len(data))
    except TypeError:
        print("data 객체는 len() 함수를 지원하지 않습니다.")
    if hasattr(data, 'shape'):
        print(data.shape)
    else:
        print("data.shape 속성이 존재하지 않습니다.")

conf = SparkConf()
conf.set("spark.executor.cores", "2")
conf.set("spark.executor.memory", "128G")
conf.set("spark.executor.instances", "1")
conf.set("spark.executor.resource.gpu.amount", "1")
conf.set("spark.task.cpus", "1")
conf.set("spark.task.resource.gpu.amount", "0.5")
conf.set("spark.rapids.sql.explain", "NOT_ON_GPU")
conf.set("spark.rapids.sql.concurrentGpuTasks", "2")
conf.set("spark.sql.files.maxPartitionBytes", "512m")
conf.set("spark.plugins", "com.nvidia.spark.SQLPlugin")
conf.set("spark.rapids.sql.python.gpu.enabled","true")

spark = SparkSession.builder \
    .appName("Linear_Regression") \
    .config(conf=conf) \
    .getOrCreate()   

image_to_vector_udf = udf(image_to_vector, VectorUDT())
cassetteDF = spark.read.format("image").load( "/dev/shm/RamDisk/imagenette2/train/cassette" )
resized_cassetteDF = cassetteDF.select(resize_image(cassetteDF["image"]).alias("resized_image")).withColumn( "label" , lit( 0 ))
castleDF = spark.read.format("image").load("/dev/shm/RamDisk/imagenette2/train/castle" )
resized_castleDF = castleDF.select(resize_image(castleDF["image"]).alias("resized_image")).withColumn( "label" , lit( 1 ))
chainsawDF = spark.read.format("image").load( "/dev/shm/RamDisk/imagenette2/train/chainsaw" )
resized_chainsawDF= chainsawDF.select(resize_image(chainsawDF["image"]).alias("resized_image")).withColumn( "label" , lit( 2 ))
data_frames = [resized_cassetteDF, resized_castleDF, resized_chainsawDF]

train_df = reduce( lambda first, second: first.union(second), data_frames) 

train_df = train_df.withColumn("resized_image", image_to_vector_udf("resized_image"))

assembler = VectorAssembler().setInputCols(['resized_image']).setOutputCol('features')
train_df = assembler.transform(train_df)

train_df = train_df.repartition( 1 ) 

print("Regression Start")

lr = LogisticRegression()
lr.setMaxIter(5)
lr.setRegParam(0)
lr.setFeaturesCol("features")
lr.setLabelCol("label")
Spark_model = lr.fit(train_df)
Spark_model.save("hdfs://127.0.0.1:9000/model/Logistic_model")
`
**Expected behavior**
reduce GRAM share by openJDK 

**Environment details (please complete the following information)**
- Standalone
- spark : spark-3.4.1-bin-hadoop3
- rapids jar : rapids-4-spark_2.12-23.10.0.jar
- kafka : kafka_2.12-3.2.1
- hadoop : hadoop-3.3.6
- conf = SparkConf()
conf.set("spark.executor.cores", "2")
conf.set("spark.executor.memory", "128G")
conf.set("spark.executor.instances", "1")
conf.set("spark.executor.resource.gpu.amount", "1")
conf.set("spark.task.cpus", "1")
conf.set("spark.task.resource.gpu.amount", "0.5")
conf.set("spark.rapids.sql.explain", "NOT_ON_GPU")
conf.set("spark.rapids.sql.concurrentGpuTasks", "2")
conf.set("spark.sql.files.maxPartitionBytes", "512m")
conf.set("spark.plugins", "com.nvidia.spark.SQLPlugin")
conf.set("spark.rapids.sql.python.gpu.enabled","true")

**Additional context**

Hi, When i submit job using 

spark-submit\
       --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 \
       --jars ${SPARK_RAPIDS_PLUGIN_JAR} \
       --master spark://127.0.0.1:7077 \
       /root/sources/rapids/Examples/Linear_Train.py   

The GRAM usage of the GPU confirmed in nvidia-smi quickly reaches almost its maximum.
Without any specific tasks, as soon as the job starts, it uses almost the majority of the GRAM, and Spark operates.

![jdk use 8800MB of GPU GRAM](https://github.com/rapidsai/docs/assets/88310559/37a71722-f909-40cf-9168-2e625e3c0493)

**Comment by jlowe** [comment]
Note that lowering the amount of GPU memory that the RAPIDS Accelerator can use could result in more GPU memory spilling during queries and thus lower performance overall.
