### ISSUE TITLE
[BUG] Existence default values in schema are not being honored

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9648]
[SPARK-39143](https://issues.apache.org/jira/browse/SPARK-39143) added default value support for fields in a Spark schema. The RAPIDS Accelerator does not check for the use of this feature in a schema nor does it implement the behavior.  It looks like it was primarily added for CSV, but it is also supported by JSON reads and also is referenced in the CPU code that builds Parquet column readers.

**Comment by mattahrens** [comment]
Scope for this issue: fallback appropriately when existence default values are detected.

Long-term: file separate issue to track full support of existence default values in the plugin.

**Comment by firestarman** [comment]
From Spark 340, ORC, Parquet, JSON and CSV all support the default values in schema.
See

1.  ORC          [SPARK-39294](https://issues.apache.org/jira/browse/SPARK-39294)
2.  Paruqet    [SPARK-39265](https://issues.apache.org/jira/browse/SPARK-39265)
3.  CSV         [SPARK-39143](https://issues.apache.org/jira/browse/SPARK-39143)
4.  JSON     [SPARK-39211](https://issues.apache.org/jira/browse/SPARK-39211)

**Comment by firestarman** [comment]
Fallback solution is here https://github.com/NVIDIA/spark-rapids/pull/9765
