### ISSUE TITLE
[BUG] rapids4spark-version-info.properties file getting corrupted during nightly builds

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9662]
A few times now we've seen corrupted rapids4spark-version-info.properties files in various artifacts.  First it was the spark313 integration tests artifact where the file was present in the jar but empty, then recently it was the spark350 aggregator artifact where the file was only 4 bytes of 0x00.

**Comment by pxLi** [comment]
this could also happen to all other intermediate artifacts like IT or aggregator ones intermittently.

I have been trying to add debug log in maven processing but no useful info. the property files would just be empty but all other artifacts (ahead or after) in the same agent/container can correctly generate the property files

**Comment by pxLi** [comment]
Let me re-assign to @GaryShen2008 for now. Please let me know if I could help with anything, thanks
