### ISSUE TITLE
[FEA][JSON] Add support for non default `dateFormat` in `from_json`

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#9667]
**Is your feature request related to a problem? Please describe.**
PR https://github.com/NVIDIA/spark-rapids/issues/9590 adds basic support for dates in `from_json` but only supports the default `dateFormat` of `yyyy-MM-dd`.

**Describe the solution you'd like**
I would like to be able to support other formats.

**Describe alternatives you've considered**

**Additional context**

**Comment by mattahrens** [comment]
Added as low priority to this epic: https://github.com/NVIDIA/spark-rapids/issues/9
