### ISSUE TITLE
[BUG] Casting FLOAT64 to DECIMAL(12,7) produces different rows from Apache Spark CPU

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#9682]
Update:

This bug was originally filed with the title: 
> [BUG] test_window_aggs_for_rows fails with rounding errors with DATAGEN_SEED=1698940723

It has since been established that the problem does not lie in window functions, or aggregations. The problem is with casting float64 to decimal, producing rounding errors.

Repro:
```scala
Seq(3527.61953125).toDF("d").repartition(1).selectExpr("CAST(d AS DECIMAL(12,7)) as_decimal").show
```
This produces different results on CPU and GPU.
On CPU:
```scala
+------------+
|  as_decimal|
+------------+
|3527.6195313|
+------------+
```
On GPU:
```scala
+------------+
|  as_decimal|
+------------+
|3527.6195312|
+------------+
```

The old description continues below:

`test_window_aggs_for_rows` fails with `DATAGEN_SEED=1698940723`.

Repro:
```
SPARK_RAPIDS_TEST_DATAGEN_SEED=1698940723 ./run_pyspark_from_build.sh -k test_window_aggs_for_row\ and\ RepeatSeq\ and\ Integer\ and\ Decimal
```

```
 [gw4]^[[36m [ 96%] ^[[0m^[[31mFAILED^[[0m ../../src/main/python/window_function_test.py::test_window_aggs_for_rows[[('a', RepeatSeq(Long)), ('b', Integer), ('c', Decimal(8,3))]-1000][DATAGEN_SEED=1698940723, IGNORE_ORDER({'local': True})]
[gw4]^[[36m [ 96%] ^[[0m^[[31mFAILED^[[0m ../../src/main/python/window_function_test.py::test_window_aggs_for_rows[[('a', RepeatSeq(Long)), ('b', Integer), ('c', Decimal(8,3))]-1g][DATAGEN_SEED=1698940723, IGNORE_ORDER({'local': True})
```

```
[2023-11-02T17:07:56.063Z]  Row(sum_c_asc=Decimal('-231179.895'), max_c_desc=Decimal('-48178.972'), min_c_asc=Decimal('-99999.999'), count_1=103, count_c=97, avg_c=Decimal('-9080.9564433'), rank_val=57, dense_rank_val=57, percent_rank_val=0.5490196078431373, row_num=57)
[2023-11-02T17:07:56.064Z]  Row(sum_c_asc=Decimal('-227954.458'), max_c_desc=Decimal('89948.943'), min_c_asc=Decimal('-95651.987'), count_1=103, count_c=98, avg_c=Decimal('-598.2695306'), rank_val=82, dense_rank_val=82, percent_rank_val=0.7941176470588235, row_num=82)
[2023-11-02T17:07:56.064Z]  Row(sum_c_asc=Decimal('-223873.440'), max_c_desc=Decimal('48971.237'), min_c_asc=Decimal('-86568.757'), count_1=102, count_c=94, avg_c=Decimal('9590.8501170'), rank_val=88, dense_rank_val=88, percent_rank_val=0.8613861386138614, row_num=88)
[2023-11-02T17:07:56.064Z] -Row(sum_c_asc=Decimal('-220416.559'), max_c_desc=Decimal('34383.780'), min_c_asc=Decimal('-67119.262'), count_1=102, count_c=96, avg_c=Decimal('3527.6195313'), rank_val=84, dense_rank_val=84, percent_rank_val=0.8217821782178217, row_num=84)
[2023-11-02T17:07:56.064Z] +Row(sum_c_asc=Decimal('-220416.559'), max_c_desc=Decimal('34383.780'), min_c_asc=Decimal('-67119.262'), count_1=102, count_c=96, avg_c=Decimal('3527.6195312'), rank_val=84, dense_rank_val=84, percent_rank_val=0.8217821782178217, row_num=84)
[2023-11-02T17:07:56.064Z]  Row(sum_c_asc=Decimal('-220028.169'), max_c_desc=Decimal('2270.621'), min_c_asc=Decimal('-91351.118'), count_1=102, count_c=97, avg_c=Decimal('-4903.2057010'), rank_val=47, dense_rank_val=47, percent_rank_val=0.45544554455445546, row_num=47)
[2023-11-02T17:07:56.064Z]  Row(sum_c_asc=Decimal('-219560.674'), max_c_desc=Decimal('-32132.633'), min_c_asc=Decimal('-95941.789'), count_1=102, count_c=95, avg_c=Decimal('-1184.0629789'), rank_val=4, dense_rank_val=4, percent_rank_val=0.0297029702970297, row_num=4)
[2023-11-02T17:07:56.064Z]  Row(sum_c_asc=Decimal('-219399.848'), max_c_desc=Decimal('43804.921'), min_c_
```

**Comment by ttnghia** [comment]
We've observed the same issue before, as documented:
```
# Spark supports times starting at
            # "0001-01-01 00:00:00.000000"
            # but it has issues if you get really close to that because it tries to do things
            # in a different format which causes roundoff, so we have to add a few days,
            # just to be sure
            start = datetime(1, 1, 3, tzinfo=tzinfo)
```
However, generating timestamps from `datetime(1, 1, 3)` is not enough. When deserializing from Spark into Python we still get data roundoff issue. For example, from `test_ts_formats_round_trip`:
```
self = TimestampType, ts = -62135596800000000

    def fromInternal(self, ts):
        if ts is not None:
            # using int to avoid precision loss in float
>           return datetime.datetime.fromtimestamp(ts // 1000000).replace(microsecond=ts % 1000000)
E           ValueError: year 0 is out of range
```

The corresponding timestamp that causes error is `0001-01` read from csv. For better avoiding the issue, we should start from `datetime(1, 2, 1)` instead. I tried that the tests pass.

**Comment by mythrocks** [comment]
Attached
[herewith](https://github.com/NVIDIA/spark-rapids/files/13444584/decimals_avg.parquet.zip) is a zipped Parquet file with 102 rows in a single `Decimal(8,3)` column.

Taking the window functions out of the equation, one sees that running `AVG()` produces slightly different results on Apache Spark and the plugin:
```scala
// On Spark.
scala> spark.read.parquet("/tmp/decimals_avg.parquet").select( expr("avg(c)") ).show
+------------+
|      avg(c)|
+------------+
|3527.6195313|
+------------+

// On the plugin:
+------------+
|      avg(c)|
+------------+
|3527.6195312|
+------------+
```

**Comment by mythrocks** [comment]
I have filed https://github.com/rapidsai/cudf/issues/14507 to track the CUDF side of this.

I was able to repro this on CUDF by writing the input as `DECIMAL(12,7)` to Parquet, and then running the `MEAN` aggregation on it.  The bug I filed has the repro details.

**Comment by mythrocks** [comment]
A couple of other findings. I tried querying `SUM`, `COUNT`, `AVG`, etc. as follows:
```sql
select sum(c),  count(c), sum(c)/count(c), avg(c), cast(avg(c) as DECIMAL(12,8)) , cast(sum(c)/count(c) as decimal(12,7)) from foobar 
```
On CPU, those results tally up:
```
+----------+--------+----------------------------+------------+-----------------------------+------------------------------------------+
|sum(c)    |count(c)|(sum(c) / count(c))         |avg(c)      |CAST(avg(c) AS DECIMAL(12,8))|CAST((sum(c) / count(c)) AS DECIMAL(12,7))|
+----------+--------+----------------------------+------------+-----------------------------+------------------------------------------+
|338651.475|96      |3527.61953125000000000000000|3527.6195313|3527.61953130                |3527.6195313                              |
+----------+--------+----------------------------+------------+-----------------------------+------------------------------------------+

```

Here's what one finds on GPU:
```
+----------+--------+----------------------------+------------+-----------------------------+------------------------------------------+
|sum(c)    |count(c)|(sum(c) / count(c))         |avg(c)      |CAST(avg(c) AS DECIMAL(12,8))|CAST((sum(c) / count(c)) AS DECIMAL(12,7))|
+----------+--------+----------------------------+------------+-----------------------------+------------------------------------------+
|338651.475|96      |3527.61953125000000000000000|3527.6195312|3527.61953120                |3527.6195313                              |
+----------+--------+----------------------------+------------+-----------------------------+------------------------------------------+
```

**Comment by mythrocks** [comment]
There were some red herrings in investigating this bug.

First off, I have closed the CUDF bug (rapidsai/cudf#14507) I raised for this.  CUDF is not at fault; it consistently truncates additional decimal digits.

It looked like this might have to do with `GpuDecimalAverage` and `GpuDecimalDivide`, but those operators are not involved. Consider this query:
```sql
SELECT avg(c) FROM foobar; -- c is a DECIMAL(8,3).
```
The execution plan indicates `GpuDecimalAverage` isn't invoked at all. The operation is done completely in integer/double, and the result is cast to `DECIMAL(12,7)`:
```
== Optimized Logical Plan ==Aggregate [cast((avg(UnscaledValue(c#9)) / 1000.0) as decimal(12,7)) AS avg(c)#888]
+- Relation [c#9] parquet

== Physical Plan ==
GpuColumnarToRow false
+- GpuHashAggregate(keys=[], functions=[avg(UnscaledValue(c#9), DoubleType)], output=[avg(c)#888])
   +- GpuShuffleCoalesce 1073741824
      +- GpuColumnarExchange gpusinglepartitioning$(), ENSURE_REQUIREMENTS, [plan_id=1819]
         +- GpuHashAggregate(keys=[], functions=[partial_avg(UnscaledValue(c#9), DoubleType)], output=[sum#892, count#893L])
            +- GpuFileGpuScan parquet [c#9] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex[file:/tmp/decimals_avg.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<c:decimal(8,3)>
```
The `avg()` is computed on the unscaled decimal reps, and the average is divided by `1000.0`.  The result is cast to `DECIMAL(12,7)`.

The `avg()` and the divide produce the same results on CPU and GPU.  So this amounts to a casting problem.

Here's the simplest repro for the problem:
```scala
Seq(3527.61953125).toDF("d").repartition(1).selectExpr("d", "CAST(d AS DECIMAL(12,7))").show
```
On CPU:
```
+-------------+---------------+
|            d|as_decimal_12_7|
+-------------+---------------+
|3527.61953125|   3527.6195313|
+-------------+---------------+
```
On GPU:
```
+-----------+---------------+
|          d|as_decimal_12_7|
+-----------+---------------+
|3527.619531|   3527.6195312|
+-----------+---------------+
```
(Ignore how `d` is printed as `3527.619531` on GPU.  I think that's just a string/display formatting issue. The correct/complete value is written if serialized to file.)

All mention of window functions, aggregation, `GpuDecimalAverage` and everything else is a distraction.

**Comment by revans2** [comment]
I am remembering more now.  Converting a double to a decimal value has problems because they do it by going from a double to a string to a decimal. This is inherent in how scala does it in their BigDecimal class, and it is even a bit of magic with an implicit method that just makes it happen behind the scenes. But going from a Double to a String we cannot match what java does. It is not standard which is why we have `spark.rapids.sql.castStringToFloat.enabled`, which is off by default. Now I really want to understand what would happen if this optimization is disabled and what the result really would be. Is Spark right and we are wrong, or is Spark wrong and we are right?

**Comment by revans2** [comment]
But before we do any of that I want to be sure that we know what the original input long was before the divide happened and what the double was that we are dividing? I am assuming that it was `(352761953125 / 10 ^ 8)`

**Comment by mythrocks** [comment]
> know what the original input long was before the divide happened and what the double was that we are dividing? I am assuming that it was `(352761953125/ 10 ^ 8)`

Not exactly. The result of the average (of the unscaled decimals) was `3527619.53125L`. That was then divided by `1000.0L` to rescale it.

**Comment by mythrocks** [comment]
I've relinquished ownership on this bug. I'm not actively working on this one.

**Comment by thirtiseven** [comment]
> I am remembering more now. Converting a double to a decimal value has problems because they do it by going from a double to a string to a decimal. This is inherent in how scala does it in their BigDecimal class, and it is even a bit of magic with an implicit method that just makes it happen behind the scenes. But going from a Double to a String we cannot match what java does. It is not standard which is why we have `spark.rapids.sql.castStringToFloat.enabled`, which is off by default. Now I really want to understand what would happen if this optimization is disabled and what the result really would be. Is Spark right and we are wrong, or is Spark wrong and we are right?

Since we have an _almost match_ float to string kernel in [jni](https://github.com/NVIDIA/spark-rapids-jni/blob/branch-24.06/src/main/cpp/src/cast_float_to_string.cu), does that means we can also _almost match_ float to decimal easily by follow Spark's _float => string => decimal_ way?
