### ISSUE TITLE
Create nightly test for Mortgage GPU demo notebook on GCP Dataproc

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#974]
**Is your feature request related to a problem? Please describe.**
We need to run the [Morgtage GPU demo notebook](https://nvidia.github.io/spark-rapids/docs/demo/GCP/Mortgage-ETL-GPU.ipynb) on GCP Dataproc preview2 as part of our nightly tests.  

**Describe the solution you'd like**

- Run with one master and two nodes with one year of the Mortgage ETL [dataset](http://rapidsai-data.s3-website.us-east-2.amazonaws.com/notebook-mortgage-data/mortgage_2000_1gb.tgz).  
- The driver node should not have a GPU
- Use a script similar to [this one](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-gcp.html#spin-up-a-dataproc-cluster-accelerated-by-gpus) to spin up a cluster on the latest version of GCP dataproc (currently preview-ubuntu18)
- Validate the correctness of the data output
- Run the script as part of the nightly build 
- Run with all versions of CUDA we support using the metadata option.  For example
`--metadata rapids-runtime=SPARK,cuda-version=10.1`
Current supported versions are 10.1, 10.2 and 11.0
- Run with the current released version of the plugin (0.2, cudf 0.15) on Dataproc `preview-ubuntu18`.  Although our plugin is stable, the Dataproc environment is in beta and constantly changing.  When Dataproc stabilizes on a release version for 2.0 we need to update to their new beta version.  
- Run with the latest nightly plugin and cudf snapshot on Dataproc `preview-ubuntu18`.  When Dataproc stabilizes on a release version we need to continue to test our latest nightly plugin and cudf snapshot on the stable version of Dataproc. 

**Describe alternatives you've considered**

**Additional context**

**Comment by wjxiz1992** [comment]
Updates:
We've found the way to launch the notebook and run it remotely by using `gcloud compute` and `ipython -c ...`. I've succeeded run it on a Dataproc cluster. 
I've work with @NvTimLiu to enable it in our Blossom CI.

**Comment by NvTimLiu** [comment]
pipeline created: https://blossom.nvidia.com/sw-gpu-spark-jenkins/view/CSP/job/rapids_Dataproc_Notebook/
Jenkins script uploaded: https://gitlab-master.nvidia.com/nvspark/blossom-jenkins/-/tree/main/notebook
