### ISSUE TITLE
[FEA] Add non-UTC cases in nightly test script

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#9855]
**Is your feature request related to a problem? Please describe.**
Follow up of https://github.com/NVIDIA/spark-rapids/pull/9773

As non-UTC cases could potentially cause OOM in process, and there must be some manual maintenance and commit history to track the changes. Lets,
1. Add an independent func in https://github.com/NVIDIA/spark-rapids/blob/branch-23.12/jenkins/spark-tests.sh to cover the test requirements
2. Add a new `TEST_MODE` at https://github.com/NVIDIA/spark-rapids/blob/branch-23.12/jenkins/spark-tests.sh#L266-L272 and only enable if people/CI want to test against it explicitly (do not enable the as `DEFAULT`)

**Describe the solution you'd like**

**Comment by res-life** [comment]
[PR](https://github.com/NVIDIA/spark-rapids/pull/9885) merged.
After the nightly CI pass, then close this issue.
