### ISSUE TITLE
[FEA] Replace RowEncoder with ExpressionEncoder for Delta Lake 

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#9883]
**Is your feature request related to a problem? Please describe.**
In Spark 3.5.0 `RowEncoder`'s apply method has been moved to `ExpressionEncoder`

**Describe the solution you'd like**
We use this method in the Delta Lake module and we should switch to the new method in versions of Databricks greater than 13.3

**Additional context**
https://github.com/apache/spark/commit/071feabbd4#diff-bcb03e1769f63da7a6ca53a3bb9c9d9f648d860520fa8de95b680c67d8c89fd9

**Comment by mattahrens** [comment]
This will be fixed with compiler failures when supporting Delta Lake on Spark 3.5 which needs Delta Lake 3.0.
