### ISSUE TITLE
[DOC] A little confuse that we recommend a spark config but it does not exist in spark official doc

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#9901]
In spark-rapids [doc](https://nvidia.github.io/spark-rapids/docs/additional-functionality/advanced_configs.html) we said spark.rapids.sql.concurrentWriterPartitionFlushSize need to work with a spark config spark.sql.maxConcurrentOutputFileWriters, but I cannot find this in spark [doc](https://spark.apache.org/docs/latest/configuration.html), it is a little odd that we recommend a spark config that does not exist in spark official doc.

**Comment by nvliyuan** [comment]
CC @res-life

**Comment by revans2** [comment]
The config is an internal config to Spark.

https://github.com/apache/spark/blob/9bb358b51e30b5041c0cd20e27cf995aca5ed4c7/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala#L4308-L4314

Yes it is a little odd that we reference it. But that is in the advanced config section of our docs also.
