### ISSUE TITLE
[Audit][SPARK-45060] Fix an internal error from `to_char()`on `NULL` format

### ISSUE THREAD

**Issue by cindyyuanjiang** [NVIDIA/spark-rapids#9919]
Spark fixed an error in `to_char()`on `NULL` format. The changes checks the `format` argument is not a NULL in `ToCharacterBuilder`. And if it is, throw an `AnalysisException` with new error class `INVALID_PARAMETER_VALUE.NULL`.

https://github.com/apache/spark/commit/d03ebced0ef

**Comment by mattahrens** [comment]
Does not impact the plugin
