### ISSUE TITLE
[Audit][SPARK-45033] Support maps by parameterized `sql()`

### ISSUE THREAD

**Issue by cindyyuanjiang** [NVIDIA/spark-rapids#9920]
Spark added support for allowing more column expressions as parameters of `sql()` to construct maps/array: `CreateArray`, `MapFromArrays`, `CreateMap`, MapFromArrays` and `MapFromEntries`.

https://github.com/apache/spark/commit/416207659aa

**Comment by mattahrens** [comment]
Does not impact our plugin
