### ISSUE TITLE
[FEA] Add config option for the parquet reader input read limit.

### ISSUE THREAD

**Issue by nvdbaranec** [NVIDIA/spark-rapids#9926]
We need to make sure the `pass_read_limit` parameter of the parquet chunked reader is a configurable option for the plugin.  The sub-rowgroup PR is not yet merged but the parameter is already exposed in cudf.

https://github.com/rapidsai/cudf/blob/c8074b5176a74630101c78c43c24b66141352b24/cpp/include/cudf/io/parquet.hpp#L466

**Comment by revans2** [comment]
This was closed by https://github.com/NVIDIA/spark-rapids/pull/9991
