### ISSUE TITLE
[FEA] Support to_date with non-UTC timezones without DST

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#9927]
I wish we can support to_date with CST(China Time Zone) support.

```
SELECT to_date(col) from xxx;
```

**Comment by NVnavkumar** [comment]
@nvliyuan What is the specific string format needed for `to_date` needed here?

**Comment by nvliyuan** [comment]
Confirmed in customers query, they only use default format.(yyyy-MM-dd)

**Comment by winningsix** [comment]
Thanks. Then it's on the list of our supported formats. It's depending on https://github.com/NVIDIA/spark-rapids/issues/9997 @razajafri 
```
'yyyy-MM-dd', 'yyyy-MM', 'yyyy/MM/dd', 'yyyy/MM', 'dd/MM/yyyy',  'MM-dd', 'MM/dd', 'dd-MM', 'dd/MM'
```

**Comment by NVnavkumar** [comment]
`to_date(date_str, fmt)` is actually replaced at runtime with `cast(gettimestamp(date_str, fmt, TimestampType, Some(<session timezone>), false) as date)`. So it actually depends on #10035 which might depend on #9997

**Comment by NVnavkumar** [comment]
Ultimately once the dependency issues are completed, this is just a verification task.

**Comment by NVnavkumar** [comment]
Basically this requires `GpuGetTimestamp` work with a non-UTC timezone
