### ISSUE TITLE
[BUG] HostColumnVector memory leak at `GpuTimeZoneDB.doLoadData`

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#9971]
**Describe the bug**
 HostColumnVector memory leak on `GpuTimeZoneDB.doLoadData`

**Steps/Code to reproduce bug**
Use the code in: https://github.com/NVIDIA/spark-rapids/pull/9814

vi integration_tests/run_pyspark_from_build.sh
--driver-java-options "$driverJavaOpts -Dai.rapids.refcount.debug=true"

export DATAGEN_SEED=1701843612
export TZ=Iran
export TEST_PARALLEL=1
clear && ./integration_tests/run_pyspark_from_build.sh -s -k test_from_unixtime

```
../../src/main/python/date_time_test.py::test_from_unixtime[Long-yyyy-MM][DATAGEN_SEED=1701843612, INJECT_OOM] ### CPU RUN ###
### GPU RUN ###
23/12/06 10:14:33 ERROR HostColumnVector: A HOST COLUMN VECTOR WAS LEAKED (ID: 109)
23/12/06 10:14:33 WARN GpuOverrides: 
  ! <RDDScanExec> cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.execution.RDDScanExec
    @Expression <AttributeReference> a#12L could run on GPU

23/12/06 10:14:33 ERROR MemoryCleaner: Leaked vector (ID: 109): 2023-12-06 10:14:33.0387 IRST: INC
java.lang.Thread.getStackTrace(Thread.java:1564)
ai.rapids.cudf.MemoryCleaner$RefCountDebugItem.<init>(MemoryCleaner.java:336)
ai.rapids.cudf.MemoryCleaner$Cleaner.addRef(MemoryCleaner.java:90)
ai.rapids.cudf.HostColumnVector.incRefCountInternal(HostColumnVector.java:190)
ai.rapids.cudf.HostColumnVector.<init>(HostColumnVector.java:97)
ai.rapids.cudf.HostColumnVector$ColumnBuilder.build(HostColumnVector.java:987)
ai.rapids.cudf.HostColumnVector.fromLists(HostColumnVector.java:331)
com.nvidia.spark.rapids.jni.GpuTimeZoneDB.doLoadData(GpuTimeZoneDB.java:242)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)

23/12/06 10:14:33 ERROR HostColumnVector: A HOST COLUMN VECTOR WAS LEAKED (ID: 107)
23/12/06 10:14:33 ERROR MemoryCleaner: Leaked vector (ID: 107): 
23/12/06 10:14:33 ERROR HostColumnVector: A HOST COLUMN VECTOR WAS LEAKED (ID: 106)
23/12/06 10:14:33 ERROR MemoryCleaner: Leaked vector (ID: 106): 
23/12/06 10:14:33 ERROR HostColumnVector: A HOST COLUMN VECTOR WAS LEAKED (ID: 105)
23/12/06 10:14:33 ERROR MemoryCleaner: Leaked vector (ID: 105): 
### COLLECT: GPU TOOK 0.15069293975830078 CPU TOOK 0.11223554611206055 ###
PASSED

```

**Expected behavior**

**Environment details (please complete the following information)**
branch-24.02
Spark311

**Additional context**
I saw the call of `GpuTimeZoneDB.shutdown()` in the plugin shutdown,  `GpuTimeZoneDB.shutdown()` uses `zoneIdToTableFuture.isDone()` to decide whether to clear GpuTimeZoneDB cache. Seems `isDone` is not reliable under multiple-threads, we may to do thread synchronization.

**Comment by res-life** [comment]
Maybe this problem is not a big deal since eventually it will be released after the JVM process exits.

**Comment by revans2** [comment]
> Maybe this problem is not a big deal since eventually it will be released after the JVM process exits.

That is mostly correct, but we want to eventually have automated tests that fail the build if we see memory leaks. So at a minimum we want to make sure that we declare this okay by suppressing leak warnings about this particular issues. Or we make it so it is always freed properly.

https://github.com/NVIDIA/spark-rapids-jni/issues/1571

**Comment by res-life** [comment]
Duplicated with https://github.com/NVIDIA/spark-rapids-jni/issues/1571.
And it can be put into next release.
